### ISSUE TITLE
Stuck on "Initializing Vue language features"

### ISSUE THREAD

**Issue by bartoszhalwa** [johnsoncodehk/volar#100]
Version 0.22.13
After opening project taskbar says "Initializing Vue language features" and Intellisense is not working.
In my project I'm using:
- Nuxt (2.14.5)
- @vue/runtime-dom (3.0.5)
- Typescript (4.2.3)

After reversing to version 0.22.11 everything works fine.

**Comment by bartoszhalwa** [comment]
correction, 0.22.12 is working too

**Comment by johnsoncodehk** [comment]
Thanks for your report! I'm not sure this is a performance issue or a bug.

Some informations I need:

- Your OS.
- It's working in 0.22.14?
- Will this problem occur in https://github.com/johnsoncodehk/volar-starter?
- Can you see init progress when you click `Initializing Vue language features`?

**Comment by bartoszhalwa** [comment]
Sorry for not responding. I just checked and it seems to be fixed in 0.22.16.
