### ISSUE TITLE
Request textDocument/formatting failed

### ISSUE THREAD

**Issue by chenguzhen87** [johnsoncodehk/volar#1002]
![image](https://user-images.githubusercontent.com/28331609/156334379-8aab8941-4bf0-44cd-93c0-0705b0aa28db.png)

**Comment by johnsoncodehk** [comment]
Hi @chenguzhen87, could you provide minimal reproduction code in text?

**Comment by iamzzm** [comment]
Get similar err on .vue with pug template:
Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: i is not defined
  Code: -32603 

and there is no such "i" in the file.

**Comment by iamzzm** [comment]
My minimal reproduction code：
1.New File in vscode.
2.Write this:
![tmp](https://github.com/iamzzm/tmp/blob/main/2022-03-04%20220955.png?raw=true)
3.Format by Volar
You shall get:
Request textDocument/formatting failed.
Message: Request textDocument/formatting failed with message: i is not defined
Code: -32603

**Comment by jdheeter** [comment]
I'm also seeing this error, using pug

**Comment by jdheeter** [comment]
I saw this issue was resolved before in vetur
https://github.com/vuejs/vetur/issues/918

**Comment by Helius-web** [comment]
Has this bug been resolved yet? I also met today
