### ISSUE TITLE
vue  template eslint  error

### ISSUE THREAD

**Issue by hearsay316** [johnsoncodehk/volar#1006]
![mmexport1646319139933](https://user-images.githubusercontent.com/10139810/156589304-c24bc87b-8d10-40cc-b5c5-12ee34d0423e.jpg)
   Index and src  field assignment display type error，How can I fix this problem?

**Comment by xiaoxiangmoe** [comment]
If you use vue 3. Just use `v.name!` and `v.meta!.title`.
