### ISSUE TITLE
custom component with self defined change event  show params type error, this is a error.

### ISSUE THREAD

**Issue by WormGirl** [johnsoncodehk/volar#1007]
![image](https://user-images.githubusercontent.com/16078260/156713661-7b9fbf99-b080-4ceb-965e-132098d29196.png)

actruely this event has two params, but  eslint get one params. this is a error.

**Comment by johnsoncodehk** [comment]
Duplicate of #1001

**Comment by WormGirl** [comment]
This problem appeared again at volar  version `0.34.3`
