### ISSUE TITLE
Vue langugage server does not handle objects in bound :style tag. 

### ISSUE THREAD

**Issue by redsuperbat** [johnsoncodehk/volar#101]
In my template i am conditionally applying styles with the object syntax. Even though the style is correct the language server is complaining. See screenshot below. 

![Screenshot from 2021-03-16 12-13-31](https://user-images.githubusercontent.com/44667637/111300205-1bb12800-8651-11eb-9932-903eb3456104.png)

Full error message:
`
Type '{ 'stroke-width': string; stroke: string; }' is not assignable to type 'string | CSSProperties | undefined'.
`

**Comment by johnsoncodehk** [comment]
Duplicate of #30

Please try change `'stroke-width'` to `strokeWidth`.

**Comment by johnsoncodehk** [comment]
Duplicate of #30

**Comment by redsuperbat** [comment]
That fixes the issue. 
Thanks
