### ISSUE TITLE
v-for typing error when used with named slot

### ISSUE THREAD

**Issue by Shayan-To** [johnsoncodehk/volar#1010]
This template code always gives me an error on the first line:

```
<template v-for="abc in ['str1', 'str2']">
    <slot :name="abc" />
</template>
```

Error message: `'abc' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Comment by johnsoncodehk** [comment]
Hi @Shayan-To, I can't reproduce this problem, please reproduce complete reproducible vue code.

**Comment by Shayan-To** [comment]
@johnsoncodehk 
I managed to create a minimal repro: https://gist.github.com/Shayan-To/0e258ea107942c74123ae53966179cb9

**Comment by johnsoncodehk** [comment]
Duplicate of #1392
