### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by pisandelli** [johnsoncodehk/volar#1012]
Hello guys! I have a small issue. It's quite annoying, but it does not take the bright of Volar! :smile: 

Every time I try to type an address in `src` attribute from a `<style>` three error raises: `Request textDocument/codeAction failed.`, `Request textDocument/completion failed` and `Request textDocument/hover failed`
First it seemed to be random... but it's not. I just realize that it happens in a certain condition.

If I use any one of these formats, the error does not appear `<style src='.....'>` or `<style src='.....' lang="stylus">`  
But if I try using scoped styles `<style src='.....' lang="stylus" scoped>`, the error is thrown.  

The moment I start typing the **single quote**, the error `textDocument/completion failed` is thrown and then the `textDocument/codeAction failed` followed by the `Request textDocument/hover failed` witch keeps appearing when I move the mouse through the screen. Using double quotes seems not to trigger the error.

To stop this behavior I have to close VSCode and reopen the file (and do not touch src with single quotes again. :sweat_smile: ).

![volar](https://user-images.githubusercontent.com/1986634/157085366-8fdf7224-f62f-4ac2-b61a-246ead61bc56.gif)

Here is the output

```
[Error - 2:25:16 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
[Error - 2:25:16 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
[Error - 2:25:16 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
[Error - 2:25:16 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
(node:37610) UnhandledPromiseRejectionWarning: Error: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
    at Object.create (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:48953:17)
    at shiftRange2 (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94841:17)
    at pathToReplaceRange2 (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94800:20)
    at PathCompletionParticipant3.<anonymous> (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94982:32)
    at step (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94939:23)
    at Object.next (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94886:18)
    at /home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94872:71
    at new Promise (<anonymous>)
    at __awaiter5 (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94854:14)
    at PathCompletionParticipant3.computeCompletions (/home/pisandelli/.vscode/extensions/johnsoncodehk.volar-0.32.1/out/node/server.js:94962:16)
(Use `code --trace-warnings ...` to show where the warning was created)
(node:37610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:37610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:25:49 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
[Error - 2:25:50 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
```

**Comment by johnsoncodehk** [comment]
Thanks to found this out!

**Comment by pisandelli** [comment]
Glad to help!

Em seg., 7 de mar. de 2022 às 14:48, Johnson Chu ***@***.***>
escreveu:

**Comment by zardoy** [comment]
I would highly appreciate if it wasn't so noisy. I think one error notification that something went wrong is enough.

**Comment by Joeycz** [comment]
got the same issue

**Comment by Boundless666** [comment]
> 

me too

**Comment by pisandelli** [comment]
@johnsoncodehk I can't reproduce either. I'm using the latest v0.34.7. It seems the problem was somehow solved. Great! :smiley: 

Thanks for your patience and effort!
Cheers

**Comment by sebaguse** [comment]
I still have this issue with `v0.34.16`

![image](https://user-images.githubusercontent.com/53968879/170698545-70d00c82-9e1c-4a3b-ba68-d5d86af3b6fa.png)

**Comment by kingyue737** [comment]
I also meet this issue in v0.34.16

![image](https://user-images.githubusercontent.com/40021217/170822331-1c2fddd1-4130-4b70-8b64-a0475bca44be.png)

**Comment by yaronveg** [comment]
Just got it, on v0.040.6

![image](https://user-images.githubusercontent.com/64664467/188326582-96f165f6-2238-4be5-ae3d-73d916de68f4.png)
![image](https://user-images.githubusercontent.com/64664467/188326597-fb789457-655c-4d33-a141-3286fb584887.png)
