### ISSUE TITLE
Autocomplete Imports and Imported Modules (Bootstrap) in SFC

### ISSUE THREAD

**Issue by st11x** [johnsoncodehk/volar#1015]
Hi,

Inside a Vue file when I import anything from Bootstrap, it doesn't show me the modules available as in this screenshot.

![image](https://user-images.githubusercontent.com/7398499/157272163-22a2f51b-1459-409d-8bb6-06e2e00321c4.png)

if I mouse over the three dots under 'bootstrap', I see this

![image](https://user-images.githubusercontent.com/7398499/157272536-d5bd85cc-37eb-4e40-8b28-f38c3c509a60.png)

The same works in a JS file in the project

![image](https://user-images.githubusercontent.com/7398499/157272308-f6dac6fa-acb9-43db-9819-a87737a98ec7.png)

Because of this, autocomplete like this is also not working

![image](https://user-images.githubusercontent.com/7398499/157272951-f42d9de4-166e-49f8-9bdb-731a9f5e7ade.png)

Do I need to update a config in the plugin for it to work as intended? 

Thanks
  Matt

**Comment by johnsoncodehk** [comment]
I have no use `bootstrap`, I think maybe install https://www.npmjs.com/package/@types/bootstrap can helps.
