### ISSUE TITLE
[Bug]torefs are not supported

### ISSUE THREAD

**Issue by DJReact** [johnsoncodehk/volar#1018]
hi,
![image](https://user-images.githubusercontent.com/9939801/157360441-f4ab5136-1ca2-4020-afef-b4648d2c9b43.png)
![image](https://user-images.githubusercontent.com/9939801/157360497-d2af6528-32e2-44e6-bea5-b00c28a50303.png)
![image](https://user-images.githubusercontent.com/9939801/157360555-a4cb2580-5e47-40ad-b581-94789b359c20.png)
need support
Thanks
Matt

**Comment by DJReact** [comment]
return {
      ...toRefs(state),
      buyStoreInfo,
    };
function is also not supported. BTY

**Comment by johnsoncodehk** [comment]
I tried in below code and it's works for me, please provide repro case.

```vue
<template>
  {{ foo }}
  {{ count }}
</template>

<script lang="ts">
import { defineComponent, reactive, ref, toRefs } from 'vue'

export default defineComponent({
  setup() {
    const data = reactive({ foo: 123 })
    const count = ref(0)
    return {
      ...toRefs(data),
      count,
    };
  },
});
</script>
```
