### ISSUE TITLE
No auto-import on Mac VSCode

### ISSUE THREAD

**Issue by TheDutchCoder** [johnsoncodehk/volar#102]
In our team (all Mac) we can't seem to get auto-import in Vue files working.

If we type `const foo = computed` and hit tab, it won't import `computed` from vue, but will instead auto-complete to `getComputedStyle`. None of vue's methods get imported and we have to do that manually.

It looks like auto-complete does work for people on Windows (I can't test that myself).

Maybe we're missing a setting or something, but this is the default install for Volar and our tsconfig has the proper node resolution and strict mode.

**Comment by johnsoncodehk** [comment]
I can't reproduce the problem, can you try:

1. Can working on *.ts files?
2. Can working on a new project? (Try https://github.com/johnsoncodehk/volar-starter)
3. Can working with Vetur?

**Comment by TheDutchCoder** [comment]
These are my results (I will also dig deeper in the mean time):

Using `.ts` files (my Vite project, **not working**):
![image](https://user-images.githubusercontent.com/1668207/111400251-52ad2b00-869d-11eb-9e4b-a880c3ed8c0e.png)

New project (cloned from your repo, **working**):
![image](https://user-images.githubusercontent.com/1668207/111400425-b2a3d180-869d-11eb-990d-18d8035bbd34.png)

Vetur (my Vite project, **not working**):
![image](https://user-images.githubusercontent.com/1668207/111400557-ef6fc880-869d-11eb-8b69-75c4b105e01e.png)

So far it looks like it may be something related to the configs?

**Comment by johnsoncodehk** [comment]
> So far it looks like it may be something related to the configs?

Yes I think so, can you share a small reproduce to me for check?

**Comment by TheDutchCoder** [comment]
If I copy over the vite config and tsconfig it still doesn't work.
I'm at a complete loss...

**Comment by johnsoncodehk** [comment]
I think it might be related to path finding of node_modules, share full project (no need *.ts and *.vue) to me will be better.

**Comment by TheDutchCoder** [comment]
I can't unfortunately, it's a huge, private repo.
I'll try to figure this out myself then :/

**Comment by TheDutchCoder** [comment]
Oh man I found it!
This particular instance is a vue component library and it doesn't have vue as a dependency as it gets removed from the library anyway. If I make it a dep it works.

**Comment by fvdung** [comment]
@TheDutchCoder I am facing the same problem as you. Please let me know the specific cause and how to fix it!

**Comment by xinller** [comment]
my *.ts is no problem , but in my *.vue file  auto import not working .what happend? (vetur plugins is working, volar not working)

**Comment by johnsoncodehk** [comment]
Please provide a repro case, otherwise I can't survey at all.

**Comment by johnsoncodehk** [comment]
@ami7ava thanks. `[TS Error] Error: Debug Failure. False expression` is upstream TS bug, you can try to use lower TS version from workspace to avoid for now.

**Comment by xwnwho** [comment]
Same problem. Use [https://github.com/johnsoncodehk/volar-starter](https://github.com/johnsoncodehk/volar-starter) as project, in vscode plugin vetur is ok, but volar is not. In *.ts or *.vue file, volar can only auto import defineComponent from '@vue/runtime-core', other like ref, reactive will not work.

**Comment by TheDutchCoder** [comment]
I also have this problem again. If memory serves me well, I reported the issue and it was closed due to it being a TS problem.

I just don't understand how this keeps changing with TS versions.

**Comment by hakula139** [comment]
It seems like using Take Over mode, and switching TypeScript version from VS Code version (4.4.3) to workspace version (4.5.2) at the Command Palette worked for me. Not sure if this solution may help.

**Comment by xwnwho** [comment]
> It seems like using Take Over mode, and switching TypeScript version from VS Code version (4.4.3) to workspace version (4.5.2) at the Command Palette worked for me. Not sure if this solution may help.

It worked! Thank you so much.

**Comment by johnsoncodehk** [comment]
> I just don't understand how this keeps changing with TS versions.

We are downstream so we can't avoid it. :S We can just try to adapt it as fast when it introduces breaking changes.

You can follow @hakula139's suggestion to config fixed TS version in workspace, so VSCode version updating will not change your TS behavior in IDE.

**Comment by TheDutchCoder** [comment]
@johnsoncodehk I understand, thanks, I will try @hakula139's suggestion!

**Comment by johnsoncodehk** [comment]
@TheDutchCoder I think it just because volar extension have not active yet, you need to open any *.vue script to trigger volar active.
