### ISSUE TITLE
[vue-tsc & vscode volar] wrong function ref "el" param type gets evaluated as type `any`

### ISSUE THREAD

**Issue by D4RKAR117** [johnsoncodehk/volar#1032]
Hello currently, volar with takeover mode in vscode and vue-tsc evals [template refs](https://vuejs.org/guide/essentials/template-refs.html#function-refs) functions refs aka `:ref` callback, has the same behavior described in the issue #473 
![image](https://user-images.githubusercontent.com/23545823/158044873-cc1559a1-83c7-4c62-af94-acd99bce8d5b.png)

Maybe related with [this](https://github.com/vuejs/core/issues/5525) identified issue at @vue/core ? . idk if this can affect at any level the type evaluation of volar

Repro at stack blitz [here](https://stackblitz.com/edit/vitejs-vite-qgyxo9?file=src/App.vue)

Versions in the repro cases: 
- Vue: 3.2.31
- vue-tsc / volar 0.32.1

**Comment by johnsoncodehk** [comment]
Hi @D4RKAR117, this is vue types issue, please forward to vue repo.

```html
<script setup lang="tsx">
import Test from './components/Test.vue';

(<Test ref={el => {}} />); // Parameter 'el' implicitly has an 'any' type.ts(7006)
</script>
```
