### ISSUE TITLE
Request textDocument/formatting failed with message: Void elements do not have end tags "image"

### ISSUE THREAD

**Issue by tianyiw2013** [johnsoncodehk/volar#1033]
# Code
```vue
<template>
    <image></image>
</template>

```
# Output
```text
  Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Void elements do not have end tags "image"
  Code: -32603 
```

# Expect
**Compatible with end tags, don't abort because of end tags.**
Give at most a warning, but don't abort formatting.
Volar should be more tolerant of errors, rather than aborting formatting because of errors.

**Comment by johnsoncodehk** [comment]
Good point. :)
