### ISSUE TITLE
Bug: class error - type is not assignable to __VLS_StyleScopedClasses

### ISSUE THREAD

**Issue by raymer** [johnsoncodehk/volar#1037]
After upgrading to 0.33.0 I am getting this error:

![image](https://user-images.githubusercontent.com/490221/158068057-6c9d8188-ae94-44a5-8061-efe3ba3fd8d9.png)

Did not happen prior to the latest release.

**Comment by johnsoncodehk** [comment]
Also fixed in https://github.com/johnsoncodehk/volar/commit/8cb50ccf4660f1a27364fc898ac78149c99442fd, thanks for the report!

**Comment by raymer** [comment]
Awesome thank you sir!
