### ISSUE TITLE
Emmet suggestions are showed inside tags (including top level)

### ISSUE THREAD

**Issue by zardoy** [johnsoncodehk/volar#1039]
Steps to reproduce:

1. Clone [volar-starter](https://github.com/johnsoncodehk/volar-starter)
2. Open `src/components/HelloWorld.vue` in line `25`
3. Remove `setup` word and type `s`
4. Trigger suggestions

Actual: emmet suggestions are showed

Expected: not showing

![image](https://user-images.githubusercontent.com/46503702/158073060-01943c88-e8ae-4103-9edf-1909fbf484c4.png)

- tested in insiders with clean `settings.json`

Also, I don't remember that in previous version emmet suggestions were showing inside every tag in template and even in interpolations: try to type `div` after `count` in `src\components\HelloWorld.vue:16`

**Comment by number304** [comment]
Yes, in my case it doesn't even show any suggestions. :(

**Comment by zardoy** [comment]
Thank you so much for resolving this! However I wonder is there a test to ensure that the bug won't rise again?

**Comment by johnsoncodehk** [comment]
@zardoy Haven't had time to write tests before, there will be later. (PR is also welcome!)
