### ISSUE TITLE
[BUG] Object in "mustache" syntax causes TS error

### ISSUE THREAD

**Issue by AaronBeaudoin** [johnsoncodehk/volar#1041]
Make a minimal `.vue` file like this:

```vue
<template>
  <div>{{ { "a": 1, "b": 2 }["a"] }}</div>
</template>
```

Note the error:

![image](https://user-images.githubusercontent.com/26592486/158263616-e8a1d406-a085-4a45-807f-d53632e24bd1.png)

Weirdly, you can fix the error by assigning the object to a dummy variable inside the mustache interpolation like so:

```vue
<template>
  <div>{{ a = { "a": 1, "b": 2 }["a"] }}</div>
</template>
```

**Comment by johnsoncodehk** [comment]
Hi @AaronBeaudoin, this is expected limitation, you could use parentheses to wrap it.

```
<template>
  <div>{{ ({ "a": 1, "b": 2 }["a"]) }}</div>
</template>
```
