### ISSUE TITLE
Bug: vim-lsp fails to parse headers sent from volar when using @volar/vue-language-server with `--stdio` flag

### ISSUE THREAD

**Issue by tsukkee** [johnsoncodehk/volar#1043]
For example, when the user don't set `volar.config.js`, volar v0.33.0 or later calls `console.log` for logging. But, when using volar with `--stdio`, texts output from `console.log` also included to messages sent to vim-lsp. Then, it breaks parsing function in vim-lsp and I cannnot use volar... After I replaced `console.log` to `console.warn`, which means the message goes to stderr, both volar and vim-lsp look work fine.
https://github.com/johnsoncodehk/volar/blob/3852ee85c8d7a8e20e0bca084d2b73cf11491f93/packages/vue-language-service/src/languageService.ts#L519

Also, following code could cause same problem.
https://github.com/johnsoncodehk/volar/blob/271cdc7c3ad9f93725b422ce7e4086775b09929b/packages/shared/src/ts.ts#L142

**Comment by johnsoncodehk** [comment]
Thanks for the report! Don't know that logging had big impact. 😅

**Comment by tsukkee** [comment]
@johnsoncodehk If just replacing `console.log` to `console.warn` is good solution for this project, I'll make pull request for this. Does it look good to you? If no, I'll just wait for the fix.
Anyway, I'm very happy since now I could share the problem with you 😄  Thank you!

**Comment by johnsoncodehk** [comment]
Of course, nice to have a PR for this. :)
