### ISSUE TITLE
[BUG] "Cannot find name..." unless empty `<script>` tag is present in `.vue` file?

### ISSUE THREAD

**Issue by AaronBeaudoin** [johnsoncodehk/volar#1051]
**Initial clarification:** When I create my Vue app I do an `app.config.globalProperties.$payload = reactive(...);` to make some server injected data accessible across my application on the client side. I generally treat the data as read only, and use it even sometimes in tiny components with no need for logic outside of the `<template>`.

**Now the bug:** Using the following minimal `test.vue` file:

```vue
<template>
  {{ $payload }}
</template>
```

I get a `Cannot find name '$payload'` TS error.

![image](https://user-images.githubusercontent.com/26592486/158391410-19ac5717-be29-4830-9f7a-6957281ee7d2.png)

Oddly, I can resolve this error by simply adding an empty `<script>` to the file like so:

```vue
<script>
</script>

<template>
  {{ $payload }}
</template>
```

I never got this error when previously using Vetur. I also am not using TypeScript in my project, just JavaScript. Possible solutions I've thought of:

- Always adding an empty `<script>` tag to silence the error. Nasty.
- Somehow telling Volar/TypeScript what `$payload` is, but I don't know how to do this.
- Going back to Vetur (but overall that feels like a downgrade).
- Using `inject("payload")` with an `app.provide("payload", ...)` instead of `app.config.globalProperties`. I'd rather not do this, I know that an argument can be made for better clarity or whatever but in my project it really only adds extra boilerplate code across  many of my components.

What is the solution?

**Comment by xiaoxiangmoe** [comment]
```ts
// file: main.ts

...

app.config.globalProperties.$payload = 1;
declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $payload: number
  }
}
```

**Comment by AaronBeaudoin** [comment]
Hi @xiaoxiangmoe, I haven't used TypeScript before in any of my projects, as I sort of implied above. Would you mind explaining what exactly the code you shared is doing?

**Comment by xiaoxiangmoe** [comment]
This is using [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) in TypeScript.

When I write

```
declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $payload: number
  }
}
```

I registered `$payload` to the global type ComponentCustomProperties.

Volar will read `ComponentCustomProperties` interface in `@vue/runtime-core` and use it in all template type checking.
