### ISSUE TITLE
Support excluding `.vue` files by specifying `exclude` in `tsconfig`

### ISSUE THREAD

**Issue by ahnpnl** [johnsoncodehk/volar#1053]
### Problem

Currently, it is not possible to exclude `.vue` files from `vue-tsc` check by using `exclude` option of `tsconfig`.

### To reproduce

- Clone this repo https://github.com/ahnpnl/volar-starter-vite (branch `master`)
- Install deps with `yarn`
- Open `tsconfig.json` and check there is a `exclude` defined.
- Run `yarn build` and observe a TypeScript error

### Feature request

It would be a lot useful and closer to TypeScript native behavior that excluding files by option `exclude` would exclude files from type checking.

**Comment by ahnpnl** [comment]
Thanks for the information, but I look for a way to exclude specific files

**Comment by johnsoncodehk** [comment]
Hi @ahnpnl, this is expected TS behavior because App.vue is import by main.ts.

**Comment by ahnpnl** [comment]
Does it mean all `.vue` files would be the same? Or only `.vue` files which are imported by `main.ts` cannot be excluded?

**Comment by johnsoncodehk** [comment]
> Or only `.vue` files which are imported by `main.ts` cannot be excluded?

It is.
