### ISSUE TITLE
Go to Definition does not work

### ISSUE THREAD

**Issue by vinogradov** [johnsoncodehk/volar#1054]
Hi,
could anybody please help me with this problem? How to make it work? Proof (vue3):

![screencast 2022-03-16 2 AM-59-58](https://user-images.githubusercontent.com/439939/158489792-106bd07c-c7a5-4f61-b1a9-ab56a77aa02c.gif)

~Thanks,
Vadim

**Comment by johnsoncodehk** [comment]
Hi @vinogradov, you need to wrap components option by `defineComponent` to have language support, but please not that the language support for JS is limited.

**Comment by johnsoncodehk** [comment]
It was supported by https://github.com/johnsoncodehk/volar/commit/a78acac01eb23562d9ce28906a4a185911c57131.
