### ISSUE TITLE
@define-mixin syntax highlighting in VSCode

### ISSUE THREAD

**Issue by Galvo87** [johnsoncodehk/volar#1058]
Hi, I am currently getting visual warning when using @define-mixin rule inside postcss style of Vue3 components.
I have Volar and extensions installed...
Is there any cfg rule to avoid this when developing?

**Comment by johnsoncodehk** [comment]
I planed migrate postcss language support to external language service plugin (#1027), I will point out how to ignore specific warning with language service plugin yourself.

**Comment by johnsoncodehk** [comment]
I tried this code and it look normal, do you other case?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/16279759/164122477-7e7df810-60b2-4bfe-847c-7c7f68276708.png">

```html
<style scoped lang="postcss">
@define-mixin icon $network, $color: blue {
    .icon.is-$(network) {
        color: $color;
        @mixin-content;
    }
    .icon.is-$(network):hover {
        color: white;
        background: $color;
    }
}
</style>
```
