### ISSUE TITLE
The presence of a string of i-xxx-xxx in template raises an error

### ISSUE THREAD

**Issue by xiaojieajie** [johnsoncodehk/volar#1062]
![image](https://user-images.githubusercontent.com/39750199/158730407-5e975aa5-00b3-4c3d-8c34-106265ddf855.png)

![image](https://user-images.githubusercontent.com/39750199/158731887-acb429d9-9d4b-4cd0-8ccc-ed41970eb16c.png)

delete i-xxx-xxx normal

**Comment by xiaojieajie** [comment]
<i  i-xxx="x" /> It would also

**Comment by xiaoxiangmoe** [comment]
Can you provide me a minimal reproduction?

**Comment by xiaojieajie** [comment]
> Can you provide me a minimal reproduction?

sorry，I updated my library version, and it was fine
