### ISSUE TITLE
Volar caused me to have repeated prompts

### ISSUE THREAD

**Issue by xiaojieajie** [johnsoncodehk/volar#1063]
![image](https://user-images.githubusercontent.com/39750199/158749572-86b3164f-99b9-4f06-8959-24e6fde46e93.png)

**Comment by xiaojieajie** [comment]
In js ts file
Vue files do not

**Comment by Cansiny0320** [comment]
I have that problem too.

**Comment by johnsoncodehk** [comment]
Make sure you have `"volar.takeOverMode.enabled": "auto"` instead of `"volar.takeOverMode.enabled": true`.

**Comment by xiaojieajie** [comment]
thx
