### ISSUE TITLE
Detect unknown/undefined prop usage

### ISSUE THREAD

**Issue by IceBlizz6** [johnsoncodehk/volar#1077]
This is a proposal for enhancing vue-tsc

Example:
```
<MyComponent
    :propThatDoesNotExist="42"
/>
```
When running npx vue-tsc --noEmit i want it to detect that propThatDoesNotExist is not presently defined in myComponent.
This could produce a warning or error.

Feature like this currently exists in TS files.
When trying to edit fields that is not defined in some typescript class it will output:
Property 'xxx' does not exist on type 'MyClass'.

This would be very helpful for Vue developers when renaming props or performs refactoring or git rebases as looking through the code manually can be tedious.

**Comment by johnsoncodehk** [comment]
This is intentional behavior as this is often used in css selectors.

I'll explore add a option in vueCompilerOptions to change this behavior.

**Comment by IceBlizz6** [comment]
@johnsoncodehk thanks
would be great to have.
Having to opt in through some configuration is fine.

**Comment by sapphi-red** [comment]
I also think it is great to have this feature.
IMO `data-*` and `aria-*` can be ignored even if it is not used.

**Comment by xiaoxiangmoe** [comment]
> https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking
> Note: If an attribute name is not a valid JS identifier (like a data-* attribute), it is not considered to be an error if it is not found in the element attributes type.

But it seems that vue always treat attribute `data-foo` as `dataFoo`

**Comment by IceBlizz6** [comment]
It may be more appropriate to handle this case by giving a warning rather than an error.
The proposed solution is to add option in vueCompilerOptions so maybe users can select option there for themselves of how severe they want to treat this issue, including the possiblity of disabling the check itself

**Comment by eladcandroid** [comment]
@johnsoncodehk Do you have any plan for adding that?

**Comment by johnsoncodehk** [comment]
In 0.36, custom / unknown attrs types behavior handle responsibility will transfer to developer.

- Expand custom attrs example

```vue
<template>
	<div myprop="a">
</template>
```

```ts
// env.d.ts
declare module '@vue/runtime-dom' {
    interface HTMLAttributes {
        myprop: string
    }
}

export { }
```

- Allow any attrs

```ts
// env.d.ts
declare module '@vue/runtime-dom' {
    interface HTMLAttributes {
        [key: string]: any
    }
}

export { }
```

**Comment by lohchab** [comment]
@johnsoncodehk Thankyou for mentioning that here. Suddenly today my Visual Studio Code started giving 'property does not exist on type' warnings for all the custom attributes starting with 'data-*' like this <h1 data-icon="check">Test</h1> after adding the code in env.d.ts for allow any attrs it solved the issue.

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
      [key: string]: any
  }
}

export { }

**Comment by lohchab** [comment]
@johnsoncodehk Since this change regarding unknown properties. I am also getting this error on a V-Calendar Components v-model value before this it was fine. I am newbie and don't have any idea how I can omit this warning.

![image](https://user-images.githubusercontent.com/6769716/171817132-47982299-7eef-4822-b456-a8c9c88f0275.png)

**Comment by ildan95** [comment]
> I also think it is great to have this feature. IMO `data-*` and `aria-*` can be ignored even if it is not used.
Hello. How to enable ignoring this case?

**Comment by Fuzzyma** [comment]
This change is bonkers! How do volar check where this attribute that I passed on purpose ends up? Does it just "assumes" it is the root element of the template? But even that doesn't work properly. Vue has an attribute fallthrough on purpose and this change makes vue-tsc crash on basically every component where I use attribute fallthrough (which I use A LOT).  

This feature should be opt-in and not opt-out.

How can I disable this?

**Comment by Fuzzyma** [comment]
@johnsoncodehk your solution does not work for components. I cant even pass an id attribute to a component

**Comment by lohchab** [comment]
@Fuzzyma His solution has worked for me and now I am able to add any properties and Visual Studio Code dont show up any warnings for them just like earlier.

Add this to your env.d.ts file in your Project Root Folder.
```
// env.d.ts
declare module '@vue/runtime-dom' {
    interface HTMLAttributes {
        [key: string]: any
    }
}

export { }
```

**Comment by Harkonnen13** [comment]
@lohchab I can't make it work on components
![image](https://user-images.githubusercontent.com/28978908/171844231-17792df0-02c5-4448-9f2d-0741ab9c1db0.png)

**Comment by Fuzzyma** [comment]
exactly. it might work for html elements but attribute fallthrough for components doesn't work at all

**Comment by lohchab** [comment]
> @lohchab I can't make it work on components ![image](https://user-images.githubusercontent.com/28978908/171844231-17792df0-02c5-4448-9f2d-0741ab9c1db0.png)
> 
> LIke on native components it works fine, but what about component attributes? I have VInput component which is just a wrapper around native input. SO i have to describe ALL native attributes in props to apply them?

I got you. Yes, you are right I can confirm its is not working. Its only working for HTML Elements.

For a temporary workaround till the time there's a no solution to this my recommendation is that you switch your Volar Extension Version to the '0.35.2' and Restart the Visual Studio Code.

![image](https://user-images.githubusercontent.com/6769716/171846540-71c04dec-f33a-4f23-8e3b-5028297c3a25.png)

**Comment by Fuzzyma** [comment]
Until this is fixed, the proper solution is to revert this feature or hide it behind a flag and release a new version because in the current state it's just plane broken

**Comment by johnsoncodehk** [comment]
> @lohchab I can't make it work on components ![image](https://user-images.githubusercontent.com/28978908/171844231-17792df0-02c5-4448-9f2d-0741ab9c1db0.png)
> 
> LIke on native elements it works fine, but what about component attributes? I have VInput component which is just a wrapper around native input. SO i have to describe ALL native attributes in props to apply them?

You should use `AllowedComponentProps` interface, please check updated [example code](https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472).

**Comment by lohchab** [comment]
> ```ts
> // env.d.ts
> 
> // for native html elements
> declare module '@vue/runtime-dom' {
>     interface HTMLAttributes {
>         [key: string]: any
>     }
> }
> 
> // for vue components
> declare module '@vue/runtime-core' {
>     interface AllowedComponentProps {
>         [key: string]: any
>     }
> }
> 
> export { }
> ```

Thankyou @johnsoncodehk  I can confirm adding this code has solved the unknown property problems for both HTML and Vue Component Elements. Keep up the good work. We all appreciate what you are doing on Volar!

**Comment by keithbrink** [comment]
I agree that this type of strict linting should be opt-in, fallthrough attributes are a common use case with Vue and the default configuration of Volar should just work with the examples from the Vue docs.

**Comment by henribru** [comment]
This isn't just about fallthrough either, as shown in https://github.com/johnsoncodehk/volar/issues/1383 this is causing errors for many completely standard HTML attributes directly on the elements. It seems unreasonable requiring people to add custom declaration files to avoid that

**Comment by Harkonnen13** [comment]
Is it possible to make an option like mode="strict" to change default behavior? I mean, props existence check looks like an edge case than something default. Because everything that not described in props are custom attributes, that's vue default behavior

**Comment by Harkonnen13** [comment]
So i can't even make pure component wrapper to my button without adding env.d.ts 😄 Because this component don't have props at all 

![image](https://user-images.githubusercontent.com/28978908/171875890-edd620a0-c2d3-4eee-9099-cbc61be34b11.png)

![image](https://user-images.githubusercontent.com/28978908/171876088-67bdcef9-ae25-4c17-9669-d21c8cfbd1b9.png)

**Comment by cawa-93** [comment]
@johnsoncodehk Is it possible specify allowed attributes for specific component? Or only globally for all?

**Comment by cawa-93** [comment]
These changes may make some sense, however. Let's my IDE shows a warning if I use an attribute on a tag that doesn't have one. However, this is only a warning and it does not block the CI/CD.

Volar could introduce a similar, gentle check but only for vue components. However, it is also necessary to be able to describe individually for each component, which STML attributes are valid for it
```vue
<template>
	<div>
		<button v-bind="$attrs"><slot/></button>
	</div>
</template>

<script>
interface AllowedHTMLAttributes extends HTMLButtonAttributes {}
</script>

<script setup>
// ...
</script>
```

**Comment by Fuzzyma** [comment]
Imo this feature would be only useful if volar could analyze which element receives the attributes in the end. And only then, it can perform a check if that attribute is valid on that element. However, this is almost impossible to analyze statically because you can change where your attrs end up as you want.

It doesn't make sense to me to restrict passing attributes to a component because that basically takes away a lot free customizability (look at all attributes you can give to inputs for validation reasons. You don't want that as a prop).

**Comment by danielwaltz** [comment]
FWIW, the fix outlined in the comment above related to updating the `env.d.ts` file is not working in my team's project. Unsure of the exact reasons, but one potential difference is our team is still using Vue 2 /w the composition API, so declaring types on `@vue/runtime-core` (and potentially even `@vue/runtime-dom` may not be working as expected.

Still trying to troubleshoot and find a more concrete reason why it's not working for us, but figured I'd share that in case other Vue 2 users are finding the fix is not working for them too.

**Comment by jzs11** [comment]
> In 0.36, custom / unknown attrs types behavior handle responsibility will transfer to developer.
> 
> * Expand custom attrs example
> 
> ```
> <template>
>     <div myprop="a">
> </template>
> ```
> 
> ```ts
> // env.d.ts
> declare module '@vue/runtime-dom' {
>     interface HTMLAttributes {
>         myprop: string
>     }
> }
> 
> export { }
> ```
> 
> * Allow any attrs
> 
> ```ts
> // env.d.ts
> 
> // for native html elements
> declare module '@vue/runtime-dom' {
>     interface HTMLAttributes {
>         [key: string]: any
>     }
> }
> 
> // for vue components
> declare module '@vue/runtime-core' {
>     interface AllowedComponentProps {
>         [key: string]: any
>     }
> }
> 
> export { }
> ```

Not so great...

**Comment by rffl** [comment]
> In 0.36, custom / unknown attrs types behavior handle responsibility will transfer to developer.
> 
> * Expand custom attrs example
> 
> ```
> <template>
>     <div myprop="a">
> </template>
> ```
> 
> ```ts
> // env.d.ts
> declare module '@vue/runtime-dom' {
>     interface HTMLAttributes {
>         myprop: string
>     }
> }
> 
> export { }
> ```
> 
> * Allow any attrs
> 
> ```ts
> // env.d.ts
> 
> // for native html elements
> declare module '@vue/runtime-dom' {
>     interface HTMLAttributes {
>         [key: string]: any
>     }
> }
> 
> // for vue components
> declare module '@vue/runtime-core' {
>     interface AllowedComponentProps {
>         [key: string]: any
>     }
> }
> 
> export { }
> ```

It didn't work unfortunately as the project that I'm working on at the moment is using pure JavaScript without TypeScript, and the errors always appear.

**Comment by SegaraRai** [comment]
Thanks to this feature, I noticed that the Vuetify property names had been updated and was able to correct them. :)
However, it took some work to resolve the issue. FYI:

- I had to explicitly add `@vue/runtime-core` and `@vue/runtime-dom` to `dependencies` (probably because I am using pnpm)
- The `.d.ts` file needs to be separate from the file defining vite's `ImportMetaEnv` (if exists)

For now, I use the following definition in `env2.d.ts`.

```ts
import '@vue/runtime-core';
import '@vue/runtime-dom';

// for vue components
declare module '@vue/runtime-core' {
  export interface AllowedComponentProps {
    [key: string]: any;
  }
}

// for native html elements
declare module '@vue/runtime-dom' {
  export interface HTMLAttributes {
    // allow any data-* attrs
    [key: `data${string}`]: string;
  }
}

export {};
```

Complex libraries such as Vuetify do not always have all properties defined (especially if they are passed through), and users will end up having to disable the feature completely.
The ideal solution would be for the type definitions of Vuetify components to be updated, but this is not always done quickly.
It seems difficult to use without at least a way to define additional attributes for individual components.

**Comment by johnsoncodehk** [comment]
In v0.36.1 this behavior is control by `vueCompilerOptions.experimentalSuppressUnknownJsxPropertyErrors` and default enabled, if you want report unknown props you need config:

```json
// tsconfig.json
{
  "vueCompilerOptions": {
    "experimentalSuppressUnknownJsxPropertyErrors": false
  }
}
```

If you see how volar hacking JSX types to ignore unknown prop errors you may want to disable it. (This shouldn't be part of volar's control)

https://github.com/johnsoncodehk/volar/blob/104af79387fec40ec3c9e82299f1258f1947673e/packages/vue-typescript/src/typescriptRuntime.ts#L282-L290

**Comment by TheDutchCoder** [comment]
Can you make this disabled by default instead?
I still don't understand what the real point is, as this change breaks totally valid code all over the place for known attributes like all aria attributes.

I'm sure there's good intentions here, but people (especially new users) will have no idea what is going on when their `data-` attributes are throwing errors suddenly.

**Comment by johnsoncodehk** [comment]
@TheDutchCoder Maybe there are some misunderstood, "SuppressUnknownJsxPropertyErrors" mean ignore unknown prop errors, I think you don't want disabled it by default.

**Comment by TheDutchCoder** [comment]
Okay I'll give it a spin later.

Just to clarify: `data-` and `aria-` attributes are not unknown jsx attributes/properties.

So regardless of the setting, these should never throw errors, which was the original issue.

**Comment by Fuzzyma** [comment]
I can confirm that the update fixes all issues.  It is now opt-in as described above

**Comment by lucas-labs** [comment]
As @TheDutchCoder said, `data-*` and `aria-*` are not unknown attributes, specially on "plain" html elements. They are standard W3C recommendations. The following piece of code is valid html and it should not throw an error regardless of the setting:

```xml
<template>
    <input aria-describedby="emailHelp">
    <p id="emailHelp">aria help...</p> 
</template>
```

**Comment by johnsoncodehk** [comment]
> As @TheDutchCoder said, `data-*` and `aria-*` are not unknown attributes, specially on "plain" html elements. They are standard W3C recommendations. The following piece of code is valid html and it should not throw an error regardless of the setting:
> 
> ```
> <template>
>     <input aria-describedby="emailHelp">
>     <p id="emailHelp">aria help...</p> 
> </template>
> ```

Fix by ba2835fdcf233cad92bdd39519c0d723b7dee42e.

**Comment by TheDutchCoder** [comment]
@johnsoncodehk 
I still can't get this to work properly.

If I disable `experimentalSuppressUnknownJsxPropertyErrors` I still get errors thrown for data- and aria- attributes.
If I enable it, invalid attributes don't throw errors at all.

Example:
The `data-test-id` attribute should **not** throw an error, but the `thisisnotvalid` attribute should:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/1668207/172053428-91a1f6c8-e6a4-46c6-a733-6ea8a6eb735e.png">

**Comment by Fuzzyma** [comment]
@TheDutchCoder if you don't have the option set, it's on by default. Which means volar behaves as if this feature wasn't enabled at all (its a feature flag). Nothing else was changed afaik.

**Comment by TheDutchCoder** [comment]
This still doesn't solve anything.

Setting this to `true` means that _unknown_ attributes (e.g. `foo="bar"`) will go unchecked.
Setting this to `false` means that _known_ attributes throw errors (e.g `data-foo` or `aria-disabled`).

**Comment by IceBlizz6** [comment]
I am unable to get this to work with the latest version.
vue-tsc 0.38.3 will report errors of unknown props like expected.
later versions reports no errors, even when it should.
I have tested 0.38.4, 0.38.5, 0.39.4

Can anyone confirm that this feature still works as expected?
if not then i suspect it broke in 0.38.4

**Comment by johnsoncodehk** [comment]
@IceBlizz6 You should use `vueCompilerOptions.strictTemplates`, see https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0384-2022711.
