### ISSUE TITLE
withDefaults eliminate undefined type even when itself assigns it

### ISSUE THREAD

**Issue by IceBlizz6** [johnsoncodehk/volar#1080]
```ts
interface Props {
    field?: number
}

const props = withDefaults(defineProps<Props>(),
    {
        field: undefined,
    }
)
```
![image](https://user-images.githubusercontent.com/38980218/159143190-49abf757-8fa4-49de-be8b-b12730c52a2f.png)

The actual field prop that is generated here:
* is optional
* is of type number

I believe that this behavior is not intended.

I have 2 possible suggestions for a different behavior
1. Prop is marked as optional and should therefore be of type (number | undefined)
2. Prop has undefined default value and should therefore be required

I think either of these approaches are more intuitive than the current one.

**Comment by johnsoncodehk** [comment]
Please report it to https://github.com/vuejs/core.
