### ISSUE TITLE
expand selection broken in 0.33.x version

### ISSUE THREAD

**Issue by kikyous** [johnsoncodehk/volar#1085]
0.33.x:
![Kapture 2022-03-21 at 10 36 27](https://user-images.githubusercontent.com/818616/159198468-731e88b8-6a0c-4fdb-b071-8c2d621d1dce.gif)

0.32.1:
![Kapture 2022-03-21 at 10 39 13](https://user-images.githubusercontent.com/818616/159198596-bbabf90c-880d-40b8-9325-177142da5c49.gif)

**Comment by johnsoncodehk** [comment]
Thanks for the report!
