### ISSUE TITLE
Completion does not work correctly in `{{ ... }}` since v0.33.3

### ISSUE THREAD

**Issue by yaegassy** [johnsoncodehk/volar#1088]
The problem seems to persist in the latest version of `v0.33.5`.

### [NG] v0.33.3

https://user-images.githubusercontent.com/188642/159219871-00a2527d-454f-4fa0-b4bd-7dfb8385b61e.mp4

### [OK] v0.33.2 

https://user-images.githubusercontent.com/188642/159219902-8bab6b1b-21d6-45b0-8044-01368fa1666f.mp4

**Comment by johnsoncodehk** [comment]
Thanks for the report!
