### ISSUE TITLE
An object literal cannot have multiple properties with the same name in strict mode.

### ISSUE THREAD

**Issue by lfhenrl** [johnsoncodehk/volar#109]
Thank you for your amazing work.
I think I've found a bug.
it looks like # 11 but with style attribute
![image](https://user-images.githubusercontent.com/10332372/112153839-035a8380-8be4-11eb-960c-2795daa9cb5a.png)

**Comment by johnsoncodehk** [comment]
Fixed in 0.22.21, thanks for the report!

**Comment by lfhenrl** [comment]
Thanks, The problem is fixed
