### ISSUE TITLE
Add snippets for scaffolding common SFC boilerplate

### ISSUE THREAD

**Issue by aentwist** [johnsoncodehk/volar#1094]
See the [VSCode Snippet Guide](https://code.visualstudio.com/api/language-extensions/snippet-guide) and [the Vetur implementation](https://github.com/vuejs/vetur/blob/master/docs/guide/snippet.md#customizable-scaffold-snippets).

For example, a snippet `vue` that allows an option for TypeScript (default to HTML and Composition API),

```vue
<template>
  
</template>

<script setup lang="ts">

</script>
```

To be honest I know Vetur included the `style` section but personally I would really like to see this excluded by default. The prevalence of component libraries defeats the need in many cases. Although, users who are not using a component library would certainly need it.

**Comment by baojunGit** [comment]
I also hope to have this function，now I only see vueinit can generate template

"
<template lang="">
  <div>
    
  </div>
</template>
<script>
export default {
  
}
</script>
<style lang="">
  
</style>
"

**Comment by johnsoncodehk** [comment]
See https://twitter.com/kromate_24/status/1510054329973198858.

**Comment by aentwist** [comment]
Users adding this themselves was certainly **not** the idea of this issue. Can you discuss a little about why this feature will not be considered, for future searchers? Maybe why it falls outside the scope of this effort?

**Comment by anburocky3** [comment]
> Users adding this themselves was certainly **not** the idea of this issue. Can you discuss a little about why this feature will not be considered, for future searchers? Maybe why it falls outside the scope of this effort?

Yes, I too personally felt like that. This is not a major change and it will definitely improve DX. Doing it yourself is little pain and for this reason, only we are using extensions. 

So having this small collections of snippets would be super helpful.
