### ISSUE TITLE
Duplicate identifier "class"

### ISSUE THREAD

**Issue by victorgarciaesgi** [johnsoncodehk/volar#11]
First off, i'm blown away by your work. Volar is very fast on a big Typescript project. I always had infuriating performance issues with Vetur.

Volar throws error when using valid vue code and `v-bind`

```vue
<span class="font-semibold" :class="{ 'text-text10': anime.isActivated }">Désactiver</span>
```

![image](https://user-images.githubusercontent.com/15092120/97287878-64ed1080-1845-11eb-943b-81d77a6fe148.png)

Workaround for now:

```vue
<span :class="['font-semibold',{ 'text-text10': anime.isActivated }]">Désactiver</span>
```

**Comment by johnsoncodehk** [comment]
Thanks for your report! It has been fixed in 0.14.4.
