### ISSUE TITLE
v-for directive doesn't work properly in template tag

### ISSUE THREAD

**Issue by Hope410** [johnsoncodehk/volar#110]
This code works well in browser, but volar throws error.

![image](https://user-images.githubusercontent.com/19515610/112157758-93a2c380-8bf8-11eb-9384-5801dfa11c31.png)

**Comment by johnsoncodehk** [comment]
It should be works, please give me a repro to check this problem.

**Comment by Hope410** [comment]
I think it doesn't work becouse of dynamic v-slot directive, could you check it?

![image](https://user-images.githubusercontent.com/19515610/112160373-25abcb80-8bfb-11eb-8073-450b9d9268a0.png)
![image](https://user-images.githubusercontent.com/19515610/112160472-3eb47c80-8bfb-11eb-906a-ed91a226739f.png)

**Comment by johnsoncodehk** [comment]
This is `@vue/compiler-dom` problem, `v-for` not working with dynamic slot, maybe fix by this PR: https://github.com/vuejs/vue-next/pull/3374

But I don't know why working on browser, are you using vue 3?

**Comment by Hope410** [comment]
> But I don't know why working on browser, are you using vue 3?

no, vue 2

**Comment by johnsoncodehk** [comment]
I see, it's makes sense.

If vue 3 fixed this problem I will publish a new version, thanks for the report!

**Comment by johnsoncodehk** [comment]
Reopen because actually vue compiled valid render code, not sure this is design or bug.

**Comment by johnsoncodehk** [comment]
Added a patch in 0.22.26 for now.
