### ISSUE TITLE
feat: add dynamic argument null type check

### ISSUE THREAD

**Issue by reslear** [johnsoncodehk/volar#1100]
https://vuejs.org/guide/essentials/template-syntax.html#dynamic-argument-value-constraints

<img width="561" alt="Screenshot 2022-03-23 at 23 53 50" src="https://user-images.githubusercontent.com/12596485/159793783-e020106e-4fa2-4e78-b483-547b43615037.png">

**Comment by johnsoncodehk** [comment]
This is expected behavior, please use `v-if="enterKey" @[enterKey]...` or `@[enterKey!]...`.
