### ISSUE TITLE
Allow to hide Vite action icon

### ISSUE THREAD

**Issue by g-plane** [johnsoncodehk/volar#1101]
I've noticed that the setting `volar.icon.vite` was removed since https://github.com/johnsoncodehk/volar/commit/4e138d44a9758efe6dc256919a7e78a9de33bc09 . Is it intentional?

It would be better that allows us to hide those icons to keep the editor simple and neat.

**Comment by johnsoncodehk** [comment]
I don't know someone needs to disable it. 😅

I think the go to code feature on preview is very useful for development, is it not suitable for you?

**Comment by g-plane** [comment]
Yes, I always use browsers to develop and never open preview in VS Code, so I disabled this.

**Comment by johnsoncodehk** [comment]
Preview is not the purpose of volar, do you know the go to code feature? https://twitter.com/johnsoncodehk/status/1496978502385422336

**Comment by g-plane** [comment]
While "Go to Code" seems good, but I won't use a embedded WebView to debug and develop. Of course, they're disadvantages of WebView, not Volar itself, but at least it prevents me from using this feature.

**Comment by johnsoncodehk** [comment]
Preview window is created for go to code and component preview features, not for development and debugging. In my experience, go to code is almost a necessary feature to find the code that needs to be modifiy. Then you can close the preview window and continue in browser development.

I want to minimize volar settings so I just wanted to make sure you don't need go to code feature at all in development so still want to hide the icon?

**Comment by johnsoncodehk** [comment]
@fardolieri Of course with authentication I will add this setting, but authentication is no need any more after 0.33.0...

**Comment by g-plane** [comment]
> you don't need go to code feature at all in development

For me, the answer is **yes**.

**Comment by g-plane** [comment]
I agree @fardolieri 's opinion:

> please don't force it on us by removing the option to hide the icon.

An extension for public should be able to be customized to face many users, not just for some parts of people.

**Comment by johnsoncodehk** [comment]
> I agree @fardolieri 's opinion:
> 
> > please don't force it on us by removing the option to hide the icon.
> 
> An extension for public should be able to be customized to face many users, not just for some parts of people.

@fardolieri's opinion is outdated, I think he misunderstood me removing the setting to impose a feature that requires authentication, which I certainly wouldn't do.

I think it's quite the opposite, I think this setting is just for some parts of people. But I will add this setting if someone does need it.

**Comment by g-plane** [comment]
> I think this setting is just for a few users.

I don't disagree this.

But, at least for me, I need that setting, please.

**Comment by fardolieri** [comment]
I would like to hide the vite icon in my editor. I used the setting `"volar.icon.vite": false` before, and I thinks it's a pity, that it is now gone. I would like to have it back.


When I was talking about authentication issues, I meant I had issues with my specific application, because it attempts to redirect to a different page when not being signed in (my own authentication logic). But that's not really the point here.

**Comment by johnsoncodehk** [comment]
@fardolieri Sorry I misunderstood. 😅

Can you change the url on the status bar to enter the login process? If it can't works, as a last resort, you can run `Developer: Toggle Developer Tools` command open dev console to change the login session.

<img width="404" alt="螢幕截圖 2022-03-24 19 15 11" src="https://user-images.githubusercontent.com/16279759/159905241-9e757b79-51a3-4aa3-9643-8c12759b7649.png">

**Comment by fardolieri** [comment]
I really appreciate your willingness to help me right of the bat, and after signing in, your feature does indeed work even with my codebase (nice work!). But I think that is not the point of this thread.

I still think many people would appreciate the opt-out option to hide/show the icon according to their preference.

**Comment by johnsoncodehk** [comment]
@fardolieri Don't worry I'll add it (I just said it :) )
