### ISSUE TITLE
vue-tsc skipLibCheck is not working

### ISSUE THREAD

**Issue by blankzust** [johnsoncodehk/volar#1102]
/Users/shufeng/code/vue3-vite-template/vue3-vite-template/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'

Why vue-tsc is not reading tsconfig.json?

`tsc`execute successfully.

**Comment by blankzust** [comment]
the vue-tsc version is 0.29.8

**Comment by xiaoxiangmoe** [comment]
Can you provide a reproduction demo?

**Comment by blankzust** [comment]
> Can you provide a reproduction demo?

Update Node version to 14 solved my problem.12.18.2 don't support grammar like '?.'Thx
