### ISSUE TITLE
SFC variables useage detect with increment or decrement

### ISSUE THREAD

**Issue by richex-cn** [johnsoncodehk/volar#1103]
When I using increment or decrement in `template` scope, I got the incorrect variables code hightlight. See video:

<video src="https://user-images.githubusercontent.com/25103518/159911568-e2913112-1648-4935-b27e-e086a538863d.mp4"></video>

**Comment by johnsoncodehk** [comment]
Hi @richex-cn, this is expected behavior, `++` does not count as usage.

<img width="158" alt="螢幕截圖 2022-03-24 20 01 46" src="https://user-images.githubusercontent.com/16279759/159912035-32be3ca3-6bf6-4888-966e-95dfb40830ff.png">

**Comment by richex-cn** [comment]
@johnsoncodehk Thanks, Maybe my understanding of highlight is wrong.
