### ISSUE TITLE
Mac os Volar plug High memory usage（1.5GB）

### ISSUE THREAD

**Issue by heianxiyi** [johnsoncodehk/volar#1104]
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/22736955/160035005-7ac78d06-35cc-4240-ab8d-6ca0abbc9730.png">

help

**Comment by johnsoncodehk** [comment]
Please use low power mode, see #531.

**Comment by johnsoncodehk** [comment]
Duplicate of #531

**Comment by heianxiyi** [comment]
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/22736955/160052506-bb3e6761-b779-46e1-9111-dde7c88b6ec0.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/22736955/160052555-7b205665-71f2-4af8-9965-118503423872.png">
help

**Comment by johnsoncodehk** [comment]
Please track #1108.
