### ISSUE TITLE
select elements receive React typings

### ISSUE THREAD

**Issue by TheDutchCoder** [johnsoncodehk/volar#111]
We're running into a very strange issue where the use of a `select` element will, for some reason, try to infer types from React:
![image](https://user-images.githubusercontent.com/1668207/112233083-213ddd80-8c10-11eb-99bb-d6834d7a2ca0.png)

I haven;'t been able to reproduce this elsewhere. Only seems to occur when using `select`

**Comment by TheDutchCoder** [comment]
Oh this also happens for regular inputs:
![image](https://user-images.githubusercontent.com/1668207/112233286-8abdec00-8c10-11eb-874e-138651968066.png)

**Comment by johnsoncodehk** [comment]
It seem your project included react types, please disable `volar.tsPlugin` and check this code types on *.ts.

```ts
declare let select: JSX.IntrinsicElements['select']; // should be ElementAttrs<SelectHTMLAttributes>
declare let input: JSX.IntrinsicElements['input']; // should be ElementAttrs<InputHTMLAttributes>
```

**Comment by TheDutchCoder** [comment]
Yeah it's very strange, we don't use React at all, nor are React types installed.
When I follow your instructions I get:
`let select: React.DetailedHTMLProps<React.SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>`

Searching for "react" in the package lock file only turns up a bunch of babel plugins. I'm not sure what dependency leans on that, because I don't use babel myself.

**Comment by TheDutchCoder** [comment]
Our project does use Storybook and their stuff is all React of course. I wonder if that's interfering (though I wouldn't know how).

**Comment by johnsoncodehk** [comment]
Try use include / exclude options in `tsconfig.json` to ignore `JSX.IntrinsicElements` from react library.

You could click `Go to Definition` on `IntrinsicElements` to find the library.

**Comment by TheDutchCoder** [comment]
`tsconfig.json` is already set to ignore `node_modules` and there's two definitions I get:
1. `node_modules/@types/react`
2. `node_modules/@vue/runtime-dom/dist`

Should I explicitly exclude the react types path? Shouldn't that already be done by ignoring `node_modules` all together?

**Comment by johnsoncodehk** [comment]
Sorry i'm not really familiar to `tsconfig.json`, maybe use the `types` option?

Let me know if you find out the correct setup.

**Comment by TheDutchCoder** [comment]
Oh man, I think I've found the issue!
The `tsconfig.json` didn't have `types` specified, so I guess it just uses everything it can find or something.

If I set it to `["node", "jest"]` it works.

nothing to do with Volar, sorry for the distraction!
