### ISSUE TITLE
In css module mode, add vscode warnings when css class no referenced.

### ISSUE THREAD

**Issue by Tzxhy** [johnsoncodehk/volar#1110]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/18610809/160069604-f53fa0cc-1629-4d52-8c24-76d9f8214a83.png">

I think it will be a good tip when a css class is not referenced. Maybe a Volar switch?
Thanks.

**Comment by johnsoncodehk** [comment]
First thanks for the suggestion, but I decided don't support this because I think this warning is a bit radical for `<style>` to me.
