### ISSUE TITLE
Jump definition and onHover in emacs get an old location and information.

### ISSUE THREAD

**Issue by jadestrong** [johnsoncodehk/volar#1113]
First, I didn't reproduce the problem in vscode, but in emacs when I register the `workspace/didChangeWatchedFiles` capability, I found the `goto definition` and `onHover` sometimes get an old information. After disabled the capability, it works as expect.

![output-2022-03-25-21:48:48](https://user-images.githubusercontent.com/18475217/160227944-2d1e2e82-9960-49ee-9303-0f1654ea9905.gif)

Then I did some debugging to check what was done in `onWorkspaceFilesChanged` function. I found that it was caused by the following here. Is the `if` statement here reversed? Or there are other effects that can lead to this problem?
https://github.com/johnsoncodehk/volar/blob/f00336e03717fb3a92b687739eb854d4f1ea4977/packages/vue-language-server/src/project.ts#L171-L176

**Comment by johnsoncodehk** [comment]
Just have a quick look I think `script.version--` is not the reason, it's just force different to `snapshotVersion` for force refetch document text.

Could you debug to check does `documents` provide new content after edit at https://github.com/johnsoncodehk/volar/blob/f00336e03717fb3a92b687739eb854d4f1ea4977/packages/vue-language-server/src/project.ts#L309?

**Comment by jadestrong** [comment]
```
2022-04-05 17:01:05 [24885] [vue-language-server projects.ts onDidChangeContent]
2022-04-05 17:01:05 [24885] [vue-language-server projects.ts onDidChangeContent]
2022-04-05 17:01:06 [24885] [vue-language-server projects.ts onDidChangeWatchedFiles]
2022-04-05 17:01:06 [24885] [languageFeatures onHover]
2022-04-05 17:01:06 [24885] [getValidTextDocument]
2022-04-05 17:01:06 [24885]
is oldDoc: file:///Users/jadestrong/Documents/JadeStrong/volar-starter/src/App.vue.ts
81218be79116cc15849d5a7322d1339ebb5611c12c982bcffff900e3a88d15c5
81218be79116cc15849d5a7322d1339ebb5611c12c982bcffff900e3a88d15c5

2022-04-05 17:01:06 [24885] [typescript-language-service hover.ts] doHover document]:
import { pageBack } from './hooks/useTest';
export default await (async () => {
const pageBack = () => {
}
return (await import('vue')).defineComponent({
setup() {
() => {
{
// @ts-ignore
() => { pageBack };
}
};
return { };
},
});
})();
```
I typed some logs. When I edited the file, the version of the file I got was the same, so it will not go to the `getScriptSnapshot` method in `volar/packages/typescript-language-service/src/index.ts getTextDocument`, and the document content returned here is also old.

**Comment by jadestrong** [comment]
In fact, one line of my code is missing:
![image](https://user-images.githubusercontent.com/18475217/161721261-5c5368b7-9424-4311-919b-3de1c75878a4.png)
```
import { pageBack } from './hooks/useTest';
export default await (async () => {
const pageBack = () => {
}
return (await import('vue')).defineComponent({
setup() {
() => {
{
// @ts-ignore
() => { pageBack };
}
};
return { };
},
});
})();
```

**Comment by yaegassy** [comment]
Hi, @jadestrong, Has this issue been resolved?

**Comment by johnsoncodehk** [comment]
@jadestrong please let me know if still have this issue with v0.40.13 or later version, if so I will reopen issue and try to test with emacs.
