### ISSUE TITLE
typeof [value] !=='undefined' when the template color is hidden

### ISSUE THREAD

**Issue by TuiMao233** [johnsoncodehk/volar#112]
![image](https://user-images.githubusercontent.com/49724027/112270786-16895400-8cb5-11eb-8295-6bb0794b1d4b.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem, please give me a minimal reproduction template code.

**Comment by johnsoncodehk** [comment]
Close because can't reproduce.

**Comment by johnsoncodehk** [comment]
Reproduce in this code.

```vue
<template>
  <div v-if="typeof {} !== 'object'">
    <input
      v-model="pendingFilename"
      spellcheck="false"
      @keyup.enter="doneAddFile"
      @keyup.esc="cancelAddFile"
      @vnodeMounted="focus"
    />
  </div>
</template>
```

Haven't inspected in depth yet, you can wrap `()` to fix for now: `v-if="(typeof ...)"`.

**Comment by johnsoncodehk** [comment]
It should a upstream problem, typeof expression can only end with valid characters, see: https://github.com/microsoft/vscode/blob/08d37a85a3fa415a67783ce339c548159d460ef0/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L3374
