### ISSUE TITLE
stylus not working

### ISSUE THREAD

**Issue by judyzhu10** [johnsoncodehk/volar#1122]
I have downloaded stylus extension. It works well in .stylus file and can complete selectors, properties, values, variables, functions etc.but it doesn't work in .vue file. when I use volar + stylus
volar version: v0.33.10

in .stylus file
<img width="643" alt="wecom-temp-fd925b5f1f0c5c2b79b01017935a9f0b" src="https://user-images.githubusercontent.com/22414761/160559227-2a8cfc89-dd02-42e1-8ea9-591439f20fb1.png">
in .vue file
<img width="361" alt="wecom-temp-75e67465ef88c9fb4836198bec9740b3" src="https://user-images.githubusercontent.com/22414761/160559282-af8bd5e3-2f65-4cc6-8fb1-3d79d8c78490.png">

**Comment by johnsoncodehk** [comment]
We do not have language support for style languages other then css, less and scss, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#notes.

If you want to implement other language support yourself, you can use language service plugin api(#1027).
