### ISSUE TITLE
Please become a verified publisher

### ISSUE THREAD

**Issue by isidorn** [johnsoncodehk/volar#1124]
Hi VS Code pm here 👋 

We are now recommending this extension for vue files 🚀 
It would be fantastic if you verify your publisher. More details about this process can be found here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

Thanks a lot!

**Comment by johnsoncodehk** [comment]
Hi @isidorn, thank you for the update! We will verify it with vuejs.org. :)

**Comment by isidorn** [comment]
@johnsoncodehk yes, that would be fantastic. Thanks a lot 👏

**Comment by johnsoncodehk** [comment]
<img width="525" alt="螢幕截圖 2022-04-23 14 49 57" src="https://user-images.githubusercontent.com/16279759/164883676-e8b89e9c-0275-4688-a956-d3cbb6a46eab.png">

We want move related extensions to a new vue official publisher and change extension id from `volar` to `vue-language-features` at the same time but not releasing new extensions (this will clear all downloads and rating 😅), is this possible?

**Comment by isidorn** [comment]
@johnsoncodehk moving the extension is possible (while preserving downloads). Moving + rename I am not sure.
But the best is to email me inikolic@micorosft.com and vsmarketplace@microsoft.com and we can take it from there. Thanks!

**Comment by yyx990803** [comment]
I have verified https://marketplace.visualstudio.com/manage/publishers/vue and we plan to move the official extensions under this publisher.

**Comment by isidorn** [comment]
Awesome, thanks!

**Comment by johnsoncodehk** [comment]
@isidorn I can't email to you 😅, I got this response in gmail:

The recipient server did not accept our requests to connect. Learn more at [https://support.google.com/mail/answer/7720 [micorosft.com](https://support.google.com/mail/answer/7720%5Bmicorosft.com) [20.53.203.50](http://20.53.203.50/): timed out] [[micorosft.com](http://micorosft.com/) [20.84.181.62](http://20.84.181.62/): timed out] [[micorosft.com](http://micorosft.com/) [20.81.111.85](http://20.81.111.85/): timed out] [[micorosft.com](http://micorosft.com/) [20.103.85.33](http://20.103.85.33/): timed out] [[micorosft.com](http://micorosft.com/) [20.112.52.29](http://20.112.52.29/): timed out]

In the email request, we want to change these 2 extensions ID and move publisher.

- https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar
Old ID: johnsoncodehk.volar
New ID: vue.vue-language-features

- https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-typescript-vue-plugin
Old ID: johnsoncodehk.vscode-typescript-vue-plugin
New ID: vue.typescript-vue-plugin

**Comment by isidorn** [comment]
@johnsoncodehk sorry I had a typo in my email. Can you please try again?
inikolic@microsoft.com and vsmarketplace@microsoft.com

**Comment by abulka** [comment]
A fresh install of volar gives me a warning each time I start up vscode.

```
The 2 extension(s) below, in workspace recommendations have 
issues: johnsoncodehk.volar (not found in marketplace) 
johnsoncodehk.vscode-typescript-vue-plugin (not found in marketplace)
```

Is this due to the publisher change that is going on? I've uninstalled and re-installed volar (and uninstaller vetur) but can't seem to shake this message.

**Comment by johnsoncodehk** [comment]
@abulka See https://github.com/johnsoncodehk/volar/commit/afd4f4ba3a34b939f158b63ac72729aec65f9cb3#commitcomment-72663442.

**Comment by abulka** [comment]
@johnsoncodehk Thanks - changing my `.vscode/extensions.json` with the new name helped. However I have been getting weird volar extension behaviour like 

1) volar extension not participating in settings sync 
2) extension uninstalling itself when I restart vscode.  *<-- most annoying*

I noticed there was a reference to the old name in `~/Library/Application Support/Code/User/settings.json`

```json
    "[vue]": {
        "editor.defaultFormatter": "johnsoncodehk.volar"
    },
```

which I removed, but that didn't help.  Interestingly, when I install Vue Volar, I'm still getting the following message in the vscode extension log, referring to the old johnsoncodehk name:

```
[2022-05-06 16:52:15.667] [exthost] [info] ExtensionService#_doActivateExtension johnsoncodehk.volar, startup: false, activationEvent: 'onLanguage:vue'
```

**Comment by johnsoncodehk** [comment]
@abulka I'll release a new version with new publisher as soon, please keep an eye out for it to fix the problem.

**Comment by lainbo** [comment]
> @abulka我会发布一个新版本的商户，请一起发布通知是否能解决问题。

There is still no solution to this problem, every time I open a Vue3 project I get the prompt "The 1 extension(s) below, in workspace recommendations have issues: johnsoncodehk.volar (not found in marketplace)"

**Comment by lainbo** [comment]
> @lainbo What is your VSCode version? Try uninstalling the currently installed Volar extension and try installing it again. Also, if it is possible to upgrade VSCode, please upgrade and try it.
My VS Code version is 1.67.1, at the time of your reply, I tried to uninstall and reinstall Volar, and also operated the VS Code account to sync immediately, but still did not solve the problem, I guess if I can delete my sync information from the server, this problem may be solved

**Comment by isidorn** [comment]
@lainbo this means that your workspace has a .vscode folder and in it an `extensions.json` file
In that file rename `johnsoncodehk.volar` to `vue.volar`.
Sorry about that!

**Comment by lainbo** [comment]
> @lainbo this means that your workspace has a .vscode folder and in it an `extensions.json` file In that file rename `johnsoncodehk.volar` to `vue.volar`. Sorry about that!

It's great, it solved the problem successfully, thanks a lot!

**Comment by goldyfruit** [comment]
> > @lainbo this means that your workspace has a .vscode folder and in it an `extensions.json` file In that file rename `johnsoncodehk.volar` to `vue.volar`. Sorry about that!
> 
> It's great, it solved the problem successfully, thanks a lot!

Same fix here, `create-vue` needs to be updated to avoid this warning.
