### ISSUE TITLE
Renaming .vue files breaks resolving import paths 

### ISSUE THREAD

**Issue by Bodokh** [johnsoncodehk/volar#1125]
Steps to reproduce issue:

Create new file called "Test.vue":
![Before](https://user-images.githubusercontent.com/8866248/160594492-102b0854-9985-4b52-8319-10005cf55905.PNG)

Rename to "test.vue":
![After](https://user-images.githubusercontent.com/8866248/160594524-2596d09b-7943-4ed1-82f1-b453e8413197.PNG)

The error:
Cannot find module '@/models/user.model' or its corresponding type declarations.ts(2307)

I also reproduced this by creating a file called "default.vue" that worked no problem with the imports, and after renaming it to "Default.vue" it stopped working. It's as if it is impossible to rename files.

I tried restarting the volar server, deleteing the ".vscode"  directory and nothing helped.
In the tsconfig.json and in vite.conte.ts I have correctly configured the mapping for the paths. 
I am able to build and run the app with no issues despite the errors shown in the vscode which leads me to believe the issue is with Volar.

tsconfig:
`{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "strict": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "~shared/*": ["../backend/src/core/models/*"]
    },
    "types": ["vite/client", "vuetify"],
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"],
    "suppressImplicitAnyIndexErrors": true,
    "rootDirs": ["./src"]
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
  "exclude": ["node_modules"]
}
`
vite.config.ts (showing only the relevant part:
I tried this:
alias: { '@': fileURLToPath(new URL("./src", import.meta.url)) }
and also this:
alias: { '@': resolve(__dirname, 'src') }

Both work but not when changing file names.

I also tried deleting the file and creating it again and still it somehow remembers the old name and won't autocomplete the paths unless the filename is as it was initially.

**Comment by Gaaraly** [comment]
maybe problem still exist

**Comment by Gaaraly** [comment]
maybe problem still exist

**Comment by yuntian001** [comment]
Also experiencing this +1 @johnsoncodehk

**Comment by yuntian001** [comment]
这个问题有修复计划么，或者对应的缓存文件夹在哪个位置，让我们临时手动清一下对应的缓存也行。
我尝试清除vs code 的缓存和重置插件都无法解决这个问题。@[johnsoncodehk](https://github.com/johnsoncodehk)

**Comment by freshsnow** [comment]
Just experienced the same issue.

**Comment by AdnanRruka** [comment]
Any fi on this one?

**Comment by Harm-Nullix** [comment]
I have this issue in Webstorm 2023.2 with 1.8.2 & 1.8.8

What works for me is restarting the vue language server. (everytime a file gets added/renamed)

Its not really a fix, but a workaround if you really have to
