### ISSUE TITLE
0.33.9 tries to compile node_modules

### ISSUE THREAD

**Issue by yannxaver** [johnsoncodehk/volar#1126]
```sh
yarn tsc-vue
error TS6504: File '/Users/x/Documents/Apps/y/node_modules/vue-spinner/src/ClipLoader.vue.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?
  The file is in the program because:
    Root file specified for compilation
```

Gone when downgrading to 0.33.7

**Comment by ahnpnl** [comment]
I got the same problem

**Comment by johnsoncodehk** [comment]
I can't reproduce it in https://github.com/johnsoncodehk/volar-starter, could you provide minimal reproduction?

**Comment by ahnpnl** [comment]
I dont run into this issue anymore with **0.34.2** but `"experimentalDisableTemplateSupport": true` no longer works. I didn't see in `CHANGELOG` mentioning about removing `experimentalDisableTemplateSupport`

**Comment by johnsoncodehk** [comment]
@ahnpnl this is a regression, it should be fix in next version.

**Comment by ahnpnl** [comment]
@johnsoncodehk I actually have a similar error but not about `node_modules`. In my case, this similar error happens when `<script>` doesn't have `lang="ts"`. A simple reproduction I have is
```
<template>
    <h1 v-text="testTitle" />
</template>

<script setup>
import { ref } from 'vue';

const testTitle = ref('Test');
</script>
```
