### ISSUE TITLE
--emitDeclarationOnly with type-based declaration is not working when using an interface

### ISSUE THREAD

**Issue by Exotelis** [johnsoncodehk/volar#1127]
Hey,

I tried to export my type declarations with `--emitDeclarationOnly` and was confused that nothing happened. After quite some while I figured out, that the interface is causing the problem.

```typescript
<script setup lang="ts">
import type { Variant } from '@/types/Variant';

interface Props {
  variant: Variant;
}
const props = defineProps<Props>();
</script>
```
However, when using the object directly as generic it works as expected :)

At least, the syntax is valid according to https://vuejs.org/guide/typescript/composition-api.html#typing-component-props

Cheers

**Comment by johnsoncodehk** [comment]
Thanks for the report! Here should have error report but it's missing, you need to move the Props interface to `<script>` tag.

```vue
<script lang="ts">
import type { Variant } from '@/types/Variant';

interface Props {
  variant: Variant;
}
</script>

<script setup lang="ts">
const props = defineProps<Props>();
</script>
```

**Comment by Exotelis** [comment]
Thank you :-)
