### ISSUE TITLE
Not load compilerOptions.plugins in tsconfig.json

### ISSUE THREAD

**Issue by ccqgithub** [johnsoncodehk/volar#1128]
I am use `typescript-plugin-css-modules` to make IntelliSense for css modules.

## Not with volar

What i do with the vscode's ts server:

- Install `typescript-plugin-css-modules`
- Add `"plugins": [{"name": "typescript-plugin-css-modules"}]` to `compilerOptions`
- Use `workspace version` typescript.

All is work right, if i import the css modules file, have auto complete for the available classnames.

## Broken with volar

But if i enable the `TypeScript Vue Plugin` or disable it and use `take over mode`, have no IntelliSense of classnames.

I tried to change volar typescript version to `workspace version`, still doesn't work.

Is it volar's ts server not load the plugins that configured in the tsconfig.json?

**Comment by johnsoncodehk** [comment]
> Is it volar's ts server not load the plugins that configured in the tsconfig.json?

Yes. 👀

**Comment by johnsoncodehk** [comment]
For TS plugin supports, please track #1005.
