### ISSUE TITLE
Syntax highlighting breaks when <template> is on one line.

### ISSUE THREAD

**Issue by killjoy1221** [johnsoncodehk/volar#1129]
Not that I usually keep my template on a single line.

On one line:
![image](https://user-images.githubusercontent.com/3409962/160904446-e58736ed-c371-4b1a-b366-0753d4382c50.png)

Multiple lines:
![image](https://user-images.githubusercontent.com/3409962/160904534-87cc3287-52f4-4242-accd-922346513115.png)

It also works fine if the single-line template is below the script.

**Comment by yaegassy** [comment]
I have checked this issue in my environment and the problem does not reproduce in the latest version. Update the volar extension and give it a try.

<img width="741" alt="volar-0-34-5-issue-1129-1" src="https://user-images.githubusercontent.com/188642/162727079-d8ff7e02-efd2-4291-8eb6-67cd3cae6cde.png">

**Comment by killjoy1221** [comment]
It appears another extension (`wscats.vue`) was hijacking the vue highlighting. I've removed it and it works fine now.
