### ISSUE TITLE
light theme volar icon can not see 

### ISSUE THREAD

**Issue by nshusr** [johnsoncodehk/volar#113]
Light Theme
![image](https://user-images.githubusercontent.com/45023042/112272816-9f08f400-8cb7-11eb-8c8a-8bc21955a8ed.png)

Dark Theme
![image](https://user-images.githubusercontent.com/45023042/112273047-de374500-8cb7-11eb-93c1-2799c43a4262.png)

**Comment by johnsoncodehk** [comment]
Interesting problem :sweat_smile:, thanks for the report.

**Comment by johnsoncodehk** [comment]
It's seem a VSCode issue and fixed in 1.55.0.
