### ISSUE TITLE
Melhorar documentação

### ISSUE THREAD

**Issue by lusacramento** [johnsoncodehk/volar#1133]
Não está claro a documentação. Pra que serve? Como funciona?  Parece interessante a proposta, sou dev júnior, buscando me aprimorar no Vue.

**Comment by VitAndrGuid** [comment]
This is a non issue, its very what this does and there are guides to install and use, use english btw.

**Comment by johnsoncodehk** [comment]
You could see https://vuejs.org/guide/typescript/overview.html#ide-support.
