### ISSUE TITLE
Volar (correctly) detects type errors in templates but Typescript can't.

### ISSUE THREAD

**Issue by earslap** [johnsoncodehk/volar#1135]
Thank you for this _amazing_ project.

There are some cases where I send the wrong value to a component (type is wrong) and Volar detects it immediately and shows it in my IDE (VSCode).

But when I do compile the project, typescript compilation gives no errors (and results in wrong behavior at runtime). I don't yet know why or how this happens. Maybe template compilation casts everything to any or something like that? I assume this is a design limitation with Volar and not a bug.

The problem is: I can see these errors only if I open the file in VSCode. If I make a change elsewhere in the project which breaks a component that is not already open in the IDE, I have no way of noticing the error. Only when I open the file I can see it, because compilation does not give any errors.

So is there a way to make Volar check all files in a project, even the files that are not open?

**Comment by johnsoncodehk** [comment]
You could use `Volar: Verify All Scripts` command on vscode, or use vue-tsc on cli( see https://vuejs.org/guide/typescript/overview.html#overview).

**Comment by earslap** [comment]
Thank you. Hmm, I have a (saved) file that shows red squiggles in the template (it is using a variable not defined in props or setup) if opened in the IDE. But if I close it and run `Verify All Scripts` it still comes up with 0 errors and 0 warnings.

**Comment by yaegassy** [comment]
@earslap Can you post a Screen Shot? Maybe there is a current glitch in "Verify All Scripts" command.

**Comment by yaegassy** [comment]
@earslap `Verify All Scripts` command has been fixed in `v0.34.5`. It should work correctly. Please try it.

**Comment by earslap** [comment]
It works now! Thank you.
