### ISSUE TITLE
Disable automatic quotation marks for attrs

### ISSUE THREAD

**Issue by JTinkers** [johnsoncodehk/volar#1139]
I would like to an option in settings to disable automatic quotation marks - we use `'` but it keeps putting `"` and it just grinds our gears :)

**Comment by yaegassy** [comment]
Duplicate of #840 and #917.

Try it with `HTML: Auto Create Quotes` disabled.

<img width="802" alt="vscode-volar-issue-1139-1" src="https://user-images.githubusercontent.com/188642/161406225-fb9eb03b-464b-45c2-bf13-d66e3fb1f780.png">
