### ISSUE TITLE
TS Syntax warning on valid code

### ISSUE THREAD

**Issue by Stanzilla** [johnsoncodehk/volar#1143]
Hey there, I'm getting TS syntax errors on the following code that is not showing errors when using Vetur:

![image](https://user-images.githubusercontent.com/75278/161646586-74bc6c5f-d64e-4848-9a07-90d113358b05.png)

Any idea what I might be doing wrong?

**Comment by johnsoncodehk** [comment]
Could you provide minimal reproduction code?

**Comment by Stanzilla** [comment]
> Could you provide minimal reproduction code?

https://github.com/WeakAuras/WeakAuras-Companion/blob/main/src/components/LandingPage.vue#L149-L163
