### ISSUE TITLE
emmet.showExpandedAbbreviation doesn't work in style tag

### ISSUE THREAD

**Issue by jiyingzhi** [johnsoncodehk/volar#1145]

**Comment by onurusluca** [comment]
I have the same problem: https://github.com/johnsoncodehk/volar/discussions/1211

**Comment by onurusluca** [comment]
For now anyone with the same problem:

- Just disable Volar
- Install Vetur
- Restart all VsCode instances.
- Add these to your VSCode settings.json:
```
  "emmet.includeLanguages": {
   "vue-html": "html",
   "vue": "html"
    }
```
I had  "vue-html": "html" but it is not enough, had to add both.
