### ISSUE TITLE
files/dirs that start with a dot (.) not be checked on take over mode

### ISSUE THREAD

**Issue by ccqgithub** [johnsoncodehk/volar#1147]
1. open `take over` mode, disable builtin typescript features.

`.ts` file not be checked in the `.vuepress` folder.

2. open builtin typescript features, it is ok.

relative issue for typescript:  [builtin typescript features.](https://github.com/microsoft/TypeScript/issues/13399)

**Comment by johnsoncodehk** [comment]
As a workaround, you can add `.vuepress` to include option in tsconfig for now. See https://github.com/johnsoncodehk/volar/issues/70#issuecomment-782876369.

**Comment by ccqgithub** [comment]
> As a workaround, you can add `.vuepress` to include option in tsconfig for now. See [#70 (comment)](https://github.com/johnsoncodehk/volar/issues/70#issuecomment-782876369).

that work with typescript, but seems not work in take over mode(disable builtin typescript features)

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/07d204f8c90c4778b4037ef5db35edf312397446
