### ISSUE TITLE
vitepress dollar variables like $site not found

### ISSUE THREAD

**Issue by DeFUCC** [johnsoncodehk/volar#115]
I get errors when using `vitepress` built in variables like `$site`, `$themeConfig` and others. Is there a way to tell `volar` that these variables are ok here?

![Screenshot 2021-03-27 at 00 02 48](https://user-images.githubusercontent.com/6184449/112692303-c74b4b00-8e8f-11eb-9585-1e338af5bdcc.png)

**Comment by johnsoncodehk** [comment]
Use `ComponentCustomProperties`, see https://github.com/vuejs/vue-next/blob/9ff70be2b357feff9b9b0157dd209a4730706eb6/packages/runtime-core/src/componentPublicInstance.ts#L53-L57.

**Comment by DeFUCC** [comment]
@johnsoncodehk Thanks for the answer! I've found this declaration in the `theme.d.ts` in the default `vitepress` theme. So it's already there:
 
```
import * as vue from '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface ComponentCustomProperties {
    $frontmatter: any
    $withBase: any
    $site: any
    $localePath: any
    $themeConfig: any
    $siteByRoute: any
  }
}
```
But I still get the variables red in the code...

**Comment by johnsoncodehk** [comment]
@DeFUCC you may need add `vitepress/theme` to `types` option of `tsconfig.json`.

**Comment by DeFUCC** [comment]
@johnsoncodehk Sorry for bothering you, but I still can't make it work...

![Screenshot 2021-03-27 at 12 06 36](https://user-images.githubusercontent.com/6184449/112716006-e4663500-8ef4-11eb-8d3b-22445b0ab7d6.png)

**Comment by johnsoncodehk** [comment]
You don't need `types` option, because `theme.d.ts` is under `include` option.

I tried your `theme.d.ts` and it's works, please provide a repro.
