### ISSUE TITLE
Conditional templates with named slots lose type checking

### ISSUE THREAD

**Issue by jaa134** [johnsoncodehk/volar#1150]
### Issue
Templates that use both conditional rendering logic and `v-slot` lose type awareness on `v-else` code block. The type checking works fine on `v-if` and `v-else-if` code blocks. See reproduction here: 

https://user-images.githubusercontent.com/13410410/162279368-23dcf0a3-e801-416d-ae5b-614910a95dc0.mov

### Versions
VS Code: v1.66.0
Volar VS Code extension: v0.33.10
Typescript: v4.6.3
Vue: v3.2.25

### Reproduction code

```vue
<script
  setup
  lang="ts"
>
  import { ref } from 'vue';
  import ComponentWithSlots from '@/src/foobar';

  const aVariableThatExists = ref(true);
</script>

<template>
  <ComponentWithSlots>
    <template
      #content
      v-if="aVariableThatExists"
    >
      <div>{{ aVariableThatExists }}</div>
    </template>
    <template
      #content
      v-else
    >
      <div>{{ thisVariableDoesNotExist }}</div>
      <div>{{ thisShouldBeUnderlinedInRed }}</div>
    </template>
  </ComponentWithSlots>
</template>
```

### Temporary workaround
Move the conditional logic into the children of a single slotted template. Define an extra set of template tags that the conditional logic can live on:
```vue
<script
  setup
  lang="ts"
>
  import { ref } from 'vue';
  import ComponentWithSlots from '@/src/foobar';

  const aVariableThatExists = ref(true);
</script>

<template>
  <ComponentWithSlots>
    <template
      #content
    >
      <template v-if="aVariableThatExists">
        <div>{{ aVariableThatExists }}</div>
      </template>
      <template v-else>
        <div>{{ thisVariableDoesNotExist }}</div>
      </template>
    </template>
  </ComponentWithSlots>
</template>
```

**Comment by johnsoncodehk** [comment]
Thanks for the report! The second template node seem missing on template AST, you could check it in debug console on template explorer.

https://vue-next-template-explorer.netlify.app/#eyJzcmMiOiIgIDxDb21wb25lbnRXaXRoU2xvdHM+XG4gICAgPHRlbXBsYXRlXG4gICAgICAjY29udGVudFxuICAgICAgdi1pZj1cImFWYXJpYWJsZVRoYXRFeGlzdHNcIlxuICAgID5cbiAgICAgIDxkaXY+e3sgYVZhcmlhYmxlVGhhdEV4aXN0cyB9fTwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlXG4gICAgICAjY29udGVudFxuICAgICAgdi1lbHNlXG4gICAgPlxuICAgICAgPGRpdj57eyB0aGlzVmFyaWFibGVEb2VzTm90RXhpc3QgfX08L2Rpdj5cbiAgICAgIDxkaXY+e3sgdGhpc1Nob3VsZEJlVW5kZXJsaW5lZEluUmVkIH19PC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9Db21wb25lbnRXaXRoU2xvdHM+Iiwib3B0aW9ucyI6eyJvcHRpbWl6ZUltcG9ydHMiOmZhbHNlfX0=

**Comment by jaa134** [comment]
@johnsoncodehk Thanks for the help. Here is a link to the bug filed. https://github.com/vuejs/core/issues/5700
