### ISSUE TITLE
Error "Cannot use JSX unless the '--jsx' flag is provided" in all SFC since 0.34.0

### ISSUE THREAD

**Issue by polmabri** [johnsoncodehk/volar#1153]
I receive the error "Cannot use JSX unless the '--jsx' flag is provided" in all singe file components since i updated the vscode plugin to version 0.34.0. The error is not reproducible in version 0.33.10 and before.

![Screenshot from 2022-04-09 23-37-40](https://user-images.githubusercontent.com/874881/162592409-7c059b46-5266-4c60-8f4f-ccf16f95e217.png)

**Comment by lukadriel7** [comment]
I am also seeing this error, but it doesn't seem to appear on my `create-vue` based project. It is visible on my `quasar/webpack` project though. Using v0.34.1

**Comment by baka-gourd** [comment]
I am also seeing this error, in a quasar project.

**Comment by debagger** [comment]
Me too, quasar project.

**Comment by antfu** [comment]
Adding `"jsx": "preserve"` will bypass the warning, but I guess it's still not the ideal solution.

**Comment by debagger** [comment]
v0.34.0 - same problem

**Comment by holazz** [comment]
This error came to me too :(

**Comment by equt** [comment]
@antfu Also found this _workaround_, but this seems to turn off the type checking for some reasons.

**Comment by johnsoncodehk** [comment]
Template type-checking base on JSX, so `"jsx": "preserve"` is required after 0.34, I will record it in breaking changes.

**Comment by debagger** [comment]
For quasar (in my case quasar/vite) `"jsx": "preserve"` must be setup in `tsconfig.node.json`

**Comment by omar-dulaimi** [comment]
I faced this error after creating a new project with vue cli.

**Comment by rgehrsitz** [comment]
Still an issue for me with a Quasar project after trying both workarounds.  Any other ideas?

**Comment by Jawsingale** [comment]
Issue here with quasar and volar also.

**Comment by vandelpavel** [comment]
@johnsoncodehk Still having the same problem with latest: 0.34.4.
Quasar project.

**Comment by Jawsingale** [comment]
Same :-/

**Comment by johnsoncodehk** [comment]
@vandelpavel the fixed is only for no tsconfig / jsconfig project, and it's not release yet, it will with 0.34.5.

**Comment by yaegassy** [comment]
@vandelpavel @Jawsingale This fix will be reflected in the next version (v0.34.5?).

There may be other fixes or adjustments, so until they are released, please downgrade to a version that is not problematic and use it.

**Comment by sheepa** [comment]
This problems seems to be back.

**Comment by Solintin** [comment]
Currently the problem still persist.

**Comment by ReaganM02** [comment]
> I Solved the issue by adding : `jsx": "preserve` to the jsconfig.json folder. the new content in jsconfig.json looks like this `{ "compilerOptions": { "jsx": "preserve", "baseUrl": ".", "paths": { "~/*": ["./*"], "@/*": ["./*"], "~~/*": ["./*"], "@@/*": ["./*"] } }, "exclude": ["node_modules", ".nuxt", "dist"] } `
> 
> in my nuxt/vue project

Thank you for sharing your solution. Tested and it worked on my learning project using quasar.

**Comment by Solintin** [comment]
OK good..

**Comment by 9QS** [comment]
I have this problem too. I used "jsx": "prevense" and this line fixed it.

**Comment by zachbryant** [comment]
> Adding `"jsx": "preserve"` to `tsconfig.json` will bypass the warning, but I guess it's still not the ideal solution.

This doesn't work for me. Volar just shows different errors

**Comment by smarlhens** [comment]
also stuck using `0.36.1`. unable to bump to greatest version

**Comment by m3hari** [comment]
on `v0.38.2` Quasar project with typescript still have this issue.

**Comment by rogi27** [comment]
Looks like `0.36.1` was latest working version without this error. At least for my project.

**Comment by benjaminv** [comment]
Add a little formatting here. 
This is for Nuxt.js project
```json
{
  "compilerOptions": {
    "jsx": "preserve", 
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"]
    }
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

**Comment by smarlhens** [comment]
version `0.38.9` fixed my issue on my case.

**Comment by MartinX3** [comment]
Now I get the issue `js emit is not support` using `lint-staged`.
Executing the lint task via npm works without this issue.

**Comment by johnsoncodehk** [comment]
`"jsx": "preserve"` is not required any more after v1.0.0-alpha.0, if someone have trouble with `"jsx": "preserve"` you can try update.

**Comment by MartinX3** [comment]
Happens again and again the workaround `"*.vue": "bash -c vue-tsc",` helps.

**Comment by xgqfrms** [comment]
## Maybe this will help for whose use the `npx` command with `--jsx` options

```sh
# ✅ usage
$ npx tsc ./src/index.ts --jsx react 

# ❌ usage
$ npx tsc ./src/index.ts --jsx='react' 

``` 

https://stackoverflow.com/questions/50432556/cannot-use-jsx-unless-the-jsx-flag-is-provided/57637588#57637588

**Comment by arish-me** [comment]
I am having the same issue with Rails and Vite-Rails project:
I have added 
tsconfig.app.json:

`{
  "compilerOptions": {
    "composite": true,
    "baseUrl": "app/javascripts",
    "jsx": "preserve",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    }
  }
}
`

and inside tsconfig.json:

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    }
  ],
  "compilerOptions": {
    "baseUrl": "app/javascripts/*",
    "paths": {
      "@/*": ["./src/*"]
    },
    "target": "ESNext",
    "allowJs": true,
    "module": "ESNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"]
  },
  "include": ["app/javascripts", "jest.setup.ts", "vite.config.ts", "postcss.config.ts"]
}

```

**Comment by praisedare** [comment]
> Adding `"jsx": "preserve"` to `tsconfig.json` will bypass the warning, but I guess it's still not the ideal solution.

For me I also had to do that in the `jsconfig.json` file before the error went away
