### ISSUE TITLE
Slot v-bind broken in v0.34

### ISSUE THREAD

**Issue by Uninen** [johnsoncodehk/volar#1156]
The latest version seems to break slots v-bind (not a single file seems to work with this code, where everything worked fine before) in VSCode.

For example:
```vue
<script setup lang="ts">
import { inject, ref } from 'vue'
import { TableState } from './types'

const state = inject('state') as TableState

const data = ref(state.data.current)
</script>
<template>
  <slot
    v-bind="{
      data,
    }"
  ></slot>
</template>
```

Results in `No value exists in scope for the shorthand property 'data'. Either declare one or provide an initializer.`

I'm seeing this with all of my code using Volar 0.34.2 and VSCode 1.66.1.

These issues are unfortunate as there is no way to downgrade the version after automatic upgrade and installing a specific version seems not to work:

```
~ code --install-extension johnsoncodehk.volar@0.33.12
Installing extensions...
Updating the extension 'johnsoncodehk.volar' to the version 0.33.12
Installing extension 'johnsoncodehk.volar' v0.33.12...
Can't install release version of 'johnsoncodehk.volar' extension because it has no release version.
Failed Installing Extensions: johnsoncodehk.volar
```

**Comment by johnsoncodehk** [comment]
Thanks for the report! You could use `v-bind="{ data: data }"` instead of `v-bind="{ data }"` for now.

**Comment by Uninen** [comment]
Indeed, `v-bind="{ data: data }" ` seems to work 👍  Will need a ton of updates to code but at least there's a workaround. 

Thanks for the swift reply 🙏
