### ISSUE TITLE
eslint  ts error  warning never refresh, even though i has fixed the problem,  i need to run `volar: restart vue server` to remove the error tip.

### ISSUE THREAD

**Issue by WormGirl** [johnsoncodehk/volar#1163]
volar: 0.34.3 , i used the take over mode.
#1007 #1001  this error occured again.

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide repro case.

**Comment by leindfraust** [comment]
Had this error too, pops up randomly when switching between Vue projects. As I have observed, it only affects Vue projects with Typescript. No errors when used in Javascript.

**Comment by WormGirl** [comment]
I still have this problem, but it happens when TS types are passed across files. For example, for component `props`, the parent component passes data to the child component. If the type is wrong, vscode will report an error. Even if I deal with this error later, the error prompt of vscode will not disappear, and the prompt is still the previous error.

**Comment by johnsoncodehk** [comment]
Will be helpful if you can describe reproduce steps on https://github.com/johnsoncodehk/volar-starter.

**Comment by WormGirl** [comment]
@johnsoncodehk  clone this demo  https://github.com/WormGirl/volar-eslint-takeOverMode-cache-bug
1. enable take over mode
2. open `src/views/HomeView.vue`, will find an ts error like below
![image](https://user-images.githubusercontent.com/16078260/164233361-7d116fa6-c534-4f91-bdca-e0bfaf5cd899.png)
3. open  `src/components/HelloWorld.vue` fixed this error by change `msg` type to string.
4. return  `src/views/HomeView.vue`. this error still show.
