### ISSUE TITLE
Cannot find name 'React'

### ISSUE THREAD

**Issue by NT-Sasoli** [johnsoncodehk/volar#1164]
Taro3+Vue3+TS 项目
Volar更新到0.34.x后，.vue文件都有 Cannot find name 'React' 的报错

<img width="1016" alt="截屏2022-04-11 15 15 42" src="https://user-images.githubusercontent.com/25737135/162684432-37311a98-6735-4e34-a1f0-6a8e014fb0ed.png">

**Comment by xiaoxiangmoe** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If not please provide minimal reproduction code.

**Comment by NT-Sasoli** [comment]
> 能否在 https://github.com/johnsoncodehk/volar-starter 中重现此问题？如果没有，请提供最少的复制代码。

我通过 https://nutui.jd.com/#/starttaro 此步骤创建项目，在初始化的项目中，将.vue文件中的 <script> 改为 <script setup lang="ts"> 就可以复现问题
如果一定要提供代码，如下
<template>
  <div>
    1
  </div>
</template>

<script lang="ts"></script>

**Comment by NT-Sasoli** [comment]
> > 能否在 https://github.com/johnsoncodehk/volar-starter 中重现此问题？如果没有，请提供最少的复制代码。
> 
> 我通过 https://nutui.jd.com/#/starttaro 此步骤创建项目，在初始化的项目中，将.vue文件中的 <script> 改为 <script setup lang="ts"> 就可以复现问题 如果一定要提供代码，如下
> 
> ```
> <template>
>   <div>
>     1
>   </div>
> </template>
> 
> <script lang="ts"></script>
> ```

我找到了一种解决报错方法
修改tsconfig.json
```
- "jsx": "react",
+ "jsx": "preserve",
```
但不知道未来是否会对项目产生其他影响

**Comment by Linhieng** [comment]
解决方案：修改 tsconfig.json 配置文件：

1. 设置 `"jsx": "preserve"`
2. 将文件添加到 `"include"` 字段中。比如 `"include": [ "lib/**/*.tsx" ]`
