### ISSUE TITLE
[Regression] `vue-tsc` false positive with `noUnusedLocals: true`

### ISSUE THREAD

**Issue by ahnpnl** [johnsoncodehk/volar#1168]
### Summary

Setting `noUnusedLocals: true` in `tsconfig` made `vue-tsc` produce false positive type check for object destructuring with template accessing via `ref`.

### Reproduce steps

- Check out https://github.com/ahnpnl/volar-starter-vite/tree/bug-no-unused-local
- Install deps with `yarn`
- Open `App.vue` to see the example codes
- Run `yarn type-check` and observe the error
```
src/App.vue:10:7 - error TS6133: 'helloWorldRef' is declared but its value is never read.

10 const { helloWorldRef } = useTestLogic();
```

### Extra information

This is a regression since **0.34.4**

**Comment by ahnpnl** [comment]
@johnsoncodehk this bug is back on 0.40.1, this time it occurs to function binding to event, happens to SFC with script setup

**Comment by johnsoncodehk** [comment]
@ahnpnl I can't reproduce this problem, and the repro seems not exist any more. If you can contribute a test case or provide minimal reproduction it will be helpful.

**Comment by ahnpnl** [comment]
Here is the one https://github.com/ahnpnl/volar-starter-vite/tree/bug/no-unused-option :)

**Comment by johnsoncodehk** [comment]
@ahnpnl Just In case you missed it, you can also update tsconfig to avoid this problem in v0.40.1.

```diff
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
+    "jsx": "preserve",
    "noEmit": true,
    "strict": true,
    "sourceMap": true,
    "allowJs": true,
    "skipLibCheck": true,
    "useDefineForClassFields": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "importsNotUsedAsValues": "error",
    "lib": ["esnext", "dom"],
    "types": ["vite/client"]
  },
-  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx"]
+  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}
```
