### ISSUE TITLE
Language features in templates

### ISSUE THREAD

**Issue by slavarazum** [johnsoncodehk/volar#1170]
Go to reference, find references, autocomplete features and other don't work in templates.

> No definition found for ...

Everything works fine in `script` section.

<details>
<summary>Volar - Language Features Server output, when trying go to component reference</summary>

```log
[Trace - 4:05:39 PM] Sending request 'textDocument/definition - (227)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/razum/Development/code/jet-client/resources/js/Jetstream/ActionSection.vue"
    },
    "position": {
        "line": 6,
        "character": 21
    }
}


[Trace - 4:05:39 PM] Received response 'textDocument/definition - (227)' in 1ms.
Result: []

```

</details>

Template to reproduce - [Laravel Jetstream](https://jetstream.laravel.com/2.x/installation.html)

More easiest way to install with [Laravel Installer](https://laravel.com/docs/8.x/installation#the-laravel-installer) and `--jet` option.

**Comment by johnsoncodehk** [comment]
Please add `"jsx": "preserve"` to project tsconfig if it don't have.

**Comment by slavarazum** [comment]
@johnsoncodehk Thanks! Looks like it works.
Could you please explain how it works? Jetstream doesn't use jsx templates.

**Comment by johnsoncodehk** [comment]
volar support TS for template base on JSX so we need to have this config.

Relate issue: #1153

**Comment by senritsu** [comment]
Still getting a warning on the root `template` tag about enabling `"jsx": "preserve"` although it *is* set in `tsconfig.json`. Likewise it seems that `lib` entries are ignored as well. Is there anything that could lead to Volar (running in takeover mode) not picking up the settings from `tsconfig.json`?
