### ISSUE TITLE
Component tags are always highlighted in red

### ISSUE THREAD

**Issue by MaxIV20** [johnsoncodehk/volar#1172]
Also, the "Go to definition" option does not work for components. Project on vue 3.

![sshot-2](https://user-images.githubusercontent.com/46497890/162794012-7dd5008d-05c4-4029-a088-1bb1af939939.jpg)

**Comment by johnsoncodehk** [comment]
You may missing `"jsx": "preserve"` project's jsconfig, after 0.34.6 you will get a prompt.

<img width="504" alt="螢幕截圖 2022-04-12 21 39 03" src="https://user-images.githubusercontent.com/16279759/162975404-0e5f566e-332c-4ad9-a032-f2a0f79de585.png">

**Comment by tol64** [comment]
@johnsoncodehk, please take a look at this comment: https://github.com/johnsoncodehk/volar/issues/1247#issuecomment-1139797104

Perhaps this information will help to solve this problem.
