### ISSUE TITLE
load volar.config.js failed in d:/***/****

### ISSUE THREAD

**Issue by gyhyfj** [johnsoncodehk/volar#1175]
volar - language feature server ( at vscode output )

vscode version: 
1.66.1
8dfae7a5cd50421d10cd99cb873990460525a898
x64

**Comment by NunoSav** [comment]
Experiencing same issue

**Comment by mariuswg** [comment]
I have the same issue. It seems that @johnsoncodehk has fixed it in the latest commit. 
How long will it take before the fix version is available in VS Code?
