### ISSUE TITLE
CSS Module reference does not work on v0.34.6

### ISSUE THREAD

**Issue by ryuseiabe15** [johnsoncodehk/volar#1178]
After updating Volar to v0.34.6, Volar shows a message "TypeScript intellisense is disabled on template, ..." on `<template>` tag.
According to the message, I changed the tsconfig setting from `"jsx": "react", "jsxFactory": "h"` to `"jsx": "preserve"` and the type of CSS module classes objects has become `any`; to be more precise, CSS reference is not working for CSS modules.
![スクリーンショット 2022-04-13 9 17 55](https://user-images.githubusercontent.com/83741925/163074955-52df857b-7b6e-4d16-8b0f-bbc54dadbb72.png)

**Comment by alleluya-young** [comment]
it seems the same situation in <style scoped>

**Comment by siauderman** [comment]
Having the same problem here. Intellisense not working in template and I have changed jsx to preserve in compilerOptions to no avail.

![bildo](https://user-images.githubusercontent.com/14951259/163662251-e47896d4-ea7a-40d4-9e01-fd5ed522f453.png)

**Comment by ryuseiabe15** [comment]
@johnsoncodehk 
Thank you for the fix. I have confirmed that it works fine on v0.34.7.

**Comment by Jomoflash** [comment]
> Dear @johnsoncodehk & all,
> 
> Still not working on my side. Am I missing something?
> 
> ![image](https://user-images.githubusercontent.com/14140226/164268455-b0b9b953-8d1d-4408-97db-41bfb16ee9d4.png)
> 
> Thanks!

@dxps In your jsconfig.json, put the following:

"vueCompilerOptions": {
"experimentalDisableTemplateSupport": true
}

Instead of "jsx": "preserve". Should make the error disappear.

**Comment by dxps** [comment]
@Jomoflash Thanks, James! :pray: 
Sure, that setting makes it disappear, as also stated in the error description.
I was hoping to have it working instead. But I guess that is part of a future episode. :blush: 
![image](https://user-images.githubusercontent.com/14140226/164387931-761a28d0-782d-4830-afda-3c52496cccb4.png)

**Comment by johnsoncodehk** [comment]
@dxps See https://github.com/johnsoncodehk/volar/issues/1219#issuecomment-1104548432.
