### ISSUE TITLE
Error parsing JavaScript expression: Expecting Unicode escape sequence \uXXXX

### ISSUE THREAD

**Issue by iendeavor** [johnsoncodehk/volar#118]
First, thank you for this powerful extension 🥳 .

I found an error, please check it:

<img width="1552" alt="Screen Shot 2021-03-31 at 8 59 10 AM" src="https://user-images.githubusercontent.com/22850435/113076176-17fcd400-9201-11eb-8244-3e7138bd0a1b.png">

Reproduce steps:
1. Run `yarn create @vitejs/app app`
2. Run `yarn add --dev pug`
3. Replace `App.vue` with the code below.

```html
<template lang="pug">
div(
  :class="[ \
    'text-white', \
    'bg-black', \
  ]"
) Foo
</template>

<style scoped>
.text-white {
  color: white;
}
.bg-black {
  background-color: black;
}
</style>
```

**Comment by johnsoncodehk** [comment]
Thanks for the report! I will check it.

You can do this for now:

```vue
<template lang="pug">
div(
  :class=`[
    'text-white',
    'bg-black',
  ]`
) Foo
</template>
```
