### ISSUE TITLE
Option to disable refactoring

### ISSUE THREAD

**Issue by mjlehrke** [johnsoncodehk/volar#1181]
Please add an option to disable file refactoring. For some reason Volar is asking to refactor JS files, outside of a Vue project, every time I move them. I don't need Volar to refactor them since VSCode will.

As far as I can tell the "Don't ask again" option is just for that individual file. Checking it does nothing.

![Volar](https://user-images.githubusercontent.com/12302343/163086397-c2de6ae4-0f8c-4817-b533-d930ab84206f.PNG)

**Comment by johnsoncodehk** [comment]
> It's really annoying that it keeps asking even after "Don't ask again" checking.

It sound like a VSCode issue? "Don't ask again" should works on VSCode side in my intuition. Extension cannot control this popup behavior.
