### ISSUE TITLE
something is wrong with v0.34.6?

### ISSUE THREAD

**Issue by mollyxfma** [johnsoncodehk/volar#1184]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/102200626/163169749-9df55d13-7036-47da-a23e-949c83b9973e.png">

**Comment by tobidalhof** [comment]
Had some issues with the latest version too and fixed it by updating VS Code

**Comment by luohuidong** [comment]
> Volar stopped working for me, fixed it by updating VS Code

Thanks buddy, it works for me.

**Comment by mollyxfma** [comment]
> Volar stopped working for me, fixed it by updating VS Code

seems works for me too, thanks~

**Comment by Coldsewoo** [comment]
> Volar stopped working for me, fixed it by updating VS Code

for someone who have issue with volar even after update vscode, try upgrade node to version 16.
