### ISSUE TITLE
auto-formatting adds unwanted spacing for tailwind breakpoint classes

### ISSUE THREAD

**Issue by hopkins385** [johnsoncodehk/volar#1185]
Hi, with the latest Volar update `v0.34.6` I'm getting unwanted spacings in the <style> section of my Vue-Files for the tailwind breakpoint-classes. Unfortunetely I had to disable the formatting feature, because after auto-formatting my build crashes.

It seems as if e.g. `sm:px-2` is reformatted to `sm: px-2` (Volar adds a spacing after the `:`) .. same for `md:`

```
<style scoped>
div.col_wrapper_nomb {
   @apply flex flex-col items-center sm:px-2 lg:px-14 md:flex-row mt-10 md:mt-20 md:space-x-20;
}
</style>
```

After saving the file the css gets reformatted (formatOnSave: true) and following error is thrown:

```
The `sm:` class does not exist. If `sm:` is a custom class, make sure it is defined within a `@layer` directive. 

  1 |
  2 | div.col_wrapper_nomb {
> 3 |   @apply flex flex-col items-center sm: px-2 lg:px-14 md:flex-row mt-10 md:mt-20 md:space-x-20;
    |   ^
  4 | }
```

```
The `md:` class does not exist. If `md:` is a custom class, make sure it is defined within a `@layer` directive.
  13 |
  14 | div.left_col {
> 15 |   @apply flex flex-col w-full justify-center items-start text-center md: w-2/5 md:text-left;
     |   ^
  16 | }
```

**Comment by hopkins385** [comment]
`lang=""`  is a workaround for now but comes with other issues.

```
<style lang="" scoped>
div.mydiv {
    @apply md:px-2
}
</style>
```

**Comment by johnsoncodehk** [comment]
This is vscode-css-languageservice formatter issue, you could use https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettier or just use [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).

**Comment by hopkins385** [comment]
I disagree. Below is my project config where I think Volar is causing unwanted spacing in style section of vue-files. 

```
{
    "editor.formatOnSave": true,
    "[vue]": {
        "editor.defaultFormatter": "johnsoncodehk.volar"
    },
    "[javascript]": {
       "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
      },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },   
}
```

Spacings are not added if I change it to:

```
    "[vue]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
```

**Comment by johnsoncodehk** [comment]
Have you try https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettier? You just need to config `languages: ['css', 'scss', 'less'],` for style blocks.

**Comment by hopkins385** [comment]
Jepp, with the prettier package it's working now. It's just confusing because this weired behavior popped up just recently. So either a Volar, a VS Code or a Prettier Update somehow broke things. 

Thanks 4 Support! :)

Closed.

**Comment by johnsoncodehk** [comment]
Css formater changed in 0.34.0, see https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0340.
