### ISSUE TITLE
There are some issues with type hints

### ISSUE THREAD

**Issue by cj0x39e** [johnsoncodehk/volar#1187]
![image](https://user-images.githubusercontent.com/8348553/163297951-c7d4b0d1-0fd4-4e17-bab4-ea9d025e6400.png)

Visual Studio Code: 1.66.2
Volar version: v0.34.6

Earlier versions did not have this problem, eg 0.33.10.

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter, could you provide minimal reproduction?

**Comment by cj0x39e** [comment]
I found the reason, when the value of the `strictNullChecks` option in `typescript.config` is `false`, there will be this prompt.
