### ISSUE TITLE
error with the new version

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#1188]
![image](https://user-images.githubusercontent.com/45350572/163298818-19879215-65a6-4187-a5b7-47651b8ad762.png)
got this error on the new vscode extension version.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by zynth17** [comment]
apparently this happen because of mismatch version between vscode ext and the vue-tsc package
my vscode ext using the latest one and my vue-tsc package using version 33.x

this is still weird tho since this never happend before even if the versiond different

upgrading the vue-tsc to the latest version fix this problem.
