### ISSUE TITLE
show  "No volar.config.js found in ..."  output in new version

### ISSUE THREAD

**Issue by mihayinoviki** [johnsoncodehk/volar#1189]
MacOS 12.3.1 Vue3

**Comment by MurmeltierS** [comment]
Same problem here on Windows with Nuxt 3.

**Comment by MurmeltierS** [comment]
Same here on Windows with Nuxt 3.

**Comment by yaegassy** [comment]
This is a "debug" message that is output when `volar.config.js` is not exists in the project. This is currently a specification.

This is not a fatal message, such as an extension not working properly, so don't worry about it.
