### ISSUE TITLE
Intellisense for props does not work in the template

### ISSUE THREAD

**Issue by HWJ-Code** [johnsoncodehk/volar#1191]
Volar
![image](https://user-images.githubusercontent.com/69111271/163356712-b8c01f1b-6fc9-4d92-82a1-960a70d56ace.png)
Vetur
![image](https://user-images.githubusercontent.com/69111271/163356883-115f7c73-b85b-4a7e-bbcb-694220858491.png)

**Comment by MurmeltierS** [comment]
Also it seems like no components are getting resolved.

**Comment by johnsoncodehk** [comment]
Duplicate of #770
