### ISSUE TITLE
Problem with syntax highlighting for non typescript project

### ISSUE THREAD

**Issue by lukaskleinschmidt** [johnsoncodehk/volar#1192]
I'm having some trouble getting syntax highlighting work for a non typescript project.
Strangely enough the error only occurs when defining props using `defineProps`.

![Animation](https://user-images.githubusercontent.com/10027897/163397471-0e544f06-c82f-4cb0-a289-db8996dc90c2.gif)

vscode: v1.66.2
volor: v0.34.6

**Comment by johnsoncodehk** [comment]
With `lang="ts"` it is working, but with js type calculation is limited.

```js
// test.js

import { defineComponent } from 'vue';

const A = defineComponent({
    setup() {
        return {
            HelloWorld: HelloWorld,
        };
    },
});
const B = defineComponent({
    props: [],
    setup() {
        return {
            HelloWorld: HelloWorld,
        };
    },
});

type A_Keys = keyof InstanceType<typeof A>; // "HelloWorld" | "$" | "$data" | "$props" | "$attrs" | "$refs" | "$slots" | "$root" | "$parent" | "$emit" | "$el" | "$options" | "$forceUpdate" | "$nextTick" | "$watch"
type B_Keys = keyof InstanceType<typeof B>; // string | number | symbol
```

**Comment by sirichart** [comment]
So is there any fix for this? or is there any way to temporarily turn off the red highlighting on the component tag. Thank you!

**Comment by lukaskleinschmidt** [comment]
@sirichart downgrading volar to `0.34.4` worked for me for now.

**Comment by sirichart** [comment]
Ah that's great, thank you for this!

**Comment by vhflat** [comment]
After the publisher was changed to `Vue` I'm not able to downgrade anymore.

**Comment by johnsoncodehk** [comment]
@vhflat You can download history versions in https://marketplace.visualstudio.com/items?itemName=Vue.volar&ssr=false#version-history.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.34.4/vspackage?targetPlatform=darwin-x64

**Comment by itpropro** [comment]
> So is there any fix for this? or is there any way to temporarily turn off the red highlighting on the component tag. Thank you!

Just use `lang="ts"`. It's just for that component and Vue 3 without Typescript is just half the fun ;)
