### ISSUE TITLE
Typescript lerna monorepo - incorrect tsconfig file is used

### ISSUE THREAD

**Issue by OlegRayskiy** [johnsoncodehk/volar#1193]
### Summary
When using volar with lerna monorepo and opening vue files from different sub-packages/projects then it might start using tsconfig from a different sub-package/project.
If you haven't opened any vue files from specific sub-package/project after opening the project in VSCode then Volar will load up correct tsconfig for that sub-package/project. But once you start opening vue files from sub-packages/projects with already loaded tsconfig then the latest loaded tsconfig will be used.

### Setup
Visual Studio code - v1.66.1
Vue Language Features (Volar) - v0.34.6
TypeScript Vue Plugin (Volar) - v0.34.6
Windows 10

### Steps to reproduce
Repro repo - https://github.com/yottaltd/volar-monorepo

1. Open the project in VSCode
1. Enable plugins - Vue Language Features (Volar) and TypeScript Vue Plugin (Volar)
1. In root dir do `npm install` and `npm run init` (this can probably be skipped just doing a lerna init)
1. Close VSCode
1. Reopen project in VSCode
1. Open `projects/ui/src/button/VButton.vue` and in the bottom statusbar you will see that `projects/ui/tsconfig.json` is used once loading is done
![image](https://user-images.githubusercontent.com/41791122/163401563-16bca4a7-0618-4fc0-8a71-c7235b553b84.png)
1. Open `projects/app/src/components/HelloWorld.vue` and in the bottom statusbar you will see that `projects/app/tsconfig.json` is used once loading is done
![image](https://user-images.githubusercontent.com/41791122/163401643-43be92f9-9a06-49bf-aff0-c82af17bcfd7.png)
1. Go back to `VButton.vue` file, statusbar will still be showing that `projects/app/tsconfig.json` is used
![image](https://user-images.githubusercontent.com/41791122/163401768-65604ba4-3f25-4af8-a653-c8309fe9ef88.png)

**Comment by cmcnicholas** [comment]
seeing the same issue
