### ISSUE TITLE
Can not rename symbol in *.ts file and sync to *.vue

### ISSUE THREAD

**Issue by Innei** [johnsoncodehk/volar#1194]
tl;dr;

I want to rename symbol in *.ts file, such as `useThemeConfig` -> `useTheme`, but not rename same time in *.vue file.

https://user-images.githubusercontent.com/41265413/163412283-42cab42d-fc0d-47d6-8666-dd225d230249.mov

**Comment by johnsoncodehk** [comment]
Duplicate of #536
