### ISSUE TITLE
V-slot is broken?

### ISSUE THREAD

**Issue by extrem7** [johnsoncodehk/volar#1195]
I've setup vitesse and made this simple example:

![image](https://user-images.githubusercontent.com/24792876/163434218-d8a1267b-6131-41a7-b6c1-6614b0995fd8.png)
![image](https://user-images.githubusercontent.com/24792876/163434253-62c33887-3291-4f17-8312-19668bd9f4b2.png)

Title type should be displayed as "string", isn't it?

**Comment by johnsoncodehk** [comment]
Typed template slots is not support after 0.34.0 until https://github.com/vuejs/core/pull/2693 done.

See #1108, https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0340.
