### ISSUE TITLE
[Typescript] Global function throwing type error when used in <template>

### ISSUE THREAD

**Issue by nurdism** [johnsoncodehk/volar#1197]
I have a global function defined using 

```ts
declare global {
  declare function test(name: string): string
}
```

When trying to use the function in a template it throws a type error, this was working just fine last week, the only thing that has changed in the last week is the extensions I'm using so I figured this was volar related

```vue
<script lang="ts" setup>
  const data = test('str') // no type errors
</script>

<template>
  <span>{{ test('str') }}</span> <!-- Property 'test' does not exist on type ...  -->
</template>
```

Here is the full type error 
```
[{
	"resource": "[redacted].vue",
	"owner": "_generated_diagnostic_collection_name_#11",
	"code": "2339",
	"severity": 8,
	"message": "Property 'test' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...>): WatchStopHandle; } & ... 4 more ... & ComponentCusto...'.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 28,
	"endLineNumber": 44,
	"endColumn": 33
}]
```

**Comment by nurdism** [comment]
reproduction here: https://github.com/nurdism/volar-1197-reproduction

**Comment by johnsoncodehk** [comment]
You need to use `ComponentCustomProperties`, see https://vuejs.org/api/utility-types.html#componentcustomproperties.

**Comment by nurdism** [comment]
@johnsoncodehk it should pick up globally defined functions, its not a custom property, is a window object. Its a globally available function in any and all context (excluding ssr of course) if a package provides a global typing (like for instance jQuery) it should be picked up and available in the component with out additional typing

**Comment by nurdism** [comment]
wait I see this is a vue specific issue
