### ISSUE TITLE
volar can not recognized Component Label, it will recognized it to a html label

### ISSUE THREAD

**Issue by shengjiong** [johnsoncodehk/volar#1198]
禁用 vetur, 安装 Volar 后。
当 使用 <script lang="ts" setup> 时候 可以识别出本地的业务组件，但无法识别出通过yarn add 安装的组件，会把组件当成一个 html 标签，如图
![image](https://user-images.githubusercontent.com/35161892/163540289-179fe817-c9cb-4df4-b35b-897e1cf2d7d7.png)

**Comment by shengjiong** [comment]
![image](https://user-images.githubusercontent.com/35161892/163537848-28bfecc9-f265-4076-b824-9cffdeda65a5.png)

**Comment by johnsoncodehk** [comment]
Duplicate of #622
