### ISSUE TITLE
[Feature request] Detect missing component import for `vue-tsc`

### ISSUE THREAD

**Issue by ahnpnl** [johnsoncodehk/volar#1203]
### Use case

I have a component like this
```
<template>
  <HelloWorld :msg="message" />
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const message = ref();
</script>
```

Here I use the `HelloWorld` component which is **NOT** registered globally. It would be nice if `vue-tsc` can catch this.

### Alternative solution

Currently I'm using https://eslint.vuejs.org/rules/no-undef-components.html#vue-no-undef-components to catch this error.

**Comment by alfeg** [comment]
Not sure if I read this read this correctly. But this feature is now not working, or maybe there is some configuration needed? @johnsoncodehk

**Comment by so1ve** [comment]
Enable `strictTemplates`
