### ISSUE TITLE
How to provide typing for scoped slot?

### ISSUE THREAD

**Issue by antonreshetov** [johnsoncodehk/volar#1204]
I get an error when I check the typing. I would like to either ensure the correct typing or make an exception in this case. Tried `<!-- @ts-ignore -->` but no luck. 

```
error TS7022: 'deep' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

65         <template #default="{ node, deep }">
                                       ~~~~
Found 1 error.
```

![image](https://user-images.githubusercontent.com/17480987/163661391-8a028f86-5884-4252-bd8c-b9ebb0026c4f.png)

Source https://github.com/massCodeIO/massCode/blob/e9dff1e7739f770d557dc8cea4fcfc2bd131d0cd/src/renderer/components/ui/AppTree/AppTreeNode.vue#L62

**Comment by antonreshetov** [comment]
I found a way out. For type checking to succeed, you must not destructuring the scoped slot and explicitly specify its type. For example: `<template #default="scoped: any">`

**Comment by pleek91** [comment]
I'm curious if there's a better way here. Seems like it should know what the type is

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/core/issues/1359#issuecomment-925251993.
