### ISSUE TITLE
Issues when using `defineProps` function

### ISSUE THREAD

**Issue by izznatsir** [johnsoncodehk/volar#121]
When using `defineProps` function in `<script setup lang='ts'>`, it brokes type intellisense in `template` block. From what I found, it causing three problems:

1. Top level variables exposure type intellisense is broken
2. Built-in `<component>` not accepting any attributes, including intrinsic attributes.
3.  Slot type intellisense is also broken

Reproduction:
https://github.com/izznatsir/define-props-volar-issue

This vue site will render just fine, but the intellisense is broken due to `defineProps` function.

**Comment by johnsoncodehk** [comment]
Fixed in 0.23.2, thanks for your report!

**Comment by izznatsir** [comment]
Wow that fast! Thanks mate!
