### ISSUE TITLE
Type inference in template v-if is working for props but not for events

### ISSUE THREAD

**Issue by jbmaisner** [johnsoncodehk/volar#1216]
When using v-if to infer type, the component props have the good type but not the event listeners, as shown below :

here `service.document` can be either a `DocumentFile` or a `SignableDocumentFile`

**Step 1**
the correct type is inferred from the method `isSignableDocument`

![CleanShot 2022-04-19 at 11 01 18@2x](https://user-images.githubusercontent.com/5312996/164005388-9b8e9765-6742-448b-a131-35f9b7121c0e.png)

**Step 2**
the type is correctly inferred in props

![CleanShot 2022-04-19 at 11 01 43@2x](https://user-images.githubusercontent.com/5312996/164005755-0f345064-12ce-4373-b879-16b2d2745aad.png)

**Step 3**
but in `@click` event listener the type is no more inferred 

![CleanShot 2022-04-19 at 11 01 54@2x](https://user-images.githubusercontent.com/5312996/164005909-8ca0cb89-e566-49cd-805a-6b98a26f4112.png)

**Comment by johnsoncodehk** [comment]
Try this `@click="'signAsync' in service.document && service.document.signAsync()"`, see #146.

**Comment by jbmaisner** [comment]
thanks for the tip
