### ISSUE TITLE
类型不兼容 ts2322

### ISSUE THREAD

**Issue by roronoa-chen** [johnsoncodehk/volar#1218]
![20220420205615](https://user-images.githubusercontent.com/50428336/164235448-304eb167-ab17-4fec-942e-4bd52e08a3dd.png)
![20220420205953](https://user-images.githubusercontent.com/50428336/164236021-14564a47-1d51-45ea-a1f8-568b13e983d7.png)

please，，please help，，

how can I fix it...

咔咔报错😂

**Comment by johnsoncodehk** [comment]
Try `(event.target as any).value.replace` instead of. Please ast typescript question in https://discord.com/channels/325477692906536972/331999220125138944.

**Comment by roronoa-chen** [comment]
> 尝试`(event.target as any).value.replace`代替。请在https://discord.com/channels/325477692906536972/331999220125138944中询问打字稿问题。

Think U very much but how can I fix ‘@input’ tip？ And discord can't be used in China...
