### ISSUE TITLE
What does the vue-tsc "-p" parameter do?

### ISSUE THREAD

**Issue by crobinson-expl** [johnsoncodehk/volar#1220]
In the new project created by `npm init vue@latest` the typecheck npm script uses this: `vue-tsc --noEmit -p tsconfig.vitest.json --composite false`.  I assume this is telling vue-tsc to use that particular tsconfig file, but I wanted to be sure.

**Comment by johnsoncodehk** [comment]
Yes, and vue-tsc args is same with tsc args: https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options

**Comment by CptSpaceToaster** [comment]
Google redirects here... but unambiguous answer I was seeking is unfortunately not in the linked reference, but rather in the output from `npx vue-tsc --help`

Specifically, `-p` is short for `--project`
>  ``` --project, -p  Compile the project given the path to its configuration file, or to a folder with a 'tsconfig.json'.```
