### ISSUE TITLE
Default boolean prop type error

### ISSUE THREAD

**Issue by extrem7** [johnsoncodehk/volar#1224]
According to [fix(runtime-core): ensure declare prop keys are always present](https://github.com/vuejs/core/commit/4fe4de0a49ffc2461b0394e74674af38ff5e2a20) and `vue/no-boolean-default` I declare boolean props like this:
```ts
defineProps<{ prop: boolean }>()
```
The prop is always presented in the props proxy object, but when I use such component without passing boolean prop (I want it to be false) vue-tsc gives me the next error:
 `Property 'prop' is missing in type '{}' but required in type ...`
 
 Making a boolean prop undefinedable(?:) resolve this problem, but the further use of toRefs makes its type `Ref<boolean | undefined> | undefined` 😭 with all resulting problems.
 
 Should vue-tsc react to missing boolean props in this way?

**Comment by johnsoncodehk** [comment]
Try this `withDefaults(defineProps<{ prop?: boolean }>(), { props: false })`.

**Comment by extrem7** [comment]
@johnsoncodehk yes, I know about it. But it triggers [vue/no-boolean-default](https://eslint.vuejs.org/rules/no-boolean-default.html), and it is right because there is no sense to force false here. It'll be present in props and will be false anyway.

**Comment by johnsoncodehk** [comment]
@extrem7 IMO this is `vue/no-boolean-default` issue, it should not reporting if the boolean prop is optional, because undefined and false is different strictly.
