### ISSUE TITLE
Nuxt3 cmd(ctrl) + click on an auto imported component shows the d.ts definition first and source second

### ISSUE THREAD

**Issue by altryne** [johnsoncodehk/volar#1226]
Not sure if Volar can do anything about this, but would be amazing if we could cmd+click and go directly to the source of the component instead of the d.ts. Right now it takes 4 clicks to get to the component itself from cmd+click and it's really slowing down dev. 

P.S - if the component is imported explicitly, cmd+click goes to its source.

![CleanShot 2022-04-22 at 09 09 11](https://user-images.githubusercontent.com/463317/164743287-3652657f-73c2-40a8-adfc-43ed5b0d684e.gif)

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, please track #1245.
