### ISSUE TITLE
Import statement intellisense prepends first typed character to selection

### ISSUE THREAD

**Issue by danielrjames** [johnsoncodehk/volar#1227]
Hi,

To start - I've disabled all my plugins one by one and come to the conclusion that Volar is the cause of this.

When importing modules, consts, etc, when you type the first few letters of what you'd like to import and select a intellisense suggestion from the targeted file, the first character of what was previously typed is prepended to the selection.

Note - this does not happen when you select a snippet.

![image](https://user-images.githubusercontent.com/3918362/164786961-7764d5a7-ea9d-42b8-96c5-d5f7bf3b4e24.png)

![image](https://user-images.githubusercontent.com/3918362/164787046-307e1490-75fa-4484-9ce2-ab7f94917971.png)

This only happens in Vue 3 and Nuxt3 projects. I'm also using take over mode.

I really like the plugin, but this bug is pretty annoying. 😭

**Comment by johnsoncodehk** [comment]
Thanks for the report! But I can't see this problem, can you reproduce it in https://github.com/johnsoncodehk/volar-starter?

**Comment by ziloen** [comment]
I had the same problem
![volar](https://user-images.githubusercontent.com/34268416/165232631-433ab587-4b9d-4986-98c1-76f473830d7b.gif)

**Comment by johnsoncodehk** [comment]
@ziloen Thanks for the repro case!
