### ISSUE TITLE
Resolving custom directive in SFC is partially broken since v0.34.3 and v0.34.4

### ISSUE THREAD

**Issue by lakca** [johnsoncodehk/volar#1228]
From v0.34.3, the argument types of custom directive cannot be resolved (checked).
And from 0.34.4, the problem in [Unused script setup directives #327](#327) ('xxx' is declared but its value is never read.ts(6133)) was started appear again .

**Comment by paya-cz** [comment]
Yep I have v0.34.10 but I get `unused warnings/errors` for directives, no matter if the directives are locally declared or imported from another file.
