### ISSUE TITLE
Component typing is broken since v0.23.0 and at least up to v0.23.3

### ISSUE THREAD

**Issue by germsb** [johnsoncodehk/volar#123]
### Before
![Imgur](https://i.imgur.com/q2Aaqci.jpg)
### After
![Imgur](https://i.imgur.com/mvZ0MJd.jpg)

**Comment by johnsoncodehk** [comment]
Can it reproduce in https://github.com/johnsoncodehk/volar-starter?

**Comment by germsb** [comment]
Sorry but I have the same result. 
![Imgur](https://i.imgur.com/QyegFub.jpg?1)

pnpm 5.18.7
node 14.15.3

**Comment by johnsoncodehk** [comment]
Fixed in 0.23.4, thanks for your report!

**Comment by germsb** [comment]
It works like a charm! Thank you
