### ISSUE TITLE
[bug?] cannot resolve global components from "@vue/runtime-core".

### ISSUE THREAD

**Issue by JuerGenie** [johnsoncodehk/volar#1230]
I need add the code to my `.dts` file to get my global components' hint:

```typescript
import { GlobalComponents as GCS } from "@vue/runtime-core";

declare module "vue" {
  interface GlobalComponents extends GCS {}
}
```

before:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/20407230/164965354-f8863439-6614-4d57-9e3d-bcd21c40b1fc.png">

after:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/20407230/164965391-4c21fab8-0d5d-4c87-a9a3-059692fa5a98.png">

my extensions version: v0.34.10
my `vue` version: ^3.2.31
my `@vue/runtime-core` version: ^3.2.31

**Comment by johnsoncodehk** [comment]
Hi @JuerGenie, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by JuerGenie** [comment]
> Hi @JuerGenie, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

ok, I'm trying to reproduce the problem now, but cannot reproduce it... so weird😮‍💨. I'll try it again, if I reproduced the problem, I'll update this issue and let you know, thanks for your reply 🙂️.

**Comment by johnsoncodehk** [comment]
It seems a TS + pnpm issue, see https://github.com/antfu/unplugin-vue-components/issues/355.

**Comment by JuerGenie** [comment]
> It seems a TS + pnpm issue, see [antfu/unplugin-vue-components#355](https://github.com/antfu/unplugin-vue-components/issues/355).

yes its! thank you very much!
