### ISSUE TITLE
when `strict: false`, in <script> language-server will get nothing, <template> is correct

### ISSUE THREAD

**Issue by chenjiangui** [johnsoncodehk/volar#1231]
in vue2, i open the `strict: false` in tsconfig.json, in <script> all code-completion will loss.

this is `strict: false`
<img width="650" alt="image" src="https://user-images.githubusercontent.com/18565140/164971391-58a89472-9930-415e-ad39-4c75a0181156.png">

this is `strict: true`
<img width="693" alt="image" src="https://user-images.githubusercontent.com/18565140/164971367-dafc723c-c494-49eb-9b88-3fbe6bb78694.png">

it is a vue-cli default template with vue2, ts, @vue/composition-api
```
<template>
  <div class="about">
    <h1>This is an about page</h1>
    <h1>{{ names }}</h1>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "@vue/composition-api"

export default defineComponent({
  props: {
    xx: String,
    a: [String, Number],
  },
  data() {
    return {
      id: 1,
      names: {
        code: 1,
      },
    }
  },
  created() {
    console.log(2)
  },
  methods: {
    abc() {
      this.console.log(this.names)
    },
    bb() {
      this.abc()
    },
  },
})
</script>

```

**Comment by chenjiangui** [comment]
i not try in vue3, maybe has same problem.

**Comment by johnsoncodehk** [comment]
`strict: true` or `noImplicitThis: true` is required, see https://vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json.

**Comment by chenjiangui** [comment]
> `strict: true` or `noImplicitThis: true` is required, see https://vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json.

okay, why <template> can be incorrect, I'm just curious.
