### ISSUE TITLE
Passing a valid string to an enum prop shows as an error

### ISSUE THREAD

**Issue by SharpSeeEr** [johnsoncodehk/volar#1239]
When a component defines a prop as an enum type volar shows an error when a parent component passes a valid enum string value.  

![image](https://user-images.githubusercontent.com/4459909/165342638-255f8661-cf09-4788-bfa4-7f9084fc1277.png)

enum:
```ts
export enum Recipient {
  World = 'World',
  Country = 'Country',
  State = 'State',
  City = 'City',
  Nobody = 'Nobody',
}
```

Child component:
```ts
defineProps<{ msg: string, recipient: Recipient }>()
```

 Parent component: 
```vue
<template>
  <HelloWorld recipient="Nobody" />
</template>
```

Typescript sees the two values as equal:
```ts
const same = Recipient.Nobody === 'Nobody'; // true
```

I created a repo that reproduces the issue:  https://github.com/SharpSeeEr/volar-enum-props

**Comment by johnsoncodehk** [comment]
This is expected TS behavior, see https://stackoverflow.com/questions/50464141/cannot-assign-a-string-value-to-typescript-enum-initializer-type-string-not-ass.
