### ISSUE TITLE
server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by Sh1-5** [johnsoncodehk/volar#1242]
version: 0.34.10

error: The Volar - Language Features Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

cause: no CodeInsight in all file

solution: 0.34.0

**Comment by johnsoncodehk** [comment]
Hi @Sh1-5, what are your vscode version? Please try update vscode if it can.

**Comment by Sh1-5** [comment]
> Hi @Sh1-5, what is your vscode version? Please try update vscode if it can.

My vscode version is 1.66.2.

If I use 0.34.10, the program based on vue2 will cause this problem, the program based on vue3 will not.(I try agian,  and find a new error: Request textDocument/inlayHint failed.)

If I use 0.34.0, everything is all right.

**Comment by Sh1-5** [comment]
0.34.10

a program based on vue3

<img width="612" alt="截屏2022-04-28 12 24 08" src="https://user-images.githubusercontent.com/48705798/165677785-4717cad3-5846-49c8-82ac-c30fbc3897f0.png">

a program based on vue2

<img width="596" alt="截屏2022-04-28 12 21 20" src="https://user-images.githubusercontent.com/48705798/165677830-0b2e5b27-719a-45df-a3d1-1693db0b5570.png">

**Comment by Sh1-5** [comment]
> Hi @Sh1-5, what is your vscode version? Please try update vscode if it can.

thank you, maybe I haven't turned my mbp off in too long😂, I restart it and the probelm disappear.

**Comment by Sh1-5** [comment]
The problem has cropped up again, I'm sure this problem is caused by Volar, I uninstalled Volar and installed Vetur without any problems

**Comment by jbhammon** [comment]
For what it's worth, I just started seeing a similar error with Volar whenever I start up vs code today. The extension is version 0.34.10 and vs code is up to date. Happy to share whatever terminal or server logs would be helpful for troubleshooting.

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem in vue2 branch of https://github.com/johnsoncodehk/volar-starter, will be helpful if you can provide minimal reproduction.

**Comment by dark-kitt** [comment]
Hey guys, I have the same problem.

VS Code,  1.66.2 (mac os)
Volar,  v0.34.11

```
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0x1175368a0 node::FatalException(v8::Isolate*, v8::TryCatch const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 1: 0x1175368a0 node::FatalException(v8::Isolate*, v8::TryCatch const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x117536a28 node::OnFatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x117536a28 node::OnFatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x11324c78c v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x11324c78c v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x11324c6bc v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x11324c6bc v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1133fe738 v8::internal::Heap::StartIncrementalMarking(int, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1133fe738 v8::internal::Heap::StartIncrementalMarking(int, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x1134450a4 v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x1134450a4 v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x11344488c v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x11344488c v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x1134444ec v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x1134444ec v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x11345fa28 v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x11345f958 v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x11759814c node::CommonEnvironmentSetup::context() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x117598860 node::CommonEnvironmentSetup::context() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x11759852c node::CommonEnvironmentSetup::context() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x117598ed0 node::CommonEnvironmentSetup::context() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x1a381a26c _pthread_start [/usr/lib/system/libsystem_pthread.dylib]
13: 0x1a381508c thread_start [/usr/lib/system/libsystem_pthread.dylib]
12: 0x11344769c v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x113446c90 v8::internal::MarkCompactCollector::EnsureSweepingCompleted() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
[Info  - 9:29:30 AM] Connection to server got closed. Server will restart.
[Error - 9:29:30 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
...
[Error - 9:29:30 AM] Request textDocument/inlayHint failed.
Error: Connection got disposed.
...
[Error - 9:29:30 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
...
[Error - 9:29:30 AM] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
...
[Error - 9:29:30 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
```

Tried to switch versions, but the problem still appears.

**Comment by johnsoncodehk** [comment]
@dark-kitt Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If it can't please open a new issue and provide repro case.

**Comment by dark-kitt** [comment]
@johnsoncodehk I couldn't reproduce my error with your repo and I forgot to mention that my project is a Vue 2 project without TypeScript support. Are there any problems with Vue 2? I thought Volar supports Vue 2.

Anyhow, I figured out that if I open your test project with my VS Code and switch to my Vue 2 project (in one VS Code instance), Volar works like charm. But when I'm opening my Vue 2 project directly, I get the same error as above.

Do you have any idea why that happens?

**Comment by johnsoncodehk** [comment]
@dark-kitt I can't confirm if no repro case, but maybe if check your workspace TS version if it can update.

**Comment by Sh1-5** [comment]
A little down lately, always look forward to volar, try again and again. As soon as I install volar, the code prompt disappears.

Formatting code gets stuck because it takes up too much memory(vscode plugin: prettier)

Don't struggle, switch to vetur

**Comment by johnsoncodehk** [comment]
@Sh1-5 The `Request textDocument/inlayHint failed.` error should be fixed by https://github.com/johnsoncodehk/volar/commit/981061f562aa710494c70dc9318b502988d5c6a5, it is due to workspace TS version too low. Would be helpful if you can provide repro case / error log / screen recording to show what problem you have currently.

> Formatting code gets stuck because it takes up too much memory(vscode plugin: prettier)

We do not have builtin prettier support, this problem should not be related to volar.

Please understand that I cannot "psychic", https://github.com/johnsoncodehk/volar-starter have a vue2 branch and you should able to check and compare what different with it.

**Comment by tjx666** [comment]
碰到和标题一样的错误，简直崩溃，也是 vue2：

![image](https://user-images.githubusercontent.com/41773861/169757542-3fe2656c-fc86-4309-9c6e-fbc47b7b09dd.png)

**Comment by maicolbruski** [comment]
Same here, with VSCODE Version: 1.68.1, doesn't work.

**Comment by Muluk-m** [comment]
<img width="286" alt="企业微信截图_3a999e19-99bd-49f7-9705-e2a784c1aaa3" src="https://user-images.githubusercontent.com/69963532/174464464-060d3ee1-0e20-4720-953a-35b19976cbb4.png">
Demoted to the previous version, which made me usable
