### ISSUE TITLE
vue-tsc fails to detect typechecks through computed property

### ISSUE THREAD

**Issue by lllopo** [johnsoncodehk/volar#1246]
I'm having the following case (will try to shorten it up as much as possible) :

```
class Options1 = {
   id:number = 0;
}

class Options2 = {
    somethingelse:string = ''
}
```

then a SFC component that looks like this :

```
<template>
      ...
     <div v-if="isOptionOne" :some-prop="opts.id" />
      ...
</template>

<script>
...
setup(props, context) {
     const opts= ref<Options1 | Options2>();

     const isOptionOne= computed<boolean>(() => !!opts.value && opts.value instanceof Options1);

     const doSomething= (extops: Options1 | Options2) => {
				if(extops.isValid()) {
					opts.value = extops;
				}
			};

     return {isOptionOne, opts, doSomething}
}
...
</script>
```

The problem with the code above is, that vue-tsc complains both the `opts` in `some-prop` could be undefined and that it has no property `id`, while `isOptionOne` in the `v-if` clearly verifies both.

I don't know if this is already posted, but I couldn't find anything similar, so if it is - I apologize in advance.

**Comment by lllopo** [comment]
This is with TypeSscript latest 4.6.4 and vue-tsc latest 0.34.11

**Comment by pikax** [comment]
@lllopo volar is correct, your `opts` has a type of `Ref<Options1 | Options2 | undefined>`

Because you not init it with a value as you can see by this [ref overload](https://github.com/vuejs/core/blob/main/packages/reactivity/src/ref.ts#L71)

**Comment by lllopo** [comment]
@pikax No, it is not correct as the `v-if` would happen only when `opts` IS defined and it is instance of Options1, which has a property `id`. 
If you write this :

```
if(!!opts.value && opts.value instanceof Options1) {
    someOpts = opts.id;
}
```

it would work perfectly fine, right ? Then why not with the computed property and v-if ?!

**Comment by pikax** [comment]
@lllopo typescript cannot narrow types based on other variables, even if the javascript code is correct, you must ensure the typescript is also correct, which in this case the `computed` isOptionOne will not change the typescript type.

**Comment by pikax** [comment]
@lllopo here's [typescript only code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgMwDRwMYXAVxhQBM4BfONKPOAcgDd8VaAobAGwEMBnbuAeTAxgEAHbcAjIhZxZcYMQBccUfhAAjFFDgBeOAAYA3DLnBuANU7sFACgCU0uU+QoY+KKLgwoTE7LIsAWxcvAJCIuIATI5y3HiuABbAogDmKOzcKMrc3skpunSsTmaW1sT2Mc4ubh5ePih+5IEsLbji8BBCfHqoaAA8gsJiknAAPmFDUQB89sZsw-BmgxH8oigFuARExH3qEBDsKJyiMxU6U3AAhJedMNwAdPRWTHAAZK9wtw9P7C-JOcdsCgIGgJhFJHY5m0cnBiBAAMrxGBJVIFGwoAAeME63GUy2GUnG+KiDnOlXkoPRWJx9xKVlsdgcCEaTi+j2e6z0mOxYG4xicATIcxawEpS3CYlWKHZvxQTMabJ+TFpFnp5TszRaLSAA), kept `ref` and `computed` to be easier to understand:
```ts
import { ref, computed } from 'vue'
class Options1 {
    id: number = 0;
    isValid() {
        return true
    }
}

class Options2 {
    somethingelse: string = ''
    isValid() {
        return true
    }
}


const opts = ref<Options1 | Options2>();

const isOptionOne = computed<boolean>(() => !!opts.value && opts.value instanceof Options1);

const doSomething = (extops: Options1 | Options2) => {
    if (extops.isValid()) {
        opts.value = extops;
    }
};



if (isOptionOne.value) {
    opts.value.isValid()
}
```

Or just [plain typescript equivalent](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=24&pc=2#code/MYGwhgzhAEDyAOAXAlgewHYQIzQN4ChojpkATALmnQFcBbAIwFMAnaAXmgAYBuQ45CADUwIMgAoAlHj7FizRomrN00RM2qMZ0AL75d+UJBgIUGCACZpsiKloKAFsnQBzRiAiNKENU+ftoAOQBWgLCoqSSVrJyCkoqahpauvr4pIyG8tAgCtCoSBCUJmiYOAA+cEjFFtDl1OhpAGZOjKS8+AZmiCQQRRiw6Iz+YpFsAHzQAIQTeYgwAGRzufkkmIhg6MCMqA0VpiUSku34yDtiAr3o-YxSBLIzEAB0oSLiEnpH7UA)

**Comment by lllopo** [comment]
@pikax The 'plain typescript equivalent' is a good one. So my question is how :

```
const isOptionOne = (() => !!opts && opts instanceof Options1)()

if (isOptionOne) {
    opts.isValid()
}
```

differs to :

```
if (!!opts && opts instanceof Options1) {
    opts.isValid()
}
```

so the first one fails and the second one works ? 
Because this example is simple, but actually the so called `isOptionOne` is used on at least 7-8 places in a huge component at my place, and making copy of it is a really bad practice, especially having that the conditions of  `isOptionOne` might change over time. doesn't mentioning that I workarounded it like this :

```
<template>
      ...
     <div v-if="!!optionOneId" :some-prop="optionOneId" />
      ...
</template>

const optionOneId= computed<number|null>(() => !!opts.value && opts.value instanceof Options1? opts.value.id : null);
```

and guess what - it works without complaining about the `null`. Have in mind, in my case the 'div' is not a div, but another component which prop `some-prop` is defined as Number and required. If the workaround works, because vue/typescript doesn't get it that the `some-prop` should be a number and not null, then it is even messier than I though.

**Comment by pikax** [comment]
> @pikax The 'plain typescript equivalent' is a good one. So my question is how :
> 
> ```
> const isOptionOne = (() => !!opts && opts instanceof Options1)()
> 
> if (isOptionOne) {
>     opts.isValid()
> }
> ```
> 
> differs to :
> 
> ```
> if (!!opts && opts instanceof Options1) {
>     opts.isValid()
> }
> ```

The second one the `opts` type is [narrowed](https://www.typescriptlang.org/docs/handbook/2/narrowing.html), on the first one typescript cannot narrow the type because the scope is a function and it does not keep that type. 
- Bear in mind that `computed` in vue is basically a function that returns something when something inside of the function changes, the representation in typescript must be a function call with a return straight away.



> Because this example is simple, but actually the so called `isOptionOne` is used on at least 7-8 places in a huge component at my place, and making copy of it is a really bad practice, especially having that the conditions of `isOptionOne` might change over time

One possible solution is having a [function](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) on the template

```html
<div v-if="isOptionOne(opts)">
  // opts is narrowed to 
</div>
<div v-else>
  // opts is other type
 </div>

function isOptionOne(o: Options1 | Options2): o is Options1 {
 // return true or false
}
```

**Comment by lllopo** [comment]
> typescript cannot narrow the type because the scope is a function and it does not keep that type

Ahhh ... that explains it then. I overestimated typescript a bit then :-). Thought it can handle this. Thanks fort he explanation.

> One possible solution is having a function on the template

Yes, I'm using this approach on some places for other reasons indeed. Thanks for the suggestion, though.
