### ISSUE TITLE
Component tags are always highlighted in red (idem like #1172)

### ISSUE THREAD

**Issue by stefaanMLB** [johnsoncodehk/volar#1247]
Same problem like #1172. 
Same thing in the volare-starter project (pulled, not changed in any way)
![image](https://user-images.githubusercontent.com/50827063/165935660-abfe2b84-b5ca-472f-aff4-d76081a0fcbe.png)

jsx property set as requested in tsconfig.json
```ts
"jsx": "preserve"
```
How can I debug this problem further ?

**Comment by plashenkov** [comment]
I have the same problem for `"jsx": "preserve"` too.

**Comment by johnsoncodehk** [comment]
This error is due to missing `@vue/runtime-dom` because you do not have install node_modules in volare-starter.

**Comment by johnsoncodehk** [comment]
@plashenkov Make sure you have put it in `compilerOptions`, see https://github.com/johnsoncodehk/volar/issues/1219#issuecomment-1104548432.

**Comment by stefaanMLB** [comment]
Sorry, no change.  Example in starter project, after vscode reload

![image](https://user-images.githubusercontent.com/50827063/166458937-706591c8-10aa-41d5-ac2b-c3df050dbda9.png)
package.json
```json
{
  "name": "volar-starter",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "vue": "next"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "latest",
    "@volar-plugins/prettier-html": "latest",
    "@vue/compiler-sfc": "latest",
    "@vue/runtime-dom": "^3.2.31",
    "typescript": "latest",
    "vite": "latest",
    "vue-tsc": "latest"
  }
}
```
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}
```

**Comment by johnsoncodehk** [comment]
@stefaanMLB Please check if you have disabled `editor.semanticHighlighting.enabled` in vscode settings, you need to enable it.

<img width="665" alt="螢幕截圖 2022-05-03 21 22 01" src="https://user-images.githubusercontent.com/16279759/166460774-ffc2a7bb-5130-4cf3-b0a3-3764b716b9a2.png">

**Comment by stefaanMLB** [comment]
This was set to configuredByTheme`, I changed to `true`.  This doesn't help.

**Comment by negipoyoc** [comment]
I have the same problem.

**Comment by johnsoncodehk** [comment]
@stefaanMLB Please follow steps.

1. config `"volar.vueserver.useSecondServer": true` and `"volar-language-features-2.trace.server": "verbose"` in volar-starter vscode workspace settings. <img width="997" alt="螢幕截圖 2022-05-05 12 56 17" src="https://user-images.githubusercontent.com/16279759/166865623-684bbb0f-45d4-4328-847c-c3c049c6d230.png"> <img width="627" alt="螢幕截圖 2022-05-05 12 50 45" src="https://user-images.githubusercontent.com/16279759/166865267-33f609a1-ef97-4252-bbfb-5adb76064d65.png">
3. Reload vscode window
4. Open `src/App.vue`
5. Open output -> Volar - Second Language Features Server, search `Received response 'textDocument/semanticTokens/range` and show me the response log. <img width="1400" alt="螢幕截圖 2022-05-05 12 58 56" src="https://user-images.githubusercontent.com/16279759/166865813-cfdb9b3d-2a01-4b7a-b545-22c1cc6f67ed.png">

**Comment by negipoyoc** [comment]
@johnsoncodehk 
I tried the above Step, but unlike yours, the contents of the "data" is empty.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/31283418/166866587-e4d0ff06-b76a-4a73-9622-27e2d1febcad.png">

**Comment by stefaanMLB** [comment]
@johnsoncodehk thanks for the precise instructions. appreciating it.
I have the search string 5x in the output, so I included some more text just in case.  Seems the text you're looking for is in there twice
```txt
[Trace - 07:11:35] Received response 'textDocument/semanticTokens/range - (5)' in 3141ms.
Result: {
    "resultId": "1651727495813",
    "data": [
        2,
        3,
        10,
        12,
        0
    ]
}


[Trace - 07:11:35] Received response 'textDocument/documentLink - (7)' in 2502ms.
Result: [
    {
        "range": {
            "start": {
                "line": 1,
                "character": 27
            },
            "end": {
                "line": 1,
                "character": 44
            }
        },
        "target": "file:///c%3A/Users/lcartreul/Documents/projecten/volar-starter/src/assets/logo.png"
    }
]


[Trace - 07:11:35] Received response 'textDocument/codeLens - (8)' in 2455ms.
Result: []


[Trace - 07:11:35] Received response 'textDocument/codeLens - (6)' in 2659ms.
Result: []


[Trace - 07:11:35] Received request 'vue/docVersion - (10)'.
Params: {
    "uri": "file:///c%3A/Users/lcartreul/Documents/projecten/volar-starter/src/App.vue"
}

```

**Comment by johnsoncodehk** [comment]
@negipoyoc Do you have install node_modules of volar-starter?

@stefaanMLB Seems you have correct response data, please try:
1. Update vscode if it can.
2. Check what extensions it may affect vue document you have installed and try disable it just keep volar. (`Help: Start Extension Bisect` command may help)

**Comment by stefaanMLB** [comment]
@johnsoncodehk 
didn't help.
I tried to uninstall and reinstall Volar, but it now fails after every reload (no code coloring + below error message)
![image](https://user-images.githubusercontent.com/50827063/167127051-e9ca7910-2d87-4b36-9a30-5d8cf4baa362.png)

**Comment by negipoyoc** [comment]
@johnsoncodehk Hello. Thank you for your answer.

It seems that the data was Empty because I checked the output without resolving the dependency with volar-starter.
After doing the npm install, the Component was highlighted successfully.

I then reviewed the tsconfig.json of my project, which has a similar problem, while looking at the tsconfig.json of volar-starter.

By adding the following to tsconfig.json, I was able to get the highlighting and the problem was resolved in my project.

```
 "compilerOptions": {
    "jsx": "preserve",
  }
```

Thank you for addressing the problem despite my simple carelessness.

**Comment by yoyo837** [comment]
Same here.
![image](https://user-images.githubusercontent.com/6134547/168029394-cfedcc03-3de6-4d4e-90d5-6507bcd9b125.png)

**Comment by johnsoncodehk** [comment]
@stefaanMLB For that message, see https://github.com/johnsoncodehk/volar/issues/1124#issuecomment-1123312339.
But I have no clue as to why your component is showing red, the LSP is returning the expected response, the VSCode settings is find, if it is not the influence of other extensions, it can only be considered a problem with VSCode (but this is the least likely).

@negipoyoc It's ok, I will improve user guidance.

@yoyo837 See #1192.

**Comment by stefaanMLB** [comment]
@johnsoncodehk I tried disabling any exntensions that could interfere (like vetur), but no luck.
I can live with the problem, I'll try volar out on my home computer which has less extensions installed. Wo't have time in the first few days though.

**Comment by tol64** [comment]
@johnsoncodehk, created a new project in `Nuxt 3` on a virtual machine `Windows 10` (VMware). In the editor `VSCode` installed only one extension - `Vue Language Features (Volar)`.

With `Developer: Inspect Editor Tokens And Scopes` you can see additional data, how the tag marked in red is interpreted.

![2022-05-27_194124](https://user-images.githubusercontent.com/50295805/170743806-248918c2-e7bd-4132-ae70-bbf63fdb72a3.png)

The custom components look the same. In this case, the application is correctly displayed and works in the browser.

With this information in mind, how can I try to solve this problem?

**Comment by johnsoncodehk** [comment]
Please update to v0.34.17.

**Comment by tol64** [comment]
> Please update to v0.34.17.

Updated to version `v0.35.0` and now everything is correct.
Thank you! 👍

**Comment by stefaanMLB** [comment]
Same here, update to v0.35.0 has solved the problem.

**Comment by litvinovvo** [comment]
We using explicit components import and now it is hard to see what wasn't imported correctly

**Comment by johnsoncodehk** [comment]
> We using explicit components import and now it is hard to see what wasn't imported correctly

The past behavior was abandoned to resolve the situation in this issue, if you need the past behavior, please open a new feature request.
