### ISSUE TITLE
v-click= MouseEvent vs PointerEvent

### ISSUE THREAD

**Issue by JTravis76** [johnsoncodehk/volar#1248]
This appears to be a bug, Not sure if Volar or from Typescript.
When using **@click="foo"**  directive within a template, Volar expects the method to be type of `((payload: MouseEvent): void)`.
However, the console log result returned in of type `((payload: PointerEvent): void)`.

Actual:
v-click directive type of MouseEvent

Expected:
v-click directive type of PointerEvent

### Environment Info
Volar: v0.34.11
VSCode: 1.66.2
npm
```
"tslib": "^2.3.1",
"typescript": "~4.1.5",
"vite": "^2.9.1",
"vue-tsc": "^0.34.5"
```

### Error Sample
![image](https://user-images.githubusercontent.com/9905282/165951353-859a338c-d607-4e57-af4c-629732743693.png)

**Comment by JTravis76** [comment]
> This is different for browser to browser, also see https://stackoverflow.com/questions/70626381/why-chrome-emits-pointerevents-and-firefox-mouseevents-and-which-type-definition

Learn something new all the time. I guess I'll have to leave the red squiggly.
Thanks

**Comment by johnsoncodehk** [comment]
Event type is define by `@vue/runtime-dom`, please forward to vue repo.
