### ISSUE TITLE
Cannot start Volar `command 'volar.action.switchTsPlugin' not found`

### ISSUE THREAD

**Issue by arpadgabor** [johnsoncodehk/volar#125]
Along with this error I'm also seeing some logs in the `Log (Window)` panel.

```
[2021-04-06 13:01:10.886] [renderer3] [error] Unable to load and parse grammar for scope text.html.vue from vscode-remote://wsl%2Bubuntu/home/arpad/.vscode-server/extensions/johnsoncodehk.volar-0.23.3/syntaxes/vue.tmLanguage.json {}
[2021-04-06 13:01:10.887] [renderer3] [error] No grammar provided for <text.html.vue>: Error: No grammar provided for <text.html.vue>
```

Doing a `cat .vscode-server/extensions/johnsoncodehk.volar-0.23.3/syntaxes/vue.tmLanguage.json` returns nothing and I've reinstalled the plugin multiple times. Vetur is disabled too.

And here is the VSCode info:

```
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

Also to note, I'm running WSL2.

**Comment by johnsoncodehk** [comment]
> Cannot start Volar command 'volar.action.switchTsPlugin' not found

For this first problem, you need to open any `*.vue` file to trigger Volar enable first.

**Comment by arpadgabor** [comment]
I did, however it wouldn't parse the file and any command I tried for volar failed. Now that I've uninstalled both plugins and restarted VSCode it seems to work. Not sure what happened there. Will close this issue.

**Comment by johnsoncodehk** [comment]
`vue.tmLanguage.json` file will modify by `volar.style.defaultLanguage` option and this may be the reason.

btw let me know if any other infos for reproduce.
