### ISSUE TITLE
tip unknown type , optional property + "strictNullChecks": false

### ISSUE THREAD

**Issue by cj0x39e** [johnsoncodehk/volar#1250]
![image](https://user-images.githubusercontent.com/8348553/166084965-6b4683b1-d171-4ee0-9cb6-4f46fb4c8d22.png)
```ts
import { PropType, ref } from "vue";

type Options = {
  value?: string;
};

const helloWorldProps = {
  options: Object as PropType<Options>,
};

const props = defineProps(helloWorldProps);


props.options;
```

If the `value` field is not optional, the hint is right.

**Comment by johnsoncodehk** [comment]
`defineProps` type is define by `@vue/runtime-core`, please forward to vue repo.
