### ISSUE TITLE
Can It list all the slots when I press #?

### ISSUE THREAD

**Issue by jiyingzhi** [johnsoncodehk/volar#1251]
It now prompts the name of the slot only when the first letter is pressed:
![image](https://user-images.githubusercontent.com/21698836/166146032-1620eaf2-6707-4009-8bd5-b3d019a0a66c.png)
But it doesn't show me all the slot names when I press #:
![image](https://user-images.githubusercontent.com/21698836/166146061-7057aadf-8e74-4856-a9ef-ab0313dbd589.png)

**Comment by jiyingzhi** [comment]
I'm using script Setup syntax

**Comment by johnsoncodehk** [comment]
We do not supported template slots since 0.34.0 and can't implement it for now, see #1253.

**Comment by johnsoncodehk** [comment]
Reopen this because I found that this issue is not related to typed template slots.
