### ISSUE TITLE
Support for typed template slots

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#1253]
Since 0.34.0, typed template slots is not supported due to #1108, we need to wait for https://github.com/vuejs/core/pull/2693 implemented to have a new way to support typed template slots that do not have performance issue.

**Comment by oliverzy** [comment]
Could we make this feature as an option that default as true and add a warning if user want to enable it?  Because I see this upstream issue has been opened almost two years, typed slot is an very important feature that volar has

**Comment by TotomInc** [comment]
I agree with @oliverzy, the best of both worlds would be to make it an option that is turned off by default.
