### ISSUE TITLE
Add some `css` feature  like React Style Helper

### ISSUE THREAD

**Issue by rottenpen** [johnsoncodehk/volar#1256]
Is it possible to add some feature like [React Style Helper](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper)?
![](https://img.alicdn.com/imgextra/i2/O1CN01fiRbHN1gY7XQOSAlk_!!6000000004153-1-tps-750-545.gif)
I think i can pr for it.

**Comment by johnsoncodehk** [comment]
We has support similar features for `<style scope>` and `<style module>`, what do you think is missing?

**Comment by rottenpen** [comment]
> We has support similar features for `<style scope>` and `<style module>`, what do you think is missing?

oh，it doesn't work in my workspace, or am I missing some configuration item？

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/12029924/166665462-aad42f5c-07b4-41c3-8a53-8941851e0abe.png">

**Comment by rottenpen** [comment]
> We has support similar features for `<style scope>` and `<style module>`, what do you think is missing?

@johnsoncodehk such as show stylesheet info when hover on classname. Has this feature been implemented？

![image](https://user-images.githubusercontent.com/12029924/166695347-e7dac1dc-d801-4ef3-9bee-a1f3a051135d.png)
And My workspace only show the info like this.
<img width="924" alt="image" src="https://user-images.githubusercontent.com/12029924/166696702-3757ddea-e009-4b1b-b3cd-a69289536407.png">

**Comment by johnsoncodehk** [comment]
Show stylesheet in hover info is out of project scope, it will not built-in support in extension. But you can implement it by language service plugin API, see #1027.
