### ISSUE TITLE
Syntax highlighting break if we have multiline script tag

### ISSUE THREAD

**Issue by jd-solanki** [johnsoncodehk/volar#1258]
I am using prettier and at the moment it converts script tag to multi-line tag. With this volar syntax highlight breaks.

![image](https://user-images.githubusercontent.com/47495003/166696337-84213ea7-734b-448b-802f-51b1c717e134.png)

**Comment by johnsoncodehk** [comment]
<img width="365" alt="螢幕截圖 2022-05-28 20 24 45" src="https://user-images.githubusercontent.com/16279759/170825414-04e1ec1d-2ea8-464a-bb35-111a3f6a242b.png">

Hi @jd-solanki, I can't reproduce this problem, maybe you have installed other syntax highlight extensions and which affect syntax highlight on vue document.
