### ISSUE TITLE
Typescript @ts-ignore and @ts-nocheck are not respected

### ISSUE THREAD

**Issue by stijn-gravity** [johnsoncodehk/volar#1260]
## setup

I am using Nuxt 3 with Vue 3, and the tsconfig looks like this:

```
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "useUnknownInCatchVariables": false,
    "noImplicitAny": true
  },
  "exclude": ["node_modules", "**/__mocks__/*.ts", "**/*.spec.ts"]
}
```

## issue

If a line of code throws a typescript error that can't be resolved this is blocking for the entire project. In original typescript you can use @ts-ignore or @ts-nocheck to circumvent this.

## example

The following piece of code is giving me an issue, where swiper is an imported module.

```
<template>
    <!-- @ts-nocheck -->
    <swiper
      slides-per-view="auto"
      :space-between="40"
      :navigation="{
        nextEl: `.swiper-next-${id}`,
        prevEl: `.swiper-prev-${id}`
      }"
      :modules="swiperModules"
    >
</template>
```

This throws the following error: 
```
Type '{ nextEl: string; prevEl: string; }' is not assignable to type 'undefined'.

55             :navigation="{

```

There is clearly something wrong in the typing of this module, so I have reported it to them as well. However typechecking now fails without us being able to work around it. The @ts-nocheck on top of this is being ignored. I've also tried putting a ts-nocheck in the script, without any results.

## resolution

I hope this functionality can be supported. Until then, are there any other ways to exclude files from typecheck? (without removing them from the build obv).

**Comment by johnsoncodehk** [comment]
`<!-- @ts-nocheck -->` has no effect in expected because it is html comment not template TS comment. You can only use `@ts-ignore` for event expression or interpolation, for prop bindings, you could use `as any`.

```html
<template>
    <swiper
      slides-per-view="auto"
      :space-between="40"
      :navigation="({
        nextEl: `.swiper-next-${id}`,
        prevEl: `.swiper-prev-${id}`
      } as any)"
      :modules="swiperModules"
    >
</template>
```

**Comment by stijn-gravity** [comment]
@johnsoncodehk, Thanks that solves this issue.
