### ISSUE TITLE
vue-tsc behaves inconsistently with tsc in monorepo

### ISSUE THREAD

**Issue by lovetingyuan** [johnsoncodehk/volar#1262]
I have a monorepo, I install `vite` in the root position instead under the vue project, while `vite/client` defined in "types" is not applied to .vue files, it can not recognize `ImportMetaEnv` defined in `vite/client`, but .ts files work well.

There is the reporduce repo: https://github.com/lovetingyuan/vue-tsc-vite-client-error

**Comment by lovetingyuan** [comment]
`vue-tsc --noEmit` works well, no error.

**Comment by lovetingyuan** [comment]
![1651731692(1)](https://user-images.githubusercontent.com/7310471/166871869-8f18a768-647d-429b-8fb3-c442eff31473.png)

**Comment by johnsoncodehk** [comment]
It's seems a module resolve issue of volar, you could add `import 'vite/client';` to apps/vue2-project/env.d.ts to avoid this problem for now.
