### ISSUE TITLE
volar not found in marketplace?

### ISSUE THREAD

**Issue by leosin** [johnsoncodehk/volar#1265]
today in vscode tips:
The 1 extension(s) below, in workspace recommendations have issues: johnsoncodehk.volar (not found in marketplace)

![image](https://user-images.githubusercontent.com/3676670/167062078-d5cd5604-1bf1-400c-b36f-978bb476e1c4.png)

**Comment by yaegassy** [comment]
Check this issue and commit comments.

- <https://github.com/johnsoncodehk/volar/issues/1124>
- <https://github.com/johnsoncodehk/volar/commit/afd4f4ba3a34b939f158b63ac72729aec65f9cb3#commitcomment-72663442.>
