### ISSUE TITLE
in workspace recommendations have issues: johnsoncodehk.volar (not found in marketplace)

### ISSUE THREAD

**Issue by lyJava** [johnsoncodehk/volar#1266]
![image](https://user-images.githubusercontent.com/14010610/167066485-ad8d10b1-c57a-4311-981f-710878a59dff.png)
![image](https://user-images.githubusercontent.com/14010610/167066494-f4cfda21-3fd8-4da4-a7e0-3eebb5173f4c.png)
It only appeared when I opened vscode recently, and I saw the prompt message
![image](https://user-images.githubusercontent.com/14010610/167066581-f21dcc63-13a2-48a9-9fb6-abfc6b01191e.png)，
This is my extended screenshot：
![image](https://user-images.githubusercontent.com/14010610/167066894-77e2c9ed-efbf-4b9c-b145-f3049d0a31ed.png)
Configuration screenshot：
![image](https://user-images.githubusercontent.com/14010610/167066991-ec9b1498-ef28-4248-9647-86e01bf678c2.png)
And the Vue page previously configured using volar format does not take effect

**Comment by lyJava** [comment]
This problem has now been solved. Later, I tried to update vscode itself, and suddenly found that volar works normally.

**Comment by tno2007** [comment]
**File -> Close Folder** ... on all instances of vscode
Then re-opened my project folder. Warning gone now.

**Comment by hisahisabanbi** [comment]
Me too

**Comment by tohagan** [comment]
You *might* want these as replacements ...

```js
{
    "recommendations": [
      "Vue.volar",                        // Vue 3 Language Features 
      "Vue.vscode-typescript-vue-plugin", // Typescript Vue Plugin (Volar)
      "MisterJ.vue-volar-extention-pack"  // Vue Volar extension pack (includes many extenstions)
    ]
}
```

**Comment by Soviut** [comment]
@tohagan thanks, this is the correct solution to the error (assuming you're planning to keep Volar installed).

The vue typescript plugin is also a good suggestion. It seems like it might have gotten rid of the quirk where you see a typescript error twice in VSCode when you hover over an error.

Finally, the volar extension pack has really sparse documentation; maybe update your comment to explain what it does?
