### ISSUE TITLE
Language features still broken in templates

### ISSUE THREAD

**Issue by TimothyKrell** [johnsoncodehk/volar#1269]
Jump to definition does not work in `<template>` section, but works in `<script>` section.

Currently I _do_ have `"jsx": "preserve"` in my jsconfig.json compiler options.

Steps to reproduce:
1. install vue-cli - `npm install -g @vue/cli`
2. Create project - `vue create my-project`
3. Choose [Vue 3]
4. Add `"jsx": "preserve"` to jsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "baseUrl": "./",
    "jsx": "preserve",
    "moduleResolution": "node",
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  }
}
```
6. Edit `App.vue` to use script setup

```
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <HelloWorld msg="Welcome to Your Vue.js App"/>
</template>

<script setup>
import HelloWorld from './components/HelloWorld.vue'
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
7. Try to jump to definition on <HelloWorld ... /> in <template> (no definition found)
![image](https://user-images.githubusercontent.com/1585669/167129136-c9029808-02aa-4b89-b2b8-c0483ddee226.png)
8. Jump to definition works on HelloWorld import

Probably related to #1170

**Comment by johnsoncodehk** [comment]
Resolved by https://github.com/johnsoncodehk/volar/commit/7d257ed75b0ab5fa30ec2cd9833d01709418f1e5.
