### ISSUE TITLE
[feature request] <i18n> tag

### ISSUE THREAD

**Issue by lanyizi** [johnsoncodehk/volar#127]
Thanks a lot for making this extension!
Could you also add syntax support for `<i18n>`? 
(normally it just contains a JSON: https://vue-i18n.intlify.dev/guide/advanced/sfc.html)

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion! It may support by plugin mode in future, because this is not a part of vue core. And will be nice if we have type-checking to `$t(...)` by `<i18n>` json.

Plugin mode needed lot of work, and I maintain this project in my spare time, so don't expect it to come too soon. 😅

**Comment by kazupon** [comment]
Hi!
I'm `vue-i18n` author.

I’m improving vue-i18n's typescript support in this issue now.
This issue completion of the i18n resource keys and allows typesafe support for i18n resources.
https://github.com/intlify/vue-i18n-next/pull/489
but, `<i18n>` custom block needs Volar support.

I hope you will support the plugin mode for custom blocks. :)

**Comment by johnsoncodehk** [comment]
Supported `lang="json"` in 0.25.5. (Use `<i18n lang="json">`)

Please track #185 for Plugin API.
