### ISSUE TITLE
Volar V0.34.11 Server returned 404.

### ISSUE THREAD

**Issue by mrtdmrmrt** [johnsoncodehk/volar#1279]
I get an error when I try to download VOLAR from VS Code editor.
Error content:
'Unable to open 'Extension: Vue Language Features (Volar)': Server returned 404.'

**Comment by chicAboo** [comment]
I had the same problem.

> Vue Language Features (Volar)”: Server returned 404。

**Comment by yaegassy** [comment]
Try uninstalling the currently installed Volar extension and try installing it again. Also, if it is possible to upgrade VSCode, please upgrade and try it.

**Comment by mrtdmrmrt** [comment]
> Try uninstalling the currently installed Volar extension and try installing it again. Also, if it is possible to upgrade VSCode, please upgrade and try it.

I upgraded VSCode and the problem went away
vscode v1.67

**Comment by LuisDev2001** [comment]
You need to update ur vscode :)
