### ISSUE TITLE
Path autocomplete suggest system root when use root dash absolute path

### ISSUE THREAD

**Issue by sklme** [johnsoncodehk/volar#1282]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/4933537/167571817-01281277-0976-4bba-bc0f-1ce5f85128f0.png">

This problem only occurs in .vue files, and occurs in .ts files as well when using take over mode. I suppose it could be a volar bug.

**Comment by johnsoncodehk** [comment]
I get same behavior in .ts without takeover mode, it should be correctly TS behavior.
