### ISSUE TITLE
Getting started with Volar?

### ISSUE THREAD

**Issue by ADataGMan** [johnsoncodehk/volar#1285]
I'm trying to learn Vue from this course, which was upgraded to Vue 3 despite the link name. https://www.udemy.com/course/vuejs-2-the-complete-guide .

The course uses Javascript rather than Typescript, but when I enable Volar, and make sure Vetur is disabled, I get 0 language functionality. No color coding, no hints, I can't even select the language, I just see a lot of pieces about TS, no tsconfig, no tag, and something to do with attributes.

Does Volar work with Javascript? Is this a case where Volar is not a good fit? Is Volar aimed at helping experienced developers be more productive and a new developer isn't the intended audience?

This is a case where I don't know enough to even google my way out of the problem because I have no idea what's wrong, no errors are created.

**Comment by ADataGMan** [comment]
I did try restarting both VS Code and the Volar language server as I've seen other suggestions for getting it to pick up anything, but still see no hints.

**Comment by IIFelix** [comment]
Are you using the composition or options api?
Volar + Javascript works for me with composition api and script setup (see image).
![volar-js](https://user-images.githubusercontent.com/56734789/168298707-9e2f024e-0769-4d3d-84e4-80327c35c6a5.png)

**Comment by johnsoncodehk** [comment]
v0.34.15 is more out of the box for JS, please update extension and try again.

**Comment by ADataGMan** [comment]
I'm not sure which API I was using, it was an out of the box experience with no particular set up beyond installing Vue per the latest guidance and setting up a project.

I rebuilt my dev container and made sure to use the new 0.34.15 and now I'm seeing content populate as expected. Not sure what changed but thank you!
