### ISSUE TITLE
Can't get volar to read my jsconfig.json in multiroot workspace

### ISSUE THREAD

**Issue by SomeoneIsWorking** [johnsoncodehk/volar#1286]
I have a multiroot workspace with 3 roots
X, Y, Z
X has vue projects in `X/Vue` folder
I tried putting it in `X/Vue/jsconfig.json` with

    "vueCompilerOptions": {
        "experimentalShamefullySupportOptionsApi": false
    },

somewhere in-between
But I still get the warning
Moved the file to to `X/jsconfig.json` (modified include paths)
Still getting the warning
Same with

    "vueCompilerOptions": {
        "experimentalShamefullySupportOptionsApi": false,
        "experimentalDisableTemplateSupport": true
    },

As for `defineComponent()` I might try to build a migration tool because the project is long ongoing and has too many pages to cover one by one

**Comment by turkhero** [comment]
I'm facing the same issue on VSCode 1.68.0-insider version

**Comment by mrtdmrmrt** [comment]
I'm facing the same issue on VSCode 1.67 version

**Comment by MarekOravec** [comment]
Same issue VSCode 1.67

**Comment by lhermann** [comment]
Same here on VSCode 1.67.1

**Comment by johnsoncodehk** [comment]
Hi @SomeoneIsWorking, please make sure `**/*.vue` is added to `include` property in `X/Vue/jsconfig.json`, you can reference to https://github.com/johnsoncodehk/volar-starter/blob/8fce372ab521f80542537d174897af219a5946d4/tsconfig.json#L15.

**Comment by SomeoneIsWorking** [comment]
It seems to went away on its own for some reason
Now I get the same (desired) behavior regardless of having include `Vue/Web/ClientApp/src` or `Vue/Web/ClientApp/src/**/*.vue`

**Comment by johnsoncodehk** [comment]
@SomeoneIsWorking `experimentalShamefullySupportOptionsApi` is changed to `experimentalImplicitWrapComponentOptionsWithDefineComponent` in 0.34.13 and disabled by default, so the warning should be remove when extension updated on your vscode.

**Comment by lhermann** [comment]
@johnsoncodehk confirmed, the warning is no longer showing. Thank you!

**Comment by SomeoneIsWorking** [comment]
With the version when I had when I wrote the comment, toggling the boolean affected the warning
Also with `experimentalDisableTemplateSupport`
