### ISSUE TITLE
Why is the logo a skull?

### ISSUE THREAD

**Issue by mijorus** [johnsoncodehk/volar#1289]
☠️?

Looks like it was hijacked or smthing 😂

**Comment by Filipe-Rodrigues** [comment]
It's literally a recolor of the One Piece's logo, check it out:

![image](https://user-images.githubusercontent.com/28969294/167784643-d8af4e9e-9078-44fa-a0a6-02a6aa53ff16.png)

Now, why did they use this logo? Idk, maybe the authors love this franchise so much? lol

**Comment by Shinigami92** [comment]
I think it was going with the history of Vue 3.0 announcement: https://blog.vuejs.org/posts/vue-3-one-piece.html

**Comment by johnsoncodehk** [comment]
Answer: All of the above. 😄

We will update to official icon for extensions later.

**Comment by mijorus** [comment]
@johnsoncodehk ![IMG20220515200256.jpg](https://user-images.githubusercontent.com/39067225/168487309-fdc16cb8-1efc-41b0-abaf-aa35c9837110.jpg)


Found it! LoL
