### ISSUE TITLE
Doesnt work if project has both jsconfig and tsconfig

### ISSUE THREAD

**Issue by eidyz** [johnsoncodehk/volar#129]
I get the "Volar cannot offer intellisense auto completion due to your project being a Vue 2 project and not having @vue/runtime-dom installed. You can find more information at https://github.com/johnsoncodehk/volar" error when I have both jsconfig and tsconfig in my project

**Comment by johnsoncodehk** [comment]
You need to install `@vue/runtime-dom` if you are using vue 2, see: https://github.com/johnsoncodehk/volar#using

**Comment by eidyz** [comment]
@johnsoncodehk the problem is I am using vue 3.0.7

**Comment by johnsoncodehk** [comment]
@eidyz please provide a reproduce.
