### ISSUE TITLE
A wild defineComponent() Warning appears!

### ISSUE THREAD

**Issue by Filipe-Rodrigues** [johnsoncodehk/volar#1291]
I'm following a video tutorial to get started into Vue.js, and everything was fun and games until a few hours ago, when this warning became appearing all over my files that features a "export default {" entry:

[{
	"resource": "/c:/Users/kasin/Documents/Extra/VueJS/hakurei-asobi/src/components/Task.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Component options are wraped by `defineComponent()` internally to support intellisense on IDE for backward compatible, but this is an hacking which lead to this component type inconsistent with same script code on .js / .ts. Recommended wrap component options by `Vue.extends()` or `defineComponent()`. Or you can configure `\"experimentalShamefullySupportOptionsApi\": true / false` in `\"vueCompilerOptions\"` property in tsconfig / jsconfig to disable this warning.",
	"source": "volar",
	"startLineNumber": 6,
	"startColumn": 16,
	"endLineNumber": 6,
	"endColumn": 16
}]

Here's a screenshot of the VSCode screen:

![image](https://user-images.githubusercontent.com/28969294/167785966-07ca07e6-dccb-4737-8ff8-dc56a233beb5.png)

I don't know whether this is easily reproducible or not, I just created the simplest vue project, without even TypeScript suport in the options (I guess), so if anyone need more info, just let me know to help you help me.

**Comment by Garmagon** [comment]
I honestly don't know why would volar add a default option like this. This is instantly confusing, suddenly all the components was showing warnings and it took me a bit until I understood what is the problem. Also the option name is kinda offensive I guess, because why would it be shamefull to support Options API? New vue developers start with Options API, its in all the courses on the internet.

**Comment by MarekOravec** [comment]
Same issue for me, I installed Vue and this warning appears... Any solutions ? I have pure Vue 2 with vuetify plugin

**Comment by mcrapts** [comment]
This is terrible. Volar is the official recommended extension for VS Code + Vue 3. Volar is literally shaming the Options API, which is fully supported syntax. This error should not appear!

**Comment by wuguocai2000** [comment]
You can try to use vetur and turn off volar，and then restart vscode

**Comment by souadbarabad** [comment]
> 

how can i turn off volar pls

**Comment by souadbarabad** [comment]
> You can try to use vetur and turn off volar，and then restart vscode

Thank u it works !!

**Comment by Filipe-Rodrigues** [comment]
It also mitigates the warning by adding the following property in your jsconfig.json:

"vueCompilerOptions": {
    "experimentalShamefullySupportOptionsApi": true
  }

I don't know why we should get this warning by default, since it seems to be some kind of internal API issue (at least for me), and not something wrong with my code. Was there a change on Vue standards that I don't know of?

**Comment by johnsoncodehk** [comment]
Sorry for the misnomer, I just realized that "Shamefully support options API"  is incorrect meaning.

Volar cannot support intellisense for component options without `defineComponent()` / `Vue.extend()`, so Volar have to wrapped component options by `defineComponent()` internally with this option. But of course this is not shameful. I think this case is similar to the trade-off of pnpm hoist packages, so I reference to `--shamefully-hoist` option of pnpm to named the option.

This option is default enabled with warning in 0.34.12 to backward compatible for projects that migrate from Vetur. I will rollback to default disable and fix option words in next version.

**Comment by mrleblanc101** [comment]
I have this error in a Nuxt2/Vue2 projet.
Also I don't have a jsconfig or tsconfig file, why can't I disable this in the Volar VS Code settings ?

**Comment by Jorgehn1995** [comment]
> I have this error in a Nuxt2/Vue2 projet.

Any solution por nuxt2/vue2?

**Comment by johnsoncodehk** [comment]
@mrleblanc101 Warning has been removed, please update to v0.34.14.
