### ISSUE TITLE
volar.action.splitEditors splits only in two

### ISSUE THREAD

**Issue by crystalfp** [johnsoncodehk/volar#1293]
Despite the definition "Split \<script>,\<template>,\<style> Editors" `volar.action.splitEditors` creates only two windows:

- One with `template` collapsed
- One with `script` and `style` collapsed

I was expecting three views with only one section not collapsed each.
Wrong expectation or I'm missing something?

Thanks!\
mario

**Comment by johnsoncodehk** [comment]
Duplicate of #755
