### ISSUE TITLE
Vue-Volar - hight CPU usage on OSX

### ISSUE THREAD

**Issue by sneila** [johnsoncodehk/volar#1295]
Hi, my VSCODE, after the last update was overheating my Macbook Pro 2019, the fans run havok!.
Initially i thought that Electron/Vscode has something to do. 

But once i verified it under the Process Explorer (Vscode), i realised that Volar used 200+ CPU time. 

Open Vscode, and a VUE project with VOLAR enabled and it just starts the CPU usage 150%+ on my Mac, without cooling down.

**Comment by IIFelix** [comment]
Have you tried TakeOverMode ? https://github.com/johnsoncodehk/volar/discussions/471
Could maybe help.

**Comment by johnsoncodehk** [comment]
Hi @sneila, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? Will be helpful if you can provide a repro case.

**Comment by johnsoncodehk** [comment]
You can increase `volar.diagnostics.delay` in 0.38.6 to reduce CPU usage on typing.
