### ISSUE TITLE
Intellisense not working in template when not using "script setup"

### ISSUE THREAD

**Issue by enodr** [johnsoncodehk/volar#1298]
Hi,

I have noticed that Intellisense is not working in template under two conditions:
- if the component doesn't have a <script setup></script> part but only <script></script>

with script setup (even if empty):
![image](https://user-images.githubusercontent.com/10436257/168109987-1047655d-6640-4237-a436-89c7e85abe49.png)

without script setup:
![image](https://user-images.githubusercontent.com/10436257/168110145-75eb9182-7a55-4840-bb40-bf9a9bc13bbc.png)

- if the component has a <script setup></script> part but props are defined then Intellisense stops working inside the template:

![image](https://user-images.githubusercontent.com/10436257/168110556-60a95542-5679-4449-8b30-3b12d2d982ac.png)

**Comment by johnsoncodehk** [comment]
This is expected, Volar intellisense supports base on defineComponent, if you don't have, you can use `experimentalImplicitWrapComponentOptionsWithDefineComponent` option to tell Volar auto wrap component options by `defineComponent`.

`tsconfig.json` / `jsconfig.json`
```jsonc
{
  "compilerOptions": {
    // ...
  },
  "vueCompilerOptions": {
    "experimentalImplicitWrapComponentOptionsWithDefineComponent": true
  },
  "include": ["src/**/*.js", "src/**/*.ts", "src/**/*.d.ts", "src/**/*.vue"]
}
```

**Comment by VincentDream** [comment]
组件中，props不使用defineProps的形式还是会出现这个问题

**Comment by Dazaer** [comment]
The suggested solution by @johnsoncodehk is deprecated, and even though this is old I am still getting this issue.

The solution is to have both `data` option and a script with setup: https://github.com/vuejs/core/issues/9296#issuecomment-2074595734
