### ISSUE TITLE
v-else-if null checks not working correctly

### ISSUE THREAD

**Issue by MattAG** [johnsoncodehk/volar#130]
This code produces an "Object is possibly 'null'" error on _person.name_.

![image](https://user-images.githubusercontent.com/16511389/114059184-03b57880-988c-11eb-8f54-ad88a3961bba.png)

Changing it to use v-if resolves this error:

![image](https://user-images.githubusercontent.com/16511389/114059250-18920c00-988c-11eb-906d-04098c2add09.png)

A simple app showing this is attached.
[v-else-if-error.zip](https://github.com/johnsoncodehk/volar/files/6279918/v-else-if-error.zip)

**Comment by johnsoncodehk** [comment]
Fixed in 0.23.6, thanks for your report!

**Comment by johnsoncodehk** [comment]
@romain20100 I can't reproduce this problem, if you still get this error please open a new issue.
