### ISSUE TITLE
Language Features Server server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by yangzhenfeng1994** [johnsoncodehk/volar#1300]
![image](https://user-images.githubusercontent.com/29218855/168241006-f9627c3e-4154-4dd5-96ed-b1a3439f4c14.png)
more infomation
![image](https://user-images.githubusercontent.com/29218855/168241343-1e5ab712-61eb-4774-bd8a-fa856e254e3a.png)
os info
![image](https://user-images.githubusercontent.com/29218855/168241563-c5b9168e-a5dd-45fe-ba98-1971d9842604.png)
vscode version 
![image](https://user-images.githubusercontent.com/29218855/168241721-a655f03a-8332-41fb-b6c9-ae82a652c4c7.png)

**Comment by timoransky** [comment]
Hey! Same thing happens to me since yesterday. I tried to uninstall Volar but did not have any luck 😞

**Comment by artmizu** [comment]
also happens to me, maybe issue related with this message? 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/12496464/168422964-4b1a1971-9e54-4d0d-9305-2a835a702357.png">

**Comment by artmizu** [comment]
yesterday the [johnsoncodehk/volar](https://www.changelogs.md/github/johnsoncodehk/volar) receive update [0.34.14](https://github.com/johnsoncodehk/volar/releases/tag/v0.34.14) maybe it also relate

**Comment by artmizu** [comment]
Volar VSCode extension has a «Max Old Space Size» setting and description said it may help, but it doesn't work for me 
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/12496464/168423440-ffda3142-09ed-4ef5-beb0-fd6c42ae4b7b.png">

**Comment by artmizu** [comment]
rollback to any older version also not helped
<img width="745" alt="image" src="https://user-images.githubusercontent.com/12496464/168423864-6959b5ec-844d-4b9b-8bc4-29b156805f00.png">

**Comment by johnsoncodehk** [comment]
Hi @yangzhenfeng1994, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by artmizu** [comment]
i found the reason of a issue. Lets look at the piece of code:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/12496464/168489958-04a11ffc-496a-4596-8f2d-42a07c7e2c6d.png">

it produce the error and vue server will crash. but if i change "constructor" to something else, for example to "block", everything works fine. so reason of a issue in "constructor" class name.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/12496464/168490033-97914aa1-8dd1-4fed-827f-460749904f45.png">

**Comment by benjaminpaul** [comment]
Just adding myself to this issue, I am currently experiencing the same issue.
Windows 11, V0.34.15

**Comment by webdo** [comment]
I also have the exact same issue as the one above, the server will crash as soon as it reach 512MB of ram used, even with Max Old Space Size set to 8GB.
The server is ran correctly with the --max-old-space-size set to 8096 from the settings:

`/root/.vscode-server-insiders/bin/9c29becfad5f68270b9b23efeafb147722c5feba/node --max-old-space-size=8096 /root/.vscode-server-insiders/extensions/vue.volar-0.34.15-linux-x64/server --node-ipc --clientProcessId=27123`

I'm not sure why it doesn't want to use more than 512mb of RAM.

**Comment by changk99** [comment]
I seem to have solved this problem, the error message is that the specific file cannot be requested, I used the scientific Internet(科学上网), and then it was fine

**Comment by TimothyKrell** [comment]
I am having this issue as well. Using typescript 4.7 causes the same error and crash. Using 4.6 works fine.

**Comment by adenvt** [comment]
I got same problem on TS 4.7, but no crash, just auto import and some autocomplete not work properly. Switch to 4.6 work normally.
