### ISSUE TITLE
Code hints for pinia disappeared !!!

### ISSUE THREAD

**Issue by ZhuHeart** [johnsoncodehk/volar#1301]
The v0.34.14 version of volar has no code hints for pinia.But the version before works.
![image](https://user-images.githubusercontent.com/49355255/168248442-8e524020-b394-4b89-a706-c22926a5ce02.png)

**Comment by maroon1** [comment]
MacOS 下直接死循环，内存占用激增到4G，然后爆栈挂掉

**Comment by IIFelix** [comment]
Code hints are working for me with v0.34.15.

@ZhuHeart 
Could you post your "LayoutsState" type? 
Normally you should not have to type the state of your store. Typescript infers that automatically.

**Comment by ZhuHeart** [comment]
> Code hints are working for me with v0.34.15.
> 
> @ZhuHeart Could you post your "LayoutsState" type? Normally you should not have to type the state of your store. Typescript infers that automatically.


Thanks for your response. ❤

I upgrade my _Volar_ to version v0.34.16 and _JavaScript and TypeScript Nightly_ to version v4.8.20220522 today. The code hinks are working now~~

Thanks all of you very much! ❤
