### ISSUE TITLE
Import autocomplete does not suggest components while typing the path

### ISSUE THREAD

**Issue by olivervorasai** [johnsoncodehk/volar#1304]
### Environment
```
Visual Studio 1.67.1 (cleared settings.json)
Volar 0.34.14 (no settings changed)
johnsoncodehk/volar-starter
```

### Describe the bug
While typing the `path` portion of an import, Volar does not suggest components. Although I am not sure if this is something that Volar isn't suppose to support.

#### Example 1
![image](https://user-images.githubusercontent.com/6283219/168319389-42b08285-d3d6-4125-bb67-33832001451d.png)
`App.vue` does not show up as a suggestion.

#### Example 2
![image](https://user-images.githubusercontent.com/6283219/168319519-a47ae795-053f-441b-ba9f-e76c7d16028d.png)
`HelloWorld.vue` does not show up as a suggestion.

### Other Notes
The autocomplete does work when typing the name portion of the component.
![image](https://user-images.githubusercontent.com/6283219/168319720-cccfda6b-62c6-4c55-b63d-aee93b5f6c2b.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter.

<img width="895" alt="螢幕截圖 2022-05-22 19 17 10" src="https://user-images.githubusercontent.com/16279759/169692548-4fe8717c-19f1-4f48-9e39-777157e91464.png">

Could you provide the vscode info by `Help: About` command?

**Comment by olivervorasai** [comment]
> Could you provide the vscode info by `Help: About` command?

```
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042
```

I wonder if this is a windows issue?

**Comment by the-tech-stack** [comment]
I am also facing same issue but in a JavaScript environment.
So, I also installed vetur to see if there is something wrong with my editor/environment.

This is the result with volar enabled (vetur disabled):
![volarEnabled](https://user-images.githubusercontent.com/95937042/170537359-5552335a-4a9b-423c-a315-f51be8ea7ca7.png)

This is the result with vetur enabled (volar disabled):
![veturEnabled](https://user-images.githubusercontent.com/95937042/170538145-ac4f7f73-55c7-4111-9a5a-ca17943a7716.png)

Here is my setup info:

- Version: 1.67.2 (user setup)
- Date: 2022-05-17T18:15:52.058Z
- Electron: 17.4.1
- Chromium: 98.0.4758.141
- Node.js: 16.13.0
- V8: 9.8.177.13-electron.0
- OS: Windows_NT x64 10.0.17763

**Comment by johnsoncodehk** [comment]
I'm assuming this is an issue on windows, will switch environments to check it out later.

**Comment by johnsoncodehk** [comment]
Just for record, maybe related to this line https://github.com/johnsoncodehk/volar/blob/a1830673f2a41f96abd3e4a2d5a16d16449c1c8b/packages/vue-typescript/src/typescriptRuntime.ts#L235.

**Comment by GentleSevenV** [comment]
that is still not working in Volar 0.38.5
