### ISSUE TITLE
Code prompt

### ISSUE THREAD

**Issue by xi98707228** [johnsoncodehk/volar#1315]
The code prompt for VsCode does not appear after installing this plug-in

Use this plugin

I waited a long time...

![image](https://user-images.githubusercontent.com/49353649/169245712-0f4d99ff-d566-45af-9e32-1a3de8afe897.png)

After disabling

![image](https://user-images.githubusercontent.com/49353649/169245975-7ec17836-9c56-4ccb-8557-0e5b5e10bc16.png)

**Comment by johnsoncodehk** [comment]
Hi @xi98707228, please provide repro case so I can check the problem, thanks.
