### ISSUE TITLE
Code highlighting not working correctly (0.34.15)

### ISSUE THREAD

**Issue by mityaua** [johnsoncodehk/volar#1316]
Ext Version | 0.34.15
VSC Version | 1.67.2

"vue": "^3.0.0",
"quasar": "^2.5.4",
SFC Composition API

Code highlighting in some components does not work correctly. There are no errors in the terminal.

![Screenshot 2022-05-19 161738](https://user-images.githubusercontent.com/20481332/169303840-52218fdf-ae68-4365-a394-9115b00593bd.png)

Restarting VSC and reinstalling ext doesn't help.

**Comment by johnsoncodehk** [comment]
Hi @mityaua, please provide minimal reproduction code so I can check the problem, thanks.
