### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by IIFelix** [johnsoncodehk/volar#1319]
Right now there is no website with documentation available for Volar as far as i can see.
You have to check the README files for docs. I think it would help a lot if there's a website for volar
similiar to vetur's website: https://vuejs.github.io/vetur/

Is there already a plan for a website or do you want me to look into this? @johnsoncodehk

**Comment by IIFelix** [comment]
First version is comitted - https://github.com/johnsoncodehk/volar/pull/1513

**Comment by joshgrift** [comment]
How do we access the documentation?

**Comment by IIFelix** [comment]
Wanted to finish the last 2 pages before deploying it on GitHub pages.
Docs should be accessible in a few days 👍

**Comment by johnsoncodehk** [comment]
@joshgrift Sorry may take more 1~2 weeks. 😅
