### ISSUE TITLE
declare global { ... } in a Vue component file has error "Cannot redeclare block-scoped variable"

### ISSUE THREAD

**Issue by Keavon** [johnsoncodehk/volar#1321]
I am using the solution described in #596.

```ts
// Satisfies Volar (https://github.com/johnsoncodehk/volar/issues/596)
declare global {
	const MENU_LIST_ENTRY: MenuListEntry;
}
```

In my HTML section:
```vue
<MenuList
	...
	@update:activeEntry="(newActiveEntry: typeof MENU_LIST_ENTRY) => activeEntryChanged(newActiveEntry)"
	...
/>
```
([my file](https://github.com/GraphiteEditor/Graphite/blob/master/frontend/src/components/widgets/inputs/DropdownInput.vue))

But I get this error:
```
const MENU_LIST_ENTRY: MenuListEntry<string>
Cannot redeclare block-scoped variable 'MENU_LIST_ENTRY'. ts(2451)
DropdownInput.vue(97, 8): 'MENU_LIST_ENTRY' was also declared here.
```

![image](https://user-images.githubusercontent.com/4388688/169457258-9f5354d2-da7e-4a92-b90c-4c9a15d3de2a.png)

I believe this wasn't an issue several months ago when I initially wrote this code, but more recently (in the past few months) it seems to have cropped up. Perhaps a regression in Volar?

**Comment by johnsoncodehk** [comment]
Fixed in 0.40.0.
