### ISSUE TITLE
Emmet Multiplication

### ISSUE THREAD

**Issue by kalenmike** [johnsoncodehk/volar#1322]
Emmet multiplication is not working in the template section of .vue files. Everything else seems to be working fine. But as soon as I press * the Emmet snippet disappears and autocomplete does not work.
Works:
`.test>.child`
```
<div class="test">
    <div class="child"></div>
</div>
```
Fails:
`.test>.child*4  `
```
.test>.child*4  
```

The snippets work fine with Volar disabled and Vetur running. Disabling Vetur and using Volar causes it to break. Tested after reloading.

Vue Language Features (Volar) v0.34.15
Visual Studio Code 1.67.2 (Linux x64 5.11.0-37-generic)

**Comment by abitwhy** [comment]
It is related to #716, which has a solution.
