### ISSUE TITLE
Path aliases in tsconfig don't work with vue-tsc

### ISSUE THREAD

**Issue by Darkzarich** [johnsoncodehk/volar#1323]
Hello

I have the following in my tsconfig.json : 

```json
{
    "paths": {
      "@/*": ["./src/*"],
      "@@/*" : ["./*"],
      "@public/*" : ["./public/*"],
    },
}
```

When I just run 

```
vue-tsc --noEmit --skipLibCheck
```

It works just fine

but I use Husky git hooks to check staged files defined like that

```
"lint-staged": {
    "*.{vue,ts,tsx}": [
	"vue-tsc --noEmit --skipLibCheck"
    ]
},
```

When I do `git add .` & `git commit` it checks the staged files and fails with the following error:

```
error TS2307: Cannot find module '@/entities/revision' or its corresponding type declarations.
error TS2307: Cannot find module '@/entities/user' or its corresponding type declarations.
error TS2307: Cannot find module '@/shared/api' or its corresponding type declarations.
error TS2307: Cannot find module '@/shared/lib/errors' or its corresponding type declarations.
error TS2307: Cannot find module '@/shared/ui' or its corresponding type declarations.
```

It seems that my path aliases are not recognized in this check

**Comment by littledot** [comment]
Your `tsconfig.baseUrl` is missing

https://www.typescriptlang.org/tsconfig#paths

**Comment by Darkzarich** [comment]
> Your `tsconfig.baseUrl` is missing
> 
> https://www.typescriptlang.org/tsconfig#paths

I didn't provide the full content of `tsconfig`, here it is

```json
{
  "compilerOptions": {
    "strict": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "checkJs": false,
    "sourceMap": true,
    "module": "ESNext",
    "target": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "jsx": "preserve",
    "noImplicitThis": true,
    "importHelpers": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "@@/*" : ["./*"],
      "@public/*" : ["./public/*"],
    },
    "outDir": "./built"
  },
}
```

**Comment by johnsoncodehk** [comment]
Hi @Darkzarich, I think this is not vue-tsc issue because it do not occur in execute `vue-tsc --noEmit --skipLibCheck` directly. I have no experience with Husky git hooks, but if you can provide repro case I may able to found out the problem.

**Comment by johnsoncodehk** [comment]
Not sure it helps, but you could check https://github.com/sethidden/vue3-eslint-stylelint-demo.

**Comment by mockingjet** [comment]
same problem here, any workaorund please?

**Comment by aparajita** [comment]
Same here. It isn't working from the command line.

**Comment by pencilcheck** [comment]
include + baseUrl are needed in addition to paths

**Comment by TrueMoein** [comment]
+1 same issue.

**Comment by aurium** [comment]
+1 same issue.

**Comment by 91khr** [comment]
It's illustrated in [this StackOverflow answer](https://stackoverflow.com/questions/44676944/how-to-compile-a-specific-file-with-tsc-using-the-paths-compiler-option) that tsc (and maybe vue-tsc) doesn't respect `tsconfig.json` when an input file is specified from arguments, and in this case, all compiler options must be specified with arguments.

A workaround is also suggested in the SO answer: create a file like this, and use it as vue-tsc project file:

```json
{
  "extends": "./tsconfig.json",
  "include": [
      "src/root/index.ts"
  ]
}
```
