### ISSUE TITLE
Support JSDoc for script setup

### ISSUE THREAD

**Issue by xiaoxiangmoe** [johnsoncodehk/volar#1327]
```vue
<script setup lang="ts">
import Vue from 'vue';
console.log(Vue);
</script>
<script lang="ts">
/** JSDoc for component */
export default {};
</script>
```

The generated virtual file is:

```ts
/** JSDoc for component */


import Vue from 'vue';
export default await (async () => {
console.log(Vue);
// @ts-ignore
return (await import('vue')).defineComponent({
...({}),
setup() {
() => {
};
return {
};
},
});
})();
```

JSDoc for export default move into wrong place

**Comment by kamenkolev-shared** [comment]
I'm not sure why this was closed, but it doesn't seem to work.

Tested with:
Volar 1.0.9
Typescript 4.8.4

Default setup as shown in [Getting Started](https://vuejs.org/guide/quick-start.html#creating-a-vue-application)

![image](https://user-images.githubusercontent.com/57657834/200169267-a3a700dc-4d9f-44dc-b352-c1db4c44e92d.png)

**Comment by johnsoncodehk** [comment]
@kamenkolev-shared this is different issue and fixed by https://github.com/johnsoncodehk/volar/commit/04863b016bc672617acdc98ad34274be8be5e814
