### ISSUE TITLE
Extension fails to find tsconfig.json when vue file is in a subdirectory.

### ISSUE THREAD

**Issue by adamrybak** [johnsoncodehk/volar#1331]
Extension fails to find tsconfig.json when vue file is in a subdirectory.

Example: src/views/ViewTest.vue
Typescript config is loaded and vscode is providing the correct errors in the code.
![image](https://user-images.githubusercontent.com/32214327/169731594-2fb0dfb7-92a9-4a53-af25-b63a86ff930e.png)
![image](https://user-images.githubusercontent.com/32214327/169731743-07253b30-d87b-4cc4-a360-43e902b8688f.png)

Example: src/views/hello/ViewItem.vue
Typescript config is not loaded and vscode is not providing the errors that I am expecting.
![image](https://user-images.githubusercontent.com/32214327/169731710-8101672d-9b37-4adb-b619-ba84feb3ca25.png)
![image](https://user-images.githubusercontent.com/32214327/169731759-54084f19-d525-45ac-be8c-234220714a9d.png)

**Comment by johnsoncodehk** [comment]
Please make sure the tsconfig included vue files in `src/views/hello` correctly, you can reference https://github.com/johnsoncodehk/volar-starter/blob/master/tsconfig.json#L15.

If you can't make it works please provide a repro case.
