### ISSUE TITLE
[Feature Request] Support using nightly TypeScript

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#1332]
As we know, there is an extension [JavaScript and TypeScript Nightly](https://github.com/microsoft/vscode-typescript-next) which enables the nightly build of TypeScript (typescript@next) as VS Code's built-in TypeScript version used to power JavaScript and TypeScript IntelliSense.

![image](https://user-images.githubusercontent.com/41773861/169733077-a520b0d3-990e-4694-beee-dbdc341c8551.png)

But now volar only support toggle typescript version between builtin and workspace version:

![image](https://user-images.githubusercontent.com/41773861/169733033-579ad042-0951-4442-ae4e-4274bc57ea10.png)

It would be helpful to support using the nightly typescript version. For example, I can using the latest `got to source definition` function comes with the latest typescript.

![image](https://user-images.githubusercontent.com/41773861/169733265-b3b7bbff-5f6e-4ab0-b58d-2bcfecd3e838.png)

**Comment by tjx666** [comment]
Seems not work in latest version. @johnsoncodehk

**Comment by johnsoncodehk** [comment]
@tjx666 What behavior are you expecting and it doesn't work?

**Comment by tjx666** [comment]
For TS project, I can easily toggle to ts4.8 with extension: [JavaScript and TypeScript Nightly](https://github.com/microsoft/vscode-typescript-next).


https://user-images.githubusercontent.com/41773861/179938524-9a10443c-5fcc-4f23-b435-72fe6a1d48c1.mov

But volar can only select 4.7:

![image](https://user-images.githubusercontent.com/41773861/179938978-60709f8b-f34c-470d-ba1d-89dcf2636950.png)

**Comment by tjx666** [comment]
@johnsoncodehk So, how can I easily toggle ts version to 4.8. Seems I have to install 4.8 as dependency now.

**Comment by yaegassy** [comment]
@tjx666 This "JavaScript and TypeScript Nightly" extention goes into the extension folder installed by the user.

Try setting `typescript.tsdk` in `.vscode/settings.json`. This is an example of my environment.

```jsonc
{
  "typescript.tsdk": "/Users/yaegassy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.8.20220719/node_modules/typescript/lib",
}
```

You will probably see more items available for selection in "Use Workspace Version". Perhaps, but it is also 
possible to use typescript/lib installed at an arbitrary location.

<img width="940" alt="volar-issue-1332-1" src="https://user-images.githubusercontent.com/188642/179949763-8c3bd470-1df4-40f1-ad02-255deaab9180.png">

**Comment by tjx666** [comment]
I think volar can search the folder `/Users/yaegassy/.vscode/extensions/ms-vscode.vscode-typescript-next-xxx/node_modules/typescript/lib` and provide it in pick list.

 [JavaScript and TypeScript Nightly](https://github.com/microsoft/vscode-typescript-next) is the official recommend extension to using the latest typescript.

**Comment by yaegassy** [comment]
@tjx666 Are there any other VSCode extensions that support this?

**Comment by yaegassy** [comment]
If you are a user with a high technical level who uses TypeScript's Nightly, setting up `typescript.tsdk` is very very easy task. :)

`typescript.tsdk` can handle this, but if you need the feature you want ASAP, you may want to create a pull request.

I think this is the related code. (and there may be others)

- https://github.com/johnsoncodehk/volar/blob/master/extensions/vscode-vue-language-features/src/features/tsVersion.ts
- https://github.com/johnsoncodehk/volar/blob/master/packages/shared/src/ts_node.ts

**Comment by johnsoncodehk** [comment]
Reference: https://github.com/microsoft/vscode/blob/8559324b0988ffac5cd6a1af35b77d279c927545/extensions/typescript-language-features/src/tsServer/versionProvider.electron.ts#L77

**Comment by tjx666** [comment]
Ok, I will try to implement this and make a pr this weekend

**Comment by tjx666** [comment]
@johnsoncodehk @yaegassy any way to get currrent used ts version?

using `clients[0].clientOptions.initializationOptions.typescript` ?
