### ISSUE TITLE
Missing Nuxt types in Vue 2 + Nuxt + Options API project

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#1337]
I've set up a project at https://github.com/rchl/volar-vue2-test where the `pages/index.vue` is using Nuxt-specific `asyncData` component option. The argument to that option is Nuxt Context:

```js
  async asyncData(context) {
    context.redirect('https://google.com');
  },
```

The issue is that `context` is not typed.

`@nuxt/types`, which extends component types, is included in `tsconfig.json` `types` array and also the following volar-specific options are enabled:

```js
  "vueCompilerOptions": {
    "experimentalCompatMode": 2,
    "experimentalImplicitWrapComponentOptionsWithDefineComponent": true,
    "experimentalTemplateCompilerOptions": {
      "compatConfig": { "MODE": 2 } // optional
    }
  }
```

and also:

```js
  "compilerOptions": {
    "jsx": "preserve",
  },
```

**Comment by johnsoncodehk** [comment]
Pleaes use `experimentalImplicitWrapComponentOptionsWithVue2Extend` instead of in v0.38.6.

```json
  "vueCompilerOptions": {
    "target": 2,
    "experimentalImplicitWrapComponentOptionsWithVue2Extend": true
  }
```
