### ISSUE TITLE
Error: Connection got disposed

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#1339]
After I type global component, the extebsion crashed.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/41773861/169867956-4453010f-faba-4c9a-a8cf-29cd31acb3a3.png">

- Vue: 2.6.11
- volar-typescript: 4.7.1-rc
- MacOS: 12.3.1
- VSCode: 1.68.0-insider

**Comment by johnsoncodehk** [comment]
Fixed by #1360.
