### ISSUE TITLE
VS Code states that the extension is not available in the marketplace

### ISSUE THREAD

**Issue by murugappanrm** [johnsoncodehk/volar#1346]
Whenever i load up vs code i get this message that states the Volar is not available in the marketplace. What does this mean? 

![Screenshot_5](https://user-images.githubusercontent.com/63133893/170133707-e131bc8f-6c57-4b10-961c-faea304070b3.png)

**Comment by zardoy** [comment]
https://github.com/johnsoncodehk/volar/issues/1124#issuecomment-1123312339
