### ISSUE TITLE
To enable syntax highlighting  for SFC custom block 

### ISSUE THREAD

**Issue by moliu666** [johnsoncodehk/volar#1347]
How to  enable syntax highlighting  for SFC custom block 

like [Vetur's Custom Code Blocks](https://vuejs.github.io/vetur/highlighting.html#custom-block)

**Comment by johnsoncodehk** [comment]
You can use `lang` attribute to specify any language for custom block like `<foo lang="md">...</foo>`.

**Comment by johnsoncodehk** [comment]
Duplicate of #127
