### ISSUE TITLE
Emmet abbreviation is working incorrectly

### ISSUE THREAD

**Issue by cunc** [johnsoncodehk/volar#135]
https://user-images.githubusercontent.com/43318850/114338684-272b3c80-9b86-11eb-8f5c-0a42688cef58.mov

As above, sometimes emmet is no effect when typing letters, but Vetur is OK.

VS Code version: 1.55.1
Volar version: 0.23.7

**Comment by oliverzy** [comment]
![image](https://user-images.githubusercontent.com/1321817/114347880-4af77e00-9b98-11eb-9487-8d72b4a5bae9.png)
Looks like a regression.
The div tag in vue template reports an error. I never see such kind of error before.

**Comment by johnsoncodehk** [comment]
@oliverzy I can't check it without reproduce, please provide a repro case in new issue, thanks.

**Comment by johnsoncodehk** [comment]
Fixed in 0.24.0, thanks for your report!
