### ISSUE TITLE
vue2: no error will be reported with nonexistent data.Type is unknown

### ISSUE THREAD

**Issue by hexf00** [johnsoncodehk/volar#1350]
![Snipaste_2022-05-26_00-59-22](https://user-images.githubusercontent.com/9587872/170319833-21c82c17-dfbe-4a8c-8540-42d985a36a1e.png)

I use https://github.com/johnsoncodehk/volar-starter  vue2 branch.

I propose this issue because the Class API  or  Vue.extend  performs better. 

I don't understand how this difference is caused.

ts version:4.6.3 / 4.5.5
vscode version: 1.67.2
volar version: v0.34.16

Volar is doing very nice. I like volar. Thank you for your efforts and hope it can be better.

p.s I have been experiencing 5-minute crashes mentioned by other issues. I always restart vscode. I hope I can help you with this problem, but I don't know what I should do?

![Snipaste_2022-05-26_01-07-37](https://user-images.githubusercontent.com/9587872/170320884-57dab79f-b527-4217-abef-6fc3cf37ce43.png)

**Comment by johnsoncodehk** [comment]
This is `@vue/composition-api` behavior from https://github.com/vuejs/composition-api/blob/032f2c75992043a02a61e05d5f1493d78738ae72/src/component/common.ts#L1.
