### ISSUE TITLE
Vue 2 cannot assert type in template

### ISSUE THREAD

**Issue by jaredmcateer** [johnsoncodehk/volar#1354]
## Minimal test case

https://github.com/jaredmcateer/vue2-volar-type-error

## Issue explanation

When passing an object with a variable key to `:checked` on an input element I am getting a type error where the types might not align. 
I've tried various ways of calming the error but have not found an ideal solution.

![image](https://user-images.githubusercontent.com/781540/170518020-42ed6db8-db74-44bd-a10e-2ca0bb701647.png)

```vue
<script lang="ts">
import { defineComponent, PropType } from "@vue/composition-api";

export default defineComponent({
  props: {
    features: { type: Object as PropType<Record<string, string | boolean>>, required: true }
  },
  data() {
    return {
      feature: 'foo',
    };
  },
});
</script>
```

```vue
<template>
  <div>
    <h2>Error in ide</h2>
      <label>Checkbox <input
        type="checkbox"
        :checked="features[feature]"
        ^------- Type 'string | boolean' is not assignable to type 'any[] | Booleanish | Set<any> | undefined'
      />
     </label>
  </div>
</template>
```

I tried changing the line to `:checked="(feature[feature] as boolean)"` which calms the error in the IDE but is a runtime error (unexpected token)

![image](https://user-images.githubusercontent.com/781540/170519605-79fadf65-1c74-4897-ab34-7cdcffad6416.png)

Other things I've tried is adding:

`v-if="typeof features[feature] === 'boolean'"`

and

adding a method that has a type predicate

```ts
methods: 
  isBoolean(feature: any): feature is boolean {
    return typeof features[feature] === 'boolean';
  }
}
```

with

`v-if="isBoolean(features[feature])`

But these do not work. However if I try them with accessing the property directly such as:

```ts
<label>Checkbox <input
  type="checkbox"
  v-if="isBoolean(features.foo)"
  :checked="features.foo"
  />
</label>
```
Then it works (but doesn't for my real world usage)

**Comment by hexf00** [comment]
It seems that your error prompt is not caused by volar, your ide type derivation works correctly.
but I found that type assertion syntax(`as xxxx`) cannot be used in templat in vue2. I think this is related to the compiler used in vue2.

I think the reason why your last code can work is that TS has a feature that context judgment can narrow the range of types.

Maybe you can try,it works well with me

```
<input  type="checkbox"  :checked="isBoolean(features[feature])"  />
```

**Comment by jaredmcateer** [comment]
Technically that would work but `:checked="typeof features[feature] === 'boolean'"` isn't the same as `:checked="features[feature]"`. But from what you're saying my only solution would be to use a method with a boolean return type.

**Comment by johnsoncodehk** [comment]
Hi @jaredmcateer, please try

```diff
<script lang="ts">
import { defineComponent, PropType } from "@vue/composition-api";

export default defineComponent({
  props: {
-    features: { type: Object as PropType<Record<string, string | boolean>>, required: true }
+    features: { type: Object as PropType<Record<string, 'true' | 'false' | boolean>>, required: true }
  },
  data() {
    return {
      feature: 'foo',
    };
  },
});
</script>
```
