### ISSUE TITLE
Vue 2 errors accessing scoped properties in slots

### ISSUE THREAD

**Issue by jaredmcateer** [johnsoncodehk/volar#1355]
## Minimal Test Case

https://github.com/jaredmcateer/vue2-volar-type-error

## Explanation

```vue
  <SlotComponent>
    <template v-slot="props"><span>{{ props.value }}</span> </template>
    <template #oneThing="props"><span>{{ props.value }}</span> </template>
  </SlotComponent>
```

Trying to access scope properties of a slot in Vue 2 results in an error `Property 'value' does not exist on type 'VNode[]'... ts(2551)`

in https://github.com/johnsoncodehk/volar/issues/439 the workaround appears to be to assert the scoped property to a type (`#oneThing="props as MyProp"`) but in Vue 2 trying to do that will result in an `Unexpected token` error at compile time.

**Comment by hexf00** [comment]
see https://github.com/johnsoncodehk/volar/issues/1354#issuecomment-1139321368

and you nee read document chapter "Setup for Vue 2", add package and config

https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features

**Comment by jaredmcateer** [comment]
I've read the documentation and followed it as best I can, do you think I've missed something?
