### ISSUE TITLE
Vue2 with @vue/composition-api causes error

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#136]
![image](https://user-images.githubusercontent.com/1321817/114349327-551a7c00-9b9a-11eb-96be-caf0bf8b5ae7.png)

It's a Vue2 project with @vue/runtime-dom installed already.

If I use `export default {}`, the error will disappear.

**Comment by johnsoncodehk** [comment]
@oliverzy this is `@vue/composition-api` problem, you need to return something in `setup()`, otherwise the component instance types is `never`.
