### ISSUE TITLE
[Regression] False positive type check for method arguments with `defineExpose`

### ISSUE THREAD

**Issue by ahnpnl** [johnsoncodehk/volar#1364]
### Summary

`vue-tsc` shows false positive type check for this piece of codes
```
<script setup lang="ts">

interface Bar {
    foo(bar: string): void;
}

defineExpose<Bar>({
    foo(bar) {
        console.log('foo', bar);
    }
})
</script>
```

The error is `error TS7006: Parameter 'bar' implicitly has an 'any' type.`

This bug happens since **0.34.15**+

### Reproduce repo

- Check out https://github.com/ahnpnl/volar-starter-vite/tree/bug/args-type-define-expose (branch `args-type-define-expose`)
- Install deps with `yarn`
- Run `yarn type-check`

### Expectation

The error should not be there.

**Comment by Tarrowren** [comment]
I've found that I still have this bug on 1.8.16, and the version of vue I'm using now is 2.7.14

**Comment by so1ve** [comment]
@Tarrowren Open a new issue.
