### ISSUE TITLE
The code intelligence prompt appears twice in .ts file

### ISSUE THREAD

**Issue by liamwang** [johnsoncodehk/volar#1366]
After the Volar VS Code extension was enabled, the code intelligence prompt appears twice in `.ts` file. 

It seems to be a conflict with VS Code itself.

![image](https://user-images.githubusercontent.com/5000396/170980893-4103d1cf-ae75-43f1-aaed-3e4804ace232.png)

**Comment by johnsoncodehk** [comment]
Duplicate of #1063
