### ISSUE TITLE
Nuxt 2 is missing (I think) a few components

### ISSUE THREAD

**Issue by szulcus** [johnsoncodehk/volar#1368]
A temporary solution for me is to create global types in `components.d.ts`, but it's nice if elements like `<nuxt />` or `<nuxt-link />` are added like `<transition />` tag.
![image](https://user-images.githubusercontent.com/48328739/171139000-a3c21913-d8a7-460b-a164-76fce9d15a8d.png)
![image](https://user-images.githubusercontent.com/48328739/171139011-c242a135-3ea2-4fac-9890-ee608e87b4d5.png)
![image](https://user-images.githubusercontent.com/48328739/171139136-f446f2af-847c-4790-9a3f-f43d73881a71.png)

**Comment by johnsoncodehk** [comment]
We will not built-in support Nuxt tag, but you could send feature request to Nuxt for add GlobalComponent type to library, or use https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/vetur.

**Comment by iamandrewluca** [comment]
You can add this in a `*.d.ts` for some completion

Nuxt 2 + Vue 2.7

```ts
declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		NuxtLink: ReturnType<typeof import('vue')['defineComponent']>;
		ClientOnly: ReturnType<typeof import('vue')['defineComponent']>;
		NuxtPicture: ReturnType<typeof import('vue')['defineComponent']>;
		// ...
	}
}
```
