### ISSUE TITLE
How to solve Object is possibly 'undefined' errors without optional chaining

### ISSUE THREAD

**Issue by tom-richter** [johnsoncodehk/volar#137]
Since optional chaining and nullish coalescing not being supported in vue 2 templates I wonder what to do with possibly undefined values like this `{{ tags.get(question.tagId).name }}` which gives me the error `Object is possibly 'undefined'`. Is there a possibility to solve this in the template or do have to use a getter in the script part of the component?

**Comment by johnsoncodehk** [comment]
Actually I'm not sure, you could try to ask in official typescript channel:  https://discord.com/channels/325477692906536972/331999220125138944

**Comment by johnsoncodehk** [comment]
@tom-richter maybe you can do this `{{ (tags.get(question.tagId) || {}).name }}`.
