### ISSUE TITLE
--extendedDiagnostics and --generateTrace do not work

### ISSUE THREAD

**Issue by blake-newman** [johnsoncodehk/volar#1375]
The following tooling is useful for [diagnosing TypeScript performance issues](https://github.com/microsoft/TypeScript/wiki/Performance#extendeddiagnostics) in applications. 

Reports of slow IDE experiences may not be directly due to Volar but underlying poor preforming hot code in applications. In our case we have a very large project and have always suffered performance issues. Volar doesn't seem to respond well; likely due to it now generating more typing for vue files. 

I don't want to create yet another issue about bad performance with Volar; because it may not be due to Volar itself but underlying poor performance in application code. 

The ability to use this tooling will help users (and ourselves) be able to triage performance issues before blaming the tooling; however the methods to triage performance issues do not work.

I've taken a look myself into why `vue-tsc` is not reporting on diagnostics; but i've not yet found any resolutions as to why this may be.   

## Extended Diagnostics
```
yarn vue-tsc --extendedDiagnostics

Files:                         7102
...
Types:                           80 <--
Instantiations:                   0 <--
...
```

```
yarn tsc --extendedDiagnostics

Files:                        3203
...
Types:                      293160
Instantiations:             661562
...
```

As you can see with `vue-tsc` the extended diagnostics is reporting more files checked (which makes sense as this would be the vue files), but the types and instantiations are basically no longer being reported.

## Trace Generation 

```
yarn vue-tsc --generateTrace trace

/home/blake/work/attest-maker-fe/node_modules/typescript/lib/tsc.js:2099
            throw e;
            ^

Error: Debug Failure. False expression.
```

This error appears because the trace information is empty; which is not expected. Which indicates tracing and diagnostic information is bailing out. 

----

Removing the generated code for VLS, which causes diagnostic errors (we use TSX and vue 2 so it isn't required to be generated in our scenario). These errors are filtered out but I was curious if that caused bail out of counting and tracing type information. After removing all diagnostic errors from generated code it still fails; so this tells me that the issue is not directly related to the generated code.

**Comment by blake-newman** [comment]
So from what i can tell the issue is due to the following:

There are many outputs in `typescript`. When tracing the `tracingEnabled.stopTracing` method is called within `tsc.js`

The diagnostics and information is captured in `tsserverlibrary.js`, and the `tracing` logic is called via `tsc.js`. Which is why the information is empty. 

I'm not sure what is causing the above; but that is the reason its failing.

**Comment by johnsoncodehk** [comment]
I can reproduce `--generateTrace` command error in volar-starter so it do not need repro case, thank you. But I'm not sure it can fix because cross tsc -- tsserverlibrary to patch `ts.tracing` may not be possible.

**Comment by blake-newman** [comment]
@johnsoncodehk i believe i found a way to enable this feature; not sure is the solution is appropriate but PR'd it anyway

**Comment by johnsoncodehk** [comment]
Thanks for investigating it!

**Comment by johnsoncodehk** [comment]
Since v0.35.0 auto-import cache is not support for TS <= 4.6.x, and it's re-support in v0.37.1, it may resolve the performance issue on your project.
