### ISSUE TITLE
vue  IntelliSense suggestion not show in vscode 

### ISSUE THREAD

**Issue by tanpengsccd** [johnsoncodehk/volar#1376]
I want a  IntelliSense suggestion for  ":key" after "v-for" statements. but itn't show here.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/13959880/171502632-cb3c9419-3287-4aaf-886c-aaf7e1c7a352.png">

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/13959880/171502690-bc67c9ac-e6d2-4bd3-b819-05f9afaf57f4.png">

I am sorry to ask this basic question here , but I have search google for 10 pages , can't found real valuable answer.

**Comment by huzedong2015** [comment]
+1  for v0.35.2

**Comment by GooGee** [comment]
try install [v0.34.16](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.34.16/vspackage?targetPlatform=win32-x64)
or upgrade your VSCode.
I'm using VSCode 1.66.2

**Comment by xiaoxiangmoe** [comment]
@tanpengsccd @huzedong2015  Can you reproduce it in a new VSCode,  such as [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/).

**Comment by nagman** [comment]
Since last Thursday, I wasn't able to have any types or autocompletion in <template> (all the objects were tied to an "any" type), so I downgraded volar from v0.37.6 to v0.34.14 and now it re-works.
