### ISSUE TITLE
older version of volar (0.17.6)

### ISSUE THREAD

**Issue by vivek9patel** [johnsoncodehk/volar#1377]
I need to get an older version of volar which supports vscode version `1.50.0` or below, specifically i was trying to get volar with version number `0.17.6`. Is it possible to get the .vsix file from somewhere? 

I tried getting it from [vsix hub](https://www.vsixhub.com/vsix/45731/) but the download link is not valid!

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1192#issuecomment-1124907892.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.17.6/vspackage
