### ISSUE TITLE
Nuxt auth support - Cannot find name '$auth'.

### ISSUE THREAD

**Issue by tom-richter** [johnsoncodehk/volar#138]
How can I get support for [Nuxt auth](https://auth.nuxtjs.org/) types? If I use $auth in the template I get the Error `Cannot find name '$auth'.`

```
<div v-if="$auth.loggedIn">
      <v-btn to="/logout">Logout</v-btn>
</div>
```

**Comment by johnsoncodehk** [comment]
Try this:
```
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $auth: any;
  }
}
```

**Comment by thefoxie** [comment]
@tom-richter if you use next then add this `"types": ["@nuxtjs/auth-next"]` to jsconfig.json ;)

**Comment by johnsoncodehk** [comment]
> @tom-richter if you use next then add this `"types": ["@nuxtjs/auth-next"]` to jsconfig.json ;)

A better answer!
