### ISSUE TITLE
[vscode][pug] formatter keep adding spaces in v-for on save  

### ISSUE THREAD

**Issue by chiboreache** [johnsoncodehk/volar#1380]
![2022-06-03x03:29:28](https://user-images.githubusercontent.com/16459251/171761799-4455675f-a049-4590-96d9-ef7026631f66.jpg)

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem, please provide minimal reproduction code.

**Comment by chiboreache** [comment]
@johnsoncodehk 

disabled almost all extensions, but with no luck

only the volar affects on the vue file

https://user-images.githubusercontent.com/16459251/172031433-f800a2c7-1379-4923-89dc-0d931dcd1e78.mp4

**Comment by johnsoncodehk** [comment]
Duplicate of #1398
