### ISSUE TITLE
Named slot gets ts(7053) error with <script setup> alongside normal <script>

### ISSUE THREAD

**Issue by linfengOu** [johnsoncodehk/volar#1389]
Say I have below component: `SlotComponent`. It has normal `<script>` to define `inheritAttrs: false`. Also I use `<script setup>`:
``` vue
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({ inheritAttrs: false });
</script>

<script setup lang="ts"></script>

<template>
  <slot name="header"></slot>
  <br />
  <slot></slot>
  <br />
  <slot name="footer"></slot>
</template>
```

And when using it in another component:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/18301111/171975964-2193526b-d11b-4d57-99b8-955840791a81.png">
Named slots get error: 
```
Element implicitly has an 'any' type because expression of type '"header"' can't be used to index type '{} | {}'.
  Property 'header' does not exist on type '{} | {}'.ts(7053)
```

But as long as I remove `<script setup lang="ts"></script>`, everything is fine.

Please kindly suggest.

**Comment by yangdanping** [comment]
Seems to have the same problem.
named slot will changes the type of elements and attributes to any
![GIF 2022-6-4 12-17-23](https://user-images.githubusercontent.com/42269873/171982479-be8bf09c-7baa-4a19-b2ae-7140a89f26c3.gif)

**Comment by yangdanping** [comment]
> 
and this problem only seems to occur when setup sugar is used

**Comment by AnyaParry** [comment]
![image](https://user-images.githubusercontent.com/60728866/171992821-9d44a58c-19b3-43b5-8c6f-8ff85171844a.png)
so, what happend?
