### ISSUE TITLE
Disable volar type checking for parts of the template

### ISSUE THREAD

**Issue by tom-richter** [johnsoncodehk/volar#139]
How can I disable TypeScript for parts of the template? Is there something like `/* tslint:disable-next-line */ `supported in templates?

**Comment by johnsoncodehk** [comment]
You can use `@ts-ignore` in template interpolation.

```
{{
  // @ts-ignore
  true + true
}}
```

**Comment by tom-richter** [comment]
Okay thanks, I guess it's not possible in directives at the moment?

**Comment by johnsoncodehk** [comment]
It's works on all TS scope, so also works in directives.

**Comment by tom-richter** [comment]
Oh sry, yes you're right. I didn't know that you can put comments inside directives.
