### ISSUE TITLE
Selecting a tag highlights all other similar tags and not the matching closing tag

### ISSUE THREAD

**Issue by amrnn90** [johnsoncodehk/volar#1393]
I think this is a recent issue since I did not notice it before, but I am not sure.

Anyway, when I select a tag I expect the editor to highglight the closing tag only similar to how it works in HTML files, but instead when using volar it highlights all matching tags with the same name as illustrated in the screenshot.

## Current Behavior:
![Annotation 2022-06-04 231927](https://user-images.githubusercontent.com/38134195/172024459-a4cc865a-367d-4f52-8deb-2fba955ffe23.png)

## Expected Behvaior:
![new](https://user-images.githubusercontent.com/38134195/172024505-a3e14a0d-a55f-442c-9097-e995aec17548.png)

**Comment by langfeld** [comment]
Hi,

I still have exactly this problem. Have installed Volar 1.0.7.

Many greetings

**Comment by johnsoncodehk** [comment]
@langfeld I can't reproduce, please try to disable other related extensions if you have.

**Comment by langfeld** [comment]
Hi @johnsoncodehk,

thank you very much for your response.
After updating to v1.0.9 it works fine again.

Many greetings

**Comment by botkalista** [comment]
Same problem in the last 3 new versions
