### ISSUE TITLE
How to prompt the complete TypeScript type

### ISSUE THREAD

**Issue by tanhh326** [johnsoncodehk/volar#1397]
![image](https://user-images.githubusercontent.com/82007768/172101401-511a665b-382a-4cb1-a392-89c851dbf73f.png)

Hello, please advise, how do I configure so that the full TypeScript type is prompted ! (*^▽^*)

**Comment by johnsoncodehk** [comment]
Unfortunately this is TypeScript intellisense behavior and we can't change it.
