### ISSUE TITLE
[vscode][pug] formatter keep adding spaces in v-for on save

### ISSUE THREAD

**Issue by chiboreache** [johnsoncodehk/volar#1398]
```vue
<template lang="pug">
div(v-for='i in list') {{i}}
</template>
<script setup>
</script>
```

```json
    "editor.formatOnSave": true,
    "[vue]": {
        "editor.defaultFormatter": "Vue.volar"
    },
```

https://user-images.githubusercontent.com/16459251/172031433-f800a2c7-1379-4923-89dc-0d931dcd1e78.mp4

**Comment by johnsoncodehk** [comment]
Hi @chiboreache, I note that formatting trimmed last line space character when you save, but this is not volar behavior.
I think you have other extension installed that auto format with ignore `editor.defaultFormatter` setting.

**Comment by chiboreache** [comment]
> Hi @chiboreache, I note that formatting trimmed last line space character when you save, but this is not volar behavior. I think you have other extension installed that auto format with ignore `editor.defaultFormatter` setting.

![2022-06-06x19:30:04](https://user-images.githubusercontent.com/16459251/172203986-9c09e8fb-5d60-43c8-ba24-c4202b311939.jpg)

**Comment by chiboreache** [comment]
**FOUND!**

as always it was the m$ issue... even with disabled formatter, it still did its nasty things....

```json
    "javascript.format.enable": false,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
    "javascript.format.placeOpenBraceOnNewLineForFunctions": true,
    "javascript.format.semicolons": "remove",
    "javascript.updateImportsOnFileMove.enabled": "always",
```

so this is the line causing the issue

```json
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
```

**Comment by sh4wn** [comment]
any progress?

**Comment by negativems** [comment]
I still have the same issue

**Comment by focussing** [comment]
save overhere... any progress?

**Comment by andriasmelianus** [comment]
This bug is still exists. I'am using version 1.8.27.
It keeps adding spaces before the HTML elements on Save.
It's sad that there is no solution for this until now.

**Comment by andriasmelianus** [comment]
However this article could be a good alternative:

https://dev.to/tao/adding-eslint-and-prettier-to-nuxt-3-2023-5bg

**Comment by jmvelazquezr** [comment]
Setting these two to false did it for me:

```json
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
```

**Comment by flyingduck92** [comment]
i still have the issue

**Comment by kelvin-zhao** [comment]
still not fixed it seems...
