### ISSUE TITLE
Support for script syntactical sugar "setup"

### ISSUE THREAD

**Issue by onx2** [johnsoncodehk/volar#14]
I attempted to use the `setup="props"` shorthand with TS but it doesn't seem to work - is there a plan to support this while it is experimental?

Heres an example of what i'm attempting:

**HelloWorld.vue** 
```vue
<script lang="ts" setup="props">
import { ref } from "vue"

declare const props: {
  msg: string
}

export const count = ref(0);
</script>

<template>
 <div>
    {{ count }}
    <button @click="count++">Add</button>
  </div>
</template>
```

**App.vue**
Import the `HelloWorld` component; the props aren't registered when hovering over the component in the template, prop completion and type checking aren't working, and missing a prop doesn't error highlight the component.

- Create vite app
- Add typescript pkg and vue shim
- Add volar shims
- Update files to use TS (index.html and .vue files' `script` tag)

BTW this is looking great so far, really good work! Thanks for your time 😄

**Comment by johnsoncodehk** [comment]
fixed in 0.14.5

**Comment by onx2** [comment]
Wow, that was quick. Thanks!

**Comment by johnsoncodehk** [comment]
@onx2 Sorry to tell you that the old `<script setup>` support will be remove...

you can follow up or comment here: https://github.com/johnsoncodehk/volar/issues/27
