### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by TheJaredWilcurt** [johnsoncodehk/volar#140]
Does this tool offer any value to those not using TypeScript. The README sounds like it's just for TS projects, but doesn't explicitly say that.

**Comment by johnsoncodehk** [comment]
Volar purpose is, close to native `*.js`/`*.ts` performance and development experience in `<script>` block. And provide more interactivity between `<script>`, `<style>`, `<template>` and custom blocks to get SFC maximize its benefits.

So JavaScript is just a part and it's not a limitation, you can typing js in `<script>` block like typing in `*.js`.

**Comment by cereschen** [comment]
In VS Code, even JS files are provided by ts server for advanced features, and Volar is the same way.
