### ISSUE TITLE
After upgrading to 0.36 x version can't get to use the < script setup > syntactic sugar component types

### ISSUE THREAD

**Issue by RennCheung** [johnsoncodehk/volar#1400]
I used `defineExpose` in the child component:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/50518861/172093323-fb3af08d-021e-40ab-ba70-45feb90ac389.png">

But you can't use `typeof` to obtain the corresponding types in the parent component, and error message will appear:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/50518861/172093278-cef752be-73c6-41e7-9f7d-a80481e0cf76.png">

**Comment by johnsoncodehk** [comment]
Hi @RennCheung, maybe you want to use `ref<InstanceType<typeof operateCatalog>>` instead of.

**Comment by RennCheung** [comment]
Thanks Reply.

emm...Do I need to write this in the future? The need for an additional nested layer of `InstanceType`can sometimes be annoying.

And I found another problem. When I hovered over value, the ts type prompt mainly showed the property methods of the component instance object, while the property methods I exported myself were hidden because of too much content, which was very unfriendly, as follows:
![image](https://user-images.githubusercontent.com/50518861/172181863-0b907115-5aa2-4015-83bf-b62ed0c1edd4.png)


---

The reminder here in the `0.35.x` version will be more friendly. I can see the method type I exported very intuitively, and I don't care about the attributes of the component instance itself, as follows:
![image](https://user-images.githubusercontent.com/50518861/172182477-ea21459a-99dd-47cb-89c3-213d2daf8e26.png)


Is this an expected behavior? Maybe you can do this function better

**Comment by exherb** [comment]
when use unplugin-vue-components with `dts: true`, some issue happens.

```typescript
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AfCard: typeof import('./src/anyforce/components/card.vue')['default']
  }
}
```

`error TS2604: JSX element type 'AfCard' does not have any construct or call signatures.`

**Comment by johnsoncodehk** [comment]
@exherb See https://github.com/johnsoncodehk/volar/issues/1405#issuecomment-1148123423.

**Comment by exherb** [comment]
> @exherb See [#1405 (comment)](https://github.com/johnsoncodehk/volar/issues/1405#issuecomment-1148123423).

Thanks, is this a temporary solution?

**Comment by johnsoncodehk** [comment]
> The reminder here in the `0.35.x` version will be more friendly. I can see the method type I exported very intuitively, and I don't care about the attributes of the component instance itself, as follows: ![image](https://user-images.githubusercontent.com/50518861/172182477-ea21459a-99dd-47cb-89c3-213d2daf8e26.png)
> 
> Is this an expected behavior? Maybe you can do this function better

It seem that you do not have use `InstanceType` in this picture so the type is not unwrap yet in hover info, and this is expected TS behavior we can't change it.

**Comment by johnsoncodehk** [comment]
@exherb AfCard should not report error if it is valid component type. Can you show `card.vue` content?

**Comment by RennCheung** [comment]
> > The reminder here in the `0.35.x` version will be more friendly. I can see the method type I exported very intuitively, and I don't care about the attributes of the component instance itself, as follows: ![image](https://user-images.githubusercontent.com/50518861/172182477-ea21459a-99dd-47cb-89c3-213d2daf8e26.png)
> > Is this an expected behavior? Maybe you can do this function better
> 
> It seem that you do not have use `InstanceType` in this picture so the type is not unwrap yet in hover info, and this is expected TS behavior we can't change it.

This picture uses VOLAR in version 0.35.2, so there is no need to use the `InstanceType`, but the type is more friendly

**Comment by exherb** [comment]
> @exherb AfCard should not report error if it is valid component type. Can you show `card.vue` content?

```vue
<template>
  <div>
    <div
      :class="[
        'rounded-t-lg border flex items-center justify-between',
        headerClass,
      ]"
    >
      <slot name="header">
        {{ header }}
      </slot>
    </div>
    <div :class="['rounded-b-lg border-b border-l border-r', bodyClass]">
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
export default defineComponent({
  props: {
    header: {
      type: String,
      default: "",
    },
    headerClass: {
      type: String,
      default: "p-2 text-base",
    },
    bodyClass: {
      type: String,
      default: "p-2",
    },
  },
});
</script>
```

**Comment by exherb** [comment]
just a simple component @johnsoncodehk

**Comment by johnsoncodehk** [comment]
@exherb where are `import { defineComponent } from 'vue'`? 😅
