### ISSUE TITLE
The JSX element type "XXX" does not have any structural signature or call signature.

### ISSUE THREAD

**Issue by RennCheung** [johnsoncodehk/volar#1404]
0.37.0 version Volar appears the following problems

<img width="692" alt="image" src="https://user-images.githubusercontent.com/50518861/172184930-76cf466e-f1ae-4727-973b-4eb6add28227.png">

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1405#issuecomment-1148123423.
