### ISSUE TITLE
JSX element type does not have any construct or call signatures.ts(2604)

### ISSUE THREAD

**Issue by zengkaii** [johnsoncodehk/volar#1407]
ts version: 4.5.4
volar version  v0.37.1
![image](https://user-images.githubusercontent.com/38418699/172295503-c4c94605-ba00-475d-8995-a2c5fb5462f7.png)
![image](https://user-images.githubusercontent.com/38418699/172295546-bac500e8-31ff-4161-97f3-604fe4390e44.png)

**Comment by monster898** [comment]
Same here, solved this problem after reverting version to v0.36.1.

**Comment by zengkaii** [comment]
> Same here, solved this problem after reverting version to v0.36.1.

ok

**Comment by lianyitj** [comment]
更新到 v0.37.2 仍然不行

**Comment by johnsoncodehk** [comment]
Duplicate of #1405
