### ISSUE TITLE
0.37.1更新后出现element-plus的template里的标签全部报这个错误

### ISSUE THREAD

**Issue by CreatorAnd** [johnsoncodehk/volar#1408]
JSX 元素类型“ElFormItem”不具有任何构造签名或调用签名

**Comment by linzhenjie** [comment]
同样出现问题，自定义组件都报错了。
<img width="706" alt="image" src="https://user-images.githubusercontent.com/3871365/172313874-e1e3f882-00ae-48bf-90b6-d80729334daf.png">

**Comment by Zhoushunshun541** [comment]
我也遇到了

**Comment by leo-own** [comment]
加一，突然就不可以了

**Comment by leo-own** [comment]
我回退到0.36.1也可以了

**Comment by LinWeiZZ** [comment]
> 我回退到0.36.1也可以了

大佬，怎么回退，昨天刚刚开始做项目，今天就报错了

**Comment by Nauxscript** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/13010589/172338021-ba9b75e3-939c-4f81-bed8-ed0fa5c6109b.png">

然后选择旧版本

<img width="826" alt="image" src="https://user-images.githubusercontent.com/13010589/172338207-38d3458b-5edb-441b-9734-ff2ab555f97d.png">

**Comment by LinWeiZZ** [comment]
用不着回退，插件下面不是有个重新加载，我重新加载以后就好了

**Comment by RosyClousXun** [comment]
今天没更新之前，执行 vue-tsc --noEmit，会报这样的错：
```
Please update to v0.35.0 or higher for TypeScript version: 4.7.3
src/main.ts:13:9 - error TS2345: Argument of type 'Router' is not assignable to parameter of type 'Plugin_2'.
  Type 'Router' is not assignable to type '{ install: PluginInstallFunction; }'.
    Types of property 'install' are incompatible.
      Type '(app: App) => void' is not assignable to type 'PluginInstallFunction'.
        Types of parameters 'app' and 'app' are incompatible.
          Type 'App<any>' has no properties in common with type 'App'.

13 app.use(router);
```
更新到最新后，不仅element-plus，JSX 元素类型“ElFormItem”不具有任何构造签名或调用签名这种错，上面的错继续报，
大神求解啊，折腾了一下午了还没解决

**Comment by johnsoncodehk** [comment]
Duplicate of #1405
