### ISSUE TITLE
Global Filters can not find in template from type check

### ISSUE THREAD

**Issue by SGAMERyu** [johnsoncodehk/volar#141]
if i define global property
`app.config.globalProperties.$filters = { ...filters };`
 However, TypeScript does not recognize it in the component
![image](https://user-images.githubusercontent.com/17926105/115329796-6defe680-a1c5-11eb-9173-2f206e9d87fb.png)

**Comment by johnsoncodehk** [comment]
hi @SGAMERyu, you need to use define `ComponentCustomProperties` interface, see: https://github.com/johnsoncodehk/volar/issues/138

**Comment by johnsoncodehk** [comment]
Duplicate of #138

**Comment by SGAMERyu** [comment]
> hi @SGAMERyu, you need to use define `ComponentCustomProperties` interface, see: #138

OK, thank you for your answer
volar it's a great project
