### ISSUE TITLE
JSX element type does not have any construct or call signatures.ts

### ISSUE THREAD

**Issue by pengxiaotian** [johnsoncodehk/volar#1411]
这个bug 在 0.37.2 中 并没有解决啊？！还是报错！
并且还发现 属性不识别？ `dataSetId`  和 `data-set-id` 不匹配。
<img width="622" alt="image" src="https://user-images.githubusercontent.com/27847994/172360735-92135cda-a031-42bd-a6bf-73b4ef883a57.png">

**Comment by yingyi666** [comment]
我也是这个问题，使用unplugin-vue-components插件自动导入就这样全红了。。。。
之前还好好的

**Comment by yingyi666** [comment]
先参考这个吧。可以暂时屏蔽掉错误提示https://github.com/johnsoncodehk/volar/issues/1405#issuecomment-1148315173
