### ISSUE TITLE
JSX element type does not have any construct or call signatures.ts

### ISSUE THREAD

**Issue by ltcodes** [johnsoncodehk/volar#1412]
![image](https://user-images.githubusercontent.com/58774318/172365990-c4a13256-bcfd-40bc-86d1-f885b12f05bd.png)
在0.37.2版本，这个问题似乎并没有解决

**Comment by cslettengren** [comment]
I have the same problem (in 0.37.2):
error TS2604: JSX element type 'RouterLink' does not have any construct or call signatures.

**Comment by RSS1102** [comment]
me too.
