### ISSUE TITLE
JSX element type <Component> does not have any construct or call signatures.

### ISSUE THREAD

**Issue by vphilot** [johnsoncodehk/volar#1414]
Seeing this quite a lot after the most recent update - example with routerLink. Any clues on what might be happening?

![image](https://user-images.githubusercontent.com/30128268/172388387-172d9d7f-032a-444f-ad6b-d4bf7cb7a126.png)

**Comment by PickClass** [comment]
https://github.com/johnsoncodehk/volar/issues/1408

**Comment by kingyue737** [comment]
Template error in Vue2 project has been solved for me, but run vue-tsc v0.37.1 in terminal still throw this error
![image](https://user-images.githubusercontent.com/40021217/172421256-b9290341-bf95-4326-8607-d76731470b04.png)

**Comment by kingyue737** [comment]
> ![image](https://user-images.githubusercontent.com/40021217/172423284-51b5d01c-5198-4b76-b9d3-e8d34e06336e.png)
> 
> In vue 2 project, global components explicitly typed have no error now, but for those not defined this bug still exists

Oh no, template errors appear again after 5 mins, I didn't touch anything

**Comment by innocenzi** [comment]
On a Vue 3 project, setting the following in `tsconfig.json` does suppress the errors, but makes all components `any` (although they are all typed via `components.d.ts`):

```json
"vueCompilerOptions": {
	"experimentalSuppressInvalidJsxElementTypeErrors": true,
}
```
