### ISSUE TITLE
JSX 元素类型“ElInput(第三方组件、自定义组件)”不具有任何构造签名或调用签名

### ISSUE THREAD

**Issue by JHPCCOM** [johnsoncodehk/volar#1415]
最新版本Volar 0.37.2 在使用element plus 自动导入插件的情况下第三方组件和自定义组件会报JSX元素类型(组件名)具有任何构造签名或调用签名错误 请开发者排查一下

**Comment by JHPCCOM** [comment]
[](url)

**Comment by JHPCCOM** [comment]
![image](https://user-images.githubusercontent.com/62272192/172416920-596f28f9-e0aa-4060-acf1-e4c14c49c482.png)

**Comment by JHPCCOM** [comment]
鱿鱼须!

**Comment by Delevin888** [comment]
我也是，好难受，改也改不好。。

**Comment by Delevin888** [comment]
![image](https://user-images.githubusercontent.com/38110513/179661751-667db01e-cb9c-43e0-ad8e-5cc83d9be52a.png)

**Comment by zhiming2076** [comment]
我也是呀。官方没人来解决这个问题么？
