### ISSUE TITLE
不能将类型“Router”分配给类型“{ install: PluginInstallFunction; }”。

### ISSUE THREAD

**Issue by hesichuan** [johnsoncodehk/volar#1416]
v0.37.2版本
尝试过降级版本，配置components.d.ts，experimentalSuppressInvalidJsxElementTypeErrors = true
以上尝试均没有解决问题

![image](https://user-images.githubusercontent.com/17641227/172424865-af42a68a-8599-4f6d-8495-8d6734993e25.png)

![image](https://user-images.githubusercontent.com/17641227/172424417-0b0cf09d-8704-4aac-bcd3-27690be4f8bc.png)

**Comment by Lzp0225** [comment]
问题解决了吗？昨天重新安装后就出现这种情况了

**Comment by hesichuan** [comment]
我的windows电脑上没有解决，mac电脑上只出现了Jsx类型错误但是解决了

**Comment by Lzp0225** [comment]
我也是，重新安装volar后jsx类型错误消失了

**Comment by Lzp0225** [comment]
目前暂时的解决方案是断言成any，后续有回复了再看看

**Comment by Lzp0225** [comment]
目前暂时的解决方案是断言成any，后续有回复了再看看

**Comment by rfirefly** [comment]
这个是 Element-plus 的问题
https://github.com/element-plus/element-plus/issues/8122

**Comment by Adaer** [comment]
> 我也是，重新安装volar后jsx类型错误消失了

害我重新安装了依赖包，没想到是这个问题，现在是降级volar降级问题，vant 组件 jsx报错无法解决
