### ISSUE TITLE
Add proper unknown attribute detection

### ISSUE THREAD

**Issue by TheDutchCoder** [johnsoncodehk/volar#1418]
As referenced in previous issues (e.g. https://github.com/johnsoncodehk/volar/issues/1386) Volar currently does not correctly detect all HTML attributes while simultaneously detecting invalid ones.

Example that will throw an error when `experimentalSuppressUnknownJsxPropertyErrors` is disabled:
```html
<div data-test-id="root">
  Root
</div>
```

Example that doesn't (but should) throw an error when `experimentalSuppressUnknownJsxPropertyErrors` is enabled:
```html
<div foo="bar">
  Root
</div>
```

The correct functionality would be only `foo` throwing an error:
```html
<div data-test-id="root" foo="bar">
  Root
</div>
```

**Comment by johnsoncodehk** [comment]
`experimentalSuppressUnknownJsxPropertyErrors` and `experimentalSuppressInvalidJsxElementTypeErrors` will be replace by `strictTemplates` in next version.

> Volar currently does not correctly detect all HTML attributes while simultaneously detecting invalid ones.

When `strictTemplates` is true, all props / attrs is parse with Camel case as trade-off to avoid this problem, it mean you should always define props with Camel case on strict mode.

```diff
defineProps<{
-	'my-prop': string
+	myProp: string
}>
```

> The correct functionality would be only `foo` throwing an error:

Volar will not special handle `data-*` to avoid #1413.

**Comment by johnsoncodehk** [comment]
Replenish: you can define `HTMLAttributes` interface to allow `data-*`: https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1146573602
