### ISSUE TITLE
There is something wrong with `v-for` `index` type

### ISSUE THREAD

**Issue by CNMathon** [johnsoncodehk/volar#1420]
I think the type of `index` in `v-for` is only `number`, but in addition to the `number` I also got a bunch of inexplicable `string`s.

![image](https://user-images.githubusercontent.com/44454223/172551798-a594bf66-e56c-46d0-a6d7-0052ceb37178.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, but it may a bug of low TS version, please try update your TS version if it can.

**Comment by CNMathon** [comment]
I tried to update to `v0.37.9`, it works.

**Comment by muhammadyusuf-kurbonov** [comment]
![image](https://user-images.githubusercontent.com/45625440/205273647-90d2750e-cd00-4778-884e-0866c85f6be2.png)

TS version: 3.7.2
Extension version: v1.0.10
