### ISSUE TITLE
pug slot shorthand highlighting

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#1423]
This is really a minor not-breaking-anything bug! 🙂 
The `#` in front of slots are not highlighted in correctly, when it doesn't use an `=` sign after the slot.

<img src="https://user-images.githubusercontent.com/7195563/172580008-01d54b71-457d-4f5a-a9f1-d1fc857363e6.png" width="600px"/>

**Comment by Shinigami92** [comment]
Back from vacation and updated vue-tsc
Result: 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/180732015-5a6edd82-99b0-44ac-8101-eec47b058230.png">

Works fine 🙌 💚

**Comment by Shinigami92** [comment]
@johnsoncodehk 
🤔 Mh... but I now see that the `2` and the `!` is coloured differently
If you like to, you can also try to fix that

**Comment by johnsoncodehk** [comment]
@Shinigami92 could you paste the code?

**Comment by Shinigami92** [comment]
> @Shinigami92 could you paste the code?

@johnsoncodehk send full file via Discord direct message

**Comment by johnsoncodehk** [comment]
@Shinigami92 I can't reproduce, but it seems to me that the problem is caused by another theme extension you have installed.
<img width="374" alt="螢幕截圖 2022-09-26 03 44 50" src="https://user-images.githubusercontent.com/16279759/192162298-7b820bb2-cd37-4cf6-8a9c-32da30bbe622.png">

**Comment by Shinigami92** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7195563/192205150-541733cb-b20e-44bf-9d01-27239d315402.png">

I'm using `Dark+ (default dark)`

Also note that my screenshot is taken with vue-tsc / volar `v0.40.1` as I cannot update to the latest and also cannot use/test the preview v1 version right now
I need to wait until it is in stable extension branch to test it
