### ISSUE TITLE
Nuxt Bridge with 0.37 causes any in template variables and components

### ISSUE THREAD

**Issue by ThomasBerneSV** [johnsoncodehk/volar#1424]
Nuxt bridge VueJS template intellisense didn't work in 0.37 but worked in 0.36. It marked any to any variable and component used in a template in a SFC.

**Comment by johnsoncodehk** [comment]
Please provide minimal reproduction.

**Comment by ThomasBerneSV** [comment]
I figured it out. This was caused by old version of nuxt bridge. I updated it to the latest and it works like a charm.
