### ISSUE TITLE
is dynamic component slot typing supported?

### ISSUE THREAD

**Issue by exherb** [johnsoncodehk/volar#1425]
version: 0.37.3

```vue
<component  :is="list">
  <template #default="scope">
    <slot v-bind="scope" />
  </template>
</component>
```

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/65154/172607915-e804f101-ee79-4836-baf5-ace0826d745a.png">

0.36.1 is not have this kind of lint issue.

**Comment by exherb** [comment]
here is the minimal reproductive repo

https://github.com/exherb/vite-project

`https://github.com/exherb/vite-project/blob/main/src/components/HelloWorld.vue`

Run `npm run lint` will report 

```
➜ npm run lint

> vite-project@0.0.0 lint
> vue-tsc --project . --noEmit

src/components/HelloWorld.vue:9:10 - error TS2339: Property 'scope' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & Readonly<...> & Sha...'.

9       {{ scope.msg}}
           ~~~~~


Found 1 error in src/components/HelloWorld.vue
```

got time to check this issue? thanks @johnsoncodehk

**Comment by mesqueeb** [comment]
For me it also started happening recently.

Slot scope variables used to default to `any` I believe, causing no issues throughout our app, but now suddenly we have a million of these:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/3253920/172740034-ce0b6cea-2deb-43ca-a9ab-4c2e5a2f3d03.png">

Manually typing as was suggested somewhere else also doesn't work.
Eg. `#default="{ index }: { index: number }"`

<img width="500" alt="image" src="https://user-images.githubusercontent.com/3253920/172740139-8a72b99f-05e6-4dfb-b970-88e320a13f30.png">

@johnsoncodehk any idea for a work around?
