### ISSUE TITLE
Use ctrl + left mouse button to click on the variable can not jump

### ISSUE THREAD

**Issue by wilikeit** [johnsoncodehk/volar#1439]
vscode version：1.69
volar version：v0.37.3

If you add props ,use ctrl  left mouse button to click variable ,  can not jump   ,but if you delete props, you can jump.

```
import {defineComponent,reactive}  from 'vue'
export default defineComponent({
  props:{
    title:{
      type:String
    }
  },


  setup(){
    var state = reactive({
        name:'lucy',
        code:'',
    })
    return {
      state
    }
  },
  render(){
    return <div>{this.state.name}</div>
  }

})
```
[Video_2022-06-11_224050.zip](https://github.com/johnsoncodehk/volar/files/8884166/Video_2022-06-11_224050.zip)

**Comment by johnsoncodehk** [comment]
This is JS and defineComponent type limitation not volar issue, you can reproduce it in .jsx file. For workaround you can use tsx instead of jsx.
