### ISSUE TITLE
0.37.6 breaks event payload type detection (npm monorepo)

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#1445]
Some oddities
- cannot find volar running in the `output` list, but it's definitely running
- volar is not able to retrieve the type of the event payload of the vue file
- when ⌘+Click on the Vue component, it goes to the `shims` file instead of to the component
- on `0.37.3` everything works as expected

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/3253920/173284616-46714a9c-217e-4ac3-8119-9c343f5a4884.png">

**Comment by johnsoncodehk** [comment]
> * cannot find volar running in the `output` list, but it's definitely running

This is expected, because volar do not have any console.log if it's running normally.

> * volar is not able to retrieve the type of the event payload of the vue file
> * when ⌘+Click on the Vue component, it goes to the `shims` file instead of to the component

Could you provide minimal reproduction? (Btw I suggest you use [takeover mode](https://vuejs.org/guide/typescript/overview.html#takeover-mode) instead shims)

**Comment by mesqueeb** [comment]
@johnsoncodehk we have takeovermode enabled. `@builtin typescript` is disabled:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/3253920/173289209-86bfdf12-5651-47f7-8ef4-4dada8e70f4e.png">


working on creating a minimal reproduction now

**Comment by mesqueeb** [comment]
@johnsoncodehk here's a minimal reproduction. (in takeovermode)
<img width="711" alt="image" src="https://user-images.githubusercontent.com/3253920/173290917-1d53be43-3bfb-488b-a178-0029a0164de4.png">

and on `v0.37.3`, works as expected:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/3253920/173291114-7703f5a5-08c4-4363-aa0c-69edbb8ab2ff.png">

zip without `node_modules`:
https://www.dropbox.com/s/qyhin4xwr2cgnok/volar-issue-0.37.6.zip?dl=0

1. open in VSCode
2. `npm i` (make sure you have npm v8+)
3. install volar
4. disable `@builtin typescript`
5. reload VSCode
6. open `packages/app/src/App.vue` see the event payload is not typed

**Comment by mesqueeb** [comment]
@johnsoncodehk what is this dark magic fix? 😂 it's just a variable rename? 

What was wrong? 🤔

**Comment by johnsoncodehk** [comment]
@mesqueeb Variable rename obfuscate the fix 😅, it should be:

```diff
						const fileExists = !!host.fileExists?.(fileNameTrim);
						if (fileExists) {
							// create virtual files
-							const scriptSnapshot = host.getScriptSnapshot(fileName);
+							const scriptSnapshot = host.getScriptSnapshot(fileNameTrim);
							if (scriptSnapshot) {
-								documentRegistry.set(fileName, createSourceFile(
-									fileName,
+								documentRegistry.set(fileNameTrim, createSourceFile(
+									fileNameTrim,
									scriptSnapshot.getText(0, scriptSnapshot.getLength()),
									compilerOptions,
									vueCompilerOptions,
```
