### ISSUE TITLE
Scope class name can't show underline

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#1447]

**Comment by Xu-doudou** [comment]
This problem still exists
The scope class name also can not show underline when class are used by nested and outermost layer

version: 0.37.9

**Comment by Xu-doudou** [comment]
> _No description provided._

This problem still exists
The scope class name also can not show underline when class are used by nested and outermost layer

version: 0.37.9

**Comment by johnsoncodehk** [comment]
@Xu-doudou Could you provide reproduction code?

**Comment by Xu-doudou** [comment]
> @Xu-doudou Could you provide reproduction code?

![image](https://user-images.githubusercontent.com/69188637/174246471-375e4f69-b92f-4f2f-83a0-7bc2d094503c.png)
![image](https://user-images.githubusercontent.com/69188637/174246533-ef96d3ae-193e-4a39-8d45-dd1a02638713.png)

It seems like the Class with the same start name like "demo" and "demoComp", the latter isn't recognized and show the underline

**Comment by Xu-doudou** [comment]
![image](https://user-images.githubusercontent.com/69188637/174251536-9ebfee72-ca93-4296-b36e-110cc5e822bf.png)

Oh, It looks like a problem with camel case ?
