### ISSUE TITLE
Indentation is removed on line break in <script setup>

### ISSUE THREAD

**Issue by mateusk** [johnsoncodehk/volar#1449]
Hi, I have a minor but still annoying issue regarding formatting Vue3 files while using VSCode + Volar + ESLint + Prettier. Formatting was working fine until a couple days ago, when I noticed that, within`<script setup>`, whenever I hit enter, the formatter removes the indentation from the previous line (refer to the .gif below for an example). When I save, indentation is correctly fixed (I have `formatOnSave` enabled).

![ezgif-5-559853bbe8](https://user-images.githubusercontent.com/1747445/173332931-5472ee81-cd82-43f6-bee6-a8e446d8794c.gif)

When I disable the Volar extension in VSCode, the issue is gone. 

This issue only happens within `<script setup>`, within `<template>` or `<style>` formatting works fine.

Here are my ESLint settings:

```
// .eslintrc.js

module.exports = {
  root: true,
  env: { node: true },
  parser: 'vue-eslint-parser',
  parserOptions: {},
  plugins: ['prettier'],
  extends: [
    'plugin:vue/vue3-recommended',
    'plugin:vuejs-accessibility/recommended',
    'prettier',
  ],
  rules: {
    'prettier/prettier': 'warn',
    'vue/comment-directive': 'off',
    'vue/multi-word-component-names': 'off',
    'vue/component-definition-name-casing': ['error', 'PascalCase'],
    'vue/component-name-in-template-casing': [
      'error',
      'PascalCase',
      { registeredComponentsOnly: true },
    ],
    'vue/max-attributes-per-line': [
      'error',
      {
        singleline: {
          max: 4,
        },
        multiline: {
          max: 1,
        },
      },
    ],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'never',
      },
    ],
  },
}
```

And my Prettier settings:

```
{
  "vueIndentScriptAndStyle": true,
  "arrowParens": "always",
  "bracketSpacing": true,
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "tabWidth": 2,
  "useTabs": false,
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "parser": "html"
      }
    }
  ]
}
```

Any hints would be appreciated. Thanks for the great extension!

**Comment by johnsoncodehk** [comment]
Hi @mateusk, VSCode [format on type](https://youtu.be/m-3Symq2-V8) is supported after v0.36.0 (https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0360-202263), you may would to disable it with `editor.formatOnType` setting in vscode.
