### ISSUE TITLE
在 Markdown 中输入反引号时会提示 csdn

### ISSUE THREAD

**Issue by lymims** [johnsoncodehk/volar#1450]
最近在 VSCode 中写 markdown 添加 C# 代码块时，输入三个反引号及cs后（```cs），智能提示会列出 `cs` `csdn` `class` 等选项，有时误操作就会把 csdn 输上去了。

![image](https://user-images.githubusercontent.com/9443706/173382504-7bc5b834-ecb5-4cb2-9b3e-4a4de7d68108.png)

不确定该问题的根源是不是 Volar，但目前的现象是：禁用 Volar 插件后，该问题就不再出现。

已经尝试在配置及 Volar 源码中查找 csdn 关键字，但都没有结果。

是否能检查该问题，或者提供途径在 Markdown 格式文件中禁用 Volar ？

**Comment by JamesLIAOHJ** [comment]
Open a  .md file,  then  open the Sencondary Side Bar  from vscode menu "view " -> "Appearance" -> "Show Secondary Side Bar".   we now can see Volar has scan the md file and show the result at the second side bar.  bellow is my vscode screenshot 

<img width="613" alt="Volar_md_file" src="https://user-images.githubusercontent.com/13430516/177081005-af03e0a5-81a5-42bf-848d-62090db3afe9.png">

does anyone know how to disable this for md file?  or how ro only enable volar for vue related file ?

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/66083fc73f91c224190ce432e79524739bd1bf6f.
