### ISSUE TITLE
File '[...]/src/App.vue.__VLS_template.jsx' is a JavaScript file. Did you mean to enable the 'allowJs' option?

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#1452]
This is new and occurred between `> 0.37.5, <= 0.37.8`

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/7195563/173509849-60a8418d-1055-4fd9-b052-e142d57059d6.png">

Setting it to allowJs true works for now, but I personally prefer not to allow it, so I get an error when someone in my team writes a js instead of ts file.

**Comment by Eusebius1920** [comment]
Seeing the same problem.

In my case it is caused by single-file-components that do not have a `<script>` tag.

Adding `<script lang="ts" setup></script>` to these files helps as a workaround for now.

**Comment by Shinigami92** [comment]
@Eusebius1920 You are right 💚

The content of my `App.vue` is
```html
<template lang="pug">
router-view
</template>
```
