### ISSUE TITLE
type error when import file missing the <script> block

### ISSUE THREAD

**Issue by seesawsin** [johnsoncodehk/volar#1455]
### Reproduction link
https://github.com/see-saw-seen/vue3-test
The repo was generated by `create-vue`.

### Description
The error seems due to the missing of `<script setup lang="ts">` block.
It happened in v0.37.8 and It looks well when i fall back to v0.37.7.

![微信截图_20220614162652](https://user-images.githubusercontent.com/107463723/173533310-82edc3a0-2c90-4ae2-860b-8d0761cfa642.png)
![微信截图_20220614162823](https://user-images.githubusercontent.com/107463723/173533330-4969e45e-1153-4ad1-ab92-cd861bcf04d7.png)

v0.37.7 works well
![微信截图_20220614162544](https://user-images.githubusercontent.com/107463723/173534116-a60c8e0e-6380-4078-b838-3ce1c0d96ccc.png)

**Comment by exherb** [comment]
encounter this too

**Comment by johnsoncodehk** [comment]
Thanks for the report. v0.37.8 is a version update for petite-vue, if you don't use petite-vue, you can downgrade to v0.37.7 for now.
