### ISSUE TITLE
volar 0.37.8 + vue 2 error. `Property 'props' does not exist on type '{}'.ts(2339)`

### ISSUE THREAD

**Issue by juner** [johnsoncodehk/volar#1457]
Type cannot be resolved by hovering to a variable on template
`Property 'props' does not exist on type '{}'.ts(2339)`

This issue did not occur in volar 0.37.7.

## version
volar 0.37.8
vue 2 
vscode 1.68.0

## sample project:
[https://github.com/juner/vue_volar_error_sample](https://github.com/juner/vue_volar_error_sample)

## pattern

| `volar_vue` | `vue 2` | `vue 3`
| -- | -- | --
| `volar 0.37.7` | ![vue2+volar0.37.7 \ vue 2](https://user-images.githubusercontent.com/753914/173569168-c86ff967-74d5-4d56-9c86-8263e8198bf1.png) | ![volar 0.37.7 \ vue 3](https://user-images.githubusercontent.com/753914/173569421-d5c3227c-6b23-44ae-8d7d-f35a123f4794.png)
| `volar 0.37.8` | ![volar 0.37.8 \ vue 2](https://user-images.githubusercontent.com/753914/173569082-294a4432-4e08-4030-8bbc-b643dda68b5b.png) | ![volar 0.37.8 \ vue 3](https://user-images.githubusercontent.com/753914/173569206-4985b90e-d1e3-4ee4-b34d-b15d6a3388c6.png)

**Comment by kingyue737** [comment]
+1

![image](https://user-images.githubusercontent.com/40021217/173729585-7f557128-bba9-4fd2-86e4-961450d703cf.png)

**Comment by kingyue737** [comment]
Replace `"experimentalCompatMode": 2` with `"target": 2`  in `tsconfig.json`

**Comment by juner** [comment]
@kingyue737 Thank you. It was very helpful.
