### ISSUE TITLE
Component Tag Name including "Vue" on import

### ISSUE THREAD

**Issue by eduardocmoreno** [johnsoncodehk/volar#1461]
I just updated VsCode and Volar extension, and now the import suggestions for Vue files are including "Vue" at the end, like in the picture. Is there a way to disable this? Thx!

![image](https://user-images.githubusercontent.com/4020449/173721247-1a725cb6-cbf1-4de0-aa7f-c026e424a641.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report. v0.37.8 is a version update for petite-vue, if you don't use petite-vue, you can downgrade to v0.37.7 for now.

**Comment by eduardocmoreno** [comment]
Yep, downgrading to v0.37.7 did the job. Thx @johnsoncodehk

**Comment by cannap** [comment]
is this fixed?

 i still have this issue with v0.39.4 i use vue 2

**Comment by cannap** [comment]
i enabled takeover mode like here 
https://github.com/johnsoncodehk/volar/discussions/471

when i import vue files in a .js file

**Comment by johnsoncodehk** [comment]
@cannap could you demonstrate it and show tsconfig content?

**Comment by SamuelNitsche** [comment]
@johnsoncodehk Sorry for bumping this old issue but it looks like this reappeared. Is there a way to disable this?
