### ISSUE TITLE
如何在格式化时，让html属性独占一行

### ISSUE THREAD

**Issue by wishong** [johnsoncodehk/volar#1462]
更新了一下版本发现格式化规则似乎变了，想保留原有的规则没找到配置项
![image](https://user-images.githubusercontent.com/53365470/173762213-c4e9447f-d0f7-42e1-9b89-e5309b869088.png)
![image](https://user-images.githubusercontent.com/53365470/173762149-710da09f-f441-432f-95fc-e8b6b13dcb00.png)

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1268#issuecomment-1119452383.
