### ISSUE TITLE
Unreasonable high RAM usage in new version

### ISSUE THREAD

**Issue by Fuzzyma** [johnsoncodehk/volar#1463]
vue-tsc is not known for being especially savy on RAM (it used to take about 2GB on my local machine).
**However**, it got even worse with one of the latest versions and it is not at **3GB**.
At this point, the Github pipeline runs out of ram whenever I try to run vue-tsc in Github actions

What happened and what can be done to fix this problem? 

PS: I also would say that it got significantly slower but that would be just my perception

Version I used before: 0.36.1 (that one was less hungry)

**Comment by johnsoncodehk** [comment]
@Fuzzyma, thanks for the report. Just for check the problem, does ram usage reduce by config `"exclude": ["**/*.md"]` in the project tsconfig in latest version?
