### ISSUE TITLE
why v-slot is typeof VNode[]

### ISSUE THREAD

**Issue by poyoho** [johnsoncodehk/volar#1467]
why v-slot is typeof `VNode[]` 😭

```html
<Comp v-slot="ctx">
</Comp>
```

in mac is ok, when run in window I got ctx is type of `VNode[]`.

![origin_img_v2_2565c0f5-c3d2-44d7-bc9e-dfdbb499102g](https://user-images.githubusercontent.com/36070057/174029762-4dd5aaa8-a1a5-4947-889f-d9797f260c8a.jpg)

**Comment by Tcioch** [comment]
I have same question. Is there any way to at least turn it off? 
I have everywhere errors like 
`"const item: any Property 'item' does not exist on type 'VNode[] | undefined'.ts(2339)"`

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/75fc5254549654b432995b911771ed24bf7b62ca
