### ISSUE TITLE
There is no prompt for passing values to child components

### ISSUE THREAD

**Issue by xiangyuisabatman** [johnsoncodehk/volar#1468]
- volar: v0.37.9
- vue: 3.2.25
- typescript: 4.5.4
```
/**
* declare some props {labelWidth, popText, label}
*/
<template>
  <div
    class="label"
    :style="{ width: labelWidth + 'px', flex: `0 0 ${labelWidth}px` }"
  >
    {{ label }}
    <Popover v-if="popText" type="base" placement="top-left">
      <template #content>
        <article>
          {{ popText }}
        </article>/
      </template>
      <Icon class="icon" :name="'tagError'" />
    </Popover>
    :
  </div>
</template>

<script setup lang="ts">
interface Props {
  labelWidth: number; 
  popText: string; 
  label: string;
}
const props = withDefaults(defineProps<Props>(), {
  labelWidth: 140,
  popText: "",
  label: "",
});
</script>
```

There is no hint and no mandatory verification
![image](https://user-images.githubusercontent.com/23613080/174047084-9eefc507-ffcc-403e-b265-e0737ce5d105.png)

## hope
I want to know what parameters the child component has and is there anything missing

**Comment by xiangyuisabatman** [comment]
- volar:v0.37.9

**Comment by johnsoncodehk** [comment]
Works for me, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

<img width="588" alt="image" src="https://user-images.githubusercontent.com/16279759/174050135-cc53f55a-503a-4e65-b279-b80b117be7fe.png">

**Comment by johnsoncodehk** [comment]
@xiangyuisabatman Seens related to https://github.com/vuejs/core/pull/5871, please try update to latest vue version.
