### ISSUE TITLE
No intellisense of Global Components

### ISSUE THREAD

**Issue by abitwhy** [johnsoncodehk/volar#1469]
![image](https://user-images.githubusercontent.com/68452982/173893956-a31e446c-3e6f-47bd-8cda-807dcebb42de.png)
![image](https://user-images.githubusercontent.com/68452982/173893987-bf9d26a7-6b90-4ae3-900c-61a23498b374.png)

It must be caused by the change:

```diff
- declare module 'vue' {
+ declare module '@vue/runtime-core' { 
```

Because rollback will make intellisense work.

**Comment by abitwhy** [comment]
Beside Volar's support, setting `shamefully-hoist=true` in `.npmrc` is needed, or package like '@vue/runtime-core' won't be found (without warning).

@johnsoncodehk You may need to declare this in your plugin introduction page, like [here](https://marketplace.visualstudio.com/items?itemName=Vue.volar#:~:text=Define%20Global%20Components).

**Comment by Anoesj** [comment]
> Besides Volar's support, another requirement is you can access the package like '@vue/runtime-core' (even if you can't, it won't warn).
> 
> You can achieve that by:
> 
> * add the package directly (as devDependence)
> * setting `shamefully-hoist=true` in `.npmrc` (for pnpm project)
> 
> @johnsoncodehk You may need to declare this in your plugin introduction page, like [here](https://marketplace.visualstudio.com/items?itemName=Vue.volar#:~:text=Define%20Global%20Components).
> 
> Reference: [shamefully-hoist](https://pnpm.io/npmrc#shamefully-hoist).

Thanks! I‘m using pnpm, so packages aren‘t hoisted by default. This should be added to the docs indeed.
