### ISSUE TITLE
Option to ignore check

### ISSUE THREAD

**Issue by yenkos** [johnsoncodehk/volar#147]
i want  to use volar in my team, Volar is very good tool.

my project build with Vue3 but not used Setup api. 

Volar display many error tips on old .vue file. 

How to solve this problem in a simple way. like ```/* eslint-disable */ ```

[![](https://raw.githubusercontent.com/yenkos/PicGo/main/img/20210422151055.png)](url)

**Comment by johnsoncodehk** [comment]
Options api is still support in vue 3, you should use `defineComponent({ ... })` to wrap your options.

**Comment by yenkos** [comment]
thank you. 

In fact, what I want to say is that old files are not written in TS, but there is no time to refactor them. If can't turn off the error tips, it will appear with ESLint's tips, which can be confusing.

**Comment by yenkos** [comment]
Most old files look like this with volar.

[![](https://raw.githubusercontent.com/yenkos/PicGo/main/img/20210422172117.png)](url)

**Comment by johnsoncodehk** [comment]
You can config `exclude` in your tsconfig.json to ignore all checking for some vue scripts (may need to reload vscode):

`"exclude": ["src/path-to-your-vue2-scripts/**/*.vue"]`

**Comment by yenkos** [comment]
I tried this method, but it didn't work very well. 
It seems that Volar can only be enabled on new projects

**Comment by johnsoncodehk** [comment]
@yenkos sorry about that, before we can use `@vue-ignore`, but it was be remove. 😅 (https://github.com/johnsoncodehk/volar/discussions/134)
