### ISSUE TITLE
What is a FormEvent?

### ISSUE THREAD

**Issue by bartenra** [johnsoncodehk/volar#148]
I have this input element:

```
<input
  name="description"
  type="text"
  :value="getFormDataSelectedLang('description')"
  autocomplete="off"
  @input="handleInput($event, 'description')"
/>
```

And a method that receives an `Event`. To my knowledge this is the only type for Vue events.

But I am getting:

```
Argument of type 'FormEvent<HTMLInputElement>' is not assignable to parameter of type 'Event'.ts(2345)
```

**Comment by johnsoncodehk** [comment]
Seems similar problem to: https://github.com/johnsoncodehk/volar/issues/111

**Comment by bartenra** [comment]
Ah yeah I recently started using Storybook, which pulls in React as a dependency. :-/

**Comment by johnsoncodehk** [comment]
So I think you have solved it? If not, just let me know.

Duplicate of #111

**Comment by johnsoncodehk** [comment]
Duplicate of #111
