### ISSUE TITLE
vue-typescript organize imports issues

### ISSUE THREAD

**Issue by Shayan-To** [johnsoncodehk/volar#1480]
As project `prettier-plugin-organize-imports` implemented organize imports based on `vue-typescript` (in [prettier-plugin-organize-imports#55](https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/55) and [prettier-plugin-organize-imports#56](https://github.com/simonhaenisch/prettier-plugin-organize-imports/pull/56)), I found these two issues:

- In vue files with both `script` and `script setup`, the imports of both blocks are merged into one of them.

  Example input:

  ```vue
  <template>
    <BComp v-model="value"></BComp>
  </template>

  <script lang="ts">
  import { defineComponent } from "vue";
  export default defineComponent({ inheritAttrs: false });
  </script>

  <script setup lang="ts">
  import BComp from "./BComp.vue";
  import { ref } from "vue";

  const value = ref("");
  </script>
  ```

  Current output:

  ```vue
  <template>
    <BComp v-model="value"></BComp>
  </template>

  <script lang="ts">
  import { defineComponent, ref } from "vue";
  import BComp from "./BComp.vue";
  export default defineComponent({ inheritAttrs: false });
  </script>

  <script setup lang="ts">
  const value = ref("");
  </script>
  ```

  Diff:

  ```patch
  @@ -3,13 +3,11 @@
   </template>

   <script lang="ts">
  -import { defineComponent } from "vue";
  +import { defineComponent, ref } from "vue";
  +import BComp from "./BComp.vue";
   export default defineComponent({ inheritAttrs: false });
   </script>

   <script setup lang="ts">
  -import BComp from "./BComp.vue";
  -import { ref } from "vue";
  -
   const value = ref("");
   </script>
  ```

  Expected output: No change, the same as input.

- Imports that are only used in the template, are removed (except for components).

  Example input:

  ```vue
  <template>
    <AComp v-model="value" v-some-directive></AComp>
  </template>

  <script setup lang="ts">
  import AComp from "./AComp.vue";
  import { value, vSomeDirective } from "./utils";
  </script>
  ```

  Current output:

  ```vue
  <template>
    <AComp v-model="value" v-some-directive></AComp>
  </template>

  <script setup lang="ts">
  import AComp from "./AComp.vue";
  </script>
  ```

  Diff:

  ```patch
  @@ -4,5 +4,4 @@

   <script setup lang="ts">
   import AComp from "./AComp.vue";
  -import { value, vSomeDirective } from "./utils";
   </script>
  ```

  Expected output: No change, the same as input.

These examples are available in [this repro](https://gist.github.com/Shayan-To/bd4d432a4dfa9bb7dc980961694a0a0c).

**Comment by johnsoncodehk** [comment]
Hi @Shayan-To, I think this problem can be avoid by update typescript version to 4.7.3, can you confirm this?

**Comment by Shayan-To** [comment]
Hi @johnsoncodehk!

I added `typescript` to the repro project I sent here, and tried version `4.7.4` and `4.7.3`, and the behavior is no different from before.

I pushed a commit to the [same repro gist](https://gist.github.com/Shayan-To/bd4d432a4dfa9bb7dc980961694a0a0c) so you can see whether I did something wrong.

**Comment by Shayan-To** [comment]
Hi @johnsoncodehk!
Thanks for the update.
I checked it. Part of the problem was fixed, but the rest is still there.
I created a new repro [gist](https://gist.github.com/Shayan-To/aa4eef90f692313bec1a51e2f1cdaee9).
Thanks again.
