### ISSUE TITLE
Css references on properties when using scss functions

### ISSUE THREAD

**Issue by lucas-labs** [johnsoncodehk/volar#1481]
I'm getting this kind of references report:
![image](https://user-images.githubusercontent.com/12949236/174522006-10f63d3c-0533-412e-9bc4-70125dc5133a.png)

Whenever I use a function, the "references" label is shown on the css property I'm applying the function to.
Is this behaviour ok?

**Comment by johnsoncodehk** [comment]
This is css class name parsing bug at https://github.com/johnsoncodehk/volar/blob/master/packages/vue-typescript/src/utils/parseCssClassNames.ts. I'm working on other issues, if someone want to try a fix please feel free to send a PR.

**Comment by lucas-labs** [comment]
Thanks for the tip! 
I'll give it a try and send a PR

**Comment by lucas-labs** [comment]
@johnsoncodehk I just sent a PR regarding this issue. Feel free to check it out whenever you want!
