### ISSUE TITLE
When use pnpm in windows REFS system, get code hints error

### ISSUE THREAD

**Issue by LemoFire** [johnsoncodehk/volar#1482]
Code:

import { onMounted, provide } from "vue";

VSCode Tips:
- **onMounted, provide:** Module “vue“ has no exported member“onMounted”。
- **vue:** module "D:/.pnpm-store/v3/files/47/a231b6e349c0a5f70d00e451c5b110ed4ca665cdea0a2b317d7e0fa518e3b673cce9b584b277b97733ab2f0b0d4b34c8c8032282dbe90cd1f51884aed40d98"

**Comment by johnsoncodehk** [comment]
Hi @LemoFire, I think OS file system would not affect language server behind LSP, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter.

**Comment by LemoFire** [comment]
now I'm using a new disk and formating it to RESF

### clean installation vscode uses the following plugin:
```
Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code
TypeScript Vue Plugin (Volar)
Vue Language Features (Volar) v0.38.3
Vite v0.2.5
```
### clean installation pnpm
```
nvm install 18
nvm use 18.5.0
npm install pnpm -g
set-ExecutionPolicy RemoteSigned
```

### clone template in REFS and install dependencies
```
git clone https://github.com/johnsoncodehk/volar-starter
cd volar-starter
pnpm i
```

### open folder as VSCode and open `main.ts`
we get a same error when mouse move to the first line `import { createApp } from 'vue';`
- createApp : 
```
import createApp
模块“"vue"”没有导出的成员“createApp”。ts(2305)   // Module “vue“ has no exported member“createApp”。
没有可用的快速修复
```
- vue : 
```
module "D:/.pnpm-store/v3/files/47/a231b6e349c0a5f70d00e451c5b110ed4ca665cdea0a2b317d7e0fa518e3b673cce9b584b277b97733ab2f0b0d4b34c8c8032282dbe90cd1f51884aed40d98
```

**Comment by LemoFire** [comment]
@johnsoncodehk

**Comment by tiyunchen** [comment]
我也出现这种问题了

**Comment by ywenhao** [comment]
我也出现这种问题了
![image](https://github.com/user-attachments/assets/a2f9d23e-7f82-49df-9064-0ffacd0ed323)
有的项目有 有的没有

**Comment by LyXiaoYao** [comment]
> 我也出现这种问题了 ![image](https://private-user-images.githubusercontent.com/37856060/398060818-a2f9d23e-7f82-49df-9064-0ffacd0ed323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzk1NzksIm5iZiI6MTczNDkzOTI3OSwicGF0aCI6Ii8zNzg1NjA2MC8zOTgwNjA4MTgtYTJmOWQyM2UtN2Y4Mi00OWRmLTkwNjQtMGZmYWNkMGVkMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMmIxMDBkMjc0YjBkNWRhNDk2MTQ3MDhhMmM3ZjQ1ZTBiODI0MWRkOTJhMGNmYjMwNzYwYjI2ZmE1OTViNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wQyetNluPqVej4WoRFZoqPJ7sO7FnquZyqIgiIrvPrA) 有的项目有 有的没有

+1，老哥解决了嘛

**Comment by ywenhao** [comment]
> > 我也出现这种问题了 ![image](https://private-user-images.githubusercontent.com/37856060/398060818-a2f9d23e-7f82-49df-9064-0ffacd0ed323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzk1NzksIm5iZiI6MTczNDkzOTI3OSwicGF0aCI6Ii8zNzg1NjA2MC8zOTgwNjA4MTgtYTJmOWQyM2UtN2Y4Mi00OWRmLTkwNjQtMGZmYWNkMGVkMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMmIxMDBkMjc0YjBkNWRhNDk2MTQ3MDhhMmM3ZjQ1ZTBiODI0MWRkOTJhMGNmYjMwNzYwYjI2ZmE1OTViNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wQyetNluPqVej4WoRFZoqPJ7sO7FnquZyqIgiIrvPrA) 有的项目有 有的没有
> 
> +1，老哥解决了嘛

解决了，你检查一下你的项目里面哪`declare module "vue"`了一下，把他删了，或者不是vue是其他的module，你要不删还能正确使用，那你得学会d.ts为啥需要export {}相关的ts知识

**Comment by LyXiaoYao** [comment]
好的，我往这个方向去研究下，之前一直以为是插件版本和依赖版本的兼容问题，多谢！

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/23/2024 22:10 |
| To | vuejs/language-tools ***@***.***> |
| Cc | LyXiaoYao ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [vuejs/language-tools] When use pnpm in windows REFS system, get code hints error (Issue #1482) |

我也出现这种问题了 有的项目有 有的没有

+1，老哥解决了嘛

解决了，你检查一下你的项目里面哪declare module "vue"了一下，把他删了，或者不是vue是其他的module，你要不删还能正确使用，那你得学会d.ts为啥需要export {}相关的ts知识
