### ISSUE TITLE
无法像vetur插件一样指定vue中不同模块的格式化工具

### ISSUE THREAD

**Issue by Dante617** [johnsoncodehk/volar#1488]
![image](https://user-images.githubusercontent.com/29395599/174704139-09326fc9-ede4-48bc-9251-70a08a9f1698.png)
有一个需求就是使用volar格式化vue代码只想格式化<style>中的样式代码，不格式化<template>和<script>中的代码，之前vetur插件是可以像上图一样设置，就可以达到这种需求，但volar插件目前似乎不支持

**Comment by richex-cn** [comment]
https://github.com/johnsoncodehk/volar/issues/478
Please search before asking questions.
