### ISSUE TITLE
[v0.38.1] Vue 2.6 No intellisense of Global Components

### ISSUE THREAD

**Issue by kingyue737** [johnsoncodehk/volar#1489]
![image](https://user-images.githubusercontent.com/40021217/174713714-e6a684aa-1fa1-49f7-be37-cfb4ff6e0281.png)
![image](https://user-images.githubusercontent.com/40021217/174714211-b561f5c4-2b3d-4b68-9d38-93614b91207e.png)

I don't know whether it is related to [this commit](https://github.com/johnsoncodehk/volar/commit/cefed1e135ad34fcd5351d7255ad08d84d1a2fcb), but still not working if I replace `@vue/runtime-dom` with `@vue/runtime-core`

Roll back to v0.37.9, all the intellisense comes back.

**Comment by kingyue737** [comment]
@beholderrk  Are you using `Vue2`? Replace `@vue/runtime-core` with `@vue/runtime-dom` should work in v0.37.9

**Comment by beholderrk** [comment]
> @beholderrk Are you using `Vue2`? Replace `@vue/runtime-core` with `@vue/runtime-dom` should work in v0.37.9

Sorry. I change previous comment. I had another problem.

**Comment by RennCheung** [comment]
Vue3 have same problem

**Comment by abitwhy** [comment]
If still dosen't work, check this [ralated issue](https://github.com/johnsoncodehk/volar/issues/1469).
