### ISSUE TITLE
Text document version is implemented incorrectly

### ISSUE THREAD

**Issue by Holi0317** [johnsoncodehk/volar#1490]
I am using neovim as the client. Whenever I apply a code action, neovim shows a warning saying "Buffer X newer than edits".

Searching through the Internet points me to this issue on neovim: https://github.com/neovim/neovim/issues/12970.

A quick hack on neovim code shows that in my case, volar is reporting `text_document.version` as 5 while neovim is having `14`.

Volar is at version `0.38.1`.

**Comment by Holi0317** [comment]
Related logs and neovim config: https://gist.github.com/Holi0317/4463e117942cbc2c9533ceae2b9c937c

# System information

- Volar 0.38.1
- Neovim v0.7.0

# Step to reproduce

1. Create a vite vue typescript project
2. Edit a `.vue` file
3. Edit and add `const a = computed(() => false)` in `<script>` block
4. Move cursor on `computed` (which should be a missing import)
5. Invoke code action (`<space>a` in the config given), choose "Add import from vue"
6. Neovim complains text document version mismatch

# Diagnostic

The log attached in the gist only contains a section of the whole lsp log. However it is clear that neovim did indicate `textDocument.version == 44` in the last `textDocument/didChange` call and volar returns `textDocument.version == 32` in all the suggested edits in code action response.

**Comment by yaegassy** [comment]
Hi, @Holi0317 

Thanks for the steps to reproduce this in Neovim.

This problem is probably a known defect. However, I cannot reproduce it in VSCode on my environment.

Can you reproduce this issue in VSCode? If VSCode can reproduce the problem, it may be possible to correct it.

**Comment by Holi0317** [comment]
Hey @yaegassy,

I've tried to do the code action thing on vscode. Here is the related logs: https://gist.github.com/Holi0317/7498749499be45f77d9410e167bca677

Seems that the behavior of volar are the same in vscode and neovim. But vscode ignores the incorrect `textDocument.version` and apply the changes volar propose even if the version is lower than the one in vscode. I think it might be just because vscode's client implementation does not care `textDocument.version` when applying code action.

The lsp spec says the version should always be increasing: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#optionalVersionedTextDocumentIdentifier

Have tried similar action on tsserver (ask the server apply missing import for me) and tsserver respond with correct (increasing) `textDocument.version`.

**Comment by yaegassy** [comment]
@Holi0317 Thanks for checking the behavior in VSCode. I think we have made a step forward in solving this problem.

BTW, I am the maintainer of `coc-volar`. `coc-volar` currently avoids the bug by adjusting the document version when executing code actions.

**Comment by vanarok** [comment]
A workaround? Please.
