### ISSUE TITLE
Find reference in vue file

### ISSUE THREAD

**Issue by richex-cn** [johnsoncodehk/volar#1493]
Is there a way to find references in Vue files ? Just now, I found all references of a type in the project and replaced the name, Then the project could not run normally because I found that vscode could not find the reference in the Vue file.

Like this issue: https://github.com/Microsoft/vscode/issues/64844

**Comment by richex-cn** [comment]
It works now for me: https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin

**Comment by subinznz** [comment]
worked after getting both Volar plugins !

**Comment by arshamalh** [comment]
TypeScript Vue Plugin (Volar) is deprecated and the [recommended alternative](https://marketplace.visualstudio.com/items?itemName=Vue.volar) is also not working.

**Comment by MrSunshyne** [comment]
I found that using the "TypeScript: Find File References" works the same and doesn't require the old Volar plugin.

`cmd + shift + p` then type "Find File References", you should see it.

Hope this helps ! 

<img width="879" alt="Image" src="https://github.com/user-attachments/assets/f0357193-aa1b-45b8-8f3f-224ef56ee832" />

**Comment by avataka9** [comment]
для тех, кто так же будет пытаться найти, как установить это deprecated расширение - 
ctrl+p и выполнить 'ext install Vue.vscode-typescript-vue-plugin'

так можно установить принудительно, и теперь наконец-то  всё работает
