### ISSUE TITLE
jsx comments?

### ISSUE THREAD

**Issue by whaaaley** [johnsoncodehk/volar#1494]
I didn't see an issue for this. If this is already known, I appologize.

![](https://i.gyazo.com/7a886c984a6b01347157519fc3cde2de.gif)

**Comment by whaaaley** [comment]
Additionally, tag auto complete also does not work in JSX.

**Comment by whaaaley** [comment]
@johnsoncodehk it looks like comments inside map functions are incorrect. should I file a new issue for this?
![gif](https://i.gyazo.com/11e220c9634ad3592a4836c4acb2a46b.gif)

**Comment by johnsoncodehk** [comment]
@whaaaley yes please open a new issue.
