### ISSUE TITLE
vue-tsc emit extra event hints on VSCode which i don't need

### ISSUE THREAD

**Issue by Jackie1210** [johnsoncodehk/volar#1496]
## what issue i met
i was using `script setup` to build a vue UI lib

<img width="477" alt="image" src="https://user-images.githubusercontent.com/14737221/174955949-27e5f8ec-e6d8-4480-a800-04c656d2fcc4.png">

when i use this component it will have extra hints which i didn't declare

<img width="628" alt="image" src="https://user-images.githubusercontent.com/14737221/174956144-ed6e1a73-fcf2-4bfb-bcbd-096594749e64.png">

## how i emit type declartion files

<img width="604" alt="image" src="https://user-images.githubusercontent.com/14737221/174956711-a19f52d5-3b69-4806-bea4-13be76adccfe.png">

vue-tsc ^0.38.1
vue ^3.2.37

**Comment by sethidden** [comment]
Seems like those just come from Vue itself https://github.com/vuejs/core/blob/main/packages/runtime-core/src/vnode.ts#L103 and are valid events, even if you haven't defined them explicitly.
