### ISSUE TITLE
Props with multiple types

### ISSUE THREAD

**Issue by thefoxie** [johnsoncodehk/volar#150]
If I have prop like this:
```js
value: {
	type: [Number, String],
	default: 0,
},
```
Then everything else stops working
![image](https://user-images.githubusercontent.com/15309350/115821635-6f0e5700-a403-11eb-9b80-c1c1d499fc55.png)

Works if I change it to:
```js
value: {
	type: Number,
	default: 0,
},
```
![image](https://user-images.githubusercontent.com/15309350/115821817-c6142c00-a403-11eb-8ee8-9b092401ae89.png)

**Comment by johnsoncodehk** [comment]
Hi @thefoxie, I can't reproduce this problem, can you provide a repro case? you can modify https://github.com/johnsoncodehk/volar-starter.

**Comment by thefoxie** [comment]
@johnsoncodehk sure. Here it is https://github.com/thefoxie/volar-props-types
Check components `HelloWorldWorks.vue` vs `HelloWorldNotWorking.vue`

**Comment by thefoxie** [comment]
Forgot to mention I use vue 2 with options api.

**Comment by johnsoncodehk** [comment]
volar does not fully handle options api without `defineComponent`, in vue 2 you need to wrap your options with `defineComponent` from `@vue/composition-api`.

```ts
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
	name: "HelloWorldNotWorking",
	props: {
		msg: {
			type: [String, Number],
			required: true,
		},
	},
	data() {
		return { count: 0 };
	},
});
```

**Comment by thefoxie** [comment]
Oh sure. It would be great to add that to docs/readme. Thank you
