### ISSUE TITLE
Incompatible with the berry/latest version of yarn? @yarn version berry or latest

### ISSUE THREAD

**Issue by XiangShuUncle** [johnsoncodehk/volar#1501]
The reproduction steps are as follows：

1. Use https://github.com/johnsoncodehk/volar-starter
2. In Command : 
yarn set version berry
yarn
3. Result：
Base  Prompt of voltage is invalid
![image](https://user-images.githubusercontent.com/37469567/175256836-3d194596-7036-417b-bd20-332bde8787df.png)

If you remove the “yarn set version berry” command We have Prompt appears normally
![image](https://user-images.githubusercontent.com/37469567/175256955-3070880c-3456-4858-bc14-4e40441f52af.png)

Please take a moment to tell me how to solve the problem of no code prompt when using the berry version of yarn. be deeply grateful.

**Comment by johnsoncodehk** [comment]
Is this issue duplicate to #918? (If yes, thanks for the setup explain, I'm unfamiliar with it for now)
