### ISSUE TITLE
Editor colors

### ISSUE THREAD

**Issue by lacherogwu** [johnsoncodehk/volar#1502]
Hey, I've noticed that the colors of attributes and components are not colored in different colors than the default HTML elements
I've tried to lookup online for that but I didn't find any thread about that.

Is it popular issue or it's only on my side?
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/49835614/175420806-5a3f9da6-9c3b-4c2f-b835-37db00ab86d5.png">

As you can see the v-if and v-else and the Test components are colored with the same color of the html tags which makes it harder to read.

I'll appreciate a solution for that
Thanks for your help

I know that Vetur does have it, but it doesn't support the setup syntax so the used variables are marked as unused which is also not pleasant to work that way
<img width="662" alt="image" src="https://user-images.githubusercontent.com/49835614/175422577-9802c8a6-b675-4b43-bed7-cc7badd19176.png">

**Comment by lucas-labs** [comment]
maybe this depends on the color schema you're using?
I don't have this issue
![image](https://user-images.githubusercontent.com/12949236/175757024-594e1462-19f5-40a1-93a9-4382a265b586.png)

**Comment by lacherogwu** [comment]
> maybe this depends on the color schema you're using? I don't have this issue ![image](https://user-images.githubusercontent.com/12949236/175757024-594e1462-19f5-40a1-93a9-4382a265b586.png)

What's your Color Schema?

**Comment by lucas-labs** [comment]
I use [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) theme

**Comment by lacherogwu** [comment]
You were right, it's due to the color theme, I was using Monokai++
I wish I could stay with Monokai++ because the colors are much better in my opinion
