### ISSUE TITLE
Function template ref type isn't correspond component type

### ISSUE THREAD

**Issue by extrem7** [johnsoncodehk/volar#1504]
`const componentRef = ref<InstanceType<typeof VolarComponent>>()`

`<VolarComponent :ref="el=>componentRef=el" />`

Current type of `el` is `Element | ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}` not `InstanceType<typeof VolarComponent>`

**Comment by extrem7** [comment]
@johnsoncodehk why don't provide the correct type of `el` at Volar level?

**Comment by johnsoncodehk** [comment]
`el` type of `:ref` it's define from vue at https://github.com/vuejs/core/blob/24f4c479d661698afd967cf428f9439be4578a04/packages/runtime-dom/types/jsx.d.ts#L1313 not from Volar.
