### ISSUE TITLE
Using typescript other than VSCode's version fails to type check inside <template>

### ISSUE THREAD

**Issue by jerryc05** [johnsoncodehk/volar#1507]
Assume a `.vue` file like this:
```
<template>
  <div @click="someVariableThatDoesNotExist"/>
</template>
```
---
`vscode`'s version of `ts` (`=v4.7.3`) works well in detecting that the variable does not exist: 
```
Cannot find name 'someVariableThatDoesNotExist'. ts(2304)
```

However, when I switched to workspace's version of `ts` (regardless of version, but I tried `v4.7.4` and `v4.8.0-dev.20220624`), `vscode` no longer shows the error.

Switching back to `vscode`'s version of `ts` makes this problem show up again.

Note that I am switching `ts` using command provided by `volar`.

Any thoughts?

---
Interestingly, a fresh install of `vscode` and `volar` sometimes works with workspace's `ts` (but it only worked once).

However, after I turn on my account's settings sync (which syncs settings and extensions), then turn it off, then uninstall all extension except `volar`, and remove everything in vscode's `settings.json` (trying my best to turn `vscode` into its fresh-installed state), workspace's `ts` does not work from then on, no matter what I do.

I suspect that some built-in extensions might be the cause, because there were merge conflicts between my account's settings sync and the default `vscode` ones. After merging, this issue occurs.

---
`vscode: 1.69.0-insider (user setup)`
`volar: v0.38.1`

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem. Can you reproduce in https://github.com/johnsoncodehk/volar-starter?

**Comment by jerryc05** [comment]
> Thanks for the report, but I can't reproduce this problem. Can you reproduce in https://github.com/johnsoncodehk/volar-starter?

Yes I can reproduce with `typescript@next`
![image](https://user-images.githubusercontent.com/8305074/179367112-279069ed-acf7-4660-b3bb-1f5677122c1b.png)
