### ISSUE TITLE
Vue components imported with @ into script setup have no type 

### ISSUE THREAD

**Issue by DanSweeney23** [johnsoncodehk/volar#1508]
If I import a vue component into a .ts file, volar picks up the type of the imported component as a DefineComponent.
![image](https://user-images.githubusercontent.com/14074655/175776154-e1804293-50c0-41be-b99d-77fa66439840.png)

However if I import a component the same way into another component, with script setup, no type is picked up.
![image](https://user-images.githubusercontent.com/14074655/175776183-873d6881-459e-4bd8-b9f0-f6841c188049.png)

And that causes an issue if I try to pass it to the render function. The vue compiler doesn't mind of course, it's just volar complaining about it. But volar also does pick up the type if I use a relative path to the component.
![image](https://user-images.githubusercontent.com/14074655/175776207-ec63338c-97c7-4a8c-a7c4-2ed94a9f1a32.png)

And the @ alias is defined like this in vue.config.js
![image](https://user-images.githubusercontent.com/14074655/175776123-a982385c-a901-42c3-acf6-ee1e09f55f22.png)

**Comment by dpschen** [comment]
@DanSweeney23 Did you also [add the path to compiler options](https://github.com/vuejs/create-vue-templates/blob/main/typescript/tsconfig.json#L7=) e.g. like what [create-vue](https://github.com/vuejs/create-vue) does.
