### ISSUE TITLE
Monokai++

### ISSUE THREAD

**Issue by lacherogwu** [johnsoncodehk/volar#1515]
When I use Monokai++ with Volar(Official vue extension), I don't get component s highlight and it just look same color of the HTML tag 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/49835614/175882340-e68b59bd-87fb-4c52-bfb5-30e8363a454c.png">

When I use vetur(the previous vue extension) it is showing correctly
<img width="488" alt="image" src="https://user-images.githubusercontent.com/49835614/175882466-c6f61a61-cacc-403e-ae4b-e08b10253fff.png">

And also if I use Volar with any other color theme it's working great
<img width="565" alt="image" src="https://user-images.githubusercontent.com/49835614/175882803-0c673e67-fe02-40a5-8a52-2344058eef3e.png">

But I didn't find any other Color theme that looks good, I think Monokai++ has the best colors
I don't know if I should open an issue here or in Monokai++ extension repo.

Thanks for your help!

**Comment by johnsoncodehk** [comment]
Could you run `Developer: Inspect Editor Tokens and Scopes` and show the info box at `HelloWorld` tag?

**Comment by lacherogwu** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/49835614/177710028-639303a7-e9a9-47b3-8a11-9fc77dde2f43.png">

**Comment by johnsoncodehk** [comment]
@lacherogwu thanks, and I also need the info box at `<Form>` tag with other theme that can show component color.

**Comment by lacherogwu** [comment]
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/49835614/177712357-fb1b0ab3-a037-44d6-957b-2ca3b488760d.png">

**Comment by johnsoncodehk** [comment]
It seems that this problem already fixed by https://github.com/dcasella/monokai-plusplus/commit/e4e4f7daa7712d868ffe15e335e32d0b9ee5f505.
