### ISSUE TITLE
After update vue-tsc to the latest version, 'outFile' option not working

### ISSUE THREAD

**Issue by xinheHuang** [johnsoncodehk/volar#1519]
my project is now emit all types file to a single 'd.ts' file by using compiler option 'outFile', all things work fine under vue-tsc version 0.33.9.  But when i update vue-tsc to the latest version(like 0.38.2), the option does not work. The 'd.ts' file is not generated.

**Comment by johnsoncodehk** [comment]
Just tried latest vue-tsc v0.38.2 in https://github.com/johnsoncodehk/volar-starter and it's working to me (but I found there are many unneeded emit code 🤦), please provide minimal reproduction if you still have this problem when use latest version.

<img width="1373" alt="螢幕截圖 2022-07-07 12 13 29" src="https://user-images.githubusercontent.com/16279759/177689654-5f03ca04-b1cd-4039-bc69-3b6cba530439.png">
