### ISSUE TITLE
Problem with $attrs

### ISSUE THREAD

**Issue by lfhenrl** [johnsoncodehk/volar#152]
Thanks for an amazing tool.
If i use the $attrs like in this code, I got errors saying that Type 'unknown' is not assignable to type 'string | undefined'.
I know it is TS but in this situation I think it should be ignored.

![image](https://user-images.githubusercontent.com/10332372/115832139-d1228880-a412-11eb-9ac9-502a66c1c7f4.png)

**Comment by johnsoncodehk** [comment]
We should not ignore this type error, but should fix the attr type on your way.

For example:

- `:name="typeof $attrs.name === 'string' ? $attrs.name : ''"`
- `:name="String($attrs.name)"`
- `:name="$attrs.name as string"` (when https://github.com/vuejs/vue-next/issues/1359 arrive)

**Comment by lfhenrl** [comment]
Ok, thanks for fast response.
