### ISSUE TITLE
intellisense not working on first open file with watch

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#1523]
with the new version, using watch and watching reactive variable the ide will protesting when we first open the file.
right now, a way to fix this is re-typed the `current.name` and the intellisense will work again, it has no problem on build.

![image](https://user-images.githubusercontent.com/45350572/176582407-b69a02e6-e94b-4d0f-8bd5-9f588658a9e5.png)

**Comment by johnsoncodehk** [comment]
It seems TS 4.7 issue, it can't reproduce with TS 4.6.2, can you confirm this?

<img width="554" alt="螢幕截圖 2022-07-10 14 22 20" src="https://user-images.githubusercontent.com/16279759/178133880-2e319d96-6d1e-4a5e-ae6a-db50c158d8b0.png">

**Comment by zynth17** [comment]
> It seems TS 4.7 issue, it can't reproduce with TS 4.6.2, can you confirm this?
> 
> <img alt="螢幕截圖 2022-07-10 14 22 20" width="554" src="https://user-images.githubusercontent.com/16279759/178133880-2e319d96-6d1e-4a5e-ae6a-db50c158d8b0.png">

yes i can confirm this does appear on TS 4.6.2

**Comment by johnsoncodehk** [comment]
It may fix in TS 4.8: https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#file-watching-fixes-especially-across-git-checkouts
