### ISSUE TITLE
Format not following vue/html-closing-bracket-newline

### ISSUE THREAD

**Issue by miku3920** [johnsoncodehk/volar#1527]
![image](https://user-images.githubusercontent.com/45704185/176703843-d26847cf-43f8-430a-bbe2-a3aba770ffa7.png)

.eslintrc.js
```json
"vue/html-closing-bracket-newline": ["error", {
  "singleline": "never",
  "multiline": "always"
}]
```
setting.json
```json
"[vue]": {
  "editor.defaultFormatter": "Vue.volar"
}
```

**Comment by johnsoncodehk** [comment]
You could change html formatter of volar, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#credits.

**Comment by thopiddock** [comment]
> You could change html formatter of volar, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#credits.

I've seen this link provided for this same scenario on a few issues, but it's a broken link now - is there any up to date link / documentation for the feature you were linking to?
