### ISSUE TITLE
说实话，性能有点差啊。

### ISSUE THREAD

**Issue by mztlive** [johnsoncodehk/volar#1529]
电脑配置：
i7-10510u 8核
内存16G
全固态硬盘

编辑.vue文件的时候经常弹不出代码提示来。
纯ts, js文件没问题。

另外，内存占用也高啊

Computer Configuration:
i7-10510u 8 cores
Memory 16G
All solid state drive

Code prompts often fail to pop up when editing .vue files.
Pure ts, js files are fine.

Also, the memory usage is high.

**Comment by FFFirer** [comment]
最近碰到同样的问题，一个月内，突然发现在*.vue文件内的提示非常的慢，而ts文件内的提示会快一点，新建的vue3+vite+ts初始项目也没有问题。
R7-5800H+16G+500G固态

**Comment by xiaojia21190** [comment]
performance is really bad, Code hints are slow, Please also optimize it, it is very unfriendly to machines with low configuration.

**Comment by kola-web** [comment]
M1 都卡

**Comment by FFFirer** [comment]
最近用起来稍微缓解了，打印了一下Output，部分请求响应达到秒级，[volar vscode trace output](https://github.com/FFFirer/volar-trace-output)，不知道有没有更好的调试办法

**Comment by mztlive** [comment]
官方没人响应一下这个问题吗？

**Comment by xiaojia21190** [comment]
现在基本上本地是不能用的状态, 好奇你们的电脑都是什么配置,是我电脑垃圾了吗?

**Comment by xiaoxiangmoe** [comment]
你们能给我们一个可复现的 demo 吗？我想知道那种 case 下会性能远远不够。

**Comment by BTBMan** [comment]
+1 智能感应之类的真的非常慢

**Comment by trlanfeng** [comment]
插件设置的最后一项`Use Second Server`开启后会好很多

**Comment by pecopeco** [comment]
开启后cpu占用率多了30%

**Comment by yoyo930021** [comment]
請按照這個文件提供類似的效能報告出來
https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

不然專案作者無法通靈
最好還提供個 repro case
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by mztlive** [comment]
![image](https://user-images.githubusercontent.com/13467892/179885064-235232fc-d286-4502-8c53-30e9cc98b69d.png)

这并不是个例啊

**Comment by IOLOII** [comment]
# I got same problem
#1582 
I find in the windows task manager, the vscode used memory was upto 4GB,who know I just opened one project & not running

So I find maybe my computer has some hack soft, when I use vscode process manager , see the same pid from the extension of vue.volar

It works was bit by bit it goes up, up to about 4GB memory  and then down (maybe depending on the computer  configuration) and up again.

So I uninstall this extension 

> vue.volar extension version : v0.38.8
> 版本: 1.69.2 (system setup)
提交: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
日期: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by L1yp** [comment]
webstorm依然很卡  5700G 32G 1T固态  应该不是电脑问题

**Comment by mztlive** [comment]
# 分享一个做法也许能对你有帮助

1. 关闭volar扩展
2. 下载 vue3 support - all in one （用来做代码着色）
3. 将.vue文件里面script标签的代码写到一个独立的ts/js文件中.
4. 在.vue文件里面的script标签引入你的代码

*就像这样*
![image](https://user-images.githubusercontent.com/13467892/180359046-fcdd5145-b00d-4029-9e12-0776f588002d.png)

这样一来就可以利用vscode自己对ts和js的支持完成高效的代码提示，完全不依赖volar。

### 缺点是：
template 里面没了代码提示

**Comment by yanbowe** [comment]
代码提示真的太慢了

**Comment by L1yp** [comment]
> 代码提示真的太慢了

哎 感觉没人理

**Comment by L1yp** [comment]
> 代码提示真的太慢了

昨天去看svelte发现没有vue方便

**Comment by IOLOII** [comment]
> 你们能给我们一个可复现的 demo 吗？比如社区中的哪个项目打开，在你的啥环境下会出现卡顿。
> 
> 我现在的使用情况是，初始化慢一些（这是所有 ts 项目的通病啦），但是开发中还算流畅。

https://github.com/johnsoncodehk/volar/issues/1529#issuecomment-1192116003

[你看下插件运行时内存的占用情况](https://github.com/johnsoncodehk/volar/issues/1529#issuecomment-1192116003)

**Comment by tangerren** [comment]
![image](https://user-images.githubusercontent.com/16789187/182987033-35049a0f-c8b1-4dcf-8140-9df2fac7ba22.png)

**Comment by leosin** [comment]
![image](https://user-images.githubusercontent.com/3676670/183094370-83bc212e-844d-48c3-a68f-2a7e52ee4f5f.png)
你们都是几百，几千的占用内存？
我这300多还觉得有点卡。。哈哈，还能再优化吗？

**Comment by GiveMe-A-Name** [comment]
- 尝试过删除掉 node_modules 目录，volar 能够正常使用。CPU使用率，内存使用量都低
![截屏2022-08-08 上午8 50 46](https://user-images.githubusercontent.com/58852732/183318665-74fcc49a-99c9-409b-af56-8d778d4c4820.png)

- 安装好 node_modules , volar 的内存使用量能够达 1G 多，CPU 占有率也高

![截屏2022-08-08 上午8 53 40](https://user-images.githubusercontent.com/58852732/183318829-24cf36a1-faf9-42c3-b78d-66295c793607.png)

这是因为 volar 会去解析我 node_modules 里的文件吗，希望官方能好好排查这个问题，能够复现的项目社区已经提供了很多了。

**Comment by BTBMan** [comment]
<img width="1486" alt="图片" src="https://user-images.githubusercontent.com/26108004/183559756-f6cbb1e6-1655-4bca-af81-fb407a8a2e47.png">

换了m1 pro较比之前的15款intel是快了非常多 不过内存占用还是很高

而且我感觉在monorepo里会拖慢ts文件的加载速度 tsserver内存也过高 volar 不知道是我配置的问题还是其他原因

<img width="2555" alt="图片" src="https://user-images.githubusercontent.com/26108004/183560955-ec269ecc-bc24-4192-bace-dadb4dde777b.png">

**Comment by C1oudust** [comment]
本来想反馈一下占用内存高的问题，没想到已经有这么多了。。这玩意在我机器占700多M。导致我一跑vue项目，vscode占用直接飙到快2g

**Comment by johnsoncodehk** [comment]
> 可以用我这个项目试试 [FFFirer/webhooks.net.git](https://github.com/FFFirer/webhooks.net.git)
> 
> vue项目路径是 client\webhooks-ui 主要是在*.vue文件中的智能提示非常慢 *.ts文件中的智能提示速度还是可以的

這個項目裡的WorkDetail.vue引入了@vicons/fluent，@vicons/fluent裡有超過30000個.d.ts檔導致Volar的TS language service需要花長時間計算auto import。
.ts快是因為沒有引入@vicons/fluent，tsserver沒有計算@vicons/fluent的auto import，你在.ts裡加import @vicons/fluent的話.ts提示一樣會變慢。
禁用VSCode的`typescript.suggest.autoImports`就可以解決。

**Comment by johnsoncodehk** [comment]
對於個別項目的性能問題，請先將dependencies裡的依賴逐個移除去排查，確定是插件問題再開issue描述如何復現。

**Comment by shenke119** [comment]
tsconfig.json里的include 没必要的删掉 感觉好多了

**Comment by leosin** [comment]
> tsconfig.json里的include和compilerOptions里的types， 没必要的删掉 感觉好多

```json
  "exclude": [
    ".output",
    ".vscode",
    "assets",
    "dist"
   "// and other..."
  ]
```

**Comment by GiveMe-A-Name** [comment]
> > 可以用我这个项目试试 [FFFirer/webhooks.net.git](https://github.com/FFFirer/webhooks.net.git)
> > vue项目路径是 client\webhooks-ui 主要是在*.vue文件中的智能提示非常慢 *.ts文件中的智能提示速度还是可以的
> 
> 這個項目裡的WorkDetail.vue引入了@vicons/fluent，@vicons/fluent裡有超過30000個.d.ts檔導致Volar的TS language service需要花長時間計算auto import。 .ts快是因為沒有引入@vicons/fluent，tsserver沒有計算@vicons/fluent的auto import，你在.ts裡加import @vicons/fluent的話.ts提示一樣會變慢。 禁用VSCode的`typescript.suggest.autoImports`就可以解決。

在正常的 ts 文件中去引入 @vicons/fluent，代码提示没有问题。但在 Volar ts lsp 的是有问题的，这是有什么特别之处吗？
导致 ts 文件的代码提示不用去计算 30000 多个的 .d.ts 文件，但 volar 一定要去计算

**Comment by huzedong2015** [comment]
我一直以为是我电脑性能问题，也是提示要3，4秒甚至更长才能出来

**Comment by canwhite** [comment]
> 现在基本上本地是不能用的状态, 好奇你们的电脑都是什么配置,是我电脑垃圾了吗?

m2 都卡

**Comment by L1yp** [comment]
> 

我本地用volar挺正常的 AMD 5700G 32G内存  就是代码提示有点演示 修改了 interface vue文件感应有点慢 代码提示不算太慢

**Comment by liulib** [comment]
> * 尝试过删除掉 node_modules 目录，volar 能够正常使用。CPU使用率，内存使用量都低
>   ![截屏2022-08-08 上午8 50 46](https://user-images.githubusercontent.com/58852732/183318665-74fcc49a-99c9-409b-af56-8d778d4c4820.png)
> * 安装好 node_modules , volar 的内存使用量能够达 2G 多，CPU 占有率也高
> 
> ![截屏2022-08-08 上午8 53 40](https://user-images.githubusercontent.com/58852732/183318829-24cf36a1-faf9-42c3-b78d-66295c793607.png)
> 
> 这是因为 volar 会去解析我 node_modules 里的文件吗，希望官方能好好排查这个问题，能够复现的项目社区已经提供了很多了。
> 
> 在简单项目里复现不出，但在真实项目中能够复现，我的依赖是这样子的：
> 
> ```json
> {
>   "dependencies": {
>     "@element-plus/icons-vue": "^2.0.6",
>     "@vueuse/core": "^5.3.0",
>     "axios": "^0.27.2",
>     "codemirror": "^5.65.6",
>     "codemirror-editor-vue3": "^2.1.7",
>     "element-plus": "^2.2.8",
>     "monaco-editor": "^0.33.0",
>     "vue": "^3.2.25",
>     "vue-router": "^4.0.16"
>   },
>   "devDependencies": {
>     "@types/node": "^18.0.0",
>     "@vitejs/plugin-vue": "^2.3.3",
>     "vite": "^2.9.9"
>   }
> }
> ```
> 
> 当我重建一个简单项目，但在代码中不使用这些依赖的时候，并不会出问题，是否是因为我在代码中使用了 `element-plus` 等组件依赖，导致 volar 会去递归的解析 node_modules 中的文件，导致 CPU，内存使用过大，导致无法对我的正常的代码文件进行代码提示。

一模一样，请问下有解决方案吗

**Comment by yoyo930021** [comment]
Please open new issue when you have repro case and have problem.
