### ISSUE TITLE
Not detecting possible 'null' in `v-for` source

### ISSUE THREAD

**Issue by romalytvynenko** [johnsoncodehk/volar#153]
Hello. Thanks for this great plugin!

During testing found this issue. When a possibly 'null' object is used as a source in `v-for`, Volar does not report this problem.

Here is the example. 

Actual behavior: No problems found by Volar.
Expected behavior: Volar reports "Object is possibly 'null'. ts(2531)" on `items` in `v-for`.

```vue
<template>
  <div v-for="item of items">
    {{ item }}
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  data () {
    return { 
      items: null as string[] | null
    }
  },
})
</script>
```

At the same time, if I use some array's methods in the template's code on the `items` variable, Volar correctly reports about `items` possibly can be `null`.

**Comment by johnsoncodehk** [comment]
Hi @romalytvynenko, thanks for report this problem!

But this is design because vue do not have error on runtime with this case. (If you think this is a design error, I can move this issue to [Discussions](https://github.com/johnsoncodehk/volar/discussions) to discuss.)

**Comment by romalytvynenko** [comment]
Oh, I didn't know that! If there is no runtime problem (I should've checked first), I think this is a great design decision! Thank you! 

P.S.:

Just out of curiosity, where I should have look in the source code to change this behavior? Not that I'm going to change it for this particular case now, but I really would be happy to contribute to the other issues. 

Yesterday I played around with the source of template generator (`packages/vscode-vue-languageservice/src/generators/template.ts`) but wasn't able to understand why I cannot get reporting. Generated code looked good to me and from the first look, I felt like it should give this thing reported. 

And now, knowing that this is by design, I'm really wondering how this works :see_no_evil: 

Would be great to know it, but please feel free to ignore this question, if it is too much to explain, that is fine.

Have a great day and thanks again for this plugin. This is really inspiring!

**Comment by johnsoncodehk** [comment]
You can replace this code to do it: https://github.com/johnsoncodehk/volar/blob/a688b0b37c58788993a11daffb6b425e56af9d76/packages/vscode-vue-languageservice/src/generators/template.ts#L265

Replace to:

```ts
tsCodeGen.addText(`for (var ${forOfItemName} of `);
writeCode(
	sourceVarName,
	{
		start: source.loc.start.offset,
		end: source.loc.end.offset,
	},
	SourceMaps.Mode.Totally,
	{
		vueTag: 'template',
		capabilities: capabilitiesSet.diagnosticOnly,
	},
);
tsCodeGen.addText(`) { }\n`);
```

I think you can easy to understand so I don't say more explanation. 😅

But I'm not really recommend you spend time to check the code in v0.x, because this library is still a fast implementation prototype, and I plan to rewrite `vscode-vue-languageservice` to support plugin API in future.

**Comment by romalytvynenko** [comment]
Thank you so much! Now I get it :)
