### ISSUE TITLE
Class and slot properties errors in Vue 2.7 without @types/react dependency

### ISSUE THREAD

**Issue by Hope410** [johnsoncodehk/volar#1534]
In order to solve this issue as fast as possible, I created a small repo to reproduce the problem: https://github.com/Hope410/slot-class-issue

1. Volar throws the error of class property doesn't exist in vue component defined by `defineComponent` function:
`Property 'class' does not exist on type 'IntrinsicAttributes & Readonly<Partial<{}> & Omit<{} & {}, never>>'.`
![image](https://user-images.githubusercontent.com/19515610/177139134-aeb357ec-05f8-494f-b63e-9f961822dfdc.png)

I've tried to fix the error by providing a type of `class` property in `IntrinsicAttributes` interface in jsx.d.ts file, and the problem has gone, but seems like the solution must be provided by Volar itself.
```typescript
declare namespace JSX {
  interface IntrinsicAttributes {
    class?: any;
  }
}
```

2. The next problem is about property 'slot':
`Property 'slot' does not exist on type 'ElementAttrs<HTMLAttributes>'.`
![image](https://user-images.githubusercontent.com/19515610/177140707-21a8bf6f-0b2b-4d4f-9710-932dcd5f6d67.png)

I've tried to solve this as well as `class`-property problem, but it didn't help. VS Code shows that property exists in `JSX.IntrinsicAttributes` interface, but compiler still throws the same.

Extending `HTMLAttributes` interface in declaration of `vue/types/jsx` module in jsx.d.ts file didn't fix the error. But direct extension of `HTMLAttributes` interface in `node_modules/vue/types/jsx.d.ts` helped.

**Comment by NikhilVerma** [comment]
I have the same issue with `data-*` attributes.

```html
<template>
   <div :data-selected="selected"></div>
</template>
```

Results in

```
Type '{ dataSelected: boolean; "data-selected": boolean; }' is not assignable to type 'ElementAttrs<HTMLAttributes>'.
  Property 'dataSelected' does not exist on type 'ElementAttrs<HTMLAttributes>'.ts(2322)
```

**Comment by NikhilVerma** [comment]
Here is my solution

`shims.d.ts.`
```ts
declare module "vue/types/jsx" {
	export interface HTMLAttributes {
		[key: `data${any}`]: any;
		[key: `aria${any}`]: string;
	}
}

export {};
```
