### ISSUE TITLE
Hide "Highlight dom elements"?

### ISSUE THREAD

**Issue by joshstobbs** [johnsoncodehk/volar#1535]
Hey there!

Thanks so much for all the hard work on this - I was wondering is there a way to disable the "highlight dom elements" toggle?

![CleanShot 2022-07-04 at 20 43 04](https://user-images.githubusercontent.com/57326077/177229393-e51d0201-9805-42b4-a00c-6edcdc70d7b2.png)

It looks like I can disable it if I disable Codelens across board though I'd prefer not to do that if possible.  I've looked around for answers and have found this older PR (https://github.com/johnsoncodehk/volar/issues/1209) though I can't find the associated option in Settings.

Thanks so much!

**Comment by andrekolmeijer** [comment]
Yeah I'd say that toggle belongs in the status bar. Or title bar. Or View -> Appearance. Anyway, I was wondering the same thing. Thanks for asking!
