### ISSUE TITLE
template v-for typescript error

### ISSUE THREAD

**Issue by fansheng0594** [johnsoncodehk/volar#1545]
## problem
Open in vscode notice typescript error, but in phpstorm normal.

## code
```vue
<script setup lang="ts">
type Book = {
    id: number,
    title: string,
}
defineProps<{books: Book[]}>()
</script>

<template>
    <div v-for="book in books" :key="book.id">
        <div>
            <span>{{ book.title }}</span>
        </div>
    </div>
</template>
```

## In vscode
 <img width="554" alt="image" src="https://user-images.githubusercontent.com/32379148/178090943-17ec6e7c-3306-4f09-8f83-32f0b5c63efa.png">

- <img width="554" alt="image" src="https://user-images.githubusercontent.com/32379148/178090996-29f8e704-5dc9-4f15-84b2-3e95df48d248.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/32379148/178090977-9dc2ff94-ba94-4dd0-94eb-b7decfedc59d.png">

## In phpstorm
<img width="557" alt="image" src="https://user-images.githubusercontent.com/32379148/178091176-04aeac77-93f1-4477-9adf-54008eda53bb.png">

**Comment by johnsoncodehk** [comment]
Please try update your VSCode and workspace TS version if it can.
