### ISSUE TITLE
Inconsistent formatting effect

### ISSUE THREAD

**Issue by ywtboy** [johnsoncodehk/volar#1550]
In some files, there are two spaces:
![image](https://user-images.githubusercontent.com/30440750/178140917-c79acdf5-2ab3-4972-81ab-a8cbcac0ed55.png)
In some files, four spaces
![image](https://user-images.githubusercontent.com/30440750/178140991-ac72d470-30f4-4d08-a5b4-213d1a4d1016.png)
plugins:
![image](https://user-images.githubusercontent.com/30440750/178141000-853fac2d-bcc9-4170-b1f3-3adb1ab23b9a.png)
settings:
![image](https://user-images.githubusercontent.com/30440750/178141015-5f592776-66f5-4e10-a4fb-74debfc21abd.png)

**Comment by johnsoncodehk** [comment]
See https://code.visualstudio.com/docs/editor/codebasics#_indentation
