### ISSUE TITLE
Two color blocks displayed when enable this extension

### ISSUE THREAD

**Issue by awxiaoxian2020** [johnsoncodehk/volar#1552]
![20220711085746](https://user-images.githubusercontent.com/69554233/178169998-97e87c1c-d581-470e-b43c-7e2d185ef494.png)
See also https://github.com/microsoft/vscode/issues/154688

**Comment by awxiaoxian2020** [comment]
@johnsoncodehk It seems the bug still exists in `.vue` files.
![22](https://user-images.githubusercontent.com/69554233/178238284-64a0d226-4183-402b-b924-1378b9339d1f.png)

**Comment by johnsoncodehk** [comment]
@awxiaoxian2020 You should disable Vetur.
