### ISSUE TITLE
Vue class binding problem after updated the extension.

### ISSUE THREAD

**Issue by nor1c** [johnsoncodehk/volar#1553]
Hello!

So, I'm working on my project this morning, it's all good and nothing wrong happened until the extension auto-updated, and it start to recognize the binding code as a typescript type annotation and the rest of code below it turns into white.

My English is not very well, but you can see screenshots below so you can know what exactly happened.

![image](https://user-images.githubusercontent.com/7555972/178224213-c3e15e64-109c-4ea3-aa3b-e8c158700792.png)
_<p align="center">without volar installed</p>_

<br>

![image](https://user-images.githubusercontent.com/7555972/178224177-52483d67-1412-4076-9a50-5ea8d5008d77.png)
<p align="center">with volar 0.38.4 installed</p>
<br>

### **Also**, 
it look good in version 0.38.3 (see the image below), so I think it's a bug from the latest version (0.38.4)

![image](https://user-images.githubusercontent.com/7555972/178226169-141535de-fc58-43ed-8755-e53539c832a1.png)

<br>

**Additional information**
OS: Windows 10
VS Code: latest
Volar: 0.38.4 (latest)

<br><br>

_Thank you._

**Comment by johnsoncodehk** [comment]
Hi @nor1c, could you paste the code to issue in text?

**Comment by tomsq** [comment]
For example, this code is causing the issue:

```html
<div class="md:w-56 sm:w-80"></div>
```

Also, Tailwind's arbitrary values with colors inside: e.g.

```html
<div class="bg-[#ffffff]"></div>
```

Or

```html
<div class="group-hover:block"></div>
```

Next issue: `@assets` is highlighted in following code

```html
<img src="@assets/someimage.png" alt="SomeImage" />
```

Thank you for your great work! Volar is incredibly powerful and helpful.

**Comment by LoiLock** [comment]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/33485182/178244520-b60a0391-176e-45a7-ba4d-d8a2a9814064.png">
Also applies when casting types in style bindings

**Comment by fanzihui** [comment]
+1, I've got the same issues running version 0.38.5

**Comment by IIFelix** [comment]
https://github.com/johnsoncodehk/volar/commit/abbd29f0dc0682c4a2d129c374a18baa9a6f3069
This change is responsible for this. Would like to fix it but regex is just not my thing ..

**Comment by agm1984** [comment]
My code has a common pattern of declaring state-dependant classes in an object appended to an array, such as:

```vue
<div
    :class="['class1 class2 class3', {
        class4: true,
        'class-5': false,
    }]"
>
```
`'class-5': false,` breaks the syntax highlighting in many of my files.
