### ISSUE TITLE
vetur and volar about compatibility issue

### ISSUE THREAD

**Issue by cpWhitecat** [johnsoncodehk/volar#1562]
### when I only install **vetur(v0.35.0)** and **volar(v0.38.5)** in **vscode(v1.69.0)** ,  the code hints are repetitive and the color also  repetitive

![image](https://user-images.githubusercontent.com/93856406/178279006-bba4cffb-616c-4186-9287-9762d3b6a506.png)

### when i uninstall one of extensions , this issue will been resolved

other environment
```
Version: 1.69.0 (user setup)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by kingyue737** [comment]
volar and vetur cannot be used together. This is documented: 
https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#vetur
You need to disable vetur in workspace.
