### ISSUE TITLE
Highlight problem when v-xxx attribute contains a "[{a: []}]"

### ISSUE THREAD

**Issue by sswater** [johnsoncodehk/volar#1564]
When v-xxx attribute contains a "[{a: []}]", the highlight is wrong. When "[{a:[]}]" (no space), the highlight is OK
![WX20220712-132128](https://user-images.githubusercontent.com/5098724/178415074-2fe3ca06-fbb0-4c21-8fd9-b813118e3591.png)

**Comment by WormGirl** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/16078260/178431514-055a1e3d-b15b-49dc-80ad-38262695180d.png)

**Comment by Zauberbutter** [comment]
It seems that this issue was introduced with [v0.38.4](https://github.com/johnsoncodehk/volar/releases/tag/v0.38.4).

**Comment by johnsoncodehk** [comment]
Please use 0.38.3 for now.

**Comment by shaobeichen** [comment]
It's 0.38.5 version now, I  tried reinstall after uninstall, but it still doesn't work
