### ISSUE TITLE
Object with quoted key breaks highlighting

### ISSUE THREAD

**Issue by doominator42** [johnsoncodehk/volar#1568]
![20220712_195016](https://user-images.githubusercontent.com/45132909/178617723-f16df0cd-1057-4233-9208-a04622002abf.png)

Happens only when there are parentheses around the object.
Versions `0.38.4` and `0.38.5` are affected, `0.38.3` works fine.

**Comment by fanzihui** [comment]
+1, I'm having the same problem
![image](https://user-images.githubusercontent.com/8360311/178636186-669f718e-2562-470c-8790-ac4be7fd999d.png)

**Comment by doominator42** [comment]
@LoiLock oh yeah it's the same. I overlooked that one for some reason.
