### ISSUE TITLE
标签内颜色字符串高亮不正确

### ISSUE THREAD

**Issue by yeyuqh** [johnsoncodehk/volar#1569]
## v0.38.5
![v0.38.5](https://s2.loli.net/2022/07/13/o7pr3aFzqetAGSv.png)
## v0.38.3
![v0.38.3](https://s2.loli.net/2022/07/13/ye4pcrOfgKDYl8T.png)

**Comment by ZhouYC404** [comment]
我这更离谱。。
![image](https://user-images.githubusercontent.com/69456034/178888538-9ca2d8e5-5cca-4adf-ac98-c94b805cd841.png)
