### ISSUE TITLE
With take over mode and disable built-in ts LSP, folding doesn't work in the ts/js file

### ISSUE THREAD

**Issue by imyangyong** [johnsoncodehk/volar#1571]
![Snapshot@2x](https://user-images.githubusercontent.com/42476396/178717667-50707fa3-eba5-4cd6-86a8-b974871b69e2.png)

**Comment by imyangyong** [comment]
VSCode version 1.69.1

**Comment by wangxdmm** [comment]
same issue +1

**Comment by doecs** [comment]
same issue +1

**Comment by johnsoncodehk** [comment]
Duplicate of #1563
