### ISSUE TITLE
Component autocomplete in template doesn't work for libraries/modules

### ISSUE THREAD

**Issue by Doeke** [johnsoncodehk/volar#1575]
Currently autocomplete in template is limited to importing local component files directly. It would be nice if it detected exported components from library 

In script:

![image](https://user-images.githubusercontent.com/240530/178935309-3193ab90-d666-4100-aebd-56fc46fee401.png)

In template:

![image](https://user-images.githubusercontent.com/240530/178935539-1d78ebbb-516b-4c04-8996-e348fb06b5a3.png)

Is this doable to implement?

**Comment by johnsoncodehk** [comment]
Please track #1643
