### ISSUE TITLE
Syntax highlighting in Vue files isn't working when using v-bind class with array and string object-keys

### ISSUE THREAD

**Issue by agm1984** [johnsoncodehk/volar#1579]
![image](https://user-images.githubusercontent.com/17655219/179136591-9dfaa18a-b2f7-471b-9749-c543c51f6705.png)
![image](https://user-images.githubusercontent.com/17655219/179136633-52ae6f03-b88e-4add-aa44-57c8727d77c3.png)

I updated VS Code earlier today and now this one file is broken. It seems to have something to do with the code:

``` vue
<template>
    <div
        :class="['filters-pane', {
            'w-0': !isActive,
            active: isActive,
        }]"
    >
```

The problem goes away if I remove `'w-0': !isActive,`

Background info: when I run VS Code with `code . --disable-extensions`, all syntax highlighting in the Vue file goes away. I also tried the following steps:
1. uninstall Volar
2. restart VS Code
3. reinstall Volar
4. restart VS Code

Still broken.

**Comment by lloydaarn** [comment]
I have the same issue. using a string for a class in v-bind:class with array syntax breaks the syntax highlighting. 
![image](https://user-images.githubusercontent.com/12797526/179157002-35a1fe2a-6f45-439f-bbea-20a3746f8ed3.png)

**Comment by lloydaarn** [comment]
working syntax highlighting when using object syntax in v-bind:class
![image](https://user-images.githubusercontent.com/12797526/179157383-fb7e70b8-1e25-4f7e-940d-b4ce23420cab.png)

**Comment by lloydaarn** [comment]
@agm1984 my temporary fix was reverting the volar version to 0.38.3
![image](https://user-images.githubusercontent.com/12797526/179160486-5394a616-ba5d-4fc7-a52a-a5ea0762bada.png)

**Comment by pegiadise** [comment]
Same issue here mostly with array objects in templates. Also reverted back to `0.38.3`.

**Comment by agm1984** [comment]
I fixed mine by refactoring the string key away:

``` vue
    <div
        :class="['filters-pane', {
            active: isActive,
        }]"
    >

...

<style>
.filters-pane {
    @apply w-0;
}
```

**Comment by agm1984** [comment]
This is a duplicate of https://github.com/johnsoncodehk/volar/issues/1553
