### ISSUE TITLE
It seems incompatible with yarn2 pnp

### ISSUE THREAD

**Issue by strrchr** [johnsoncodehk/volar#158]
With yarn2 pnp, volar falsely consider a vue3 project as vue2 project.

**Comment by johnsoncodehk** [comment]
Already fix inaccurate warning message in 0.24.2.

Incompatible with yarn2 pnp is upstream problem, TS dose not support it yet, so volar can't import types from `@vue/runtime-dom`.

See: https://github.com/Microsoft/TypeScript/issues/28289
