### ISSUE TITLE
从0.38.4开始 格式化ts文件key值后面不会添加空格

### ISSUE THREAD

**Issue by wishong** [johnsoncodehk/volar#1580]
例如
interface Test {
  id:string
}
之前格式化会在冒号之后添加空格，现在格式化不会添加空格，需要手动添加

**Comment by richex-cn** [comment]
What formatter do you use?

You can try `Ctrl+Shift+P` and then select `Format Document With...`.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/a01ef4675063a99b3f7aa4060f0cda75eca35143
