### ISSUE TITLE
未来是否能支持yarn3?

### ISSUE THREAD

**Issue by WhiteCoffee9834** [johnsoncodehk/volar#1581]
yarn3将node_modules文件移除了,采用了压缩包的形式存放依赖

![图片](https://user-images.githubusercontent.com/72718918/179141595-7f195242-3553-4d6a-96c3-657d9c8f8bd5.png)
在ts文件中能有效提示出依赖的位置

但在vue文件中却找不到
![图片](https://user-images.githubusercontent.com/72718918/179141683-4576bcd2-b85f-4fb0-8c37-5b3297e716f2.png)

项目运行正常,没有问题.

**Comment by johnsoncodehk** [comment]
Duplicate of #918
