### ISSUE TITLE
性能瓶颈已经验证影响到插件几乎无法正常工作

### ISSUE THREAD

**Issue by itmanyong** [johnsoncodehk/volar#1582]
1.volar内存占用率太高,关闭volar比开启volar低了15个点
2.除了着色渲染,volar严重影响vscode的代码提示,不只是*.vue文件.
3.差距如下图,差异仅仅是开启/关闭volar的对比
开启volar状态:
![开启volar](https://user-images.githubusercontent.com/53500371/179189147-52b4562f-8a45-4028-93f9-a6e53ce15ccf.gif)
关闭volar状态
![关闭volar](https://user-images.githubusercontent.com/53500371/179189201-78de9c75-6035-4ea8-ac5e-e09e24d8572f.gif)

tip：与硬件性能毫无关系,即使是如下配置，也是一样。
![image](https://user-images.githubusercontent.com/53500371/180639417-3370e6b4-382a-448d-b1db-02ff928c4427.png)

**Comment by WhiteCoffee9834** [comment]
看上去你使用了tabnine
可能是冲突了

**Comment by itmanyong** [comment]
@WhiteCoffee9834 并没有,无论是禁用tabnine还是卸载tabnine。还好已经找到了其他着色+语法插件搭配,相比volar体验来说，回到了最初的丝滑。

**Comment by yuyinws** [comment]
> @WhiteCoffee9834 并没有,无论是禁用tabnine还是卸载tabnine。还好已经找到了其他着色+语法插件搭配,相比volar体验来说，回到了最初的丝滑。

其他插件是指什么呢 能否分享一下😀

**Comment by aring1998** [comment]
> > @WhiteCoffee9834 并没有,无论是禁用tabnine还是卸载tabnine。还好已经找到了其他着色+语法插件搭配,相比volar体验来说，回到了最初的丝滑。
> 
> 其他插件是指什么呢 能否分享一下😀

求插件+1

**Comment by JamesLIAOHJ** [comment]
did you try this  setting option?  `"volar.vueserver.useSecondServer": true`

**Comment by Inori-Lover** [comment]
> did you try this setting option? `"volar.vueserver.useSecondServer": true`

a little better but not too much, it still far more slower than normal ts project.
hope volar will focus on this more

**Comment by itmanyong** [comment]
@yuyinws @funzeros @aring1998 Vue3 Support - All In One    +   Vue VSCode Snippets     简直爽，除流畅外基本和volar没太大区别。可以尝试一下

**Comment by llk2yq** [comment]
@itmanyong 我试了一下好像没有代码提示啊，不管是TS还是模板中。

**Comment by pecopeco** [comment]
> @yuyinws @funzeros @aring1998 Vue3 Support - All In One + Vue VSCode Snippets 简直爽，除流畅外基本和volar没太大区别。可以尝试一下

代码提示自动补全这些功能都无法满足

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1529#issuecomment-1232572335.
