### ISSUE TITLE
Unable to run volar in BBEdit

### ISSUE THREAD

**Issue by viewfromthesky** [johnsoncodehk/volar#1583]
Currently debugging the server when running through the custom language settings in BBEdit (`vls` works fine). In the custom language settings for Vue.js I've specified the following settings (after realising the executable for the server is a `.js` file):

![Screenshot 2022-07-15 at 22 47 29](https://user-images.githubusercontent.com/47668096/179315588-a5a3dd8e-1c9a-44ad-9b39-163e780a4dc5.png)

This didn't work alone, but BBEdit allows providing `initializationOptions` which I nicked from this repo, which works great in Nova: https://github.com/tommasongr/nova-vue

The resultant options file is as follows:
```json
{
	"initializationOptions":
	{
		"typescript":
		{
			"serverPath": "/Users/tom/.nvm/versions/node/v14.19.1/bin/tsserver",
		},
		"languageFeatures":
		{
			"references": true,
			"implementation": true,
			"definition": true,
			"typeDefinition": true,
			"callHierarchy": true,
			"hover": true,
			"rename": true,
			"renameFileRefactoring": true,
			"signatureHelp": true,
			"codeAction": true,
			"workspaceSymbol": true,
			"completion":
			{
				"defaultTagNameCase": "both",
				"defaultAttrNameCase": "kebabCase",
				"getDocumentNameCasesRequest": false,
				"getDocumentSelectionRequest": false,
			},
			"documentHighlight": true,
			"documentLink": true,
			"codeLens":
			{
				"showReferencesNotification": false
			},
			"semanticTokens": true,
			"diagnostics": true,
			"schemaRequestService": true,
		},
		"documentFeatures":
		{
			"selectionRange": true,
			"foldingRange": true,
			"linkedEditingRange": true,
			"documentSymbol": true,
			"documentColor": true,
			"documentFormatting": true
		}
	}
}
```

Now as far as I can see, there's nothing wrong with this, but the server is crashing on startup... Any idea what this error might mean or what's wrong with my config?

```
2022-07-15 22:34:53.106: Error starting LSP server at /Users/tom/.nvm/versions/node/v14.19.1/bin/npx: Error Domain=LSPResponseError Code=-32603 "Request initialize failed with message: Invalid Version: undefined" UserInfo={NSLocalizedDescription=Request initialize failed with message: Invalid Version: undefined}
```

**Comment by viewfromthesky** [comment]
That did the job; the server's now running in BBEdit, thanks!

Is the `initializationOptions` config documented anywhere here or is that a Language Server Protocol default config? I wasn't sure how to get this started without looking through someone else's code to get it working

**Comment by yaegassy** [comment]
It is not documented. You can check the type with this code.

- <https://github.com/johnsoncodehk/volar/blob/master/packages/shared/src/types.ts#L5-L86>
