### ISSUE TITLE
Property * does not exist on type '{}'.

### ISSUE THREAD

**Issue by seahindeniz** [johnsoncodehk/volar#1584]
Hi,
I just create a new project with `npm create vite@latest` and tried to test Volar with Vue 3 for the first time. However, seems like there's something wrong, or I may have done something incorrect.

I have changed the initial Composition API to Options API and created some component and store states. After that, I have these errors
![image](https://user-images.githubusercontent.com/5789670/179397799-c5f783dd-2969-4f64-8443-ecbc0973b967.png)

The only thing that doesn't get affected is the `setVisibility` action.

I'm not sure if this related to Pinia either. 

Here's the MRE repo https://github.com/seahindeniz/volar-vue-js-issue

<sub>Version: 1.70.0-insider</sub>
<sub>Commit: 1cd90cceddf3c413673963ab6f154d2ff294b17c</sub>
<sub>Date: 2022-07-15T05:32:19.076Z</sub>
<sub>Electron: 18.3.5</sub>
<sub>Chromium: 100.0.4896.160</sub>
<sub>Node.js: 16.13.2</sub>
<sub>V8: 10.0.139.17-electron.0</sub>
<sub>OS: Darwin arm64 21.5.0</sub>

**Comment by andre-aaspere** [comment]
Had same issue, downgraded Volar to 0.38 to make the error go away.

**Comment by seahindeniz** [comment]
I didn't want to downgrade, and the only workaround I have found so far was creating the component via `defineComponent` function.

Here's the commit https://github.com/seahindeniz/volar-vue-js-issue/commit/2618789b5da21d49ba2e04e55fc4cca20dbdc178

![image](https://user-images.githubusercontent.com/5789670/182411969-3ba9cb1a-a64c-434a-b633-31172f1d8bbd.png)
