### ISSUE TITLE
Bug: Instance properties appear in components list

### ISSUE THREAD

**Issue by g-plane** [johnsoncodehk/volar#159]
![图片](https://user-images.githubusercontent.com/17216317/116015461-ec3c0500-a66b-11eb-97ac-c10874ed9651.png)

As the screenshot shows, instance properties shouldn't be showed in components completion list.

**Comment by johnsoncodehk** [comment]
This is expected, because these ones is subtypes of `FunctionalComponent`.

```ts
// true
type IsComponent = typeof $emit extends FunctionalComponent<infer _> ? true : false;
```

**Comment by g-plane** [comment]
So strange...Is there a workaround?

**Comment by johnsoncodehk** [comment]
@pikax can you take a look to this problem?

**Comment by pikax** [comment]
> @pikax can you take a look to this problem?

This is a bit tricky since `FunctionalComponent` kinda looks the same as the `$emit`

You can validate the functional component like this:
```ts
type IsComponent<T> = T extends FunctionalComponent<infer P>
  ? P extends object ? true : false // `P` should be always an object on a functional component, but on emit extends `string`
  : false
```

**Comment by johnsoncodehk** [comment]
@pikax thanks, but that may handle well, there have more other properties like `$d`, `$el`, `$n`... and these ones can be any other Prop type.

I'm not sure if this is appropriate, can we make some FunctionalComponent properties not optional.
For example, maybe change `__file?: string` to `__file: string | undefined`.

**Comment by pikax** [comment]
> I'm not sure if this is appropriate, can we make some FunctionalComponent properties not optional to block these function type variables?

I'm afraid that is not possible because that would break a simple `function`: 
```ts
      function MyFunctionalComponent(p: { a: 1}) {
        return h('div', p.a)
      }
      type FunctionComponent = IsComponent<typeof MyFunctionalComponent>
```

This changes will affect users [using Javascript](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8TXlDb21wIGE9XCJIZWxsbyB0aGVyZVwiPjwvTXlDb21wPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IGggfSBmcm9tICd2dWUnXG5cbmZ1bmN0aW9uIE15Q29tcChwKXtcblx0cmV0dXJuIGgoJ2RpdicsIHAuYSlcbn1cbjwvc2NyaXB0PiJ9)
```html
<template>
  <MyComp a="Hello there"></MyComp>
</template>

<script setup>
import { h } from 'vue'

function MyComp(p){
	return h('div', p.a)
}
</script>
```



> @pikax thanks, but that may not handle well, there have more other properties like `$d`, `$el`, `$n`... and these ones can be any other Prop type.

I reckon this only affects the `script setup`, right?

**Comment by johnsoncodehk** [comment]
> I reckon this only affects the script setup, right?

@pikax Unfortunately, widespread impact. 😅

Or can we narrow the FunctionComponent caller return type?

`(props: P, ...): any` -> `(props: P, ...): ComponentPublicInstance<...> // or other`

**Comment by pikax** [comment]
Can you give some examples on what's breaking on your side? I can think on ways to improve it, `DefineComponent` should be straight forwards to get the type. 

You could also just make a "rule": Only the `defineComponent` (and `components:[]`) components are available on the template. Which I think is a reasonable request, and it wouldn't break the upstream users

**Comment by johnsoncodehk** [comment]
@pikax of course, sorry I should give this first.

```ts
import { defineComponent, FunctionalComponent } from '@vue/runtime-core';

type ExtractFunctionalComponents<T> = { [K in keyof T as T[K] extends FunctionalComponent<infer _> ? K : never]: T[K] }
const component = defineComponent({
    setup() {
        return {
            foo: () => 123,
            bar: () => 'str',
        };
    }
});
const localComponents: ExtractFunctionalComponents<InstanceType<typeof component>>;
localComponents. // doing auto-complete here should not have `foo`, `bar`
```

---

This two way also can fix it:

1.

> EDIT: Probably this is a more correct component for your needs
> 
> ```ts
> type IsComponent<T> = T extends (p: any, ctx?: any) => VNode
>   ? true
>   : false
> ```

2.

> Or can we narrow the FunctionComponent caller return type?
> 
> `(props: P, ...): any` -> `(props: P, ...): VNode // or other`

If FunctionComponent is not easy to change, I think I can use the way 1.

**Comment by pikax** [comment]
Check this  [playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICBcdDxmb28+PC9mb28+XG4gICAgPGJhcj48L2Jhcj5cbiAgICA8TXlDb21wIGE9XCIyeHgyMlwiPjwvTXlDb21wPiAgXG4gICAgPCEtLTxPdGhlckNvbXA+PC9PdGhlckNvbXA+LS0+XG4gIDwvZGl2PlxuIFxuICA8aHIvPlxuICBcbiAgPENvbXA+PC9Db21wPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7aH0gZnJvbSAndnVlJ1xuICBcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG5cbmNvbnN0IGZvbz0gKCkgPT4gMTIzO1xuY29uc3QgYmFyPSAoKSA9PiBcInN0clwiO1xuY29uc3QgTXlDb21wID0gKHApID0+IGgoXCJkaXZcIiwgcC5hKTtcbmNvbnN0IE90aGVyQ29tcCA9IHt9O1xuPC9zY3JpcHQ+IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+XG4gIERvZXNuJ3Qgc2hvdyBpZiByZXR1cm5lZCBvbiB0aGUgc2V0dXBcblx0PGZvbz48L2Zvbz5cbiAgICA8YmFyPjwvYmFyPlxuICAgIDxNeUNvbXAgYT1cImFhZWQzXCI+PC9NeUNvbXA+ICBcbiAgICA8IS0tPE90aGVyQ29tcD48L090aGVyQ29tcD4tLT5cbjwvdGVtcGxhdGU+XG48c2NyaXB0PlxuaW1wb3J0IHsgZGVmaW5lQ29tcG9uZW50LCBoIH0gZnJvbSBcInZ1ZVwiO1xuXG5leHBvcnQgZGVmYXVsdCBkZWZpbmVDb21wb25lbnQoe1xuICBzZXR1cCgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgZm9vOiAoKSA9PiAxMjMsXG4gICAgICBiYXI6ICgpID0+IFwic3RyXCIsXG4gICAgICBNeUNvbXA6IChwKSA9PiBoKFwiZGl2XCIsIHAuYSksXG4gICAgICBPdGhlckNvbXA6IHt9LFxuICAgIH07XG4gIH0sXG59KTtcbjwvc2NyaXB0PiJ9)
 
 `foo` and `bar` are valid components actually (if used in script setup)

**Comment by johnsoncodehk** [comment]
@pikax I see... So actually I should keep this behavior. Thanks to check it!

@g-plane do you agree to close this issue?

**Comment by pikax** [comment]
I would exclude if the key starts with `$`

Something of sorts
```ts
type ExtractFunctionalComponents<T> = {
  [K in keyof T as K extends `$${string}`
    ? never
    : IsFunctionalComponent<T[K]> extends true
    ? K
    : T extends DefineComponent<
        any,
        any,
        any,
        any,
        any,
        any,
        any,
        any,
        any,
        any,
        any,
        any
      >
    ? K
    : never]: T[K];
};
```

**Comment by johnsoncodehk** [comment]
`<$foo>` report illegal tag name in vue compiler, so yes I can filter it, thanks again!
