### ISSUE TITLE
Typescript 错误报错

### ISSUE THREAD

**Issue by chivesssss** [johnsoncodehk/volar#1590]
当多个项目以 **工作区** 的方式同时打开时，在0.38.6之前不会有任何问题

<img width="507" alt="image" src="https://user-images.githubusercontent.com/23553358/179470320-94031a8a-8355-4ad3-ac41-d4911553f601.png">

0.38.7 版本以后

<img width="732" alt="image" src="https://user-images.githubusercontent.com/23553358/179470587-ee81b27c-fead-4d2c-881e-2f3e53c6d56c.png">

当 **单独** 打开该项目时，0.38.6，0.38.7，0.38.8 均不会提示报错。

**Comment by web-xp** [comment]
我也遇到这个问题

**Comment by chivesssss** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/23553358/180642202-53ea8b13-f8e9-4596-a0f9-b052f0f762ff.png">

**MAC 系统，0.39.1 版本问题依然存在**
