### ISSUE TITLE
vscode 下部分文件中的函数无法ctrl+左键跳转

### ISSUE THREAD

**Issue by supf1994** [johnsoncodehk/volar#1591]
在vscode下使用typescript，部分模块下函数无法通过 ctrl+左键 进行跳转定位，但鼠标放上去可以正确显示函数的声明信息

**Comment by extclp** [comment]
#1585

**Comment by Archsx** [comment]
> > #1585
> 
> 这些均已配置，程序可以正常运行，编译也没问题，将鼠标放于类型或函数上面，也能正确的显示声明信息，但是有些函数或类型的定义无法跳转，不管是用 ctrl+左键 或者右键转到定义均不行， 右键转到定义点击后会提示 未找到“xxxxxxx”的任何定义，这个问题只会在vue文件中出现，在纯ts文件下测试没有这个问题

我也遇到了这个问题，安装之前的某个版本(比如v0.37.0)可以解决，但是到底是哪个版本开始出现这个问题还不了解.

**Comment by Archsx** [comment]
> > > > #1585
> > > 
> > > 
> > > 这些均已配置，程序可以正常运行，编译也没问题，将鼠标放于类型或函数上面，也能正确的显示声明信息，但是有些函数或类型的定义无法跳转，不管是用 ctrl+左键 或者右键转到定义均不行， 右键转到定义点击后会提示 未找到“xxxxxxx”的任何定义，这个问题只会在vue文件中出现，在纯ts文件下测试没有这个问题
> > 
> > 
> > 我也遇到了这个问题，安装之前的某个版本(比如v0.37.0)可以解决，但是到底是哪个版本开始出现这个问题还不了解.
> 
> 好像半个月前写代码的时候还没有这个问题，今天要写突然就出现，记得并不清楚，也不知道是不是之前没碰到

我感觉应该提英文的issue，所以我已经用散装英语提了一个 #1593

**Comment by macheteHot** [comment]
应该是 export default 在 windows 下 vue 中 的 import 无法跳转

**Comment by heibaikn** [comment]
https://github.com/johnsoncodehk/volar/issues/1593#issuecomment-1188917811

**Comment by Zeng0716** [comment]
我的vscode也不行,vue文件可以,jsx文件倒不行,连右键都不显示转到定义

**Comment by xhsxq** [comment]
安装vue-helper这个插件，然后重启vscode就好了

**Comment by xuyucheng** [comment]
楼上正解，找了好久的方法
