### ISSUE TITLE
vue文件的文件名会影响tsconfig的读取？

### ISSUE THREAD

**Issue by supf1994** [johnsoncodehk/volar#1592]
![image](https://user-images.githubusercontent.com/23397492/179503779-9217ed06-c842-4cf1-8937-17bd33c9c110.png)
我将文件名设置成 CookView.vue， vs右下方就会显示 No tsconfig
![image](https://user-images.githubusercontent.com/23397492/179503943-3689e765-9d79-492c-bbe6-2b2d67f4d272.png)
将其该下名字，又能正常的读取tsconfig，
并且这会影响代码提示，导致一些导入的module路径下出现红线

**Comment by Inori-Lover** [comment]
u can try exit the vscode and wait a little time then restart; i more like volar get stuck in some where;

and may be roll back volar version will work(i keep use 0.38.3), keep in mind: every time u change the volar version, try do above actions

====

试下退出vscode并等一阵子（大概3-5分钟？）再重启，这看起来更像是volar在解析这个文件时遇到了点什么问题然后这个错误一直缓存在那每次打开都被这个错误block了

以及可以尝试下回滚volar版本（我暂时停在0.38.3了），注意每次回滚都重复一下上边的操作，或者f1然后 'restart vue server' 可能也行

// ↓ 修改链接里的版本就可以下载不同的版本了
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.38.3/vspackage?targetPlatform=win32-x64

**Comment by Inori-Lover** [comment]
我之前也以为system是一个关键词，最后改名绕过去了；
主要是想搞复现也搞不了…复现不出来

**Comment by supf1994** [comment]
> u can try exit the vscode and wait a little time then restart; i more like volar get stuck in some where;
> 
> and may be roll back volar version will work(i keep use 0.38.3), keep in mind: every time u change the volar version, try do above actions
> 
> ====
> 
> 试下退出vscode并等一阵子（大概3-5分钟？）再重启，这看起来更像是volar在解析这个文件时遇到了点什么问题然后这个错误一直缓存在那每次打开都被这个错误block了
> 
> 以及可以尝试下回滚volar版本（我暂时停在0.38.3了），注意每次回滚都重复一下上边的操作，或者f1然后 'restart vue server' 可能也行
> 
> // ↓ 修改链接里的版本就可以下载不同的版本了 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.38.3/vspackage?targetPlatform=win32-x64

是的，使用旧版之后可以正常的读取tsconfig文件，并且最近发现的无法部分函数无法跳转到定义的问题也解决了
#1591

**Comment by kingyue737** [comment]
是不是改过文件名大小写了？改文件名大小写会变成no tsconfig，以前也有人遇到过类似的问题

https://github.com/johnsoncodehk/volar/issues/1125

**Comment by Inori-Lover** [comment]
> 是不是改过文件名大小写了？改文件名大小写会变成no tsconfig，以前也有人遇到过类似的问题
> 
> #1125

确实…回忆了一下，我这边两次遇到这个情况都有这个操作

**Comment by supf1994** [comment]
> > 是不是改过文件名大小写了？改文件名大小写会变成no tsconfig，以前也有人遇到过类似的问题
> > #1125
> 
> 确实…回忆了一下，我这边两次遇到这个情况都有这个操作

是的，我刚刚测试了，修改文件名的大小写确实会有这问题
