### ISSUE TITLE
import ts file in .vue SFC file , `Ctrl + Click`  not jump to definition.

### ISSUE THREAD

**Issue by Archsx** [johnsoncodehk/volar#1593]
Basically the issue is almost same as #435 , I've use takeover mode, install previous version(eg: v0.37.0) can solve the problem.

V0.37.0:
![right](https://user-images.githubusercontent.com/21698481/179505805-3f902b98-653d-4ac5-a121-3edad1342c37.gif)

V0.38.8:
![wrong](https://user-images.githubusercontent.com/21698481/179505937-58a1a1da-10cb-4c66-b103-ca5be9137f80.gif)

**Comment by an501920078** [comment]
me too

**Comment by 001123** [comment]
Same issue

**Comment by BryanAdamss** [comment]
Same issue.

**Comment by 001123** [comment]
> > Same issue. I tried back to `v0.38.6` and it works.
> 
> how to back to `v0.38.6`

![image](https://user-images.githubusercontent.com/32441266/179729068-4fd7d2f9-db46-4499-a6c1-132833587d6d.png)
Click on gear -> select install other version

**Comment by heibaikn** [comment]
> > Same issue. I tried back to `v0.38.6` and it works.
> 
> how to back to `v0.38.6`

>
https://marketplace.visualstudio.com/items?itemName=Vue.volar  , download 
![image](https://user-images.githubusercontent.com/17714507/179735904-045836cc-3174-4d28-9efa-890fb2756921.png),    
then  import in vscode ,

![image](https://user-images.githubusercontent.com/17714507/179735953-02c7fcc4-e5e0-4e53-aed6-59c3c9042132.png)

**Comment by BryanAdamss** [comment]
> > > Same issue. I tried back to `v0.38.6` and it works.
> > 
> > 
> > how to back to `v0.38.6`
> 
> ![image](https://user-images.githubusercontent.com/32441266/179729068-4fd7d2f9-db46-4499-a6c1-132833587d6d.png) Click on gear ⚙️ -> select install another version

It's work😀
