### ISSUE TITLE
As of version 0.38.4 volar Formatter conflicts with ESLint

### ISSUE THREAD

**Issue by GWIian** [johnsoncodehk/volar#1594]
Test in ESLint Standard mode

Volar formatting automatically removes Spaces before function argument parentheses when adding project folders to vscode workspace,This causes a ESLint error: Missing space before function parentheses

The following Settings have been set
`"javascript.format.insertSpaceBeforeFunctionParenthesis": true`
```
data() {   !!Missing space before function parentheses.
    ...
}
```

This doesn't happen when you open the project folder directly and will work with ESLint
```
data () {   \\It's Ok.
    ...
}
```

**Comment by GWIian** [comment]
> `javascript.format.insertSpaceBeforeFunctionParenthesis` works for me.
> 
> In case you're using `lang="ts"`, please make sure you also have config `typescript.format.insertSpaceBeforeFunctionParenthesis`.

This is fine if you open the project folder directly, but adding the project to the vscode workspace will cause the above problems.

**Comment by johnsoncodehk** [comment]
Maybe you have workspace VSCode settings which override `insertSpaceBeforeFunctionParenthesis` value.

**Comment by cirolosapio** [comment]
same issue here

insertSpaceBeforeFunctionParenthesis does not resolve

volar v1.2.0
