### ISSUE TITLE
language server error in tsx,  contain ctrl+click...

### ISSUE THREAD

**Issue by chenjiangui** [johnsoncodehk/volar#1597]
os: windows
vscode: latest
volar: v0.38.8

https://user-images.githubusercontent.com/18565140/179666935-d8fac129-ac39-4668-92a8-2cab792b0c74.mp4

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter, please provide minimal reproduction.
