### ISSUE TITLE
Having the same issue as in #685

### ISSUE THREAD

**Issue by davepile** [johnsoncodehk/volar#1598]
Crazy colors in vscode 1.69.1 , exactly as shown in #685

Non typescript Quasar project.

Was behaving fine. been away from it for about a week.

Disabled prettier, no change. Disable Volar, problem gone

**Comment by Yooling-lei** [comment]
i had same issue in 0.38.8, temporarily fixed by roll back to 0.38.3

**Comment by charliepy** [comment]
0.38.9 was just released. It seems to have helped me.

**Comment by mreduar** [comment]
> 0.38.9 was just released. It seems to have helped me.

I confirm that I have had this problem for about a week or maybe a little longer, and I believe it has been resolved with the latest update.
