### ISSUE TITLE
Props auto-completion weaknesses

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#160]
When I type a prop for a component, that is of type `string`, I usually don't need to store it in a variable somewhere, and I just pass it as a string. For example:

```vue
<v-component label="I am component!" />
```

But Volar always completes it as `:label=""`, and I have to remove `:` part, so my code looks clean 😅 

The same could be said for `boolean` props. I almost never need to pass a variable to it, I just use it like this:

```vue
<v-component disabled />
```

So I was wondering if it's possible to make an option in Volar to enable this behavior? Or make it default.

**Comment by johnsoncodehk** [comment]
This behavior already changed in 0.24.2. See: https://github.com/johnsoncodehk/volar/pull/154

**Comment by sheremet-va** [comment]
Thanks. Updated the extension, and now it works!
