### ISSUE TITLE
Typescript error / highlighting issue

### ISSUE THREAD

**Issue by ktotam1** [johnsoncodehk/volar#1600]
When I add a class to divs, the string highlighting messed up temporarily and I get this TS error:
![image](https://user-images.githubusercontent.com/6313219/179719882-fda5cc52-0643-4bf5-b36f-cbb5cbfe37ba.png)

**Comment by ktotam1** [comment]
Here is some more context
![image](https://user-images.githubusercontent.com/6313219/179721171-d00f2b0f-6a30-4c31-b17b-24dc73b7fea4.png)

**Comment by web-xp** [comment]
metoo

**Comment by ImFarel** [comment]
I have the same problem, try re-installing vscode and all the extension still producing this issue

**Comment by bakashigure** [comment]
I chose to downgrade to the previous version...
![image](https://user-images.githubusercontent.com/33803916/179798328-c1065134-42e3-4437-addb-87ea3e0a82ad.png)

**Comment by danmalear** [comment]
I was also having issues with volar being able to locate files in typescript import statements. @bakashigure your suggestion got me back up and running. I downgraded to v0.38.5 and all is well.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

If it can't, please provide minimal reproduction and describe how it occur.

**Comment by ktotam1** [comment]
It's very fickle, I can't consistently reproduce it. It happened in a .vue file with the following content: 
`
<template>
    <div class="container-plans">
        <div class="free-container">
            <div class="free-forever-header">Free Forever</div>
            <div class="information-free">
                <div class="free-title">
                    Free Package
                </div>
                <div class="free-body">
                    Addtional Text
                </div>
            </div>
        </div>
        <div class="paid-container">
            <div class="paid-forever-header">14 days Free Trial</div>
            <div class="information-paid">
                <div class="middle-tier">
                    <div class="title-middle">
                        Monthly Package
                    </div>
                    <div class="body-middle">
                        Body text
                    </div>
                </div>    
                <div class="highest-tier" >
                    <div class="title-highest">
                        Monthly Package
                    </div>
                    <div class="body-highest">
                        Something Else
                    </div>
                </div>
            </div>
        </div>

    </div>
</template>

<script>
import Button from "@/components/Buttons/Button.vue";
export default {
    components: { Button },
}
</script>

<style lang="scss">
.container-plans {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    .free-container {
    width: 33%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
        .free-forever-header {
            font-weight: bold;
            color: #fff;
            text-align: center;
            background-image: linear-gradient(to right, #00bcd4, #8e2d9c);
        }
    }
}

</style>`
If the error doesn't occur, try to add a div with a random class name.

**Comment by ktotam1** [comment]
The button import is not important and can be removed

**Comment by johnsoncodehk** [comment]
Has this problem happened since 0.38.9?

**Comment by ktotam1** [comment]
It seems like no

**Comment by johnsoncodehk** [comment]
I can reproduce it in https://github.com/nuxt-modules/design-tokens/blob/main/playground/pages/index.vue.
