### ISSUE TITLE
vue-tsc not allow v-for string

### ISSUE THREAD

**Issue by xiao-e-yun** [johnsoncodehk/volar#1604]
This code allows to compile and diagnosis
But vue-tsc will drop `error TS2407: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter, but here has type 'string'.`
```vue
<template lang="pug">
span(v-for="char in chars") {{char}}
</template>

<script lang="ts" setup>
const chars = ref("HelloWorld")
</script>
```

**Comment by xiao-e-yun** [comment]
![image](https://user-images.githubusercontent.com/67814228/179855108-9c6ff1b8-ea60-482f-94ef-ec13aaa9f08d.png)

**Comment by mesqueeb** [comment]
`v-for` is for arrays and objects

you could do `v-for="char in chars.split('')"`

**Comment by johnsoncodehk** [comment]
I can't reproduce this error, please try update your workspace TS version, if it can't fix please provide minimal reproduction.

**Comment by xiao-e-yun** [comment]
Sorry, I didn't notice it's not the latest version
```
- vue-tsc 0.29.8
+ vue-tsc 0.39.0
```
