### ISSUE TITLE
Highlighting and intellisense randomly stopped working

### ISSUE THREAD

**Issue by TerryDieckmann** [johnsoncodehk/volar#1608]
I've been using Volar for a while now but for a while now the auto-complete and highlighted colors for imported components (from eg npm packages) no longer work when using the Vue 3 Composition API. This has certainly worked.

The local components still work no matter which API I use in Vue 3.

What I notice is that when I use the Options API of Vue 3, and define the `components` property with the same component as I would have imported if I were using the Vue 3 Composition API, the auto-complete and the highlighted colors work like it is supposed to.

I only have these extensions enabled in Visual Studio Code:

**Docker (v1.22.1)
ESLint (v2.2.6)
Volar (v0.38.9)**

Nothing else. Downgrading didn't help and reloading/reinstalling didn't help either. Are there any other things I can try?

The photos below shows where it doesn't work:
![image](https://user-images.githubusercontent.com/18029728/180003739-af8dba5e-4c06-41a0-88e1-3809a0d31ac1.png)
![image](https://user-images.githubusercontent.com/18029728/180003907-0add9a7b-8e89-4cde-894a-a2f427e6928b.png)

The photo below shows where it does work:
![image](https://user-images.githubusercontent.com/18029728/180004047-bd6c3802-dacc-47b8-9726-5166c1a75d54.png)
![image](https://user-images.githubusercontent.com/18029728/180004090-a241d719-aafc-4ee3-a1ad-6b2487a844bf.png)
![image](https://user-images.githubusercontent.com/18029728/180004135-70c367c1-5ea2-4c68-886d-03b6527f7566.png)

**Comment by TerryDieckmann** [comment]
Working example of auto-complete (using the Options API):
![image](https://user-images.githubusercontent.com/18029728/180005006-52af008c-1504-4938-bde7-fcef92808d63.png)


Example of non-working auto-complete (using the Composition API)
![image](https://user-images.githubusercontent.com/18029728/180004909-ec749e54-bcd7-41e3-b243-04696916b38a.png)

**Comment by TerryDieckmann** [comment]
Uhm, now it's broken everywhere... It doesn't work now either when I use the options API. No highlighting, no auto-complete, nothing.

**Comment by johnsoncodehk** [comment]
Do you still have this problem with v0.40.13 / v1.0.0-alpha?
