### ISSUE TITLE
Syntax highlight is broken without semicolons (Automatic Semicolon Insertion) on Vue 3

### ISSUE THREAD

**Issue by JoaoHamerski** [johnsoncodehk/volar#1609]
# Without semicolons: 
![](https://i.imgur.com/twrWLdA.png)

# With semicolons:
![](https://i.imgur.com/QgNTfQa.png)

Vetur is already disabled.

**Comment by JoaoHamerski** [comment]
I figured out it was conflicting with Babel Javascript extension:
Name: Babel JavaScript
Id: mgmcdermott.vscode-language-babel
Description: VSCode syntax highlighting for today's JavaScript
Version: 0.0.36
Publisher: Michael McDermott
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

**Comment by TerryDieckmann** [comment]
You probably want to close this issue
![image](https://user-images.githubusercontent.com/18029728/180389809-3f278e67-7ce6-4421-bbca-ea28547281dc.png)
