### ISSUE TITLE
Props renaming doesn't work in setup

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#161]
Renaming props (when you rename them inside `props declaration` in `defineComponent` or `defineProps`) doesn't rename them inside `setup` function or inside `script setup`, but renames them everywhere else, including templates.

**Comment by johnsoncodehk** [comment]
This is upstream problem, and should be fix in next vue version. See: https://github.com/vuejs/vue-next/pull/3656

**Comment by sheremet-va** [comment]
I see! Thank you, waiting for the next release then!

**Comment by johnsoncodehk** [comment]
Close because not handle in this repo, thanks. :)
