### ISSUE TITLE
type imported for JSDoc is not recognised as "used" variable

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#1612]
To make it easy to jump to certain TS types, we can use JSDoc `{@link SomeType}` feature, so the type name will become a clickable hyper link in VSCode.

However, for this to work, the type must be imported in the file... See:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/3253920/180121105-e6f1848f-8171-43d2-b884-62f43ffb504d.png">

However, Volar in take-over mode doesn't recognise these types as "used variables" so it greys them out.

It's too confusing when it's greyed out, because we often delete unused imports when we come across them, multiple times breaking these JSDoc links.

Would be great of Volar could correctly colour the imported types! : )

**Comment by johnsoncodehk** [comment]
I can reproduce this problem without takeover mode in .ts, when remove `{@link ...}` and add it again unused report will not update, it should be TS problem, please forward to https://github.com/microsoft/TypeScript.
