### ISSUE TITLE
volar throw Request textDocument/foldingRange failed with message tips while in github.dev

### ISSUE THREAD

**Issue by we125182** [johnsoncodehk/volar#1613]
example: https://github.dev/element-plus/element-plus
open a vue file after installed volar plugin. it happens.
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/17947588/180143456-4b583b82-7ffd-49f4-909b-57b1169e49e1.png">

**Comment by johnsoncodehk** [comment]
Duplicate of #1479
