### ISSUE TITLE
type imported for slot type is not recognised as "used" variable

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#1614]
when only used as slot scope type, it's incorrectly greyed out, as if it is an "un-used import" while it's being used to type the slot scope.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/3253920/180153011-b1aa698e-f752-4e53-b2bd-d39c8799e265.png">

Would be great of Volar could correctly colour the imported types! : )

**Comment by mesqueeb** [comment]
@johnsoncodehk what is this pending? anything else I can help with?

**Comment by johnsoncodehk** [comment]
It should be supported since v0.40.0.

**Comment by mesqueeb** [comment]
@johnsoncodehk i confirmed it works great! 🎉 💯
