### ISSUE TITLE
Syntax highlight breaks on tsx class binding

### ISSUE THREAD

**Issue by extrem7** [johnsoncodehk/volar#1617]
![image](https://user-images.githubusercontent.com/24792876/180223416-24c94b22-89a0-4b55-8c24-a428bdcaa8b2.png)
![image](https://user-images.githubusercontent.com/24792876/180223588-4d5e859b-a644-4b79-9159-8b36a5839955.png)

**Comment by pikax** [comment]
It also breaks if you use arrays on a regular template
```html
<template>
  <div :class="['vallid', { 'marked-correct': isCorrect }]">
    // broken syntax highlight
    <div></div>
  </div>
</template>```
