### ISSUE TITLE
Vue 2.7 strictTemplates with custom HTML attributes

### ISSUE THREAD

**Issue by jfrs** [johnsoncodehk/volar#1619]
I have a `div` element that needs custom attributes like an ID and coordinates for a grid. I've tried to override the types but that doesn't seem to work with Vue 2.7.

![image](https://user-images.githubusercontent.com/4005764/180297395-30ddc255-a56e-4fa5-b6e0-87d2e19cb26c.png)

Reproduction repo: https://github.com/jfrs/volar-strict-vue27

**Comment by johnsoncodehk** [comment]
`HTMLAttributes` interface is from `node_modules/vue/types/jsx.d.ts`, so you need replace `vue/types/vnode` to `vue/types/jsx`.

```diff
declare module 'vue/types/vnode' {
  interface AllowedComponentProps {
    gsId?: string;
  }
}

- declare module 'vue/types/vnode' {
+ declare module 'vue/types/jsx' {
  interface HTMLAttributes {
    gsId?: string;
  }
}

export { };
```
