### ISSUE TITLE
Error on `import.meta` statements

### ISSUE THREAD

**Issue by kevinmarrec** [johnsoncodehk/volar#1621]
Using VSCode `1.69.2` & Volar `0.38.9` in `Take Over` mode.

![image](https://user-images.githubusercontent.com/25272043/180431950-4346fd7e-772b-4bcf-bf76-0a1fd0a159ec.png)

I have this TypeScript error in every `.ts` files having `import.meta` statements.

This is an Editor only error (no build/runtime issues) and only happens in `Take Over` mode.

Mentioned potential fix in tooltip is not relevant as my `tsconfig.json` do have `module` set to `ESNext`.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If it can't, please provide minimal reproduction.
