### ISSUE TITLE
高亮错误

### ISSUE THREAD

**Issue by 2A5F** [johnsoncodehk/volar#1625]
typescript的一些语法高亮错误

以前还只有 tsx 有问题，现在更新的 ts 都有问题了

![mmexport1658556761344.png](https://user-images.githubusercontent.com/13982338/180592968-647ae24c-c942-4636-8007-eea1ddad7200.png)![mmexport1658556756912.png](https://user-images.githubusercontent.com/13982338/180592971-5f1ffba3-c335-4feb-8957-7adfa29bdc78.png)

主要就是尾随 ! 和 as 有问题

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, please provide minimal reproduction, and nice to add the case into https://github.com/johnsoncodehk/volar/tree/master/packages/vue-test-workspace/syntax if it not have.

<img width="546" alt="螢幕截圖 2022-07-23 19 54 52" src="https://user-images.githubusercontent.com/16279759/180603791-a5333c72-b994-4d9a-a7cf-7d46b529eee3.png">

**Comment by 2A5F** [comment]
![image](https://user-images.githubusercontent.com/13982338/180604381-2833bf7c-6f54-4a4a-b74a-5b8a511d04b9.png)
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
If you have already update to latest volar version, please check your other extensions it may provide conflicting typescript syntax token.

**Comment by 2A5F** [comment]
![image](https://user-images.githubusercontent.com/13982338/180605590-c29ebb11-77ad-4adf-88ff-8e3f0bd96106.png)
试出来了

**Comment by fanzihui** [comment]
@2A5F Then how do you solve it, after all, you also have to use windicss.

**Comment by 2A5F** [comment]
@fanzihui endure
