### ISSUE TITLE
md file content hightlight parsed wrong in vscode

### ISSUE THREAD

**Issue by gyhyfj** [johnsoncodehk/volar#1628]
vscode verson: 1.69.2 （latest till 7/24）
volar verson: 0.39.1（latest till 7/24）

if I open volar extension in vscode, md file like this could be parsed wrong in vscode editor：

``````md
# h1

## h2

```vue
<script setup lang="ts">
type Props = {
  title?: string
  data?: number[]
}
// defineProps<Props>()
withDefaults(defineProps<Props>(), {
  title: 'default title',
  data: () => [1, 2, 3],
})
</script>
```

## h2

something..
another codeblock:

```
let i=0
```

## h2

something...

``````

Content after the end of vue codeblock  can be recognize as part of  codeblock 
If I switch to other extension like `vetur` for vue2,  md hightlight is correct.

However, if I insert a blank row before `// defineProps<Props>()` , everything'll works well again again

**Comment by johnsoncodehk** [comment]
It should be VSCode issue, you can it reproduce in .ts.

- type expression without semicolon
<img width="515" alt="螢幕截圖 2022-07-31 18 57 23" src="https://user-images.githubusercontent.com/16279759/182022909-61950ee6-4e73-4ef8-950b-924444830cf7.png">

- type expression with semicolon
<img width="540" alt="螢幕截圖 2022-07-31 18 58 17" src="https://user-images.githubusercontent.com/16279759/182022937-84d99a3d-987c-4078-9249-716ee624b2a0.png">
