### ISSUE TITLE
Not found in marketplace error in VSCodium - Why?

### ISSUE THREAD

**Issue by mikwee** [johnsoncodehk/volar#1630]
I installed Volar from Open VSX Registry on VSCodium. The moment it finished installing, I got this error: `The 1 extension(s) below, in workspace recommendations have issues: vue.volar (not found in marketplace)`. Why? Thank you.

**Comment by lokicalmito** [comment]
If I search for Volar on VSCodium I get this extension:
![image](https://user-images.githubusercontent.com/107685698/181226031-5349a7c5-abb1-4f68-be31-a0f4aee02c65.png)

It's not maintained buy Vue and I think it searches for the Volar from Vue. This extension is also outdated, it seems.

**Comment by filiptronicek** [comment]
Hi there, at Open VSX, we're working on fixing this (see https://github.com/open-vsx/publish-extensions/pull/626).

It would be really great if @johnsoncodehk and the team could consider publishing to Open VSX directly to prevent issues like this in the future 🙏. I would love to assist with the process if needed.

**Comment by anbraten** [comment]
linking https://github.com/johnsoncodehk/volar/pull/1255

**Comment by johnsoncodehk** [comment]
Resolved by #1255
