### ISSUE TITLE
Potential bug on SFC template section for custom events

### ISSUE THREAD

**Issue by shortaflip** [johnsoncodehk/volar#1631]
![vue](https://user-images.githubusercontent.com/23621173/180705754-8924c42a-39e4-48f8-84fe-4069a91b5e27.png)

The above photo displays an SFC that is using a component from the library PrimeVue.  The error on line 26 is a custom event defined in the PrimeVue [docs](https://primefaces.org/primevue/fileupload) that is suppose to emit an event of type `FileUploadSelectEvent`.  The error on the template seems to think that it should emit an event of type `Event` instead.

I am wondering if this stems from Volar?  As I turn off my extensions, the SFC seems to only be affected by that extension.

IDE is vscode with the following plugins:
* Volar v0.39.1
* JavaScript (ES6) code snippets v1.8.0
* Monokai Pro v1.1.20
* GraphQL v.0.6.0
* Go v0.35.1
* ESLint v2.2.6
* Auto Rename Tag v0.1.10

Do note that I have tried disabling each plugin with no resolution.

**Comment by johnsoncodehk** [comment]
It seems PrimeVue do not have define `onSelect` type, you need to send a feature request to PrimeVue for it.
