### ISSUE TITLE
Nested Ref Template Access

### ISSUE THREAD

**Issue by king-11** [johnsoncodehk/volar#1632]
In the below code, `org` is of type `Ref<OrgData>` destructured out of `orgData` of type `Ref<AsyncData>`. When using it inside the template, it shows errors when accessing keys of `org` directly even though that is the usual method for `Ref` when accessing inside of the template.

![image](https://user-images.githubusercontent.com/52061363/180734885-3f0af683-c401-476b-8ea8-346e9dee18ef.png)

The errors disappear when we use `org.value.name` instead of directly accessing keys, but then the component fails to load with accessing undefined error.

![image](https://user-images.githubusercontent.com/52061363/180735617-6a05c403-bbe7-474c-abcd-658c067f3b16.png)

This seems to occur when Ref(s) is/are nested inside another Ref.

**Comment by joo1es** [comment]
seem problem

**Comment by king-11** [comment]
@johnsoncodehk any suggestion

**Comment by midhuhu** [comment]
plus one

**Comment by johnsoncodehk** [comment]
If `orgData` define by `ref()`, it should auto unwrap nested ref type. If you define `orgData` type yourself, please make sure you have use `UnwrapRef<>` like `orgData: Ref<UnwrapRef<AsyncData[]>>`.

**Comment by king-11** [comment]
no `orgData` is returned by `useLazyAsynData`...I should give the full context code which is this:

```ts
type OrgData = {
  name: string,
  description: string,
  url: string,
  websiteUrl: string | undefined,
  twitterUsername: string | undefined,
  avatarUrl: string,
}

const { data:orgData, pending } = useLazyAsyncData('open-source', async () => {
  return (await Promise.all(
    organizations.value.map((val) => {
      return useFetch('https://api.github.com/graphql', {
        key: val,
        method: 'POST',
        headers: {
          authorization: ''
        },
        body: JSON.stringify({
          query: `
            query($name:String!) {
              organization(login:$name) {
                name,
                description
                id
                avatarUrl
                websiteUrl
                twitterUsername
                url
              }
            }
          `,
          variables: {
            name: val
          }
        }),
        transform: (res) => (res as any).data.organization as OrgData
      })
    })
  ))
})
```
