### ISSUE TITLE
Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jackqiu0123** [johnsoncodehk/volar#1633]
"vue-tsc": "^0.39.0"

npx vue-tsc --noEmit

<--- Last few GCs --->

[28822:0x7fbce5200000]   109872 ms: Mark-sweep 4041.9 (4131.9) -> 4031.4 (4137.5) MB, 1354.7 / 0.0 ms  (average mu = 0.336, current mu = 0.025) allocation failure scavenge might not succeed
[28822:0x7fbce5200000]   112348 ms: Mark-sweep 4051.8 (4141.5) -> 4037.2 (4145.5) MB, 2429.2 / 0.0 ms  (average mu = 0.171, current mu = 0.019) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1052b0a25 node::Abort() (.cold.1) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 2: 0x103fa60f9 node::Abort() [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 3: 0x103fa626f node::OnFatalError(char const*, char const*) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 4: 0x104127787 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 5: 0x104127723 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 6: 0x1042c8e05 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 7: 0x1042c778c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 8: 0x1042d4030 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
 9: 0x1042d40b1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
10: 0x1042a1147 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
11: 0x104658d4e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
12: 0x104a02819 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/bj89046ml/.nvm/versions/node/v16.14.0/bin/node]
13: 0x109a9dc1b
[1]    28821 abort      npx vue-tsc --noEmit

**Comment by DaniilIsupov** [comment]
i have same problem

**Comment by jackqiu0123** [comment]
@johnsoncodehk

**Comment by yanbowe** [comment]
same here

**Comment by Alexis2004** [comment]
Getting the same issue after upgrading `vue-tsc` from version `0.37.9` to any other version starting from `0.38.0`

**Comment by johnsoncodehk** [comment]
We have fix some memory issue in v1.0, if still have same problem please open an new issue.
