### ISSUE TITLE
Vitepress + Volar causing ts(2322)

### ISSUE THREAD

**Issue by dmnkrthrt** [johnsoncodehk/volar#1635]
After adding Vitepress to a project I find errors like this on class props of any HTML tags:

```
Type '{ class: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'. Did you mean 'className'?ts(2322)
```
I found that issue in #592 but adding "vite/client" to types in tsconfig.ts doesn't seem to work anymore or in this special case.

Maybe someone out here can help?

Thank you, Dominik

**Comment by dmnkrthrt** [comment]
Closing this, seems to be an issue related to vitepress + tsconfig.json - vitepress is adding @types/react.

**Comment by johnsoncodehk** [comment]
See #592.
