### ISSUE TITLE
The code hint is really slow in the.vue file

### ISSUE THREAD

**Issue by yanbowe** [johnsoncodehk/volar#1636]
Code prompts in.vue files are too slow, and the same project prompts in TS files are too slow for the development experience

https://user-images.githubusercontent.com/43030980/180920015-174596ab-7107-48da-a36f-dcb2e5bfc6d2.mp4

**Comment by ludwig801** [comment]
For me it is the same in essentially any js/ts file, not only in SFC files.
Even simple code analysis / error detection is slow and painfully so.

**Comment by JiangBingLong** [comment]
The code hint is really slow in the.vue a slightly larger file, please fix！

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1615#issuecomment-1236852594.
