### ISSUE TITLE
auto-import inconsistencies within template

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#1643]
Having some funky behaviour around auto-import suggestions only within vue templates, which leads me to believe it is a volar issue. The issue is that in the script section of a vue file (or other .ts files) importing a component that is exposed via an index file works correctly, while within the template block, the import suggestion is to import from the file directly.

**Correct behaviour (within script block)**
<img width="650" alt="Screen Shot 2022-07-25 at 8 51 27 AM" src="https://user-images.githubusercontent.com/1158956/181289094-1397e91b-e360-4a9f-89cc-cc6d09157567.png">

**Incorrect behaviour (within template tag)**
<img width="566" alt="Screen Shot 2022-07-25 at 8 51 51 AM" src="https://user-images.githubusercontent.com/1158956/181289147-ad590b3c-9dc4-446f-ab53-813d907981e5.png">

I'm unclear on what scenarios this occurs, but in my case specifically, the module `@si/ui-lib` is a shared component library within the monorepo, and is being used directly without being built first - meaning

my web app's package.json includes the dependency via pnpm workspace linking
```
"@si/ui-lib": "workspace:*",
```

and `@si/ui-lib`'s package.json exports the ts files directly
```
"main": "src/index.ts",
"types": "src/index.ts",
```
the index file just re-exports the components, for example
```
export { default as CoolButton } from './components/CoolButton/CoolButton.vue';
```

I have tried many different iterations of tsconfig files using aliases, project references, etc... What I have now seems to work the best and be very simple, with the only issue being this auto-import in vue templates.

Let me know if you need a minimal repro and I'll set one up.

Cheers!

**Comment by RSS1102** [comment]
I am currently participating in the development of a component, and there are requirements for web types (code completion and description). like: https://vuejs.github.io/vetur/guide/component-data.html#supported-frameworks
Enhance the completion and prompt of components by using code.
```ts
// package.json
  // vscode
  "vetur": {
    "tags": "highlight/tags.json",
    "attributes": "highlight/attributes.json"
  },
```
 see that the plug-in [vertur ](https://github.com/vuejs/vetur)is like this. I don't know what to do with volars?
 thanks.

**Comment by louia** [comment]
The component/function autocomplete feature not work actualy.

I use Typescript with TakeOver with vue 3.2 on the latest version of vscode.

If there is no import of the library into the project, volar does not recognize the library. You have to import your component manually for the first time and then the auto-import will work as expected.

BUT if you remove all the imports to the lib you will have a error like this in the suggestions window : 
![image](https://user-images.githubusercontent.com/33846211/222756738-d10aef8f-e005-4731-a224-d44f7e47acc8.png)

I don't understand that volar can't analyze the dependencies in the node_modules to propose the autocompletion of the imports


Is this a bug?

**Comment by tobychidi** [comment]
Has this issue returned? `isArticlePublished` is an auto imported util in Nuxt 3
![image](https://github.com/user-attachments/assets/deaa7b28-d8d3-4216-87b0-434785cf9f2c)

**Comment by ivanmem** [comment]
> Функция автозаполнения компонентов/функций фактически не работает.
> 
> Я использую Typescript с TakeOver с Vue 3.2 на последней версии vscode.
> 
> Если в проект не импортирована библиотека, volar не распознает библиотеку. Вам придется импортировать компонент вручную в первый раз, и тогда автоимпорт будет работать как положено.
> 
> НО если вы удалите все импорты из библиотеки, в окне предложений появится такая ошибка: ![image](https://user-images.githubusercontent.com/33846211/222756738-d10aef8f-e005-4731-a224-d44f7e47acc8.png)
> 
> Я не понимаю, почему volar не может анализировать зависимости в node_modules, чтобы предложить автодополнение импортов.
> 
> Это ошибка?

I have the same problem in [this ](https://github.com/ivanmem/vue-vkontakte-icons)project. Were you able to fix it?
