### ISSUE TITLE
[vue-tsc]: Watch mode doesn't pick up code-changes

### ISSUE THREAD

**Issue by rs3d** [johnsoncodehk/volar#1647]
Hi,

I'm trying to use `vue-tsc --watch` to see type errors of my vue-files,
although I'm not sure if this is already released, because I haven't found much information about using it in watch-mode.

### But what I experienced:
First run it checks and complains about type errors like this:
`const a:number = 'xxxx';`
![image](https://user-images.githubusercontent.com/1399149/181520007-9203ee3e-e549-483b-a4d5-41243228bd4d.png)

After removing the line with the error, the watch process runs again, 
but still shows the error:
![image](https://user-images.githubusercontent.com/1399149/181520096-b5e850ac-d353-416a-b3f9-fc5d80594108.png)

After restarting the vue-tsc manually, it shows no errors as expected.

Deps:
+-- vue-tsc@0.39.2
+-- vue: @2.7.8",
+-- @vue/composition-api@1.7.0
+-- @vue/runtime-dom@3.2.37
+-- typescript@4.7.4
+-- vite@3.0.3
+-- vite-plugin-checker@0.4.9
+-- vite-plugin-vue2@2.0.2
+-- vue-class-component@7.2.6
+-- vue-property-decorator@9.1.2
+-- vue-server-renderer@2.7.8
+-- vue-slider-component@3.2.18
+-- vue-template-compiler@2.7.8

on Win@11

**Comment by xieyuheng** [comment]
same problem for me.

**Comment by xieyuheng** [comment]
I found that, version "0.39.0" works fine.

**Comment by danparm** [comment]
This still appears to be a bug on v1.0.10

**Comment by douira** [comment]
I'm also experiencing vue-tsc to not watch for file changes. Maybe this is an already patched upstream issue?

**Comment by stichingsd-vitrion** [comment]
Seems like it is still a issue.

**Comment by miyacoz** [comment]
it doesn't work at my end either, but if i add `--project tsconfig.app.json` besides `--watch`, it works.. i don't know if it's the right workaround though.

any of `--project tsconfig.json`, `--project tsconfig.node.json`, or no `--project` doesn't work.

my working `package.json`, fyi:

```json
{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "start": "run-p tsc:build main:preview",
    "dev": "run-p tsc:watch main:watch",
    "main:watch": "vite",
    "tsc:watch": "vue-tsc --project tsconfig.app.json --watch",
    "tsc:build": "vue-tsc -b && vite build",
    "main:preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.31"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "npm-run-all2": "^6.2.2",
    "typescript": "^5.2.2",
    "vite": "^5.3.4",
    "vue-tsc": "^2.0.24"
  }
}
```

i installed `vue-tsc` via `vite --template vue-ts`.  
also `run-p` comes from `npm-run-all2`.
