### ISSUE TITLE
The code hint is really slow in the.vue a slightly larger file, please fix！

### ISSUE THREAD

**Issue by JiangBingLong** [johnsoncodehk/volar#1648]
Seriously affect the development efficiency！
please fix！
please fix！
please fix！
please fix！

**Comment by brys0** [comment]
Hi, just like you I have really slow Vue development. There is a alpha version of plugin to marginally increase the speeds. Please see https://github.com/johnsoncodehk/volar/issues/1615

**Comment by WhiteCoffee9834** [comment]
try `0.38.5`

**Comment by JiangBingLong** [comment]
> try `0.38.5`

thanks

**Comment by JiangBingLong** [comment]
> Hi, just like you I have really slow Vue development. There is a alpha version of plugin to marginally increase the speeds. Please see #1615

try ^0.38.5
