### ISSUE TITLE
typescript: error TS2693: 'Promise' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by myWsq** [johnsoncodehk/volar#165]
This error is raised when import a type or interface into a vue file, and is not returned within the ts file. 

![image](https://user-images.githubusercontent.com/35214490/116534779-88d50000-a915-11eb-967a-bef125f1cde2.png)

Here is my `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "node",
      "vite/client",
      "vite-plugin-pages/client",
    ],
    "baseUrl": ".",
    "paths": {
      "/@/*": [
        "src/*"
      ]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

**Comment by johnsoncodehk** [comment]
This is expected, you should use `import type { Ref } "vue"`, otherwise you will have a runtime error. See: https://github.com/johnsoncodehk/volar/issues/132.

**Comment by myWsq** [comment]
Thanks for your reply, it is works.
