### ISSUE TITLE
volar doesn't read `compilerOptions.types` of tsconfig.json

### ISSUE THREAD

**Issue by aimergenge** [johnsoncodehk/volar#1650]
volar version: v0.39.2
vscode version: 1.69.2

repo: https://github.com/aimergenge/blog

see this file: src/pages/index.vue:2

![image](https://user-images.githubusercontent.com/13799160/181672031-52ffdbd6-6eef-4fbd-980e-087f99ee3dd2.png)

`.png` module type is in `vite/client` and `tsconfig.json`'s `compilerOptions.types` includes it

**Comment by chivesssss** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/23553358/182007739-9aa327f5-707d-4d12-b98d-ff32db10da28.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/23553358/182007767-83961652-36df-4f94-9402-829fe4e26fe5.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/23553358/182007779-2edcc1e1-dc09-402e-b139-b84706ff7c55.png">


** 遇到同样地问题。**

**Comment by aimergenge** [comment]
> ### I have the same problem.
> <img alt="image" width="455" src="https://user-images.githubusercontent.com/23553358/182007739-9aa327f5-707d-4d12-b98d-ff32db10da28.png">
> 
> <img alt="image" width="619" src="https://user-images.githubusercontent.com/23553358/182007767-83961652-36df-4f94-9402-829fe4e26fe5.png">
> 
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/23553358/182007779-2edcc1e1-dc09-402e-b139-b84706ff7c55.png">

I found a temp solution:
create a *.d.ts file which use `/// <reference types=“vite/client” />` then make sure tsconfig.json includes this file.

**Comment by DimplesY** [comment]
> > ### I have the same problem.
> > <img alt="image" width="455" src="https://user-images.githubusercontent.com/23553358/182007739-9aa327f5-707d-4d12-b98d-ff32db10da28.png">
> > <img alt="image" width="619" src="https://user-images.githubusercontent.com/23553358/182007767-83961652-36df-4f94-9402-829fe4e26fe5.png">
> > <img alt="image" width="365" src="https://user-images.githubusercontent.com/23553358/182007779-2edcc1e1-dc09-402e-b139-b84706ff7c55.png">
> 
> I found a temp solution: create a *.d.ts file which use `/// <reference types=“vite/client” />` then make sure tsconfig.json includes this file.

This temporary solution is useless for me here

**Comment by m-mcardle** [comment]
I also have the same issue. While working on a Nuxt app all of the items in my `compilerOptions.types` are not being applied to my `VueInstance`'s.

![image](https://user-images.githubusercontent.com/5607044/182165864-7e9893fd-c86c-4641-9066-9f62d3f6c3f3.png)

![image](https://user-images.githubusercontent.com/5607044/182165960-a4be6c46-1bb9-4121-91fa-9fa91baaf470.png)

I was able to resolve this by changing my extension back to an older version (`v0.39.1`). I've noticed this only broke recently so something must have changed in the past week or so.

**Comment by ModyQyW** [comment]
@chivesssss 0.38.9 should work.

**Comment by fliebe92** [comment]
`v0.39.1` works fine for me, afterwards, it's broken.

**Comment by xuanxuan321** [comment]
I have the problem too. i don't use typeScript in my project, but vetur can also read types form tsconfig, i hope volar can also 
do it

**Comment by zhouxiang1991** [comment]
Still not working in v0.39.5

**Comment by fliebe92** [comment]
Works fine again in `v0.39.5`, thanks @johnsoncodehk 😎

**Comment by aimergenge** [comment]
> Still not working in v0.39.5

maybe you can reinstall the volar extension

**Comment by zhouxiang1991** [comment]
I mean, it doesn't work in workspace mode, but it works in directory mode.

**Comment by johnsoncodehk** [comment]
@zhouxiang1991 If still not working in v0.40.13 or later, please open an issue and provide repro case.
