### ISSUE TITLE
vue 2.7 template type check for inline function

### ISSUE THREAD

**Issue by troy351** [johnsoncodehk/volar#1654]
I'm using vue 2.7 with TypeScript

```vue
<template>
<div>
  <div v-for="(item, index) in arr" :key="index">
    <el-input type="text" :value="item" @input="(val) => doSomething(index, val)" />
  </div>
</div>
</template>
```
As code shown above, the problem is `@input="(val) => doSomething(index, val)"` part.

- ts error `Parameter 'val' implicitly has an 'any' type.` since `noImplicitAny` in `tsconfig` was enabled
- Vue 2.7 doesn't support ts syntax in template as the [CHANGELOG](https://github.com/vuejs/vue/blob/main/CHANGELOG.md) said
  > ❌ TypeScript syntax in template expressions (incompatible w/ Vue 2 parser)
- `ts-ignore` will causing `prettier` add leading semi colon which is not valid attribute value
   ```
  @input="
    //@ts-ignore
    ;(val) => doSomething(index, val)
   "
  ```
- Since `val` is an argument so [asAny](https://github.com/johnsoncodehk/volar/issues/176#issuecomment-838711592) magic won't work

Any workaround I can do?

**Comment by douglasg14b** [comment]
I see this as well, you can also see similar behavior with template literals in some situations

**Comment by troy351** [comment]
Solved by disabling both ts and prettier

```vue
@input="
 // @ts-ignore
 // prettier-ignore
 (val) => doSomething(index, val)
"
```

**Comment by lsdsjy** [comment]
I think it shouldn't trigger the `noImplicitAny` error because TS has contextual typing which would infer `val` as `Event` since `input` is of type `((payload: Event) => void) | undefined`. What do you see when you hover over `input`?

**Comment by troy351** [comment]
It just a demo. In the actual case, `<input>` could be any custom component or third party component which would unlikely infer `val`

**Comment by lsdsjy** [comment]
I see. Instead of `@ts-ignore` you can use something similar to the `asAny` trick:
```
@input="anyFn((val) => doSomething(index, val))"
```
, where `const anyFn = (fn: (val: any) => any) => fn`. And you can annotate it more accurately if you want.

**Comment by troy351** [comment]
Oh, I didn't think of it. Thanks!

**Comment by troy351** [comment]
`@input="anyFn((val) => doSomething(index, val))"` will compile to 
```js
on: {
    "command": function($event) {
        _vm.anyFn((val) => _vm.doSomething(index, val))
    }
}
// which should be 
on: {
    "command": (val) => _vm.doSomething(index, val)
}
```

**Comment by lsdsjy** [comment]
Try `const anyFn = function (fn: (val: any) => any) { fn.apply(this, arguments) }`?

**Comment by troy351** [comment]
It won't work, `val` should be directly declared as an argument of `command` handler function, or it won't be reached

**Comment by lsdsjy** [comment]
Isn't `$event` equal to `val`, both representing the `command` event's payload?

**Comment by troy351** [comment]
You are right, but again, real world case is mush more complicated, like multiple arguments

I ended up modify the `vue` source code to make it recognize the leading comment as a `function expression`

change [this line](
https://github.com/vuejs/vue/blob/1d8b892fcd9edcef1feeed74ad586beabb9f6df2/src/compiler/codegen/events.ts#L3) to `const fnExpRE = /^(\/\/.*\n)*([\w$_]+|\([^)]*?\))\s*=>|^(\/\/.*\n)*function(?:\s+[\w$]+)?\s*\(/`

**Comment by xiaoxiangmoe** [comment]
try use 
```vue
<template>
<div v-for="(item, index) in arr" :key="index">
  <input type="text" :value="item" @input="doSomething(index, $event)" />
</div>
</template>
```

**Comment by troy351** [comment]
`input` could be `el-input` or other custom components which doesn't support `$event`

**Comment by xiaoxiangmoe** [comment]
Why they don't support `$event`?

**Comment by troy351** [comment]
`$emit` support multiple arguments, and `$event` only got one. Works for most cases though

**Comment by xiaoxiangmoe** [comment]
Maybe you should create a bug in prettier —— add leading semi colon will break vue event listener

**Comment by troy351** [comment]
Not only the leading semi problem.
As the previous [comment](https://github.com/johnsoncodehk/volar/issues/1654#issuecomment-1207916581) said, even I add both ts-ignore  and prettier-ignore, vue template compiler won't treat leading comment (i.e. `//`) function expression as a function expression due to the regular expression test

**Comment by troy351** [comment]
That's what I'm thinking about.

**Comment by johnsoncodehk** [comment]
LGTM <img width="576" alt="螢幕截圖 2022-09-22 16 12 03" src="https://user-images.githubusercontent.com/16279759/191693983-c5a7d87c-4b03-487f-8e1c-a4fc31c2789e.png">

Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter/tree/vue2?

**Comment by troy351** [comment]
My bad, I've updated code snippet, using `<el-input>`(which is from [element-ui](https://github.com/ElemeFE/element)) instead of `<input>`

**Comment by xiaoxiangmoe** [comment]
Can you provide me a repo？

**Comment by troy351** [comment]
check [this](https://github.com/troy351/volar-vue2-demo/blob/main/src/App.vue)

**Comment by xiaoxiangmoe** [comment]
Using this instead:

```ts
// file: components.d.ts
declare module "element-ui/types/input" {
  interface ElInput {
    $props: {};
    $emit: (event: "input", val: string, maybeAnother: number) => void;
  }
}
declare module "vue" {
  interface GlobalComponents {
    ElInput: typeof import("element-ui/types/input").ElInput;
  }
}
export {};
```

![image](https://user-images.githubusercontent.com/8111351/192204502-56b8e7c6-d8cf-46ba-a469-6b828a3884ad.png)

**Comment by xiaoxiangmoe** [comment]
You can create a PR in element-ui to add `$props` and `$emit` in `class ElInput`

**Comment by xiaoxiangmoe** [comment]
We can create a PR for element-ui types latter

**Comment by troy351** [comment]
Thanks

**Comment by Papooch** [comment]
For late-comers like me, the `asAny` trick works perfectly well:

```vue
<el-input type="text" :value="item" @input="(val) => doSomething(index, asAny(val))" />
```
