### ISSUE TITLE
Surrounding pairs missing backticks

### ISSUE THREAD

**Issue by movy** [johnsoncodehk/volar#1659]
I believe backticks should be surrounding, at least this how it works (and expected to work) in normal JS files. Volar disables this however, I believe must be added here:
https://github.com/johnsoncodehk/volar/blob/4963cd1350431e4bc3734486e56c6f6e877ce8f9/extensions/vscode-vue-language-features/languages/vue-language-configuration.json#L74

**Comment by johnsoncodehk** [comment]
For `<script>` block, vscode use JS surroundingPairs config from https://github.com/microsoft/vscode/blob/b5a1bb34e9c6b77c2a8ccf54bcdbb4bac4d420cb/extensions/javascript/javascript-language-configuration.json#L72, so it do not need to define in vue language config.

**Comment by movy** [comment]
Thanks for following up, 
I apologize for not being more verbose in my initial issue description:
Whenever I select a string inside JS in a `.vue`  file and try to surround it with backticks by typing a backtick, the whole string gets replaced with a single backtick. This is not how it works with all other surrounding symbols (`{} () '' "" ` etc), hence my guess about the wrong `surroundingPairs` config. 

This is still happening and would be nice to find out why.

https://user-images.githubusercontent.com/4336560/187037029-788d9b61-fa19-49be-b0ec-ab7d6cb0aba9.mov
