### ISSUE TITLE
[vue-tsc] ignore index.html

### ISSUE THREAD

**Issue by arpowers** [johnsoncodehk/volar#1661]
hey there, 
we are using `vue-tsc` to run some type checking on `.vue` files... however, its also checking `*.html` files including Google tags and so on ... 

Anyway to disable that? 

We are also getting issues w/ imported `.md` files. 

Great work though, much appreciated.

**Comment by IIFelix** [comment]
You can use the exclude option in your tsconfig.json i think.
https://www.typescriptlang.org/tsconfig#exclude
