### ISSUE TITLE
TS auto-import happens in incorrect script tag

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#1664]
If your SFC has more than one script block, typically a `<script setup>` + a regular `<script>`, then triggering auto-import inside the regular block will auto-import into the `script setup`, which is incorrect.

```vue
<script lang="ts">
  // This is where I expect the auto-import to be added
  
  function x() {
    // Trigger auto-import of `h` from "vue" here 👇
    return h("div");
  }
</script>

<script setup lang="ts">
  // `h` import will incorrectly be added here 👇
  import { computed } from "vue";
</script>
```

**Comment by johnsoncodehk** [comment]
This is expected behavior, `<script>` + `<script setup>` is combine to single virtual file in language server, typescript language service cannot distinguish `<script>` and `<script setup>` auto import insert range.
