### ISSUE TITLE
bug: the file path suffix is `js` when `ts` auto-import in `<script setup lang="ts">`

### ISSUE THREAD

**Issue by Cenavy1019** [johnsoncodehk/volar#1667]
https://user-images.githubusercontent.com/20083373/183049251-5c9126ab-9b8d-4c86-9814-709686ea1490.mov

Volar `0.39.4`
TypeScript Vue Plugin `0.39.4`

I'm downgrade the version to `0.39.2` and  it's ok

**Comment by calebwaldner** [comment]
I had the same problem with version `0.39.4`, all my `.ts` files were auto-importing as `.js`. Downgrading to `0.39.2` fixed this.

**Comment by yao8384** [comment]
same as me😞
