### ISSUE TITLE
BUG: volar start error

### ISSUE THREAD

**Issue by LeezQ** [johnsoncodehk/volar#1668]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/972813/182575324-0d2f95ab-2c4b-4084-a134-29cd02c20a1a.png">

if I use this tool to start app, it will cause error

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/972813/182575190-270b7568-41ff-45c4-9c41-fd5d3c6f07c8.png">

when I use start with `node ./node_modules/vite/bin/vite.js --port 3333 --open` , no error

dependencies:
@element-plus/icons-vue 2.0.6  dayjs 1.11.4                   pinia 2.0.17                   
@vicons/carbon 0.12.0          element-plus 2.2.12            postcss 8.4.14                 
@vicons/material 0.12.0        get-user-locale 1.5.0          vite-plugin-vue-layouts 0.7.0  
@vicons/utils 0.1.4            laf-client-sdk 0.8.2           vue 3.2.37                     
@vueuse/core 9.0.2             lodash 4.17.21                 vue-i18n 9.2.0                 
aws-sdk 2.1187.0               md5 2.3.0                      vue-request 1.2.4              
axios 0.27.2                   monaco-editor 0.33.0           vue-router 4.1.3               
bson 4.6.5                     nprogress 0.2.0                

devDependencies:
@antfu/eslint-config 0.25.2          balanced-match 2.0.0                 unplugin-auto-import 0.10.3          
@iconify-json/carbon 1.1.7           eslint 8.21.0                        unplugin-vue-components 0.21.2       
@intlify/vite-plugin-vue-i18n 5.0.1  jsdom 20.0.0                         vite 3.0.4                           
@types/lodash 4.14.182               magic-string 0.26.2                  vite-plugin-inspect 0.6.0            
@types/md5 2.3.2                     pnpm 7.8.0                           vite-plugin-monaco-editor 1.1.0      
@types/node 18.6.3                   postcss-nested 5.0.6                 vite-plugin-pages 0.25.0             
@unocss/reset 0.45.1                 sass 1.54.1                          vitest 0.20.3                        
@vitejs/plugin-vue 3.0.1             typescript 4.7.4                     vue-tsc 0.39.4                       
@vue/test-utils 2.0.2                unocss 0.45.1  

Volar version:  
- Vue Language Features (Volar)  v0.39.4
- TypeScript Vue Plugin (Volar)  v0.39.4

**Comment by dolsup** [comment]
I had the same problem. 
Workaround for busy people: Install Vue Language Features (Volar) **v0.39.2**. It works well.

<img width="621" alt="스크린샷 2022-08-03 오후 7 05 58" src="https://user-images.githubusercontent.com/8360934/182582572-e6a75d83-99e8-4924-b531-d5e4685b1932.png">

**Comment by AlexKratky** [comment]
I guess I have similar problem, Volar does not provide any type hints, for example, if I use code:

```js
 setup() {
    const store = useStore()
    return {
      store
    }
  },
```
and hover over `store` variable within the same function, it shows all methods from store, but if I write `this.store` in other function, the VS code thinks its type is `any` and not a store.


changing version back for 0.37.2 works for me
