### ISSUE TITLE
[vue-tsc] .d.ts files are not emitted after upgrade from 0.33.9

### ISSUE THREAD

**Issue by Alexis2004** [johnsoncodehk/volar#1669]
I am developing a library of Vue components. To export type declarations during the build, we use the command `vue-tsc --declaration --emitDeclarationOnly`.

Everything worked well on `vue-tsc@0.33.9`. After upgrading to `0.34.1`, no types are exported anymore, and there are no errors or warnings in the terminal. I observe the same behavior on the latest version of the library at the moment (`0.39.4`). I was unable to check the build for version `0.34.0`, due to the previously [fixed bug](https://github.com/johnsoncodehk/volar/commit/21df5bac58cadc77811644ff0118ed0d5fc33e61).

How to reproduce the issue:
1) Checkout the demo repository `git clone git@github.com:Alexis2004/vue-tsc-dts-issue.git`.
2) Execute command `yarn install && yarn run dts` in the project root.
3) Make sure that the `dist/` folder with `.d.ts` files is not created.
4) Downgrade the `vue-tsc` library in the `package.json` file to version `0.33.9`.
5) Rerun command `yarn install && yarn run dts`.
6) Make sure that the `dist/` folder with `.d.ts` files appears in the project root.

**Comment by johnsoncodehk** [comment]
You can remove `"noEmitOnError": true` to avoid the problem, emit is block by volar internal errors currently.

**Comment by Alexis2004** [comment]
Thank you very much! The proposed workaround with removing `noEmitOnError` helped me – now `.d.ts` files are generated successfully (I've tried to build using the latest `vue-tsc` version).
