### ISSUE TITLE
InstanceType is always typed as 'any'

### ISSUE THREAD

**Issue by IIFelix** [johnsoncodehk/volar#1671]
When i try to type a template ref with 'InstanceType<typeof ....> the type result is always 'any'.
When i downgrade Volar to 0.38.5 it works again.

![volar_instancetype](https://user-images.githubusercontent.com/56734789/182858534-2b535944-eadd-44b8-b430-31197f5a0dd1.png)

**Comment by johnsoncodehk** [comment]
I tried in https://github.com/johnsoncodehk/volar-starter but cannot reproduce, could you provide minimal reproduction?

<img width="776" alt="螢幕截圖 2022-08-26 19 31 49" src="https://user-images.githubusercontent.com/16279759/186894458-00bfcf48-94b8-4c74-bf1d-da9e6eefd7aa.png">

**Comment by IIFelix** [comment]
Works again - thanks for looking into it :)
