### ISSUE TITLE
Typescript possible undefined loses type when using withDefaults and setting explicitly to undefined

### ISSUE THREAD

**Issue by VividLemon** [johnsoncodehk/volar#1672]
If you do
```ts
interface Props { id?: number }

const props = withDefaults(defineProps<Props>(), { id: undefined })
```
if you observer `props.id`, even though the default is undefined, it will **lose it's type** and it will always claim to be `number`. 

![image](https://user-images.githubusercontent.com/31498096/182895581-0088a76c-35e4-4d2b-a806-9c6420818a78.png)

![image](https://user-images.githubusercontent.com/31498096/182895636-d48e4515-73cc-449b-ac47-d439506e4a33.png)

**Comment by johnsoncodehk** [comment]
This is `withDefaults` types behavior, please forward to https://github.com/vuejs/core.
