### ISSUE TITLE
[feat-req] Allow compiling vue SFC like ts file

### ISSUE THREAD

**Issue by jd-solanki** [johnsoncodehk/volar#1676]
Hi,

I have TS + Vue 3 project to deliver and along with this I also need to provide the same version of the project but using JS instead of TS.

In React, we can compile (_not build_) the source to JS and it removes all the TypeScript.

When I tried `vue-tsc` I found that it just type check & emit declaration files only. It can't compile the Vue SFC to "JS Vue SFC" as `tsc` does with `.ts` and `.tsx`

[Discord Message](https://discord.com/channels/793943652350427136/899997357649821716/1005010088349679656)

Thanks for this awesome extension ❤️

**Comment by johnsoncodehk** [comment]
Unfortunately vue-tsc can't do it, see #640.
