### ISSUE TITLE
Syntax highlighting of < and > inside <script>

### ISSUE THREAD

**Issue by 2-5** [johnsoncodehk/volar#1677]
#1675 not fully solved by 0.39.5, created new issue since I can't reopen that:

![2022-08-06_144452](https://user-images.githubusercontent.com/3753822/183247706-9bcb21a9-7b63-4811-9a13-4cb49a362bd6.png)

**Comment by kifuan** [comment]
I'm in the same situation as you.
![image](https://user-images.githubusercontent.com/61240774/183248260-f3f8ca70-ce75-477f-a063-92338e62c5bc.png)

**Comment by kifuan** [comment]
It seems that the problem is caused by `Bracket Pair Colorization`, which can be turned off in VSCode's Settings.

**Comment by johnsoncodehk** [comment]
Please track https://github.com/microsoft/vscode/issues/157241.

**Comment by hediet** [comment]
@johnsoncodehk

I know it is suboptimal, but this bug can be fixed short-term by adding this to the [vue grammar contribution](https://github.com/johnsoncodehk/volar/blob/master/extensions/vscode-vue-language-features/package.json#L173):
```json
"unbalancedBracketScopes": [
    "keyword.operator.relational",
    "storage.type.function.arrow",
    "keyword.operator.bitwise.shift",
    "meta.brace.angle",
    "punctuation.definition.tag"
]
```

Unfortunately, there is a bug in our textmate grammar implementation that only considers `unbalancedBracketScopes` of the root grammar and not of injected grammars.

**Comment by Nercus** [comment]
Adding the following to `settings.json` does help temporarily (at least that fixed it for me 😃):
```json
"editor.language.colorizedBracketPairs": [
    [
        "{",
        "}"
    ],
    [
        "[",
        "]"
    ],
    [
        "(",
        ")"
    ]
]
```

**Comment by hedwiggggg** [comment]
Got wrong bracket matching in addition to wrong colorization when using JSX/TSX inside of a `.vue` file. Workaround was downgrading vs-code to version 1.69.

https://code.visualstudio.com/updates/v1_69
