### ISSUE TITLE
Tips and advice are not available in VUE3

### ISSUE THREAD

**Issue by jahnli** [johnsoncodehk/volar#1680]
Volar does not have reacttive Ref Watch useRoute related tips and import

https://user-images.githubusercontent.com/20943608/183295784-6831f7e6-9805-4a94-853a-ae3d119881a8.mp4

**Comment by jahnli** [comment]
Can we do it like Vetur 

![image](https://user-images.githubusercontent.com/20943608/183296162-53b760e3-053d-4f6f-8aa8-aa12d287a93e.png)

**Comment by AlexKratky** [comment]
@jahnli try to installing version v0.37.2 , I guess its bug and at this version it works well

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/183296594-7146adeb-e2bf-4ab6-98ec-32d3a29470ed.png)
I adjusted the version to 0.37.2, but I still couldn't get the router and Watch suggestions

**Comment by sadeghbarati** [comment]
probably the best course is to stick with Volar **[v0.39.5](https://github.com/johnsoncodehk/volar/releases/tag/v0.39.5)** and wait for new release after **[v0.40.1](https://github.com/johnsoncodehk/volar/releases/tag/v0.40.1)**

**Comment by jahnli** [comment]
Not fixed in v0.40.1 @sadeghbarati

**Comment by jahnli** [comment]
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
Do you have disable / enable `typescript.suggest.autoImports` VSCode setting?

**Comment by AlexKratky** [comment]
@johnsoncodehk I have similiar issues and have both for typescript and normal javascript enabled autoimports, should that be turned off?

**Comment by johnsoncodehk** [comment]
If v1.0 still not working, please try re-install VSCode. (Yes this is weird, but someone actually got fix after do this)

**Comment by Mingo-233** [comment]
I encountered the same problem. My volar version is v1.0.14, and the vue tsc version is 1.0.14. The project uses pnpm. But miraculously, it is normal for me to open another project with vscode. When using the vue api, there are type prompts and automatic import
