### ISSUE TITLE
Sort import on save

### ISSUE THREAD

**Issue by joseluisgs** [johnsoncodehk/volar#1689]
Hi
Could be possible to add in volar configuration auto sort import or sort import on save?
Thank you!!!

**Comment by troy351** [comment]
It should be done via [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import)

**Comment by joseluisgs** [comment]
Thanks. But how? Using the same order that volar use?

**Comment by troy351** [comment]
I don't see that volar would sort any import orders, you can define your own order via that eslint plugin

**Comment by joseluisgs** [comment]
> 

Hi, pelease could you give me an example?
Thanks so much

**Comment by Shinigami92** [comment]
Using https://github.com/simonhaenisch/prettier-plugin-organize-imports for this job already works fine
No need to have this additionally in volar

**Comment by johnsoncodehk** [comment]
You can config `source.organizeImports` in .vscode/settings.json.

```json
{
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
}
```
