### ISSUE TITLE
Error: v-if/else branches must use unique keys.

### ISSUE THREAD

**Issue by timsayshey** [johnsoncodehk/volar#1693]
I switched from Vetur to Volar and started seeing these lint errors:
`v-if/else branches must use unique keys.`

Seems like a strange error because Vue is only using one of the elements, why would they both need their own unique keys? Or is the error a false positive?

![image](https://user-images.githubusercontent.com/1148940/183969750-845a06cf-a4af-42d1-b713-958f0abfdc89.png)

**Comment by johnsoncodehk** [comment]
For vue 2 project, you need to config `"target": 2` / `"target": 2.7` in tsconfig.

```
{
  "vueCompilerOptions": {
    "target": 2,
  }
}
```
