### ISSUE TITLE
v0.40.0 template type problems

### ISSUE THREAD

**Issue by zigomir** [johnsoncodehk/volar#1694]
Hi,

Since upgrading to `v0.40.0` some of my Vue component templates stopped detecting types, e.g. on hover where I see a type in `v0.39.5` I don't see it anymore in `v0.40.0`.

I also see some of variables, for example computed property defined in `script setup` marked as not used, even though I'm using them in the `template`.

Sorry for being sparse with the details, I just am not sure what else than version number and behavior I could provide 😊

[edit] I also found out that when I run `Volar: Verify All Scripts` in `v0.40.0` I got about 5 errors, but I get none in `v0.39.5` and I'm almost certain that errors are false positives.

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem in project in my hand, if you can add a test case to https://github.com/johnsoncodehk/volar/tree/master/packages/vue-test-workspace/vue-tsc it will be helpful.

**Comment by danielwaltz** [comment]
Unfortunately I am still experiencing template type issues in a project using `vue@2.7`. I'm not sure if it's specific to 2.7 but both `v0.40.1` and `v0.40.0` lead to every component in my templates being of type `any`. Downgrading to `v0.39.5` allows template types to work again.

Having to explicitly downgrade the version in vscode when these updates land with regressions is a little difficult to manage, especially when having to communicate the problem with multiple team members who all need to not only manually downgrade themselves to keep working effectively, but need to remember to upgrade again when it's fixed.

Shameless plug, but it would be really nice if `volar` used the version of `vue-tsc` found in your local repo/node_modules folder as described [here](https://github.com/johnsoncodehk/volar/issues/1388). That way projects can opt in to newer versions when they are stable.

**Comment by danielwaltz** [comment]
Another clue - it appears this is only the case in components that are not yet using `<script setup>`. Template type checking is working with `<script setup>`, but is not working without it.

**Comment by johnsoncodehk** [comment]
@danielwaltz just guessing it might be related to https://github.com/johnsoncodehk/volar/commit/412e9858b53e981ea1ee170d855bb2fe0de43573.

For vue 2.7 project, please make sure you have config target 2.7 not target 2 in tsconfig.

```json
{
  "vueCompilerOptions": {
    "target": 2.7
  }
}
```

If still not working, you can also try setup `experimentalImplicitWrapComponentOptionsWithVue2Extend` to discharge https://github.com/johnsoncodehk/volar/commit/412e9858b53e981ea1ee170d855bb2fe0de43573.


```json
{
  "vueCompilerOptions": {
    "target": 2.7,
    "experimentalImplicitWrapComponentOptionsWithVue2Extend": true
  }
}
```

> Shameless plug, but it would be really nice if `volar` used the version of `vue-tsc` found in your local repo/node_modules folder as described [here](https://github.com/johnsoncodehk/volar/issues/1388). That way projects can opt in to newer versions when they are stable.

Unfortunately it probably won't happen soon, `@volar/vue-language-core` API must be stable for it, but current is still moving fast.

This request may be more worth looking forward to: https://github.com/microsoft/vscode/issues/138048

**Comment by danielwaltz** [comment]
The target in my `tsconfig` is indeed set to `2.7` already, but that is a really good thought!

I also just tested out enabling the `experimentalImplicitWrapComponentOptionsWithVue2Extend` option and unfortunately it still does not fix template type checking in components not using `<script setup>`.

Really appreciate the additional information on a version locking feature too, it's true that Microsoft supporting extension version locking in their workspace recommendations would also be an excellent solution. Understandable with the speed of iteration that now maybe wouldn't be the best time for that feature. Still hoping for it one day!
