### ISSUE TITLE
Format Document broken in 0.40.0

### ISSUE THREAD

**Issue by littledot** [johnsoncodehk/volar#1697]
In 0.40.0, `Ctrl+Shift+P > Format Document` shows the following error message instead of formatting:

```
[Error - 2:22:08 PM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Overlapping edit
  Code: -32603 
```

Reverting to 0.39.5 works.

**Comment by LynxTR** [comment]
I am getting same error as well. It just started today.

**Comment by Caococos** [comment]
这个问题解决了吗？v0.40.1也出现了这个问题。

**Comment by pablomuro** [comment]
My VScode had prettier enabled in the workspace, and I was had this same problem, I disabled prettier for my Nuxt project and set the vue editor to Volar, and I don't have this error anymore.
