### ISSUE TITLE
I'm not sure if it's a replacement for Vetur, or..

### ISSUE THREAD

**Issue by eladcandroid** [johnsoncodehk/volar#17]
Or kind of some "big brain" for that.. 
Please add some explanation and code demonstrations on README..

**Comment by johnsoncodehk** [comment]
Thank you for your attention to this project! I didn't think too much about the positioning of this project, it was just created to solve vetur was too slow on my vue 3 project(and convenient added the features I needed). If vetur works well for you just keep using vetur :)

**Comment by soulsam480** [comment]
This is a worthy replacement to vetur on my part. The only thing I miss in volar is the html tag suggestions are not coming unless I initiate the tag with a < as prefix
e.g.
`<span` after typing this the suggestion comes.
`span.classname` this doesn't work.

I think the integration of emet should be rechecked!.

Another problem is in  template the`$event` param is throwing error.
```html
<template>
<button @click="someMethod($event)" >YOLO</button>
</template>
```
The `$event` param throws not defined error. But in vetur this doesn't throw an error. Please have a look into that

again thank you @johnsoncodehk  for this amazing project.

**Comment by johnsoncodehk** [comment]
@soulsam480 Thank you for your feedback and bug report! It has been updated to 0.14.9 :)

**Comment by johnsoncodehk** [comment]
I have added some introduction to readme, but I didn't say how to choose because will like a competing product, this is not my purpose and I just create this tool to resolve my own problems.

Hope is answered you question. :)
