### ISSUE TITLE
Volar development issues in vscode

### ISSUE THREAD

**Issue by DTHLove** [johnsoncodehk/volar#1701]
Hello ，Volar couldn't find the global registry component in the red wavy line of UI library introduced by VUE3 Vscode development

**Comment by inscorpio** [comment]
I also encountered this problem

**Comment by DTHLove** [comment]
> 我也遇到了这个问题
You can add it in tsconfig.json ，"vueCompilerOptions": {
        "experimentalDisableTemplateSupport": true
    },

**Comment by wahhh555** [comment]
I don not what happend，my project components are all red wavy line。

**Comment by wenzheng-yi** [comment]
I got the same problem

**Comment by d1y** [comment]
I got the same problem +1

**Comment by saberc8** [comment]
我遇到了同样的问题+2

**Comment by johnsoncodehk** [comment]
Please try v1.0.0-alpha.x.
