### ISSUE TITLE
Split editor, when coding in the left side,the folding code on the right will auto expand

### ISSUE THREAD

**Issue by Cheerwhy** [johnsoncodehk/volar#1702]
version:0.40.1

**Comment by Cheerwhy** [comment]
向右拆分.vue文件，在左边script脚本里面写代码，右边script会自动展开

**Comment by Cheerwhy** [comment]
vscode version:1.70.1

**Comment by ddenev** [comment]
Same issue here - splitting opens script on the left and template on the right. Editing the template code on the right would open the template tag on the left.

This is very annoying - I need to go and explicitly close the template tag on the left every time.

**Comment by Cheerwhy** [comment]
> Same issue here - splitting opens script on the left and template on the right. Editing the template code on the right would open the template tag on the left.
> 
> This is very annoying - I need to go and explicitly close the template tag on the left every time.

VScode version 1.70.2
I think its a VScode problem
but I can't find any solution

**Comment by OhaiHFO** [comment]
I'm experiencing the same issue, very frustrating to have the code presentation shift around unexpectedly.

**Comment by johnsoncodehk** [comment]
This is editor issue, please report to https://github.com/microsoft/vscode/issues.
