### ISSUE TITLE
About wrap in html part

### ISSUE THREAD

**Issue by a1751504** [johnsoncodehk/volar#1703]
when active vetur and diasbled  volar
![image](https://user-images.githubusercontent.com/31113826/184057948-59de3251-a57f-42f5-85b9-9f9d0fd9b1ab.png)
press Enter ↓
![image](https://user-images.githubusercontent.com/31113826/184057966-c84e6c3b-7918-4b8c-ac00-6bd00122435d.png)

but active volar and diasbled vetur
![image](https://user-images.githubusercontent.com/31113826/184057806-73d33016-c273-4d16-9814-fc06b4733ac7.png)
press Enter ↓
![image](https://user-images.githubusercontent.com/31113826/184057852-1deb0bdc-326c-4483-821c-d6910e6b22f0.png)

In my opnion,wrap like Vetur is customary

Ahh.. It's also a bit of fun to disable the ‘vue3 support -All in one‘ when use volar，the cursor position is correct after line wrapping like use veture
So the problem is with 'vue3 support -All in one' or 'volar'？I have no idea

**Comment by johnsoncodehk** [comment]
I think "vue3 support -All in one" has it own vue language config, and which override volar vue langauge config randomly.
