### ISSUE TITLE
SyntaxError:  Not a valid JSX element

### ISSUE THREAD

**Issue by tangerren** [johnsoncodehk/volar#1705]
Volar version v0.40.1

while set ```"jsx": "preserve"``` in the tsconfig.json file

![image](https://user-images.githubusercontent.com/16789187/184083668-98efb705-722f-4035-96c9-8b3d5538008f.png)

the ```<T>``` will prompt error

![image](https://user-images.githubusercontent.com/16789187/184083536-6ccb7b02-86c1-4796-87ef-666332e55f7b.png)

**Comment by tangerren** [comment]
Volar  version  v0.40.1

**Comment by ms-mayya** [comment]
Same here!

**Comment by XYGR** [comment]
Same here!

**Comment by joeyberkovitz** [comment]
^ version 0.40.0 is also impacted. Generally it just seems to be not detecting typings for third party globally registered components

**Comment by jhxxs** [comment]
Same here!

**Comment by kirkwaiblinger** [comment]
Having the same problem. It appears that type assertions using bracket notation are being interpreted as JSX now, which did not used to be a problem.
![image](https://user-images.githubusercontent.com/53019676/185022728-23cc8b01-73c9-4214-88c4-a9be714c2a0b.png)
![image](https://user-images.githubusercontent.com/53019676/185022786-c2d74b6a-f2d8-4a00-ab76-e8ca30c45ffe.png)
I am on Vue 2.7 and Volar 0.40.1

**Comment by johnsoncodehk** [comment]
Fixed by #1865
