### ISSUE TITLE
Release 0.40.1 breaks typescript compatibility on script setup

### ISSUE THREAD

**Issue by Tails128** [johnsoncodehk/volar#1708]
This morning's release breaks the typescript/tslint's compatibility on `<script lang='ts' setup>`.

More specifically the following error is triggered:
```
'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

As you may see it only happens in `<script>` and does not extend outside it.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/12231147/184092885-8c8181d1-c629-47c6-bb51-7893381b4e55.png">

**Comment by Shinigami92** [comment]
https://palantir.github.io/tslint/

<img width="456" alt="image" src="https://user-images.githubusercontent.com/7195563/184095005-a7cd6148-1937-4797-8233-ed111be937d2.png">

PLEASE move away from TSLint!!!

**Comment by francoism90** [comment]
@Shinigami92 I'm getting the same error on a default Vue getting started project. 
```
"devDependencies": {
    "@rushstack/eslint-patch": "^1.1.4",
    "@types/jsdom": "^20.0.0",
    "@types/node": "^16.11.47",
    "@vitejs/plugin-vue": "^3.0.1",
    "@vitejs/plugin-vue-jsx": "^2.0.0",
    "@vue/eslint-config-prettier": "^7.0.0",
    "@vue/eslint-config-typescript": "^11.0.0",
    "@vue/test-utils": "^2.0.2",
    "@vue/tsconfig": "^0.1.3",
    "cypress": "^10.4.0",
    "eslint": "^8.21.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-vue": "^9.3.0",
    "jsdom": "^20.0.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.7.1",
    "start-server-and-test": "^1.14.0",
    "typescript": "~4.7.4",
    "vite": "^3.0.4",
    "vitest": "^0.21.0",
    "vue-tsc": "^0.39.5" // works, but higher breaks lint
  }
```
I don't see any TSLint?

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter, please provide minimal reproduction.

**Comment by francoism90** [comment]
@johnsoncodehk I don't have a public repo, however it can be easy triggered using the latest versions and trying to import something like `vue` (`computed`, `watch`, etc.).

I'm using https://cli.vuejs.org/guide/creating-a-project.html, select TS support and upgrade to the latest versions using `ncu`. It will break VSCode and `npm install`.

**Comment by so1ve** [comment]
I also had this problem, but it only appeared in some components.

**Comment by so1ve** [comment]
I've found this problem in any `.vue` file that uses components.

**Comment by so1ve** [comment]
Downgrading to 0.40.0 solved it.

**Comment by jiangmaniu** [comment]
+1 

Similarly, I have this problem in some components, and I have not found the regularity of the problem. I tried to rename the same `.vue` component code file (for example: `name.vue` => `name1.vue` ), and found that the error of the named file disappeared, which is very strange.

old file name：
![image](https://user-images.githubusercontent.com/50100681/184368284-e0b97fe8-718f-4c44-b2b5-fafcafa306b7.png)

new file name：
![image](https://user-images.githubusercontent.com/50100681/184368331-8ad11baf-8f58-4051-96e6-2ee99bc0ad62.png)

**Comment by Tails128** [comment]
@Shinigami92 my situation is the same as @francoism90, actually!
I've said tslint because the error is reported as `ts(7022)`, but all I have on my project is prettier.

I can also confirm @jiangmaniu 's experiment: if you rename the file, the error disappears... if you rename it back it still produces no error... very odd.

As for the components it happens into it's extremely random, for instance one component where it happens is structured as follow:

```
// imports

const emit = defineEmits([EmitsEnum.Close, EmitsEnum.Save])
const filtersStore = useFiltersStore() //pinia
const currentStructure = computed(() => filtersStore.currentFilter?.structureId)

const creationRange = ref({ start: new Date(), end: new Date() })
const stayRange = ref({ start: new Date(), end: new Date() })

const structureLabel = LocaKeys.STRUCTURE
// some more enum assignments as they are used in the template but cannot be called directly via {{}}
```

**Comment by Shinigami92** [comment]
@Tails128 You should update the Issue title accordingly to make it more searchable so potentially others can help

**Comment by so1ve** [comment]
When I downgraded Volar and then upgradeWhen I downgraded Volar and then upgraded, the error went away again...d, the error went away again...

**Comment by Tails128** [comment]
@Shinigami92 Would

Release 0.40.1 breaks typescript compatibility on script setup.

be a better fit?

**Comment by Shinigami92** [comment]
> @Shinigami92 Would
> 
> 
> 
> Release 0.40.1 breaks typescript compatibility on script setup.
> 
> 
> 
> be a better fit?

I assume so 👍
A reproduction would still be welcome even if it sounds simple for you
But Johnson needs it to somehow investigate deeper into it

**Comment by Shinigami92** [comment]
Additionally could you try two things?
1. try to write `<script setup lang="ts">` (so swap lang with setup)
2. clean you lock file and node_modules folder and make a full reinstall of your node modules

**Comment by francoism90** [comment]
@Shinigami92 I have tried both steps, and it still breaks.

Like said before, simple create a Vue3 project with TS and you'll the same error.

**Comment by Shinigami92** [comment]
Please read this:

- https://stackoverflow.com/help/minimal-reproducible-example
- https://antfu.me/posts/why-reproductions-are-required

**Comment by arpowers** [comment]
@johnsoncodehk have this issue as well, will create an example but can already tell you it is because the plugin isn't respecting `import type` and allowing a circular type reference via import of vue component

**Comment by mPyth** [comment]
I'm getting this problem only in files that use `defineAsyncComponent(...)`, large number of errors is generated in both files - file that imports another one and in imported file. `defineAsyncComponent(...)` was needed to break circular dependency.

**Comment by Tails128** [comment]
@Shinigami92 i confirm once more @francoism90 's report: both things still create issues

**Comment by ouuan** [comment]
I have a minimal reproduce: https://github.com/ouuan/volar-1708-reproduce

I find this happens when using recursive components with [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components).

**Comment by MrBrax** [comment]
I don't use setup but I still get this at https://github.com/MrBrax/twitch-vod-chat/blob/master/src/components/VODPlayer.vue

**Comment by DerZade** [comment]
I experienced the same issue, when having circular references between components.

[Here](https://github.com/DerZade/volar-bug-report-1708) is a minimal reproducible example. (literally just `npm init vue@latest` with only two components)

Hope it helps!

**Comment by shurco** [comment]
Not work after update :(

**Comment by DerZade** [comment]
My issue seems to be resolved with v0.40.2 🥳 

Thanks a lot!

**Comment by andrewcourtice** [comment]
> In my case downgrading to 0.39.5 solved it.
> 
> Edit: I have experiencied many issues arround my code after update to 0.40+ (my components, vue imports, etc), after change to 0.39.5 they have been gone.

I've had several problems, especially with global components since v0.39.5 also.

**Comment by Tails128** [comment]
still broken in ```0.40.13```

**Comment by caio-2k** [comment]
> still broken in `0.40.13`

Refer to https://github.com/johnsoncodehk/volar/issues/1706#issuecomment-1233819252

**Comment by Tails128** [comment]
@caio-2k using as would be viable, but...

Looking a bit more into it, it seems the issue relates to the default `<slot>` element. Hence why it was hard to reproduce: the ts part of the code is fine until a `template` containing a `slot` is inserted.

While using `as` would be a solution, the main issue is there's no way to define a slot as any that I know of... Do you know if there's a way to do it?
