### ISSUE TITLE
Volar/vue-tsc no longer showing type errors in templates after v0.35.2

### ISSUE THREAD

**Issue by codethief** [johnsoncodehk/volar#1709]
I'm experiencing an issue related to type checking in templates: VSCode/Volar correctly shows a type violation when trying to pass a variable of type `SomethingNonFalsy | undefined` to a component's prop that basically only accepts `SomethingNonFalsy | null`:

![image](https://user-images.githubusercontent.com/207803/188835539-c12e7398-3347-498e-baf0-e91f744554db.png)

Prop definition:
![image](https://user-images.githubusercontent.com/207803/188836307-d50c05e3-d4b2-4b32-a3fe-e6fc36436c49.png)

However, `vue-tsc --noEmit` exits with code 0 and without showing any errors.

**Now here's the thing:** The above happened with VSCodium 1.70.0, vue-tsc 0.40.1 and Volar **0.30.1**. 

\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Intermezzo BEGIN ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The latter was the most recent version of Volar (more specifically: [johnsoncodehk.volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar)) that I could find in VSCodium:

![grafik](https://user-images.githubusercontent.com/207803/184117953-5f8c4861-0c74-4bb3-9b5d-4ff6999f8f65.png)
![grafik](https://user-images.githubusercontent.com/207803/184117836-b6d578e5-9fc7-485f-82c9-16f5eae8a76e.png)

My understanding is that the package `johnsoncodehk.volar` has been renamed to [`vue.volar`](https://marketplace.visualstudio.com/items?itemName=vue.volar) and only the latter comes with more recent versions. But `vue.volar` doesn't show up in my search results in VSCodium?

\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Intermezzo END ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Anyway, if I download `Vue.volar-0.40.1@linux-x64.vsix` manually from the marketplace and install it in VSCodium by hand, the above type error disappears, i.e. the behavior of Volar then matches the (IMO wrong) behavior of vue-tsc 0.40.1. Could it therefore be that a bug has been introduced here in the repo between Volar/vue-tsc 0.30.1 and Volar/vue-tsc 0.40.1?

To double-check I rolled back to vue-tsc 0.30.1. Now, `vue-tsc --noEmit` shows the same (correct) type error and, in fact, many other type errors in templates – not necessarily related to prop types – such as:

```
[…] error TS2345: Argument of type 'Maybe<string> | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

19         :disabled="disabledItems.includes(selectedItemId)"
                                             ~~~~~~~~~~~~~~

[…] error TS2533: Object is possibly 'null' or 'undefined'.

32             >{{ item.description }}</span
                   ~~~~
```

(Background: Both `selectedItemId` and `item` can indeed be `null` or `undefined`, so these type errors are correct as well.)

PS: I also happened to have vue-tsc v0.35.2 lying around – that version, too, fails to recognize the type errors.

**Comment by codethief** [comment]
I can't confirm that, unfortunately. Like v0.35.2 and v0.40.1, vue-tsc v0.39.5 doesn't show any of the type errors that it should. I believe the bug I'm seeing made it into the code base before v0.35.2.

**Comment by last-partizan** [comment]
I tested different versions of vue-tsc, and found `0.37.9` also working. (I'm using vue 2.7)

**Comment by fi3ework** [comment]
The same issue was encountered in vite-plugin-checker. No error was reported in `0.40.1`, after downgrading to `0.39.5`, everything works fine.

**Comment by codethief** [comment]
@Alverrt @last-partizan @fi3ework Again, it looks like you might be experiencing a separate issue. The present ticket is about a bug that's been occurring starting from at least v0.35.2. You seem to be talking about a bug that was introduced in 0.40.x? If so, would you mind opening a new ticket?

**Comment by johnsoncodehk** [comment]
Hi @codethief, first thanks for the report, but I can't reproduce it, could you try can it reproduce in https://github.com/johnsoncodehk/volar-starter?
