### ISSUE TITLE
[question] type error in template

### ISSUE THREAD

**Issue by germsb** [johnsoncodehk/volar#171]
Hi, I'm back :D
```vue
<slot
    v-for="(item, i) of items"
    name="select"
    :select="event => selectItem(event, item, i)"
/>
```
If I understood correctly, it is not possible to type in the template part.
In this example, I did not have the choice, I get an error ` Parameter 'event' implicitly has an 'any' type.` 
Is there a way to locally disable a typescript error? like `<! -- @ts-ignore -->`

**Comment by johnsoncodehk** [comment]
Hi @germsb, try this:

```vue
<slot
    v-for="(item, i) of items"
    name="select"
    :select="
        // @ts-ignore
        event => selectItem(event, item, i)
    "
/>
```

**Comment by germsb** [comment]
perfect !
