### ISSUE TITLE
Components type inference and highlighting got broken in version 0.40.0

### ISSUE THREAD

**Issue by jagoncalves14** [johnsoncodehk/volar#1711]
Looks like since Volar 0.40 was released that Components lost highlighting and type inference in my project.

This seems to be happening in versions 0.40.0 and 0.40.1
To confirm this, I rolled back VSCode's Volar plugin to version 0.39.5 and everything came back to work as before.

Example below:

**In version 0.39.5 👇**
![image](https://user-images.githubusercontent.com/17235977/184171024-f383685e-d3d4-4cdc-87b0-3337b689b8c0.png)

**In version 0.40.1 👇**
![image](https://user-images.githubusercontent.com/17235977/184171110-b2e99f83-06ca-46b6-8575-968abc2bbad4.png)

Notes:
**Typescript version:** 4.7.4

**Comment by francoism90** [comment]
"error ts7022: 'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer."

Downgrading to `0.39.5` solves the issue.

**Comment by ameryu716** [comment]
I am the same.
I had the same issue with all `.vue` and `.ts` files.
Reverting the Volar version to `0.395` works fine.

I appreciate this extension. thank you for always.

**Comment by Ragura** [comment]
This might not be the exact same issue because mine wasn't fixed by downgrading Volar's version. I had the same problem and thought it was caused by Volar, but it turned out to be caused by the plugin `unplugin-vue-components`. If you are using a recent version of the plugin together with pnpm, you need to take extra steps to resolve the issue (add shamefully-hoist to `.npmrc`). For more information, read this issue: https://github.com/antfu/unplugin-vue-components/issues/477

After following the instructions in the last post on the linked issue, intellisense worked again, even with the latest version of Volar.

**Comment by jagoncalves14** [comment]
Updated the extension to version to the recent 0.40.6 and the issue seems to be resolved.

@francoism90, @ameryu716 — can you also confirm this, so I can close the issue?

**Comment by francoism90** [comment]
@jagoncalves14 It indeed seem to fix the issues, thanks! :)

**Comment by cawa-93** [comment]
Still got similar issue when checks types by `vue-tsc` v.0.40.7 in nuxt rc-9

```node
components/SingoutAndNavigateLink.vue:1:25 - error TS7022: 'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectl
y in its own initializer.

  1 <script lang="ts" setup>
                            
  2 import { useCookie } from '#imports'
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 10 }
    ~
 11 </script>
   

components/CabinetHeader.vue:1:25 - error TS7022: 'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its 
own initializer.

  1 <script lang="ts" setup>
                            
  2 import { IconList } from '@iconify-prerendered/vue-bi'
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 13 })
    ~~
 14 </script>
```

**Comment by johnsoncodehk** [comment]
@cawa-93 If should be a different problem, if you still have this problem with v.0.40.13 or newer, please open an new issue and provide repro case.
