### ISSUE TITLE
tsconfig excluded files are ignored in v0.40.0 (regression)

### ISSUE THREAD

**Issue by cexbrayat** [johnsoncodehk/volar#1712]
The following repo contains a reproduction 

https://github.com/cexbrayat/volar-exclude-regression

The repo is a simple project created with create-vue. The second commit adds a component called `Repro` that has a template with an error with `"strictTemplates": true` but that component is ignored in tsconfig, so `npm run type-check` still works.

The third commit bumps vue-tsc to v0.40.1 and `npm run type-check` fails with:

```
> vue-tsc --noEmit

src/components/Repro.vue:3:6 - error TS2604: JSX element type 'Users' does not have any construct or call signatures.

3     <Users></Users>
       ~~~~~


Found 1 error in src/components/Repro.vue:3
```

It looks like there is a regression in v0.40.0 that messes up the exclusions.

**Comment by johnsoncodehk** [comment]
This is expected behavior, because Repro.vue is used in App.vue. You should also exclude main.ts -> App.vue to ignore Repro.vue errors.

```
  "exclude": [
    "src/components/Repro.vue",
    "src/App.vue",
    "src/main.ts",
  ],
```

**Comment by cexbrayat** [comment]
@johnsoncodehk Using v0.39 or lower, this was working without having to exclude other files that include the one with an error. If it is not possible to restore this behavior, is there a way to ignore errors in the template (as `ts-ignore`?) Some errors are sadly hard/impossible to fix, and excluding all of the hierarchy is not really an option in that case...

**Comment by johnsoncodehk** [comment]
@cexbrayat It should report error, v0.39 or lower should be have something wrong if no error with it.

Do you accept using @ts-nocheck?

**Comment by cexbrayat** [comment]
Right, `@ts-nocheck` is an option 👍 

But sometimes you want to just ignore one line in the template, not the complete file like we can do with `@ts-ignore` in TS code. It would be awesome to have the same in templates.

**Comment by johnsoncodehk** [comment]
I want to avoid introducing new syntax for this, but you can open a feature request for it, so we can discuss it.

**Comment by johnsoncodehk** [comment]
Btw, this error should not report any more in v1.0.0-alpha by default. (unless enable `vueCompilerOptions.jsxTemplates`)
