### ISSUE TITLE
BUG in version 0.40 and 0.41

### ISSUE THREAD

**Issue by wallysonn** [johnsoncodehk/volar#1715]
When using namespace in components, intellisense does not work and says that the component is not being used. In version 0.39.5 I don't have this problem.
![Image preview 1](https://i.imgur.com/aU9WGHe.png)
![image preview 2](https://i.imgur.com/hVlKzWT.png)

In version 0.39.5 the result is:
![Preview 3](https://i.imgur.com/viiuRLs.png)

**Comment by RosApr** [comment]
same problem

**Comment by rainwellyh** [comment]
我也是这个问题！

**Comment by muhamadamin1992** [comment]
same problem

**Comment by Eusebius1920** [comment]
I am seeing the exact same issue:

- 0.39.5 works
- 0.40.0 does not work
- 0.40.1 does not work either

Same with variables that are defined (in script setup) and only used in the template

**Comment by colinblaise** [comment]
I'm seeing further issues even on 0.39.5.

Undefined properties are not throwing any errors

![image](https://user-images.githubusercontent.com/6540262/185199387-b2758266-af8e-4cb6-87a7-bbe642200367.png)

**Comment by kdlslyv** [comment]
0.40.0 onwards can no longer handle vue2 class components for me

```
@Component
export default class Home extends Vue {
...
}
```

![image](https://user-images.githubusercontent.com/13890151/185493191-b0cf22c1-db74-49e9-ad8d-be7566207832.png)

**Comment by kwarnkham** [comment]
Same here

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/3d84c0d8f5b55a347f437b580e722cdc2da91178.
