### ISSUE TITLE
Supoort for Nuxt 3 direct components?

### ISSUE THREAD

**Issue by tobychidiu** [johnsoncodehk/volar#1716]
![image](https://user-images.githubusercontent.com/111127651/184455109-49aa7426-2cb3-451d-a5b2-e4672b8c04ef.png)

Cannot find module '#components' or its corresponding type declarations.

**Comment by so1ve** [comment]
Maybe there is something wrong with your tsconfig.json configuration.

**Comment by tobychidiu** [comment]
Yes. There was. The issue was fixed in a recent edge release of Nuxt 3, Thanks 🙂
