### ISSUE TITLE
input"{"  in html appear "{}}"

### ISSUE THREAD

**Issue by liweiook** [johnsoncodehk/volar#1717]
When I input "{" in template, "{}}" will appear. I used the VScode extension "Start extexsion bisect" and found that Volar added it to me. Why is that?
![image](https://user-images.githubusercontent.com/42706756/184502028-6bbc5431-5707-4218-8a83-fbffab3c7007.png)

![image](https://user-images.githubusercontent.com/42706756/184502014-2f6c6e6e-2815-4edf-806a-f23d0d7652a0.png)

**Comment by liweiook** [comment]
If I have the value of the "Auto Closing Brackets" changed from "always" to "never" and I type "{" to get "{}",.it mean both Volar and VSCode to add "}" for me. But when I delete "{","}" will not be deleted, which means that Volar will not comply with "Auot Closing Delete".
![image](https://user-images.githubusercontent.com/42706756/184502638-7555d440-e5d1-45fc-8eab-7f99d495fd8e.png)

**Comment by liweiook** [comment]
only type in <></>, For example, there is a problem at 1. But it's fine at 2. Then I type "{" twice in 3 and get "{{}}}"
![image](https://user-images.githubusercontent.com/42706756/184503022-0f331b68-e996-4f7b-aaa7-650c7f35c39f.png)

**Comment by liweiook** [comment]
if I changed the  value of"Auto Closing Brackets" to default value--"languageDefined",its also have the problem.

**Comment by liweiook** [comment]
Sorry, I know why. Volar conflicts with VUe-helper. If I disable all plug-ins and only turn on Volar, there is no error. This error occurs if I enable VUe-Helper together. Oddly enough, when I only start the VUe-helper, the VUe-helper does not actively add "}" for me. Why did they make this mistake when they were together? So I'm going to have to disable it, although I like some of its features, it's very useful. If possible, I hope the authors give these features to Volar.

**Comment by johnsoncodehk** [comment]
@liweiook Thanks for the information, it seems from https://github.com/jiaolong1021/vue-helper/blob/f1c1e82f23bb5f3f227b17099c3118bfe6d881dc/src/app.ts#L1141-L1151.
