### ISSUE TITLE
"} expected css(css-rcurlyexpected)" error when using postcss-nested

### ISSUE THREAD

**Issue by segevfiner** [johnsoncodehk/volar#1720]
I get CSS errors such as "} expected css(css-rcurlyexpected)" with the following component:
```vue
<script setup lang="ts"></script>

<template>
  <header>
    <div class="hello">Hello</div>
  </header>
</template>

<style scoped>
header {
  line-height: 1.5;

  .hello {
    color: red;
  }
}
</style>
```

And with:
```js
module.exports = {
  plugins: [require('postcss-nested')],
};
```

With:
VS Code v1.70.1
Volar v0.40.1
csstools.postcss v1.0.9 (The syntax highlighting it adds does seem to work)

**Comment by segevfiner** [comment]
If Volar could add support for using [`csstools.postcss`](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) for SFC `style` tags without a `lang` it might make this work.

**Comment by segevfiner** [comment]
### Workaround
Use the deprecated/unmaintained extension `cpylua.language-postcss` and add `lang="postcss"` to all `style` tags using postcss syntax. Not ideal as it requires changes to the code and that extension is not maintained.

**Comment by johnsoncodehk** [comment]
You can try disable `css.validate` in VSCode. For `lang="postcss"` language support, you can use language service plugin API (#1027) to implement, we have no plan to built-in support currently.

**Comment by MrEraxd** [comment]
@segevfiner How did you get this to work? It does not work for me. Do you have any settings in config?

![image](https://user-images.githubusercontent.com/34748386/189941274-efbcbcbf-65d3-48bb-a299-4e30297ffe63.png)

**Comment by segevfiner** [comment]
We also have a postcss config file, and not have the other postcss extension installed. Not sure what else.

**Comment by MrEraxd** [comment]
Can you share your postcss config?

**Comment by johnsoncodehk** [comment]
@MrEraxd for `<style lang="postcss">`, try setting `"postcss.validate": false` in .vscode/settings.json.
