### ISSUE TITLE
Declare type `const ` in `<template>`

### ISSUE THREAD

**Issue by tachibana-shin** [johnsoncodehk/volar#1721]
Hi,

As you can see I have a prop with type `Data.Link` and attribute `[AT_TYPE]` but when I access this property in `<template>` an error occurred while in `<script>` it worked fine

![Ảnh chụp màn hình 2022-08-15 200650](https://user-images.githubusercontent.com/45375496/184640643-8ae53701-c558-4f1e-b4d0-9ba5e78bf2ba.png)

![image](https://user-images.githubusercontent.com/45375496/184641144-96dcfa02-eb9a-49ec-804b-c1299e39c559.png)

**Comment by xiaoxiangmoe** [comment]
Can you provide me a minimal reproducible example?
