### ISSUE TITLE
vue3 2个组件相互引用报错

### ISSUE THREAD

**Issue by hkaikai** [johnsoncodehk/volar#1722]
“default”隐式具有类型 "any"，因为它不具有类型批注，且在其自身的初始化表达式中得到直接或间接引用。

**Comment by ann0gy** [comment]
#1708 目前看来只能降级解决

**Comment by so1ve** [comment]
我把Volar降级又升级了 Bug消失术👀

**Comment by johnsoncodehk** [comment]
Duplicate of #1708
