### ISSUE TITLE
[Feature request] Need find component's references in <script setup> sugar

### ISSUE THREAD

**Issue by melan0802** [johnsoncodehk/volar#1724]
Seems like there is no way to find current component's references in <script setup> tag. Which is one of the best feature of Volar in my mind. Maybe we can add 'Go to References' for script/setup/template symbol?

**Comment by johnsoncodehk** [comment]
You can use find file references in right click menu or command palette.

<img width="420" alt="螢幕截圖 2022-08-27 23 57 49" src="https://user-images.githubusercontent.com/16279759/187038026-b905c819-447e-40ae-8798-9ac8aac91312.png">
