### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by theRenard** [johnsoncodehk/volar#1728]
Hi, I'm on a vue 2.6.14 using class components with vue-property-decorator, got a lot of errors of this kind.

![image](https://user-images.githubusercontent.com/61255863/185201281-b94b7a0d-6b14-401b-9c49-cc488dcacebc.png)
 
![image](https://user-images.githubusercontent.com/61255863/185201894-4c73d580-58f8-4959-be64-90cf2118a37d.png)

**Comment by nikosgpet** [comment]
I am on vue 3 and a similar error appeared for a component with a complicated type. Is there a way to disactivate this error inside the template ?

**Comment by theRenard** [comment]
I had inconsistent behavior in a way that as you said a complex component made ts go nuts but I can tell you that I had these errors on __every__ SFC. It seems to work right now 🤞 with a different version of typescript (4.9 on VSC, 4.5.2 on my project).

What I've done is force ts version for ts server on workspace settings

// .vscode/settings.json

    { ...   "typescript.tsdk": "./node_modules/typescript/lib" ... }

before moving to volar I had vetur crashing like crazy so maybe it was just a VSC ts update that doesn't like my code 🙁

**Comment by johnsoncodehk** [comment]
I think this is not Volar problem, but if you can provide repro case I may able to find the problem. 😅

**Comment by theRenard** [comment]
Hi @johnsoncodehk, unfortunately I can't share this repository but I can share my experience: the problem goes away when I remove all components from decorator (and import all of them in batch into a dedicate file). This works pretty much 90% of the time. Another issue I've noticed that is probably related is that when one file has errors, they cascade also in files that otherwise are ok. In this case I just have to close the incriminated tab and reload VSC window. It works all the time.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem with move the code from `<script>` block to a .ts file with disable takeover mode?

If it can't reproduce it should be `@Component` problem, you should report to vue-property-decorator repo.

**Comment by theRenard** [comment]
Alright, with takeover mode disabled I can reproduce it

<img width="389" alt="image" src="https://user-images.githubusercontent.com/61255863/191688843-e8e95d50-30e6-4c67-b59f-425c8890ebc8.png">

this is a .ts file.

With takeover mode enabled I don't have the error, BUT if there's another VSC tab with an error in it, it cascades also into all open files, in this case the .ts file

![2022-09-22 09 53 21](https://user-images.githubusercontent.com/61255863/191690315-e2b3d40c-4354-4797-be71-5ac98d126137.gif)

En example of error after pasting component into decorator, on the left the .ts file on the right the .vue file

**Comment by johnsoncodehk** [comment]
Thanks for the information, so it should be `vue-property-decorator` problem.

I can't sure without repro case if this works, but you can try:

```ts
const options = { components: { ModalDialog } } as any;

@Component(options)
export default ...
```

**Comment by pkonieczniak-statscore** [comment]
I had the same issue in monorepo with many Vue 2 apps. We're migrating some legacy Vue 2 class components code to composition/options API.

Instead of changing manually typings to `any` for each component I overwritten typings for `vue-property-decorator` lib which looks to be not maintnained anymore.

shims.d.ts
```js
import 'vue-property-decorator'
declare module 'vue-property-decorator' {
  export declare function Component(options: ComponentOptions): any
};
```

**Comment by pkonieczniak** [comment]
I had the same issue in monorepo with many Vue 2 apps. We're migrating some legacy Vue 2 class components code to composition/options API.

Instead of changing manually typings to `any` for each component, I overwrote typings for `vue-property-decorator` lib which looks to be not maintained anymore.

shims.d.ts
```js
import 'vue-property-decorator'
declare module 'vue-property-decorator' {
  export declare function Component(options: ComponentOptions): any
};
```
