### ISSUE TITLE
Breaking component import. "... is declared but its value is never read"

### ISSUE THREAD

**Issue by Ailis7** [johnsoncodehk/volar#1729]
Hello!
Tell me when you fix this problem, and will you? :)
I don’t know if this error was introduced .. or how to get around it, but there is no such problem with the functions.
Only when importing components. Thank you!
![image](https://user-images.githubusercontent.com/57756040/185363744-0f1cd960-691a-4043-970c-2b14e8101a7b.png)

**Comment by Ailis7** [comment]
![image](https://user-images.githubusercontent.com/57756040/185378610-dd3fe57b-bfc5-4a60-933f-271045bae7e2.png)
Found a similar problem with functions

**Comment by Ailis7** [comment]
Hmm, in this form it is not possible to use the extension (I returned to Vetur and turned off the script validation setting + installed the usual extension of EsLinter. Maybe it will help someone:
![image](https://user-images.githubusercontent.com/57756040/185380850-5c8a5e94-65ca-4aa4-81ce-400e8e1a0c54.png)

**Comment by esbeto** [comment]
I discovered that I by adding `"jsx": "preserve",` in my jsconfig `compilerOptions`, it solved this issue.

Looks something like this:
```
{
  "compilerOptions": {
    "jsx": "preserve",
    // other stuff
  },
}
  ```

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/6f79f8fe77efe90ead624d6731de414cbb029331.
