### ISSUE TITLE
Using "moduleResolution": "node16" causes "Module 'somelib/browser' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead." for ESM only modules

### ISSUE THREAD

**Issue by segevfiner** [johnsoncodehk/volar#1730]
1. Clone `https://github.com/segevfiner/vite-self-reference`
2. Open "apps/web/src/App.vue".
3. You will get:
    ```json
    [{
	    "resource": "/Users/segevfiner/junk/vite-self-reference/apps/web/src/App.vue",
	    "owner": "_generated_diagnostic_collection_name_#0",
	    "code": "1471",
	    "severity": 8,
	    "message": "Module 'somelib/browser' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.",
	    "source": "ts",
	    "startLineNumber": 3,
	    "startColumn": 28,
	    "endLineNumber": 3,
	    "endColumn": 45
    }]
    ```

**Comment by johnsoncodehk** [comment]
It seems expected behavior, I got same error when move `import { helloAlert } from 'somelib/browser'` to main.ts (with takeover mode disabled).

**Comment by segevfiner** [comment]
It might be that they made this extra confusing by essentially not really caring what `"module"` says in this mode and just using the node strategy of `"type": "module"` in `package.json` and `.cjs, .mjs, .cts, .mts` extensions to figure out what the module format is. Even if you specify in tsconfig.json `"module": "ESNext"` it will still consider the module to be CommonJS if the `package.json` doesn't say `"type": "module"`. Doesn't help that `tsc` also has poor support for outputting dual packages in the first place. Well this mode is kinda new... Hopefully they might decide to improve it... or not... tsconfig.json related issues are getting on my nerves lately...
