### ISSUE TITLE
Vue3 using type-based DefineEmits receives incompatible error

### ISSUE THREAD

**Issue by sw-joechen** [johnsoncodehk/volar#1732]
// child component
![image](https://user-images.githubusercontent.com/101158194/185555091-2f9e735d-f638-4768-bede-44460bc3458e.png)

// parent component
![image](https://user-images.githubusercontent.com/101158194/185555181-a9c9cff3-d488-4c7c-bcbd-727b4547b855.png)

it works fine in v0.35.0

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter, please provide minimal reproduction.

**Comment by sw-joechen** [comment]
I created a new project with
`npm init vue@latest`
add the code which is shown above
run build script
`npm run build`
you will receive the error like above
here is the repo 
https://github.com/sw-joechen/demo2
thanks for replying

**Comment by johnsoncodehk** [comment]
It seems fixed in v0.40.2.
