### ISSUE TITLE
变量和方法不能高亮

### ISSUE THREAD

**Issue by baibaibai455** [johnsoncodehk/volar#1734]
变量和方法不能高亮，只在模板中引用的变量不能高亮
<img width="932" alt="image" src="https://user-images.githubusercontent.com/47173675/185599140-5cdbfee5-2e7f-4672-9b30-67cadd62e35f.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/47173675/185599401-76a19848-1be7-4289-ba2b-92369e83a9f7.png">

**Comment by yeyuqh** [comment]
```json
"editor.semanticHighlighting.enabled":  true
```

**Comment by baibaibai455** [comment]
> ```json
> semanticHighlighting
> ```

尝试了一下，并没有作用，template中引用的不能高亮

**Comment by baibaibai455** [comment]
> ```json
> "editor.semanticHighlighting.enabled":  true
> ```


 尝试了一下，并没有作用，template中引用的不能高亮

**Comment by baibaibai455** [comment]
已经安装了Volar  并卸载了Vetur

**Comment by johnsoncodehk** [comment]
Duplicate of #1729
