### ISSUE TITLE
Using the ts plugin outside vscode

### ISSUE THREAD

**Issue by egoist** [johnsoncodehk/volar#174]
I'm using rollup-plugin-typescript2 with Vite, but rollup-plugin-typescript2 cannot recognize .vue files, so maybe adding a ts plugin manually to tsconfig.json would help, similar to https://www.npmjs.com/package/typescript-svelte-plugin, is this already possible?

**Comment by johnsoncodehk** [comment]
I planed to publish `typescript-vue-plugin` in 0.25.3, please track #169.
