### ISSUE TITLE
Can't install 'vue.volar' extension because it is not compatible with the current version of Visual Studio Code (version 1.70.2).

### ISSUE THREAD

**Issue by tassoman** [johnsoncodehk/volar#1751]
Hello there,
  I'm running VSCode on Windows10 remotely connected to its version inside WSL:Ubuntu in a WSL2 environment Ubuntu Jammy.

The problem with this extension happen when I try to install for the project, looks like version it's not compatible

- Volar extension version: v0.40.1
- VSCode version: 1.70.2

**Comment by pdob-git** [comment]
Me too.
- The same version of Volar. 
- VSCode 1.62.3

**Comment by johnsoncodehk** [comment]
Please update WSL env VSCode to latest.

**Comment by tassoman** [comment]
Problem persists with

- Volar 0.40.13
- VsCode 1.71.2

![Screenshot (52)](https://user-images.githubusercontent.com/92727/191741315-186d57ce-b0ca-42da-9a0c-d788813216aa.png)

**Comment by johnsoncodehk** [comment]
Should be fixed in VSCode: https://github.com/microsoft/vscode/issues/142890
