### ISSUE TITLE
now if you use await,volar can't throw a error that you should use async in the function

### ISSUE THREAD

**Issue by jianxingxuejian** [johnsoncodehk/volar#1753]
```
<script setup lang="ts">
  async function test1() {
    await do something
  }
  function test2(){
    await test1()
  }
</script>
```

**Comment by CressZZ** [comment]
I have same issue.

Is it related with version update?

Because I found this issue on today.....

**Comment by jianxingxuejian** [comment]
> I have same issue.
> 
> Is it related with version update?
> 
> Because I found this issue on today.....

yes, it worked normally in  v0.39.5.
