### ISSUE TITLE
Template interpolation syntax highlighting

### ISSUE THREAD

**Issue by rhernandog** [johnsoncodehk/volar#1759]
Hello,

First thanks for the great work in this package!!!

It seems that since the last update syntax highlighting for template interpolation (double curly braces) is not working on VSCode, as show in the image:

![Screenshot from 2022-08-24 11-48-26](https://user-images.githubusercontent.com/4622323/186464353-32a880b0-5fb3-4c93-8cc1-dd0c694b8231.png)

Is not a breaking situation, but it would be nice to have it back if this was ever implemented of course, honestly I can't remember if the extension had this before. If it didn't it'd be great to include it.

Best,
Rodrigo.

**Comment by johnsoncodehk** [comment]
Do you have enable `editor.bracketPairColorization.enabled` in VSCode?

**Comment by rhernandog** [comment]
@johnsoncodehk Yep is set to true in the global configs in VSCode.

In fact here is the same file using Vetur:
![image](https://user-images.githubusercontent.com/4622323/187041942-c6e522c5-017d-44b8-81a6-c6916e6c14a2.png)

**Comment by johnsoncodehk** [comment]
I guess this is a random problem with new VSCode version. Volar only provides `colorizedBracketPairs` that are not repeated for embedded html language. VSCode may have changed the resolution.

https://github.com/johnsoncodehk/volar/blob/master/extensions/vscode-vue-language-features/languages/sfc-template-language-configuration.json

**Comment by rhernandog** [comment]
What's really baking my noodle is why(how) is working on Vetur?? :confused:

**Comment by johnsoncodehk** [comment]
Vetur define template langauge as `vue-html`, Volar use `html`, it may the different.

**Comment by johnsoncodehk** [comment]
It can always reproduce in latest VSCode version, I have to see what are VSCode doing. 👀
