### ISSUE TITLE
Disable volar type checking for template attributes

### ISSUE THREAD

**Issue by mseele** [johnsoncodehk/volar#176]
I got a (wrong) typescript error for placeholder attribute.
```
<Textbox
            v-if="isTextbox"
            :id="data.columnKey"
            :key="index"
            v-model="record.value.proposal"
            :placeholder="record.value.released"
            :name="data.columnKey"
            :label="label(record)"
            class="col-span-full"
          />
```

It should be possible to tell typescript via @ts-ignore or @ts-expect-error to skip these errors

**Comment by johnsoncodehk** [comment]
You can use `@ts-ignore` in expression and interpolation in template, but `:placeholder="record.value.released"` across over html and expression content, we can't support something like `@ts-ignore` for that without a new syntax, so you can only define a helper function to resolve.

```vue
<template>
...
:placeholder="asAny(record.value.released)"
...
</template>

<script lang="ts">
...
const asAny = (foo: any) => foo as any;
...
</script>
```

**Comment by neal2018** [comment]
Hey, I am using javascript so I am not able to use an  `asAny` helper function to convert type. 
Is there any other workaround? Any help is appreciated.

**Comment by johnsoncodehk** [comment]
@neal2018 Just remove types from function in js: `const asAny = (foo) => foo;`

**Comment by filiperaupp-egsys** [comment]
There is a way to disable type check on template properties? I'm using the last version of Volar
![image](https://user-images.githubusercontent.com/58449123/206723873-b8cc6d09-5c53-4efd-81a5-b36e2ae7ea8e.png)

**Comment by olivierlauzon85** [comment]
@filiperaupp-egsys did you figure out a way? I am migrating a project from Vue2 to Vue3, and as much as I like having type checks in template, I would like to disable them for now.

**Comment by filiperaupp-egsys** [comment]
@olivierlauzon85 unfortunately i didn't find a right way to resolve this. But, in my case, i could use a workaround adding type to the prop on the template, like this:
```html
<q-input>
  ...,
  :type="(type as any)"
/>
```

**Comment by johnsoncodehk** [comment]
@filiperaupp-egsys Currently there is no way, unless we introduce additional syntax for this. If you think this feature is still needed, please open a feature request.
