### ISSUE TITLE
No type hints when hovering an imported .vue component

### ISSUE THREAD

**Issue by zam157** [johnsoncodehk/volar#1760]
no type hints: 
![image](https://user-images.githubusercontent.com/24277775/186546238-9a8e1b47-e0fe-491a-bec5-e51db6cede91.png)

autocomplete:
![image](https://user-images.githubusercontent.com/24277775/186546932-15f4b89d-56e8-4e83-82ef-bd04eeb68da6.png)

**Comment by johnsoncodehk** [comment]
This is typescript language service behavior we can't change.
