### ISSUE TITLE
在标签里面使用大括号，会多生成一个

### ISSUE THREAD

**Issue by jialouluos** [johnsoncodehk/volar#1769]
![image](https://user-images.githubusercontent.com/82502205/186893631-dca561ee-b179-4bcf-b221-200221719b5e.png)

**Comment by jialouluos** [comment]
在问题得到解决之前，我不得不换回Vetur,非常影响我的代码效率

**Comment by a145789** [comment]
最新版本在我的 `vscode` 没出现问题，提供点更详细的信息给作者，比如 vscode 配置或者更详细的复现场景。

**Comment by lsdt45** [comment]
你是不是用了vue-helper?把它关掉就可以了。

**Comment by jialouluos** [comment]
> 你是不是用了vue-helper？把它关掉就可以了。

是的，我刚试了下，现在成功解决了，非常感谢

**Comment by jialouluos** [comment]
> 在我没有出现问题的最新版本`vscode`中，提供点更详细的信息给作者，例如 vscode 配置或者更详细的现场场景。
应该是vue-helper导致的一些问题，现在已经解决了

**Comment by johnsoncodehk** [comment]
Duplicate of #1717

**Comment by ghostcode** [comment]
> 你是不是用了vue-helper?把它关掉就可以了。

感谢，关掉就好了。
