### ISSUE TITLE
Why result of using shift+alt+f format code is defferent from formating on save?

### ISSUE THREAD

**Issue by kkqy** [johnsoncodehk/volar#1773]
I use shift+alt+f for formating code manually，but the result have so many warnings (against some rules of eslint).
but when I use ctrl+s for saving ,It will automatically format code because of "formating on save" setting , the result is perfect and there is no error or warnings.
It seems like that the "formating on save" will obey the rules that defined in config of eslint.
How to make "shift+alt+f" do the same thing?

**Comment by kissu** [comment]
Depends on what you do use as your formater I guess.

**Comment by KuoKongQingYun** [comment]
> Depends on what you do use as your formater I guess.

I use volar as formatter, but it dosen't obay rules of eslint.

**Comment by johnsoncodehk** [comment]
We don't support ESLint rules on formatting, if you should use ESLint instead of Volar to format if you need follow ESLint rules.
