### ISSUE TITLE
template里用了element-plus的el-table,属性中align为红色

### ISSUE THREAD

**Issue by yanllllk** [johnsoncodehk/volar#1774]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/31483702/187066041-ddf9742c-bbd9-4ca6-9151-62c3693a2f59.png">

vscode 1.70.2
volar 0.40.2

使用element-plus 2.2.15

其中的template里,el-table-column的属性 align标成了红色.

align在新的标准中,被标为了废弃,可能是这个原因 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#Attributes
但这是element-plus中的属性,有没有解决办法?

**Comment by Cheerwhy** [comment]
不仅align border也会红，换个主题解决 用one dark pro

**Comment by johnsoncodehk** [comment]
Duplicate of #1363
