### ISSUE TITLE
"You may need an additional loader to handle the result of these loaders."

### ISSUE THREAD

**Issue by Reptiluka** [johnsoncodehk/volar#1776]
I spend like 5 hours trying to fix this extension, and it never worked....
The extension told me a problem with <template>, should add "jsx": "preserve" in tsconfig file,
then i have a <script> tag, he want to add lang="ts", and when i add this i got :
![image](https://user-images.githubusercontent.com/26306696/187095602-8468ed2c-efab-4de7-bdae-b06587153f33.png)

I'm with Inertiajs in an Adonisjs project, but i don't think it's related.
Even 2 years ago, when i tried a simple vue project or a Nuxt project, this extension never never works...
It is a lie or ????? Someone already have some intellisense in their vue project ? I think i dont believe it...

**Comment by johnsoncodehk** [comment]
`"jsx": "preserve"` is not required by default after v1.0.0-alpha.0 you can try.
