### ISSUE TITLE
导致重复的提示 Repeated code hints

### ISSUE THREAD

**Issue by aquawius** [johnsoncodehk/volar#1777]
Type: <b>Bug</b>

开启扩展后,编辑html文件将会出现与vscode自带的提示相同的提示,关闭本插件即可修复(我通过禁用插件二分法查找得到问题tracker)

Translate: When the extension is turned on, editing the HTML file will appear the same as the prompt provided by VSCode. It can be fixed by closing the plugin (I got the issue tracker by disabling the plugin dichotomy).

![image](https://user-images.githubusercontent.com/70997816/187106576-cc7c5415-e576-4bb8-bd01-184b4f362d58.png)

Extension version: 0.40.4
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (7.71GB free)|
|Process Argv|--crash-reporter-id adef78c7-cb6f-4c2e-bf4d-ab78fba7ed0f|
|Screen Reader|no|
|VM|44%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by johnsoncodehk** [comment]
Fixed by #1878, please try v1.0.0-alpha.x.
