### ISSUE TITLE
script setup + vue 2 (& model) + vue-tsc not support?

### ISSUE THREAD

**Issue by juner** [johnsoncodehk/volar#1778]
# problem
`script setup` + `vue2` ( `export default { model }` ) + `vue-tsc` does not support specifying `props / emits` for `v-model`.

1. add props and emits

```ts
type Props = {
    inputValue: boolean;
};
const props = defineProps<Props>();
const emits = defineEmits<{
    (name:"change", value:boolean):void
}>()
```

2. add export default model

```ts
export default {
    model: {
        prop: "inputValue",
        event: "change",
    },
}
```

3. use v-model

```vue
<checkbox-sample v-model="checked" />
```

# error.

## vue 2.6
![vue2 6_error](https://user-images.githubusercontent.com/753914/187107395-48b74d85-329d-4896-be64-5618ce2748f0.png)

* [HelloWorld.vue#L9](https://github.com/juner/vue_model_volar_error_sample/blob/3517340f593a9ea75e2be73429bc49d1296e80e0/vue2.6/src/components/HelloWorld.vue#L9)
* [CheckboxSample.vue#L7](https://github.com/juner/vue_model_volar_error_sample/blob/3517340f593a9ea75e2be73429bc49d1296e80e0/vue2.6/src/components/CheckboxSample.vue#L7)

## vue 2.7
![vue2 7_error](https://user-images.githubusercontent.com/753914/187107402-a5b3a56c-2e68-4e84-8718-1cd38b1ad157.png)

* [HelloWorld.vue#L9](https://github.com/juner/vue_model_volar_error_sample/blob/3517340f593a9ea75e2be73429bc49d1296e80e0/vue2.7/src/components/HelloWorld.vue#L9)
* [CheckboxSample.vue#L7](https://github.com/juner/vue_model_volar_error_sample/blob/3517340f593a9ea75e2be73429bc49d1296e80e0/vue2.7/src/components/CheckboxSample.vue#L7)

# sample project.

[juner/vue_model_volar_error_sample](https://github.com/juner/vue_model_volar_error_sample/tree/3517340f593a9ea75e2be73429bc49d1296e80e0)

# version

* vue-tsc : 0.40.1
* vue: 2.6.14 / 2.7.8

**Comment by xiaoxiangmoe** [comment]
It looks like vue 3 doesn't support this API.

**Comment by juner** [comment]
> It looks like vue 3 doesn't support this API.

Does that mean v-model only supports `prop:value` and `event:input` in vue2?

**Comment by johnsoncodehk** [comment]
> Does that mean v-model only supports `prop:value` and `event:input` in vue2?

Yes, unfortunately we have no plans to support this, but you can try cheating vue-tsc with `type Props = { value: boolean; inputValue?: boolean; };`.
