### ISSUE TITLE
Emmet error on style tag  after installed volar.

### ISSUE THREAD

**Issue by wgf4242** [johnsoncodehk/volar#1780]
![image](https://user-images.githubusercontent.com/3336626/187120531-b471919d-3cb8-4096-9c22-f196f7281e4a.png)

`div{ ` should not show emmet in style tag.

Installed volar got this error.

VSCode: 1.70.2

Vue.volar-0.40.1：Works.
From Vue.volar-0.40.2:   Get this emmet error.

**Comment by johnsoncodehk** [comment]
Should be fixed in v1.0.0-alpha.0.
