### ISSUE TITLE
JSX element type 'X__VLS_' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#1783]
> JSX element type 'X__VLS_' does not have any construct or call signatures.

I have this component in my source code:

```vue
<script lang="ts">
import type { QInputProps } from 'quasar';
import { QInput } from 'quasar';
import { defineComponent } from 'vue';

// @ts-expect-error: We know what we are doing
export default defineComponent<QInputProps>({
  ...QInput,
  ...{
    props: {
      ...QInput.props,
      outlined: { type: Boolean, default: true },
    },
  },
  name: 'DInput',
  inheritAttrs: true,
});
</script>

<template lang="pug">
QInput(v-model="modelValue", :outlined="outlined ?? true")
</template>
```

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/187155251-a4de2d6b-de30-428e-ab16-ff5e794b6f83.png">

It shows this warning when updating Volar to 0.40.2, with 0.40.1 everything was working and it showed no errors

I'm still on TS 4.7.4 and not 4.8
Using `vue-tsc` and `@volar/pug-language-service`

**Comment by johnsoncodehk** [comment]
Version > v0.40 have a few pug mapping issues, you can use v0.39.5 for pug for now.

**Comment by chy9610** [comment]
It happened to me too. Error after click event._(:з」∠)_

**Comment by Shinigami92** [comment]
This bug starts to spread side effects for me as https://github.com/simonhaenisch/prettier-plugin-organize-imports/releases/tag/v3.1.1 now declared 0.40.2 as peer dep...
So I have a second dep now that I cannot upgrade as 0.40.1 is the last working version

**Comment by johnsoncodehk** [comment]
@Shinigami92 It's planed to fixed in v0.40.12.

**Comment by Shinigami92** [comment]
> @Shinigami92 It's planed to fix in v0.40.12.

Tested with `v0.40.13` and still same issue

**Comment by johnsoncodehk** [comment]
Sorry because I found it not so easy to fix, may have to rewrite lot of the code, but will soon.

**Comment by Shinigami92** [comment]
Meanwhile, I'm working with `v0.40.1`
So no real hurry, take your time and make it right
I see that there are/were many issues and PRs in the last weeks 🙏
