### ISSUE TITLE
useNuxtApp() type checking

### ISSUE THREAD

**Issue by szulcus** [johnsoncodehk/volar#1785]
Hi! I decided to use Nuxt 3. I have a little problem with types. Why do types work for the `$dayjs` plugin, but no longer work for `$route` and `$hello`?

![image](https://user-images.githubusercontent.com/48328739/187229741-07d53531-bbca-407d-8a08-89fcc1a98516.png)

~/plugins/dayjs.ts
```
import { defineNuxtPlugin } from '#app';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime.js';

declare module '#app' {
	interface NuxtApp {
		$dayjs(date?: dayjs.ConfigType): dayjs.Dayjs;
	}
}
declare module '@vue/runtime-core' {
	interface ComponentCustomProperties {
		$dayjs(date?: dayjs.ConfigType): dayjs.Dayjs;
	}
}

export default defineNuxtPlugin(({ provide }) => {
	// eslint-disable-next-line import/no-named-as-default-member
	dayjs.extend(relativeTime);
	provide('dayjs', dayjs);
});
```

~/plugins/hello.ts
```
import { defineNuxtPlugin } from '#app';

declare module '#app' {
	interface NuxtApp {
		$hello (msg: string): string | boolean;
	}
}
declare module '@vue/runtime-core' {
	interface ComponentCustomProperties {
		$hello (msg: string): string;
	}
}

export default defineNuxtPlugin(({ provide }) => {
	const hello = (msg: string) => `Hello ${msg}!`;
	provide('hello', hello);
});
```

Interestingly, if in `~/.nuxt/types/plugins.d.ts` I break the path to the `$dayjs` plugin, the type for `$hello` plugin starts working. It looks like only one type can work at a time 🤔.

**Comment by xiaoxiangmoe** [comment]
Can you give me a minimal reproduction？

**Comment by szulcus** [comment]
> Can you give me a minimal reproduction？

I abandoned Nuxt 3 because, as it turned out, the package with the components written in Vue 2 was not compatible, but I will try to upload a reproduction today.

**Comment by szulcus** [comment]
Ready! :)
[Nuxt 3 useNuxtApp() reproduction.zip](https://github.com/johnsoncodehk/volar/files/9480112/Nuxt.3.useNuxtApp.reproduction.zip)

As you can see `$hello2` works fine,` $hello1` is of type `any`
![image](https://user-images.githubusercontent.com/48328739/188210474-28c7eda6-5e09-4455-9252-91ce4536f816.png)
in command line:
```console
yarn
yarn dev
```

**Comment by johnsoncodehk** [comment]
This is TS behavior, but I don't know why. 👀 I think you should search in TS issues for it.

<img width="662" alt="螢幕截圖 2022-09-22 16 35 07" src="https://user-images.githubusercontent.com/16279759/191699218-fa65c0ba-7a90-440c-8837-fbd5d82aaf2b.png">
<img width="698" alt="螢幕截圖 2022-09-22 16 35 41" src="https://user-images.githubusercontent.com/16279759/191699361-b54624a0-bfcb-4129-9679-a1c82efa5b50.png">
