### ISSUE TITLE
Latest version 0.40.4 breaks SFC script parsing

### ISSUE THREAD

**Issue by cmcnicholas** [johnsoncodehk/volar#1786]
After being automatically upgraded to `0.40.4` all my SFC's break with the following error:

`Virtual Script Not Found`

![image](https://user-images.githubusercontent.com/41394833/187232141-158be254-7773-48a6-b355-5456ad564dde.png)

If I look at the output for the plugin I see:

![image](https://user-images.githubusercontent.com/41394833/187232264-ebd1d27b-0ffc-429a-a77b-1d3316c15a30.png)

Reverting to version 0.40.1 and everything is working as expected.

**Comment by WORMSS** [comment]
I am not seeing the exact same error, but waking up this morning to find Volar has updated to 0.40.4 and I am getting this repeatedly: 
![image](https://user-images.githubusercontent.com/1384537/187373617-5a71d746-2399-4543-9f63-f0b42fb4ea4a.png)
Unsure if it's related to what OP is seeing but it seems such a coincidence. 

Running Volar in takeover mode in a multi-project monorepo.
