### ISSUE TITLE
Type narrowing not working in templates with union types

### ISSUE THREAD

**Issue by austin-agronick** [johnsoncodehk/volar#1788]
v-if is not narrowing union types.
```
<template>
  <span v-if="user.id">({{ user.id }})</span>
</template>

<script setup lang="ts">
type User = {
  id: number
  email: string
}

let user: string | User
</script>
```
`Property 'id' does not exist on type 'string | User'`

See [demo on stackblitz here](https://stackblitz.com/edit/vue3-typescript-vue-cli-starter-jf14mc?file=tsconfig.json,src%2Fcomponents%2FHelloWorld.vue).

**Comment by LinusBorg** [comment]
That's just how TS works here, here's the same code on TS playground, raising the same errors:

https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gKClAlgEwC4oA7AVwFsAjJbKCCgQ1wBti5hFcSBzTAX0yYWEYFDIJE7Ttx5QAPrEmoMeIlADkBDVEGZcAMygAKCUgB0BAJQY6AYwD2JOA5HmWDnqcmX8VgUA

This, however, would work:

```ts
type User = {
  id: number
  email: string
}

let user: string | User = { id: 'id' }

if (isObj(user)) {
  console.log(user.id)
}

function isObj(obj: any): obj is Record<string, any> {
  return typeof obj === 'object'
}
```

https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gKClAlgEwC4oA7AVwFsAjJbKCCgQ1wBti5hFcSBzTAX0yYWEYFDIJE7Ttx5QAPrEmoMeIlADkBDVEGZcAMygAKXHADyVAFbGJSAJT2MdAMYB7EnDciAdCzc8tpI+BPYCQgZkJC7AuB54FtbGbtbEjCQg9sQpVglQAEoQ7oj4ADwcXLwANFDpIAB8zjiIomSIJFCgkG5GOagoaBo5RcAaAkA

**Comment by johnsoncodehk** [comment]
Try `typeof user === 'object'` or `'id' in user`.
