### ISSUE TITLE
Different behavior in normal script and script setup while using namespace

### ISSUE THREAD

**Issue by Edge00** [johnsoncodehk/volar#179]
import a namespace works well in normal script. throws error in script setup

### works well in normal script
![image](https://user-images.githubusercontent.com/23715779/118085446-02302080-b3f5-11eb-9129-4b0b4669a1ab.png)
###  throws error in script setup
![image](https://user-images.githubusercontent.com/23715779/118085194-8d5ce680-b3f4-11eb-81bf-b0f00396be21.png)

**Comment by sheremet-va** [comment]
I read somewhere, that you have to use `import type` when importing types inside `script setup`. I think it's esbuild problem. But unfortunately Volar doesn't do that automatically.

**Comment by Edge00** [comment]
Thank you! `import type` solved this problem. i found this [iuuse](https://github.com/vuejs/vue-next/issues/3183)
BTW. i am using babel and there is no error in build process.

**Comment by johnsoncodehk** [comment]
> Thank you! `import type` solved this problem. i found this [issue](https://github.com/vuejs/vue-next/issues/3183)
> BTW. I am using babel and there is no error in build process.

It should throw error in runtime.

**Comment by Edge00** [comment]
> It should throw error in runtime.

@johnsoncodehk  In my scenario runtime works well also. Only editor error.

**Comment by johnsoncodehk** [comment]
Sorry for not noticing that this is namespace, it should be working, could you provide a repro case?
