### ISSUE TITLE
When formatting code with volar, can I choose not to wrap line?

### ISSUE THREAD

**Issue by lsdt45** [johnsoncodehk/volar#1792]
When formatting code with volar, "{" will be wrapped line in options "methods",
e.g.
**before format**:
add(x, y) {
 ...
}
**after format**:
add(x, y) 
{
  ...
}

Can I choose not to wrap line?

volar version:0.40.4

**Comment by LinusBorg** [comment]
Volar doesn't do any formatting.

**Comment by johnsoncodehk** [comment]
@LinusBorg Actually we do. 👀

@lsdt45 You should disalbe `typescript.format.placeOpenBraceOnNewLineForFunctions` in VSCode.

**Comment by lsdt45** [comment]
> @LinusBorg Actually we do. 👀
> 
> @lsdt45 You should disalbe `typescript.format.placeOpenBraceOnNewLineForFunctions` in VSCode.

Problem was solved. Thank you for support.
