### ISSUE TITLE
Please add a CHANGELOG file

### ISSUE THREAD

**Issue by eladcandroid** [johnsoncodehk/volar#18]

**Comment by johnsoncodehk** [comment]
Now the version is updated almost daily... I will check how to process documents efficiently.
But is it really necessary?:sweat_smile: currently has very few users, and I think there are almost no users who watch CHANGELOG.

**Comment by soulsam480** [comment]
> _No description provided._

Hey I think in the readme, there is some info about the features with ref to their versions! It's not much but manageable for a fast-moving project!

**Comment by johnsoncodehk** [comment]
We have a CHANGELOG now!

I will add the old version changes when I have time. (also welcome pr for that. XD)
