### ISSUE TITLE
Event handler with modifier and no callback doesn't typecheck

### ISSUE THREAD

**Issue by henribru** [johnsoncodehk/volar#180]
If you do e.g. `@keydown.space.prevent` (notice the lack of `="someCallback"`), you get this error `Type 'undefined' is not assignable to type '((...payload: unknown[]) => void) | ((...args: any) => void)'`. Having an event handler that only has a modifier and no callback is legal and useful, so it shouldn't give an error.

**Comment by johnsoncodehk** [comment]
`@keydown.space.prevent` do not report error for me, please provide a repro case.

<img width="270" alt="螢幕截圖 2021-05-14 上午12 41 15" src="https://user-images.githubusercontent.com/16279759/118157410-1b64bb80-b44d-11eb-9f0a-0e66c4c8ea10.png">

**Comment by henribru** [comment]
Seems like it happens on Vue components but not native HTML elements: https://github.com/henribru/volar-event-handler-repo

**Comment by johnsoncodehk** [comment]
Fixed in 0.25.5.
