### ISSUE TITLE
语法全部提示红色波浪线

### ISSUE THREAD

**Issue by DreamapleHT** [johnsoncodehk/volar#1800]
![image](https://user-images.githubusercontent.com/23546866/187920669-cb41da71-9c01-40e4-9dca-50277f4318ac.png)
![image](https://user-images.githubusercontent.com/23546866/187920729-b3c119c8-2ce3-4537-a630-224cd6c7185f.png)

**Comment by xiaoxiangmoe** [comment]
Can you provide me a minimal reproducible example?

**Comment by DreamapleHT** [comment]
好像是这个语法的识别问题，您看看呢，这就是一个vue3+ts+vant的项目


1036243868
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnsoncodehk/volar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnsoncodehk/volar] 语法全部提示红色波浪线 (Issue #1800)





 
Can you provide me a minimal reproducible example?

**Comment by DreamapleHT** [comment]
![image](https://user-images.githubusercontent.com/23546866/187931081-268b1742-2d97-489b-a1ad-4fa7b8a7cdfa.png)
我把上面的这行代码删除，页面就正常了

**Comment by xiaoxiangmoe** [comment]
duplicate of #1706
