### ISSUE TITLE
stop formatting <router-link> on multiple lines

### ISSUE THREAD

**Issue by mariusa** [johnsoncodehk/volar#1802]
Hi,

When making a link with
```
<router-link to="/support">help</router-link>
```

using vscode & Volar, on save it changes to
```
<router-link to="/support">
               help
            </router-link>
```

which results in rendering with an extra space underlined ("help_" instead of "help")

How to fix this, please?

Thanks!

**Comment by cuebit** [comment]
Volar doesn’t format code. Are you using eslint or alike?

**Comment by mariusa** [comment]
> Volar doesn’t format code.

Thanks for confirmation. 
Yes, eslint. I'll look into it. Have a good day!

**Comment by mariusa** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/1749

**Comment by johnsoncodehk** [comment]
> Volar doesn’t format code. Are you using eslint or alike?

We do. 😅

@mariusa You can also try https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettyhtml

**Comment by mariusa** [comment]
Thanks, but no, vscode is good enough :D
