### ISSUE TITLE
<script setup> in Vue 2 (Nuxt)

### ISSUE THREAD

**Issue by szulcus** [johnsoncodehk/volar#1803]
Could it be that `<script setup>` doesn't work with Vue 2? I have migrated a project from Nuxt 2 to Nuxt Bridge (https://v3.nuxtjs.org/bridge/overview/) and I cannot access the data in <template>:
![image](https://user-images.githubusercontent.com/48328739/188115675-0923eb56-2945-400a-b456-ec93ee960688.png)
Composition api with standard `<script>` tag and Options API works fine.:
![image](https://user-images.githubusercontent.com/48328739/188116808-5ed25c25-2811-4478-9b4f-925b5e58f771.png)

**Comment by szulcus** [comment]
Sorry, I didn't set `vueCompilerOptions.experimentalCompatMode` in my tsconfig.json file (https://github.com/antfu/unplugin-vue2-script-setup#support-vue-2-template). Now everything works fine :)

**Comment by johnsoncodehk** [comment]
Please note that `experimentalCompatMode` is renamed to `target` in v0.37.0. https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0370-202266

**Comment by szulcus** [comment]
> Please note that `experimentalCompatMode` is renamed to `target` in v0.37.0. https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0370-202266

After renaming to target, it works as above 🤷‍♂️ (Nuxt 2 with Bridge)
