### ISSUE TITLE
Support custom delimiters for petite-vue

### ISSUE THREAD

**Issue by ivanjeremic** [johnsoncodehk/volar#1804]
petite-vue same as vue has the option to set custom delimiters, `${var}` is a common one but still not supported in HTML for petite-vue or other in HTML solutions. Would be awesome to have it work out of the box just like `{{var}}`

**Comment by johnsoncodehk** [comment]
You can use `resolveTemplateCompilerOptions` from plugin API, see #1991.

**Comment by ivanjeremic** [comment]
It is unclear to me where to find `resolveTemplateCompilerOptions` should I put this in the vscode/settings.json or does it belong to a special config file?

**Comment by johnsoncodehk** [comment]
It don't have documatation for now, but you can reference https://github.com/sxzz/unplugin-vue-macros/blob/37fa0cda384e0df51b8c869d3ffc67bac4972230/packages/volar/src/short-vmodel.ts.

And it should add to tsconfig:

```json
{
  "vueCompilerOptions": {
    "plugins": ["./your-plugin.js"]
  }
}
```
