### ISSUE TITLE
Add settings to allow initial indentation for script and style

### ISSUE THREAD

**Issue by jez9999** [johnsoncodehk/volar#1806]
Volar uses the VS Code settings for indentation of code, but it doesn't put an initial indent in for the `script` or `style` tags in `vue` files.  Could you add in a couple of settings that allows us to have that indent?  I know the Vue default style may not have it, but to my eyes it looks horrible having opening and close tags with no indent.  I'd like to have the indent option for auto-formatting.

**Comment by cabal95** [comment]
We are running into this as well. To my personal aesthetics I also prefer the script tag to be indented - though I could live with it. The problem for us is we use a mixed environment of C# and TS/Vue code. Some of those C# bits are WebForms and other languages/frameworks that aren't supported in VS Code (more specifically, easily running them is not supported).

As a result, we have a mix of users on VS2022 and VS Code. The issue is that VS2022 indents the script tag in the .vue files since it just sees it as an XML/HTML file and that is the standard formatting it does. I looked and could not find a setting to change this. So when people auto format the document on VS 2022, it adds the 4 character indentation inside the script tag. But then when people auto-format in VS Code, it removes the 4 character indentation.

So it would be nice to be able to configure Volar to add/keep the indentation so it matches - or at least is a very close match.

**Comment by jez9999** [comment]
I notice that Vetur had two options, `vetur.format.scriptInitialIndent` and `vetur.format.styleInitialIndent`, so this is actually a regression from Vetur. 😢

**Comment by johnsoncodehk** [comment]
@jez9999 You can add a new VSCode setting and fetch and use it in at https://github.com/johnsoncodehk/volar/blob/2758510a8e519563f16ce023c700ab98b8b65ad8/packages/vue-language-service/src/plugins/typescript.ts#L246-L252.

**Comment by jez9999** [comment]
@johnsoncodehk Right but how do you debug the formatting code?  When I open the Volar project and hit F5, it opens a new VS Code window, but inside that window there is no Volar code formatter configured for .vue files.

**Comment by johnsoncodehk** [comment]
@jez9999 You need to open an other workspace such as github.com/johnsoncodehk/volar-starter to the new VSCode window.

**Comment by jez9999** [comment]
@johnsoncodehk That appears to work but I now have a new problem; it doesn't appear to be changing indentation *at all* for `script` contents when I format a document.  I could've sworn it was doing so yesterday!  I'm not sure what's changed.  See the GIF screencap.

![capture](https://user-images.githubusercontent.com/793830/188325218-2243ca53-7270-42b7-9e3a-da6c22c45830.gif)

**Comment by jez9999** [comment]
Also, no breakpoints are binding in `typescript.ts`.  Is there a build step I need to go through first for debugging?

**Comment by jez9999** [comment]
PR submitted.

**Comment by jez9999** [comment]
@johnsoncodehk Thanks for merging!  However, I think your refactor means that "Format Selection" will reformat an entire section of a .vue file if *any* of that section is selected, rather than just formatting the code within the selected range.  What I tried to do was only format the code in the selected range.  This is admittedly pretty difficult for style and JSON, but at least with Typescript/Javascript you might want to go back to the method I used of passing the indent through to `onRange` in `packages/vue-language-service/src/plugins/typescript.ts`, which then sets `tsOptions.baseIndentSize` - this is actually built into the TS formatter, so can reliably change base indent just for the selected range without reformatting the entire script section.

**Comment by jez9999** [comment]
It's also causing the entire `<template>` section to get reformatted rather than just the selected section.  Presumably this can be fixed just be returning the `<template>` formatting to the previous behaviour when `"html": true` is set.

**Comment by jez9999** [comment]
Another idea that might work in a more general sense is to have an algorithm like:

- Send document and range to parser
- If no edits and baseIndent is true, apply base indent (parser thinks code is OK, meaning it doesn't have the base indent)
- If edits exist, for each edit:
  - Replace \n in edit with \n${baseIndentCharacters}
  - If range begins at the start of a line, prefix baseIndentCharacters
  - Apply edit

**Comment by michaeldaw** [comment]
The new setting "volar.format.initialIndent" seems to be ignored. The default is for only HTML to have the initial indent, but in my experience, the initial indent is applied everywhere (in script setup files, at least), whether they are set to 'false' or not.

Additionally, this new feature seems to add the initial indent not just at the beginning of the script tag, but after new lines in the interior of the script tag code. I'm afraid it's become somewhat frustrating for me and I've had to revert back to 0.40.1 to restore the original functionality.

I've tried explicitly setting each language to false in the setting, but it still adds the initial indent in each section of the script setup file.

This behavior starts in 0.40.2.

Given that it changes the original functionality, I don't think this feature should be implemented without the ability to turn it off.

![code](https://user-images.githubusercontent.com/8949148/189197039-57e4be8a-b99f-4629-8402-0af523e56143.gif)

**Comment by jez9999** [comment]
Odd, I'm running 0.40.13 and this config gets rid of all the indentation:

```
"volar.format.initialIndent": {
        "html": false,
        "typescript": false,
        "javascript": false,
        "typescriptreact": false,
        "javascriptreact": false,
        "css": false,
        "scss": false,
        "json": false,
        "jsonc": false,
    }
```

**Comment by jez9999** [comment]
I think if you select all and format selection it will remove the indentation.  The specific bug seems to be the indentation given when you hit Enter, which does seem to give indentation if these are set to false.  Perhaps worth opening an issue on that specific behaviour?
