### ISSUE TITLE
No typecheck of .vue file properties when imported into a .tsx (JSX) file.

### ISSUE THREAD

**Issue by xaviergonz** [johnsoncodehk/volar#181]
Given the default vite vue typescript template, if we change the app file to an app.tsx:

```ts
import { defineComponent, ref } from "vue";
import HelloWorld from "./components/HelloWorld.vue";
import {HelloWorldJSX } from "./HelloWorldJSX " // another jsx component

export const App = defineComponent({
  components: {
    HelloWorld,
  },
  setup() {
    return () => (
      <>
        <img alt="Vue logo" src="./assets/logo.png" />
        <HelloWorldJSX wrongProp="Hello Vue 3 + TypeScript + Vite" /> <!-- will error :D -->
        <HelloWorld wrongProp="Hello Vue 3 + TypeScript + Vite" /> <!-- won't error :( -->
      </>
    );
  },
});
```

It seems as if properties from other TSX files are imported ok, but those from .vue files are not.

**Comment by johnsoncodehk** [comment]
It's should works, have you enabled TS plugin?

**Comment by xaviergonz** [comment]
yes I have

**Comment by johnsoncodehk** [comment]
Please provide a repro case by https://github.com/johnsoncodehk/volar-starter.

**Comment by xaviergonz** [comment]
Apparently I did something wrong before, because after cloning the template and making the same changes it now seems to work. Closing the issue. Sorry to waste your time!
