### ISSUE TITLE
Uniquely scope attribute shorthands

### ISSUE THREAD

**Issue by roydukkey** [johnsoncodehk/volar#1812]
As a theme developer, I would like the shorthands for `v-bind`, `v-on`, `v-slot` to be uniquely scoped so they can be targeted in themes.

I proposed that we replace the `punctuation.separator.key-value.html.vue` scope from each of the following shorthands with...

1. `punctuation.attribute-shorthand.bind.html.vue` for `:`
2. `punctuation.attribute-shorthand.event.html.vue` for `@`
3. `punctuation.attribute-shorthand.slot.html.vue` for `#`

Let me know if you'll accept a PR.

**Comment by johnsoncodehk** [comment]
Of course, PR is welcome!

**Comment by roydukkey** [comment]
Closes by #1830
