### ISSUE TITLE
Can't format JavaScript in .vue

### ISSUE THREAD

**Issue by agoudbg** [johnsoncodehk/volar#1813]
Format works for template HTML but not work for JavaScript in <script>

VSCode 1.71, Volar 0.40.6

https://user-images.githubusercontent.com/55237525/188307411-6a0b0da5-12b8-4af0-af07-c8582ef09088.mp4

**Comment by cloydlau** [comment]
Hi! I'm currently on `v0.40.13` but this is still happening for me.

**Comment by johnsoncodehk** [comment]
@cloydlau please open an new issue and describe how to reproduce.
