### ISSUE TITLE
volar keeps crashing and vscode disables the extension after a time

### ISSUE THREAD

**Issue by clever-rob** [johnsoncodehk/volar#1816]
<--- Last few GCs --->

[2181:0x4c71990]  1857604 ms: Scavenge 2043.7 (2083.3) -> 2042.4 (2087.6) MB, 3.8 / 0.0 ms  (average mu = 0.814, current mu = 0.315) allocation failure 
[2181:0x4c71990]  1858205 ms: Mark-sweep (reduce) 2046.0 (2087.6) -> 2045.5 (2084.1) MB, 261.6 / 0.0 ms  (+ 214.6 ms in 56 steps since start of marking, biggest step 5.2 ms, walltime since start of marking 495 ms) (average mu = 0.702, current mu = 0.263) 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 5: 0xeaf465  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 6: 0xebf12d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 7: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 8: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 9: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
10: 0x15f0b19  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
[Info  - 10:04:35 AM] Connection to server got closed. Server will restart.

<--- Last few GCs --->

[2639:0x5c62990]    30750 ms: Scavenge (reduce) 2044.3 (2082.2) -> 2043.8 (2082.7) MB, 4.6 / 0.0 ms  (average mu = 0.108, current mu = 0.004) allocation failure 
[2639:0x5c62990]    30890 ms: Scavenge (reduce) 2044.6 (2082.7) -> 2044.0 (2082.7) MB, 5.0 / 0.0 ms  (average mu = 0.108, current mu = 0.004) allocation failure 
[2639:0x5c62990]    31009 ms: Scavenge (reduce) 2044.7 (2082.7) -> 2044.2 (2082.9) MB, 5.4 / 0.0 ms  (average mu = 0.108, current mu = 0.004) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 5: 0xeaf465  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 6: 0xeaff46  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 7: 0xebe46e  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 8: 0xebeeb0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 9: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
10: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
11: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
12: 0x15f0b19  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
[Info  - 10:05:06 AM] Connection to server got closed. Server will restart.

<--- Last few GCs --->

[2656:0x54cb990]    31764 ms: Mark-sweep (reduce) 2046.3 (2083.6) -> 2045.5 (2083.9) MB, 922.1 / 0.0 ms  (average mu = 0.088, current mu = 0.011) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 5: 0xeaf465  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 6: 0xebf12d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 7: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 8: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 9: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
10: 0x15f0b19  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
[Info  - 10:05:38 AM] Connection to server got closed. Server will restart.

<--- Last few GCs --->

[2665:0x4f80990]    57680 ms: Mark-sweep (reduce) 2042.9 (2081.8) -> 2042.7 (2082.1) MB, 19.1 / 0.0 ms  (+ 823.7 ms in 101 steps since start of marking, biggest step 17.7 ms, walltime since start of marking 946 ms) (average mu = 0.218, current mu = 0.289)[2665:0x4f80990]    57689 ms: Scavenge 2043.7 (2082.1) -> 2043.0 (2085.1) MB, 4.3 / 0.0 ms  (average mu = 0.218, current mu = 0.289) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 5: 0xeaf465  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 6: 0xeaff46  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 7: 0xebe46e  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 8: 0xebeeb0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 9: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
10: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
11: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
12: 0x15f0b19  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
[Info  - 10:06:37 AM] Connection to server got closed. Server will restart.

<--- Last few GCs --->

[2712:0x55da990]    35147 ms: Scavenge 2043.5 (2083.6) -> 2042.3 (2087.9) MB, 4.5 / 0.0 ms  (average mu = 0.373, current mu = 0.335) allocation failure 
[2712:0x55da990]    36011 ms: Mark-sweep (reduce) 2045.8 (2087.9) -> 2045.2 (2084.4) MB, 478.8 / 0.0 ms  (+ 205.2 ms in 55 steps since start of marking, biggest step 6.2 ms, walltime since start of marking 710 ms) (average mu = 0.318, current mu = 0.258) 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 5: 0xeaf465  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 6: 0xebf12d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 7: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 8: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
 9: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
10: 0x15f0b19  [/home/robert/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node]
[Error - 10:07:13 AM] The Volar - Language Features Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by johnsoncodehk** [comment]
Could you try can this problem avoid by config `"volar.vueserver.maxOldSpaceSize": 4000` in VSCode setting?

**Comment by TAUnionOtto** [comment]
> Could you try can this problem avoid by config `"volar.vueserver.maxOldSpaceSize": 4000` in VSCode setting?

Same question，and `"volar.vueserver.maxOldSpaceSize": 4000` fixed it for me, thanks 👍

**Comment by tom-evaristo** [comment]
I'm not really sure what just happened,

I kept increasing the size upto `8000`  for the config  `volar.vueserver.maxOldSpaceSize`
and it still crashes.

reloaded the window and restarted VSCODE, still it crashes, 
I see to it that the config is also synced on the user and workspace. 
Still it crashes

until i added the 

tsconfig.json file

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "allowJs": true,
    "lib": ["esnext", "dom"],
    "types": [
      "vite/client",
      "vite-plugin-vue-component-preview/client"
    ]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}
```
the error went away,

I'm not 100% sure that this is the fix, but I'm not going to spoil it for now. 
This has been bugging me for a month and can't use the autocomplete functionality

**Comment by harrikauhanen** [comment]
Please note that the `volar.vueserver.maxOldSpaceSize` no longer exists. 

This seems to be the correct setting:

```
vue.server.maxOldSpaceSize: 4096
```
