### ISSUE TITLE
After 4.0 +, the introduction of pug components and variables are all wave lines

### ISSUE THREAD

**Issue by brighthxl** [johnsoncodehk/volar#1817]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/7731281/188356512-8aaf8dd8-ccec-49e6-a55d-dd6e88546f5d.png">
``

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, could you provide repro case?

**Comment by lorefnon** [comment]
@brighthxl Have you configured the the vue-language-plugin-pug dev-dependency ? 

```
npm i -D @volar/vue-language-plugin-pug
```
In tsconfig.json

```
  "vueCompilerOptions": {
    "plugins": [
      "@volar/vue-language-plugin-pug"
    ]
  }
```

That is needed for pug specific features
