### ISSUE TITLE
Volar 完成列表对接

### ISSUE THREAD

**Issue by spf-oss** [johnsoncodehk/volar#1818]
客户端在对接Completion 功能时候，首先会在第一个字母输入时候弹出列表，然后在后面的输入过程中不会再次进行请求，但是我回车的时候需要拿到最新的`TextEdit`数据，请问这个部分应该怎么对接。

比如：我输入doc选中document回车这个过程，首先在输入'd'时候请求数据，输入'o'和'c'不会再次请求数据，但是回车的时候我需要最新的基于'doc'的“TextEdit”替换数据，我应该怎样去做？

**Comment by spf-oss** [comment]
还是说当完成列表打开的时候需要保存好当前的文本内容，而不是继续更新。

**Comment by johnsoncodehk** [comment]
你應該用[Completion Item Resolve Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem_resolve)來請求準確的TextEdit.

**Comment by spf-oss** [comment]
是的，但是从场景出发，我输入"d"时候请求的数据中，TextEdit是基于我输入'd'时候生成的，但是当我接着输入'o'和'c'两个字母之后使用 `CompletionItem/Resolve`请求，请求的参数是我输入第一个字母'd'时候获取的CompletionItem，这时候返回的`TextEdit`数据并不是基于'doc'这三个字母生成的数据，而是基于输入'd'时候的数据，请问我应该再客户端自己处理还是说再语法服务器上设置什么属性。

**Comment by johnsoncodehk** [comment]
`completionItem/resolve`不需要得知當前輸入，只需要知道你請求完成列表中哪一個項目，不論你輸入'd'還是'doc'，`completionItem/resolve`要求的參數和回傳結果都是一樣的。你應該根據完成列表的當前selection去發送請求，比如輸入'd'時selection時'document'的完成項，就立即對'document'請求`completionItem/resolve`，輸入'doc'時selection仍然是'document'則重用先前的`completionItem/resolve`結果即可。

**Comment by spf-oss** [comment]
假设我在第0行第0列输入'd',这个时候获取到一个'CompletionItem',并立即请求`completionItem/resolve`，此时'TextEdit'的数据是将（0，0）到（0，1）位置替换为'document'，但是此时我输入'o'和'c'，我希望能够获取到将'doc'三个字母替换成'document'的'TextEdit'数据，但是这个时候我去请求`completionItem/resolve`获取的还是从(0,0)到(0,1)，而不是(0,0)到(0,3)的替换数据，请问是要我在编辑器客户端自己处理这一现象吗？

**Comment by johnsoncodehk** [comment]
如果啟用`"volar-language-features.trace.server": "verbose"`，可以看到VSCode不管你輸入到第幾個字，都統一按你第一次觸發完成列表時的狀態處理resolve，TextEdit統一是（0，0）到（0，1）的結果，我猜VSCode的做法是比較最終回車時文本對比觸發完成列表時文本的更改範圍，將更改範圍合併到TextEdit處理。

這部份各IDE處理方法可能不同，language server不需要處理這個邏輯只能猜測，你問問某IDE client的維護者比較好。

**Comment by spf-oss** [comment]
谢谢！！
