### ISSUE TITLE
Is volar Spanish or French?

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#182]
Tried google translation, Spanish volar means "fly", French volar means "palm". I guess it's Spanish then?

**Comment by johnsoncodehk** [comment]
Yes Volar mean "fly" for this plugin, but this name from [a song](https://youtu.be/67a_sfCeZW8) name, and the song name is from a nightclub name, I'm also not sure what the original name mean. 😅

**Comment by wenfangdu** [comment]
Thanks!
