### ISSUE TITLE
input: JSX elements cannot have multiple attributes with the same name.

### ISSUE THREAD

**Issue by Fuzzyma** [johnsoncodehk/volar#1821]
The recent update made my build crash. The Error is:

>ts(17001): JSX elements cannot have multiple attributes with the same name.

It's an input whose type is either "radio" or "checkbox" with a v-model and a value. Obviously, those 2 are allowed for these types.
Only for other inputs, it would be a duplication

```
<input type="myType" v-model="foo" :value="bar" />

defineProps({
  myType: {
    type: String as PropType<'radio' | 'checkbox'>
  }
}
```

Volar seems to handle this case as a regular input even tho the type of type (haha) is radio or checkbox.

# Possible Solution

If you know that your input is a checkbox or radiobox, dont use v-model.
Instead use `:checked="foo"` and `@change="foo = $event.target.checked"`

That will solve the duplication because volar seems  to handle v-model as :value instead of :checked.

**Comment by xmatthias** [comment]
Unfortunately, this issue seems to persist - and is also still happening on 0.40.10.

**Comment by hanskusters** [comment]
last version that does not give this error in my project is `v0.40.1`

**Comment by xmatthias** [comment]
Seems to be still problematic in `v0.40.13`

**Comment by hfhchan** [comment]
This also happens when using `<b-form-checkbox>` instead of `<input type=checkbox>`.

**Comment by johnsoncodehk** [comment]
We have added new `experimentalModelPropName` setting in https://github.com/johnsoncodehk/volar/commit/5cad688875e76330c34e066920eca38d37281d84 so you can customize it.

**Comment by Fuzzyma** [comment]
@johnsoncodehk your fix seems to be vue 2 related. I am not sure how this solves the issue. I just updated volar and the configuration setting doesnt seem to exist. I wouldnt know what to put there anyway to solve the issue.

Can you elaborate?

**Comment by Fuzzyma** [comment]
@johnsoncodehk thx, and how do I use it? I cannot find any documnentation and intellisense is not helping me

**Comment by xmatthias** [comment]
in my case, the following worked.
```
 "experimentalModelPropName": {
      "": {
        "b-form-radio": true
      },
    }
```

for your case - i think the following should work 

```
 "experimentalModelPropName": {
      "": {
        "input": {"type": "myType"}
      },
    }
```

**Comment by johnsoncodehk** [comment]
@Fuzzyma look to your code I guess `type` is dynamic, you can try this hack way:

```
<input :type="myType" v-model="foo" :value="bar" hack-ignore-vmodel=""  />

defineProps({
  myType: {
    type: String as PropType<'radio' | 'checkbox'>
  }
}
```

```
 "experimentalModelPropName": {
      "": {
        "input": {"hack-ignore-vmodel": ""}
      },
    }
```

**Comment by Fuzzyma** [comment]
@johnsoncodehk the error goes away if i just write this:

```
  "vueCompilerOptions": {
    "experimentalModelPropName": {
      
    },
  },
```

But i assume thats because I overwrite the defaults.
If I add the defaults however, I dont know how to add your hack:

```
  "vueCompilerOptions": {
    "experimentalModelPropName": {
      "": {
        "input": { "type": "radio", "hack-ignore-vmodel": "" }
      },
      "checked": {
        "input": { "type": "checkbox" }
      },
      "value": {
        "input": true,
        "textarea": true,
        "select": true
      }
    },
  },
```

The above does not work. How can I add multtiple optiosn for the "ignore" case?

**Comment by johnsoncodehk** [comment]
> The above does not work. How can I add multtiple optiosn for the "ignore" case?

You can't, this is design mistake of `experimentalModelPropName`, I will check how update `experimentalModelPropName` for this case. (Please let me know if you has idea)

**Comment by Fuzzyma** [comment]
We could simply allow passing an array:

```
  "vueCompilerOptions": {
    "experimentalModelPropName": {
      "": {
        "input": [
          { "type": "radio" },
          { "hack-ignore-vmodel": "" }
        ]
      },
      "checked": {
        "input": { "type": "checkbox" }
      },
      "value": {
        "input": true,
        "textarea": true,
        "select": true
      }
    },
  },
```

**Comment by johnsoncodehk** [comment]
@Fuzzyma please try v1.0.7

**Comment by Fuzzyma** [comment]
It works like  a charm @johnsoncodehk . Thank you very much!

I also found out that you can use `{ "hack-ignore-vmodel": null }` and then just use a standalone attribute in the template like `<input hack-ignpre-v-model type="myType" ...>`

**Comment by johnsoncodehk** [comment]
> I also found out that you can use `{ "hack-ignore-vmodel": null }` and then just use a standalone attribute in the template like `<input hack-ignpre-v-model type="myType" ...>`

Good to know. :)

> I cannot find any documnentation and intellisense is not helping me

If anyone wants to add documentation for it PR is much appreciated. (I plan to do but not these days)

**Comment by Fuzzyma** [comment]
> > I also found out that you can use `{ "hack-ignore-vmodel": null }` and then just use a standalone attribute in the template like `<input hack-ignpre-v-model type="myType" ...>`
> 
> Good to know. :)

I might be wrong on this one. When I opened vs-code later, it showed as wrong again so maybe my types just didnt update properly :D

**Comment by johnsoncodehk** [comment]
@Fuzzyma you can use `Show Virtual Files` to inspect for this.

**Comment by Fuzzyma** [comment]
> @Fuzzyma you can use `Show Virtual Files` command to inspect for this.

Wow - I INSTANTLY found the issue when using this. In the virtual file, standalone attributes have the value `(true)`. Unfortunetaly, using "true" instead of "null" didnt work either. Maybe because it is treated as a special value? I dont know. The empty string works and is fine for now

**Comment by hfhchan** [comment]
After setting the tsconfig.json it seems it doesn't work with Bootstrap Vue. Using "Show Virtual Files" shows that the `b-form-checkbox` is still being compiled incorrectly:

```
let __VLS_54!: import('./__VLS_types.js').ComponentProps<typeof BFormCheckbox>;
__VLS_54 = { value: ((__VLS_ctx.selectedRows)), value: ((data.item)),  };
[selectedRows,];
```

I am using the following configuration:

```
"experimentalModelPropName": {
      "type": "object",
      "default": {
        "": {
          "input": { "type": "radio" },
          "b-form-radio": true,
          "BFormRadio": true
        },
        "checked": {
          "input": { "type": "checkbox" },
          "b-form-checkbox": true,
          "BFormCheckbox": true
        },
        "value": {
          "input": true,
          "textarea": true,
          "select": true
        }
      }
    }
```

**Comment by hfhchan** [comment]
For anyone using BootstrapVue, the following reference is provided. In `tsconfig.json`, add the following code into `"vueCompilerOptions"`:

```
    "experimentalModelPropName": {
      "": {
        "input": { "type": "radio" },
        "b-form-radio": true
      },
      "checked": {
        "input": { "type": "checkbox" },
        "b-form-checkbox": true
      },
      "value": {
        "input": true,
        "textarea": true,
        "select": true
      }
    }
```

**Comment by last-partizan** [comment]
I cannot get this to work with `vue@2.7.14` and `vue-tsc@1.1.5`.

Here's my minimal reproduction:
https://github.com/last-partizan/vue-examples/tree/1f960defcec69d0154176d4cf8c170b498e31410

Any ideas?

**Comment by last-partizan** [comment]
Found my problem, this setting is sensitive to component name casing, i needet to add `BFormCheckbox` and `BFormRadio` to suggested config.
