### ISSUE TITLE
代码缩进无了

### ISSUE THREAD

**Issue by VirensCn** [johnsoncodehk/volar#1823]
如图，格式化就导致没有缩进了，版本：40.8，ts+setup
![image](https://user-images.githubusercontent.com/9736815/188527424-22263de8-bd20-4d7d-82c2-e6835d64b971.png)

**Comment by ZacFengY** [comment]
应该是遇到了三分钟加载失败五次的问题，我也缩进无了

**Comment by joy-Pai** [comment]
+1 我下了旧版本  
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.40.7/vspackage?targetPlatform=win32-x64
