### ISSUE TITLE
Incorrect formatting and no highlighting

### ISSUE THREAD

**Issue by talaxasy** [johnsoncodehk/volar#1824]
How to make Volar correctly format postcss syntax and highlight it?
![image](https://user-images.githubusercontent.com/25802675/188527729-4201a3e8-b154-475e-8139-e996e0879f6d.png)

**Comment by talaxasy** [comment]
OK, I installed a Prettier extension for VScode and it normalized the formatting, but the Highlight problem remains.

**Comment by johnsoncodehk** [comment]
You need to install [language-postcss](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss), see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#notes.

For postcss formatting, you can use https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettier.

**Comment by talaxasy** [comment]
> You need to install [language-postcss](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss), see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#notes.
> 
> For postcss formatting, you can use https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettier.

Okay with formatting, what about highlighting?

**Comment by johnsoncodehk** [comment]
You need to install [language-postcss](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss) for highlighting.

**Comment by talaxasy** [comment]
> You need to install [language-postcss](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss) for highlighting.

I already installed this extension a long time ago
