### ISSUE TITLE
格式化

### ISSUE THREAD

**Issue by linxiaoran-a** [johnsoncodehk/volar#1827]
连续多次格式化，代码会缺失

**Comment by xinde** [comment]
> 连续多次格式化，代码会缺失

我这是多次格式化后，有时候会删除最后一个div的尾标签，有时候会删掉一半
![image](https://user-images.githubusercontent.com/1617414/188592823-3c75e4e1-c57a-4671-8d4a-d8c152185960.png)

**Comment by linxiaoran-a** [comment]
> 
一样的
