### ISSUE TITLE
Property 'XXX' does not exist on type '{}'.

### ISSUE THREAD

**Issue by ilgiznurgaliev** [johnsoncodehk/volar#1828]
Hello.

I'm working on Vue3 application created by `npm init vue@latest`. For some reason recently VSCode started to show `Property 'XXX' does not exist on type '{}'.` error for every property and methid returned by `setup()` (I'm using Composition API with Typescript). The same picture for every single file component:

![image](https://user-images.githubusercontent.com/10621366/188591951-95956b0e-f693-4c62-8c9f-2bbaf6624837.png)

At the same time Vue application works just fine, I'm able to succesfully run it in dev mode and create prod build. Type checks and linting are also with no any errors. That's why I think this is probably Volar extension.

Installed version:
Vue Language Features (Volar) v0.40.9 (takeover mode configured for vue workspace).
"vue": "^3.2.38"

**Comment by ilgiznurgaliev** [comment]
Tried to reinstall Volar, didn't help. After reloading VSCode the errors went away for some time but appear again in some minutes.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by akunlee** [comment]
I had the same problem yesterday，maybe you should check this configuration:
![image](https://user-images.githubusercontent.com/52097543/188767700-ea2fad2c-3ae3-4db6-8569-fb3ad42cd8e5.png)

**Comment by ilgiznurgaliev** [comment]
Thanks for your responses.

@johnsoncodehk Yesterday I tried to remove VSCode with all extensions, cleared everything and installed it again, then installed Volar and configured takeover mode. Since that activities the issue was not appearing. Probably there was a conflict with some of the extensions. Let me test some more time, I'll update this issue.

@akunlee My `extensions.json` looks like below. It was installed by `npm init vue@latest`, I didn't customize it.
```
{
  "recommendations": ["Vue.volar", "Vue.vscode-typescript-vue-plugin"]
}
```

**Comment by johnsoncodehk** [comment]
@ilgiznurgaliev Any update? I think it maybe happen due to some conflict types from node_modules .

**Comment by ilgiznurgaliev** [comment]
@johnsoncodehk no any issues anymore after re-installing vscode and configuring volar again. So the issue can be closed I think.
Thank you.
