### ISSUE TITLE
Message: Request textDocument/documentSymbol failed with message: host.fileExists is not a function

### ISSUE THREAD

**Issue by loclahost** [johnsoncodehk/volar#1829]
Today Volar started giving me this error for every change

[Error - 1:35:19 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: host.fileExists is not a function
  Code: -32603 

Volar version: v0.30.1

VSCode
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T22:40:32.806Z
Electron: 19.0.13
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.7-arch1-1
Sandboxed: No

Any ideas?

**Comment by aesyondu** [comment]
Volar is at version [v0.40.9](https://github.com/johnsoncodehk/volar/releases/tag/v0.40.9) now.

Could you try updating?
