### ISSUE TITLE
[FR] Customizable Scaffold Snippets using `.vue` files

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#183]
I haven't found Vetur's [Customizable Scaffold Snippets](https://vuejs.github.io/vetur/guide/snippet.html#customizable-scaffold-snippets) equivalent in Volar, I think its main advantage is:

> You can use everything that's allowed in [VS Code Snippet Syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets). The good thing is, you write them in `.vue` files instead of `.json` files, and you don't need to escape special characters.

Could you please consider adding it?

**Comment by johnsoncodehk** [comment]
Thanks for your suggestion, but I think plugin specific things is not good for development ecology, I think it is simpler and more appropriate to build a .vue -> .json converter.

**Comment by wenfangdu** [comment]
@johnsoncodehk I've gone ahead and created a [snippet generator extension](https://github.com/wenfangdu/vscode-snippet-generator) for this. It supports code to JSON conversion.

**Comment by johnsoncodehk** [comment]
Great work! Added to readme.

I hope there is an online converter for two-way conversion, which can help edit and preview existing VSCode snippets.
