### ISSUE TITLE
Support formatting selected text only with indent

### ISSUE THREAD

**Issue by jez9999** [johnsoncodehk/volar#1833]
When indent is set to true, all code in a section gets formatted instead of just the selection on "Format selection".  More discussion in [this comment](https://github.com/johnsoncodehk/volar/issues/1806#issuecomment-1237701955) and later comments.

**Comment by johnsoncodehk** [comment]
Thanks for the comments! It should be already resolved by https://github.com/johnsoncodehk/volar/commit/12ee9c46f37267412f779216ed811ccb1d2316cb, please let me know if still not working.
