### ISSUE TITLE
Remove globalAttributes from html customData configuration

### ISSUE THREAD

**Issue by zardoy** [johnsoncodehk/volar#1836]
The problem: `globalAttributes` produces extremely misleading suggestions and makes `lang` in `attributes` of `tags` (which are above) useless and causes duplications in `<script lang="` completions (chaos in a short)

Obviously, it can suggest to set `script`'lang to `scss` and `div` to `tsx`.

https://github.com/johnsoncodehk/volar/blob/0ef9fa24a4aa06186c172f3046a55e9644967abf/packages/vue-language-service/src/plugins/vue.ts#L64-L70

I'm just curious what are the cases where `globalAttributes` are being used?

**Comment by johnsoncodehk** [comment]
It's for custom block like `<i18n>`, I think the problem it should only affect for SFC blocks but not for template elements.

**Comment by zardoy** [comment]
No, it affects all template elements as the same html service is being used e.g.
```vue
<template>
    <div lang=""></div>
</template>`
```

> It's for custom block like <i18n>

If we use the same service along SFC blocks and template elements I think we should handle SFC blocks attributes manually somehow, not sure for now
