### ISSUE TITLE
Type narrowing does not affect template

### ISSUE THREAD

**Issue by some-user123** [johnsoncodehk/volar#1838]
If a type is narrowed properly in script, this does not affect template, but still causes a type error.

```html
<script setup lang="ts">
import { ref } from 'vue';

const data = ref<{ id: number } | null>({ id: 42 });

if (data.value === null) {
  data.value = { id: 0 };
}

data.value.id++;
// Does not cause type error as type is narrowed
</script>

<template>
  <div>
    {{ data.id }}
    <!-- Causes a type error :-( -->
  </div>
</template>
```

Reproduction: https://stackblitz.com/edit/vitejs-vite-c8g7sk?file=src%2FApp.vue&terminal=dev

cf. https://github.com/nuxt/framework/issues/7309

**Comment by xiaoxiangmoe** [comment]
```vue
<script setup lang="ts">
import { ref } from 'vue';

const data = ref<{ id: number } | null>({ id: 42 });

if (data.value === null) {
  data.value = { id: 0 };
}

data.value.id++;
// Does not cause type error as type is narrowed
setTimeout(()=>{
   // data.value in mutable, it can be changed.
   data.value = null;
},10000)
</script>

<template>
  <div>
    {{ data.id }}
    <!-- Causes a type error  -->
    <!-- Work as intended  -->
    <!-- Because  data in template is data.value in script -->
  </div>
</template>
```

**Comment by some-user123** [comment]
That's not the point. `data.value` is narrowed to `{ id: number }` in script. So should be `data` in template, which still is `{ id: number } | null}`.

**Comment by CapitaineToinon** [comment]
I see this is closed but I don't believe this works as intended in the situation where the setup function throws an error. I'm using nuxt's createError util function to throw if my data is not present:

```vue
<script setup lang="ts">
const route = useRoute()
const { data } = await useFetch(`/api/movies/${route.params.slug}`)
if (!data.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page Not Found' })
}
</script>
```

In this case, the template should never render with a null value and therefore should be correctly narrowed in my opinion. Any issues with this?
