### ISSUE TITLE
[FR] Emmet support for JSX/TSX

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#184]
Emmet support for JSX/TSX in SFC would be nice.

**Comment by johnsoncodehk** [comment]
Supported in 0.25.5, thank you!

**Comment by wenfangdu** [comment]
Thanks, that was fast! However, the current tag expansion doesn't always work, and `className` should be adjusted to `class`:

![volar](https://user-images.githubusercontent.com/28700378/118593495-629ad580-b7da-11eb-9b81-01378c067c9a.gif)

**Comment by johnsoncodehk** [comment]
You need to use [custom-emmet-snippets](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets) to change `className`.

`baz` is not match to element name so it's not works in expected, if you typing `baz.xxx` it should working as `<baz className="xxx">|</baz>`.

`foo` works for me as `<footer>|</footer>`, could you provide a repro case?
