### ISSUE TITLE
格式化后，标签剩一半

### ISSUE THREAD

**Issue by 690523225** [johnsoncodehk/volar#1840]
格式化前
![1662538884065](https://user-images.githubusercontent.com/57696990/188828259-a10bf76b-5a2b-469f-b373-501088cd155e.jpg)
格式化后
![1662539042027](https://user-images.githubusercontent.com/57696990/188828844-9e3fd9c6-13ea-4fef-9102-2b5cca7c44b1.png)

**Comment by DSzhongweizi** [comment]
这个最近几个小版本都这样，不清楚是新版本vscode的问题还是插件问题，太影响开发体验了

**Comment by 690523225** [comment]
> 

用别的插件没有这个问题呀

**Comment by zhengxdlol** [comment]
我也是这个问题 还有复制一段代码后 也会出现问题 会直接删除一部分的代码
