### ISSUE TITLE
Formatting screws up on second 'Format Selection'

### ISSUE THREAD

**Issue by jez9999** [johnsoncodehk/volar#1843]
Given the following document saved in a `.vue` file:

```
<script setup>
import { ref } from 'vue';
import { RouterView } from 'vue-router';
import Navbar from '@/components/Navbar.vue';

    //const test1 = ref(0);
</script>

<template>
    <Navbar />
    <div class="container-fluid mt-3 border border-2 rounded" style="background-color: #e3fff9;">
        <div class="p-3">
            <RouterView />
        </div>
    </div>
</template>

<style scoped>
.aaaa {
    color: red;
}

.bbbb {
    color: red;
}
</style>
```

Select all, then 'Format Selection' twice in a row.  The second time, the formatting screws up and the `</template>` tag is partially deleted.

**Comment by sevillaarvin** [comment]
I think these are all duplicate issues:

https://github.com/johnsoncodehk/volar/issues/1827
https://github.com/johnsoncodehk/volar/issues/1832
https://github.com/johnsoncodehk/volar/issues/1840
https://github.com/johnsoncodehk/volar/issues/1842

**Comment by jez9999** [comment]
It's some kind of state error with the `vueDocument`s stored in the language server.  The second time round the state identifies the wrong range for the `<template>` block.  I gave up debugging at that point because it's super complex.

**Comment by Ragura** [comment]
It's happening to me too, deleting text somewhere else in the file (not only in the template) on 'format on paste' (which uses format selection under the hood I believe). It doesn't seem to matter where or what I paste. I don't have a reproduction available at the moment, but it happens across all my Vue projects.

Not using a `volar.config.js`, but I do have an eslint config that does formatting for me. However, I always had that and haven't changed anything about it. Extremely dangerous problem for a code base.

**Comment by johnsoncodehk** [comment]
Could you try [volar-0.40.11-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/9507710/volar-0.40.11-alpha.1.vsix.zip)?

**Comment by jez9999** [comment]
Yep that fixes it for me!
