### ISSUE TITLE
vue-language-core: Breaks when extending nested tsconfig files

### ISSUE THREAD

**Issue by ilyub** [johnsoncodehk/volar#1844]
Consider the following 3 config files:
```
./tsconfig.json: 
{ 
  extends: "./configs/strict" ,
...
}

./configs/strict.json: 
{ 
  extends: "./min",
  ...
}

./configs/min.json: 
{ 
  ...
}
```

Extending "./min" works fine for all other tools except volar.

With volar I get error in @volar/vue-language-core/out/utils/ts.js at this line:
```ts
const extendsPath = require.resolve(content.raw.extends, { paths: [folder] });
```
saying "Cannot find module ./min"

**Comment by johnsoncodehk** [comment]
Could you try `extends: "./min.json"`?

**Comment by ilyub** [comment]
Hi, I tried "./min.json" with the same result.

I think the issue is that require.resolve resolves path relative to project root folder.

**Comment by kpetracca-formfree** [comment]
Hi - I also am running into a similar issue. It's occurring in versions `vue-tsc@0.40.6` and above.

**Comment by johnsoncodehk** [comment]
Could you provide minimal reproduction?
