### ISSUE TITLE
pasting emits causes strange deletions

### ISSUE THREAD

**Issue by magicseth** [johnsoncodehk/volar#1845]
If I paste this code:
```
const emit = defineEmits<{
    (e: "s", site: string): void;
}>();
```

it automatically deletes the `const emit =` part in a very simple vue template.

In more complex files, it ends up deleting random parts of the .vue file instead.

**Comment by sevillaarvin** [comment]
Hi, there is a similar problem with a fix here but not yet released:

https://github.com/johnsoncodehk/volar/issues/1843#issuecomment-1239577799

**Comment by magicseth** [comment]
Yep, that fixed it!
