### ISSUE TITLE
definition to lazy component

### ISSUE THREAD

**Issue by Flashantik** [johnsoncodehk/volar#1846]
Volar doesn't see the lazy component 
<img width="413" alt="Screen Shot 2022-09-08 at 14 43 53" src="https://user-images.githubusercontent.com/25429994/189090622-e9c62b07-1bbf-4fd4-8a51-4ee725e478d8.png">
<img width="720" alt="Screen Shot 2022-09-08 at 14 44 23" src="https://user-images.githubusercontent.com/25429994/189090733-5d6f1d8b-6199-40db-a407-b4f432a69f5e.png">

components are registered globally in  components.d.ts

```
components.d.ts
import SharedListPostsLoadingError from './components/shared/list/posts/LoadingError.vue'

declare module '@vue/runtime-dom' {
  export interface GlobalComponents {
    SharedListPostsLoadingError: typeof SharedListPostsLoadingError
  }
}
```

Volar v0.40.13
Vscode: 1.71.0
nuxt@2.15.8
vue@2.6.14
typescript@4.7.3

**Comment by xiaoxiangmoe** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?
