### ISSUE TITLE
Miss the first letter on property (web component)

### ISSUE THREAD

**Issue by AngryChocobo** [johnsoncodehk/volar#1849]
demo1: 
![image](https://user-images.githubusercontent.com/24283492/189264866-7de915ef-70fe-4143-8359-b0298d159c8f.png)

demo2: 
![image](https://user-images.githubusercontent.com/24283492/189264890-914190c6-f024-49d2-86f6-6336b9ffbbd9.png)

I checked the Elements. It is correct.

My device info: 
> Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Name: Vue Language Features (Volar)
Version: 0.40.13

I tried restart vscode. But it still shows error info.

**Comment by johnsoncodehk** [comment]
Could you try can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?

**Comment by johnsoncodehk** [comment]
I think this is `@vue/runtime-dom` issue and fixed in latest version.
