### ISSUE TITLE
Duplicate options appear in html

### ISSUE THREAD

**Issue by tlyboy** [johnsoncodehk/volar#1852]
![image](https://user-images.githubusercontent.com/95838362/189368419-cfc56d87-fd8f-4e26-aa7e-9858410277e0.png)

**Comment by you-hengh** [comment]
是的 我也遇到这个情况了
vscode 版本:
> 版本: 1.70.2 (Universal)
提交: e4503b30fc78200f846c62cf8091b76ff5547662
日期: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

volar插件版本:v0.40.13

![image](https://user-images.githubusercontent.com/34816426/189471663-24cf92c9-b40b-4d5f-9e84-a20dcef69d90.png)

希望能够尽快修复这个 BUG, Thanks♪(･ω･)ﾉ

**Comment by DawidFrankiewicz** [comment]
![image](https://user-images.githubusercontent.com/69369874/190458811-b272e07d-e0d9-44f2-b06c-afa805e020d9.png)
Same issue, with only this extension enabled. Everything else disabled. As soon as I disable extension and reaload, bug is gone.

**Comment by you-hengh** [comment]
@johnsoncodehk   nonono,  are you sure ? I retested it your way, but it didn't change anything. And vscode doesn't recognize these configurations.

![未命名](https://user-images.githubusercontent.com/34816426/190629498-ed242919-32b0-430d-8447-a1eb9fcdd1f6.jpg)

![未命名 2](https://user-images.githubusercontent.com/34816426/190629530-304b82d0-e3bf-4df4-ba4b-0a4b7bbb2347.jpg)

Can you reproduce this problem locally? 

Myvscode version:
> Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

volar version:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/34816426/190629991-7b585e63-c373-4783-99fd-edf9a04a6224.png">

**Comment by johnsoncodehk** [comment]
@you-hengh You should install v1.0.0-alpha.0: #1880

**Comment by you-hengh** [comment]
> @you-hengh You should install v1.0.0-alpha.0: #1880

Can you create a normal html file to open your volar and see if the code hints will be repeated twice?
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/34816426/190633259-28342744-4edf-4c67-8cf4-1688bb4d2ac6.png">
I installed v1.0.0-alpha according to your request and set the specified configuration as you suggested, but the code hint was still displayed twice.

When the volar plug-in is disabled, the code prompt is displayed only once
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/34816426/190633912-869d002b-3dfd-4cd0-8044-0a4844d0c4d6.png">

so.....you look

**Comment by johnsoncodehk** [comment]
@you-hengh You should not enable `volar.vueserver.petiteVue.processHtmlFile` and `volar.vueserver.vitePress.processMdFile`, it's for petite-vue / VitePress supports, please remove `volar.vueserver.petiteVue.processHtmlFile`, `volar.vueserver.vitePress.processMdFile` and reload VSCode.

**Comment by you-hengh** [comment]
> @you-hengh You should not enable `volar.vueserver.petiteVue.processHtmlFile` and `volar.vueserver.vitePress.processMdFile`, it's for petite-vue / VitePress supports, please remove `volar.vueserver.petiteVue.processHtmlFile`, `volar.vueserver.vitePress.processMdFile` and reload VSCode.

yes!   yes!  it's OK!!!
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/34816426/190636381-10f67c2a-20cc-406f-9039-83ee4e168288.png">

Thank you very much!
