### ISSUE TITLE
ref  的.value自动补全失效  

### ISSUE THREAD

**Issue by wtq1996503** [johnsoncodehk/volar#1853]
voalr版本 0.40.13
vscode版本1.71.0
已勾选
![image](https://user-images.githubusercontent.com/51228740/189465254-4856e6d8-2f64-4d5e-9b3d-68ca3684f221.png)
输入newsListActiveIndex无.value提示
![image](https://user-images.githubusercontent.com/51228740/189465271-5585c72c-9f69-4e3d-94a5-61cf833ae4e4.png)

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?
