### ISSUE TITLE
✨ Improve vue-component-meta for dynamic props

### ISSUE THREAD

**Issue by jd-solanki** [johnsoncodehk/volar#1854]
Thanks for publishing `vue-component-meta`. Every lib requiring component docs needs this package. It is very helpful ❤️ 

At the moment volar can extract the props correctly, however, if there are dynamic props volar can't extract the proper information.

```ts
  props: {
    ...useLayerProps({
      color: {
        default: 'primary',
      },
      variant: {
        default: 'fill',
      },
      states: {
        default: true,
      },
    }),
    disabled,
```

[Complete reference](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/components/btn/ABtn.tsx)

Here's a discussion [thread](https://github.com/johnsoncodehk/volar/discussions/1809#discussioncomment-3591499) regarding what's not working properly.

We might need to add dynamic props test in [this](https://github.com/johnsoncodehk/volar/tree/2758510a8e519563f16ce023c700ab98b8b65ad8/packages/vue-test-workspace/vue-component-meta) dir.

Thanks.

**Comment by alokVishu** [comment]
+1

**Comment by johnsoncodehk** [comment]
Close because it was expected TS behavior, and it can't be resolved on Volar side.
