### ISSUE TITLE
Request textDocument/linkedEditingRange failed.

### ISSUE THREAD

**Issue by gregveres** [johnsoncodehk/volar#1856]
I have volar v0.40.13 installed. I have a Vue 2 project using the composition api. I am not yet on Vue 2.7.

 I am getting this error from Volar constantly: 
```
[Error - 10:45:06 AM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
```

And after this, it seems like Volar is no longer working. I have to restart the volar vue server to get it working again.

**Comment by johnsoncodehk** [comment]
Could you show detailed error message (In particular the line number where the error occurred) or provide minimal reproduction?

To see error message, you can execute `Developer: Toggle Developer Tools` VSCode command and check logs on console tab.

**Comment by gregveres** [comment]
Ok, I will do that and get back to you.

**Comment by gregveres** [comment]
If I execute Developer: Toggle Developer Tools (which brings up the chrome debugger), are you saying that the console should show output from volar that augments the errors I am seeing in the Volar Output window? 

I ask because I am seeing a lot of errors in the  Volar Output window but there is nothing that looks like errors in the console window. 

I decided to restart VSCode to sync up the Output window and the Console. Then I got this in the Volar - Language Features Server output window and the same in the Volar - Second Language Features Server

```
Error: Cannot find module '../../../tsconfig.base.json'
Require stack:
- c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js
- c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at $ee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4337)
    at Vee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4186)
    at $ee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4385)
    at Object.Vee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4186)
    at x (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:27333)
    at c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:23898
    at Generator.next (<anonymous>)
    at c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:23662 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\Greg\\.vscode\\extensions\\vue.volar-0.40.13-win32-x64\\dist\\node\\server.js',
    'c:\\Users\\Greg\\.vscode\\extensions\\vue.volar-0.40.13-win32-x64\\server.js'
  ]
}
Error: Cannot find module '../../../tsconfig.base.json'
Require stack:
- c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js
- c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at $ee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4337)
    at Vee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4186)
    at $ee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4385)
    at Object.Vee (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1019:4186)
    at x (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:27333)
    at c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:23898
    at Generator.next (<anonymous>)
    at c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:23662 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\Greg\\.vscode\\extensions\\vue.volar-0.40.13-win32-x64\\dist\\node\\server.js',
    'c:\\Users\\Greg\\.vscode\\extensions\\vue.volar-0.40.13-win32-x64\\server.js'
  ]
}
```

I suspect I have something misconfigured. 
I am using Nx with Vue 2. I have 4 apps and 25 libraries. I am not sure which of those nx projects it is complaining about though.

**Comment by johnsoncodehk** [comment]
@gregveres Thanks for the information, this error message is failed at https://github.com/johnsoncodehk/volar/blob/76abcdd5d9457893f50122410a58b2c3145c7dea/packages/vue-language-core/src/utils/ts.ts#L54, but it should not lead to `Cannot read properties of undefined (reading 'version')` error, so I think there are 2 different problems.

**Comment by gregveres** [comment]
since this is hitting an error with a path, does that mean I have messed up the configuration and I am missing setting some necessary path? Volar used to work great for me, but a month or two ago, it started failing like this and I started missing functionality like document formatting of the template portion of my vue files.

**Comment by johnsoncodehk** [comment]
Could you provide minimal reproduction? It's most helpful to me.

Or you can try downgrade extension and let me know which version begin to happen this problem, I might be able to compare the changes to find the reason.

**Comment by gregveres** [comment]
I will see what I can do. My project is fairly big: 4 Nx apps and 30 Nx libraries. But I will see what I can put together when I get a chance.

**Comment by gregveres** [comment]
I wanted to come back and give you some feedback here.
I recently upgraded my project to Vue 2.7 while waiting for Vuetify to release version 3.1. I figured I should get on to the 2.7 version and get as close to Vue 3 as I can while I wait.

Once I got onto Vue 2.7, things are pretty rock solid. There was one out of memory issue from Volar when I had a couple hundred vue files open (I was changing the references from the composition api import to the vue import). Once I closed the files and restarted, things were good.

Since that point, I haven't noticed any issues from Volar and it has been helping out tremendously as I convert to vue 2.7.

If you want, you can probably close this issue.

**Comment by dalibormrska** [comment]
I had this problem with a new Vue 3 project and Volar extension, I resolved it by disabling **Volar: Auto Complete Refs** setting.

**Comment by gregveres** [comment]
@dalibormrska Thank you for pointing that out. I have been looking for a way to get rid of the .value auto complete. I thought I had installed a different extension to do it. 
I find the .value auto complete to be really buggy and annoying. I thought it was going to be fantastic, but saidly it gets in the way more than I find it useful. Now that I know it is part of Volar, I think I will open an issue for it.
