### ISSUE TITLE
importing vue file with auto-completition gives wrong name.

### ISSUE THREAD

**Issue by humbleCoder1990** [johnsoncodehk/volar#1861]
![image](https://user-images.githubusercontent.com/87828192/189584705-d15c2c9e-455b-49c1-a56b-c6dcb21ff7b6.png)

I want "HelloWorld", but It auto-completes "helloWorldVue". (not CamelCase, and it addes "Vue" at the end)

**Comment by johnsoncodehk** [comment]
Duplicate of #82
