### ISSUE TITLE
Issue with resolving JSON file with vue-tsc

### ISSUE THREAD

**Issue by azat-io** [johnsoncodehk/volar#1862]
<img width="1199" alt="Screenshot 2022-09-12 at 8 48 40 PM" src="https://user-images.githubusercontent.com/5698350/189743829-f69c8884-1b59-4358-b769-1583785b3e7e.png">

When I try to import `.json` files into `.vue` files with declared JSON file data as a module, vue-tsc doesn't understand the type of data being exported

Here is my TypeScript config:

```json
{
  "compilerOptions": {
    "types": ["node"],
    "forceConsistentCasingInFileNames": true,
    "importsNotUsedAsValues": "error",
    "moduleResolution": "nodenext",
    "preserveValueImports": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "module": "esnext",
    "target": "es2020",
    "jsx": "preserve",
    "allowJs": true,
    "strict": true,
    "baseUrl": ".",
    "noEmit": true,
  }
}
```

Also I have `"type": "module"` in my `package.json` file. My `vue-tsc` version is 0.40.13.

**Comment by azat-io** [comment]
Thanks!

**Comment by azat-io** [comment]
Looks like the problem persists in v1.0.0-alpha.5

**Comment by johnsoncodehk** [comment]
@azat-io could you provide minimal reproduction?
