### ISSUE TITLE
Volar gives tsx error

### ISSUE THREAD

**Issue by Legion64** [johnsoncodehk/volar#1863]
Hello,

I wanted to develop an application with TS support with Volar. But for some reason the volar keeps throwing an error. I've tried different things on this. For example, I tried again with VSCode Insider without any plugins, then I changed the volar version. But none of these gave me a solution.

Screenshot;
![Screenshot_13](https://user-images.githubusercontent.com/35144787/189932773-4041d58b-7b69-4df5-92c5-4a0556a63e7c.png)

At first I thought it wasn't related to volar. And I have eliminated all TypeScript controllers on VSCode. But when it came to removing Volar as a last resort, the whole problem was solved. But without volar it seems like there is no point in developing vue application in VSCode. How can I fix this error?

**Comment by johnsoncodehk** [comment]
Could you try #592 solutions?

**Comment by Legion64** [comment]
I guess I'm stupid. I can't solve the problem anyway. For example, what should I write in the "types" part of the solution you sent? Or for the "exclude" field you mentioned? Do I need to type the path to the vue router types file for types?

**Comment by johnsoncodehk** [comment]
Please use v1.0.0-alpha, see https://github.com/johnsoncodehk/volar/discussions/592#discussioncomment-3660903.
