### ISSUE TITLE
Type { ... } is not assignable to type 'SomeClass'

### ISSUE THREAD

**Issue by colinblaise** [johnsoncodehk/volar#1864]
Using `vue-tsc 0.40.13`, `vue 2.7.9`, and using the options api.

I have a class called `ActionList` that I am assigning in `data()`  like so:

```ts
data() {
  return {
    actionList: new ActionList([]),
  }
},
...
```

Viewing the type when hovering over `actionList` correctly shows `ActionList`.

![image](https://user-images.githubusercontent.com/6540262/189947417-d4509c46-8219-428d-b849-9e4fe245364d.png)

However, hovering over `this.actionList` shows a destructured representation of `ActionList` (fine, nbd)

![image](https://user-images.githubusercontent.com/6540262/189947857-c47e6b6e-25e8-4caf-8e82-c7a361ec09e0.png)

The problem is that the template is throwing a type error.

![image](https://user-images.githubusercontent.com/6540262/189948046-0bd5f8c0-24a5-410a-b17d-61fee87e3da9.png)

This error is shown when I set the component's prop definition to either:

```ts
props: {
    actionList: {
      type: Object as PropType<ActionList>,
      required: true,
    },
}

or

props: {
    actionList: {
      type: ActionList,
      required: true,
    },
```

Has anyone experienced similar issues? Perhaps I just need additional configuration.

**Note**

Doing the following suppresses the error, but vue-tsc complains about this

![image](https://user-images.githubusercontent.com/6540262/189950560-c056dcf2-b3e5-44cd-99b3-d71c148f4083.png)

**Comment by lukemovement** [comment]
Everything passed to a component via the props is wrapped in a deep read only type. This results in non public properties being made public. I know this bug has been previously raised on the Vue Github repo so they are aware of it, however I'm not sure if it is fixable at this current time.

Alternative solutions:
* Cast the actionList variable to any instead of using the ActionList type
```
:actionList="(actionList as any)"
```

* Wrap the actionList property in a computed property and cast the return type
```js
export default {
  computed: {
    computedActionList(): ActionList {
      return this.actionList as ActionList;
    }
  }
}
```

**Comment by colinblaise** [comment]
Thanks for the reply.  Yeah… I already settled on just wrapping it in a

**Comment by colinblaise** [comment]
Thanks,  I gave up pretty much immediately after posting this and just wrapped it in a computed, casting it exactly as you described.   

I’ve been opting for using <script setup>  for new components which doesn’t have this particular issue I believe, since I can define the props via an interface using ‘defineProps’.
