### ISSUE TITLE
After using volar, the project freeze is particularly serious

### ISSUE THREAD

**Issue by sidoc-cn** [johnsoncodehk/volar#1868]
After using volar, the project freezes very seriously, and the import prompt is also very slow. Is there any solution?

**Comment by lmiller1990** [comment]
You'll probably need to provide more information - how many files, lines of code, vue files, etc?

If you are on a large monorepo, you could try only opening VS Code in one or a few of the packages you are using - this may help. Volar does struggle on some repositories, especially ones with many different `tsconfig.json` files.

**Comment by sidoc-cn** [comment]
My project is very small, it's just a Demo, my source code is here [https://github.com/sidoc-cn/vue3-demo-ts](https://github.com/sidoc-cn/vue3-demo-ts)

**Comment by johnsoncodehk** [comment]
One of repo depend element-plus has many .d.ts files, it will lead to TypeScript language service auto import slow, you can disable `typescript.suggest.autoImports` in VSCode setting to skip auto import calculate.
