### ISSUE TITLE
After 0.23.0 version app.component, there is no prompt.

### ISSUE THREAD

**Issue by TuiMao233** [johnsoncodehk/volar#187]
0.29.0 version
![image](https://user-images.githubusercontent.com/49724027/118602217-fc678000-b7e4-11eb-83f3-f819ff934b78.png)
![image](https://user-images.githubusercontent.com/49724027/118602353-25881080-b7e5-11eb-84d1-08f7e6bbc9f8.png)
0.30.0 Later version
![image](https://user-images.githubusercontent.com/49724027/118602427-418bb200-b7e5-11eb-895d-55e37cc7dcb3.png)
![image](https://user-images.githubusercontent.com/49724027/118602445-46e8fc80-b7e5-11eb-83c4-8a5e82e76e78.png)

**Comment by johnsoncodehk** [comment]
This is expected, see https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0230

You need to use `interface GlobalComponents` after 0.23.0.

```ts
import HelloWorld from './components/HelloWorld.vue'

declare module 'vue' {
	export interface GlobalComponents {
		HelloWorld: typeof HelloWorld
	}
}
```

**Comment by TuiMao233** [comment]
I think this must be a good idea to compile templates faster, but what I might care more about is saving this job. I wonder if it can be an option, let’s choose whether to enable it. What do you think of this feature?

**Comment by johnsoncodehk** [comment]
Yes, this feature can be convenient for some users, but it was decided to remove it for many reasons.

The two most important reasons are:

- This is a Volar-specific feature, and users cannot smoothly transition to other IDEs such as webstorm.
- This feature prevents users learning Vue 3 TS on the correct path.
