### ISSUE TITLE
Nuxt 3 component typings not working

### ISSUE THREAD

**Issue by tazaraz** [johnsoncodehk/volar#1876]
I am unsure what the cause is, but components do not get resolved properly by TypeScript. I have a custom directory for shared components for multiple projects, and they are imported in the 'common' folder. This is achieved using:
```js
export default defineNuxtConfig({
    …,
    components: {
        global: true,
        dirs: [
            '~/components',
            '~/common/components',
        ]
    },
    …
})
```
I have this problem with all of my components, but for demonstration I show only one.

The Nuxt 3 command 'nuxt prepare' prepares the following '.nuxt/components.d.ts':
![Screen Shot 2022-09-15 at 21 18 40](https://user-images.githubusercontent.com/31385426/190490806-32ebfc83-5794-48d6-852e-e1addf15a24f.png)
which seems fine, and clicking on the path it goes straight to the actual component. However, upon hovering over the component in a template (pressing 'command' to show more info), the following happens:

![Screen Shot 2022-09-15 at 20 48 40](https://user-images.githubusercontent.com/31385426/190485921-237fa71e-b07c-475c-83aa-a4bc0641452e.png)
I have also tried replacing `declare module 'vue'` with `declare module '@vue/runtime-core'`, but to no avail. It always seems unable to properly resolve the `typeof import(…)` to get the type definitions, and besides, it says that it is `typeof Url1`, which does not exist in 'components.d.ts' (only `Url` does). Placing the component in the default location (`~/components`) fixes the incorrect definition to `typeof Url`, but that's about all.

The class itself looks like:
![Screen Shot 2022-09-15 at 21 15 54](https://user-images.githubusercontent.com/31385426/190490272-8411dac8-8afc-4d1d-ada8-e7cc3ec1be04.png)

I have disabled all extensions besides a custom theme and Volar, and I am using class components in Nuxt 3, with only the following dependencies:
```json
"dependencies": {},
"devDependencies": {
    "nuxt": "npm:nuxt3@latest", // As of writing 3.0.0-rc.9
    "vue-class-component": "^8.0.0-rc.1",
    "vue-property-decorator": "^10.0.0-rc.3"
}
``` 

macOS High Sierra 10.13.6
node v16.17.0
@nuxt/cli v2.14.12

**Comment by johnsoncodehk** [comment]
> which seems fine, and clicking on the path it goes straight to the actual component. However, upon hovering over the component in a template (pressing 'command' to show more info), the following happens:
> 
> ![Screen Shot 2022-09-15 at 20 48 40](https://user-images.githubusercontent.com/31385426/190485921-237fa71e-b07c-475c-83aa-a4bc0641452e.png)

Sorry I don't understand what the main. Could you provide minimal reproduction?
