### ISSUE TITLE
在.vue文件的<template>输入大括号会跟系统自带的括号补全冲突导致多出来一个大括号

### ISSUE THREAD

**Issue by mxp131011** [johnsoncodehk/volar#1877]
在.vue文件的<template>{中输入大括号会跟系统自带的括号补全冲突导致多出来一个大括号
![image](https://user-images.githubusercontent.com/31055355/190536478-82cd7701-0a7e-472a-b1a0-e88ee9615604.png)

**Comment by liweiook** [comment]
It happened to me too: but I solved it. You can try it.。https://github.com/johnsoncodehk/volar/issues/1717

**Comment by liweiook** [comment]
不过我今天用volar写vue2又遇到新问题了，碰巧首页就看到你这个我曾经遇到过的问题，不确定是否有用。

> It happened to me too: but I solved it. You can try it.。#1717

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1717#issuecomment-1253393373
