### ISSUE TITLE
JS/TS language service crashed

### ISSUE THREAD

**Issue by Vilsafur** [johnsoncodehk/volar#1879]
Type: <b>Bug</b>

Service crash always when open .ts or .vue files

Extension version: 0.40.13
VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (0.93GB free)|
|Process Argv|--crash-reporter-id 72e375e9-4260-4d39-b2e5-1a22fefd47f3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & TypeScript|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2591)|
|Memory (System)|7.65GB (2.10GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
2144e591:30553903
fc301958:30567733

```

</details>

**Comment by d0m4te** [comment]
For me the language server also always crashes with  Fatal JS-Error that heap allocation failed because the memory capacity alloted to the js-server was exhausted.

Extension-version: 0.40.13
VS-Code-version: 1.71.2, 74b1f979648cc44d385a2286793c226e611f59e7, x64
OS: Ubuntu 22.04.1 LTS x86_64

**Comment by johnsoncodehk** [comment]
"JS/TS language service" is from VSCode built-in TS extension not Volar, please report to VSCode.

**Comment by Vilsafur** [comment]
It's for vscode bult-in TS extension but the message Say it's frim this extension. 

When i disable this extension, i don't have this problem.

**Comment by johnsoncodehk** [comment]
Can you show the message?
