### ISSUE TITLE
v1.0.0 Preview Download

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#1880]
Because VSCode marketplace [do not support prerelease semver versions yet](https://github.com/microsoft/vsmarketplace/issues/50), you need to manually install a extension packaged for now. I will upload each preview version to this issue.

- [volar-1.0.0-alpha.0.vsix.zip](https://github.com/johnsoncodehk/volar/files/9582196/volar-1.0.0-alpha.0.vsix.zip)
- [volar-1.0.0-alpha.2.vsix.zip](https://github.com/johnsoncodehk/volar/files/9611422/volar-1.0.0-alpha.2.vsix.zip)
- [volar-1.0.0-alpha.3.vsix.zip](https://github.com/johnsoncodehk/volar/files/9614624/volar-1.0.0-alpha.3.vsix.zip)
- [volar-1.0.0-alpha.4.vsix.zip](https://github.com/johnsoncodehk/volar/files/9638044/volar-1.0.0-alpha.4.vsix.zip)
- [volar-1.0.0-alpha.5.vsix.zip](https://github.com/johnsoncodehk/volar/files/9639140/volar-1.0.0-alpha.5.vsix.zip)
- [volar-1.0.0-beta.0.vsix.zip](https://github.com/johnsoncodehk/volar/files/9639909/volar-1.0.0-beta.0.vsix.zip)
- [volar-1.0.0-beta.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/9651293/volar-1.0.0-beta.1.vsix.zip)
- [volar-1.0.0-beta.2.vsix.zip](https://github.com/johnsoncodehk/volar/files/9683545/volar-1.0.0-beta.2.vsix.zip)
- [volar-1.0.0-beta.3.vsix.zip](https://github.com/johnsoncodehk/volar/files/9694691/volar-1.0.0-beta.3.vsix.zip)
- [volar-1.0.0-beta.4.vsix.zip](https://github.com/johnsoncodehk/volar/files/9701223/volar-1.0.0-beta.4.vsix.zip)
- [volar-1.0.0-beta.5.vsix.zip](https://github.com/johnsoncodehk/volar/files/9704149/volar-1.0.0-beta.5.vsix.zip)
- [volar-1.0.0-beta.6.vsix.zip](https://github.com/johnsoncodehk/volar/files/9704294/volar-1.0.0-beta.6.vsix.zip)
- [volar-1.0.0-rc.0.vsix.zip](https://github.com/johnsoncodehk/volar/files/9709065/volar-1.0.0-rc.0.vsix.zip)
- [volar-1.0.0-rc.3.vsix.zip](https://github.com/johnsoncodehk/volar/files/9714315/volar-1.0.0-rc.3.vsix.zip)
- [volar-1.0.0-rc.4.vsix.zip](https://github.com/johnsoncodehk/volar/files/9723789/volar-1.0.0-rc.4.vsix.zip)
- [volar-1.0.0-rc.5.vsix.zip](https://github.com/johnsoncodehk/volar/files/9731718/volar-1.0.0-rc.5.vsix.zip)

How to install: https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix (In short, unzip and drag the .vsix to VSCode "Extensions" Side Bar)

**Comment by ahnpnl** [comment]
Can we change `alpha.0` version to be in `next` tag instead of `latest`?

**Comment by johnsoncodehk** [comment]
@ahnpnl Done, thanks for reminding!

**Comment by baixiaoyu2997** [comment]
thanks for you work,  i'm not sure, beat.1 is still deploy or just missing in this place

**Comment by johnsoncodehk** [comment]
@baixiaoyu2997 just updated it, but beta.1 accidentally bundled the language server dependency in the language client (increased the package size, but not causing any problems), and I didn't find an easy fix yet.

**Comment by satrong** [comment]
![图片](https://user-images.githubusercontent.com/5283258/193716046-c64bd3a1-a4cf-4e6d-95c4-f5f15638bbc9.png)
![图片](https://user-images.githubusercontent.com/5283258/193716333-7ae44a89-1a31-4070-b355-ad2d8c12a310.png)

I'm not sure if it's a Volar's problem.

> vscode: 1.71.2, win 10, volar: 1.0.0-beta.4
>
> Not work fine for me from 1.0.0-beta.3

**Comment by johnsoncodehk** [comment]
@satrong could you show LSP logs in this out window by setting `"vue-syntactic-server.trace.server": "verbose"`?

**Comment by satrong** [comment]
Now I cannot get these errors again. This is LSP logs:
```
[Trace - 10:49:01] Sending request 'textDocument/linkedEditingRange - (363)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/ZH382/code/vite-project/src/components/HelloWorld.vue"
    },
    "position": {
        "line": 13,
        "character": 0
    }
}


[Trace - 10:49:01] Received response 'textDocument/linkedEditingRange - (363)' in 1ms.
No result returned.
```

![图片](https://user-images.githubusercontent.com/5283258/193724373-e0a1772a-b885-4b30-a20b-26ac3072165c.png)

**Comment by satrong** [comment]
And maybe a new problem, tooltip not working after file was saved

https://user-images.githubusercontent.com/5283258/193726902-c066a8c5-3d10-423c-9ccd-93b694c48f4c.mp4

**Comment by johnsoncodehk** [comment]
> And maybe a new problem, tooltip not working after file was saved

Fixed by https://github.com/johnsoncodehk/volar/commit/91f137faa5a4044b074016ad4e53d6f21fff0e81

**Comment by johnsoncodehk** [comment]
Just updated beta.5.

**Comment by yaegassy** [comment]
@johnsoncodehk it looks like `1.0.0-beta.5` is not published in npm.

**Comment by satrong** [comment]
Hi @johnsoncodehk , I found a new error in 1.0.0-beta.5
```
Element is missing end tag.vue(24)
```

https://user-images.githubusercontent.com/5283258/193776607-155d4b54-78bd-4b9c-abed-ae9675f4e2c5.mp4

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk it looks like `1.0.0-beta.5` is not published in npm.

Please use beta.6.

**Comment by johnsoncodehk** [comment]
> Hi @johnsoncodehk , I found a new error in 1.0.0-beta.5
> 
> ```
> Element is missing end tag.vue(24)
> ```

Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by satrong** [comment]
> > Hi @johnsoncodehk , I found a new error in 1.0.0-beta.5
> > ```
> > Element is missing end tag.vue(24)
> > ```
> 
> Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

Works fine in beta.6

Thank you.

**Comment by satrong** [comment]
Hi @johnsoncodehk , I don't know how to describe this problem, maybe useful for you after watch the video below
> Volar: 1.0.0-rc.3

https://user-images.githubusercontent.com/5283258/194240479-288f4de0-e91a-4ba1-87a1-b06460b5b54d.mp4

**Comment by johnsoncodehk** [comment]
@satrong I just found that this problem is only occur when disabled takeover mode, thanks!
