### ISSUE TITLE
Unable to install `vue-tsc` via npm

### ISSUE THREAD

**Issue by Theiaz** [johnsoncodehk/volar#1881]
I am unable to install `vue-tsc` via npm.

Steps to reprocude:

1. Creating new directory with default package.json
2. Install `vue-tsc` as dev dependency

```
schaefer@mystis:~/projects/examples/minimal-example-vue-tsc$ npm init
...
schaefer@mystis:~/projects/examples/minimal-example-vue-tsc$ npm i -D vue-tsc 
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:1.0.0-alpha.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/schaefer/.npm/_logs/2022-09-16T12_55_21_438Z-debug-0.log
schaefer@mystis:~/projects/examples/minimal-example-vue-tsc$ node -v && npm -v
v17.8.0
8.6.0
```

**Comment by productdevbook** [comment]
some problem 

Scope: all 10 workspace projects
 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @volar/language-core@1.0.0-alpha.0 inside the workspace

This error happened while installing the dependencies of vue-tsc@1.0.0-alpha.0
 at @volar/vue-typescript@1.0.0-alpha.0
Progress: resolved 135, reused 130, downloaded 0, added 0

**Comment by rikbrowning** [comment]
Quick workaround is to use the previous release.

```
npm i vue-tsc@v0.40.13 -D
```

**Comment by buffet-time** [comment]
>  ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @volar/language-core@1.0.0-alpha.0 inside the workspace

can confirm have the same issue with PNPM v 7.11.0

**Comment by johnsoncodehk** [comment]
Thanks for the report! Please use `v1.0.0-alpha.1` / `v0.40.13` instead of `v1.0.0-alpha.0`.

**Comment by buffet-time** [comment]
> Thanks for the report! Please use `v1.0.0-alpha.1` / `v0.40.13` instead of `v1.0.0-alpha.0`.

alpha.1 is working :) thank you
