### ISSUE TITLE
Moving components doesn't trigger import updates

### ISSUE THREAD

**Issue by guilherme-gm** [johnsoncodehk/volar#1884]
Hello, first of all, thanks for the awesome extension!

**System info**
- OS: Linux Mint 19.3
- VS Code version: 1.71.2
- Volar version: v0.40.13
- Vue 3 / Typescript / SFC

### Issue

Recently I noticed that while moving my components (SFC), other components that relies on them didn't get updated to match the new paths. I have tested both Takeover mode (with VS Code's version TS, which right now is 4.8.2) and without Takeover, both gives the same result.

For example, using Vue's startup project, where we have this structure:
```
src/
|- components/
    |- HelloWorld.vue
|- App.vue
```

and with `App.vue` importing `HelloWorld.vue`:
```TS
import HelloWorld from './components/HelloWorld.vue'
```

if I move `HelloWorld.vue` to the `src` folder, giving me:
```
src/
|- components/
|- HelloWorld.vue
|- App.vue
```

`App.vue` keeps the import as `./components/HelloWorld.vue`, which is an error. The dialog asking if I want it to update imports doesn't show up at all.

### Additional info
**Old versions:**
I tried downgrading to older versions of Volar and I noticed that it works fine on v0.39.5, the dialog shows up and once I accept, it update the imports. Upgrading to v0.40.0 and testing a few version between it and v0.40.13 (current) failed in every case.

**Project setup:**
If it helps, I created the project using vue cli tool with the following settings:
```
» npm init vue@latest 

Vue.js - The Progressive JavaScript Framework

✔ Project name: … test
✔ Add TypeScript? …  Yes
✔ Add JSX Support? … No 
✔ Add Vue Router for Single Page Application development? … Yes
✔ Add Pinia for state management? … Yes
✔ Add Vitest for Unit Testing? … Yes
✔ Add Cypress for End-to-End testing? … No
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … No 
```

**Comment by VladBrok** [comment]
Is it fixed? I have 2 files for a component: .vue and .ts in one folder. When i move folder, imports are not updated

**Comment by felixele217** [comment]
How to fix this?

**Comment by VladBrok** [comment]
@felixele217 do you use SFC? For me, this bug occurred when I split components into .vue and .ts files. I tried SFC once and it worked fine.

**Comment by VladBrok** [comment]
I was advised to use WebStorm, which has better Vue support, but I couldn't quit vscode
