### ISSUE TITLE
Request textDocument/codeAction failed. when create new tsx file

### ISSUE THREAD

**Issue by chenjiangui** [johnsoncodehk/volar#1885]
Request textDocument/codeAction failed. when create new tsx file

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by satrong** [comment]
今天我升级了依赖后，也出现了这个问题，最后将依赖一个一个的降级尝试后发现似乎不是 volar 的问题，最后定位到与 `@typescript-eslint/eslint-plugin` 和 `@typescript-eslint/parser` 有关，原本我升级到了 `5.38.0` ，然后降级到了 `5.35.1` ，目前用了2个小时，没出现这个问题。（我用的是 takeover 模式，ts 版本 4.7.4, vscode 1.71.2, win10）
