### ISSUE TITLE
[vue-component-meta] re-check same components with update

### ISSUE THREAD

**Issue by Tahul** [johnsoncodehk/volar#1889]
Follow up of: https://github.com/nuxtlabs/nuxt-component-meta/pull/43

Currently, when using `vue-component-meta` checkers, once the checker has been initialized, any request to a component metas will return the data for the component at the state it was when the checker has been created.

Including the fact that the checker can take a pretty long time to be initialized, that makes vue-component-meta impossible to add in a toolchain with HMR.

I'm not sure if this is a limitation of embedding a TS language server, what I would imagine is that any request to a file path metas would return the metas for the actual content of the file, and not a cached one.

**Comment by melishev** [comment]
ran into a similar problem.
when trying to integrate vue-component-meta into hmr applications, I get cached data, although the component itself has been updated
