### ISSUE TITLE
Update imports on file move not working in VSCode

### ISSUE THREAD

**Issue by HenryC-3** [johnsoncodehk/volar#1890]
## Env info

- volar: v0.40.13
- vscode: 1.71.2

## Steps to reproduce

>  codebase used below [HenryC-3/reproduce-volar\_update\_import\_dont\_work](https://github.com/HenryC-3/reproduce-volar_update_import_dont_work)

1. disable all extensions except volar
2. move `src/components/HelloWorld.vue` to `src/HelloWorld.vue`
3. checkout [App.vue](./src/App.vue), the import remain the same.

**Comment by johnsoncodehk** [comment]
Fixed in v1.0
