### ISSUE TITLE
vue-tsc: Add --onSuccess argument that runs command after every successful compilation triggered by --watch

### ISSUE THREAD

**Issue by lucadalli** [johnsoncodehk/volar#1891]
Similarly to  [tsc-watch](https://www.npmjs.com/package/tsc-watch), support an `--onSuccess COMMAND` argument that when paired with `--watch` runs a command on every successful compilation.
Useful when developing local packages with [yalc](https://www.npmjs.com/package/yalc) and need to run `yalc push` on every change.

**Comment by johnsoncodehk** [comment]
tsc-watch already support pass tsc path, you can try `tsc-watch --compiler vue-tsc/bin/vue-tsc.js`.
