### ISSUE TITLE
Iterating over a TS Class that implements Symbol.Iterator is not correctly inferred in the template, but works in script.

### ISSUE THREAD

**Issue by LinusBorg** [johnsoncodehk/volar#1892]
Volar Version: 0.40.13

Hi Johnson!

My issue kind of an edge case I came across in a client project. 

They use some classes that were auto-generated from some Javacode. One of these classes implements `[Symbol.Iterator]` 

They then loop over the class with `for ... of`. that works fine in the script block, but in the template, Volar generates a union type reflecting the classes methods - even though Vue's runtime uses Iterators/for ...of for v-for as well.  So it works fine a runtime, but infers a wrong type in the template

Example:
```html
<script setup lang="ts">
class Test<T> {
  [Symbol.iterator](): Iterator<T> {
    return {
      next(): IteratorResult<T> {
        return "" as unknown as IteratorResult<T>;
      },
    };
  }
  test(): "Hey!" {
    return "Hey!";
  }
}

const test = new Test<string>();
for (const t of test) {
  console.log(t); // this is typed correctly
}

</script>
<template>
  <!-- this types t as Test's prototype & instance properties -->
  <div v-for="t in test" :key="t"></div>
</template>
```

For the above code, `t` in the script's loop if inferred correctly as `string`:

<img width="368" alt="Bildschirmfoto 2022-09-21 um 18 20 30" src="https://user-images.githubusercontent.com/1444526/191558447-566e81b5-d44a-4f64-a7a3-7a64dc413bb0.png">

But in the template, the type is wrong, being a union of the Iterator function and the `test` function:

<img width="514" alt="Bildschirmfoto 2022-09-21 um 18 23 08" src="https://user-images.githubusercontent.com/1444526/191558681-f165d9af-8219-418b-8b84-689c0a83e3b6.png">

**Comment by johnsoncodehk** [comment]
Thanks for the report! You can try `v1.0.0-alpha.4` tomorrow for it.

**Comment by LinusBorg** [comment]
Wow, that was quick! :D Awesome!
