### ISSUE TITLE
Enabling TypeScript in Vue setup script causes weird import errors

### ISSUE THREAD

**Issue by jez9999** [johnsoncodehk/volar#1896]
When I enable TypeScript on my `.vue` setup script, it causes weird import errors:

![import errors](https://user-images.githubusercontent.com/793830/191803682-927b79d4-2191-4dfe-8925-55ff9cb64281.png)

They disappear when I remove the reference to `./tsconfig.app.json` in my base `tsconfig.json`:

```
	"references": [
		{
			"path": "./tsconfig.config.json"
		},
		{
			"path": "./tsconfig.app.json"
		}
	]
```

I have no idea why this would remove the errors.  It seems to be a bug in Volar.

The error happens when importing `.js` or `.ts` files into the Vue template, but not when importing other `.vue` files.

**Comment by johnsoncodehk** [comment]
Duplicate of #1344
