### ISSUE TITLE
[ERROR] Cannot find *.vue module and its type declarations

### ISSUE THREAD

**Issue by angelhdzmultimedia** [johnsoncodehk/volar#1897]
Volar was working like a charm last time I worked on a Vue 3 TypeScript Vite project.

Today, I created a project with create-vue (which uses Vite too, but provides more options),
and I'm getting this error when a *.ts file has focus:

![image](https://user-images.githubusercontent.com/10191085/191903855-5c4ca00b-a49c-43d3-a55a-c22cc7f70dcd.png)

Then, VSCode recommended me the TypeScript Volar extension, and I installed it, and the error went away,
but I'm now confused, didn't Volar already have TS support? Why do I need this other extension now?

Thanks.

**Comment by IIFelix** [comment]
did you install this one https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin ?

As far as i know if you want to support .ts files you have 2 options:
- install the typescript vue plugin extension as you did
- activate take over mode: https://github.com/johnsoncodehk/volar/discussions/471

Activating takeover mode is the recommended way i think so maybe you could switch to that option.
Hope this helps.

**Comment by angelhdzmultimedia** [comment]
Thank you to all the repliers.

Since I installed Volar extension, I haven't had any issues and I've been promoting it for Vue 3 + TypeScript.

Until 3 days ago that I used a create-vue project instead of a Vite one, that this issue started.

So something evidently change and I can't see what.

The fact that VSCode told me to install the TS Plugin says something.

So that's why I opened this issue. Not because I don't know who to set up Take Over Mode or those things.
Just I'm curious/confused what changed if I've been using only Volar for TS without issues.

Of course, I did the steps for Take Over Mode, and everything seems to be working now.

**Comment by angelhdzmultimedia** [comment]
Hello again.

Didn't want to saturate the issues section, so I will make my question here, that is directly related to this issue.

### New Question
That means that every time that I make a project, pure Vue TS, Nuxt TS, etc., we need to go to Extensions, filter by built-in, find the typescript & javascript extension, disable it for the workspace, reload the workspace?

**Comment by johnsoncodehk** [comment]
@angelhdzmultimedia Yes, Vue document has great explain for it: https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode

And you should also track https://github.com/microsoft/vscode/issues/40239

**Comment by unicornware** [comment]
@johnsoncodehk is there support for vscode insiders?

i installed both volar and the typescript vue plugin, but i'm still getting `Cannot find module` errors.

**Comment by johnsoncodehk** [comment]
@unicornware can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? Please provide repro case and open a new issue if it can't reproduce.

And how takeover mode crashes VSCode?

**Comment by stouch** [comment]
This helped me :

VSC + Volar setup : 

https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode (mentioned in issue : https://github.com/vuejs/language-tools/issues/1173)
