### ISSUE TITLE
Autocomplete and syntax highlight missing for recursive components

### ISSUE THREAD

**Issue by victorgarciaesgi** [johnsoncodehk/volar#190]
Hi and first of all thanks for this awesome extension. I'm just in a middle of a migration from Vetur.
I'm still using Vue 2 with `@nuxt/composition-api`, I installed `@vue/runtime-core` and everything is working great so far.
I noticed Volar can't recognize components calling themselves.

![image](https://user-images.githubusercontent.com/15092120/118727073-838f1500-b832-11eb-9f64-f86bd6b3263a.png)

Tell me if you need a minimal reproduction

**Comment by johnsoncodehk** [comment]
Support in 0.25.7, thanks for the report!

**Comment by johnsoncodehk** [comment]
> I installed @vue/runtime-core and everything is working great so far.

Please note we need `@vue/runtime-dom` for vue 2 but not `@vue/runtime-core`.

**Comment by victorgarciaesgi** [comment]
> > I installed @vue/runtime-core and everything is working great so far.
> 
> Please note we need `@vue/runtime-dom` for vue 2 but not `@vue/runtime-core`.

Ah it's was just a typo I have `@vue/runtime-dom` installed aha thanks!

**Comment by victorgarciaesgi** [comment]
@johnsoncodehk Type checking works great on 0.25.7!
But the component is still treated as `invalid` in Editor Tokens 
![image](https://user-images.githubusercontent.com/15092120/118783772-adc2f000-b88f-11eb-9dd8-342199392719.png)

**Comment by johnsoncodehk** [comment]
Recursive components semantic token works for me in this template: https://github.com/johnsoncodehk/volar-starter

<img width="397" alt="螢幕截圖 2021-05-19 下午4 56 57" src="https://user-images.githubusercontent.com/16279759/118785237-3eff8a00-b8c3-11eb-9a6f-c6b711b7b781.png">

Please provide a repro case if it's not works in your project.

**Comment by victorgarciaesgi** [comment]
Can't reproduce on the starter but I think it comes from me.

I have a nasty thing for declaring components in the `FormItem` (don't juge)

```ts
import * as Components from './forms/components'

export default defineComponent({
    components: { ...(Components as any) },
})
```

When I comment it out, the Editor scopes works well

Fixed it by doing
```ts
components: { ...(Components as Record<string, any>) },
```
