### ISSUE TITLE
Not formatting ts files

### ISSUE THREAD

**Issue by usama8800** [johnsoncodehk/volar#1903]
On the latest version `0.40.13` volar is not fomatting my ts files. I started downgrading one by one until it worked. On version `0.40.8` it tried to format but removed all formatting and all lines started on column 0. It works correctly on version `0.40.7`

**Comment by devhus** [comment]
Same issue here

**Comment by johnsoncodehk** [comment]
Can you provide LSP logs of formatting?

1. Config `"volar-document-features.trace.server": "verbose"` in VSCode settings.
   <img width="430" alt="螢幕截圖 2022-09-27 02 40 17" src="https://user-images.githubusercontent.com/16279759/192354995-c4220b92-caf7-4421-a08d-615fc13eed05.png">
2. Do formatting
3. Check "Volar - Document Features Server" logs on output window.
   <img width="669" alt="螢幕截圖 2022-09-27 02 41 46" src="https://user-images.githubusercontent.com/16279759/192355308-194adbe0-e6c8-4fca-944d-9c707965e291.png">

**Comment by johnsoncodehk** [comment]
It seems to be fixed by https://github.com/johnsoncodehk/volar/commit/da0de24281927d445ac585404d85116c878595df, you can use beta version for now: #1880
