### ISSUE TITLE
Prop type checks don't work for components using kebab-case

### ISSUE THREAD

**Issue by fanckush** [johnsoncodehk/volar#1909]
## Problem
simply put volar/ts doesn't complain about this when the component is defined using kebab-case:
![image](https://user-images.githubusercontent.com/6278713/192527925-43fc1108-403b-45f7-b6f9-46721a93bf7a.png)

but when using PascalCase it does complain about this (as it should)
![image](https://user-images.githubusercontent.com/6278713/192528008-ac46530b-1a15-43e3-9de3-b3de133ec8f6.png)

## Expected Behaviour
the prop `required` is of type `boolean | undefined` so I expect to see a squiggly line in **both** cases
![image](https://user-images.githubusercontent.com/6278713/192528295-48d920c0-0142-45d4-98d0-acf7141c91a2.png)

Is this a bug in Volar or is something wrong with my config?

**Comment by icepole-jon** [comment]
I have the same problem. Using camelCase for the properties of a component will not prompt an error, but there will be a problem with using kebab-case.
Change to camelCase and you will prompt Attribute': varName' must be hyphenated.eslintvue/attribute-hyphenation.
This problem will not occur until you upgrade to version 1.0. It is normal to return the old version.

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, could you provide repro case?

**Comment by saifahn** [comment]
I've run into something similar:

- If the tag for the component in the template is not exactly the same as a component defined in the `components` field of `defineComponent` options, it will give a type of `unknown` when hovering on it. An incorrect prop type will not be highlighted.
  - If it is the same, it will show the proper type and give a proper warning when the prop type does not match.
  - A couple of examples below using badge and Badge.

![Screen Shot 2022-10-13 at 13 29 56](https://user-images.githubusercontent.com/9913851/195501896-f66799fe-f032-4042-9a8c-3ba8ad9ab020.png)

![Screen Shot 2022-10-13 at 13 29 02](https://user-images.githubusercontent.com/9913851/195501888-ae3e05d6-e7f7-4d2d-9477-76404c396fd7.png)

- Using the example from the top post, if we import `DateRangePicker` and define the component as `DateRangePicker` in defineComponent, then it must be used as `<DateRangePicker>` in the template for proper type information. We can also define it as `'date-range-picker': DateRangePicker` in the components field to allow us to use `<date-range-picker>`

I reverted my version of volar to 0.40.13, where I do not run into this issue. I tried 1.0.0, 1.0.5, and 1.0.7 and ran into the issue.

**Comment by johnsoncodehk** [comment]
I tried in https://github.com/johnsoncodehk/volar-starter but can't reproduce, if you have repro case please provide and I will reopen this issue.
<img width="199" alt="image" src="https://user-images.githubusercontent.com/16279759/196306657-a4cae979-c7d1-4074-8596-cb9fc1c1e97e.png">

**Comment by fanckush** [comment]
@johnsoncodehk Maybe it's not a bug but some wrong configuration. In other projects it works just fine, given that it's a big production project I can't tell exactly why it's happening. I was wondering if there is anything setting or config that can cause such behaviour that you are aware of. If not i'll try to detect a pattern and report here

**Comment by johnsoncodehk** [comment]
@fanckush Can you try these screenshots?

1. Hover `<date-range-picker>`
2. Hover `<DateRangePicker>`
3. Right click `<date-range-picker>` -> Peek Definition
4. Right click `<DateRangePicker>` -> Peek Definition

And please provide your vue version and vueCompilerOptions setting.

Also helpful if @saifahn can fill these information.
