### ISSUE TITLE
PostCSS syntax highlighting is broken since v0.25.5

### ISSUE THREAD

**Issue by sto3psl** [johnsoncodehk/volar#191]
I noticed that since version 0.25.5 of Volar, the syntax highlighting of `<style lang="postcss"></style>` blocks is broken and doesn't highlight anything anymore.

When I remove `lang="postcss"` the highlighting works again (I assume because the block is now considered normal CSS), but now I get linting errors from Stylelint (because it assumes normal CSS).

I noticed in the changelog that you made a bunch of changes with language support, maybe that's why it broke for PostCSS.

<table>
<tr>
	<td>v0.25.4
	<td>v0.25.7
<tr>
	<td>

![0 25 4](https://user-images.githubusercontent.com/5798652/118764668-2c149780-b87a-11eb-85fc-d70df5ae8885.png)

</td>
	<td>

![0 25 7](https://user-images.githubusercontent.com/5798652/118764683-33d43c00-b87a-11eb-8a81-21a732eff0ed.png)

</td></tr>

</table>

**Comment by johnsoncodehk** [comment]
You need to install additional extension for postcss syntax highlighting if you have not, because vscode do not built-in support postcss syntax highlighting, see https://github.com/johnsoncodehk/volar#note.

If you don't, in version 0.25.4 it's show incorrect syntax highlighting and it's bug.

**Comment by sto3psl** [comment]
I know and have [`csstools.postcss`](https://github.com/csstools/postcss-language) installed. Since it's the first search result and has pretty big usage, I thought it would work.

Do you recommend another one?

**Comment by sto3psl** [comment]
I tried out `ricard.postcss` and `cpylua.language-postcss` just now. Only `cpylua.language-postcss` seems to work but it isn't maintained anymore. Maybe it keeps working but no idea why the other ones work fine with everything except `.vue` files.

**Comment by johnsoncodehk** [comment]
I'm not sure why, it seems to be related to this issue https://github.com/csstools/postcss-language/issues/6.

**Comment by christhofer** [comment]
I'm swithing to Volar, and notice this issue too.

But when I try `lang="pcss"`, it seems to be working just fine.

![image](https://user-images.githubusercontent.com/13524958/131963650-2ed485b0-00d8-4bf2-b0e9-993d48a386af.png)

I don't know if there's any side effect using `lang="pcss"`instead of  `lang="postcss"`
My program seems to be working fine in `npm run dev`

**Comment by johnsoncodehk** [comment]
@christhofer `<style lang="pcss">` just rollback to `<style>`, so it's syntax highlighting of `lang="css"`.

**Comment by christhofer** [comment]
@johnsoncodehk 
Seems to be different though
I got error with `@apply` using `lang="css"`

![image](https://user-images.githubusercontent.com/13524958/131970748-11b0cb67-3472-43f8-bf6d-582adbc9319e.png)

**Comment by johnsoncodehk** [comment]
Syntax highlighting and language support is deal with separately.

`<style>` = css syntax highlighting + css language support
`<style lang="postcss">` = postcss syntax highlighting + postcss language support
`<style lang="pcss">` = css syntax highlighting + unknown style language support (no any supports)

**Comment by xymopen** [comment]
Sorry for bring up this thread. The reason for this seems to be that `csstools.postcss` uses `source.css` instead of `source.postcss` (which is used by `vue.volar`) as scope for PostCSS grammar.

**Comment by johnsoncodehk** [comment]
@xymopen Can you just remove `lang="postcss"` to resolve?

**Comment by xymopen** [comment]
> @xymopen Can you remove `lang="postcss"` to resolve?

Yes. Using `<style>` alone does bring tokens defined by `csstools.postcss`. However CSS Language Server is not happy about that.

**Comment by johnsoncodehk** [comment]
@xymopen Please try setting vscode `css.lint.*` it may helps.

**Comment by me-vlad-k** [comment]
I still have the same problem in November 2024. In a Vue file with lang="postcss", everything is shown in plain white.

**Comment by WesleySmits** [comment]
Just to keep this thread active, i still have this in 2025 same as @me-vlad-k. Are there any solutions or fixes for this?

**Comment by joakimc** [comment]
Using either [language-postcss](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss) or [Vue 3 Support - All In One](https://marketplace.visualstudio.com/items?itemName=Wscats.vue) solved the issue for us.
