### ISSUE TITLE
Using the pug language server without vue

### ISSUE THREAD

**Issue by gioragutt** [johnsoncodehk/volar#1911]
Can the pug language server be used without vue?

We're using pug and currently the built-in language server for pug in vscode is pretty shitty, and I'd love to get my team and I some better experience when working with pug.

**Comment by gioragutt** [comment]
ping

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, it's not in the plan, but I'll see if there is an easy solution after the 1.0.x stable release is done.

**Comment by johnsoncodehk** [comment]
Please try https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-pug.

**Comment by zaxlct** [comment]
> Please try https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-pug.

Thank you, thank you very much, this problem is killing me, this plugin, saved my life
