### ISSUE TITLE
vue-tsc - Type 'X' is not assignable to type 'never'

### ISSUE THREAD

**Issue by prof-schnitzel** [johnsoncodehk/volar#1919]
With version `1.0.0-beta.2` of vue-tsc I get the error `Type 'X' is not assignable to type 'never'` almost everywhere, for example:
```
<template>
   <transition
     name="button--animating"
   >
   ...
  </transition>
</template>
``` 
Here I am getting the error `Type 'string' is not assignable to type 'never'` for attribute `name`.

Or another example
```
<template>
<button
    :class="{
      'highlighted': buttonType.startsWith('highlight')
    }"
/>
</template>
<script lang="ts">
export default defineComponent({
    props: {
        buttonType: {
            type: String
        }
    }
})
</script>
```
I get the error `Property 'startsWith' does not exist on type 'never'`.

I am using version 1.0.0-beta.2 because with version 0.40.13 I am getting the error `JSX element type 'X' does not have any construct or call signatures` for all my custom components.

**Comment by johnsoncodehk** [comment]
Could you try can this problem  reproduce in https://github.com/johnsoncodehk/volar-starter?

**Comment by prof-schnitzel** [comment]
@johnsoncodehk In the meantime I found out that the problem occured because I had a mixin which was not migrated to typescript yet. The mixin provided some props that are needed for the component to work. But does that really matter? Shouldn't the typescript compiler still work correctly regardless of files that still use the js extension and are not migrated to typescript yet?

**Comment by johnsoncodehk** [comment]
I don't know because I have no experience with `mixin`, but I guess you can ignore mixin type by `mixin(...) as {}` to `mixin(...) as never`.
