### ISSUE TITLE
Vue 2.7.x - "props" not working when using object syntax

### ISSUE THREAD

**Issue by ludwig801** [johnsoncodehk/volar#1924]
### Issue

Using vue 2.7 in a project and a simple definition such as below:

```javascript
export default {
  data() {
    return {
      name: "Adam",
    };
  },
  props: {
    id: {
      type: String,
    },
  },
  computed: {
    fullName() {
      // vvv - Typing "this." correctly assumes "name" is a string, but "id" is not even recognized as a property
      return `${this.name} ${this.id}`; 
    }
  },
}
```

As said in the example above, typing **this.** anywhere inside a method, computed or hook function properly suggests **name**, but **id** does not even appear. When written, says **id** is of type **any**, and does not even recognize it as a valid property for the instance.

### Environment

- VSCode: v1.71 (latest)
- Typescript: v1.7.3 / v.1.8.3 (reproducible in both)
- Volar: v0.40.13 (latest)
- Vue: v2.7.10 (latest 2.7.x)

**Comment by ludwig801** [comment]
Adding to this bug: having tried this with the latest Volar extension version (1.0.2), the bug only seems to appear when I had a data() function to the definition.

So:

This works fine, both "id" and "fullName" are recognized.
```javascript
export default {
  props: {
    id: {
      type: String,
    },
  },
  computed: {
    fullName() {
      // vvv - Typing "this." correctly assumes "id" is a string
      return `Adam ${this.id}`; 
    }
  },
}
```

This doesn't work. "name" is recognized, but both "id" and "fullName" are not.
```javascript
export default {
  data() {
    return {
      name: "Adam",
    };
  },
  props: {
    id: {
      type: String,
    },
  },
  computed: {
    fullName() {
      // vvv - Typing "this." correctly assumes "name" is a string, but "id" is not even recognized as a property
      return `${this.name} ${this.id}`; 
    }
  },
}
```

**Comment by johnsoncodehk** [comment]
I think this is `defineComponent` type issue of 2.7, you can try this code in .ts without use Volar.

```ts
// test.ts
import { defineComponent } from 'vue'

export default defineComponent({
  data() {
    return {
      name: "Adam",
    };
  },
  props: {
    id: {
      type: String,
    },
  },
  computed: {
    fullName() {
      // vvv - Typing "this." correctly assumes "name" is a string, but "id" is not even recognized as a property
      return `${this.name} ${this.id}`; 
    }
  }
})
```

**Comment by ludwig801** [comment]
> I think this is `defineComponent` type issue of 2.7, you can try this code in .ts without use Volar.
> 
> ```ts
> // test.ts
> import { defineComponent } from 'vue'
> 
> export default defineComponent({
>   data() {
>     return {
>       name: "Adam",
>     };
>   },
>   props: {
>     id: {
>       type: String,
>     },
>   },
>   computed: {
>     fullName() {
>       // vvv - Typing "this." correctly assumes "name" is a string, but "id" is not even recognized as a property
>       return `${this.name} ${this.id}`; 
>     }
>   }
> })
> ```

I've tried this, and it does not work.
Somehow, adding **data** and **methods** to the same definition breaks the definition and methods is not parsed at all.

**Comment by johnsoncodehk** [comment]
@ludwig801 yes I mean this is vue 2.7 `defineComponent` type issue, so it can't work in .ts without using volar, you can report a issue for vue.
