### ISSUE TITLE
Nullable ref access is not unwrapped in template

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#1926]
I'm using Volar **version 1.0.0-beta.6**

First-level refs are unwrapped automatically in templates, but this doesn't happen with nullable variables (presumably a problem with any union type?).

Repro:
```vue
<script setup lang="ts">
  import { ref } from "vue";
  const x = Math.random() > 0.5 ? ref("abc") : null;
</script>

<template>
  {{ x?.length }}
  ^ Property 'length' does not exist on type 'Ref<string>'
</template>
```

This works at runtime since: 
If `x` is a Ref instance, the compiled template unwraps it, then proceeds to do `"abc"?.length`.
If `x` is null, then it goes through the unwrap and becomes `null?.length` -> `undefined`, which is ok.

Seems to me that when a variable is a union type, e.g. here `x: Ref<string> | null`, then in template each type in union should be unwrapped, so `x` becomes `Unwrap<Ref<string> | null>` -> `string | null`; then above example would be fine.

**Comment by johnsoncodehk** [comment]
This is vue types problem and I remember that upstream has a issue about it, but I can't find it out yet.

**Comment by johnsoncodehk** [comment]
Here it is 😅: https://github.com/vuejs/core/issues/3990
