### ISSUE TITLE
tsx type inference error

### ISSUE THREAD

**Issue by Luooooooo** [johnsoncodehk/volar#193]
```.vue
<script lang="tsx">
...
   my_cesium = initCesiumViewer('cesium-map-comprehensive');
            my_cesium.openScene().then(() => {
                my_cesium.setSceneQueryParameter();
                //设置属性查询参数
                my_cesium.pickEvent.addEventListener(function(feature) {
                    showPipe3DPropsModal(feature);
                });
            });
...
</script>
```
```tsx
...
            cesium_map = initCesiumViewer('cesium-map-comprehensive1');
            cesium_map.openScene().then(() => {
                cesium_map.setSceneQueryParameter();
                //设置属性查询参数
                cesium_map.pickEvent.addEventListener(function(feature) {
                    showPipe3DPropsModal(feature);
                });
            });
...
```
Type inference is error. there is two `.d.ts`(two namespace Cesium)。

![image](https://user-images.githubusercontent.com/29565303/118925682-affd7b00-b971-11eb-80aa-0c296b0cfede.png)
![image](https://user-images.githubusercontent.com/29565303/118926146-70835e80-b972-11eb-8942-6edb8c3c0830.png)

**Comment by johnsoncodehk** [comment]
What error you have?

**Comment by Luooooooo** [comment]
Type inference cannot be done correctly in `.vue` files

**Comment by johnsoncodehk** [comment]
Please post the error message.

**Comment by Luooooooo** [comment]
It's in the same environment

**Comment by johnsoncodehk** [comment]
I mean what is the error message from the red line? <img width="85" alt="螢幕截圖 2021-05-20 下午3 37 52" src="https://user-images.githubusercontent.com/16279759/118938542-5bfa9280-b981-11eb-8c0a-473ab6512afa.png">

Please try to provide more information or a minimal reproduction, I can't guess your problem.

**Comment by Luooooooo** [comment]
emmm,Property 'pickEvent' does not exist on type 'MyCesiumViewer' ts(2339)
![image](https://user-images.githubusercontent.com/29565303/118939260-112d4a80-b982-11eb-95f4-8eb84a1bc223.png)

**Comment by Luooooooo** [comment]
MyCesiumViewer
![image](https://user-images.githubusercontent.com/29565303/118939376-315d0980-b982-11eb-85ba-ae1c63fd2def.png)

**Comment by johnsoncodehk** [comment]
I can't repro, I think this problem is related to your project config, please try to make a minimal reproduction by https://github.com/johnsoncodehk/volar-starter.
