### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by zwfengineer** [johnsoncodehk/volar#1930]
when i use Vue Language Features (Volar) plugin,vscode will have two identical code hints
should be one code hints

![image](https://user-images.githubusercontent.com/33892516/194042812-0e33e4bb-794a-4582-a450-c3ebd1738b12.png)

**Comment by zwfengineer** [comment]
vscode version August 2022 (version 1.71)

**Comment by zwfengineer** [comment]
volar version v0.40.13

**Comment by johnsoncodehk** [comment]
Duplicate of #1852
