### ISSUE TITLE
Feature: Custom file extensions other than .vue

### ISSUE THREAD

**Issue by cabal95** [johnsoncodehk/volar#1931]
We are looking to be able to use custom file extensions with Vue to differentiate some of our components between other components we have. Our compiler chain works fine with custom file extensions other than `.vue`, but the Volar extension has a few places where this is hard coded. I did a quick test and dropped in our custom extensions in a couple places and everything seems to work.

Would you be open to a pull request that adds a new configuration setting that would pass along these custom file extensions to the underlying services?

This would just be to make Volar's internals treat these other file extensions the same as if they were `.vue`. It would not automatically add file associations (unless I can find a way to do that dynamically instead of in package.json) - but VS Code already has support for that.

**Comment by johnsoncodehk** [comment]
Please feel free to open a PR. :) (If you don't mind I will modify it directly.)

**Comment by cabal95** [comment]
Implemented by #2035
