### ISSUE TITLE
Receiving error "Vue Semantic Server client: couldn't create connection to server." since upgrading to 1.0.0

### ISSUE THREAD

**Issue by alan-strickland-red** [johnsoncodehk/volar#1942]
Hi,

Since VSC upgraded to Volar to 1.0.0 automatically this afternoon I am getting errors when loading .vue files.

![image](https://user-images.githubusercontent.com/103668835/194589177-b4dc4f65-6b30-4af9-8293-e39a4cec98c5.png)

The output window for the Vue Semantic Server shows the following errors repeatedly:

```
[Error - 16:15:48] Server initialization failed.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
  Code: -32603 
[Error - 16:15:48] Vue Semantic Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
  Code: -32603 
[Info  - 16:15:50] Connection to server got closed. Server will restart.
```

The output window for the Vue Syntactic Server shows the following errors repeatedly:

```
[Error - 16:15:48] Server initialization failed.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
  Code: -32603 
[Error - 16:15:48] Vue Syntactic Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
  Code: -32603 
[Info  - 16:15:50] Connection to server got closed. Server will restart.
```

I have downgraded to Volar 0.4 and that has resolved the issue for the time being.

**Comment by johnsoncodehk** [comment]
It seems a same problem: https://github.com/johnsoncodehk/volar/issues/1880#issuecomment-1266312500

But I don't know how it resolve, can you try reinstall extension and restart vscode?

**Comment by alan-strickland-red** [comment]
I have tried re-installing it and restarting vscode and even restarting the machine.

My colleague and I have the same setup and his is working with the latest extendion so I enabled the verbose logging you mentioned on the other thread and compared it between the two environments, the only difference is in the typescript  initializationOptions where the tsdk path on mine is pointing at the workspace and his is posing at the global install.

## Working

```
    "initializationOptions": {
        "serverMode": 0,
        "diagnosticModel": 1,
        "textDocumentSync": 2,
        "typescript": {
            "tsdk": "c:\\Users\\*******\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib",
            "isWorkspacePath": false
        },
        "petiteVue": {
            "processHtmlFile": false
        },
        "vitePress": {
            "processMdFile": false
        },
        "cancellationPipeName": "C:\\Users\\******L\\AppData\\Local\\Temp\\vscode-Vue.volar-cancellation-pipe.tmp"
    },
```

## Failing

```
    "initializationOptions": {
        "serverMode": 0,
        "diagnosticModel": 1,
        "textDocumentSync": 2,
        "typescript": {
            "tsdk": "d:\\******\\******\\******",
            "isWorkspacePath": true
        },
        "petiteVue": {
            "processHtmlFile": false
        },
        "vitePress": {
            "processMdFile": false
        },
        "cancellationPipeName": "C:\\Users\\*******\\AppData\\Local\\Temp\\vscode-Vue.volar-cancellation-pipe.tmp"
    },
```

**Comment by johnsoncodehk** [comment]
@rchl please try update `initializationOptions` (See #1916):
```diff
"initializationOptions": {
-    "documentFeatures": {
-      "documentColor": true,
-      "documentFormatting": {
-        "defaultPrintWidth": 90
-      },
-      "documentSymbol": true,
-      "foldingRange": true,
-      "linkedEditingRange": false,
-      "selectionRange": true
-    },
-    "languageFeatures": {
-      "callHierarchy": false,
-      "codeAction": true,
-      "codeLens": {
-        "showReferencesNotification": true
-      },
-      "completion": {
-        "defaultAttrNameCase": "kebabCase",
-        "defaultTagNameCase": "both",
-        "getDocumentNameCasesRequest": false,
-        "getDocumentSelectionRequest": false,
-        "ignoreTriggerCharacters": ""
-      },
-      "definition": true,
-      "diagnostics": true,
-      "documentHighlight": true,
-      "documentLink": true,
-      "hover": true,
-      "implementation": true,
-      "inlayHints": true,
-      "references": true,
-      "rename": true,
-      "renameFileRefactoring": false,
-      "schemaRequestService": false,
-      "semanticTokens": true,
-      "signatureHelp": true,
-      "typeDefinition": true,
-      "workspaceSymbol": true
-    },
+    "ignoreTriggerCharacters": ""
    "textDocumentSync": 2,
    "typescript": {
-      "serverPath": "/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.15.0/server/node_modules/typescript/lib/tsserverlibrary.js"
+      "tsdk": "/Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-volar/16.15.0/server/node_modules/typescript/lib"
    }
  }
```

**Comment by rchl** [comment]
> @rchl please try update `initializationOptions` (See #1916):

That helped. Thanks.

**Comment by rchl** [comment]
> Failing

In my case above it was about the path pointing to a file rather than the `lib` dir. You've masked yours in the failing case so hard to tell whether it's the same issue.

Also I guess make sure that the directory and files within it do exist.

**Comment by johnsoncodehk** [comment]
@alan-strickland-red I just found a way to reproduce it under specific conditions, please wait for v1.0.1.

**Comment by johnsoncodehk** [comment]
@alan-strickland-red You can try to change to VSCode Version tsdk in status bar to avoid this problem for now.

**Comment by alan-strickland-red** [comment]
@johnsoncodehk That's fixed it. I changed to "Use Workspace Version 4.8.4", note of interest switching back to "Use VC Code's  Version" also works.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/103668835/194599707-a6565e0f-7d60-4fe4-87fe-cc9aeebfacd5.png">

**Comment by carlos00027** [comment]
+1

**Comment by carlos00027** [comment]
I installed the previous version of fly and it worked for me. as a temporary solution.

**Comment by dai-oh** [comment]
Sorry to bother you all, but this problem has prevented me from using vscode to write vue projects, and using the above method has not solved the error and plugin failure.

**Comment by www-wanglong** [comment]
+1

**Comment by dev-bazz** [comment]
Same problem, downgrading the plugin worked

**Comment by jeppeerixon** [comment]
Just started showing up for me aswell.

**Comment by tw-luo** [comment]
> Same problem, downgrading the plugin worked

May I know which version you have downgraded to?

**Comment by tw-luo** [comment]
> > Same problem, downgrading the plugin worked
> 
> May I know which version you have downgraded to?

I downgraded to version 1.4.0 ,it can run normally

**Comment by MartinsOnuoha** [comment]
Same problem, I think this must have happened with an update as it only started yesterday

**Comment by GaoJuqian** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/50407511/233815026-3419f006-b363-47c4-924c-a80ef7dc1282.png">

**Comment by johnsoncodehk** [comment]
Please update your extension to v1.4.3 or later, and please don't reply on an obsolete issue.

**Comment by MartinsOnuoha** [comment]
> Please update your extension to v1.4.3 or later, and please don't reply on an obsolete issue.

@johnsoncodehk Thanks, I see this is resolved in `v1.4.3`. 
I wouldn't call it "replying to an obsolete issue" since this was happening as of v1.4.2 and `x.x.3` was only published 11 hours ago 🙂. Thanks

**Comment by GaoJuqian** [comment]
👍

**Comment by johnsoncodehk** [comment]
I mean this issue (#1942) is obsolete, it has nothing to do with the problem with the new version.

**Comment by MartinsOnuoha** [comment]
I agree, unfortunately, it happened to be the only related issue with the most engagement and most recent comment. Thanks again.
