### ISSUE TITLE
Text color is disordered 1.0.0

### ISSUE THREAD

**Issue by message163** [johnsoncodehk/volar#1946]
![C)%G}HXZ`V%{$@`SV@PRGY6](https://user-images.githubusercontent.com/32630999/194671325-c8e3d700-4e00-4077-91c9-b17d59b5abca.jpg)

TypeScript Vue Plugin volar 1.0.0 

Starting this extension will change the text color to disorder in VsCode

0.40.13 version is normal

**Comment by gustavotoyota** [comment]
Same problem here:
![image](https://user-images.githubusercontent.com/11639451/194679287-8f751aa7-e286-4233-a448-afda202cfeff.png)
Intellisense also becomes unusable.

**Comment by xudongdong40** [comment]
the same to me

**Comment by CyanSalt** [comment]
The same +1

**Comment by xieqx1991** [comment]
The same +1

**Comment by weifeiyue** [comment]
The same +1

**Comment by weifeiyue** [comment]
The same +1

**Comment by weifeiyue** [comment]
The same +1

**Comment by JiaranYa** [comment]
The same +1

**Comment by meesii** [comment]
The same +1

**Comment by MaximFedarau** [comment]
Update to 1.0.1 does not solve the problem either.

**Comment by gustavotoyota** [comment]
Updating to 1.0.2 solved the issue for me

**Comment by SD-Gaming** [comment]
And I found a new issue, 

when I open change to compare the old code with the new code in .vue file, the code color is also disordered.

![20221009093951](https://user-images.githubusercontent.com/25575589/194733688-e052028c-f313-4853-a99d-a81d608bc256.png)

**Comment by gustavotoyota** [comment]
Interesting. It only seems to happen on the old code:
![Screenshot from 2022-10-08 21-50-18](https://user-images.githubusercontent.com/11639451/194733902-3bec3bc8-8c20-455e-9151-3de00c95db95.png)

**Comment by stefnotch** [comment]
@SD-Gaming @gustavotoyota Could you open a new issue for that?

**Comment by johnsoncodehk** [comment]
> Interesting. It only seems to happen on the old code: ![Screenshot from 2022-10-08 21-50-18](https://user-images.githubusercontent.com/11639451/194733902-3bec3bc8-8c20-455e-9151-3de00c95db95.png)

This is [v0.40.6](https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0406-202294) bug, fix by https://github.com/johnsoncodehk/volar/commit/77ce7e6bb180258718e0a0676cc93366bf0d0bbc.
