### ISSUE TITLE
The color of the component tag disappears

### ISSUE THREAD

**Issue by liweiook** [johnsoncodehk/volar#1947]
Vue version:2.6.12
if    vueCompilerOptions.target:2

![image](https://user-images.githubusercontent.com/42706756/194682642-5182820d-6579-4751-82a3-5c16c4ce32f5.png)

if   no  vueCompilerOptions.target:2,its has color,but error.

![image](https://user-images.githubusercontent.com/42706756/194682724-31e3072c-7958-434c-ac68-145c495d2d02.png)

i  want  the color  of  the component tag in vue2,how to get it?

**Comment by xiaoxiangmoe** [comment]
Please provide a reproducible demo repo.

**Comment by liweiook** [comment]
![Snipaste_2022-10-24_10-24-46](https://user-images.githubusercontent.com/42706756/197437494-94b08123-b1e0-4f84-9cbe-cfa440d7a1ac.png)
The component color changed after volar was updated to version 1.0.9.Not as clear as before

**Comment by liweiook** [comment]
![image](https://user-images.githubusercontent.com/42706756/197438914-8346d01e-5486-443d-a07f-9410fb4d2287.png)
the component color of react that used same theme extensions,when volar was 1.0.8,this also green. the theme extensions not updated.

**Comment by liweiook** [comment]
![image](https://user-images.githubusercontent.com/42706756/197442104-75c97b61-fb02-49ef-a4d6-aa20b8738eac.png)
iI lowered the version to 1.0.8,it is green.
