### ISSUE TITLE
Components with native DOM events type check error since upgrading to 1.0.0

### ISSUE THREAD

**Issue by Sc-6-23** [johnsoncodehk/volar#1948]
Components with native DOM events(like input, change) volar(v1.0.0) type check error 
Type '(value: string)=>void' cannot be assigned to type '(payload: Event)=>void'. The types of parameters' value 'and' payload 'are incompatible.

**Comment by kevinzhao2233** [comment]
I also met.

**Comment by Yu-chuancheng** [comment]
俺也一样

**Comment by icepole-jon** [comment]
+1

```vue
  <van-nav-bar
    :title="title"
    :left-arrow="showBack"
    left-text="返回"
    style="--van-nav-bar-z-index: 99"
    fixed
    placeholder
    @click-left="onBack"
    @click-right="onExport"
  />
```

`placeholder` has ts error HTMLAttributes.placeholder?: undefined

**Comment by liubaicai** [comment]
俺也一样

**Comment by kevinzhao2233** [comment]
There will still be type errors after trying many methods, such as deleting node_modules and lock file, reinstalling depends, and upgrading vue-tsc.
I finally rolled back volar and vue-tsc, deleted node_modules and lock file and reinstalled depends. That is to say, it can't be used normally until it is completely rolled back to the previous version.

**Comment by weifeiyue** [comment]
The same +1

**Comment by weifeiyue** [comment]
tsconfig.json里面，设置了"types": ["miniprogram-api-typings"],直接导致typescript推导全部失效了

**Comment by weifeiyue** [comment]
> There will still be type errors after trying many methods, such as deleting node_modules and lock file, reinstalling depends, and upgrading vue-tsc. I finally rolled back volar and vue-tsc, deleted node_modules and lock file and reinstalled depends. That is to say, it can't be used normally until it is completely rolled back to the previous version.

The same +1

**Comment by weifeiyue** [comment]
The same +1

**Comment by weifeiyue** [comment]
everythings is broken down

**Comment by mosaicmask** [comment]
My question is：
@click绑定事件后会报错：不能将类型“($event: any) => void”分配给类型“MouseEvent”。ts(2322)
The error disappears after disabling the Volar plugin
<img width="583" alt="image" src="https://user-images.githubusercontent.com/65692329/194705882-d5d89498-4eec-44c0-aba8-1c8c26543945.png">
Let's see if it's my problem

**Comment by lesonky** [comment]
There will still be type errors in code-insiders

**Comment by fy5220** [comment]
same issue
