### ISSUE TITLE
Unable to infer component prop generic type from value in v1.0.0

### ISSUE THREAD

**Issue by colinj** [johnsoncodehk/volar#1949]
When using Volar 0.40.13, I was able to define Vue 3 component with generic props. When I hovered over the property in the template it would show me the inferred type of the property based on the type of the variable used.

Under Volar 1.0.0, this no longer works and instead the prop is shown as `unknown`.

Below is how I have defined the non-generic component and its generic counterpart.

```vue
// MySelectBase.vue

<script setup lang="ts">
interface Props {
  modelValue: unknown;
  options: unknown[];
  label: (option: unknown) => string;
}
defineProps<{Props}>();
const emit = defineEmits<{
  (e: "update:modelValue", v: unknown): void;
}>();

// implementation code...
</script>

```
```vue
// MySelect.vue

<script lang="ts">
import MySelectBase from "./MySelectBase.vue";

interface Props<T> {
  options: T[];
  label: (option: T) => string;
}

type MySelect = new <T = string>(props: Props<T>) => {
  $props: Props<T>;
  $emit: {
    (e: "update:modelValue", v: T): void;
  };
};

export default MySelectBase as MySelect;
</script>
```

```vue
/// App.vue

<script setup lang="ts">
import MySelect from "./MySelect.vue";

interface Person {
  name: string;
  age: number;
}

const people = ref<Person[]>([
  { name: "John", age: 24 },
  { name: "Peter", age: 37 }
]);
const showLabel = (val: Person) => `${val.name} - ${val.age}`;
const person = ref<Person>();
</script>

<template>
  <MySelect v-model="person" :options="people" :label="showLabel" />
</template>
```
When I hovered over the `options` prop in the \<template\> it would display `MySelect<Person>.options: Person[]` under Volar 0.40.13.
With Volar 1.0.0 it shows `MySelect<unknown>.options: unknown[]`. Also VS Code displays the wriggly red line since the type `Person` doesn't match `unknown`.

This approach was inspired from this comment https://github.com/vuejs/core/issues/3102#issuecomment-1193084906 in the Vue repo so I really don't know if this approach is actually supported by Volar or was just a hack. In any case, it worked in the previous version but unfortunately not in v1.0.0.

[Example code - Vue SFC Playground](https://sfc.vuejs.org/#eNqVlG1r2zAQx7/KYQp1ILHZAww8J2ODvRkbFBb2pirUjS+JW1sSkpy0ZP7uO51spw9ZoW+MdTr/76+7n3yIvmqd7FqMsii3K1NpBxZdq6Eu5GYuImdFtBCyarQyDg5gcA0drI1q4Jw+Ox+3fj38xhpXLuyJKEmHiJcX0WchKVc6NOtihXCBxioJByEBZNFgBtaZSm4oDaDY0Fq2zQ0aWnc+JORKSetAo9I1wtwbyYPI5dUivvQ5h15JRD/UVopoGoTef4Ru+nT/AsnHmPDhE1CNqwnXHgrZrdr/LG6wplrxrqiz3vIE5gu4PjtQKPFyHcwgrEiruyaNwSgfkI3GVLHGwiL1lntU9NsiGormaeg+9ZoWDhtdFw5pBZBv3y0Oh0Gw6/KUArxRVjuf7+h1bP9u1qgSaxrdUAIypV1Fpjjm2+djtT8bRcZzUjANsmnQzdPRRjSNwphnTaGTW5IlXnh2ot8gTLIwTR/jiftGb53TNktTu155DG5toswmpbfEtNJVDSZom9mNUXuLhoRF5CVoGh2VHM70jTr3FkZXqtGtw3IAtffznECjtA2WuWN/irrFL0847PuWQSvvpNoTaRzm1mUQ0/a4xViMnz5FlgvNocR1JZHL5vxcxH76IQmbyo0532lhc7YWM6+tLmkM2dGnZ3c3eJ1ksFNV6esGyWPtSlIn6AuSHroSs+4GXTzh++xaI4PH5KgfLgx12aPv87w/wvi0EZ/iZ8a1X2FZuLy/AEdKB4c8Qk9PHrpOKWtlKCGuSGEKVXk/oeP0TvvJeJDv8MHLlPejgnD+unAej4oVyCFPxfMdvu5hD45e8P747/UIvJPIPQb15f9vwPc0gfly8V8I4W//0oM38rg8ReLyJIPuQePx5zwHiXvIl/QSEhcxN4r+br0ZFmFDZ892uOKZB2G86W+jky6299UDivfcOyK+aOtnPSzsuKbskaeo+wd3bkqR)

**Comment by johnsoncodehk** [comment]
After v1.0 you need to define `"jsxTemplates": true` for generic type component, see https://github.com/johnsoncodehk/volar/discussions/592#discussioncomment-3660903.

**Comment by colinj** [comment]
Thank you @johnsoncodehk for your quick response! That did the trick!
