### ISSUE TITLE
The Vue Language Features (Volar) version is 1.0.0, but workspace vue-tsc version is 0.29.8, there may have different type checking behavior.

### ISSUE THREAD

**Issue by qhl123456** [johnsoncodehk/volar#1950]
这个报错了后导致文件中出现了很多报错，并且有文件未找到
![Uploading image.png…]()

**Comment by wgxg777** [comment]
一样的问题

**Comment by Jiangmenghao** [comment]
我也遇到了

**Comment by johnsoncodehk** [comment]
You can update `vue-tsc` or setting `"volar.doctor.statusBarItem": false` to disable doctor.

**Comment by qhl123456** [comment]
It works thanks


www.1092750452
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnsoncodehk/volar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnsoncodehk/volar] The Vue Language Features (Volar) version is 1.0.0, but workspace vue-tsc version is 0.29.8, there may have different type checking behavior. (Issue #1950)





 
You can update vue-tsc or setting "volar.doctor.statusBarItem": false to disable doctor.

**Comment by bestime** [comment]
> You can update `vue-tsc` or setting `"volar.doctor.statusBarItem": false` to disable doctor.

不能使用当前项目的版本吗，vue-tsc一天更新好几个版本...
