### ISSUE TITLE
Unable to refer component prop type in v1.0.0

### ISSUE THREAD

**Issue by TommyCat008** [johnsoncodehk/volar#1951]
When I upgraded to version 1.0.0, the UI components used in my code showed type inference errors, as shown below：

![08c77b638c1595345b4a975d3595648e](https://user-images.githubusercontent.com/16837203/194694956-37f77e9b-02df-42f7-ada7-4fe9548358ef.png)

When I clicked to see the component type reference, I found that it was inferred to runtime.d.ts in the vue, not the type in the UI component.
![0b3a2dfba892f8189f646a199f575700](https://user-images.githubusercontent.com/16837203/194695309-18e417f0-c207-47e3-b56e-38adea18622c.png)

After the downgrade, it works.
![cf782df0008bdfe05094665473232f58](https://user-images.githubusercontent.com/16837203/194695174-985bb624-d854-400a-bdf1-155e5c46e101.jpg)

**Comment by vaakian** [comment]
It's better to provide a minimal reproduction

**Comment by ll60** [comment]
我也出现了这种问题。
<img width="851" alt="image" src="https://user-images.githubusercontent.com/30487969/194696550-b85ec5c1-d272-4fc0-baf8-33f218dc8101.png">

**Comment by liubaicai** [comment]
确实

**Comment by weifeiyue** [comment]
the same +1

**Comment by weifeiyue** [comment]
everythings is broken down

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/71a00190d1a5c8a2072c9b9d74c07667e01db8b9 and https://github.com/johnsoncodehk/volar/commit/2471365cff6d7eb186a95fed6b0b19f6f7eebea7
