### ISSUE TITLE
Volar does not respect the `experimentalDisableTemplateSupport` option

### ISSUE THREAD

**Issue by CikiMomogi** [johnsoncodehk/volar#1954]
Since updating to `v1.0.0`, Volar does not respect the `experimentalDisableTemplateSupport` option. It continues doing type-checking on `<Template/>`. I solved the problem by downgrading to `v0.40.13`. Here is my `tsconfig.json` settings:

```json
{
  "compilerOptions": {
    ...
    "jsx": "preserve",
    ...
  },
  "vueCompilerOptions": {
    "experimentalDisableTemplateSupport": true
  }
}
```

**Comment by yaegassy** [comment]
Please refer here. <https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#100-alpha4-2022924>

> vueCompilerOptions property `experimentalDisableTemplateSupport` renamed to `skipTemplateCodegen`.

**Comment by CikiMomogi** [comment]
Thank you.
