### ISSUE TITLE
volar broken in neovim

### ISSUE THREAD

**Issue by Lilja** [johnsoncodehk/volar#1955]
Hi, a couple of months ago I noticed that volar didn't work with neovim. I created a neovim issue for it. 
__Is this neovim or a volar related issue?__

https://github.com/neovim/neovim/issues/20010
https://www.reddit.com/r/neovim/comments/xy2xo8/vue_volar_error_request_initialize_failed/

**Comment by johnsoncodehk** [comment]
See https://github.com/neovim/neovim/issues/20010#issuecomment-1272370198
