### ISSUE TITLE
createLanguageServer Internal Error

### ISSUE THREAD

**Issue by SjB** [johnsoncodehk/volar#1963]
Running @volar/vue-language-server  v1.0.0-beta2 and above, give me the following error:

` LSP :: Error from the Language Server: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService') (Internal Error) `
  
Everything works ok in v1.0.0-beta1.

Running on Arch Linux
 emacs 29.0.50
lsp 20221005.1731

**Comment by johnsoncodehk** [comment]
See #1916

**Comment by SjB** [comment]
Thanks,  I wass able to fix my config using these line:

`  
(with-eval-after-load 'lsp-volar
            (setq lsp-typescript-tsdk (file-name-directory (lsp-volar-get-typescript-server-path))))

`
