### ISSUE TITLE
upgrading to version 1.0.X causing errors with camel cased properties

### ISSUE THREAD

**Issue by rathax** [johnsoncodehk/volar#1965]
some Props written as camel case now break the typing when referred to with hyphens inside the components.

to reproduce: create a new app with [create-vue](https://github.com/vuejs/create-vue) and update vue-tsc/vscode and use dataCamelCase for defining a component property like below:

![image](https://user-images.githubusercontent.com/16104507/194777144-eecb4087-d188-45fd-87da-85247874c353.png)

using the hyphen syntax for defining the prop in a vue template will cause a type error since version 1.0.x
![image](https://user-images.githubusercontent.com/16104507/194777130-03d41be9-3eff-4119-beda-79c993d76055.png)

seems to work as intended when not using 'data' as the first word when defining a property

**Comment by johnsoncodehk** [comment]
You can try config `vueCompilerOptions.dataAttributes = []` in tsconfig.

**Comment by rathax** [comment]
> You can try config `vueCompilerOptions.dataAttributes = []` in tsconfig.

yes, this will resolve the issue. Thank you. It's not marked as a breaking change in the changelogs and I guess many people are using data attributes like data-test, data-cy, data-test-id, and so on and gonna see quite a lot of errors when they update their volar extension tomorrow.
