### ISSUE TITLE
[RFC436] interface delcared in setup function should be elevated to top scope instead of function scope

### ISSUE THREAD

**Issue by HerringtonDarkholme** [johnsoncodehk/volar#1966]
Input file:

```vue
<script setup lang="ts" generic="T extends Test">
interface Test {
  test: string
}
const props = defineProps<{ 
  msg: T,    // no works
  mmm: Test, // works
}>()
console.log(props.msg.test)
</script>
```

Compiled virtual file

![image](https://user-images.githubusercontent.com/2883231/194790256-4b9421db-b7d4-40f8-931b-3f017b71fcd0.png)

Note the interface should be compiled outside of render function.

**Comment by xiaoxiangmoe** [comment]
😅temp solution，use `export interface Test {}`

**Comment by Florent-Bouisset** [comment]
You can also define your type in a <script> (not setup), not very comfortable to have 2 scripts tag but it works


```vue
<script lang="ts">
interface Test {
  test: string
}
</script>

<script setup lang="ts" generic="T extends Test">
const props = defineProps<{ 
  msg: T,    // no works
  mmm: Test, // works
}>()
console.log(props.msg.test)
</script>
```

**Comment by Florent-Bouisset** [comment]
it was answered here:
https://github.com/johnsoncodehk/volar/pull/1964#issuecomment-1277519562

**Comment by johnsoncodehk** [comment]
This is expected behavior, consider following case we cannot move `Test` outside setup function.

```html
<script setup lang="ts">
let test = 'test';
interface Test {
  test: typeof test
}
</script>
```

**Comment by HerringtonDarkholme** [comment]
So the solution here is using another script tag? It is more verbose. 
Also, it is not consistent with SFC's `defineProps`.

Consider this 
```vue
<script setup lang="ts">
  import { ref } from 'vue'
  interface Test {
    test: string
  }
  
  const props = defineProps<Test>()
</script>
```

will compile to successfully.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/2883231/196330057-178bd199-4c07-4bbd-970c-2e296daf1fee.png">

Playground: 
https://sfc.vuejs.org/#eNo9ULtuwzAM/BVCS1qgttDVUAz0Dzp01OI6tKPAekCk08HQv5dS0g4SeDyedMdDfaTU33dUgzI0Z5cYCHlPsE1hPVvFZNVoA4DzKWaGAzIuUGDJ0cNJhKdGBsa8TDPCF5IM1R4ASz0AcXZhrZ1Sr3rmGGQq5ZgIznDBxQX8rMhU+fjyaoPRDzfytwBGn7aJsTkx1/fxOMDTCqUYLah1XUg7w73z8YKbOBe+WTf6X63e1CNG56fU3ygGid3M2ichaYc/+1ZJvIqtujInGrSmZa7LulEf86ql6vMe2HnskXz3neMPYZaHrXrmLar8AhA6eUc=

**Comment by johnsoncodehk** [comment]
> So the solution here is using another script tag? It is more verbose than being optimal.

Yes, I mean elevate interface to top scope is not improvement, but it's a bug.

This is an example, when interface in `<script setup>` `Props.foo` is string, when interface in `<script>` `Props.foo` is number.

```html
<script lang="ts">
const foo = 123;
</script>

<script lang="ts" setup>
const foo = 'foo';

interface Props {
  foo: typeof foo; // string
}

defineProps<Props>()
</script>
```

```html
<script lang="ts">
const foo = 123;

interface Props {
  foo: typeof foo; // number
}
</script>

<script lang="ts" setup>
const foo = 'foo';

defineProps<Props>()
</script>
```
