### ISSUE TITLE
[Improvement] Remove `Vue` suffix from imported component name

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#197]
Say I have a component `VFoo.vue`, when importing it from another `.ts`/`.tsx`/`.vue` file, Volar IntelliSense shows `VFooVue`, and when I hit tab, `VFoo` will be imported as `VFooVue`, and I have to rename it back to `VFoo` every time I import it. It's a small thing, but I hope Volar doesn't append the `Vue` suffix when importing.

VFoo.vue:

```vue
<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({})
</script>
```

Importing:

![image](https://user-images.githubusercontent.com/28700378/119216493-9b062080-bb06-11eb-8ad3-c27c1f727f25.png)

**Comment by johnsoncodehk** [comment]
Thanks for your suggestion, but this is expected behavior, in this project `<script>` block designed to have consistent behavior with `*.ts`.

**Comment by johnsoncodehk** [comment]
Duplicate of #82
