### ISSUE TITLE
hover on prop showing less info than before

### ISSUE THREAD

**Issue by kingyue737** [johnsoncodehk/volar#1971]
Before:
Volar shows acceptable types of the hovered prop and its description(jsdoc), perfect!
![image](https://user-images.githubusercontent.com/40021217/194808677-0c19e708-b2d9-499b-ba47-c9f832035cbc.png)

Now:
Volar only shows the type of the argument passed to prop.
![image](https://user-images.githubusercontent.com/40021217/194808692-33e0b780-e309-41bb-9b2b-df920377f1c0.png)

**Comment by johnsoncodehk** [comment]
Can you try setting `vueCompilerOptions.jsxTemplates = true` in tsconfig?

**Comment by kingyue737** [comment]
> Can you try setting `vueCompilerOptions.jsxTemplates = true` in tsconfig?

It works! Thanks

**Comment by johnsoncodehk** [comment]
It's also works to me without setting `vueCompilerOptions.jsxTemplates = true`, could you provide repro case?

**Comment by kingyue737** [comment]
@johnsoncodehk this issue exists in v1.0.3 when `vueCompilerOptions.jsxTemplates = false`
After upgrading to v1.0.5, no such issue.

**Comment by SD-Gaming** [comment]
I use volar v1.0.7, but I also can't see the more jsdoc description.

![image](https://user-images.githubusercontent.com/25575589/195523845-a78eb34f-2d77-4ebb-9994-7b387d980faa.png)

any other setting?

> @johnsoncodehk this issue exists in v1.0.3 when `vueCompilerOptions.jsxTemplates = false` After upgrading to v1.0.5, no such issue.

**Comment by kingyue737** [comment]
@SD-Gaming Are you using Vuetify 2? Vuetify 2 does not have built-in type support for components. I generate it myself. You can refer to this guide https://github.com/vuetifyjs/vuetify/issues/14798#issuecomment-1139788615 .
If you need full example, here is my template project https://github.com/kingyue737/vitify-admin which contains this feature.
