### ISSUE TITLE
The question of  Component property prompt 

### ISSUE THREAD

**Issue by lchxiang** [johnsoncodehk/volar#1972]
This is an old version. The property prompts are all props in the component
![3c63d343a8cf587a492dc18f3fe26c6](https://user-images.githubusercontent.com/19889748/194808576-e098e433-1d1b-4296-a6e7-f032232a8e29.jpg)
The latest version prompts that the attributes listed in the front are unnecessary. It is better to put props in the front
![5bc0cb27d866ded689b3dcec402fdcb](https://user-images.githubusercontent.com/19889748/194808809-55b5a906-5a0e-43f2-ae07-cfd4981bb12e.jpg)

**Comment by MatthD** [comment]
Yeah ! exacte same issue here, Should we rollback to a specific version of Volar to get it back ?
Not very usable without the props first order

**Comment by MatthD** [comment]
![Capture d’écran 2022-10-10 à 16 45 41](https://user-images.githubusercontent.com/7901366/194893052-f08d35f2-c767-4086-8e2b-8f4559efd59a.png)
If I downgrade volar to 0.37.9 it works (not after !)

**Comment by MatthD** [comment]
I can confirm that the version 1.0.6 has fixed it ! thanks
