### ISSUE TITLE
crashed after open vue file

### ISSUE THREAD

**Issue by caiyanhu** [johnsoncodehk/volar#1973]
nvim version: v0.8.0
voloar config:
init_options = {
    typescript = {
         serverPath = "/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js"
    }
}

when open vue file:
Error executing vim.schedule lua callback: ...l/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:128
5: RPC[Error] code_name = InternalError, message = "Request initialize failed with message: Cannot read pr
operties of undefined (reading 'createLanguageService')"
stack traceback:
        [C]: in function 'assert'
        ...l/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1285: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

the volar config shoule be ok(works fine yesterday and before), i think above error message is happen after update volar server

**Comment by yaegassy** [comment]
Settings need to be changed from volar 1.0.

`nvim-lspconfig` and `mason-lspconfig` seem to already support this, so please update your plug-in to the latest version.

- <https://github.com/neovim/nvim-lspconfig/commit/87c8c7ba29e8e07ef7e7d551d4e7a58345c50b9f>
- <https://github.com/williamboman/mason-lspconfig.nvim/commit/0eb7cfefbd3a87308c1875c05c3f3abac22d367c>

**Comment by caiyanhu** [comment]
work fine after change to mason

**Comment by yaegassy** [comment]
> work fine after change to mason

It seems to be working, so I don't think it is a problem, but there are currently multiple plugins about Neovim's built-in LSP related installation and configuration. I do not use Neovim's built-in LSP, so I cannot provide detailed support.

If there is a problem, please send an issue report or PR to the respective plug-in side for adjustment!

- nvim-lspconfig
- mason-lspconfig.nvim
- mason.nvim 
- nvim-lsp-installer
- and more...

**Comment by mikehaertl** [comment]
For those using `nvim-lspconfig`: You probably used the example for local typescript server from their [server configurations](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#volar) in your neovim config.

This part needs an update. See: https://github.com/neovim/nvim-lspconfig/pull/2219
