### ISSUE TITLE
vue-tsc FontAwesomeIcon issue with imported icons

### ISSUE THREAD

**Issue by plehnen** [johnsoncodehk/volar#1975]
We use FontAwesomeIcons with import exactly like described here:
https://fontawesome.com/docs/web/use-with/vue/dig-deeper#alternative-component-property

Upgrading vue-tsc from **0.40.13** to **1.0.3** complains with the following error:

```error TS2322: Type '{ icon: IconDefinition; class: string; }' is not assignable to type 'ComponentProps<ComponentPublicInstance<FontAwesomeIconProps, {}, {}, {}, {}, {}, FontAwesomeIconProps, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>>'.      
  Type '{ icon: IconDefinition; class: string; }' is missing the following properties from type '{ $: ComponentInternalInstance; $data: {}; $props: FontAwesomeIconProps; $attrs: Data; $refs: Data; $slots: Readonly<InternalSlots>; ... 7 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; }': $, $data, $props, $attrs, and 10 more.

40           <FontAwesomeIcon :icon="faCheckCircle" />
```

**Comment by nielsvanvelzen** [comment]
This issue is fixed when using the TypeScript definitions from this open pull request: https://github.com/FortAwesome/vue-fontawesome/pull/355

**Comment by lnvglr** [comment]
This did the trick for me:
https://github.com/FortAwesome/vue-fontawesome/issues/295#issuecomment-924658468

> ```ts
> // components.d.ts
> 
> import { DefineComponent } from 'vue';
> import { FontAwesomeIconProps } from '@fortawesome/vue-fontawesome';
> 
> declare module 'vue' {
>   export interface GlobalComponents {
>     FontAwesomeIcon: DefineComponent<Partial<FontAwesomeIconProps>>;
>   }
> }
> 
> export {};
> ```

Solution from [exreplay](https://github.com/exreplay)
