### ISSUE TITLE
Syntax highlight missing on pug components since 1.0

### ISSUE THREAD

**Issue by itzaks** [johnsoncodehk/volar#1977]
One feature that I really enjoyed in previous versions was the syntax highlighting of custom vue components being colored yellow when using volar, pug and the One Dark Pro color theme. After 1.0 and the introduction of `@volar/vue-language-plugin-pug`, this seems to have broken. All custom components are now colored the same as native html elements.

**Comment by dargmuesli** [comment]
Check the changelogs for a migration path: https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#100-alpha0-2022916
