### ISSUE TITLE
I got error to start language server after update to laest version 1.0.3 with  `mason.nvim` 

### ISSUE THREAD

**Issue by ancion** [johnsoncodehk/volar#1978]
![image](https://user-images.githubusercontent.com/49437191/194978943-e7cd574f-36c7-4f28-9169-1b0e6d86fede.png)

[platform] 
   - windows 11 -> wsl -> ubuntu
[tool]
   - neovim 8.0.3

**Comment by yaegassy** [comment]
Settings need to be changed from volar 1.0.

`nvim-lspconfig` and `mason-lspconfig` seem to already support this, so please update your plug-in to the latest version.

- <https://github.com/neovim/nvim-lspconfig/commit/87c8c7ba29e8e07ef7e7d551d4e7a58345c50b9f>
- <https://github.com/williamboman/mason-lspconfig.nvim/commit/0eb7cfefbd3a87308c1875c05c3f3abac22d367c>
