### ISSUE TITLE
Using mixins on defineComponent() with vue 2 breaks BootstrapVue

### ISSUE THREAD

**Issue by hfhchan** [johnsoncodehk/volar#1980]
Using `mixins` on `defineComponent()` with vue 2 breaks BootstrapVue. If I don't use the mixins property on `defineComponent()`, the type for `<b-col>` is `unknown` but becomes `never`when I have mixins defined.

The error that ts gives is `Type '{}' is not assignable to type 'never'. ts(2322)`.

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1919#issuecomment-1281664368
