### ISSUE TITLE
VS Code shows this error, "Volar version is 1.0.3, but workplace vue-tsc version is 0.40.13, there may have different type checking  behavior"

### ISSUE THREAD

**Issue by BroJenuel** [johnsoncodehk/volar#1981]
This is showing UP on VS Code, what is this? is this going to be a problem or should I ignore this?
![image](https://user-images.githubusercontent.com/31676163/194992878-167839eb-fdfa-44ea-a903-1ea7dff98385.png)

**Comment by Yinyiran** [comment]
me too, commit with pic
![1665473644946](https://user-images.githubusercontent.com/22965503/195024684-1746aea7-8827-48ea-853a-ead3901ce102.png)

**Comment by ymy0622** [comment]
https://github.com/johnsoncodehk/volar/issues/1950#issuecomment-1272245960
