### ISSUE TITLE
Intellisense cannot detect close tag of <script setup>

### ISSUE THREAD

**Issue by neko-para** [johnsoncodehk/volar#1982]
![image](https://user-images.githubusercontent.com/26452623/195020709-4c36830b-9c72-4f73-9e1f-8d8ab5fb9d86.png)

![image](https://user-images.githubusercontent.com/26452623/195020745-b78b7706-7ecd-47b1-abea-90a84010247c.png)

The project is generated by vite without any changes. It seems that volar treats codes after line 4 as javascript and cannot perceive the close tag `</script>` on line 5.

**Comment by neko-para** [comment]
This problem can be solved by removing all the comment. But after this process adding comment back doesn't make it break now.

**Comment by johnsoncodehk** [comment]
Could you paste the code in text?

**Comment by neko-para** [comment]
[test.zip](https://github.com/johnsoncodehk/volar/files/9760727/test.zip)

I've recreate a project, and this problem has appear again.

steps:
* npm create vite@latest
* project name: test
* framework: vue
* variant: javascript

**Comment by chrisgower** [comment]
I was having a similar issue - I think it's related to the open tag in the comment (`<script setup>`). 
Removing the tag, or adding in a closing tag in a comment, will cause Volar to act properly.
