### ISSUE TITLE
[vue-component-meta] Does not infer types based on JSDoc annotations

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#1984]
Note that I don't really use `vue-component-meta` for anything (currently) and not sure if and how it's used in Volar but I've noticed that the case when the props are annotated with JSDoc `@type` comment doesn't seem to be supported.

I'll just link to my comment that explains where it goes wrong: https://github.com/johnsoncodehk/volar/pull/1976#discussion_r991563475

**Comment by johnsoncodehk** [comment]
This is `defineComponent()` behavior we can't fix, you can try the follow code in .ts to test.

```ts
// test.ts
import { defineComponent } from 'vue'

const Comp = defineComponent({
  props: {
    /**
     * Default function Array
     * @type {import('vue').Prop<[1, 2, 3]>}
     */
    arrayDefault: {
      type: Array,
      default: () => [1, 2, 3]
    }
  }
});

(new Comp()).$props.arrayDefault // unknown[] | undefined
```

In v1.0.4 we have embedded `vue-component-meta` to langauge server and supports "Show Component Meta" command as a simplified `vue-component-meta` playground, you can use for test..

**Comment by rchl** [comment]
It seems to work in Volar itself (repo for testing: https://github.com/rchl/volar-vue2-test):

![Screenshot 2022-10-11 at 21 27 31](https://user-images.githubusercontent.com/153197/195181428-3b7e4446-c47b-4c86-9c49-c980866e3d5d.png)

Is that different from how `vue-component-meta` works?

**Comment by johnsoncodehk** [comment]
Just tried with "Show Component Meta" command and also works
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/16279759/195191536-159ce13d-6ec5-4d1f-8cf8-8bcf789f3737.png">

It seem vue 2.7 defineComponent handle this case better vue 3 defineComponent.

**Comment by rchl** [comment]
So you would suggest reporting this against Vue?
