### ISSUE TITLE
Native DOM event type checking error since upgrading to 1.0.3

### ISSUE THREAD

**Issue by ymy0622** [johnsoncodehk/volar#1985]
Native DOM event type checking error. (click, contextmenu, etc.)

vue@3.2.40
vite@3.1.7
vitejs/plugin-vue@3.1.2
vue-tsc@1.0.3
volar@1.0.3

I have deleted and installed  yarn.lock + node_modules.

```vue
<template>
  <div @click="test"></div>
</template>

<script setup lang="ts">
  const test = () => {}
</script>
````

Type '() => void' is not assignable to type 'MouseEvent'.ts(2322)
__VLS_types.ts(107, 56): The expected type comes from property 'click' which is declared here on type 'EventObject<undefined, "click", {}, MouseEvent | undefined>'
![image](https://user-images.githubusercontent.com/54923146/195041541-543cf315-c719-491a-8a23-8292b8b10e57.png)

**Comment by jbaubree** [comment]
Same issue here

**Comment by cshuawei** [comment]
I got a similar error like this：
<img width="326" alt="image" src="https://user-images.githubusercontent.com/15762056/195047296-e7f4dfae-0bf7-4354-baad-e056f033e408.png">
![image](https://user-images.githubusercontent.com/15762056/195047461-f7c807df-acdf-45b5-8441-a27cdaf44a12.png)

**Comment by bjornharrtell** [comment]
For me it works after pinning `@types/node` to `18.8.0` (+removing lockfile and reinstall deps).

**Comment by IagoLast** [comment]
Same thing but when using `vue-tsc` from the console

<img width="1471" alt="Screenshot 2022-10-11 at 11 06 22" src="https://user-images.githubusercontent.com/2657897/195047855-0c9e98c1-a36d-4d68-8c17-3b66661b0c04.png">

**Comment by ymy0622** [comment]
> For me it works after pinning `@types/node` to `18.8.0` (+removing lockfile and reinstall deps).

Wow, it works.
Thank you very much.

**Comment by cshuawei** [comment]
> > For me it works after pinning `@types/node` to `18.8.0` (+removing lockfile and reinstall deps).
> 
> Wow, it works. Thank you very much.

Also works for me.

**Comment by jbaubree** [comment]
@ymy0622 are you sure this is a real solution and not a workaround before fix ?

**Comment by bjornharrtell** [comment]
@ymy0622 I think you should leave this open. It's not really a desired workaround to pin `@types/node`.

**Comment by njtyair** [comment]
同样的报错信息
__VLS_types.ts(107, 56): 所需类型来自属性 "click"，在此处的 "EventObject<undefined, "click", {}, MouseEvent | undefined>" 类型上声明该属性

**Comment by lesonky** [comment]
1.0.3 继续报错，导致 vscode 里面报错，我的build 命令还用了 
vue-tsc --noEmit && vite build --config ./config/vite.config.prod.ts

导致无法打包，只能把 vue-tsc 去掉

**Comment by IagoLast** [comment]
@bjornharrtell I'm trying to do the @types/node hotfix but still doesn't work... 

Any idea of how volar / vue-tsc infer DOM typings? or how the __VLS_types.ts file is generated?

I'm stuck because of this 😭

**Comment by jbaubree** [comment]
@IagoLast make sur to put "@types/node": "18.8.0" and not "@types/node": "^18.8.0"

**Comment by widetrace** [comment]
> @IagoLast make sure to put "@types/node": "18.8.0" and not "@types/node": "^18.8.0". Edit: remove `node_modules` folder and `lock` file before install again.

thanks!

**Comment by IagoLast** [comment]
I did that and still does not work 🤔

**Comment by fy5220** [comment]
> I did that and still does not work 🤔

when u done this , reopen the vecode 

> @IagoLast make sure to put "@types/node": "18.8.0" and not "@types/node": "^18.8.0". Edit: remove `node_modules` folder and `lock` file before install again.

**Comment by Georgitto** [comment]
Still getting the same problem after changing the version of `@types/node` to `18.8.0` and reinstalling all dependencies (deleting `node_modules` folder and `yarn.lock`).

**Comment by steveaffleck** [comment]
18.8.0 didn't work for me but 18.7.14 did.

**Comment by cuebit** [comment]
Works with `@types/node@18.8.3` also.

**Comment by johnsoncodehk** [comment]
Please track https://github.com/vuejs/core/pull/6855

**Comment by johnsoncodehk** [comment]
We can't fix this problem in language server, but we will have a doctor message to remind user downgrade `@types/node` to 18.8.0.

**Comment by vis97c** [comment]
> We can't fix this problem in language server, but we will have a doctor message to remind user downgrade `@types/node` to 18.8.0 or update to next vue release.

Does it mean that it cannot be solved from vue-tsc?

**Comment by acidjazz** [comment]
why is this issue closed but not yet fixed?

**Comment by MaoXuKun** [comment]
我遇到了同样的问题，解决方案是切换 VSCode 的 TS 使用工作区版本。
操作方法为 Ctrl + Shift + P，输入 selectTypeScriptVersion，然后选择 Use Workspace Version。
![image](https://user-images.githubusercontent.com/26497171/195234901-15ca3c07-768f-41f1-99dd-e0a47ec16d55.png)
![image](https://user-images.githubusercontent.com/26497171/195234979-3277a65b-037d-49dd-943e-ab51bd0e21d1.png)

**Comment by warmthsea** [comment]
![image](https://user-images.githubusercontent.com/45450994/195238502-04453714-fc32-4de0-bf63-4a6ea94d9908.png)
What should I do?

**Comment by vis97c** [comment]
@warmthsea remove "^" from the version number  so it installs that specific version.

**Comment by warmthsea** [comment]
> @warmthsea remove "^" from the version number so it installs that specific version.

![image](https://user-images.githubusercontent.com/45450994/195239419-f8ef1bcb-a8b2-482e-97c8-51858a0707e0.png)
Thanks

**Comment by WilsonXinxin** [comment]
> 我遇到了同样的问题，解决方案是切换 VSCode 的 TS 使用工作区版本。 操作方法为 Ctrl + Shift + P，输入 selectTypeScriptVersion，然后选择 Use Workspace Version。 ![图像](https://user-images.githubusercontent.com/26497171/195234901-15ca3c07-768f-41f1-99dd-e0a47ec16d55.png) ![图像](https://user-images.githubusercontent.com/26497171/195234979-3277a65b-037d-49dd-943e-ab51bd0e21d1.png)

I tried, but it didn't work

**Comment by Suv4o** [comment]
Downgrading the @types/node to 18.8.0 didn't help in my project. I am still facing the same issue

Here is my package.json:

"dependencies": {
"@headlessui/vue": "^1.7.3",
"@heroicons/vue": "^2.0.12",
"@tailwindcss/aspect-ratio": "^0.4.2",
"@tailwindcss/forms": "^0.5.3",
"@vueuse/core": "^9.3.0",
"dotenv": "^16.0.3",
"firebase": "^9.11.0",
"firebase-admin": "^11.1.0",
"pg": "^8.8.0",
"pinia": "^2.0.23",
"simple-git": "^3.14.1",
"vue": "^3.2.37",
"vue-router": "^4.1.5"
},
"devDependencies": {
"@pinia/testing": "^0.0.14",
"@testing-library/vue": "^6.6.1",
"@types/jsdom": "^20.0.0",
"@types/node": "^18.8.0",
"@types/pg": "^8.6.5",
"@types/yargs": "^17.0.13",
"@typescript-eslint/eslint-plugin": "^5.40.0",
"@typescript-eslint/parser": "^5.40.0",
"@vitejs/plugin-basic-ssl": "^0.1.2",
"@vitejs/plugin-vue": "^3.1.0",
"@vue/test-utils": "^2.1.0",
"autoprefixer": "^10.4.12",
"c8": "^7.12.0",
"cross-env": "^7.0.3",
"eslint": "^8.25.0",
"eslint-config-prettier": "^8.5.0",
"eslint-plugin-vue": "^9.6.0",
"jsdom": "^20.0.1",
"postcss": "^8.4.17",
"prettier": "2.7.1",
"tailwindcss": "^3.1.8",
"ts-node": "^10.9.1",
"types-package-json": "^2.0.39",
"typescript": "^4.6.4",
"vite": "^3.1.0",
"vite-plugin-eslint": "^1.8.1",
"vitest": "^0.24.1",
"vue-tsc": "^1.0.3"
}

**Comment by warmthsea** [comment]
> Downgrading the @types/node to 18.8.0 didn't help in my project. I am still facing the same issue
> 
> Here is my package.json:
> 
> "dependencies": { "@headlessui/vue": "^1.7.3", "@heroicons/vue": "^2.0.12", "@tailwindcss/aspect-ratio": "^0.4.2", "@tailwindcss/forms": "^0.5.3", "@vueuse/core": "^9.3.0", "dotenv": "^16.0.3", "firebase": "^9.11.0", "firebase-admin": "^11.1.0", "pg": "^8.8.0", "pinia": "^2.0.23", "simple-git": "^3.14.1", "vue": "^3.2.37", "vue-router": "^4.1.5" }, "devDependencies": { "@pinia/testing": "^0.0.14", "@testing-library/vue": "^6.6.1", "@types/jsdom": "^20.0.0", "@types/node": "^18.8.0", "@types/pg": "^8.6.5", "@types/yargs": "^17.0.13", "@typescript-eslint/eslint-plugin": "^5.40.0", "@typescript-eslint/parser": "^5.40.0", "@vitejs/plugin-basic-ssl": "^0.1.2", "@vitejs/plugin-vue": "^3.1.0", "@vue/test-utils": "^2.1.0", "autoprefixer": "^10.4.12", "c8": "^7.12.0", "cross-env": "^7.0.3", "eslint": "^8.25.0", "eslint-config-prettier": "^8.5.0", "eslint-plugin-vue": "^9.6.0", "jsdom": "^20.0.1", "postcss": "^8.4.17", "prettier": "2.7.1", "tailwindcss": "^3.1.8", "ts-node": "^10.9.1", "types-package-json": "^2.0.39", "typescript": "^4.6.4", "vite": "^3.1.0", "vite-plugin-eslint": "^1.8.1", "vitest": "^0.24.1", "vue-tsc": "^1.0.3" }

 remove "^" from the version number so it installs that specific version. @Suv4o

**Comment by Suv4o** [comment]
@warmthsea Thanks for that. By removing `"^"` fixed the issue.

**Comment by MuTsunTsai** [comment]
This issue persists as of `@types/node` 18.8.5.

**Comment by acidjazz** [comment]
are these keydown issues the same ?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/967369/195506434-6f513d4c-50cd-4430-8216-43c3229deebd.png">

**Comment by ymy0622** [comment]
> are these keydown issues the same ?
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/967369/195506434-6f513d4c-50cd-4430-8216-43c3229deebd.png">

yes.
you can fix this by pinning the `@types/node` to `18.8.0`.
or wait for `Vue` to update to `3.2.41` (if released) or later.

**Comment by cumt-robin** [comment]
> For me it works after pinning `@types/node` to `18.8.0` (+removing lockfile and reinstall deps).

it works.

**Comment by azat-io** [comment]
![image](https://user-images.githubusercontent.com/5698350/195910393-7f2307e2-04aa-4eea-8251-a4f62cd005b0.png)

I have the same problem. 

But I'm not using `@types/node` directly. Here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "types": ["@vuepress/client/types"],
    "importsNotUsedAsValues": "error",
    "moduleResolution": "nodenext",
    "preserveValueImports": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "module": "esnext",
    "target": "es2020",
    "jsx": "preserve",
    "allowJs": true,
    "strict": true,
    "baseUrl": ".",
    "noEmit": true,
    "paths": {
      "~/components/*": ["./components/*"],
      "~/typings/*": ["./typings/*"],
      "~/assets/*": ["./assets/*"],
      "~/pages/*": ["./pages/*"],
      "~/icons/*": ["./icons/*"]
    }
  },
  "include": ["**/*.ts", "**/*.vue"],
  "exclude": ["node_modules"]
}
```

**Comment by vis97c** [comment]
> ![image](https://user-images.githubusercontent.com/5698350/195910393-7f2307e2-04aa-4eea-8251-a4f62cd005b0.png)
> 
> I have the same problem.
> 
> But I'm not using `@types/node` directly. Here is my `tsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "forceConsistentCasingInFileNames": true,
>     "types": ["@vuepress/client/types"],
>     "importsNotUsedAsValues": "error",
>     "moduleResolution": "nodenext",
>     "preserveValueImports": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "esModuleInterop": true,
>     "skipLibCheck": true,
>     "module": "esnext",
>     "target": "es2020",
>     "jsx": "preserve",
>     "allowJs": true,
>     "strict": true,
>     "baseUrl": ".",
>     "noEmit": true,
>     "paths": {
>       "~/components/*": ["./components/*"],
>       "~/typings/*": ["./typings/*"],
>       "~/assets/*": ["./assets/*"],
>       "~/pages/*": ["./pages/*"],
>       "~/icons/*": ["./icons/*"]
>     }
>   },
>   "include": ["**/*.ts", "**/*.vue"],
>   "exclude": ["node_modules"]
> }
> ```

It doesn't matter that you don't use it directly. Dependencies can install dependecies. Alternatively if you are using yarn use resolutions instead.

**Comment by yah-yuan** [comment]
seems vue@3.2.41 has been released and fixed this problem. I upgraded vue and @types/node to the latest, and the error no longer exists.

**Comment by cuebit** [comment]
> seems vue@3.2.41 has been released and fixed this problem. I upgraded vue and @types/node to the latest, and the error no longer exists.

Sadly this doesn't seem to be the case for many. [v3.2.40...v3.2.41](https://github.com/vuejs/core/compare/v3.2.40...v3.2.41) shows no indication of any fix for this and the actual fix (vuejs/core#6855) is yet to be merged and released.

**Comment by loneil** [comment]
> 

Are you sure about that? Vue 3.2.41 hasn't fixed this issue. Is it possible your types/node in your lock is still pinned to 18.8.0 and you didn't really update it? I'm trying starting from scratch and as of right now with the latest everything, you still need that 18.8.0 pin

**Comment by loneil** [comment]
> seems vue@3.2.41 has been released and fixed this problem. I upgraded vue and @types/node to the latest, and the error no longer exists.


Are you sure about that? Vue 3.2.41 hasn't fixed this issue. Is it possible your types/node in your lock is still pinned to 18.8.0 and you didn't really update it? I'm trying starting from scratch and as of right now with the latest everything, you still need that 18.8.0 pin

**Comment by johnsoncodehk** [comment]
Please wait for 3.2.42 and pin @types/node to 18.8.0 for now. :)

**Comment by johnsoncodehk** [comment]
Please also track https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62729 (Fix for next `@types/node` version)

**Comment by rodrigocfd** [comment]
@johnsoncodehk Shouldn't Volar have a new version *disabling* the doctor warning now?
