### ISSUE TITLE
Wrong semantic token for computed property

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#1988]
It's  a minor thing but computed properties referenced in the `template` are currently marked with `method` semantic token. While those are internally implemented through a method/function, to the user those are just properties so it would be more correct to not apply `method` semantic token to those.

In ST and my particular color scheme that makes the property have blue color which is normally used for methods/functions:

<img width="259" alt="Screenshot 2022-10-11 at 12 57 21" src="https://user-images.githubusercontent.com/153197/195072639-288ea7c8-3797-4e40-b021-dc75e051fd3b.png">

Repo that includes this simple `index.vue` file: https://github.com/rchl/volar-vue2-test

**Comment by johnsoncodehk** [comment]
It can reproduce in .ts, It seems a TypeScript bug but I can't sure currently, need more time to digging.

```ts
import { defineComponent } from 'vue'

const Comp = defineComponent({
  computed: {
    computedProp() {
      return 'foo'
    },
  },
});

(new Comp()).computedProp;
```

<img width="613" alt="image" src="https://user-images.githubusercontent.com/16279759/195475652-cebd0ef7-7af8-4873-b7c1-48ec7b5b265a.png">

**Comment by rchl** [comment]
It doesn't surprise me that typescript sees those as methods since computed properties are technically implemented using methods/functions. I was just thinking that maybe there would be a way to override what typescript thinks about those.

**Comment by johnsoncodehk** [comment]
This is TypeScript bug, you can report to TypeScript repo.

Minimal reproduction:

```ts
declare function foo<T>(t: T): { [K in keyof T]: T[K] extends (...args: any) => infer R ? R : T[K] };

const a = foo({ b: () => 1, c() { return 2 } });

a.b; // correct color
a.c; // incorrect color
```

**Comment by rchl** [comment]
Interestingly with `typescript-language-server` I'm getting `property` and `member` semantic tokens in your test:

![Screenshot 2022-10-18 at 09 16 43](https://user-images.githubusercontent.com/153197/196362281-fe1f101a-8113-4053-ac50-d91ae4b2c0fd.png)

while in Volar and VSCode's built-in service I'm getting `property` and `method`:

![Screenshot 2022-10-18 at 09 17 38](https://user-images.githubusercontent.com/153197/196362482-8c8cfbb4-39df-446b-8282-6ac1d0ac3d55.png)

I will try to look into it more when I have some time. I wonder which one is wrong...

**Comment by johnsoncodehk** [comment]
I think I can quickly tell you the problem, `typescript-language-server` maybe missing `SemanticClassificationFormat.TwentyTwenty`: https://github.com/johnsoncodehk/volar/blob/1444a233338e74f7da453b132f4645a4d4cb129e/plugins/typescript/src/services/semanticTokens.ts#L38

**Comment by rchl** [comment]
Is that something that VSCode's built-in typescript features handle? I can't find references to anything like that in its code and yet it still marks it as `method`.

**Comment by rchl** [comment]
OK, I see now. This is something that can be opt-in through the tsserver API with `format: '2020'` (https://github.com/typescript-language-server/typescript-language-server/blob/07d2bbc0b05febf0ffc1b96d9709071d2b286fb4/src/lsp-server.ts#L1260-L1260).

typescript-language-server already opts in so I would still have to investigate where the behavior difference is coming from...

**Comment by johnsoncodehk** [comment]
An other thing is the language client maybe missing: https://github.com/johnsoncodehk/volar/blob/1444a233338e74f7da453b132f4645a4d4cb129e/extensions/vscode-vue-language-features/package.json#L519-L547 (In VSCode: https://github.com/microsoft/vscode/blob/72e1767f7bd7f24b0e40f6881b4220b4d77e1926/extensions/typescript-basics/package.json#L127)

**Comment by johnsoncodehk** [comment]
In LSP server it should add to semanticTokensProvider : https://github.com/johnsoncodehk/volar/blob/1444a233338e74f7da453b132f4645a4d4cb129e/packages/language-server/src/registerFeatures.ts#L138-L148

**Comment by rchl** [comment]
Doesn't look like those scopes relate to the issue though as none of those mentions `member` or `method`.

But then maybe for vscode you would be able to overwrite the style using those settings? I would still prefer solution within the language server but if that's not an option then this would be second best. (For ST we could figure out something also)

**Comment by johnsoncodehk** [comment]
I'm pretty sure it's related and it's TS problem not Volar or `typescript-language-server` problem. 👀 You can see `entity.name.function`(https://github.com/microsoft/vscode/blob/72e1767f7bd7f24b0e40f6881b4220b4d77e1926/extensions/typescript-basics/package.json#L144) in your screenshot

I think the minimal reproduction is good enough for report to TypeScript, but it's ok if you need to confirm the different first.

**Comment by johnsoncodehk** [comment]
> I would still prefer solution within the language server but if that's not an option then this would be second best. (For ST we could figure out something also)

LSP have [a few preset token types](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers), with preset token types you don't need to add it to language client, I'm not sure if the preset token types set can cover all token types of `typescript-language-features` define, but I think it's worth to try.

**Comment by rchl** [comment]
I'm a bit confused by why semantic tokens defined in Typescript don't match what Volar or typescript-language-features uses:

https://github.com/microsoft/TypeScript/blob/4c9afe8812fcdb4658472ccbced4a5cd4bae70ea/src/services/classifier2020.ts#L9-L11

Notice how the last token type is called `member` in Typescript while both [Volar](https://github.com/johnsoncodehk/volar/blob/5e19424074f6c94869d860385321c5b8ea596166/plugins/typescript/src/services/semanticTokens.ts#L141-L141) and [TLS](https://github.com/microsoft/vscode/blob/1900abc88b8a0bce7446314c248c5e79deaad0c1/extensions/typescript-language-features/src/languageFeatures/semanticTokens.ts#L190-L190) use `method`. I wonder if it's a typo and then whether it's a typo in Typescript or Volar/TLS.

**Comment by rchl** [comment]
Well, I suppose that regardless of how it's called in TS, it might make more sense to call it `method` in language servers as `method` is one of the default token types while `member` is probably not widely recognized one.

**Comment by johnsoncodehk** [comment]
Maybe it's follow this flow: [support.function.vue](https://github.com/johnsoncodehk/volar/blob/1444a233338e74f7da453b132f4645a4d4cb129e/extensions/vscode-vue-language-features/package.json#L542) -> [support.function -> entity.name.function.member -> method](https://github.com/microsoft/vscode/blob/99bd8d61991a5f482cdbd94622b74262e2b3b8dc/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L561)

And `method` and `member` seems is same concept in TS language server: https://github.com/microsoft/TypeScript/blob/4c9afe8812fcdb4658472ccbced4a5cd4bae70ea/src/services/classifier2020.ts#L239
