### ISSUE TITLE
Unneeded reference to css class

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#1989]
Note how the code lens for the `.some-class` includes 2 references but there is only one use of `.some-class` in the file:

<img width="408" alt="Screenshot 2022-10-11 at 13 24 11" src="https://user-images.githubusercontent.com/153197/195077720-7911a8f9-77d5-4500-ae24-f5bd96509707.png">

I believe the references lens should not include the class definition itself.

**Comment by rchl** [comment]
Repo that includes this simple index.vue file: [rchl/volar-vue2-test](https://github.com/rchl/volar-vue2-test)

**Comment by rchl** [comment]
I've tested it only now and while the code lens shows only one reference now, the returned list on clicking it still includes both.

**Comment by johnsoncodehk** [comment]
This is intentional because I think its results should be consistent with right click -> "Fine References".

**Comment by rchl** [comment]
But it's not how it works in plain JS/TS, for example.

If you define a function and show references for it then it won't show the function definition itself.

**Comment by johnsoncodehk** [comment]
I see, will make it consistent with plain JS/TS, thanks for bringing this up!
