### ISSUE TITLE
[Bug] inline style breaks SFC syntax highlighting

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#199]
Repro: https://github.com/wenfangdu/volar-syntax-highlighting-repro

Screenshot: 

![image](https://user-images.githubusercontent.com/28700378/119223478-483f5f80-bb2c-11eb-8288-0f51e5e2ee6f.png)

**Comment by johnsoncodehk** [comment]
Thanks for your report! you could change to `style="margin-bottom:20px;"`, or downgrade to 0.25.3 to fix for now.

**Comment by johnsoncodehk** [comment]
Fixed in 0.25.11.
