### ISSUE TITLE
[ERROR] Cannot find module 'element-plus' or its corresponding type declarations

### ISSUE THREAD

**Issue by CoderDuMin** [johnsoncodehk/volar#1990]
Vue3 + TS + Vite project,It has been declared in tsconfig.json "skipLibCheck": true, 
However, an error is reported during packaging and cannot find  the module , vue-tsc version  is 0.40.13,
Please tell me where the error occurred
![image](https://user-images.githubusercontent.com/68316271/195123629-aa5989f9-090f-4603-bd4b-54330243201a.png)
![image](https://user-images.githubusercontent.com/68316271/195126411-c72bd787-6594-47dc-8f85-05fc886973ab.png)

**Comment by sxzz** [comment]
Can't reproduce, could you please provide the reproduction repo?
