### ISSUE TITLE
component type error

### ISSUE THREAD

**Issue by wenhongjie** [johnsoncodehk/volar#1996]
## BUG report
When <script lang="ts" setup> and normal <script lang="ts"> are used together. it's report: 
**Type '{}' is not assignable to type 'ComponentProps<() => ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<......'.**
```vue
<!-- ComponentWithMultipleRoots -->
<template>
  <div></div>
  <div></div>
</template>

<script lang="ts" setup>
//...
</script>

<script lang="ts">
export default {
   inheritAttrs: false
}
</script>
```

```vue
<template>
  <ComponentWithMultipleRoots />
</template>
```

![image](https://user-images.githubusercontent.com/30290407/195243415-ddb05c9f-06d6-4fd9-8101-686041d97fa6.png)

## ENV

Typescript version: 4.8.4
vite version: 3.1.7
volar version: 1.0.5
vscode version: 1.72
os: 5.17.15-1-MANJARO(x64)

**Comment by appleaway** [comment]
回滚volar到1.0.3版本等待解决吧

**Comment by jahnli** [comment]
the same problem

**Comment by DevilTea** [comment]
Here is a [reproduction repo](https://github.com/DevilTea/repro-volar-issue-1938)

when open the `App.vue` file with vscode,
the component props error message would show like below
<img width="828" alt="image" src="https://user-images.githubusercontent.com/16652879/195257176-c7c72fbe-379c-4cf2-8811-1598db3f9253.png">

when the component has both `<script setup>` and `<script> with export default defineComponent({})` existed
<img width="664" alt="image" src="https://user-images.githubusercontent.com/16652879/195257446-75b5fe7f-6728-4a73-8e90-497d172a9f94.png">

**Comment by tanghaojie** [comment]
same error

**Comment by wenhongjie** [comment]
> 回滚volar到1.0.3版本等待解决吧

回滚有效, 不过最近volar似乎不是很稳定.

**Comment by kyumoon** [comment]
+1

**Comment by JoostKersjes** [comment]
Same here, all my components components with `inheritAttrs: false` are throwing this error.

**Comment by Fuphoenixes** [comment]
> > 回滚volar到1.0.3版本等待解决吧
> 
> 回滚有效, 不过最近volar似乎不是很稳定.

+1

**Comment by MrCube42** [comment]
In my case, these errors appear when calling methods defined via options API, e.g. `this.myMethod()`. I could **workaround** this in some cases by changing `data() { ...` to `data: () =>`. In this case, the type is correctly inferred. However, when I want to access the _props_ in `data` and I need to change to `data: (vm) => vm.myProp` the inference is also broken.

Side note: The same errors appear also when _building_ with vue-cli as soon as I switch from vue `2.7.10` to `2.7.11`. As long as I stay on `2.7.10` this is only an IDE problem with Volar.

**Comment by vis97c** [comment]
Was this really fixed? I'm getting:  **not assignable to type ComponentProps<string>** when working with transition component

**Comment by dxps** [comment]
Same here: using Volar `v1.0.9` (with takeover mode enabled, ofc) and [this example](https://github.com/dxps/vue_playground/blob/master/ts-journal/src/components/EntryEditor.vue).

It compiles and runs fine, it's just this error returned:
```
Type '{ width: string; }' is not assignable to type 'ComponentProps<string>'.
  Type '{ width: string; }' is not assignable to type 'string'.ts(2322)
```
![image](https://user-images.githubusercontent.com/14140226/203091066-c9f8554f-30fd-4715-b9fb-6cac33cf0a18.png)

**Comment by Andrii-Khoptii** [comment]
Volar ts: 1.2.0

**Comment by hkochniss** [comment]
@johnsoncodehk this creates massive type errors in vue-tsc 1.3.10, somehow VS Code Volar 1.3.14 doesn't show the errors though. We can't basically use vue-tsc right now, as it emits too many unfounded errors, along the lines of 

`Argument of type '{ id: string; }' is not assignable to parameter of type '{ ref?: VNodeRef | undefined; key?: string | number | symbol | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; onVnodeBeforeMount?: VNodeMountHook | VNodeMountHook[] | undefined;`
