### ISSUE TITLE
Type '...' is not assignable to type 'Event'. ts(2322)

### ISSUE THREAD

**Issue by szulcus** [johnsoncodehk/volar#1998]
```
Type '() => Promise<void>' is not assignable to type 'Event'. ts(2322)
__VLS_types.ts(109, 56): The expected type comes from property 'submit' which is declared here on type 'EventObject<any, "submit", {}, Event>'
```

I'm not sure if it's a problem with Volar or Nuxt 3, but please help. What to do to make the event types match?
![image](https://user-images.githubusercontent.com/48328739/195278531-a4051cc0-d9da-4b2d-9fe8-e5761d581c7e.png)
I also can't open `__VLS_types.ts`
![image](https://user-images.githubusercontent.com/48328739/195278724-6b7ae07a-64f1-4b40-a5b7-1285bfc357b1.png)

**Comment by johnsoncodehk** [comment]
You need to downgrade `@types/node` to 18.8.0, see #1985

**Comment by Suv4o** [comment]
Downgrading the `@types/node` to 18.8.0 didn't help in my project. i still facing the same issue

Here is my package.json:

  "dependencies": {
    "@headlessui/vue": "^1.7.3",
    "@heroicons/vue": "^2.0.12",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.3",
    "@vueuse/core": "^9.3.0",
    "dotenv": "^16.0.3",
    "firebase": "^9.11.0",
    "firebase-admin": "^11.1.0",
    "pg": "^8.8.0",
    "pinia": "^2.0.23",
    "simple-git": "^3.14.1",
    "vue": "^3.2.37",
    "vue-router": "^4.1.5"
  },
  "devDependencies": {
    "@pinia/testing": "^0.0.14",
    "@testing-library/vue": "^6.6.1",
    "@types/jsdom": "^20.0.0",
    "@types/node": "^18.8.0",
    "@types/pg": "^8.6.5",
    "@types/yargs": "^17.0.13",
    "@typescript-eslint/eslint-plugin": "^5.40.0",
    "@typescript-eslint/parser": "^5.40.0",
    "@vitejs/plugin-basic-ssl": "^0.1.2",
    "@vitejs/plugin-vue": "^3.1.0",
    "@vue/test-utils": "^2.1.0",
    "autoprefixer": "^10.4.12",
    "c8": "^7.12.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.25.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-vue": "^9.6.0",
    "jsdom": "^20.0.1",
    "postcss": "^8.4.17",
    "prettier": "2.7.1",
    "tailwindcss": "^3.1.8",
    "ts-node": "^10.9.1",
    "types-package-json": "^2.0.39",
    "typescript": "^4.6.4",
    "vite": "^3.1.0",
    "vite-plugin-eslint": "^1.8.1",
    "vitest": "^0.24.1",
    "vue-tsc": "^1.0.3"
  }

**Comment by szulcus** [comment]
> You need to downgrade `@types/node` to 18.8.0, see #1985

Hm, despite removing `node_modules` and `yarn.lock`, `18.8.0` didn't work for me. But I used version 18.7.14 (https://github.com/johnsoncodehk/volar/issues/1985#issuecomment-1275078909) and now everything works. I couldn't find this thread, thanks a lot for your help!

**Comment by szulcus** [comment]
@Suv4o Try this:
```
"@types/node": "18.7.14",
```

**Comment by Suv4o** [comment]
@szulcus downgrading to `"@types/node": "18.7.14",` didn't help

**Comment by johnsoncodehk** [comment]
@Suv4o could you provide repro case?
