### ISSUE TITLE
ref type error

### ISSUE THREAD

**Issue by cereschen** [johnsoncodehk/volar#2]
![image](https://user-images.githubusercontent.com/52478109/93470979-50a02480-f925-11ea-95b8-5c3917c2459a.png)
`
:ref="'music'"` is ok

and Seems like miss the type file in node_modules while find something to import?

In   Vue-class files, private property will report an error
Private keyword doesn't do anything, but a lot of people get used to writing it

It's nice to see that you're still maintaining the project, and it's now much faster than Vetur

**Comment by johnsoncodehk** [comment]
Hey, This problem has been fixed in v0.9.4!

Hint: If you has return the element in setup(), you can change `ref="music"` to `:ref="music"` to make language service support.
<img width="393" alt="螢幕截圖 2020-09-17 下午9 07 57" src="https://user-images.githubusercontent.com/16279759/93474425-e76ee000-f929-11ea-8b8b-5df752a53bb2.png">

Thanks to use this tool, At least I will continue to maintain this project until open source is completed. Almost all the code needs to be refactored, so there is still a lot of work to do...

**Comment by johnsoncodehk** [comment]
Sorry I missed your second question, I did not use vue class, can you provide a piece of code that can reproduce the error?

**Comment by cereschen** [comment]
```vue
<template>
  <div >
    {{foo}}  Cannot find name 'foo'.ts(2304)
  </div>
</template>
<script lang="ts">
import { Vue, Component } from "vue-property-decorator";

@Component
export default class extends Vue {
  private foo = 1;
}
</script>
```
BTW, Vue-html has a problem with comments. It now behaves like JS

It's not easy for vue2.x to have good type intellisense, but it works well with your plugin and @vue/composition-api.

**Comment by johnsoncodehk** [comment]
Allowing access to private properties requires some hacking works, I am not sure if I should do this. If private properties are to be made public, how to control which properties are not accessible in interpolations?
The vue-html comment is in my todo list. This problem also brings me inconvenience. I will deal with it as soon as possible after completing the open source work.
I didn't expect this tool to work for vue2... The vue-html rules of vue2 and vue3 are a bit different, so I might suggest that you use Vetur to get the correct vue-html diagnosis.

**Comment by cereschen** [comment]
This may require you to do something special with the vue-class, because in vue-class, even private properties are eventually merged into data,methods... In vetur, no errors are reported

Vutur has become unbearably slow, which is why I'm giving it up for now

If  use vue2.x, need to write extra type files, but in the end it will have good TS support

**Comment by johnsoncodehk** [comment]
Oh cool, I am glad to hear that you use vue2 smoothly! And I can understand your "unbearably" feeling. :(

Can you talk about the purpose of using "private" for class properties?

**Comment by cereschen** [comment]
If i write my own project, i will avoid this problem. However, in teamwork, other members may write private properties. I recommended this extension to a friend. He didn't use it because of this
However, this is not an urgent problem to be solved, it is just a problem I found before

Now I feel sad that it can't import the definitions of other files very well, even if the file where the variable to be imported is already written
This requires me to write a full import

**Comment by johnsoncodehk** [comment]
I don't quite understand the import issue you mentioned, and I want to ask some questions about the "private" issue. Can you contact me with discord? My id is johnsoncodehk. Thanks

**Comment by cereschen** [comment]
cereschen#9837   my id

**Comment by johnsoncodehk** [comment]
Oh don't know need the tag! Please pass my application.

**Comment by ghiscoding** [comment]
was there any ways to resolve this issue? The team project I'm working on also has a ton of a `public`/`private` properties and the extension throws all. I know that I can remove `private` and then everything is fine but my team won't be happy with this change, it was also mentioned in issue #957

![image](https://user-images.githubusercontent.com/643976/156200868-f2b8df86-c470-4a6e-bdae-e8fac5a2f48e.png)

**Comment by johnsoncodehk** [comment]
@ghiscoding I did't found out a solution yet, would be nice to have a issue for track.

**Comment by ghiscoding** [comment]
it would be nice to have a solution in the future, did u wanted a new issue or just keep this issue, and perhaps reopen it?

**Comment by johnsoncodehk** [comment]
@ghiscoding this issue is different problem actually, so please open a new if you want to track.
