### ISSUE TITLE
SASS language support

### ISSUE THREAD

**Issue by pipe01** [johnsoncodehk/volar#20]
When declaring a `<style lang="sass">` block, the brace-less SASS syntax doesn't seem to be properly recognized:

![imagen](https://user-images.githubusercontent.com/3885705/97888573-92e1c180-1d2b-11eb-856f-50d9b3e8866f.png)

**Comment by johnsoncodehk** [comment]
I think less is more... sass support is not planned, additional development cost of sass is too high, and I still focus on current existing features. (You can expect will have better support for pug)

If circumstances permit, you can consider convert to scss:
http://scss2sass.herokuapp.com/

**Comment by pipe01** [comment]
Fair enough, I will likely convert to scss then, thank you

**Comment by johnsoncodehk** [comment]
supported in 0.21.18.
