### ISSUE TITLE
Support vite-plugin-components

### ISSUE THREAD

**Issue by xorik** [johnsoncodehk/volar#200]
Hi.

Thank you for your plugin, it works really great!
 
I have on-demand components with [vite-plugin-components](https://github.com/antfu/vite-plugin-components), but type checking is not working for props, unless I import the component.

It would be nice to map components automatically (by default from `'src/components' folder`)

**Comment by johnsoncodehk** [comment]
Thanks for your suggestion, but this extension will not built-in support third party plugin, please wait supports for [Plugin API](https://github.com/johnsoncodehk/volar/issues/185).

You already able to use GlobalComponent interface to define "on-demand components", see https://github.com/johnsoncodehk/volar#using.

**Comment by xorik** [comment]
Ok, thanks for quick response!

I saw the global components, but it means I need to list there every component with props. Will work for now, i guess.

You may close the ticket, if you want
