### ISSUE TITLE
No Components imports && highlighting 

### ISSUE THREAD

**Issue by XavHernandez** [johnsoncodehk/volar#2000]
I struggle since the major Volar update i made yesterday...

I lost components highlighting in Vue file (with PUG), and vite HMR seems very odd too since then.
More, since this morning and the 1.0.5 i also can't have working components imports. Not sure what to do to fix that.
I have no types info neither on composant hovering.

Here is my list of deps, reinstalled after deleting lock-file and a screen

Extension Volar 1.0.5
"vue": "^3.2.40"
"@types/node": "18.8.0",
"@vitejs/plugin-vue": "^3.1.2",
"@volar/pug-language-service": "latest", 
"@volar/vue-language-plugin-pug": "latest" + VueCompilerOptions...
"@vue/compiler-sfc": "^3.2.40",
"autoprefixer": "^10.4.12",
"postcss": "^8.4.16",
"pug": "^3.0.2",
"tailwindcss": "^3.1.8",
"typescript": "^4.8.4",
"vite": "^3.1.4",
"vitest": "^0.23.4"
"vue-tsc": "^1.0.5"

<img width="692" alt="Capture d’écran 2022-10-12 à 09 46 16" src="https://user-images.githubusercontent.com/78563059/195284989-b7b3c4d4-3a73-4ad8-8b1f-47b55b7d320e.png">

<img width="866" alt="Capture d’écran 2022-10-12 à 09 59 37" src="https://user-images.githubusercontent.com/78563059/195285094-77ccb105-61a7-422e-bf8f-77b5aa4782af.png">

**Comment by johnsoncodehk** [comment]
Could you provide repro case?

**Comment by johnsoncodehk** [comment]
I can reproduce this problem with `@volar/vue-language-plugin-pug` 1.0.5, it will be fix in 1.0.6.

**Comment by XavHernandez** [comment]
You rock Sir ;) 
Thanks.
