### ISSUE TITLE
（怎么最近天天更新，没想好就不要写，天天发版不是你的KPI）Why is it updated every day recently, if you haven't figured out what to do, don't write it, publishing every day is not your KPI

### ISSUE THREAD

**Issue by xz1024** [johnsoncodehk/volar#2005]
接连好几天收到更新，本来一直在用react的，奈何公司有个项目是vue的，装了这个插件，先是logo变了，后来天天更新，我vscode有小圆圈提示呀关键，为什么我们不能保持初衷坚持自己原来的想法，还是我们善变？还是我们那项目练手来着？没人review这事？还有没有王法了？

**Comment by foreversimon** [comment]
vscode可以选之前版本安装, 按个对应项目版本的就可以

**Comment by liujiayii** [comment]
1天多次发版确实不像是1个成熟项目的样子……

**Comment by mlzzen** [comment]
也许你可以关掉插件的自动更新。

**Comment by xiaoxiangmoe** [comment]
因为有其他人需要bug的hotfix或者新feature，所以需要发版。

如果想要只跟进minor或者major版本的插件更新，建议去vscode提issue😅

**Comment by corporal9736** [comment]
不想用可以不用

**Comment by xz1024** [comment]
> 不想用可以不用

要不是公司有个项目是vue3的，我会吃这屎？

**Comment by xz1024** [comment]
bug可以攒一攒一起修完再发，不是用户提的需求都要做，md微信成天用户提1w个需求，都做了么

**Comment by johnsoncodehk** [comment]
> 要不是公司有个项目是vue3的，我会吃这屎？

行了，我本來都不想回覆，你用字還越來越過份。1.0 Alpha到RC本來就是差不多每日更新的，你的世界圍著KPI轉不代表別人也是，這是我的個人項目沒有所謂KPI。Logo也是早就計劃換成Vue，1.0才一起換。

這個項目發版原則是基於有嚴重regression時先跟積攢的minor fixs一起發版，盡快趕上上一個minor version的穩定性再減慢更新，只是碰上剛發佈1.0這幾天嚴重regression回報頻率高，一天發幾版本來是不常見的。

你手動降版本的就可以解決的問題，非要別人配合你有嚴重影響不能使用的問題等幾天才等到更新嗎？你主要不開發Vue對你影響小，但受影響大的人多的是，我沒有理由為了你就不處理。
