### ISSUE TITLE
  Type '{}' is not assignable to type '() => VNodeChild'.     

### ISSUE THREAD

**Issue by jahnli** [johnsoncodehk/volar#2007]
Type '{}' provides no match for the signature '(): VNodeChild'.

```
interface PropsType {
  renderSlot?: RenderSlotType;
}
const { renderSlot } = defineProps<PropsType>();

const render = () => renderSlot?.render();
</script>

<template>
  <render />
</template>

```

**Comment by jahnli** [comment]
If it goes back to 1.0.3, it's OK

**Comment by k713927** [comment]
i has the same problem
`
...CopyImageVideoBar.vue:75:18 - error TS2322: Type '($event: any) => void' is not assignable to type 'MouseEvent'.
`

**Comment by SivausIrom** [comment]
https://stackoverflow.com/questions/74037132/how-to-correctly-listen-to-an-event-in-vue-3-using-ts

**Comment by NonYotsugi** [comment]
> i has the same problem `...CopyImageVideoBar.vue:75:18 - error TS2322: Type '($event: any) => void' is not assignable to type 'MouseEvent'.`

Have you solved this problem?

**Comment by cuebit** [comment]
@k713927 your issue is not the same. Please refer to #1985

**Comment by spacedawwwg** [comment]
I've just hit this issue too. Fixed the @types/node issues by pinning to 18.0.0 but now stuck with a few `Type '{}' is not assignable to type` issues.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/1691867/195587863-624c5b2b-81a3-4604-a9b9-0acbc3e32bfe.png">

**Comment by johnsoncodehk** [comment]
You can use these workaround, or use v1.0.6 for now.

```ts
const render: FunctionalComponent = () => renderSlot?.render();
```

```ts
const Chart = defineComponent({
  setup() {
    return () =>
      h(UolChart, props.componentProps, {
        default: () => h('p', props.intro),
      });
  },
});
```

**Comment by spacedawwwg** [comment]
> You can use these workaround, or use v1.0.6 for now.
> 
> ```ts
> import { FunctionalComponent } from 'vue';
> 
> const render: FunctionalComponent = () => renderSlot?.render();
> ```
> 
> ```ts
> import { defineComponent } from 'vue';
> 
> const Chart = defineComponent({
>   setup() {
>     return () =>
>       h(UolChart, props.componentProps, {
>         default: () => h('p', props.intro),
>       });
>   },
> });
> ```

```
import type { FunctionalComponent } from 'vue';
import { h } from 'vue';

const Chart: FunctionalComponent = () =>
  h(UolChart, props.componentProps, {
    default: () => h('p', props.intro),
  });
```
Got me where I needed to be, thanks @johnsoncodehk
