### ISSUE TITLE
How to only do ESLint linting of script sections where lang is ts?

### ISSUE THREAD

**Issue by jez9999** [johnsoncodehk/volar#2008]
I'd like to only lint `<script>` sections in `.vue` files - whether in VS Code with Volar or on the commandline with `npm run lint` - when it has `lang="ts"` set.  Otherwise I just think of the code as JavaScript, not TypeScript, and do not wish to lint it.  How can I configure this?  Is there a way?

**Comment by johnsoncodehk** [comment]
You should ask to ESLint not here. :p

**Comment by jez9999** [comment]
@johnsoncodehk But doesn't this rely on Volar's special handling of `.vue` files?  ESLint obviously doesn't concern itself with which files / blocks of files it lints, it expects to be passed the TypeScript to lint.  Volar does something that parses `.vue` files and pulls out the TypeScript to pass to ESLint.

**Comment by johnsoncodehk** [comment]
No we don't have cooperation with ESLine, ESLine use https://github.com/vuejs/eslint-plugin-vue to parsing SFC.

**Comment by jez9999** [comment]
OK thanks, guess I'll file an issue there.

**Comment by jez9999** [comment]
@johnsoncodehk That issue I opened there got no response.  Out of interest, how do you develop .vue files?  Do you have `lang="ts"` and do you configure ESLint linting to only apply for Typescript and not Javascript?

**Comment by johnsoncodehk** [comment]
@jez9999 I barely use ESLint, Volar's built-in Linting is enough for me.

**Comment by jez9999** [comment]
Does it give warnings about unsafe assignments of `any` typed values?

**Comment by johnsoncodehk** [comment]
Do you have a code sample?
