### ISSUE TITLE
The corresponding closed tag is no longer automatically found in template

### ISSUE THREAD

**Issue by xd-shadow** [johnsoncodehk/volar#2009]
![image](https://user-images.githubusercontent.com/35983043/195607063-82b200bd-6951-4731-ab0f-adf035dbc857.png)
![image](https://user-images.githubusercontent.com/35983043/195607502-bb18c1e6-1b65-44a7-a3dc-f8f98be7879b.png)

When I cursor over a div I don't highlight the corresponding closed tag.It seemed to work before the last update?

**Comment by johnsoncodehk** [comment]
As a workaround, you can setting `vueCompilerOptions.jsxTemplates = true` to avoid this problem.

**Comment by xd-shadow** [comment]
> It's happen after v1.0.0, as a workaround, you can setting `vueCompilerOptions.jsxTemplates = true` to avoid this problem.

Sorry, where is this methods set？

**Comment by xiaoxiangmoe** [comment]
In tsconfig.json,
add

```json

    "vueCompilerOptions": {
        "target": 2.7 or 3 or 2,
        "jsxTemplates": true
    }
```

**Comment by xd-shadow** [comment]
> In tsconfig.json, add
> 
> ```json
>     "vueCompilerOptions": {
>         "target": 2.7 or 3 or 2,
>         "jsxTemplates": true
>     }
> ```

thanks.

**Comment by xd-shadow** [comment]
This does not seem to be possible, and this setting will cause other problems.
![image](https://user-images.githubusercontent.com/35983043/195759100-3ead0ab1-7d15-4650-95e4-756b581c6a5a.png)
ts will think that my <router-view> is wrong.
