### ISSUE TITLE
Volar confuses ref for a component when using kebab-case syntax

### ISSUE THREAD

**Issue by victorgarciaesgi** [johnsoncodehk/volar#2010]
**First thing thanks a lot for making Volar and congrats on 1.0.0!** 

Basically, if I have a component and a ref that have the same name but with different casing (basically: `foo` and `Foo`), Volar will confuse the ref for a component when using kebab-case style. (`<foo/>`)
The error is not here when using PascalCase.

Exemple component: https://codesandbox.io/s/elated-hooks-d9vgsb?file=/src/App.vue

Screenshot is using `<script setup/>`

![image](https://user-images.githubusercontent.com/15092120/195624065-7266c3fa-d01a-41ae-a48d-cb9a7a6d4491.png)

**Comment by innocenzi** [comment]
I have a similar issue here: https://github.com/hybridly/demo/blob/main/resources/views/pages/chirps/show.vue#L21. It also works properly if I use `PascalCase`. 

![CleanShot 2022-10-14 at 16 11 23](https://user-images.githubusercontent.com/16060559/195867949-5fa24488-5b07-4fed-8b57-850cdca81a32.png)


![CleanShot 2022-10-14 at 16 11 50](https://user-images.githubusercontent.com/16060559/195868036-0a46735e-74ef-451d-867d-9f504981d6e0.png)

**Comment by victorgarciaesgi** [comment]
Sorry to reopen @johnsoncodehk , I encountered the same issue, but with class-api this time

![image](https://user-images.githubusercontent.com/15092120/196715433-05896c84-b31c-4117-824e-30c632a83629.png)

**Comment by johnsoncodehk** [comment]
We never supported class component decorations, you can a feature request.
