### ISSUE TITLE
Vue module not found

### ISSUE THREAD

**Issue by liujiayii** [johnsoncodehk/volar#2011]
使用pnpm安装
Vue版本：2
tsconfig: 
```
"paths": {
 "vue": "xxx/xxx/vue"
}
```
这种情况下会报Vue module not found，使用yarn正常

**Comment by xiaoxiangmoe** [comment]
能给一个复现例子吗？

**Comment by liujiayii** [comment]
> 能给一个复现例子吗？

https://github.com/liujiayii/volar-bug
类似这样的情况，开发的轮子脚手架，vue不需要在package.json里安装，引用一个全局路径的vue，

**Comment by xiaoxiangmoe** [comment]
I test it and it has no bug in my computer.

**Comment by liujiayii** [comment]
> I tested it and it has no bug in my computer.

![image](https://user-images.githubusercontent.com/38902744/196473006-a60b37a2-f7e8-48be-9d16-951a93ea8fc7.png)

**Comment by johnsoncodehk** [comment]
> > 能给一个复现例子吗？
> 
> https://github.com/liujiayii/volar-bug 类似这样的情况，开发的轮子脚手架，vue不需要在package.json里安装，引用一个全局路径的vue，

你這個用例doctor也無法正常檢查vue版本，設置`"volar.doctor.statusBarItem": false`禁用提示就好了。
