### ISSUE TITLE
Invalid prop type of global component

### ISSUE THREAD

**Issue by joo1es** [johnsoncodehk/volar#2015]
1.0.7 version:
![Snipaste_2022-10-14_11-55-24](https://user-images.githubusercontent.com/76929557/195759802-f10bbbb1-f4ce-4da3-9d67-6f7c6018b39c.png)
![Snipaste_2022-10-14_11-55-14](https://user-images.githubusercontent.com/76929557/195759810-746c96a9-4870-464f-ba1b-e71960dc8372.png)

0.40.13 version:
![Snipaste_2022-10-14_11-54-32](https://user-images.githubusercontent.com/76929557/195759749-3629156e-7fc0-4b41-b727-dc9ae4d56c27.png)
![Snipaste_2022-10-14_11-54-19](https://user-images.githubusercontent.com/76929557/195759733-93160aea-3aa1-454e-920c-5fd70662e15e.png)

it is a global component defined by unplugin-vue-components
![Snipaste_2022-10-14_11-56-49](https://user-images.githubusercontent.com/76929557/195759699-b363756a-2729-4930-90fd-94015c5289c2.png)

i have no idea why it is happen

**Comment by johnsoncodehk** [comment]
Could you provide minimal reproduction?

**Comment by joo1es** [comment]
https://stackblitz.com/edit/vitejs-vite-njn9ge?file=package.json,src%2FApp.vue,src%2Fenv.d.ts,vite.config.ts

try to run

pnpm run tsc
