### ISSUE TITLE
⚡️ Improving autocompletion DX

### ISSUE THREAD

**Issue by jd-solanki** [johnsoncodehk/volar#2016]
Hi 👋🏻

I am loving the Volar v1 ❤️

I just come across a new DX improvement we can make to Volar.

Assume I want to write `heading` prop via autocompletion as a string so when I do `ctrl` + `space` for automation I get dynamic bindings first and there's no normal/string usage.
<img width="566" alt="Screenshot 2022-10-14 at 12 43 14 PM" src="https://user-images.githubusercontent.com/47495003/195785248-1172bd6a-b82f-43bb-9351-3e628cbd8fce.png">

I get normal attribute completion if I write the prop name further:
<img width="551" alt="Screenshot 2022-10-14 at 12 44 04 PM" src="https://user-images.githubusercontent.com/47495003/195785373-75fe944f-d85d-4175-965f-384237cb3fc2.png">

The above is completely fine and normal but how about the below thought 🤔 

> Assumes `ctrl` for windows & `cmd` for mac

On `ctrl` + `space` we are already showing the props but they use `v-bind`. Now DX improvement is, we will just list the names of the props. Next when the user just presses `enter` we will write the prop name as expected:

> "heading" > `enter` => `<Comp heading="">...</Comp>`

but when user press `cmd` + `enter` we write prop with v-bind:

> "heading" > `cmd` + `enter` => `<Comp :heading="">...</Comp>`

I don't know if this is outside of the scope of volar or not but this is just my thought.

> _P.S. Feel free to close this if isn't relevant 😇_

**Comment by johnsoncodehk** [comment]
Thanks for the the suggestion! I think it can improve the DX in some case, but yes it's outside of the scope of volar, and I'm not sure if VSCode has provide API to access completion list and change the selection item.

If VSCode can do, it could be a single VSCode extension but not depend on Volar, so it can also use for other languages.
