### ISSUE TITLE
vue-tsc is checking libs

### ISSUE THREAD

**Issue by Blackfaded** [johnsoncodehk/volar#2018]
Hey there!

I have a dependency (vue-currency-input) which has a ts error. 
With the new vue-tsc version the lib also gets checked somehow and breaks my build pipeline because of this error.
Even if my tsconfig states that `skipLibCheck` is `true` and excluded `node_modules`.

For details you can track the issue [here](https://github.com/NightCatSama/vue-slider-component/issues/649)

Thanks in advance!

**Comment by johnsoncodehk** [comment]
`exclude ` and `skipLibCheck` cannot ignore library types errors that you have already direct or indirect reference with it in your code. You can see more explain here: https://stackoverflow.com/questions/59906323/typescript-skiplibcheck-still-checking-node-modules-libs

A way you can try is **stub**: https://github.com/johnsoncodehk/volar/discussions/592#discussioncomment-2163786
