### ISSUE TITLE
Prop types incorrect if duplicate name with HTMLAttributes

### ISSUE THREAD

**Issue by aki77** [johnsoncodehk/volar#202]
Thanks for the great extension!

The following error, which was fixed previously, seems to be recurring.
https://github.com/johnsoncodehk/volar/issues/41#issuecomment-757562573

![Image from Gyazo](https://i.gyazo.com/a2356a40e19bb4f1b2d74e8e24575880.gif)

**Comment by johnsoncodehk** [comment]
Thanks for your report, but this is expected behavior, you should change `:on-click` to `@click`.

**Comment by aki77** [comment]
Thanks for the reply.
Most of my projects are still written in Vue2 & composition api & typescript.
In that case, I prefer props because it cannot be typed in `@emit`.

There may be other cases where Intersection types with HtmlAttributes is inconvenient.

![Image from Gyazo](https://i.gyazo.com/c7508cc00fc8a0dfa9907825eaa4d744.gif)

**Comment by johnsoncodehk** [comment]
`:on-click="count++"` indeed transfer a number to component, this is correct type error. And I think this is a bug in your project, `count++` is trigger every time on rendering, not trigger on click.

If you don't want to use `@click`, you can use `:on-click="() => count++"`, that will correctly transfer a function to component.

HtmlAttributes props type override will be support in 0.25.12.

**Comment by aki77** [comment]
Thank you for the quick support!
The `:on-click` example may have been inappropriate as I wrote it too simply.
