### ISSUE TITLE
Add special tags to response variables to distinguish between ordinary variables and response variables

### ISSUE THREAD

**Issue by alqmc** [johnsoncodehk/volar#2020]
Add special tags to response variables to distinguish between ordinary variables and response variables

```vue
<script lang="ts" setup>
const test(Color or Superscript) = reactive({
  test: 111,
})

const test1(Color or Superscript) = ref({
  test: 222,
})

const test1 = {
  test: 333,
}
</script>
```
Marked variables can be easily known wherever they are used.

Marks can be color or corner marks or other better ways.

This allows you to easily distinguish between responsive variables.

In this way, vue can also discard the .value burden directly. If want ？

Because I want to abandon Value, but I'm afraid we can't distinguish between responsive variables. Of course, this problem already exists in reactive

**Comment by johnsoncodehk** [comment]
There is no reliable way to achieve this as far as I know, maybe you can use `"volar.autoCompleteRefs": true`.
