### ISSUE TITLE
Volar doesn't recognize .tsconfig file and throws error

### ISSUE THREAD

**Issue by Readpato** [johnsoncodehk/volar#2021]
### Issue

Working on Vue files, Volar wont recognize the `.tsconfig` file that exist on the project but for others it does.

### Error display

![image](https://user-images.githubusercontent.com/87768087/195872198-49d6f26d-f421-4642-86d2-c4aef11d5c1d.png)

```
[Error - 4:19:54 PM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'applyed')
  Code: -32603 
[Error - 4:19:59 PM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
[Error - 4:20:00 PM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
[Error - 4:20:10 PM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
[Error - 4:21:33 PM] Request textDocument/documentColor failed.
  Message: Request textDocument/documentColor failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
[Error - 4:21:33 PM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
[Error - 4:21:33 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
[Error - 4:21:33 PM] Request textDocument/linkedEditingRange failed.
  Message: Request textDocument/linkedEditingRange failed with message: Cannot read properties of undefined (reading 'version')
  Code: -32603 
  ```

### How to reproduce it?

This seems to happen randomly so I don't have a precise way of replicating it. What I can say is that lately I find myself refreshing the VSCode environment more often through the `Developer: Reload window` command and maybe that's something that affects Volar?

### Steps taken to solve it but ended with no solution

- Rename file to another name doesn't solve the issue.
- Deleting and creating a new file doesn't solve the issue.
- Added `"src/*": ["./src/*"]` to `compilerOptions.paths`
- Installed [tsconfig helper](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper) from the market place but it doesn't work. Weirdly enough though, the extensions seems to notice that it's a Vue file, but Volar doesn't recognize it. See images below.

Description: Focused on the `VerticalHeader.vue` file the `tsconfig.json` is not recognized, but the `tsconfig helper` app does recognize it. Volar displays a snackbar error on the lower right and in the console is the error that's produced when entering the file.
![image](https://user-images.githubusercontent.com/87768087/195872575-d3072eeb-e9e5-4067-b7a3-51d8f33ddff3.png)

On another file of the same project, the `tsconfig.json` is recognized and Volar doesn't throw an error when the file is focused.
![image](https://user-images.githubusercontent.com/87768087/195872910-2b824498-64cd-4f38-8697-74dae069c9dd.png)

**Comment by johnsoncodehk** [comment]
I'm almost sure error occur on https://github.com/johnsoncodehk/volar/blob/master/packages/language-server/src/utils/snapshots.ts, but don't know why. A thing you can try is that setting `"volar.vueserver.textDocumentSync": "full"` to disable incremental logic from the script, it will reduce performance but maybe avoid the problem to you.

**Comment by johnsoncodehk** [comment]
@Readpato are you still have this problem in the latest version?
