### ISSUE TITLE
Default vue-tsc --init produces incompatible Vite tsconfig.json file. compilerOptions.target is ES2016 and import_meta.hot fails.

### ISSUE THREAD

**Issue by JessicaSachs** [johnsoncodehk/volar#2022]
### Reproduction

Broken: https://github.com/JessicaSachs/vue-tsc-init
Working: https://github.com/JessicaSachs/vue-tsc-init/compare/develop...working

### Issue

I wasn't able to build a simple Vite + Vue 2.7  application yesterday due to:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'accept')
```

when running `vite` after generating a simple app.

<img width="861" alt="Screen Shot 2022-10-14 at 12 59 11 PM" src="https://user-images.githubusercontent.com/2801156/195901661-df6975eb-a683-40f5-b3de-23a1f2f81aee.png">

It took me a long time to debug, but I finally figured out it was because of the `tsconfig.json` I'd generated using `vue-tsc`

### Steps to reproduce:

1. Make a new project with bare Vite + Vue 2.7 setup
2. Run `pnpm vue-tsc --init`
3. Run `vite`
4. See `import_meta.hot` is not a function error.

**Here is the transpiled output:**

<img width="500" alt="Screen Shot 2022-10-14 at 12 58 19 PM" src="https://user-images.githubusercontent.com/2801156/195901535-c77624ac-f4b5-43e7-b15b-258865bdf02d.png">

### Workaround
Change `compilerOptions.target` to "`ES2020`" and see that the issue is fixed

### Suggested solution

Can we default `vue-tsc --init` to have a target >= ES2020?

**Comment by JessicaSachs** [comment]
It was confusing because when I **deleted** my `tsconfig.json` file, the internals of Vite were able to transpile my TypeScript code with no problem. 😅

**Comment by johnsoncodehk** [comment]
I never know vite.config depend with tsconfig.json 😅, but we can't change `vue-tsc --init` because we just proxying `tsc`:
https://github.com/johnsoncodehk/volar/blob/master/vue-language-tools/vue-tsc/bin/vue-tsc.js

Maybe we can ask vite show a warning for ES2016.

**Comment by JessicaSachs** [comment]
@johnsoncodehk I ran into this again. We need to show a warning or something. I _happened_ to remember that I ran into this and did a GitHub search for `import_meta`. Where do you think we should show a warning?
