### ISSUE TITLE
The custom global properties defined in `ComponentCustomProperties` are not recognized

### ISSUE THREAD

**Issue by kecrily** [johnsoncodehk/volar#2029]
## Summary

[`unplugin-auto-import`](https://github.com/antfu/unplugin-auto-import) use [`ComponentCustomProperties`](https://vuejs.org/api/utility-types.html#componentcustomproperties) util to define custom global properties in Vue template. But `vue-tsc` can't recognize them.

## Error

```sh
src/App.vue:2:6 - error TS2339: Property 'title' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & Readonly<...> & Sha...'.

2   {{ title }}
```

## Reproduction

Open <https://stackblitz.com/edit/vitejs-vite-i9vaiv>

Run

```sh
pnpm vue-tsc --noEmit
```

**Comment by johnsoncodehk** [comment]
Due to you are using pnpm, you should add `@vue/runtime-core` to dependencies in package.json, or change `declare module '@vue/runtime-core'` to `declare module 'vue'`.

Another problem is you need add `auto-imports.d.ts` to include option in tsconfig.json.
