### ISSUE TITLE
[Bug] The same component shows twice in IntelliSense

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#203]
Screenshot: 

![image](https://user-images.githubusercontent.com/28700378/119279143-55f40280-bc5c-11eb-824c-63eef3aaeba7.png)

**Comment by johnsoncodehk** [comment]
Can this problem reproduce in v0.25.14?

**Comment by wenfangdu** [comment]
No, it's fixed. Thanks for the fast fixes!
