### ISSUE TITLE
Component from RouterView error when update vue-tsc

### ISSUE THREAD

**Issue by gabrielmorais4** [johnsoncodehk/volar#2030]
Hello, I'm trying to update vue-tsc, but when it comes to the version 0.38.8 and higher versions, I'm having some error messages and I can't find a way to fix it!!!

![Captura de tela de 2022-10-17 11-08-15](https://user-images.githubusercontent.com/91679828/196137545-49ef4219-f584-448b-b25b-36d8d3468e51.png)

The **Component** comes from RouterView and the errors are:

![Captura de tela de 2022-10-17 11-11-11](https://user-images.githubusercontent.com/91679828/196138437-dbde3e1f-a662-4c57-b1df-5f529b348389.png)

And the other ones happens when I try to build the project

![Captura de tela de 2022-10-17 11-13-35](https://user-images.githubusercontent.com/91679828/196138739-63fa094c-e44f-4b4f-8051-0003d49f57ac.png)

These are my  dependencies:

![Captura de tela de 2022-10-17 11-16-31](https://user-images.githubusercontent.com/91679828/196139440-cef73d0e-3144-4692-9dc3-7ec065bbef7d.png)

**Comment by gabrielmorais4** [comment]
It works!!! Thanks :)

**Comment by gabrielmorais4** [comment]
It works!!! Thanks :+1:

**Comment by johnsoncodehk** [comment]
Reopen this issue because it's a bug. 😅
