### ISSUE TITLE
<MyLib.SomeComponent ../> automatically changes to <MyLib class="SomeComponent" .../>

### ISSUE THREAD

**Issue by zjbarg** [johnsoncodehk/volar#2033]
![Peek 2022-10-18 01-05](https://user-images.githubusercontent.com/26728749/196292679-955b4b10-2381-4f88-8130-83a7377cbb66.gif)

The correction happend on save.
I understand the idea behaind this, but is there a workaround to prevent this from happening?

**Comment by johnsoncodehk** [comment]
The default HTML formatter working with vscode-html-languageservice -> js-beautify, you can report to https://github.com/beautify-web/js-beautify.

And you can also change HTML formatter to [prettyhtml](https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettyhtml) or [prettier](https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettier).

**Comment by zjbarg** [comment]
Thx
