### ISSUE TITLE
🐛 BUG:  Vue Semantic Server is crashing in multi root workspace with message

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [johnsoncodehk/volar#2039]
Type: <b>Bug</b>

Vue Semantic Server is crashing in multi root workspace with message 
```
[Info  - 11:58:46 AM] Connection to server got closed. Server will restart.
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir '<workspaceRoot>\apps\<app1>' -> '<workspaceRoot>\libs\<lib1>'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (<home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:497:23691)
    at <home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:496:33997
    at Generator.next (<anonymous>)
    at <home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:496:33517
    at new Promise (<anonymous>)
    at Ss (<home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:496:33314)
    at f2e (<home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:496:33808)
    at Object.add (<home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:496:38612)
    at <home>\.vscode-insiders\extensions\vue.volar-1.0.8-win32-x64\dist\node\server.js:497:20221 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '<workspaceRoot>\\apps\\<app1>',
  dest: '<workspaceRoot>\\libs\\<lib1>'
}
```
![image](https://user-images.githubusercontent.com/86342787/196682304-8ae38bbc-33a3-404c-b05d-33f625e83e1e.png)

Extension version: 1.0.8
VS Code version: Code - Insiders 1.73.0-insider (7ea2788a43a4c35d8da63a419725ba2485de395b, 2022-10-19T05:28:16.879Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (0.91GB free)|
|Process Argv|--log-net-log=netlog.json --ignore-certificate-error --crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
pyind367:30587847
vscccc:30564267
pyindex848cf:30577859
nodejswelcome1:30587009

```

</details>

**Comment by johnsoncodehk** [comment]
This error occurs at https://github.com/johnsoncodehk/volar/blob/bf661eb740e6c351d26721d10bb14cdfba238478/packages/language-server/src/utils/nodeFileSystemHost.ts#L62

Is `<workspaceRoot>\\libs\\<lib1>` a valid path on your OS?
