### ISSUE TITLE
Can't import type of component in composable

### ISSUE THREAD

**Issue by szulcus** [johnsoncodehk/volar#2042]
In `*.vue`:
![Zrzut ekranu 2022-10-21 132905](https://user-images.githubusercontent.com/48328739/197185966-d5d5c876-b5ef-4238-af54-c275e05356be.png)
![image](https://user-images.githubusercontent.com/48328739/197185553-2b4ef589-9b03-4932-947c-dd3e5eb8ec61.png)

In `*.ts`:
![image](https://user-images.githubusercontent.com/48328739/197185385-c8ef8dc6-1a04-47fc-b75a-4c8e9cd17b08.png)
![image](https://user-images.githubusercontent.com/48328739/197185678-75ca2f40-64d9-4a16-801b-216bc4ab082c.png)

Is this the expected behavior?

**Comment by xiaoxiangmoe** [comment]
You can install [vscode-typescript-vue-plugin](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) or use [Take Over Mode](https://github.com/johnsoncodehk/volar/discussions/471)

**Comment by szulcus** [comment]
> You can install [vscode-typescript-vue-plugin](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) or use [Take Over Mode](https://github.com/johnsoncodehk/volar/discussions/471)

Thank you very much!
