### ISSUE TITLE
Unexpected signature help popup at the root of Vue component

### ISSUE THREAD

**Issue by Wetoria** [johnsoncodehk/volar#2044]
Issue Summary:

- Unexpected signature help popup at the root of Vue component

---

Sorry, I really have no idea about this issue, Can somebody help me?

When I type `,` in my vs code, it will show this widget, and disturbed my typing.

I used to type `,` and use down arrow to switch line, but it will be change the page of the widget content.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/16909518/197304686-f79c0ac1-29ae-4ada-ad56-3fc2467ee7c6.png">

I really have no idea to solve it, Can somebody tell me how to fix it?

**Comment by CheIIau** [comment]
It has nothing to do with Volar. It's vscode thing

**Comment by Wetoria** [comment]
> The data is coming from Volar and Volar is in a position to do something about that.
> 
> To the user it's an exported object (`export { ... }`) and the fact that it's a function call is an internal detail of Volar due to Volar wrapping the object into a `defineComponent` call so I would argue that signature help at the root of the Vue component is quite annoying and not necessarily expected.
> 
> @Wetoria can you update issue summary to something more descriptive like "Unexpected signature help popup at the root of Vue component"?

@rchl Hey bro, I changed the contents, am I right?

I'm not sure about it. Plz forgive my poor english and lack of experience about GitHub.

**Comment by rchl** [comment]
I meant the main issue title:

<img width="841" alt="Screenshot 2022-10-27 at 12 55 40" src="https://user-images.githubusercontent.com/153197/198266549-0cae9b0e-76df-4bcc-b831-3b21f8f54def.png">

**Comment by Wetoria** [comment]
> I meant the main issue title:
> 
> <img alt="Screenshot 2022-10-27 at 12 55 40" width="841" src="https://user-images.githubusercontent.com/153197/198266549-0cae9b0e-76df-4bcc-b831-3b21f8f54def.png">

Thanks, done of it.

**Comment by johnsoncodehk** [comment]
This is TypeScript's bug, it can be reproduce in vanilla .js file, please report to TypeScript repo.

```js
// test.js
(await import('vue')).defineComponent({
  data: () => {}, // input , can reproduce the problem
})
```

**Comment by rchl** [comment]
This is expected when writing such JS code so I don't really see the point of reporting it to Typescript.

When using Volar, the user is not explicitly writing such JS code. The fact that `defineComponent` wraps the object is an internal detail that is not visible to the user. So in that case I would say that it's unexpected and only Volar can do something about it.

I think Volar could in that case suppress the signature response though I don't know if it would be easy to detect this specific case...
