### ISSUE TITLE
 Cannot read property 'getSourceRange' of undefined

### ISSUE THREAD

**Issue by 1xuanyuan1** [johnsoncodehk/volar#2045]
"@volar/vue-language-plugin-pug": "^1.0.8"
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6700408/197346943-bcbd720f-49c3-4f12-ba67-bb48b5d6fb82.png">

**Comment by richex-cn** [comment]
This issue seems to have been introduced in 1.0.0-beta.2

https://github.com/johnsoncodehk/volar/commit/87487f067421eceabc56ec26b04ad69f7d2f67ee#diff-3f02f717706f1de4f83b88691390f512429779f84be407d164ee989ecaefa568L67

I try to install the 1.0.0-beta.1 release and it works.

**Comment by johnsoncodehk** [comment]
Please make sure update `vue-tsc` and `@volar/vue-language-plugin-pug` both to the latest version.
