### ISSUE TITLE
[BUG] When using @headlessui/vue, VS Code gets stuck at "Initializing JS/TS language features"

### ISSUE THREAD

**Issue by bartenra** [johnsoncodehk/volar#205]
When I use some specific components from [@headlessui/vue](https://github.com/tailwindlabs/headlessui), VS Code freezes at "Initializing JS/TS language features".

I created a repro here: https://github.com/bartenra/ts-extension-freeze-repro

Just hover over anything in `main.ts` and the Typescript plugin will get stuck at ""Initializing JS/TS language features"

VS Code 1.56.2
Volar 0.25.12

**Comment by johnsoncodehk** [comment]
Thanks for the report. This problem from VSCode, VSCode TS server expect a TS document but currently is Vue document. This progress will finish when you open `*.ts` file.

**Comment by bartenra** [comment]
`*.vue` works fine but `*.ts` files have no type on hover, completion and I can't even save them.

**Comment by cwaring** [comment]
I also hit this issue today after wondering why VSCode was locked at 99% cpu utilization. Subscribing for more info but if there is a temporary workaround or a better place to report the issue please lmk 😄

**Comment by cwaring** [comment]
I ran a couple of experiments with my codebase against clean install of vscode insiders and I can confirm that the `Initializing JS/TS language features` stuck process only happened upon enabling volar. I suspect there is a conflict somewhere but I'm unsure how to debug this further? Currently vetur isn't presenting the same issue for me.

**Comment by johnsoncodehk** [comment]
@cwaring VSCode Insider has a known performance issue (https://github.com/johnsoncodehk/volar/issues/162#issuecomment-842296289), please try VSCode without Insider version.

**Comment by cwaring** [comment]
Thanks @johnsoncodehk. Interesting to know about the Insider version troubles as this sounds like the same CPU spike issue that I am receiving in the stable release *only* when I enable the TS plugin. With the TS plugin disabled `Initializing JS/TS language features` resolves in a couple of seconds without a CPU spike.

Version info (w/ volar v0.25.12):
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
```

I'll try again with the template posted by @bartenra to see if this could be related to my current project setup somehow.

**Comment by johnsoncodehk** [comment]
> the stable release only when I enable the volar TS plugin

I reproduced the problem, thanks for mentioning it!

**Comment by johnsoncodehk** [comment]
Found the problem finally. This problem come from TS, TS server freeze by special invalid content.

```ts
// foo.ts
<div
  foo
  static
  class
></div>
```

Repro: https://github.com/johnsoncodehk/ts-extension-freeze-repro

**Comment by johnsoncodehk** [comment]
Added a patching for this TS bug in 0.25.13.

**Comment by bartenra** [comment]
You're awesome!!

**Comment by cwaring** [comment]
amazing, thanks for the fast turn around @johnsoncodehk! confirmed that 0.25.13 fixed the issue 🏆

**Comment by WhatFreshHellIsThis** [comment]
The endless "INitializing JS/TS language features"  is a known issue with many previously closed cases and no actual resolutions to the underlying issue. I see it all the time when working with Vue / Vuetify projects but there seem to  be endless triggers to it which seems to indicate a bigger issue here that no one is addressing comprehensively.

**Comment by johnsoncodehk** [comment]
@WhatFreshHellIsThis see the original explanation from https://github.com/johnsoncodehk/volar/issues/205#issuecomment-847815398
