### ISSUE TITLE
When import .vue file Ctrl + Click can not jump to the definition

### ISSUE THREAD

**Issue by CheIIau** [johnsoncodehk/volar#2052]
When import .vue file, Ctrl + Click can not jump to the definition anymore, and the path intellisense can not find .vue file too.

Howerver, it works in v0.40.13 and before.

behavior in v0.40.13:
![2022-10-23 19-26-12](https://user-images.githubusercontent.com/58114735/197404008-c0ce9343-b942-4bba-95f6-8c2f444d1342.gif)

behavior after v0.40.13:
![2022-10-23 19-24-22](https://user-images.githubusercontent.com/58114735/197404051-aef2a307-842a-4be8-bbe2-d02902d7ffee.gif)

Actually, there was an issue similar to this before
https://github.com/johnsoncodehk/volar/issues/435
The problem seems to be back

**Comment by mikehaertl** [comment]
I see a similar issue in neovim after upgrading to 1.x but it affects more:

Filetypes (using take-over mode): typescript, js and vue

Methods: Hover, goto definition, code actions.

Neovim gives me:

 * method textDocument/definition is not supported by any of the servers registered for the current buffer
 * method textDocument/hover is not supported by any of the servers registered for the current buffer
 * method textDocument/codeAction is not supported by any of the servers registered for the current buffer

**Comment by Cgboal** [comment]
I'm getting the same with neovim.

**Comment by KarmaBlackshaw** [comment]
I am having the same issue.

Here's what the Vue Semantic Server is logging. I'm not sure if its related tho
```bash
  - c:/Users/Administrator/.vscode/extensions/ms-vscode.vscode-typescript-next-5.0.20221103/node_modules/typescript/lib/lib.dom.d.ts
    size: 816717
    ref counts: "2|5|true|1|false|undefined|undefined|j:/outliant/sunrise/dashboard|{@/*: [./src/*]}|undefined|undefined|undefined|undefined|undefined|undefined|undefined|undefined|undefined|2|undefined|j:/,)"
```
And here's my jsconfig
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "es6",
    "target": "es6",
    "jsx": "preserve",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": ["node_modules", "dist"],
  "vueCompilerOptions": {
    "target": 2.7,
    "jsx": "preserve"
  }
}
```

**Comment by johnsoncodehk** [comment]
@CheIIau could you try can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?

**Comment by CheIIau** [comment]
@johnsoncodehk  hm, on volar-starter repository it seems to work properly. then i don't understand why it doesn't work in my project. i noticed that if you import file using path like '../../bar.vue' you can jump to the definition and everything works. but if you import your vue file using ts alias like 'src/components/bar.vue' it doesn't work. but again everything workes in my project on volar v0.40.13 and older versions. can't tell exactly why is it happening. please, write if you need more info

my ts config:

{
  "extends": "@quasar/app-vite/tsconfig-preset",
  "compilerOptions": {
    "useUnknownInCatchVariables": false,
    "baseUrl": ".",
    "paths": {
      "src/*": [
        "src/*"
      ],
      "app/*": [
        "*"
      ],
      "components/*": [
        "src/components/*"
      ],
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}

**Comment by CheIIau** [comment]
i noticed that problem occurs in quasar projects, even in a just created one (default and clean). i created them with quasar cli. in default vue project everything works fine. it seems to be some kind of conflict between quasar and volar, idk. but it's strange that everything works properly on v0.40.13 and below.

**Comment by johnsoncodehk** [comment]
Unfortunately I can't reproduce the problem even use your tsconfig, what's your OS?

If you can provide minimal reproduction or create a test case to https://github.com/johnsoncodehk/volar/tree/master/vue-language-tools/vue-test-workspace/find-definition it will be very helpful.

**Comment by CheIIau** [comment]
i tried it on windows 11 and 7

**Comment by johnsoncodehk** [comment]
I fixed a bug that most likely caused this issue, please let me know if it still doesn't work in the next version.

**Comment by CheIIau** [comment]
No, I still facing the bug. I noticed that it only happens if you use "export default defineComponent({})", not script setup. With script setup all seems to be fine. And the problem even appears for me in your volar-starter project, when i changed script setup to usual script with export default defineComponent in HelloWorld component. I didn't notice this before because I didn't think it could be the case and didn't try to change it for export default.

**Comment by hymair** [comment]
Facing the exact same issue in a Vue 2.7 project. @johnsoncodehk please re-open.

**Comment by tanpengsccd** [comment]
got same error Volar 1.2.0 with vue: ^3.2.45

**Comment by johnsoncodehk** [comment]
This issue is obsolete, if it reappears it is probably for a different reason, please open a new issue and provide a repro case.

**Comment by oshliaer** [comment]
#4063 can be a solution.
