### ISSUE TITLE
Invalid prop type of global component with unplugin-vue-components

### ISSUE THREAD

**Issue by joo1es** [johnsoncodehk/volar#2054]
i made a minimal reproduction

[minimal demo](https://stackblitz.com/edit/vitejs-vite-gfttsz?file=package.json,src%2FApp.vue,src%2Fenv.d.ts,vite.config.ts,tsconfig.json,src%2Fmain.ts)

typescript version is 4.8, vue-tsc version is 1.0.9, try to run vue-tsc

`vue-tsc`

![image](https://user-images.githubusercontent.com/76929557/197463492-96146900-3d85-401c-b663-4b25c9d6364e.png)

the "text" prop of ElButton requires `boolean`, but `number` not get an error
the "onChange" prop of ElSwitch provide current type, but got an error

and the types of components:

![image](https://user-images.githubusercontent.com/76929557/197465492-32f8fd39-b4db-4a00-b9c3-8ccde0dfc297.png)

---

if i import them, it is ok.
[import demo](https://stackblitz.com/edit/vitejs-vite-wvsspp?file=vite.config.ts,tsconfig.json,components.d.ts)

![image](https://user-images.githubusercontent.com/76929557/197465601-ba03c8d8-a38c-4c0d-900d-b92d84a7ef26.png)

**Comment by slauzinho** [comment]
Same issue happening for me after upgrading to `vue-tsc: 1.0.9`.

```
"vue-tsc": "^1.0.9"
"vue": "^3.2.41",
"typescript": "^4.8.4",
"unplugin-auto-import": "^0.11.4",
 "unplugin-vue-components": "^0.22.9"
```

**Comment by slauzinho** [comment]
Another repo using the default vitesse template: https://github.com/slauzinho/my-vitesse-template

Notice the `Counter` component defines the emits:
```ts
defineEmits<{
  (event: 'test', count: string): void
}>()
```

then on `index.vue` we have:

```html
 <Counter :initial="3" @test="printValue" />
```

If we hover on the `@test` we see it has the type of `any`:
![CleanShot 2022-11-08 at 14 54 16](https://user-images.githubusercontent.com/445345/200597279-85519744-f7a6-4433-aeb8-7d28c805d0c1.png)

**Comment by Aicmortal** [comment]
me too

**Comment by Aicmortal** [comment]
@johnsoncodehk hello,Is there a solution?

**Comment by johnsoncodehk** [comment]
See https://github.com/antfu/unplugin-vue-components/issues/177#issuecomment-1120460576
