### ISSUE TITLE
.ts file text color disorder

### ISSUE THREAD

**Issue by SD-Gaming** [johnsoncodehk/volar#2055]
![image](https://user-images.githubusercontent.com/25575589/197473507-861fd46a-b7de-4384-a77e-34445c194520.png)

TypeScript Vue Plugin (Volar)
v1.0.9 take over mode
Vue Language Features (Volar)
v1.0.9

---

and 2 unhandled errors show in the Vue Language Features (Volar) runtime status:
```
Request volar/detectTagCasing failed with message: Cannot read properties of undefined (reading 'context')
Request volar/detectTagCasing failed with message: Cannot read properties of undefined (reading 'context')
```

**Comment by rchl** [comment]
Likely a symptom of #1807.

**Comment by johnsoncodehk** [comment]
Duplicate of #1807
