### ISSUE TITLE
vue-tsc type check failing with reactivity transform 

### ISSUE THREAD

**Issue by StepanMynarik** [johnsoncodehk/volar#2059]
Hi,

the following code
```typescript
const { list, containerProps, wrapperProps, wrapperHeight } = $(
  useVirtualList($$(floatingRef), $$(items as ReactiveVariable<T[]>), {
    itemHeight: (i) => items[i].height,
    overscan: 10,
  })
);
```
![image](https://user-images.githubusercontent.com/46678816/197630371-3d080dfa-b15c-4ff5-ae7a-cdd1be388170.png)

is throwing the following error
![image](https://user-images.githubusercontent.com/46678816/197629486-953c9eba-1a02-4237-972a-b76e6e05b27e.png)
upon calling ```vue-tsc --noEmit -p tsconfig.test.json --composite false```

Is this a Volar issue? Or perhaps something I did wrong?
In VSCode, these errors are not shown.
When I run the app, everything works flawlessly.
It is just the vue-tsc type check that throws these errors.

Where did the JQuery type mentioned in the error come from? I have no JQuery anywhere in my type definitions as you can see in the code samples above, nor do I have it anywhere else in my project.

**Comment by johnsoncodehk** [comment]
Please make sure you have using the same tsconfig with VSCode shows at status bar.

<img width="150" alt="螢幕截圖 2022-11-28 22 41 56" src="https://user-images.githubusercontent.com/16279759/204305657-50c2be56-a57a-459a-bbc8-294c19cceaf4.png">
