### ISSUE TITLE
[Bug] Component rename breaks the component source file

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#206]
For reproduction, make sure to turn "Volar Vue TS Server Plugin" on, it's not reproducible otherwise.

Repro: https://github.com/wenfangdu/volar-rename-component-repro

![volar](https://user-images.githubusercontent.com/28700378/119500565-8641bb00-bd9a-11eb-92a8-09213ab7cbda.gif)

**Comment by IWANABETHATGUY** [comment]
can't reproduce 

https://user-images.githubusercontent.com/17974631/119633033-eccee380-be43-11eb-9c01-1ac22d9005a9.mp4

**Comment by IWANABETHATGUY** [comment]
I could reproduce after turn on vue ts plugin
