### ISSUE TITLE
Add validator support to defineProps

### ISSUE THREAD

**Issue by JessicaSachs** [johnsoncodehk/volar#2061]
## Why
I'd like to have support for `validators` so that the non-TS consumers of my component library will be able to have runtime warnings. I'd like to generate the validators based on simple types.

I don't know if this is possible.

### Always create runtime validator if the type is a union.
```ts
const BUTTON_TYPES = ['primary', 'secondary', 'tertiary'] as const
type MyButtonType = typeof BUTTON_TYPES[number]

defineProps<{
  type: MyButtonType
}>() // compiles down to `validator: t => BUTTON_TYPES.includes(t)`
```

### Problems

I think there may be a lot of problems with this approach. Are there current thoughts on how to support validators within `<script setup>`? Is this discussion better for the Vue Core repo?

**Comment by xiaoxiangmoe** [comment]
Yes. We should discuss runtime semantics in the Vue Core repo.
