### ISSUE TITLE
formatting work different after I update volar

### ISSUE THREAD

**Issue by shuwanghu** [johnsoncodehk/volar#2063]
In previous versions of Volar, formatting work like this:
```
<component :prop1=''
    :prop2=''
    :prop3=''
    :prop4=''
    :prop5=''
>
</component>
```
but now , it work like this:
```
<component :prop1='' :prop2='' :prop3=''
    :prop4='' :prop5=''>
</component>
```
I want go back to the frist , what should I do
(ps: my English is not good , forget Syntax error in the issue，thanks)

**Comment by shuwanghu** [comment]
I realy need help ， my team are suffering by this

**Comment by ms-mayya** [comment]
You can downgrade to last version of Volar before update.

**Comment by shuwanghu** [comment]
> 

I don't know what the version before I update

**Comment by shuwanghu** [comment]
> You can downgrade to last version of Volar before update.

I don't know what the version before I update

**Comment by shuwanghu** [comment]
> maybe you can use Prettier to format code

thrank for you advise.I never use prettier before，I don't know it's config. I don't want to spend long time to find out how config prettier that can make it work as I want, because volar work good except this problem. but if the problem can't resolve for long time，I will try prettier.

**Comment by johnsoncodehk** [comment]
You should use https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettyhtml after v0.34.0, see:
- #1078
- https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0340-2022410

**Comment by mech01nc01** [comment]
you could also use this setting in vscode:
"html.format.wrapAttributes": "force-aligned"
