### ISSUE TITLE
Takeover mode doesn't play nice with Quokka.js

### ISSUE THREAD

**Issue by NicolaasVB** [johnsoncodehk/volar#2068]
I'm not entirely sure whether I should be posting this issue over here, or in the repo of Quokka.js, but here goes...

When using Volar in TakeOver mode (and as suggested, disabling the builtin TypeScript and JavaScript Language Features), I lose all Typescript language support within Quokka.js typescript files.

How to reproduce:
- Disable TypeScript and JavaScript Language Features
- Enable TypeScript Vue Plugin (Volar)
- Quokka.js: New Typescript File
- const a: string = 5;

Expected: red squiggly line below "a", complaining that "Type 'number' is not assignable to type 'string'"
What we get: nothing... it doesn't complain

**Comment by johnsoncodehk** [comment]
You should use [Vue Language Features (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.volar) instead of [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin), see https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode.

**Comment by NicolaasVB** [comment]
Even when only using Vue Language Features without the Typescript Vue Plugin, I'm getting the same issue.

I think TakeOver mode just doesn't detect that it has to apply TS language features to a quokka ts file...

**Comment by NicolaasVB** [comment]
@johnsoncodehk 

I think I discovered what's going wrong... It's not really an issue with Quokka, but a feature mismatch with the default Typescript language support extension vs the Vue Language Features extension.

When using the @builtin Typescript language features, when you open a new file (ctrl+n) without saving, and just start typing Typescript code, you get TS language support right away.
When using the Vue Language Features extension, when opening a new file without saving, you do not get TS language support until you actually save the file.

**Comment by johnsoncodehk** [comment]
@NicolaasVB language supports for untitled files is limited in volar language server, you can't use auto-complete / lining..., only syntactic features like formatting / folding ranges are working.

**Comment by NicolaasVB** [comment]
What is the reason for this? I'm guessing that Quokka internally works with an untitled file, hence why it works just fine with the builtin TS language support, and not Volar... Is this something that can be added, or is this not happening?
If it's not happening, what do you suggest I do to also get TS language support in Quokka files?

**Comment by johnsoncodehk** [comment]
We just considered the maintenance cost and didn't implement it, if you really need untitled files support, you can use `TypeScript Vue Plugin (Volar)` instead of takeover mode.

**Comment by NicolaasVB** [comment]
Ok, thanks a lot, much appreciated.
