### ISSUE TITLE
Computed type and Discriminated Union

### ISSUE THREAD

**Issue by dvnrsn** [johnsoncodehk/volar#2073]
I hope this is the correct place to document this issue.

Reproduction
https://github.com/dvnrsn/repro-vue/blob/main/src/components/HelloWorld.vue#L18

Type discrimination is failing between <script> and <template>. Here we see `props.food` is clearly established as type Salad but TS gives us warning showing the type has not yet been discriminated. 

```
Property 'dressing' does not exist on type 'Salad | Burrito'.
```

![image](https://user-images.githubusercontent.com/9112811/198577722-939ea5ad-9a0a-4f87-b3c3-f1d4bd96deb2.png)

Note: this is not resolved by the removal of "computed"

**Comment by johnsoncodehk** [comment]
This is expected TS behavior, you can use `'dressing' in props.food ? props.food.dressing : 'none'` to replace `isSalad ? props.food.dressing : 'none'`.
