### ISSUE TITLE
How to disable auto complete?

### ISSUE THREAD

**Issue by abhijeetj100** [johnsoncodehk/volar#2076]
Hey team,

Apologies if either this isn't the correct place for this question or it's a duplicate (I couldn't find an existing one).

I have been using Vetur for a while now with Vue2, and recently during the migration process to Vue3, I started using the Volar extension for VSCode.

As a personal preference, I like to keep the auto-completion switched off for `<template>` body in a vue file, I am good with the auto-suggestions though.

Could someone help me switch the auto-completion off?

![auto completion volar](https://user-images.githubusercontent.com/33035102/198814625-68378ac7-2613-4bcd-b9b1-34db3dc002dd.gif)

If you see here, currently it auto-completed the tag to `</div>`. How to switch that off?

Thanks in advance! 🙂
Abhijeet

**Comment by johnsoncodehk** [comment]
You can config `"html.autoClosingTags": false` in VSCode settings to disable it.
