### ISSUE TITLE
Support for jump to template code from WebView

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#208]
This feature currently is experimental and rely to install [@volar/experimental](https://github.com/johnsoncodehk/volar/tree/master/packages/experimental).

Hope to achieve without configuration, but it may not be possible.

https://user-images.githubusercontent.com/16279759/119563799-9bd6d500-bdda-11eb-85ee-eebbd5b5a59e.mov

**Comment by oliverzy** [comment]
It's absolutely a killer feature，😄
