### ISSUE TITLE
Infinite Loop on organizing imports on save

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [johnsoncodehk/volar#2080]
Type: <b>Bug</b>

When codeActionsOnSave -> "source.organizeImports": true, it can lead to an infinite loop of reloading imports and rearranging them to the same position, preventing saveing or changing the file.

Extension version: 1.0.9
VS Code version: Code - Insiders 1.73.0-insider (3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709, 2022-10-27T21:34:51.585Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.38GB free)|
|Process Argv|--log-net-log=netlog.json --ignore-certificate-error --crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
pyind367:30587847
vscccc:30564267
pyindex848cf:30577859
nodejswelcome1:30587009
gswce2:30598411
j6j51389:30596843

```

</details>

**Comment by sschneider-ihre-pvs** [comment]
![high3](https://user-images.githubusercontent.com/86342787/199018143-6e79e4f8-5157-49ee-a1c9-f7f18ab70960.gif)

**Comment by PixsaOJ** [comment]
Oh my god, I was debugging for hours.
Auto save settings don't matter. Typescript settings don't matter. Other formatters enabled does not matter.

**Comment by jd-solanki** [comment]
@johnsoncodehk 

Sorry for the ping but this issue making volar useless. I am also facing this and I think it is critical.

**Comment by Eterion** [comment]
For temporary workaround

Disable organize imports
```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.organizeImports": false
  },
}
```

And run organize imports manually, default shortcut Shift + Alt + O

**Comment by PixsaOJ** [comment]
Additional info:
If one import is below other and the first import is indented with 1 TAB, second import will jump to the edge. if you move this second import line below (so 1 blank line between), issue disappears.

**Comment by CatchZeng** [comment]
I solved the problem by downgrading VSCode to 1.71.0.

**Comment by johnsoncodehk** [comment]
This is VSCode's regression, please track https://github.com/microsoft/vscode/issues/165326.

**Comment by jd-solanki** [comment]
This is solved, we can close this @sschneider-ihre-pvs
