### ISSUE TITLE
grammar.customBlocks

### ISSUE THREAD

**Issue by mrleblanc101** [johnsoncodehk/volar#2083]
Hi,
In vetur, i could define the default grammar for a custom block like this:
```
"vetur.grammar.customBlocks": {
    "i18n": "json"
},
```
How would I do this with Volar ?
Because my `<i18n>` blocks don't have any syntax highlighting (vue-i18n by default use JSON).
I can get it to work by doing `<i18n lang="json">` but it would require me to edit and commit hundreds of files.

**Comment by johnsoncodehk** [comment]
We deliberately don't support this feature because it doesn't conform to VSCode extension API design, and hacks are required in order to implement it.
