### ISSUE TITLE
Vue props with more complex structures breaks formatting

### ISSUE THREAD

**Issue by olemarius** [johnsoncodehk/volar#2085]
See </div> on the different examples:

Object with nested props does not work without trailing comma
![image](https://user-images.githubusercontent.com/184536/199454810-b27c2b2b-3fc0-4f70-8c4a-7e8a08f55a24.png)

Object with nested props works with trailing comma
![image](https://user-images.githubusercontent.com/184536/199454850-9e6e42d1-366b-4d30-9e66-67b84520ad34.png)

Object without nested props works. 
![image](https://user-images.githubusercontent.com/184536/199455441-5f52bd05-0d82-47b5-9cf4-d4e69f6d1904.png)

Array with single object without nested props also breaks
![image](https://user-images.githubusercontent.com/184536/199455822-e5a309a7-1d26-43aa-b781-00f91f012484.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, I think you have installed other syntax highlight extensions that affect to this, you can try [[extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect)].
<img width="224" alt="螢幕截圖 2022-11-29 16 01 26" src="https://user-images.githubusercontent.com/16279759/204472347-1c98c650-7360-4001-8a9c-5eab6d09a9e8.png">
