### ISSUE TITLE
use defineProps "as PropType<CustomType>" volar-plugin tip error: ts(2693)

### ISSUE THREAD

**Issue by xiaominglin789** [johnsoncodehk/volar#209]
Name: Volar
Id: johnsoncodehk.volar
Description: Language support for Vue 3
Version: 0.25.12
Publisher: Johnson Chu
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

vue3 defineProps use T as PropType<CustomType>  like:
`
<script setup lang="ts">
import { defineProps, **PropType** } from "vue";
type SigninMoleType = {
  account: string
  password: string
}

defineProps({
  signinMole: {
    type: Object as PropType<SigninMoleType>,
    required: true
  },
})
</script>
`
valor tip: ts(2693)
`...PropType...
“PropType”Represents only the type, but is used here as a value。ts(2693)`

My ability is limited and I don't know how to solve it. Turn off the valor plug-in and use vetur again. Here it doesn't report this error.

**Comment by xiaominglin789** [comment]
## packge,json
"dependencies": {
    "element-plus": "^1.0.2-beta.44",
    "vue": "^3.0.5",
    "vue-i18n": "^9.1.6",
    "vue-router": "^4.0.8"
  },
  "devDependencies": {
    "@types/node": "^15.6.0",
    "@vitejs/plugin-vue": "^1.2.2",
    "@vue/compiler-sfc": "^3.0.5",
    "prettier": "^2.3.0",
    "sass": "1.32.13",
    "typescript": "^4.1.3",
    "vite": "^2.3.3",
    "vite-plugin-style-import": "^0.10.0",
    "vue-tsc": "^0.0.24"
  }

## tsconfig
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}

**Comment by johnsoncodehk** [comment]
You should use `import type { PropType }`, otherwise you will have a runtime error.

Please try to search the error message first.

- https://github.com/johnsoncodehk/volar/issues/165
- https://github.com/johnsoncodehk/volar/issues/132
