### ISSUE TITLE
Vue 3 + Pug + Vite doctor issues

### ISSUE THREAD

**Issue by madhandennis** [johnsoncodehk/volar#2093]
Hello there,

I have been unable to get imports highlighting and any sort of intellisense to work after the Volar update. Here is my setup:

Dependancies in package.json
```
Vue 3.2
Vite 2.8
@volar/vue-language-plugin-pug: 1.0.9
```

And in vite.config.js:
```
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          plugins: ['@volar/vue-language-plugin-pug']
        }
      }
    })
  ]
});
```

However in VSCode I still see imports being marked as unused:
<img width="627" alt="Screen Shot 2022-11-04 at 09 46 00" src="https://user-images.githubusercontent.com/262761/199867431-f41ec839-8e5b-40b8-aede-c6cd2435cc4c.png">

I see the missing alert from Doctor as well:
<img width="518" alt="Screen Shot 2022-11-04 at 09 47 46" src="https://user-images.githubusercontent.com/262761/199867652-26d770fa-ae12-4090-bcd8-d423b681bf58.png">

Also, I am not using typescript in my project.

Any advise on how to resolve this?

Thanks

**Comment by johnsoncodehk** [comment]
You should add `@volar/vue-language-plugin-pug` to tsconfig not vite.config.js.

tsconfig:

```json
{
  "vueCompilerOptions": {
    "plugins": ["@volar/vue-language-plugin-pug"]
  },
}
```

**Comment by servernoj** [comment]
For those who still see this bug and nothing else helps, here is how I fixed it. I first tried to add the snippet to `tsconfig.json` as instructed, but that didn't help. After a few attempts of playing with packages versions (in one thread, it was stated that `1.0.18` of both, this plugin and VSCode extension should fix the problem) I ended up including that snippet in `tsconfig.app.json` that is referenced from `tsconfig.json` and it helped (after VSCode hard restart)
