### ISSUE TITLE
Typescript module refactor (and minification) will break `vue-tsc`

### ISSUE THREAD

**Issue by cefn** [johnsoncodehk/volar#2095]
The current strategy in `vue-tsc` for dynamically patching `tsc` by intercepting `readFileSync` before `require` will not survive the PR which converts Typescript to use modules as per https://github.com/microsoft/TypeScript/pull/51387#issuecomment-1302414856  

That PR has several ticks and is green to main.

The Typescript module refactor may be followed up by minification of the distributed code which would make the strategy unmaintainable. 

In the short term this will mean pinning the highest compatible peerDependency version to be the last release before modules (possibly 4.8.x). The [wildcard currently in place](https://github.com/johnsoncodehk/volar/blob/6490d60537715aab8e0fde19b551074d35cc92d5/vue-language-tools/vue-tsc/package.json#L22-L24 ) would implicitly include upcoming versions which will break at runtime.

In the medium term @weswigham has hinted at an api-compliant approach to extend the behaviours of tsc in the ways implied by [the patch](https://github.com/johnsoncodehk/volar/blob/354c878ea8fd73255c5f614472c4fcda907a7ff3/vue-language-tools/vue-tsc/bin/vue-tsc.js) and [the proxy](https://github.com/johnsoncodehk/volar/blob/master/vue-language-tools/vue-tsc/src/proxy.ts) ... ( see https://github.com/microsoft/TypeScript/pull/51387#issuecomment-1302471578 )

**Comment by cefn** [comment]
A strategy employed in Yarn is based on https://github.com/cevek/ttypescript via https://github.com/nonara/ts-patch

**Comment by weswigham** [comment]
Yarn's approach isn't great, and I don't recommend it (and comes out from them wanting to patch the real tsc vs y'all, who already have your own variant). Your needs are simple enough that our compiler APIs should be sufficient. I think you can just [copy the `tsc` entrypoint logic from ts](https://github.com/microsoft/TypeScript/blob/main/src/tsc/tsc.ts#L1-L23) and call `ts.setSys` (an internal API rn, but needed to polyfill direct assignment to `ts.sys` post-modules) before the `executeCommandLine` call with a custom `System` implementation that provides the file lookup behavior you're looking for.

**Comment by weswigham** [comment]
Actually, apparently I've misunderstood what's being done, sorry (why override readfile just to patch a js file you're about to execute?). I'm just going to go out on a limb and say these kinds of modifications aren't officially supported and definitely not guaranteed to be stable across TS versions, so... Good luck? This is definitely one of the weirder ways to float a patch on something, considering you could actually maintain a fork & test your modified tsc.

**Comment by jakebailey** [comment]
You may still be able to modify the output tsc file, it just won't be the same patch; but, I would agree that we should try and figure out how to actually support you in our API rather than needing to patch.

**Comment by johnsoncodehk** [comment]
I'll see what should we do when TS releases a beta version for this, I think no snag, `vue-tsc` should just need a patch version to support TS v4 and v5 both, so don't worry. :)

**Comment by cefn** [comment]
If minification of tsc is a followup (making patching infeasible) isn't this a time to restructure how `vue-tsc` wires into `tsc` though?

One concern here is if people have prior versions of `vue-tsc` for any reason they will break because of the wildcard matching (e.g. any Typescript fulfils the peer relationship with no warning, including those versions which can't work at all). Currently the patch routine has no detection whether the replacements match, meaning a silent failure.

So that suggests to me getting a semver-range into the peerDependencies as a short-term resolution, followed up by some future strategy to make vue-tsc Typescript-tooling-API aware.

**Comment by johnsoncodehk** [comment]
> If minification of tsc is a followup

Thanks for telling me, I haven't checked the PR yet 😅. With it, we can look forward to some better way instead of proxy `readFileSync` in vue-tsc.

For example, I hope the original tsc.js decoupling base ts library and allows input it with a parameter:

```js
// bin/tsc
const ts = require("../lib/typescript.js")
require("../lib/tsc.js")(ts)
```

So we can very easy to do any hacking with it in vue-tsc:

```js
const ts = require("typescript/lib/typescript.js")
ts. supportedTSExtensions = ...
ts. supportedJSExtensions = ...
ts. allSupportedExtensions = ...
ts. createProgram = ...
require("typescript/lib/tsc.js")(ts)
```

But we're at a passive position, depending on how typescript actually refactors it.

**Comment by cefn** [comment]
Well the original PR I linked to has already merged to main, so you can see the API surface you can work with already, noting comments from core Typescript contributors;

@weswigham ...

> just [copy the tsc entrypoint logic from ts](https://github.com/microsoft/TypeScript/blob/main/src/tsc/tsc.ts#L1-L23) and call ts.setSys (an internal API rn, but needed to polyfill direct assignment to ts.sys post-modules)

@jakebailey ... 

> we should try and figure out how to actually support you in our API rather than needing to patch.

So if you are able to bottom out what's already possible with the APIs, and that's not enough, there's an appetite for understanding how the Typescript API needs to be opened up to permit downstream tooling to do its work. But if you need any tweaks in place in advance of a breaking release the discussion needs to start immediately I think.

**Comment by johnsoncodehk** [comment]
@cefn I checked the output tsc.js after the PR, proxying `readFileSync` is still the only way, and I just fix code replace in https://github.com/johnsoncodehk/volar/commit/a59ee4eea0761150d7f49e85eab5e7be81665277.
