### ISSUE TITLE
Typescript `as` Type Assertion in template breaks highlighting in Visual Studio Code

### ISSUE THREAD

**Issue by Spice-King** [johnsoncodehk/volar#2096]
Volar: 1.0.9
VSC: 1.72.2/1.73.0
Vue: 3.2.41
OS: Linux, Pop!_OS 22.04

Got an interesting bug, found it while working on something, so I made a small stupid repo case. Yes, it's a stupid unneeded cast, but it does demo it just well. If Vue components could take generics, I'd probably have not bumped into this.

```html
<template>
  <div>
    <button @click="value = {} as const">Set</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data: () => ({ value: {} as Record<string, number> }),
});
</script>

```

(images provided via CodeSnap, cleans out the code from other extension enhancements and just shows syntax)
| Bugged w/ Type Assertion | Working w/o |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/590498/199836283-925b6d79-7f73-49eb-a4e8-445e17316bda.png)  |  ![image](https://user-images.githubusercontent.com/590498/200018027-600ee71b-3725-47b4-a9e4-5c738d19431b.png) |

<details>
  <summary>Show more examples</summary>

## Generic

```html
<template>
  <div>
    <button @click="value = {} as Record<string, number>">Set</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data: () => ({ value: {} as Record<string, number> }),
});
</script>
```

![image](https://user-images.githubusercontent.com/590498/199837375-28443cf1-7f4b-41ab-b381-19364cfa4ce1.png)

## Setup script

```html
<template>
  <div>
    <button @click="value = {} as const">Set</button>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const value = ref({} as Record<string, number>);
</script>
```
![image](https://user-images.githubusercontent.com/590498/199838527-14095665-ad01-4f6a-bedc-a60a69ed42a0.png)

</details>

Example code worked in both HMR and in a full Vite build. Hopefully this all helps pin down the issue.

Oh, and one interesting thing, works fine if the expression is wrapped in brackets, though tooling like Prettier and ESlint wants to remove it

<details>
  <summery>Example</summery>

## Wrapping

```html
<template>
  <div>
    <button @click="value = ({} as const)">Set</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data: () => ({ value: {} as Record<string, number> }),
});
</script>
```

![image](https://user-images.githubusercontent.com/590498/200029212-2d51c0f7-8ce6-4b34-8092-4a021ba6a9b4.png)

## Function call
```html
<template>
  <div>
    <button @click="func({} as const)">Set</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data: () => ({ value: {} as Record<string, number> }),
  methods: {
    func(value: Record<string, number>) {
      this.value = value;
    },
  },
});
</script>
```

![image](https://user-images.githubusercontent.com/590498/200043356-7a79f97a-0c55-41a4-a6a4-94bce6a3dae0.png)

</details>

**Comment by johnsoncodehk** [comment]
Duplicate of #2104

**Comment by esl51** [comment]
But code without brackets is valid in the case of Vue SFC. And prettier automatically removes these brackets as unnecessary.

**Comment by stepanroznik** [comment]
A while back, I made a custom ESLint rule that forces parentheses when using the as assertion in templates.
https://www.npmjs.com/package/eslint-plugin-vue-type-assertion-parens

It includes an automatic quick fix.
Unfortunately, it’s not compatible with Prettier, which will try to remove the parentheses.
