### ISSUE TITLE
`instanceof Class` breaks syntax highlighting in template

### ISSUE THREAD

**Issue by TheNoim** [johnsoncodehk/volar#2099]
If you use `instanceof Class` it breaks syntax highlighting after the Class.

Example:

![image](https://user-images.githubusercontent.com/5133056/200279887-b14a639e-dddd-462b-8463-a6e95558dfb9.png)

Minimal reproduction:

```vue
<template>
  <div v-if="varA instanceof Test"></div>
</template>

<script setup lang="ts">
import { ref } from "vue";

class Test {}

const varA = ref(new Test());
</script>
```

**Comment by drsmile1001** [comment]
Is this fix @ 1.0.10? It seems still has problem here.
![image](https://user-images.githubusercontent.com/11384864/204988627-358a6ee6-e3d2-4132-95cc-495c0533eb96.png)

**Comment by johnsoncodehk** [comment]
You need to wrap it to `v-if="(xxx instandceof yyy)"`, in v1.0.10 it will automatically wrap.

**Comment by johnsoncodehk** [comment]
This is VSCode bug, see https://github.com/johnsoncodehk/volar/issues/520#issuecomment-926286939

**Comment by TheNoim** [comment]
But this will not play well with linters and formatters like prettier or eslint.

**Comment by johnsoncodehk** [comment]
You should open an issue to VSCode. 😅
