### ISSUE TITLE
Methods not found when using mapGetters

### ISSUE THREAD

**Issue by LeanderD** [johnsoncodehk/volar#21]
First I would like to say that I like this extension. It's working well!

In my code I'm using mapGetters to well.. map the getters from my Vuex store.
Unfortunately, this is not working with Volar. It says it can't find these methods.

A "solution" would be to not use the mapGetters of course, but to me that's not really an option.
Hope this can be fixed!

**Comment by johnsoncodehk** [comment]
Thanks for your attention and report! I didn't use vuex, but I searched and tested projects using mapGetters from github, and it seems to work. Can you give me a reproduction project?

**Comment by LeanderD** [comment]
I am using [vue-class-component](https://github.com/vuejs/vue-class-component/). So that probably has something to do with it. 
The project is also set up as a mono-repo. I did have some issues with that before (with other extensions and resolving paths etc), but those have been resolved.

A simple component looks like this:
```
<template>
    <div>{{ getSomething(param) }}</div>
</template>

<script lang="ts">
import { Options, Vue } from 'vue-class-component';
import { mapGetters } from 'vuex';

@Options({
    computed: {
        ...mapGetters(['getSomething']),
    },
})
export default class SimpleComponent extends Vue {}
`

In this case it would tell me that it can't find `getSomething` (the one in the template).
It will build and work.. it just shows me an error in the editor.

Hope this is clear enough. Thanks for making this amazing extension!

**Comment by johnsoncodehk** [comment]
I am not familiar with vue-class-component. I asked someone familiar with it. The problem is not from mapGetters, but because @Options decorator has no effect on the type. Decorator is runtime only. You need to use mixins instead.
I'm not sure if this is the best solution, so I suggest you propose it here: https://github.com/vuejs/vue-class-component/issues

**Comment by LeanderD** [comment]
Thank you for your answer! That does make sense. I will take a look at it!

**Comment by johnsoncodehk** [comment]
Thanks for the update!
