### ISSUE TITLE
[Feature Request]: support volar.splitEditors.layout.(top | down)

### ISSUE THREAD

**Issue by BlackHole1** [johnsoncodehk/volar#2102]
In a vertical display, the left-right split can lead to a lack of space.

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/8198408/200752081-1ee22b8a-97cf-4f9b-9893-a7f6570c816b.png">

**Comment by johnsoncodehk** [comment]
You can click this or use `View: Toggle Layout of Split Editor in Group` command.
<img width="130" alt="螢幕截圖 2022-11-27 16 08 39" src="https://user-images.githubusercontent.com/16279759/204125300-c2916bb7-53e6-4e37-a230-ef40ed22c6e6.png">
