### ISSUE TITLE
Feature Request: vue-tsc `--files` glob pattern flag

### ISSUE THREAD

**Issue by johnnyshankman** [johnsoncodehk/volar#2103]
`vue-tsc` doesn't have a documented way of telling it what folder the vue files are in. right now this causes it to check *everything* which in some cases is not what I want. For example, I dont want this typechecking my `infra` folder, I just want it in `src`. Would be nice to be able to say `--files=src/**/*`

**Comment by johnnyshankman** [comment]
When I do it normally it works, when I specify my entry point of glob out src I get issues around using `@/` syntax.

```
vue-tsc --noEmit src/entry.ts

...

src/entry.ts:5:38 - error TS2307: Cannot find module '@/exports/MConnectProps' or its corresponding type declarations.

```

**Comment by xiaoxiangmoe** [comment]
This feature should provided by tsc. You should create a issue on [TypeScript](https://github.com/microsoft/TypeScript/issues).
