### ISSUE TITLE
Code color ERRO while using TypeScript `as` assertion in template

### ISSUE THREAD

**Issue by Rich4st** [johnsoncodehk/volar#2104]
witch `as` assertion:
![image](https://user-images.githubusercontent.com/50189508/200985466-13c9ddee-29a7-4359-9082-fd92ff63a2a1.png)

without `as` assertion:
![image](https://user-images.githubusercontent.com/50189508/200985527-721436a6-ef16-42f8-8a0c-90771ef4b28d.png)

**Comment by johnsoncodehk** [comment]
You need to wrap AS expressions with parentheses: `:filter-item-values="(item.terms.values as filterItemValue[])"`

**Comment by esl51** [comment]
> You need to wrap AS expressions with parentheses: `:filter-item-values="(item.terms.values as filterItemValue[])"`

But code without brackets is valid in the case of Vue SFC. And prettier automatically removes these brackets as unnecessary.

**Comment by Dorianslavov** [comment]
Why is this closed as it's still an issue ?
As mentioned above, wrapping it with parentheses is not an option since prettier removes them on file save

**Comment by moritz-baecker-integra** [comment]
I agree with the other people before me. This is an annoying problem. I can't always write prettier-ignore for every line that does a type cast in the template. Did anybody find a better solution then wrapping it in brackets?

**Comment by fengtomy** [comment]
Recently I started to develop a vue project and I also met this situation.
It is really annoying, and our eslint/prettier config will automatically remove the wrapping parentheses.
If you guys have better solutions, please tell me.

**Comment by BMFreed** [comment]
My friend found an ingenious solution! The highlighting doesn't break if there's a comment above or below the expression.

<img width="641" height="272" alt="Image" src="https://github.com/user-attachments/assets/035c923c-d21f-4ad5-bae7-f85be7446975" />

Still waiting for the fix tho

**Comment by stepanroznik** [comment]
A while back, I made a custom ESLint rule that forces parentheses when using the as assertion in templates.
https://www.npmjs.com/package/eslint-plugin-vue-type-assertion-parens

It includes an automatic quick fix.
Unfortunately, it’s not compatible with Prettier, which will try to remove the parentheses.
