### ISSUE TITLE
Error when naming a function prop 'onNNN'

### ISSUE THREAD

**Issue by GustavTaxen** [johnsoncodehk/volar#2107]
The component

```
<template></template>

<script lang="ts">
import {defineComponent, PropType} from 'vue';
export default defineComponent({
  props: {
    onDelete: {type: Function as PropType<() => void>, required: true}
  },
  setup(props) {
    props.onDelete();
  }
});
</script>
```

produces the following error in Volar 1.0.9:

```
Cannot invoke an object which is possibly 'undefined'. [Ln 10, Col 5]
```

Running `vue-tsc` from the command line does not produce any errors.

It seems any function prop named `onNNN` (where `NNN` is any word) produces the error.

Volar version 1.0.9.

**Comment by johnsoncodehk** [comment]
This is types issue of `defineComponent`, please forward it to https://github.com/vuejs/core/issues.
