### ISSUE TITLE
[Bug] TypeScript Server Error (4.2.4) Debug Failure

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#211]
Press `F2` to rename the class.

I'm not sure what should be the correct behavior for Volar. Typically, in react, the following will occur:

![image](https://user-images.githubusercontent.com/28700378/119640278-0889b800-be4b-11eb-9d27-290c79e5c8a1.png)

Repro: https://github.com/wenfangdu/tsx-vue-style-rename-repro

![volar](https://user-images.githubusercontent.com/28700378/119639773-84cfcb80-be4a-11eb-90d0-3e81150b494a.gif)

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/2ae4afd0a9077cf7f5877d3558e9e13442b83ef4.
