### ISSUE TITLE
vue-tsc - false positive  Type 'string' is not assignable to type 'XXX | undefined'.

### ISSUE THREAD

**Issue by sfe-efficy** [johnsoncodehk/volar#2114]
Hi!

We are using vue-tsc 1.0.9, in the template of a vue component, we are using constant values to provide the value for a closed string list as a type and it's reporting this error.

For example, given a parent component using this code:

```vue
        <object-field-form  :item-render-type="TYPE_CURRENCY"
        />
```

TYPE_CURRENCY is a constant defined in a ts file:

```ts
export const TYPE_CURRENCY = "currency";
```

And item-render-type is a property in a child component:

```vue
...
   itemRenderType: { type: String as PropType<ItemRenderType>, default: undefined },
....
```

And ItemRenderType is defined as:

```ts
export type ItemRenderType =
    typeof TYPE_CURRENCY
    | typeof TYPE_EMAIL
    | typeof TYPE_NUMBER
    | typeof TYPE_TELEPHONE
    | typeof TYPE_URL;
```

This code in vue-tsc is reported as an error:

```
product-table-total.vue:4:28 - error TS2322: Type 'string' is not assignable to type 'ItemRenderType | undefined'.

4                            :item-render-type="TYPE_CURRENCY" :name="total"
                             ~~~~~~~~~~~~~~~

```

But, if I use a similar code in the script side, no error is reported:

```vue
<script lang="ts" setup>
const testCode = (variable: ItemRenderType) => {
    if (variable === TYPE_CURRENCY) {
        //do something
    }
};

testCode(TYPE_CURRENCY);
</script>
```

Typescript version: 4.8.3
Vue 3 version: 3.2.39

**Comment by stijn-gravity** [comment]
Experiencing the same thing unfortunately

**Comment by johnsoncodehk** [comment]
Please try use `export const TYPE_CURRENCY = "currency" as const;` instead of.
