### ISSUE TITLE
Support using `vue-tsc` via js api

### ISSUE THREAD

**Issue by qmhc** [johnsoncodehk/volar#2115]
Thanks for your hard work on volar!

Is it possible to use `vue-tsc` in `js` and get the result in memory?

**Comment by rchl** [comment]
As far as I understand it's about using vue-tsc programatically.

**Comment by qmhc** [comment]
@rchl yes.

@xiaoxiangmoe I want to use to generate dts files form some vue files in memory.

**Comment by johnsoncodehk** [comment]
You can use `@volar/vue-typescript` for this, it provides same API with `typescript`.
