### ISSUE TITLE
syntax highlight problem with `typeof` inside a `v-if`

### ISSUE THREAD

**Issue by drocha87** [johnsoncodehk/volar#2124]
I'm experiencing a problem when using `typeof` with `!==` inside a `v-if`.  I recorded the behavior so it's a little bit easier to understand what's happening.

 https://user-images.githubusercontent.com/31552590/202249078-eab8b85a-de83-45af-94b4-811495adcb1b.mp4

To reproduce this error you just need to copy and paste the code below in a new component,

```vue
<template>
  <main>
    <div>
      <h3>The Problem</h3>
      <span v-if="typeof word !== 'string'">
        {{ word }}
      </span>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue";

import TheWelcome from "../components/TheWelcome.vue";

const word = ref("word");
</script>
```

Version: Vue Language Features (Volar) v1.0.9
Installed through `Vue Volar extension Pack v1.1.5`

I tried disabling all extensions and just enabling `volar` but the problem persists. The problem is happening in both `wsl:Ubuntu 22.04` and `Windows`. My `vscode version is 1.73.1`

**Comment by kleinptr9** [comment]
I have probably the same problem, when I upgrade to version 1.0.9 all imports are not colorized, even `const` kqywords, etc.

![image](https://user-images.githubusercontent.com/17269309/202715535-a3823005-82ea-42b7-be94-3732bbcfdbb8.png)

**Comment by johnsoncodehk** [comment]
Please try use `(typeof word) !== 'string'` instead of.

**Comment by andreww2012** [comment]
If someone has the same problem but cannot use `(typeof word) !== 'string'` due to Prettier fixing this, just negate the whole expression: `!(typeof word === 'string')`.
