### ISSUE TITLE
how to disabled volar preview server

### ISSUE THREAD

**Issue by zboyaboy** [johnsoncodehk/volar#2128]
![image](https://user-images.githubusercontent.com/13904708/202412078-54ccee23-97c7-4088-bef7-e7604108db99.png)

**Comment by zboyaboy** [comment]
in vscode

**Comment by cmdyu** [comment]
Clear the 'Volar › Preview › Script: Nuxi' in settings seems to work

**Comment by Zaiyiiiiii** [comment]
> Clear the 'Volar › Preview › Script: Nuxi' in settings seems to work

not work for me, it's annoying, and can't be disabled.
