### ISSUE TITLE
Not working with Nuxt 3 auto import plugins

### ISSUE THREAD

**Issue by lucassimines** [johnsoncodehk/volar#2129]
![Screen Shot 2022-11-17 at 10 23 10](https://user-images.githubusercontent.com/12851638/202457938-81dc724d-aa04-4dab-b810-58471c98c132.png)

Is that an Volar issue? How can I fix it?

**Comment by xiaoxiangmoe** [comment]
See https://vuejs.org/api/utility-types.html#componentcustomoptions

**Comment by lucassimines** [comment]
> See https://vuejs.org/api/utility-types.html#componentcustomoptions

Thanks!

I have 2 Vue apps in my project, one is working fine without declaring modules, and other is not working, why can this happen?

**Comment by xiaoxiangmoe** [comment]
You should provide a reproductive demo and  create an issue on nuxt.

**Comment by rchl** [comment]
Nuxt 2 doesn't auto-generate types so it's not a Nuxt issue but I agree with creating a demo.

**Comment by lucassimines** [comment]
Im using Nuxt 3 as I mentioned in the title

**Comment by rchl** [comment]
My. Read "2 Vue" as "Vue 2"

**Comment by lucassimines** [comment]
Didn't get it, I said I have two vue apps, it's a monorepo
