### ISSUE TITLE
[vue-tsc]: Feature request, skip terminal clearing on file save

### ISSUE THREAD

**Issue by nick-w-m** [johnsoncodehk/volar#2141]
**Background**: The project I have pipes a lot of different tooling output to stdout, but saving a file with `vue-tsc --watch` active clears the terminal. It would be nice with a command argument that skips this behaviour.

**Comment by johnsoncodehk** [comment]
`vue-tsc` is just a wapper of `tsc` command, so we can't have custom behavior.
