### ISSUE TITLE
TS linter fails to infer that a data property is not possibly null in event handler expression in template

### ISSUE THREAD

**Issue by grandsong** [johnsoncodehk/volar#2144]
See the [demo](https://sfc.vuejs.org/#eNqFU9uOnDAM/RVvXpaRFph9RTOrVuprVamt1JdIIxbMZQoJSsxQifLvdcJlR6XqAhJxfHJ8HNuj+Nh10a1HkYiTzUzdETSpKs9SkJXiRSr81WlDkGOR9g3BKJWkPKU0OPAS+Mm0sgTX3tJF6QHOoPqmgdTCp5QQfntzRhqk3ihH4SzYzjw5TvfqorBIl1pdLDJtbhMIn9nrwJP7TR7aIlWanQuRwcKgrTZBsyTdYNToMnhc3A+Ph9VNVW2je8E4eLHBgpijSLKVHr54SUGeeMRbCM+x08tkn1OqIqN7lQcQuDMRBwkOEEIelUjf65bjHCCG5+PxCBzRRbpPjo8S5j4b5/KBthTdHoP5k+oUzwXjIrFB2HYNh2ML4NT5Hy9eeyKt4BbWBdd0TVoK+JA1dfaT9964Xbnn7L7Oe+DULkTxzLTy2i79B+vLOK7GNLE+Bs164lnQTtem4u6uV4Z7Qd/YDbP/fT37sjycuZGY7kdVZxUM3JzjuENNE6z4tNQ79ad4u2LxJOrWjUXYpl10tVrx+PjWkIuDZydZG10Kni9nS1ERdTaJY1tkbuiu3EKmjHkVGa46X3aEtg1fjR4sGiaWYul+zxHz5g1NaFDlaND8j/Mv6I7XNxw3kpj+AIlGW0Y=)

Please, copy the code to your editor and see how your linter works.

---

Here, I declared a const `just_now` so that the TS linter could know the data property `just_now` may be either `null` or a `Date` instance.

Initially, `just_now` is `null`.

Then immediately, `mounted()` calls `refresh()`, which assigns a `new Date()` to the data property `just_now`.

For `<span v-if="just_now">{{just_now.toString()}}</span>`, linter works well. No error.

If I remove ` v-if="just_now"`, the linter will show an error for `just_now.toString()` because `just_now` may be `null` now.

Same for `<input v-if="just_now" :value="just_now.getFullYear()"/>`. Good.

For `<button v-if="just_now" @click="showOffset(just_now)">Show Offset</button>`, however, the linter shows such an error in spite that `v-if` has already eliminated such possibility.

The code runs as expected, but I still wish to get rid of this wrong error.

**Comment by johnsoncodehk** [comment]
You need to config `narrowingTypesInInlineHandlers` in tsconfig:

```json
{
  "vueCompilerOptions": {
    "narrowingTypesInInlineHandlers": true,
  },
}
```
