### ISSUE TITLE
JSDoc hints from composables don't work in <template> and work only if comments are in return statement

### ISSUE THREAD

**Issue by gustojs** [johnsoncodehk/volar#2148]
Windows 10 WSL (Ubuntu)
VSCode 1.73.1
Volar 1.09 in take over mode

Using composition functions, JSDoc hints on hover for passed variables work:
- only for `<script>`, not for `<template>`
- only if `/** */` comment is added inside of `return` statement, not above the definition.

This happens using both `setup()` and `<script setup>` syntax.

Example:
```
// useCat.ts
export const useCat = () => {

  /** DOESN'T WORK */
  const cat= ref('Meow!')

  return {
    /** WORKS */
    cat
    };
  };

// component.vue
<template>
<div :cat="cat">meow!</div> <!-- DOESN'T WORK -->
</template>
<script setup lang="ts">
const { cat } = useCat() // WORKS
</script>
```

With `setup()` syntax, the situation looks as follows:
```
return { cat: cat} // KEY DOESN'T WORK, VALUE WORKS
```

**Comment by johnsoncodehk** [comment]
This is TypeScript's behavior and we can change it, you can open an issue at https://github.com/microsoft/TypeScript/issues if you think this behavior is incorrect.
