### ISSUE TITLE
Support type guards in script setup

### ISSUE THREAD

**Issue by sharifzadesina** [johnsoncodehk/volar#2149]
Hello,

Variable `test` in the last line is typed as `object` but inside template, it is still `object|null` which causes `possible null` error.

```ts
<template>
  <div>{{ test.message }}</div>
</template>

<script setup lang="ts">
let test: { message: string }|null = { message: 'hello' };

if (test === null) {
  throw new Error('error');
}

let obj: object = test;
</script>

```

**Comment by troy351** [comment]
```ts
function setup() {
  let test: { message: string } | null = { message: 'hello' }

  if (test === null) {
    throw new Error('error')
  }

  // simulate render function
  return () => {
    return test.message // Object is possibly 'null'.
  }
}
```

**Comment by sharifzadesina** [comment]
Expected? so I am supposed to check the nullability of a variable twice in the same component?
Is this expencted?

**Comment by troy351** [comment]
You can 
- using `obj.message` inside template
- using `test?.message` inside template (no null check inside ts)
- add `v-if="test"` to `div` (no null check inside ts)

**Comment by sharifzadesina** [comment]
Well, they check nullability twice.
I am closing the issue as this is expencted.

**Comment by troy351** [comment]
Actually this behavior was designed by TS as a control flow analysis trade-off

**Comment by sharifzadesina** [comment]
So how do you guys write your components? it is really dirty to check nullability twice.

**Comment by troy351** [comment]
Guess you missed the previous comment?

**Comment by sharifzadesina** [comment]
I already knew them, but they are dirty. anyways, ty.

**Comment by troy351** [comment]
Throw error was not the best way for UI rendering, there should be placeholders when no data, so the `dirty` way was needed.

When `test` was a prop, why not using `v-if` on component instance?

**Comment by sharifzadesina** [comment]
It is not like really throw error. it will be handled later.
for example in nuxt 3 you do like this:
```
throw createError({ statusCode: 404 });
```
