### ISSUE TITLE
Outline view for vue files is empty

### ISSUE THREAD

**Issue by keosu** [johnsoncodehk/volar#2150]
Volar version: 1.0.9
VS Code: 1.72.0
MacOS 12.6

**Comment by johnsoncodehk** [comment]
Please make sure to select the correct language mode on the status bar for vue documents.
<img width="59" alt="螢幕截圖 2022-11-29 20 48 29" src="https://user-images.githubusercontent.com/16279759/204533240-aab79c84-aea9-41ca-9428-ee8804d0b28a.png">
