### ISSUE TITLE
Documentation for CSS linting?

### ISSUE THREAD

**Issue by joshukraine** [johnsoncodehk/volar#2156]
I am using the volar LSP in Neovim via [Neovim LSP](https://github.com/neovim/nvim-lspconfig). When editing Vue files, I encounter the classic "UnknownAtRules" error, which is discussed in issue #492. This issue is [listed as fixed in the CHANGELOG](https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#02721-2021916). However, I cannot find any clear documentation explaining how to configure CSS linting with volar.

Searching GitHub seems to show people adding `"css.lint.unknownAtRules": "ignore"` to `.vscode/settings.json`. Since I am using Neovim LSP, I've tried adding this to my `lsp-settings/volar.json` file, but it has no effect. Other volar settings under the `volar.~` namespace autocomplete and work fine. But I see no CSS options available, and if I just paste something, it does nothing.

Perhaps this issue has more to do with Neovim LSP config? I'm happy to ask there, but I would at least like to know what the supported config should look like. Thank you!

**Comment by johnsoncodehk** [comment]
`css.lint.unknownAtRules` is a workspace setting, not a volar plugin setting, I'm not familiar with Neovim, but I guess you should check https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings.
