### ISSUE TITLE
Volar v1.0.10 recognize RouterLink component type as never

### ISSUE THREAD

**Issue by hongquan** [johnsoncodehk/volar#2157]
After upgrading to v1.0.10, Volar now recognizes `RouterLink`, `RouterView` components as `never` type:

![image](https://user-images.githubusercontent.com/314607/204776655-57c87563-fa6e-4305-beed-077709fdb277.png)

**Comment by hongquan** [comment]
@imaverickk I upgraded `vue-tsc` and still get the same error. More than that, CI starts to failing because the error is thrown when I do type-check with `vue-tsc`,

**Comment by johnsoncodehk** [comment]
What is the `RouterLink` type in v1.0.9?

**Comment by imaverickk** [comment]
Everything works fine for me, in v1.0.9 and v 1.0.10 the type of RouterLink is `_RouterLinkI`

**Comment by hongquan** [comment]
This is how v1.0.9 recognizes `RouterLink`:
![image](https://user-images.githubusercontent.com/314607/205075951-adff297c-dd15-4d9c-bc49-2717e9f14968.png)

**Comment by xiaoxiangmoe** [comment]
@hongquan Can you provide a reproduction demo？

**Comment by hongquan** [comment]
@xiaoxiangmoe I will try tomorrow (not sure if a small demo can reproduce it, or the issue depends on something in my project).

**Comment by hongquan** [comment]
Hi, I copied part of my project to provide a reproduction demo: https://bitbucket.org/hongquan/vue-tsc-router/src/main/
You can see the issue in _LobbyPage.vue_ and _FacilityView.vue_ files.

**Comment by jbmaisner** [comment]
Same issue here, in fact it happens on all global components, despite a declaration file like explained in documentation :

```ts
// For vue 2.7
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    // ...
    // + my own global components
    // ...
  }
}

export {};
```
