### ISSUE TITLE
The split editor icon in the upper right corner is missing.version 1.0.10

### ISSUE THREAD

**Issue by Shadownc** [johnsoncodehk/volar#2158]
The split editor icon in the upper right corner is missing.version 1.0.10

**Comment by zhangyinghahaha** [comment]
I had the same problem! 
Please fix it quickly! 
Thanks!

**Comment by johnsoncodehk** [comment]
It's gone, see https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#1010-20221129.

You can use comman and or bind it to a hotkey as you need.
<img width="547" alt="螢幕截圖 2022-12-01 19 22 02" src="https://user-images.githubusercontent.com/16279759/205040263-8d874ea5-8cbe-48d5-ab0a-0e650fc233c3.png">
