### ISSUE TITLE
Class type error started occurring in version 1.0.10.

### ISSUE THREAD

**Issue by shiraishi-yuma** [johnsoncodehk/volar#2159]
After updating to version 1.0.10, I am getting the following error.
```
Type '{ class: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Object literal may only specify known properties, and 'class' does not exist in type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.ts(2322)
```
![image](https://user-images.githubusercontent.com/105183552/204956180-d68a779e-5ca2-45e0-9e60-4120eacdefeb.png)

When I reverted back to version 1.0.9, the error was resolved.

This appears to be caused by importing '@storybook/vue3'.
Excluding the story file in tsconfig.json solves this problem.

tsconfig.json
```json
{
  "exclude": [
    "**/*.stories.ts"
  ]
}
```

However, I would like to solve this problem, because this way, types does not work in the story files.

**Comment by johnsoncodehk** [comment]
Please upgrade to storybook v7, see https://github.com/storybookjs/storybook/pull/18323.

**Comment by shiraishi-yuma** [comment]
Thank you @johnsoncodehk !
