### ISSUE TITLE
Feature Request | Add settings option to toggle display of "Split button"

### ISSUE THREAD

**Issue by DanielBoettner** [johnsoncodehk/volar#2163]
# Feature request description
In **v1.0.11* the button to split a vue file into template / script / style was removed to save space.
Instead a command was added to offer the same functionality.

I would like to suggest to also add an option in the settings to display the button if the user wants
to use the functionality via the interface.

# Details
The button as seen in **v1.0.9**

![image](https://user-images.githubusercontent.com/21986545/205117470-8950ab68-d68d-489d-b277-3422d31d9439.png)

Related issues:
* #2158
* #2162 (duplicate)

**Comment by bogdan-coman-uv** [comment]
That button was actually very handy. Please add the option to show it in the interface

**Comment by johnsoncodehk** [comment]
Hi @DanielBoettner, do you think you still want it?

**Comment by DanielBoettner** [comment]
@johnsoncodehk I do. Currently I manually use a lower version so I have the functionality.

I think the original idea to hide it and allow this via command was the right choice.
Screen space can still be a precious good even when its abundant. 

However, I think an option to still be able to use a button. is useful when the user is not going _full keyboard shortcut ninja_.
Maybe at some point in the future I only use the command because it went into my muscle memory.
But without the button, I likely would have never realized this is a feature.
And this one of the important features in my view. 

The ability to easily have important parts tabbed/split in a single file tab is superb.

Offtopic: 
Is there a way too have vue files split 3 ways instead of just 2?
When I click the button it splits template and script. Sometimes I whish it would even split styles.

**Comment by zqy233** [comment]
How about adding another button to split template and styles，user can control by settings

**Comment by zqy233** [comment]
> @DanielBoettner Thanks for your feedback, I will add a setting for it in the next version.
> 
> > Is there a way too have vue files split 3 ways instead of just 2?
> > When I click the button it splits template and script. Sometimes I whish it would even split styles.
> 
> Unfortunately, it's impossible based on VSCode's editor groups.

How about adding another button to split template and styles，user can control by settings

**Comment by RamaHerbin** [comment]
Hello, any news on the ability to add the split button ?

**Comment by so1ve** [comment]
@RamaHerbin `vue.splitEditors.icon`
