### ISSUE TITLE
Ability to Enable/Disable for Projects using `.vscode/settings.json`

### ISSUE THREAD

**Issue by seanghay** [johnsoncodehk/volar#2164]
Volar sometimes interfere with other projects that it should not. I want to disable/enable Volar based on project using `.vscode` config file.

I saw Deno also uses the technique to Enable/Disable Deno server.

```jsonc
// .vscode/settings.json

{
  "deno.enable": true,
  "deno.unstable": true
}
```

For Volar, I think we should do something like this too.

```jsonc
// .vscode/settings.json

{
  "volar.enable": true,
}
```

**Comment by seanghay** [comment]
If it's already implemented, please let me know how to achieve that.

**Comment by johnsoncodehk** [comment]
Please track #https://github.com/microsoft/vscode/issues/40239
