### ISSUE TITLE
nativeTags is hard to use

### ISSUE THREAD

**Issue by ModyQyW** [johnsoncodehk/volar#2165]
Hi. Thanks for your work first!

I am `@uni-helper/uni-app-types` author and the package is providing `uni-app` elements types. I notice that v1.0.10 adds `nativeTags` and removes `experimentalRuntimeMode`. I also see <https://github.com/johnsoncodehk/volar/issues/2065>.

I think `nativeTags` is hard to use. With <https://github.com/johnsoncodehk/volar/issues/2065> example, as shown below.

```json
{
  "vueCompilerOptions": {
    "nativeTags": [
      "view",
      "scroll-view"
    ]
  },
}
```

It doesn't parse the correct types of `view` and `scroll-view`, but parse the other elements.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/31850793/205219516-3260fbd2-37c8-4a67-bfc5-a94dd6382948.png">
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/31850793/205219699-c5a8095d-8d25-43a1-a6bb-bdf13bbea7b4.png">
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/31850793/205219626-952a2a32-682b-4dc6-9257-618f710f7f99.png">

To accurately parse types, I think I need to set a long `nativeTags`, which includes <https://github.com/johnsoncodehk/volar/blob/master/vue-language-tools/vue-language-core/src/utils/ts.ts#L121-L128> elements and exclude `uni-app` elements. Here I exclude `view`, `text`, `progress` and so on.

```json
{
  "vueCompilerOptions": {
    "nativeTags": [
      "html",
      "body",
      "base",
      "head",
      "link",
      "meta",
      "style",
      "title",
      "address",
      "article",
      "aside",
      "footer",
      "header",
      "hgroup",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "nav",
      "section",
      "div",
      "dd",
      "dl",
      "dt",
      "figcaption",
      "figure",
      "picture",
      "hr",
      "img",
      "li",
      "main",
      "ol",
      "p",
      "pre",
      "ul",
      "a",
      "b",
      "abbr",
      "bdi",
      "bdo",
      "br",
      "cite",
      "code",
      "data",
      "dfn",
      "em",
      "i",
      "kbd",
      "mark",
      "q",
      "rp",
      "rt",
      "ruby",
      "s",
      "samp",
      "small",
      "span",
      "strong",
      "sub",
      "sup",
      "time",
      "u",
      "var",
      "wbr",
      "area",
      "track",
      "embed",
      "object",
      "param",
      "source",
      "script",
      "noscript",
      "del",
      "ins",
      "caption",
      "col",
      "colgroup",
      "table",
      "thead",
      "tbody",
      "td",
      "th",
      "tr",
      "datalist",
      "fieldset",
      "legend",
      "meter",
      "optgroup",
      "option",
      "output",
      "select",
      "details",
      "dialog",
      "menu",
      "summary",
      "template",
      "blockquote",
      "iframe",
      "tfoot",
      "svg",
      "animate",
      "animateMotion",
      "animateTransform",
      "circle",
      "clipPath",
      "color-profile",
      "defs",
      "desc",
      "discard",
      "ellipse",
      "feBlend",
      "feColorMatrix",
      "feComponentTransfer",
      "feComposite",
      "feConvolveMatrix",
      "feDiffuseLighting",
      "feDisplacementMap",
      "feDistanceLight",
      "feDropShadow",
      "feFlood",
      "feFuncA",
      "feFuncB",
      "feFuncG",
      "feFuncR",
      "feGaussianBlur",
      "feImage",
      "feMerge",
      "feMergeNode",
      "feMorphology",
      "feOffset",
      "fePointLight",
      "feSpecularLighting",
      "feSpotLight",
      "feTile",
      "feTurbulence",
      "filter",
      "foreignObject",
      "g",
      "hatch",
      "hatchpath",
      "image",
      "line",
      "linearGradient",
      "marker",
      "mask",
      "mesh",
      "meshgradient",
      "meshpatch",
      "meshrow",
      "metadata",
      "mpath",
      "path",
      "pattern",
      "polygon",
      "polyline",
      "radialGradient",
      "rect",
      "set",
      "solidcolor",
      "stop",
      "symbol",
      "textPath",
      "tspan",
      "unknown",
      "use",
      "slot",
      "component"
    ]
  },
}
```

Can I have a better way to specify `uni-app` elements without such a long list?

**Comment by ModyQyW** [comment]
[demo](https://github.com/MillCloud/presets/tree/main/uni-app)

**Comment by johnsoncodehk** [comment]
If you see the [change](https://github.com/johnsoncodehk/volar/commit/687812658f51238f56969ee95b6057d80107ce21#diff-99af905754edc8e056c6a9a779ff5870482ae0115004740da01f50f3d3776b0dL57), `"experimentalRuntimeMode": "runtime-uni-app"` is just equivalent to `"nativeTags": ["block", "component", "template", "slot"]`, you don't need the long list if `"experimentalRuntimeMode": "runtime-uni-app"` is working to you before.

If you really need the long list, you can modify the default long list `nativeTags` via plugin API your self:

```json
{
  "vueCompilerOptions": {
    "plugins": ["./your-plugin"]
  }
}
```

```ts
import { VueLanguagePlugin } from '../types';

const plugin: VueLanguagePlugin = (cxt) => {

	cxt.vueCompilerOptions.nativeTags = cxt.vueCompilerOptions.nativeTags.filter(...);

	return {
		order: -1,
		version: 1,
	};
};
export = plugin;
```

**Comment by ModyQyW** [comment]
Ah I just miss that change. Thanks for pointing it out and thanks again for your great work! ❤
