### ISSUE TITLE
Incorrect ts(2783) error when class attribute appear in template syntax more than once after update vue-tsc to latest version

### ISSUE THREAD

**Issue by mmis1000** [johnsoncodehk/volar#2166]
Versions

"typescript": "^4.9.3",
"vue-tsc": "^1.0.10"

```html
<template>
  <div class="a" v-bind="{ class: {b: true} }" />
</template>
```

This cause an error that don't actually exist

```txt
error TS2783: 'class' is specified more than once, so this usage will be overwritten.
```

Because vue sfc explicitly allow multi `class` and `style` to exist at same time, vue-tsc should not report error on such usage.

The template above outputs as 

```js
function render(_ctx, _cache) {
  return (_openBlock(), _createElementBlock("div", _mergeProps({ class: "a" }, { class: {b: true} }), null, 16 /* FULL_PROPS */))
}
```

Which works totally fine and nothing is overwritten.

**Comment by sawmurai** [comment]
Getting the same error with this:

```html
<slot name="label" v-bind="{name}">
<!-- ... -->
</slot>
```

Error:
```
'name' is specified more than once, so this usage will be overwritten.ts(2783)
```

**Comment by sawmurai** [comment]
Hello! I'm afraid the error case with a duplicate `name` still exists:

```vue
<slot name="label" v-bind="{name}">
<!-- ... -->
</slot>
```

**Comment by cawa-93** [comment]
@sawmurai I think for name is correct error sinse vue will owerride id. Only `class`, `style` and `onXX` props may be merged.
See https://github.com/vuejs/core/blob/c6e5bda27d13554675d68dbe33b07f3474467aa6/packages/runtime-core/src/vnode.ts#L816-L845

**Comment by sawmurai** [comment]
I think this is kind of a special case because the first `name` is the name of the slot, and the second `name` is a bound symbol. So, nothing is supposed to be merged here.

**Comment by sawmurai** [comment]
Thinking about it, maybe the special case here is `v-bind` or slot-bindings in general :)

**Comment by sawmurai** [comment]
@johnsoncodehk Do you want me to open a new issue maybe?
