### ISSUE TITLE
Wrong type of `index` of `v-for`

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [johnsoncodehk/volar#2167]
![image](https://user-images.githubusercontent.com/45625440/205276096-1cbebd51-0624-463d-82dd-cc927c9bcfb9.png)

TS version: 3.7.2
Extension version: v1.0.10

**Comment by muhammadyusuf-kurbonov** [comment]
Tried with over mode on and off. The same behaivior

**Comment by johnsoncodehk** [comment]
> TS version: 3.7.2

You pointed out the problem. 👀 Please update your typescript version.

**Comment by muhammadyusuf-kurbonov** [comment]
Upgrade of TS helped. Is it fixible or I have to upgrade?

**Comment by johnsoncodehk** [comment]
You have to upgrade, this is TS's bug.

**Comment by muhammadyusuf-kurbonov** [comment]
Thank you.
