### ISSUE TITLE
The indent size is messed after auto-import component

### ISSUE THREAD

**Issue by oliver139** [johnsoncodehk/volar#2168]
So I am inserting a component:
<img width="911" alt="Screenshot 2022-12-03 at 5 18 00 PM" src="https://user-images.githubusercontent.com/45283723/205433778-fd20740c-1dfb-4fdd-bd51-2360dc9a871d.png">

Then the auto added code messed the indent size
<img width="558" alt="Screenshot 2022-12-03 at 5 18 10 PM" src="https://user-images.githubusercontent.com/45283723/205433793-0484a419-97ef-420a-9e8a-98a543fc6cef.png">

I am sure my indent setting is kept as 2 spaces
<img width="276" alt="圖片" src="https://user-images.githubusercontent.com/45283723/205433852-d48554c3-11e5-4f50-912c-f9b057c63ba5.png">

Is there any suggestion on this? thanks

**Comment by johnsoncodehk** [comment]
TypeScript Printer API does not have an indent setting so it can't control. I decided not to do more hacks for this to make it harder to maintain. Thanks for your report.

https://github.com/johnsoncodehk/volar/blob/f1e8782d2890f8e76871ffd41be13f2554f3dde9/vue-language-tools/vue-language-service/src/languageService.ts#L108
