### ISSUE TITLE
Accept passing readonly array to props

### ISSUE THREAD

**Issue by sapphi-red** [johnsoncodehk/volar#217]
## Description
Passing a readonly array to props occurs an error.
See the example below.
```vue
<template>
  <component-a :readonly="arr" /> <!-- Passing to props should not occur an error. Now it occur errors. -->
  <component-a v-model:writeable="arr" /> <!-- Passing to v-model should occur an error. Now it occur errors. -->
</template>

<script lang="typescript">
import { defineComponent } from 'vue'
import ComponentA from 'somewhere'

export default defineComponent({
  component: {
    ComponentA
  },
  setup() {
    const arr: readonly string[] = ['aaa', 'bbbb']
    return { arr }
  }
})
</script>
```

## Additional Information
https://github.com/johnsoncodehk/volar/blob/a2635b241a3d06600ed2094229f3bc6e5320c11a/packages/vscode-vue-languageservice/src/virtuals/global.ts#L69-L72
Changing this line to below will fix the error. But this fix also suppresses the error with v-model which should occur an error. (`DeepReadonly` should be imported from `vue`)
```ts
	type __VLS_MapPropsType<T> = { [K in keyof T]: T[K] extends (arg: infer _1) => infer _2
		? T[K] : T[K] extends (arg: infer A, ...rest: infer _3) => infer R
		? (props: A) => R : (props: DeepReadonly<__VLS_ExtractComponentProps<T[K]> & Omit<__VLS_GlobalAttrs, keyof __VLS_ExtractComponentProps<T[K]>>> & Record<string, unknown>) => any
	};
```

**Comment by johnsoncodehk** [comment]
This is expected, `readonly string[]` is not subtype of `string[]`, you should define the props as readonly array like `arr: Array as PropType<readonly string[]>`.

If ignore this error we can't prevent unexpected behavior in ComponentA.

```vue
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    arr_1: Array as PropType<string[]>,
    arr_2: Array as PropType<readonly string[]>,
  },
  setup(props) {
    props.arr_1.push(''); // no error but this is unexpected behavior, because parent pass a readonly array.
    props.arr_2.push(''); // has error in expected.
  }
})
</script>
```

**Comment by sapphi-red** [comment]
Since mutating props directly is not recommended, I thought every props should accept readonly values.
https://v3.vuejs.org/style-guide/#implicit-parent-child-communication-use-with-caution
But now I noticed that this is just a "Use With Caution" and not a "Essential".
It seems like I should type every props as Readonly. (Or somehow change the type of `props` to be DeepReadonly)
