### ISSUE TITLE
Opt out of css class references

### ISSUE THREAD

**Issue by rhysburnie** [johnsoncodehk/volar#2171]
Is there anyway to opt out of these css class references?
They are not useful for our project and just get in the way.
Surely you should be able to choose if you want them or not.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/245933/205529983-d8e67eee-be57-404a-ac2c-9d3aabc56482.png">

<img width="203" alt="image" src="https://user-images.githubusercontent.com/245933/205529972-e187361a-0b1d-439e-aaef-8ee4a17de069.png">

**Comment by johnsoncodehk** [comment]
You can add `"experimentalResolveStyleCssClasses": "never"` to tsconfig.

```json
{
	"vueCompilerOptions": {
		"experimentalResolveStyleCssClasses": "never"
	}
}
```
