### ISSUE TITLE
splitEditors Disappeared

### ISSUE THREAD

**Issue by WilsonXinxin** [johnsoncodehk/volar#2173]
![image](https://user-images.githubusercontent.com/43174390/205576211-a9e816e3-21ba-4a59-87a7-703af87c8fd7.png)
I haven't modified the configuration

vscode version
![image](https://user-images.githubusercontent.com/43174390/205576465-a596d03f-f055-404e-a508-9a86edb4ad26.png)

volar version
![image](https://user-images.githubusercontent.com/43174390/205576581-22606ecd-5c7f-4b3b-8106-31203290fd40.png)

**Comment by MinatoHikari** [comment]
same problem here

**Comment by johnsoncodehk** [comment]
Duplicate of #2163
