### ISSUE TITLE
Attribute values being wrapped in parentheses while typing

### ISSUE THREAD

**Issue by kleinfreund** [johnsoncodehk/volar#2182]
Recently, Volar started to wrap some parts of attribute values in parentheses and I don’t recall a situation in which this was appropriate.

In the following examples, I expect no transformations to happen, **especially not while I’m typing**.

## Example 1

Place the cursor after the `i` in `(value, i)`, type `x`.

```vue
<template>
  <p
    v-for="(value, i) in {}"
    :key="i"
  >
    Test
  </p>
</template>
```

**Result**:

```vue
<template>
  <p
    v-for="((value, ix)) in {}"
    :key="i"
  >
    Test
  </p>
</template>
```

## Example 2

Place the cursor after the `>` in `"3 >"`, type `1`.

```vue
<template>
  <p v-if="3 >">
    Test
  </p>
</template>
```

**Result**:

```vue
<template>
  <p v-if="(3 >1)">
    Test
  </p>
</template>
```

**Comment by yooouuri** [comment]
The wrapping also happens to me, it’s kinda annoying..

**Comment by rchl** [comment]
@johnsoncodehk it seems like the original issue was a vscode-specific syntax issue so maybe those workarounds should specifically target vscode.

**Comment by johnsoncodehk** [comment]
@rchl Yes, I will make it default disabled to other IDEs. Do you plan to implement [Auto Insertion](https://github.com/johnsoncodehk/volar/blob/master/packages/vscode-language-client/src/features/autoInsertion.ts) for https://github.com/sublimelsp/LSP-volar?

**Comment by rchl** [comment]
Probably not anytime soon since ST doesn't make it easy. Just have been thinking about other editors that would likely not need those workarounds.
