### ISSUE TITLE
Incorrect "Different vue-tsc version" error

### ISSUE THREAD

**Issue by wnmzzzz** [johnsoncodehk/volar#2183]
# Problem Description

Recently, Volar has started showing the issue "Different vue-tsc version" in a Vite project. This is incorrect, as the same vue-tsc version is installed in the project.
```
The Vue Language Features (Volar)'s version is 1.0.11, but the workspace's vue-tsc version is 1.0.9. This may produce different type checking behavior.

vue-tsc: c:\Users\wnmz1\git\<name-of-my-project>\node_modules\vue-tsc\package.json
```

I have set vue-tsc to be version 1.0.11 in package.json and it is also noted as such in the `package-lock.json`. What's more, if I access the file under the noted path above, node_modules\vue-tsc\package.json, it also displays its version as `"version": "1.0.11"`
Querying the installed version directly with npm yields the same result:
```
$ npm list vue-tsc
<name-of-my-project>@0.3.0 C:\Users\wnmz1\git\<name-of-my-project>
└── vue-tsc@1.0.11
```

# Expected Behaviour

No error should be shown if the vue-tsc version that's installed matches the vue-tsc version of Volar.

# Version Info
Volar v1.0.11
VS Code v1.73.1
npm v8.15.0

**Comment by johnsoncodehk** [comment]
Do you still have this problem in latest version? (You need to setting `"volar.doctor.checkVueTsc": true`)
