### ISSUE TITLE
How does my vscode plug-in call remove all unused code

### ISSUE THREAD

**Issue by yangdan8** [johnsoncodehk/volar#2188]
Because I want users to remove useless code when saving, which cannot be done through configuration, I wrote a vscode plug-in, but my vscode plug-in does not know how to call remove all unused code.

**Comment by johnsoncodehk** [comment]
codeActionsOnSave not working before due to a bug, you can add following setting to .vscode/settings.json to remove unused code on save in the next release.

```json
{
	"editor.codeActionsOnSave": {
		"source.removeUnused.ts": true
	}
}
```
