### ISSUE TITLE
Using `volar` together with `@typescript-eslint/parser` for type checking rules to understand SFC component types

### ISSUE THREAD

**Issue by DrJume** [johnsoncodehk/volar#2189]
I'm using @typescript-eslint in a TS project with type checking enabled (https://typescript-eslint.io/linting/configs#recommended-requiring-type-checking).

This allows eslint to understand typescript types and make suggestions.

Sadly Vue SFC files are interpreted with type `any`, they are not correctly loaded. 
I found an option for @typescript-eslint/parser to specify a TS `program` in the options: (https://typescript-eslint.io/architecture/parser/#program). So it should be possible to pass the Volar proxy into @typescript-eslint/parser. This should allow eslint to also run type linting for Vue SFCs.
But sadly I didn't get it to work.

> How can I get a TS `program` which uses Volar and pass it to @typescript-eslint/parser?

This is my eslint config override for '*.vue' files:

```ts
...
overrides: [
    {
        files: ['*.vue'],
        extends: [
            'plugin:@typescript-eslint/recommended-requiring-type-checking',
            'plugin:@typescript-eslint/strict',
        ],
        parser: 'vue-eslint-parser',
        parserOptions: {
            parser: '@typescript-eslint/parser',
            parserOptions: {
                extraFileExtensions: ['.vue'],
                tsconfigRootDir: __dirname,
                project: ['./tsconfig.app.json'],
                program: vueTsc.createProgramProxy({
                    rootNames: ['./src/main.ts'],
                    options: compilerOptions,
                    host: ts.createCompilerHost(compilerOptions),
                }),
            },
        }
    }
]
...
```

I also tried to add the `typescript-vue-plugin` as a typescript plugin, to get SFCs to work with eslint type checking, but it also didn't work... 

```jsonc
"compilerOptions": {
    "plugins": [
        {
            "name": "typescript-vue-plugin"
        }
    ]
}
```

**Comment by johnsoncodehk** [comment]
> This is my eslint config override for '*.vue' files:

Can you provide this project? It can help me quickly understand, thanks!

**Comment by DrJume** [comment]
Yeah sure! 
https://github.com/DrJume/vue-volar-eslint

1. Enable Takeover Mode
2. Active ESLint VSCode Plugin
3. Go to `main.ts`
4. @typescript/eslint can't read type of `.vue` file correctly

It would be awesome, if it would work with Volar!

![image](https://user-images.githubusercontent.com/12785972/206840178-d15bcdba-fe1d-4d4e-8e43-3e1b4c53ec3f.png)

**Comment by johnsoncodehk** [comment]
It seems that ESLint TypeScript document incorrect, you should use `parserOptions.programs` instead if `parserOptions.program`, and this is works to me.

```ts
const { createComponentMetaChecker } = require('vue-component-meta')
const tsConfig = require.resolve('./tsconfig.json')
const checker = createComponentMetaChecker(tsConfig)
const program = checker.__internal__.tsLs.getProgram()

// ...
parserOptions: {
  programs: [program]
},
```

**Comment by DrJume** [comment]
@johnsoncodehk 

It still doesn't work completely. The issue stated above still exists. Can you reopen this issue?
I hope my possible explanation above can help.

**Comment by johnsoncodehk** [comment]
那個問題不是這裡可以解決的，它屬於eslint-plugin-vue，對於相關進度請追蹤https://github.com/DrJume/vue-volar-eslint/pull/1。
