### ISSUE TITLE
Experimental RFC 436 - import type extending generic appears as "unused" by TS

### ISSUE THREAD

**Issue by cohlar** [johnsoncodehk/volar#2191]
I've added experimental RFC 436 to my project because I really needed generic components. It works pretty well, but for some reason when my generic extends an imported type, that type appears as "unused" by TypeScript. With eslint, I get the following warning message:

![image](https://user-images.githubusercontent.com/57757008/206925580-ddedfeff-9d75-4dec-8a41-f5fe685496e1.png)

I made a [public repo](https://github.com/cohlar/vue-rfc436/tree/unused-var-warning) to showcase the issue. The generic component is `TheWelcome`. Please note this repo is shared with https://github.com/johnsoncodehk/volar/issues/2192 (separate branches).

**Comment by johnsoncodehk** [comment]
This is ESLint report we can't fix, but we will have complete ESLint support in the future, please track https://github.com/DrJume/vue-volar-eslint/pull/1.
