### ISSUE TITLE
Format everything with prettier

### ISSUE THREAD

**Issue by rafaelpimpa** [johnsoncodehk/volar#22]
I'm trying to use Prettier as formatter for every block, how do I do that? I tried ``workspaceExtensions`` but didn't work for the ``<template>`` block.

**Comment by rafaelpimpa** [comment]
I replaced default formatter from Volar to Prettier, didn't know Prettier could format SFC.

**Comment by johnsoncodehk** [comment]
Maybe your vscode html formatter is not properly setup. btw workspaceExtensions is just for fun now... See https://github.com/vuejs/vetur/issues/2315#issuecomment-716072524
