### ISSUE TITLE
The syntax highlighter is broken when add `jsconfig.json`

### ISSUE THREAD

**Issue by FlandreDaisuki** [johnsoncodehk/volar#2200]
Here is a minimal reproducible project: https://github.com/FlandreDaisuki/reproduce-volar-syntax-highlight-bug

![圖片](https://user-images.githubusercontent.com/5981459/207249387-43624559-1e4b-4ea0-860a-9c0c5e1d8e4c.png)

## Environments

- OS: MacOS BigSur 11.7
- volar: v1.0.13
- vscode:

  ```txt
  Version: 1.74.0 (Universal)
  Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
  Date: 2022-12-05T16:43:37.594Z
  Electron: 19.1.8
  Chromium: 102.0.5005.167
  Node.js: 16.14.2
  V8: 10.2.154.15-electron.0
  OS: Darwin x64 20.6.0
  ```

## Reproduce steps

1. clone it and install volar and `pnpm i`
2. inspect `src/Hello/World/World.vue` & `src/Bye/World/World.vue`

**Comment by johnsoncodehk** [comment]
Thanks for the repro case!

**Comment by johnsoncodehk** [comment]
This is a TypeScript bug, please forward it to https://github.com/microsoft/TypeScript/issues.

Reproduce steps in TS:

1. Run `Volar (Debug): Write Virtual Files` command
2. Disable Volar Extension in the workspace (it can be ruled out that the follow-up problem has nothing to do with Volar.)
3. Reload VSCode
4. Open src/Bye/World/World.vue.js and check the highlighter

<img width="418" alt="螢幕截圖 2022-12-18 11 48 02" src="https://user-images.githubusercontent.com/16279759/208280367-4ab95f95-5526-4baa-821d-06aa1b5cc593.png">
