### ISSUE TITLE
vue-tsc error when passing imported component

### ISSUE THREAD

**Issue by Ragura** [johnsoncodehk/volar#2208]
When writing a function like this:
```ts
import type { DefineComponent } from 'vue';
type ImportedComponent = DefineComponent<any, {}, any>;

export function wrapperFactory(component: ImportedComponent) {
  return component;
}
```
And calling it with an imported component, for example like this:
```ts
import Custom from './components/Custom.vue';
import { wrapperFactory } from './composables/wrapperFactory';
const component = wrapperFactory(Custom);
```
I do NOT get a TS error inside VSCode (using take-over mode), but running `vue-tsc` gives the following error:
`Error: Debug Failure. No error for last overload signature`

I am aware my code likely doesn't work because the types of the imported component and the argument inside the function do not match, but I have two questions about this:
1. Why does VSCode not complain about the type error but `vue-tsc` does? Shouldn't they report the same?
2. What type am I supposed to use for the `wrapperFactory` function argument? It should work for any passed component, not just the one in the example.

I have created a minimal reproduction here: https://stackblitz.com/edit/vitejs-vite-cyklse?file=src/composables/wrapperFactory.ts
Simply run `vue-tsc` in the terminal to see the error pop up.

I am on `vue-tsc 1.0.13` and `typescript 4.9.3`.

Thank you for the hard work on all of these amazing DX tools!

**Comment by Ragura** [comment]
I have solved the required type for the component, but that was always going to be something wrong on my end so that's not your problem.
But it still leaves the issue that in the described case (and in the reproduction), VSCode reports no TS error, but running `vue-tsc` does. This should probably not happen?

**Comment by johnsoncodehk** [comment]
Thanks for the report, this is TypeScript bug, you can reproduce this problem for `tsc` with following steps:

1. Rename `App.vue` to `App.vue.ts` and replace file content to:

```ts
import Custom from './components/Custom.vue';
import { wrapperFactory } from './composables/wrapperFactory';

wrapperFactory(Custom);
```

2. Rename `Custom.vue` to `Custom.vue.ts` and replace file content to:

```ts
export default (() => {
    const __VLS_setup = async () => {
        const __VLS_publicComponent = (await import('vue')).defineComponent({
            props: ({} as __VLS_TypePropsToRuntimeProps<{
                title: string;
            }>),
            setup() {
                return {
                };
            },
        });
        return {} as typeof __VLS_publicComponent;
    };
    return {} as typeof __VLS_setup extends () => Promise<infer T> ? T : never;
})();
type __VLS_NonUndefinedable<T> = T extends undefined ? never : T;
type __VLS_TypePropsToRuntimeProps<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? { type: import('vue').PropType<__VLS_NonUndefinedable<T[K]>> } : { type: import('vue').PropType<T[K]>, required: true } };
```

3: Run `npx tsc`

You can forward this problem to https://github.com/microsoft/TypeScript/issues.
