### ISSUE TITLE
nested vueCompilerOptions.skipTemplateCodeGen not respected

### ISSUE THREAD

**Issue by LuisMiguelFilipe** [johnsoncodehk/volar#2216]
Hello,

I am trying to configure several `tsconfig.json` in my in order to gradually remove `skipTemplateCodeGen: true`

when I run `vue-tsc --noEmit` only the **root** `tsconfig.json` is taken into account

I have a structure like this

```
├── src/components
│   ├── tsconfig.json
│   ├── SomeComponent.vue
├── tsconfig.json
```
My root `tsconfig.json`

```
"vueCompilerOptions: {
  skipTemplateCodeGen: false,
}
```

In `src/components/tsconfig.json` I want to skip the check

```
"extends": "../../tsconfig",
"vueCompilerOptions: {
  skipTemplateCodeGen: true,
}
```

But errors in `SomeComponent.vue` are always reported
_I tried several combinations with no success_

I see this bug has been fixed already [here](https://github.com/johnsoncodehk/volar/issues/731)
Am I doing anything wrong or is this a bug?

`vue-tsc: 1.0.13`
`typescript: 4.9.4`

**Comment by johnsoncodehk** [comment]
This is expected behavior, vue-tsc does not support applying skipTemplateCodeGen for only part of .vue, and when you execute `vue-tsc --noEmit` all settings are based on root tsconfig.json without regard to src/components/tsconfig.json unless you execute `vue-tsc --noEmit -p src/components/tsconfig.json` to specify the tsconfig path.

**Comment by LuisMiguelFilipe** [comment]
Thank you for the reply. 

As an alternative, is there any way to individually mark files to be ignored?

Something like `ts-ignore` for the template only?

**Comment by johnsoncodehk** [comment]
This behavior requires the introduction of additional syntax, so we avoid doing it.

What TS error are you getting? Maybe I can suggest other workarounds.

**Comment by LuisMiguelFilipe** [comment]
I currently have 219 errors in around 100 files.
I would like to gradually introduce TS check in the project without forcing possibly one week to solve these errors.

The errors seem to be simple and honest.

I also read that TS is now supported in the template but I haven't tested it yet. Some type assertions might be a quick hack...

I suppose that another workaround could be to wrap some props with computed<any>.

All of the above are hacks. Maybe we should just spend the time upfront fixing the TS errors.

Thank you

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
