### ISSUE TITLE
Optional boolean prop gives type `Ref<boolean | undefined>` which should be `Ref<boolean>` in vue

### ISSUE THREAD

**Issue by jd-solanki** [johnsoncodehk/volar#2219]
SFC Playground: https://sfc.vuejs.org/#eNp9kN1qwzAMhV9F+KYbNDa7DW7H2AvsAXyTpkqTEv8gOy0j+N0npz9sHfTO50j6ZJ1ZfIQgTxOKWujY0hASRExT2Bo32OApwQyEHWToyFtYcevqXvr0Nlx9qYooJC5rdUExhEVCG8YmISsAvcwofmt1L4i1uBAr2wR5jN7xd+bSbq6FaEQNi1M83lK0EX1KIdZKxa4tq49RejoofkmaXBosSoy22pE/RyQGG7H+xVBsnpAqQrdHQnrGfGj9xy3YbFzmU25BPEYKY+MOGyPKMXx/611MEMiHCBvYYzc4/CpKL3fG3p/fa9h5P2LDMebty+vzZPu37Twvc5AzVMAifQf03c3Tilv+Bp9/APuhswM=

Here, we get `show` type as `Ref<boolean>` however in VS Code it is `Ref<boolean | undefined>` 🤔 

![image](https://user-images.githubusercontent.com/47495003/208264469-de3a6d7a-2f54-4805-8cd2-e106330522be.png)

**Comment by modelair** [comment]
props are not typed to Ref

**Comment by jmroon** [comment]
This is correct behavior if you have strictNullChecks on in typescript. Any optional property should be type | undefined.

**Comment by xiaoxiangmoe** [comment]
Type definition for `defineProps` is in https://github.com/vuejs/core/blob/1fa3d9573051f549e6d381a5e88ec8d5d855e4c9/packages/runtime-core/src/apiSetupHelpers.ts#L61

Please create an issue in vuejs/core
