### ISSUE TITLE
Feature Request: Automattic EventTarget detection

### ISSUE THREAD

**Issue by cawa-93** [johnsoncodehk/volar#222]
I have simple code in template:
```html
      <a
        href="https://github.com/cawa-93/anime-library/issues/new/choose"
        @click.prevent="openURL($event.target.href)"
      >🐞 Bug</a>
```
And I got TS error:
```node
error TS2531: Object is possibly 'null'.
     @click.prevent="openURL($event.target.href)"
                             ~~~~~~~~~~~~~

error TS2339: Property 'href' does not exist on type 'EventTarget'.
     @click.prevent="openURL($event.target.href)"
                                           ~~~~


```

It would be fantastic if the TS determined that
1. `EventTarget` actually is  `HTMLAnchorElement`
2. It is guaranteed exist

I use `vue-tsc` with PhpSthorm if this have matter

**Comment by johnsoncodehk** [comment]
Event types is upstream problem, it's define in vue-next: https://github.com/vuejs/vue-next/blob/ecd97ee6e465ec5c841d58d96833fece4e899785/packages/runtime-dom/types/jsx.d.ts#L1183-L1297

Please wait for TS support in template: https://github.com/vuejs/vue-next/issues/1359
You can do this after it's supported `openURL(($event.target as HTMLAnchorElement).href)`.
