### ISSUE TITLE
Removing {{ }} just got a lot more cumbersome! !

### ISSUE THREAD

**Issue by youkei-zzz** [johnsoncodehk/volar#2222]
1.Although Volar can now automatically add left and right spaces between curly braces, I find it more difficult when I want to remove such {{ | }}. Because now I can't remove paired curly braces due to the left and right added spaces, You can only delete the left side first and then delete the right side, which is really troublesome. If Volar can automatically match the inner and outer curly braces, then I only need to press delete twice, which avoids tedious operations.
<img width="143" alt="image" src="https://user-images.githubusercontent.com/101049479/208290585-e191b082-3c6a-4f7d-9ac0-b463fdb1581c.png">

2.When I don't want the content in {{ xxx }}, if I try to remove all content from the position of the vertical bar (like this {{ xxx |}}), when removing to this case ( {{|}} ) brackets The left and right spaces will be automatically added again, which is not the result I hope

**Comment by johnsoncodehk** [comment]
1. You can ctrl + z twice instead of deleting.
2. This is a bug, will fix it in the next version.

If you don't want this feature, you can set up `"volar.addSpaceBetweenDoubleCurlyBrackets": false` in VSCode settings to disable it.
