### ISSUE TITLE
Type 'void' has no call signatures.

### ISSUE THREAD

**Issue by Delevin888** [johnsoncodehk/volar#2225]
when i upgrade to `v1.0.14` , i got some error.

![image](https://user-images.githubusercontent.com/38110513/208336567-93779af2-c66f-4096-9751-1dca69e31115.png)

`v1.0.13` it's working fine. ↓↓↓↓↓↓↓↓↓↓↓↓↓

![image](https://user-images.githubusercontent.com/38110513/208336718-d923f179-0fcb-4236-b812-e0e88a24ecbc.png)

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem with vue-tsc v1.0.14?

**Comment by Delevin888** [comment]
![image](https://user-images.githubusercontent.com/38110513/208393478-bb898fd3-0978-4469-a6bc-370d29d13ff6.png)

yes ,it's still error.

**Comment by johnsoncodehk** [comment]
Can you get this error with run `npx vue-tsc --noEmit`?

**Comment by Delevin888** [comment]
![image](https://user-images.githubusercontent.com/38110513/208555554-e35ffc31-9716-4740-a6fd-77edefdec36c.png)

no error output, i'll upload case later.

**Comment by johnsoncodehk** [comment]
Can you try to increase `"volar.vueserver.maxFileSize": 20971520` in VSCode setting?

**Comment by johnsoncodehk** [comment]
Thanks for the repro case!

**Comment by johnsoncodehk** [comment]
Never mind, repro case is helpful. :)
