### ISSUE TITLE
typescript intellisence doesn't work after upgrade v1.0.14

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#2228]
https://user-images.githubusercontent.com/41773861/208366254-0989ec9c-550f-4837-864d-5bb89203e2d7.mov

**Comment by a573367014** [comment]
metoo

**Comment by icyfe** [comment]
help~!  i have same problem

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by johnsoncodehk** [comment]
Please try update TypeScript Vue Plugin to v1.0.15.
