### ISSUE TITLE
How to exclude some files for type checking with vue-tsc?

### ISSUE THREAD

**Issue by chnejohnson** [johnsoncodehk/volar#2229]
Hi @johnsoncodehk, 

In my project, I want to exclude `src/graphql/API.ts` for type-checking so I excluded it in `tsconfig` like this

- tsconfig.json
```json
"exclude": ["node_modules", "src/graphql/API.ts"]
```

But I still got the error from this file when I run `vue-tsc --noEmit` in the project

![截圖 2022-12-19 下午3 15 29](https://user-images.githubusercontent.com/31992185/208368716-9b52195f-b036-4b32-b4b7-bf88601ddb9a.png)

Could you provide me with some advice about how to solve this issue?

Thanks

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/2018#issuecomment-1281802717.

You may consider using `@ts-nocheck`.
