### ISSUE TITLE
using pnpm cannot get type checking even if defined GlobalComponents interface

### ISSUE THREAD

**Issue by qijizh** [johnsoncodehk/volar#2231]
in docs/installation.md#vue-2

> Optional If your Vue version is >=2.7 @vue/runtime-dom is already included

but `@vue/runtime-dom` doesn't in node_modules when i using pnpm , unless i define `shamefully-hoist` in `.npmrc` , is there any way to resolve it

**Comment by LinusBorg** [comment]
you could also just explicitly install it alongside  `vue`.

**Comment by qijizh** [comment]
thank you, it works.
