### ISSUE TITLE
Error Server Crashed

### ISSUE THREAD

**Issue by RoosDev** [johnsoncodehk/volar#2234]
Hello, 

Since 10 days I have an error when I start VSCode: 
`The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information. `

Or the message : 
`Connection to server got closed. Server will not be restarted.`

In output I have : 
`[Error - 1:04:41 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 `

I try to uninstall Volar and reinstall, reinstall VSCode but it still down. 

Can you help me ?

**Comment by johnsoncodehk** [comment]
Can you provide the error messages from output?

**Comment by RoosDev** [comment]
Yes of course (sorry it's my first bug report, I didn't see this details) so , the problem is :


Error: ENOENT: no such file or directory, chdir 'F:\\MyFiles\\Dev\\Sites\\Project10\\www' -> 'c:/wamp64/www/perso'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:495:26985)
    at c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:494:35743
    at Generator.next (<anonymous>)
    at c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:494:35252
    at new Promise (<anonymous>)
    at As (c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:494:35049)
    at xve (c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:494:35551)
    at Object.add (c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:494:40418)
    at c:\Users\Me\.vscode\extensions\vue.volar-1.0.14-win32-x64\dist\node\server.js:495:22966 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'F:\\MyFiles\\Dev\\Sites\\Project10\\www',
  dest: 'c:/wamp64/www/perso'
}
[Info  - 1:46:43 AM] Connection to server got closed. Server will restart.
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);

I had a wamp server before, but not today. And it's true,.... It fall down when I uninstall it.
So I just remove the 'Perso' workspace restart VSCode, and now it's working well.... 
Sorry !! But thank you for your quick answer.

**Comment by johnsoncodehk** [comment]
Thanks for the information. :)
