### ISSUE TITLE
v-slot error when `noPropertyAccessFromIndexSignature` is enabled with v1.0.14+

### ISSUE THREAD

**Issue by jfrs** [johnsoncodehk/volar#2236]
Similar to #561, after updating from `1.0.13` to `1.0.14` (same with `.15` and `.16`), if using `<template #actions>` or `<template v-slot:actions>` then `vue-tsc --noEmit` fails with `error TS4111: Property 'actions' comes from an index signature, so it must be accessed with ['actions'].`

**Comment by 6XGate** [comment]
This has started cropping up again.
