### ISSUE TITLE
[Enhencement] Support typescript 4.3.2 

### ISSUE THREAD

**Issue by harrytran998** [johnsoncodehk/volar#224]
Currently, TS was release v4.3.2 with awesome features! But with Volar in `.vue` file ==> The feature seems doesn't to work!

You can try the feature: `Import Statement Completions`
https://devblogs.microsoft.com/typescript/announcing-typescript-4-3-beta/#import-statement-completions

Hope you can upgrade this or have some way to pick TS version 🤔 ... Thank you <3

**Comment by johnsoncodehk** [comment]
Supported in 0.25.17.
