### ISSUE TITLE
Emmet Abbreviation suggestion keeps disappearing every third letter

### ISSUE THREAD

**Issue by IcyFoxe** [johnsoncodehk/volar#2240]
Whenever I'm typing into Vue Template or CSS, I've noticed that the Emmet Abbreviation keeps disappearing every third letter, which results in very frustrating experience.

This doesn't happen in native HTML files, Svelte files or Astro files. Only in Vue files while having this extension installed.

How to reproduce:

- in Vue template start typing `div.someclass` and you will notice that the suggestion keeps disappearing and appearing as you type letters

This issue happens in both my Mac and Windows machine, even with all extensions disabled.

**Comment by johnsoncodehk** [comment]
Seems to have been accidentally fixed by https://github.com/johnsoncodehk/volar/commit/5112dbef58d2a918aa96432ee2087f64b30d1d7d.
