### ISSUE TITLE
event name case suggestion in template

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#2243]
In volar starter:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/208958916-07a92076-464b-4a74-af34-aeadb14af353.png">

I define the event name using pascal case, but get kebab case suggrstion in template:

```typescript
defineEmits<{
    (e: 'changeFontSize', newFontSize: number): void;
}>();
```

**Comment by Sight-wcg** [comment]
volar.completion.preferredAttrNameCase

![image](https://user-images.githubusercontent.com/26325820/208976724-d1edb79e-d049-4927-805d-d3ec2a45379a.png)

**Comment by tjx666** [comment]
@Sight-wcg I want kebab for non-event attr, camel for event attr
