### ISSUE TITLE
Volar doesn't validate props of functional component

### ISSUE THREAD

**Issue by gordilovvv** [johnsoncodehk/volar#2251]
Version: 1.0.16

For example, we have same function
```
function Test({ foo }: { foo: string }) {
    return <div>test</div>
}
```

And volar doesn't throw error on wrong usage
```
<Test foo="{}" />
```

But it works good in v0.40.13

**Comment by gordilovvv** [comment]
https://github.com/johnsoncodehk/volar/issues/2206

**Comment by johnsoncodehk** [comment]
Duplicate of #2206
