### ISSUE TITLE
got the TS ERROR when typing the keywords in VUE3

### ISSUE THREAD

**Issue by netitgo** [johnsoncodehk/volar#2254]
![image](https://user-images.githubusercontent.com/72277244/209477453-e02fffa9-bd25-445c-86a8-19f04b00a330.png)

keywords like `ref`, `reactive`, `onMounted`, etc. are not capable of using the Inteligent autocomplete in writing VUE3 codes.
any idea for this issue?

**Comment by webdo** [comment]
Getting the same issue, gotta restart the server every 2-3 minutes just to get auto-completion to work, it's a bit of a pain.

```
VSCode Insiders 1.75.0
Using takeover mode with typescript 4.9.4, builtin is disabled.
Volar settings:
  "volar.vueserver.maxOldSpaceSize": 10000,
  "volar.vueserver.noProjectReferences": true,
  "volar.doctor.checkVueTsc": true,
  "volar.autoCompleteRefs": true,
  "volar.completion.preferredTagNameCase": "pascal"
```

**Comment by netitgo** [comment]
I still have this issue after re-install the Volar plug-in, what I have missed?

**Comment by Sc-6-23** [comment]
Volar 1.0.18 still have this problem

**Comment by webdo** [comment]
Can confirm we still have the problem, it seems to only be with vue functions.

**Comment by netitgo** [comment]
![image](https://user-images.githubusercontent.com/72277244/210129710-e9972d91-5dea-4d06-aefb-758c015defb2.png)
`v1.0.19` still fails me.

**Comment by johnsoncodehk** [comment]
See #2190.
