### ISSUE TITLE
Verify All Scripts is no longer an option

### ISSUE THREAD

**Issue by raymer** [johnsoncodehk/volar#2259]
Was this removed as a feature?

<img width="468" alt="image" src="https://user-images.githubusercontent.com/490221/209695279-759a7132-fb4b-49ed-8801-9921c47964c5.png">

**Comment by johnsoncodehk** [comment]
Yes it was removed on purpose, as it's not actually a Vue-specific feature, it was added to make it easier for users migrating from Vetur to check for migration errors before.

This feature should be provided as a standalone extension.
