### ISSUE TITLE
Doctor warning about @vue/compiler-dom when `vue-tsc` is installed in 2.7 project.

### ISSUE THREAD

**Issue by ascott18** [johnsoncodehk/volar#2262]
I'm getting the following doctor warning because `vue-tsc` has `@vue/compiler-dom` as an indirect dependency, but the warning is telling me to remove compiler-dom from my package.json.

```
HelloWorld.vue Doctor
❗ Unnecessary @vue/compiler-dom
Vue 2.7 already includes JSX type definitions. You can remove the @vue/compiler-dom dependency from package.json.

vue: c:\src\MyProject\node_modules\vue\package.json
@vue/compiler-dom: c:\src\MyProject\node_modules@vue\compiler-dom\package.json
```

```
> npm ls @vue/compiler-dom
MyProject@0.1.0 C:\src\MyProject
└─┬ vue-tsc@1.0.18
  └─┬ @volar/vue-language-core@1.0.18
    ├── @vue/compiler-dom@3.2.45
    └─┬ @vue/compiler-sfc@3.2.45
      ├── @vue/compiler-dom@3.2.45 deduped
      └─┬ @vue/compiler-ssr@3.2.45
        └── @vue/compiler-dom@3.2.45 deduped
``

**Comment by jhxxs** [comment]
this issue still exists 🥲
![image](https://github.com/vuejs/language-tools/assets/7448223/206fd3fc-c85d-4a78-9750-bb33d76fc896)

**Comment by maolovecoding** [comment]
> this issue still exists 🥲这个问题依然存在🥲 ![image](https://private-user-images.githubusercontent.com/7448223/254497667-206fd3fc-c85d-4a78-9750-bb33d76fc896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTkwMjgsIm5iZiI6MTcyODk5ODcyOCwicGF0aCI6Ii83NDQ4MjIzLzI1NDQ5NzY2Ny0yMDZmZDNmYy1jODVkLTRhNzgtOTc1MC1iYjMzZDc2ZmM4OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTMyNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmUyNmNmMGNkZTczYzFmNWNlOWZkNGM0MTRhYjhiOWUwYjk1ODBhMmY0YzQzMzY2MGY0MTBjNDFhZWZmNWU1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2fIJskvRrl1-lqjeZgfUWRuYjP30hZNkA8Oo2OeFTXs)

How did you solve the problem

**Comment by rchl** [comment]
`@vue/runtime-dom` is not part of `vue-tsc` anymore so this issue is fixed. If you have it in your project then it might be coming from some other package. Try running `npm ls @vue/runtime-dom`.
