### ISSUE TITLE
Support for adjusting the arrangement of  Split Editors

### ISSUE THREAD

**Issue by chen-ccy** [johnsoncodehk/volar#2265]
Whether the Split Editor can support adjusting the arrangement direction, I want to put the html code on the left and the JavaScript code on the right

**Comment by johnsoncodehk** [comment]
You can change it with `volar.splitEditors.layout.left`, `volar.splitEditors.layout.right` settings.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/16279759/210428097-058e32a0-1760-44fb-8a79-82561a7a1df2.png">
