### ISSUE TITLE
[ TS Error ] 自动导入问题

### ISSUE THREAD

**Issue by lengyibai** [johnsoncodehk/volar#2269]
![image](https://user-images.githubusercontent.com/74140255/210164567-e1be1e90-c2ae-4c0f-be15-473bf7b2ef52.png)
第一次，回车，可以自动导入
![image](https://user-images.githubusercontent.com/74140255/210164588-18415b75-c75f-46a2-aa6c-8a6d209cffbe.png)

接下来，想要导入其他，报错了
![image](https://user-images.githubusercontent.com/74140255/210164622-2600219a-221b-4b4b-9b8f-03d780306cc4.png)

之后导入也会报错
![image](https://user-images.githubusercontent.com/74140255/210164685-ffc72a01-7c90-4078-baa6-e1cab9874ed1.png)

**Comment by Swz0321** [comment]
今天回来写vue也碰见了，以为是我本地包的问题，结果换了vetur之后才知道是这个插件出了问题，

> ![image](https://user-images.githubusercontent.com/74140255/210164567-e1be1e90-c2ae-4c0f-be15-473bf7b2ef52.png) 第一次，回车，可以自动导入 ![image](https://user-images.githubusercontent.com/74140255/210164588-18415b75-c75f-46a2-aa6c-8a6d209cffbe.png)
> 
> 接下来，想要导入其他，报错了 ![image](https://user-images.githubusercontent.com/74140255/210164622-2600219a-221b-4b4b-9b8f-03d780306cc4.png)
> 
> 之后导入也会报错 ![image](https://user-images.githubusercontent.com/74140255/210164685-ffc72a01-7c90-4078-baa6-e1cab9874ed1.png)

我也碰见了，本来以为是编辑器的问题，写react正常，写vue就失效，换了vetur才发现是这个插件出了问题

**Comment by Swz0321** [comment]
> ![image](https://user-images.githubusercontent.com/74140255/210164567-e1be1e90-c2ae-4c0f-be15-473bf7b2ef52.png) 第一次，回车，可以自动导入 ![image](https://user-images.githubusercontent.com/74140255/210164588-18415b75-c75f-46a2-aa6c-8a6d209cffbe.png)
> 
> 接下来，想要导入其他，报错了 ![image](https://user-images.githubusercontent.com/74140255/210164622-2600219a-221b-4b4b-9b8f-03d780306cc4.png)
> 
> 之后导入也会报错 ![image](https://user-images.githubusercontent.com/74140255/210164685-ffc72a01-7c90-4078-baa6-e1cab9874ed1.png)

碰见的+1，换了vetur才正常

**Comment by johnsoncodehk** [comment]
Duplicate of #2190
