### ISSUE TITLE
[Bug Report] v-bind:key does not work well on functional components

### ISSUE THREAD

**Issue by meteorlxy** [johnsoncodehk/volar#227]
```vue
<template>
  <FnComp v-for="item in items" :key="item.text" :text="item.text" />
</template>

<script setup lang="ts">
import { h, ref } from 'vue';
import type { FunctionalComponent } from 'vue';

const FnComp: FunctionalComponent<{
  text: string;
}> = (props) => h('div', props.text);

FnComp.props = {
  text: {
    type: String,
    required: true,
  },
};

const items = ref([
  {
    text: 'foo',
  },
]);
</script>
```

![image](https://user-images.githubusercontent.com/18205362/120151151-7f91c880-c21e-11eb-82d4-72bdfc279838.png)

**Comment by johnsoncodehk** [comment]
Hi @meteorlxy, this is expected, try this:

```ts
const FnComp: FunctionalComponent<{
  [key: string]: unknown,
  text: string;
}> = (props) => h('div', props.text);
```

**Comment by meteorlxy** [comment]
I see.

So why a stateful component could work without specifying that?

**Comment by meteorlxy** [comment]
```vue
<template>
  <FnComp v-for="item in items" :key="item.text" :text="item.text" />
  <StatefulComp v-for="item in items" :key="item.text" :text="item.text" />
</template>

<script setup lang="ts">
import { defineComponent, h, ref } from 'vue';
import type { FunctionalComponent } from 'vue';

const FnComp: FunctionalComponent<{
  text: string;
}> = (props) => h('div', props.text);

FnComp.props = {
  text: {
    type: String,
    required: true,
  },
};

const StatefulComp = defineComponent({
  props: {
    text: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    return () => h('div', props.text);
  },
});

const items = ref([
  {
    text: 'foo',
  },
]);
</script>
```

![image](https://user-images.githubusercontent.com/18205362/120163792-7871b700-c22c-11eb-8bd0-a7c675bdf1c7.png)

Looks a little weird 🤔

**Comment by johnsoncodehk** [comment]
I have add `& Record<string, unknown>` to props type for non `FunctionalComponent`: https://github.com/johnsoncodehk/volar/blob/73d09c681b24afd36e14eaaabb32d472fd89f232/packages/vscode-vue-languageservice/src/virtuals/global.ts#L71

`FunctionalComponent` should have full control over the props type to avoid unexpected behavior. And some generic types may broken by `& Record<string, unknown>`.

**Comment by meteorlxy** [comment]
Thanks for answering.

Closing as it is expected behavior. I think it could be added to the [Tips](https://github.com/johnsoncodehk/volar/discussions/53)
