### ISSUE TITLE
Package installed `@volar/vue-language-plugin-pug missing` but showing missing

### ISSUE THREAD

**Issue by Tai1013** [johnsoncodehk/volar#2272]
Package installed `@volar/vue-language-plugin-pug missing` but showing missing

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/61581782/210236702-b426b89d-7c31-4da0-a6f8-25b34c993ced.png">

**Comment by Comelpho** [comment]
@Tai1013 Hello! Until the developers fix it, you can install the 1.0.18 version in npm and in VScode extensions. The warning should go away.
![image](https://user-images.githubusercontent.com/84480605/210250236-80344d48-6579-4839-a478-4eb311d9c1d4.png)
![image](https://user-images.githubusercontent.com/84480605/210250335-d2c52de3-7def-4b8d-98b8-60ad73df7517.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?
