### ISSUE TITLE
Global component intellisense in template

### ISSUE THREAD

**Issue by ci010** [johnsoncodehk/volar#228]
Follow the instruction, I added the definition of a global component

```ts
import { Component } from 'vue'

interface MyPropTypes { 
  /**
   * document content
   */
  p: string
}

declare module 'vue' {
  export interface GlobalComponents {
    componentName: Component<MyPropTypes>
  }
}

export { }
```

In the vue template, it cannot have correct intellisense hint for this component,
but if I change it to DefineComponent

```ts
import { DefineComponent } from 'vue'

declare module 'vue' {
  export interface GlobalComponents {
    componentName: DefineComponent<MyPropTypes>
  }
}

export { }
```

it works, whereas the code navigation is wrong.

```vue
<template>
   <my-component :p="xxx" />
</template>
```

Go to definition not work for `p` (it works if I use Component), and it cannot show the document of it.

**Comment by johnsoncodehk** [comment]
Please wait for https://github.com/vuejs/vue-next/pull/3656.
