### ISSUE TITLE
File not found when clicking on .vue import in .ts file

### ISSUE THREAD

**Issue by mdoesburg** [johnsoncodehk/volar#2281]
Prior to version 1.0.20 I could navigate to a `.vue` file from a `.ts` file.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/3763566/210659884-9013a684-5bb5-4b74-8248-0b557c36f493.png">

If I attempt to navigate to `HelloWorld` in the example above, I now get this:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3763566/210659982-4d2cb8e9-c283-41a2-9e57-018e691a555e.png">

It tries to go to a `.vue.ts` file instead of `.vue`.

This is with takeover mode enabled. Downgrading to 1.0.19 fixes the problem.

**Comment by sechi747** [comment]
update to latest version, it has been resolved.

**Comment by johnsoncodehk** [comment]
FIxed by https://github.com/johnsoncodehk/volar/commit/5d7bfff546365631840122d811e4669e2a341cba
