### ISSUE TITLE
Request textDocument/documentLink failed with message: c is not iterable

### ISSUE THREAD

**Issue by fjqingyou** [johnsoncodehk/volar#2282]
# basic
switch editor file to *.vue, show this error
don't exists call stack info

``` log
[Error - 10:30:47] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: c is not iterable
  Code: -32603 
```

# env
## vscode
版本: 1.74.2 (user setup)
提交: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
日期: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: No

## Vue Language Features
名称: Vue Language Features (Volar)
ID: Vue.volar
说明: Language support for Vue 3
版本: 1.0.12
发布者: Vue
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by johnsoncodehk** [comment]
Please update your extension version, the latest version is v1.0.22.

**Comment by fjqingyou** [comment]
update to 1.0.22 and restart vscode, this error still exists

名称: Vue Language Features (Volar)
ID: Vue.volar
说明: Language support for Vue 3
版本: 1.0.22
发布者: Vue
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by fjqingyou** [comment]
@johnsoncodehk

**Comment by fjqingyou** [comment]
What do I need to do to get more information

**Comment by fjqingyou** [comment]
What do I need to do to get more information

**Comment by johnsoncodehk** [comment]
Do you have setup `vueCompilerOptions.plugins` in tsconfig?

**Comment by fjqingyou** [comment]
my tsconfig.json
``` json
{
    "compilerOptions": {
        "outDir": "./build",
        "target": "es6",
        "module": "es2020",
        "moduleResolution": "node",
        "strict": true,
        "jsx": "preserve",
        "importHelpers": true,
        "experimentalDecorators": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": false,
        "sourceMap": true,
        "types": [
            "webpack-env"
        ],
        "lib": [
            "esnext",
            "dom",
            "dom.iterable",
            "scripthost"
        ]
    },
    "include": [
        "src/**/*.ts",
        "src/**/*.tsx",
        "src/**/*.vue",
        "tests/**/*.ts",
        "tests/**/*.tsx"
    ],
    "exclude": [
        "node_modules"
    ],
    "vueCompilerOptions": {
        "target": 2,
        "extensions": [
            ".vue"
        ],
    }
}
```

**Comment by johnsoncodehk** [comment]
Since the release version is minify, I can't know what variable `c` is. I pack this non-minify version, can you try it and tell me the error message again?

[volar-1.0.22-6168c509.vsix.zip](https://github.com/johnsoncodehk/volar/files/10368241/volar-1.0.22-6168c509.vsix.zip)

**Comment by fjqingyou** [comment]
``` log
[Error - 19:26:26] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: failedLookupLocations is not iterable
  Code: -32603 
[Error - 19:26:26] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: failedLookupLocations is not iterable
  Code: -32603 
[Error - 19:26:36] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: failedLookupLocations is not iterable
  Code: -32603 
```

**Comment by johnsoncodehk** [comment]
What's your project typescript version? (You can see it at status bar)

**Comment by fjqingyou** [comment]
Sorry, network failure. Just recovered

>tsc --version
Version 4.9.3

project package.json devDependencies
"typescript": "~3.9.3",

node_modules/typescript/package.json
"version": "3.9.10",

**Comment by johnsoncodehk** [comment]
Can you try this version and still have problems?

[volar-1.0.22-8e28d05b.vsix.zip](https://github.com/johnsoncodehk/volar/files/10368298/volar-1.0.22-8e28d05b.vsix.zip)

**Comment by fjqingyou** [comment]
it's right, not create message window, only print a log
thanks
``` log
[volar] failedLookupLocations not exists, ts: 5.0.0-dev.20221209
[volar] failedLookupLocations not exists, ts: 5.0.0-dev.20221209
[volar] failedLookupLocations not exists, ts: 5.0.0-dev.20221209
[volar] failedLookupLocations not exists, ts: 5.0.0-dev.20221209
[volar] failedLookupLocations not exists, ts: 5.0.0-dev.20221209
[volar] failedLookupLocations not exists, ts: 5.0.0-dev.20221209
```
