### ISSUE TITLE
[Bug] Importing `.vue` file in `.jsx` file added `.js` extension

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#229]
Repro: https://github.com/wenfangdu/volar-jsx-import-vue-repro

![volar](https://user-images.githubusercontent.com/28700378/120189052-710cd680-c249-11eb-89c9-3c9bfcda4676.gif)

**Comment by johnsoncodehk** [comment]
I can't reproduce, please provide some informations:

- VSCode info from `Help: About` command
- volar version
- Is TS plugin enabled?

**Comment by wenfangdu** [comment]
- VSCode Info
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
- Volar Version
v0.25.17
- TS plugin is enabled

**Comment by wenfangdu** [comment]
I see why now, to reproduce, please turn on `"javascript.preferences.importModuleSpecifierEnding": "js"` in your VSCode settings. For importing `.vue` files in `.js`/`.jsx` files, I think this setting should be ignored.

**Comment by johnsoncodehk** [comment]
I see, this is expected behavior. Will check is it suitable for patching or not.

**Comment by wenfangdu** [comment]
@johnsoncodehk
Since `.vue` files import auto-completion can only be enabled by enabling Volar, I think it makes sense to remove the `.js` suffix when auto-completing, could you please reconsider patching?

**Comment by johnsoncodehk** [comment]
Since patching involves too much hacking, and this is expected behavior, it is temporarily decided not to patch. I want to avoid hacking to achieve unexpected but correct behavior.
