### ISSUE TITLE
take over mode, [ts error] debug failure

### ISSUE THREAD

**Issue by 2nthony** [johnsoncodehk/volar#2294]
the demo is created by vite, template is vue-ts

**volar version: 1.0.24, other deps see package.json below.**

### repo

- enable take over mode
- create `helpers.ts`
- exports something
- use/import in `App.vue`
- rename the exported function in `helpers.ts`
- then issue appear in vue file

https://user-images.githubusercontent.com/19513289/211232345-f9216705-c665-4081-8b03-87a8b36c7759.mp4

package.json

```json
{
  "name": "volar-bug",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.2.45"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.0.0",
    "vue-tsc": "^1.0.11"
  }
}
```

---

I am not sure.

**Comment by MaksymShutiak** [comment]
Have the same issue in neovim  . Any updates on this ?

**Comment by MaksymShutiak** [comment]
@2nthony i tried to downgrade typescript and it works .

Try to install 4.5.2 and it will help. Look like some library updates and Volar isn't ready for it :)

**Comment by onur-caplena** [comment]
Have the same issue as well, downgrading Typescript does not help either.
