### ISSUE TITLE
Syntax highlight breaks when using directives/events without parameters

### ISSUE THREAD

**Issue by rafaelpimpa** [johnsoncodehk/volar#23]
Examples:

![image](https://user-images.githubusercontent.com/18370605/98842559-84c92a80-2428-11eb-86ae-30c5dcf7c8a7.png)

![image](https://user-images.githubusercontent.com/18370605/98842498-71b65a80-2428-11eb-920a-52d11b4a3c2a.png)

**Comment by johnsoncodehk** [comment]
Thanks for your report! Has been fixed in 0.15.3.
