### ISSUE TITLE
[Bug] No path intellisense for `.jsx` files when src importing

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#230]
Repro: https://github.com/wenfangdu/volar-jsx-import-vue-repro

![image](https://user-images.githubusercontent.com/28700378/120190119-bd0c4b00-c24a-11eb-8412-0a51d9efd1d9.png)

**Comment by johnsoncodehk** [comment]
You need to config `"allowJs": true`, otherwise `*.jsx` is not include to language service.

**Comment by wenfangdu** [comment]
> [Tip: jsconfig.json is a descendant of tsconfig.json, which is a configuration file for TypeScript. jsconfig.json is tsconfig.json with the _"allowJs"_ attribute set to true.](https://code.visualstudio.com/docs/languages/jsconfig#_what-is-jsconfigjson)

@johnsoncodehk If using `jsconfig.json` or no `jsconfig.json`/`tsconfig.json`, I guess `"allowJs": true` is enabled by default?

**Comment by johnsoncodehk** [comment]
Support without `jsconfig.json` / `tsconfig.json` need to preset some options, `allowJs` is one of them. In order to avoid confusion, it is temporarily not supported.

**Comment by wenfangdu** [comment]
> `jsconfig.json` is already supported.

Yes, indeed, it didn't work somehow.
