### ISSUE TITLE
source.addMissingImports auto import props field

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#2304]
enable takeover mode: yes
vscode settings:

```
{
    "editor.codeActionsOnSave": {
        "source.addMissingImports": true,
        "source.fixAll.eslint": true,
        "source.fixAll.stylelint": true,
        "source.fixAll.markdownlint": true,
        "source.organizeImports.sortImports": false
    },
}
```

https://user-images.githubusercontent.com/41773861/211499707-9948a248-7ad3-47c3-b331-474803ff7139.mov

**Comment by Doeke** [comment]
Same here, it keep trying to add the import even though there is already a prop defined with the same name

**Comment by danielwaltz** [comment]
I am also running into this for globally registered components in a `vue@2.7.*` application using `vuetify@2.*` with `unplugin-vue-components`.

Old behavior is a template like this works just fine without automatically adding imports:

```vue
<script setup lang="ts">
import AppMain from '@/components/AppMain.vue';
import AppMainHeader from '@/components/AppMainHeader.vue';
</script>

<template>
  <AppMain>
    <AppMainHeader class="mb-6" />

    <v-card>
      <router-view />
    </v-card>
  </AppMain>
</template>
```

New behavior is after saving it looks like this:

```vue
<script setup lang="ts">
import AppMain from '@/components/AppMain.vue';
import AppMainHeader from '@/components/AppMainHeader.vue';
import { RouterView } from 'vue-router'; // automatically added
import { VCard } from 'vuetify/lib'; // automatically added
</script>

<template>
  <AppMain>
    <AppMainHeader class="mb-6" />

    <v-card>
      <router-view />
    </v-card>
  </AppMain>
</template>
```

I found that I can work around this by defining `vueCompilerOptions.nativeTags` with a list of these globally registered components to skip the auto import, but that feels kludgy and hard to maintain. Is there a way to exclude globally registered components from this add missing imports option?

**Comment by johnsoncodehk** [comment]
Since `source.addMissingImports` actually has never worked for `codeActionsOnSave` in the past, setting `"source.addMissingImports": false` is the best workaround for now.
