### ISSUE TITLE
Spaces removed from ternary operator inside {{ }}

### ISSUE THREAD

**Issue by braincomb** [johnsoncodehk/volar#2305]
I noticed this issue was introduced in version 1.0.20.

1.0.19 formatting works as expected:
```vue
{{ a ? b : c }}
```

1.0.20 formatting removes spaces like so:
```vue
{{ a? b: c }}

**Comment by johnsoncodehk** [comment]
Thanks for the report! Could you try this version? 
[volar-1.0.26-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/10534102/volar-1.0.26-alpha.1.vsix.zip)
