### ISSUE TITLE
Way to disable includeCompletionsForModuleExports TS option?

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#2320]
There doesn't seem to be a way to disable the `ts.server.protocol.UserPreferences.includeCompletionsForModuleExports` Typescript option. It's a performance killer in Sublime Text due to TS possibly returning 8MB of completions when it's enabled. It would nice if there would be a way to disable it. Hopefully it wouldn't affect too much of Volar functionality.

**Comment by johnsoncodehk** [comment]
It can disable by `javascript.suggest.autoImports` & `typescript.suggest.autoImports` settings.

Doesn't https://github.com/typescript-language-server/typescript-language-server have this problem? If yes, what the different of typescript-langauge-server response with Volar?

**Comment by rchl** [comment]
Thanks. I was grepping for the option but didn't realize that it now lives in https://github.com/volarjs/plugins :)

Yes, [tsl](https://github.com/typescript-language-server/typescript-language-server) has the same issue. Or well, it's ST that has issue with such big completion lists. It causes minor freezes of the UI.
