### ISSUE TITLE
pug v-if not guarded as defined / != null

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#2329]
I have a weird bug 🤔 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/7195563/213701485-af74224f-76a9-4f28-af4e-2116f82b9e53.png">

I have a component and use `v-if="panel"` for checking if the variable is not `null`
But in the `@click` it is still nullable, but this will never be `null` there

**Comment by rchl** [comment]
It can be `null` because that code will run when clicking the element so at that point `panel` might have become `null`.

**Comment by Shinigami92** [comment]
@rchl 
How am I possible to click on the button when the `panel` is `null`?

**Comment by rchl** [comment]
That's true, the element will disappear then. I suppose that's not something the type system is aware of though so it might be hard to fix, if possible at all. Also there might be an issue like that already.

**Comment by Shinigami92** [comment]
As far as I know in a much historical previous version of volar this was working and didn't complain
Then later on @johnsoncodehk started to implemented more and more type heavier commits to volar
So I assume it is somehow possible to fix it at least in the context when the variable is on the same tag/component

**Comment by johnsoncodehk** [comment]
We used to support it in 0.21.6, then removed it in 0.21.14, so it caused some wrong type behavior.
Later 0.34.12 supports it in [another way](https://github.com/johnsoncodehk/volar/issues/1249), in the latest version you need to set `vueCompilerOptions.narrowingTypesInInlineHandlers = true` in tsconfig to enable it.

**Comment by Shinigami92** [comment]
@johnsoncodehk I hope I just did not missed it but I feel like you need to setup a documentation (Maybe even with VitePress like other Vue-Ecosystem tools)

**Comment by johnsoncodehk** [comment]
Yes we plan to document it at https://vuejs.org/.

**Comment by Shinigami92** [comment]
Just as a user feedback:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/7195563/214237130-a19a148e-850c-48d9-96e0-2afea5982284.png">

this is the place/link where I would usually look for a docs link

**Comment by johnsoncodehk** [comment]
Good idea. :)

**Comment by EmilyRagan** [comment]
> Yes we plan to document it at https://vuejs.org/.

@johnsoncodehk Has this been documented on the Vue.js site? I get no results when searching for `vueCompilerOptions` or `narrowingTypesInInlineHandlers`, and there is no reference to this in the `v-on` documentation
