### ISSUE TITLE
Variable guarded by `v-if` is possibly undefined within the `@click` event handler

### ISSUE THREAD

**Issue by DamianGlowala** [johnsoncodehk/volar#2335]
Is this behavior intended?

![image](https://user-images.githubusercontent.com/48835293/214389149-67a5b7f0-616e-4978-8113-78ff19a4cbe4.png)
![image](https://user-images.githubusercontent.com/48835293/214389393-32a36a1f-00e1-49f5-9e1c-2f4dc1150f35.png)

**Comment by Shinigami92** [comment]
https://github.com/johnsoncodehk/volar/issues/2329#issuecomment-1401158179
