### ISSUE TITLE
Old `vue-tsc` repo contains broken redirect

### ISSUE THREAD

**Issue by dpschen** [johnsoncodehk/volar#2336]
The old and archived repo https://github.com/johnsoncodehk/vue-tsc has a broken redirect link pointing to [`https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc`](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc)

The link should point instead to [`https://github.com/johnsoncodehk/volar/tree/master/vue-language-tools/vue-tsc`](https://github.com/johnsoncodehk/volar/tree/master/vue-language-tools/vue-tsc)

Normally I wouldn't mind but since [a google search for `vue-tsc`](https://www.google.com/search?q=vue-tsc) lists the old repo already on the second position I followed this broken link manually now multiple times:

![image](https://user-images.githubusercontent.com/6173598/214424146-b2ebdede-e369-492f-a99f-cb2953017545.png)

Since the old repo is archived I wasn't able to create a pull request there :)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/johnsoncodehk/volar/issues/2319

**Comment by dpschen** [comment]
Oops, thanks. Closing this in favour of #2319.
