### ISSUE TITLE
[FR] Setting to add file extension for `.js`/`.jsx` files in import path intellisense

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#235]
Currently, no file extension is shown in the path intellisense for `.js`/`.jsx` files like `.vue` files do, would be great if we have the option to enable that.

Please note: the desired behavior should be completing what's shown in the intellisense, e.g. `Foo.ts`/`Foo.tsx` being shown as `Foo`, and completed as `Foo`, `Foo.js`/`Foo.jsx` being shown as they are, and completed as they are.

![image](https://user-images.githubusercontent.com/28700378/120271538-1a051100-c2de-11eb-806f-a62efb3b3215.png)

![image](https://user-images.githubusercontent.com/28700378/120271670-57699e80-c2de-11eb-8e5e-5b4ea1524700.png)

Repro: https://github.com/wenfangdu/volar-jsx-import-vue-repro

**Comment by johnsoncodehk** [comment]
Will check to use TS settings.

**Comment by johnsoncodehk** [comment]
Support `javascript.preferences.importModuleSpecifierEnding`, `typescript.preferences.importModuleSpecifierEnding` in 0.26.3.

**Comment by wenfangdu** [comment]
@johnsoncodehk Thanks! I've set `"javascript.preferences.importModuleSpecifierEnding": "js"`, but v0.26.3 doesn't fill the extension:

![STG 2021-07-17 10_52_51](https://user-images.githubusercontent.com/28700378/126023168-0f9c01ec-d8ee-4c2b-883b-232889a7cff1.gif)

**Comment by johnsoncodehk** [comment]
You should use `javascript.preferences.importModuleSpecifierEnding` on allowJs project maybe.

**Comment by wenfangdu** [comment]
@johnsoncodehk If I set `"typescript.preferences.importModuleSpecifierEnding": "js"`, I will get the following behavior:

![STG 2021-07-17 11_21_21](https://user-images.githubusercontent.com/28700378/126023899-a174ba50-cec3-44f1-90c9-c197ebf5d8b4.gif)

Which is not ideal, since importing `ts`/`tsx` files with extensions generally is not allowed.

Could we switch to when importing `js`/`jsx` files, use `javascript.preferences.importModuleSpecifierEnding`, and when importing `ts`/`tsx` files, use `typescript.preferences.importModuleSpecifierEnding`?

**Comment by johnsoncodehk** [comment]
For `<script>` / `<script lang="js">` / `<script lang="jsx">`, you should use `javascript.preferences.*`.
For `<script lang="ts">` / `<script lang="tsx">`, you should use `typescriptt.preferences.*`.

This behavior is incorrect 0.26.3, has been fixed in https://github.com/johnsoncodehk/volar/commit/e892ba095e94d6157febb33d93a8caaadaaa43e2.

> Could we switch to when importing `js`/`jsx` files, use `javascript.preferences.importModuleSpecifierEnding`, and when importing `ts`/`tsx` files, use `typescript.preferences.importModuleSpecifierEnding`?

We need to keep the same behavior as TS to avoid confusion. You can open an issue in the typescript repo if you think this is incorrect behavior.

**Comment by wenfangdu** [comment]
> For `<script>` / `<script lang="js">` / `<script lang="jsx">`, you should use `javascript.preferences.*`.
> For `<script lang="ts">` / `<script lang="tsx">`, you should use `typescript.preferences.*`.

@johnsoncodehk Sorry, got myself confused there, what you described is the correct behavior.
