### ISSUE TITLE
add Reactive Variables support

### ISSUE THREAD

**Issue by chiboreache** [johnsoncodehk/volar#2359]
![2023-02-05x02:58:27](https://user-images.githubusercontent.com/16459251/216794610-abebbd9e-9a21-4ffb-bd3a-3628f8d387ab.png)

**Comment by so1ve** [comment]
https://vuejs.org/guide/extras/reactivity-transform.html#typescript-integration

**Comment by chiboreache** [comment]
@so1ve would be nice to have some sort of automatization, due to `reactivityTransform: true`

![2023-02-05x22:36:45](https://user-images.githubusercontent.com/16459251/216841083-f3cf410d-de06-463e-8739-da5c3423d03f.png)
