### ISSUE TITLE
Provide dynamic prompt app.component to introduce component switch

### ISSUE THREAD

**Issue by TuiMao233** [johnsoncodehk/volar#236]
shims-volar.d.ts is inconvenient for large-scale development projects

![image](https://user-images.githubusercontent.com/49724027/120286860-45ddc200-c2f1-11eb-806b-15a87843df0b.png)

![image](https://user-images.githubusercontent.com/49724027/120287091-7f163200-c2f1-11eb-84fb-7e4a43014c98.png)

**Comment by johnsoncodehk** [comment]
`vite-plugin-components` built entirely for your case, see https://github.com/antfu/vite-plugin-components#typescript.
