### ISSUE TITLE
[FR] Provide a setting to opt out of the default saving code actions

### ISSUE THREAD

**Issue by wenfangdu** [johnsoncodehk/volar#237]
> [Vetur do not support code actions like Remove all unused code, Organize Imports... so it just do nothing on save, but Volar support it, so it will do multiple code actions when you save file.](https://github.com/johnsoncodehk/volar/discussions/144)

I'm not sure if the above statement is still relevant, if so, please read on.

---

Many people already have this config in their VSCode settings:

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
```

If Volar drastically slows down the saving process, people can have an option not to do Volar's saving code actions.

**Comment by johnsoncodehk** [comment]
I think this is a bug if VSCode's TS extension do not have performance problem on save with this config.

**Comment by wenfangdu** [comment]
@johnsoncodehk I've turned `source.fixAll.eslint` off, but seems Volar doesn't do the ESLint fixes, am I missing something?

**Comment by johnsoncodehk** [comment]
> it often takes several seconds to save a 10-line file, which is quite slow.

Can this problem fix with volar disabled? If yes, please try to provide profiling.

https://github.com/johnsoncodehk/volar/blob/master/.github/STEP_TO_PROFILING.md

**Comment by wenfangdu** [comment]
Seems a recent update fixed the performance issue when using with ESLint fix on saving, I'm going to close it for now, since it needs further investigation.

**Comment by johnsoncodehk** [comment]
Some performance issues only appear in the release version, which may be related to vscode's resource allocation strategy.

I will check how to profiling in non-debug environment.
