### ISSUE TITLE
Property 'title' does not exist on type 'unknown'.

### ISSUE THREAD

**Issue by anyclub** [johnsoncodehk/volar#240]
![image](https://user-images.githubusercontent.com/19922265/120461163-59aa2680-c3cc-11eb-99c4-3df2d91df2d2.png)

how to fixe it

**Comment by johnsoncodehk** [comment]
This is expected, you need to define value type correctly.

```
value: {
  type: Array as PropType<{ title: string }[]>
}
```

**Comment by anyclub** [comment]
This is a JS file and not a TS
Is there any other plan?

**Comment by ci010** [comment]
Do you mean we should disable part of typecheck function for js script by default?

**Comment by anyclub** [comment]
typecheck is very helpful most of the time, but if my project cannot use TS, similar situations may happen from time to time.
It is recommended to have a disable check switch for the value passed in PROPS, 
or similar to eslint use injection `/* eslint-disable */` `/* eslint-enable */` ......

**Comment by johnsoncodehk** [comment]
`@ts-ignore` is available in template:

```
{{
  // @ts-ignore
  item.title
}}
```

Please wait for https://github.com/vuejs/vue-next/issues/1359, we can use `(item, inidex) in value as { title: string }[]` to resolve after vue supported TS in template.

**Comment by Huahua-Chen** [comment]
use jsdoc?
```
@type {import('@vue/runtime-dom').PropType<any[]>}
type: Array
```
