### ISSUE TITLE
Unable to load schema from '<filepath>'. No schema request service available(768)

### ISSUE THREAD

**Issue by ci010** [johnsoncodehk/volar#243]
When I added a custom block with lang=json in sfc

```xml
<config lang="json">
{
  "$schema": "<file path>",
  ... rest of json
}
</config>
```

and I want to add schema to the json (so I have intellisense), but it gives me 
`Unable to load schema from '<file path>'. No schema request service available(768)`.

It seems we do not support json schema service right now. Do we plan to have this?

**Comment by johnsoncodehk** [comment]
Yes we will support it.
