### ISSUE TITLE
[Enhancement] Support typescript pnp

### ISSUE THREAD

**Issue by harrytran998** [johnsoncodehk/volar#248]
In typescript files, I can choose the TS version `4.3.2-pnpify` like the image below.
![image](https://user-images.githubusercontent.com/24296018/120887394-c156b080-c61c-11eb-8e65-6b80b964de8a.png)

But in the `.vue` file, I can't choose the version like above

![image](https://user-images.githubusercontent.com/24296018/120887440-1397d180-c61d-11eb-900d-a7148d0e02e5.png)

Additionally, it's the warning of volar
```
Cannot import Vue 3 types from @vue/runtime-dom. If you are using Vue 2, you may need to install @vue/runtime-dom in additionally.
```

Hope you can implement it!

**Comment by AlexandreBonaventure** [comment]
This is more a yarn pnp problem than anything. Follow this issue: https://github.com/yarnpkg/berry/issues/2986

**Comment by johnsoncodehk** [comment]
> This is more a yarn pnp problem than anything. Follow this issue: [yarnpkg/berry#2986](https://github.com/yarnpkg/berry/issues/2986)

I don't know anything about this issue, so thank you for posting related issues! Will fix in 0.25.21.

**Comment by merceyz** [comment]
I don't think that's the right fix, the `tsserver.js` file isn't the same as `tsserverlibrary.js`

0.25.21 is now crashing instantly with this error:
```
{"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":2796}}
[Error - 00:45:51] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'VariableDeclaration' of undefined
  Code: -32603 
```

**Comment by johnsoncodehk** [comment]
@merceyz please try TS `4.3.2` instead of `4.3.2-pnpify`, if the problem only occur in `4.3.2-pnpify`, it should be upstream problem.

**Comment by merceyz** [comment]
Yeah, we were returning the wrong object, will be fixed with https://github.com/yarnpkg/berry/pull/2995. I couldn't get go to definition to work but everything else looks to be working fine.

**Comment by johnsoncodehk** [comment]
Due to upstream already supported `tsserverlibrary.js`, we will reuse `tsserverlibrary.js` in 0.26.6.
