### ISSUE TITLE
Template component autocomplete does not work after dash

### ISSUE THREAD

**Issue by Doeke** [johnsoncodehk/volar#249]
With cursor before dash:

![Screenshot from 2021-06-06 03-03-12](https://user-images.githubusercontent.com/240530/120909290-fc380300-c673-11eb-8d3e-a59f530eaa24.png)

With cursor after dash:

![Screenshot from 2021-06-06 03-02-30](https://user-images.githubusercontent.com/240530/120909289-f8a47c00-c673-11eb-8bb2-0c6677eaac04.png)

Also the import is only added automatically if you use tab key to complete, but not if you click the item in the list.

Project created with `npm init @vitejs/app my-vue-app -- --template vue-ts`

`Volar 0.25.17`

**Comment by johnsoncodehk** [comment]
Thanks for the report! Will fix the "dash problem".

The second problem is upstream problem, please focus https://github.com/microsoft/vscode-languageserver-node/issues/766.
