### ISSUE TITLE
Add syntax highlight for self closing tags.

### ISSUE THREAD

**Issue by soulsam480** [johnsoncodehk/volar#25]
Hii, It's me again.
If it's possible can you add syntax highlighting for self-closing tags? I have attached an image for your reference.

![asrwer](https://user-images.githubusercontent.com/35460828/100363734-2b195080-3023-11eb-97fb-e20d628ba13a.JPG)

**Comment by johnsoncodehk** [comment]
I am still hard to see this problem when you raise it... to not obvious!

Thanks for your report :) will be fixed in next version.

**Comment by johnsoncodehk** [comment]
fixed in 0.15.14.
