### ISSUE TITLE
Does auto-import support components in node_modules ?

### ISSUE THREAD

**Issue by jiyingzhi** [johnsoncodehk/volar#255]

**Comment by johnsoncodehk** [comment]
volar search vue files by tsconfig, you need to setup `include`:

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    // ...
  },
  "include": [
    // ...
    "node_modules/**/*.vue"
  ]
}
```

**Comment by jiyingzhi** [comment]
Bug most of libraries are pre-compiled into .js file，Can Volar supports these?

**Comment by johnsoncodehk** [comment]
Considering performance, we only auto import .vue extension files.
