### ISSUE TITLE
Publish some Volar types in a standalone package

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#2557]
In #2267 there is an example of a plugin/module that one can create for Volar. It's annotated with a `import('@volar/language-core').LanguageModule` type but to take advantage of that annotation one would have to have volar installed in the project which IMO is not realistic thing to expect.

My thinking is that the the types (at least `LanguageModule` and related once) could be published separately so that one could add just the type package as a devDependency to the project.

I can't think of any other solution for that.

**Comment by johnsoncodehk** [comment]
"@volar/language-core" is almost a root dependency, and I think is fine to install it in "devDependency". It would be a maintenance issue if separate into an individual type package.

**Comment by rchl** [comment]
OK
