### ISSUE TITLE
Takes high cpu usage, use with vite vue3 typescript app.

### ISSUE THREAD

**Issue by shadowdreamer** [johnsoncodehk/volar#256]
## using volar:
![image](https://user-images.githubusercontent.com/4878501/121455235-b01ff200-c9d6-11eb-9174-e7214bdecd7e.png)

vscode status:

```
CPU %   Mem MB     PID  Process
    0       77    8468  code main
    0      257    6800     window (App.vue - hkloan - Visual Studio Code)
    0       76    9860       searchService
    0       12   19928       watcherService
    0       11   22892         console-window-host (Windows internal process)
    0      129   25200       extensionHost
    0       75    4188         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=25200
    0       98    4468         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=25200
    0       76   15512         "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=25200
    0      113   24988         electron_node server.js
   13      268   25068         electron_node server.js
   13      259   25468         electron_node server.js
    0       66    8496     shared-process
    0       23   23044       ptyHost
    0        6   22276         console-window-host (Windows internal process)
    0       69   26048         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0       30   22180     utility
    0        8   22580     crashpad-handler
    0      194   22600     gpu-process

## Workspace Stats:
|  Window (App.vue - hkloan - Visual Studio Code)
|    Folder (hkloan): 48 files
|      File types: ts(9) vue(7) json(5) js(4) ico(2) html(2) gitignore(1)
|                  css(1) md(1) png(1)
|      Conf files: package.json(1) tsconfig.json(1)
```

## disable volar:
![image](https://user-images.githubusercontent.com/4878501/121454457-697dc800-c9d5-11eb-9d03-6bee8ae5f3d3.png)

## package.json:
```
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "vue": "^3.0.5",
    "vue-i18n": "^9.1.6",
    "vue-router": "4",
    "vuex": "^4.0.1"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.170",
    "@vicons/ionicons5": "^0.8.0",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.2.6",
    "naive-ui": "^2.11.4",
    "postcss": "^8.3.0",
    "pug": "^3.0.2",
    "sass": "^1.34.1",
    "tailwindcss": "^2.1.4",
    "typescript": "^4.3.2",
    "vite": "^2.3.7",
    "vue-tsc": "^0.0.24"
  }
}

```

## tsconfig:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./src/*"
      ]
    },
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}

```
already disabled all another extensions (only leave Chinese  Language Pack).

**Comment by johnsoncodehk** [comment]
Please provide some informations:

- VSCode info from `Help: About` command
- volar version
- Can the problem reproduce in https://github.com/johnsoncodehk/volar-starter?
   - if no, please provide repro case.

**Comment by shadowdreamer** [comment]
@johnsoncodehk 


## VSCode info:
![image](https://user-images.githubusercontent.com/4878501/121619985-191d6d80-ca9c-11eb-859e-ad69e67e63ee.png)

## volar version : 0.25.21

can't reproduce in volar-starter，i tired install some dependencies.

- install `pug` ,cpu normal
- install `naive-ui` and import, cpu normal
- install `tailwindcss@latest postcss@latest autoprefixer@latest sass` and import css , vscode keeps take about 10% of cpu usage when i do nothing. and then add more vue files to repo the cpu usage keeps increase.
- disable volar cpu usage goes to 0% when do nothing in vscode.

not very sure is those css dependencies caused the problem.  here is the repo: https://github.com/shadowdreamer/volar-starter-tester

thanks

**Comment by johnsoncodehk** [comment]
Sorry I can’t reproduce the problem even I repeat your steps.

If you can provide profiling record I will check this problem again.
https://github.com/johnsoncodehk/volar/blob/master/.github/STEP_TO_PROFILING.md

**Comment by cenglegelei** [comment]
I have same problem, and I speculate it caused by @vicons.

**Comment by lwp001** [comment]
volar 0.27.4   
vscode  版本: 1.60.0-insider
提交: 89bbd372f459ce72e9c0b60eb3b26b924f64f62d
日期: 2021-08-20T17:51:50.560Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**cpu memory is very high;**

**Comment by aalexgabi** [comment]
I also experience 50% CPU usage when Volar is enabled. To reproduce it I simply type continuously in a .vue file while 10 other .vue files are open and task manager is also open. Then I go to process details for the vs code child process that uses most CPU and I find volar and eslint both using about 15%.

![image](https://user-images.githubusercontent.com/600821/149919198-3636922f-9037-4168-ad20-4de1e7e76623.png)
![image](https://user-images.githubusercontent.com/600821/149919491-15b00c6e-47bb-4be3-9074-21417cc9fcdc.png)
