### ISSUE TITLE
Publish Volar to Open VSX extension gallery

### ISSUE THREAD

**Issue by micheartin** [johnsoncodehk/volar#257]
Hi, thank you for your incredibly-fast Vue extension.

I use [Codium](https://github.com/VSCodium/vscodium) as an open source alternative to Visual Source Code (that is [not open source](https://opensource.stackexchange.com/q/4288) and sends telemetry (by default) without explicit user consent, which is [not compliant](https://gdpr.eu/gdpr-consent-requirements/) with European data protection laws).

Codium is [not allowed](https://github.com/microsoft/vscode/issues/31168) to install extensions from the VS Code Marketplace. Hopefully, Codium uses a [community driven](https://ecdtools.eclipse.org/), [open source](https://github.com/eclipse/openvsx) extension gallery: Open VSX ([open-vsx.org](https://open-vsx.org/)).

Open VSX already distributes 1151 VSCode extensions:
* https://open-vsx.org/extension/antfu/vite
* https://open-vsx.org/extension/octref/vetur
* …

To publish Volar to Open VSX, please follow this steps:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by johnsoncodehk** [comment]
Thanks for your suggestion, but sorry I don't have enough energy to maintain more releases.

If anyone needs it, you can publish it yourself.

**Comment by johnsoncodehk** [comment]
See #550.
