### ISSUE TITLE
Doesn't have some types inside .vue files

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#258]
I am using Vite with my project, which resolves `.png` files as [strings](https://vitejs.dev/guide/assets.html). 

Inside typescript file I have no errors, but `.vue` file gives me `"Cannot find module 'assets/logo.png' or its corresponding type declarations.ts(2307)"`

Also `import.met.env.PROD` gives the same error. I think it doesn't use `vite/client` from `types` inside `tsconfig.json`. Also mite be relevant that I have my `tsconfig` not inside root folder, but in `<root>/_spa`.

**Comment by johnsoncodehk** [comment]
Thanks for report, but sorry I not fully understand the problem. Could you make a repro case by https://github.com/johnsoncodehk/volar-starter?

**Comment by sheremet-va** [comment]
Using this starter, after `npm install`, this code gives me error:

```
import App from './App.vue';
// Cannot find module './App.vue' or its corresponding type declarations.ts(2307)
```

(And I haven't done anything yet)

Repro link: https://github.com/sheremet-va/volar-starter

I have basically put everything inside `_spa` folder and modified `App.vue`. You can see that I have types on `isProd, components` inside `src/App.vue`, but inside `_spa/src/App.vue` types are not inferred.

**Comment by johnsoncodehk** [comment]
It works for me...

<img width="781" alt="螢幕截圖 2021-06-11 下午10 46 49" src="https://user-images.githubusercontent.com/16279759/121705222-03915d80-cb07-11eb-89dd-76466d503765.png">

**Comment by sheremet-va** [comment]
Works for me too on my home machine. Will try again on my work machine, maybe I had an outdated extension or some kind of broken vscode config.

**Comment by sheremet-va** [comment]
Closing the issue for now!

**Comment by alperencaliskan** [comment]
This happens when vue project is in a subfolder of your root workspace. Vetur also had suffered from this problem.

**Comment by d8vjork** [comment]
@alperencaliskan And how to fix that? I'm working on a Laravel based project but I could imagine everyone on a backend + frontend project will suffer this issue...

I got this inside a .ts file, I tried million things but none of them works, and yes, I've enabled the TS plugin option of Volar (which says the support of .vue files):

![image](https://user-images.githubusercontent.com/2331052/133408180-06fe4b6e-2ef3-42f1-b9af-9215e14c1025.png)
