### ISSUE TITLE
Show full Typescript errors

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#259]
This extension is awesome but I have one big problem with it: it only displays the first message of TS errors.

TS type system is hugely complex and it's sometimes quite hard to determine why two types are not compatible with each other.
Here's one example of Volar reporting a TS "incompatible types" error:
![image](https://user-images.githubusercontent.com/3832820/121579012-978df700-ca2b-11eb-983c-1927ea52ea73.png)

There's no more information in the "Problems" panel:
![image](https://user-images.githubusercontent.com/3832820/121579099-ae344e00-ca2b-11eb-90be-405fa61803dc.png)

In regular .ts files, those errors would open into a deep nested tree of increasingly specific errors that explain why the two top level types are incompatible.

Those messages are horrible to read, but they are key to figuring out what goes on and being able to fix the code.

**Comment by jods4** [comment]
Thanks, that will be very helpful!

**Comment by johnsoncodehk** [comment]
Thanks for your report. :)
