### ISSUE TITLE
Volar doesn't unwrap `ComputedRef` types in view?

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#260]
In a regular, non-setup, Vue component, I have the following type error:
![image](https://user-images.githubusercontent.com/3832820/121580820-77f7ce00-ca2d-11eb-803e-aede36a4ecaa.png)

For a top-level property of my state, it says
```
`ComputedRef<X | undefined> | undefined is not assignable to X | undefined
```

But top-level properties are auto-unref'ed by Vue, so `ComputedRef<X | undefined>` is actually just `X | undefined` in template and so the whole thing is clearly the same and assignable.

**Comment by johnsoncodehk** [comment]
Where's `state` define from?

**Comment by jods4** [comment]
on the state object returned by `setup`.

```js
export default {
  setup() {
    let state = computed(() => 13);
    return { state }
  }
}
```

**Comment by johnsoncodehk** [comment]
It should be working, can you try to delete node_modules, or try reproduce in https://github.com/johnsoncodehk/volar-starter?

**Comment by jods4** [comment]
@johnsoncodehk sorry for being silent a few days, I have a lot of work atm and not much time and energy left for OSS.

I built a repro for you, and found what the problem actually is:
https://github.com/jods4/volar-starter/tree/issue-260

In my case you see that `state` is an union type including `ComputedRef`, specifically `ComputedRef<T> | undefined`.
Being an union seems to be what prevents the unwrapping to happen.
`ComputedRef<T> | undefined` should become `T | undefined` in template but it stays the same instead.

Observing @ananni13 case, it seems he doesn't have an union type so it might be a different issue.

**Comment by johnsoncodehk** [comment]
@jods4 `ComputedRef` unwrap by `defineComponent`, please redirect the issue to vue-next.

**Comment by jods4** [comment]
@johnsoncodehk FYI: https://github.com/vuejs/vue-next/issues/3990
