### ISSUE TITLE
Dynamic slot name do not consume variable

### ISSUE THREAD

**Issue by zhenzhenChange** [johnsoncodehk/volar#263]
[![2WM8PI.png](https://z3.ax1x.com/2021/06/11/2WM8PI.png)](https://imgtu.com/i/2WM8PI)

**Comment by zhenzhenChange** [comment]
Ow, yes, similarly there is this

[![2WWqeK.png](https://z3.ax1x.com/2021/06/11/2WWqeK.png)](https://imgtu.com/i/2WWqeK)

**Comment by johnsoncodehk** [comment]
> Ow, yes, similarly there is this
> 
> [![2WWqeK.png](https://camo.githubusercontent.com/f5742007d279fb15454b55b3dcf5738007d47e7c67716eb4144d5a303f26266f/68747470733a2f2f7a332e617831782e636f6d2f323032312f30362f31312f32575771654b2e706e67)](https://imgtu.com/i/2WWqeK)

This is new feature request for css variable injection support, please open a new issue to track.
