### ISSUE TITLE
command 'volar.action.toggleTsPlugin' not found

### ISSUE THREAD

**Issue by JounQin** [johnsoncodehk/volar#264]
命令"Volar: Switch TS Plugin on / off"导致错误 (command 'volar.action.toggleTsPlugin' not found)

![image](https://user-images.githubusercontent.com/8336744/121634831-d6698e80-cab7-11eb-8a98-dc79e77ba39a.png)

https://github.com/JounQin/test/tree/vite

src/App.vue

VSCode info:

```log
版本: 1.57.0
提交: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
日期: 2021-06-09T17:22:31.215Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 21.0.0
```

**Comment by JounQin** [comment]
It seems somehow marked as JavaScript file automatically, does this plugin register `.vue` files as Vue?

I fix this issue by adding `"*.vue": "vue"` into `files.associations` setting, but if I remove it, it will continue to error.

So don't know if it is a bug of this plugin or not.

**Comment by johnsoncodehk** [comment]
> It seems somehow marked as JavaScript file automatically, does this plugin register `.vue` files as Vue?

Thanks to shared resolve, `vue` should be default language for `"*.vue"` in VSCode, maybe you have change the default setting, or some other extension modify it. But yes this is not volar problem.
