### ISSUE TITLE
`key` results in type error when used on functional component

### ISSUE THREAD

**Issue by yyx990803** [johnsoncodehk/volar#268]
Example:

```vue
<script setup lang="ts">
function Foo(props: { x?: number }) {
  return 'hi'
}
</script>

<template>
  <Foo :key="1" />
</template>
```

**Comment by johnsoncodehk** [comment]
It is designed to give full control by user. Currently you need define props type as `{ [key: string]: unknown, x?: number }`, see  https://github.com/johnsoncodehk/volar/issues/227.

**Comment by johnsoncodehk** [comment]
After some digging, I just found `IntrinsicAttributes` should be include to props type, will resolve it.
