### ISSUE TITLE
shared_1.getWordStart is not a function

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#271]
Got an error while typing very fast in a copypasted halved deleted file

![image](https://user-images.githubusercontent.com/16173870/122562870-34fcb280-d04c-11eb-8461-6247dac5bca8.png)

Sometimes appears while I type inside `style` tag with `scss` and `module`. I got this error and I guess it got cached and now vscode shows it on every character type inside this file

(**Important!** I am running it as `Launch` script while profiling)

**Comment by sheremet-va** [comment]
Also got this error
![image](https://user-images.githubusercontent.com/16173870/122580314-7e55fd80-d05e-11eb-8b7e-00927b3e3900.png)

**Comment by johnsoncodehk** [comment]
I cannot start the repair work because I cannot reproduce it.
Is there any way to reproduce the problem more effectively?
