### ISSUE TITLE
Typing error when rendering a VNode using <component>

### ISSUE THREAD

**Issue by smarlhens** [johnsoncodehk/volar#2720]
Hi there 👋🏻 ,

I hope you are fine, thanks for your amazing job.

I am getting this issue when I use [\<component\>](https://vuejs.org/api/built-in-special-elements.html#component) from vue with a [VNode](https://vuejs.org/api/render-function.html#h): 

```vue
<template>
  <div>
    <component :is="component1"></component>
  </div>
</template>

<script setup lang="ts">
import type { VNode } from 'vue';
import { h } from 'vue';

const component1: VNode = h('span', 'Foobar');
</script>
```
![image](https://user-images.githubusercontent.com/11817371/234625296-8e9f6d0e-0019-4fef-b511-dd42add55d6c.png)

```
Binaries:
  Node: 16.14.2
  npm: 7.17.0 
npmPackages:
  typescript: 5.0.4
  vue: 3.3.0-beta.2
  vue-tsc: 1.5.4
```

Repro repo: https://stackblitz.com/edit/vitejs-vite-i2cuad

Wish you a great day 🌞 
Stay safe

**Comment by LQ6666666** [comment]
+1
![image](https://user-images.githubusercontent.com/64238945/234731469-59492a36-a744-434f-baf0-d5d01958c13f.png)
![image](https://user-images.githubusercontent.com/64238945/234731451-5c03d4ad-90cb-45ce-aad6-46b91fb66833.png)
