### ISSUE TITLE
Vue 2 support ?

### ISSUE THREAD

**Issue by IndexXuan** [johnsoncodehk/volar#273]
Thanks for this great plugin/lsp.
the document said when you install `@vue/runtime-dom`, volar/vue-tsc support Vue 2, is it really that smooth ?

I create a Vue 2 app with @vue/composition-api by vue-cli, and the first step is v-model handler.
Vue 2 v-model means props.value + emit input & Vue 3 is modelValue + emit onUpdate:modelValue, how volar handle this different ?

repro link: https://github.com/IndexXuan/vue2-volar-test-app/blob/master/src/views/Home.vue#L9
when I have a v-input component
```ts
  props: {
    value: {
      type:  String,
      required: true,
    }
  }
```

when I use this v-input on parent component
```vue
<v-input v-model="xxx" />
```

It will ends up with error.

![image](https://user-images.githubusercontent.com/6322673/122680336-33d0ae80-d221-11eb-926b-2d766a63a5c5.png)
![image](https://user-images.githubusercontent.com/6322673/122680346-3a5f2600-d221-11eb-8d4e-1adcedcfe186.png)

Also there are some template key warning(Vue 2 should place key at child), not big problem.

Thanks for you help.

**Comment by IndexXuan** [comment]
https://github.com/johnsoncodehk/volar/blob/263dd59fb71d54dc69c50ff8846350b6752648e7/packages/vscode-vue-languageservice/src/generators/template.ts#L498

**Comment by johnsoncodehk** [comment]
> the document said when you install `@vue/runtime-dom`, volar/vue-tsc support Vue 2, is it really that smooth ?

No it's not, `@vue/runtime-dom` only make Vue 3 type-checking working in Vue 2 project, full backward compatibility to Vue 2 is not the purpose, Vetur already do it.

On the other hand, you can use Vue 3 template compiler in Vue 2.

https://blog.ninja-squad.com/2021/06/07/what-is-new-vue-3.1/

**Comment by IndexXuan** [comment]
@johnsoncodehk I know Vue 3.1 compat build, but how ?
There are some scale-project which I cannot migrate to Vue 3.

Should I use vetur instead of volar ? But vetur not support slot type-checker. so sad.

**Comment by johnsoncodehk** [comment]
> Should I use vetur instead of volar?

You need to choose. If you need type support based entirely on Vue 2, please use Vetur.

**Comment by IndexXuan** [comment]
I think push vetur support slot type-checker and official globalComponent typings is better. 

Thanks.

**Comment by Djaler** [comment]
> On the other hand, you can use Vue 3 template compiler in Vue 2.

It cannot be used in many apps, because `Dependencies that rely on Vue 2 internal APIs or undocumented behavior. The most common case is usage of private properties on VNodes. If your project relies on component libraries like Vuetify, Quasar or ElementUI, it is best to wait for their Vue 3 compatible versions.` https://github.com/vuejs/vue-next/tree/master/packages/vue-compat#known-limitations

Maybe you can add some workaround for this case with `v-model` for Vue 2?

**Comment by johnsoncodehk** [comment]
@Djaler Sorry, due to maintenance costs, it will not be supported now. But technically Vue 2 template compiler can be support by Plugin API.

https://github.com/johnsoncodehk/volar/issues/185

**Comment by victorgarciaesgi** [comment]
I can confirm that Volar works on a Vue 2 project with `@vue/composition-api`, but it is way slower than Vetur. 
It's a gain & cost between great type inference ans speed

**Comment by johnsoncodehk** [comment]
> but it is way slower than Vetur

@victorgarciaesgi Have you enabled `vetur.experimental.templateInterpolationService` for Vetur?

**Comment by victorgarciaesgi** [comment]
@johnsoncodehk No Vetur is disabled in the workspace, the settings should no apply I think?

**Comment by johnsoncodehk** [comment]
@victorgarciaesgi If you want TS support in `<script>` and `<template>` with Vetur, you need to enabled `vetur.experimental.templateInterpolationService`.

Compared to Vetur + `vetur.experimental.templateInterpolationService`, Volar should be much faster.

Otherwise, Volar may have performance problems on your machine, and I need profile record for further inspection.

**Comment by victorgarciaesgi** [comment]
@johnsoncodehk Yeah I know I used Vetur in all my previous projects with `templateInterpolationService`, even with 200+ components, and for a new project i'm migrating from Vetur to Volar+composition-api (Vue 2).

Right now I have ~50 components and Volar is really slow compared to Vetur.

![Kapture 2021-07-09 at 22 08 36](https://user-images.githubusercontent.com/15092120/125130972-42183900-e102-11eb-87f6-67730339c292.gif)

I'm on a Macbook pro 2020, Big Sur, 2,3 GHz Quad-Core Intel Core i7 and 16go Ram

**Comment by johnsoncodehk** [comment]
@victorgarciaesgi It should be a perf bug, please open a new issue and try to provide repro case or profiling record.

https://github.com/johnsoncodehk/volar/blob/master/.github/STEP_TO_PROFILING.md

**Comment by victorgarciaesgi** [comment]
@johnsoncodehk I'm creating the Profiling record but the debug tools throw me an error 

> Activating extension 'johnsoncodehk.volar' failed: Cannot find module '/Users/victorgarcia/Desktop/Projects/volar/node_modules/@volar/vscode-client/out/extension' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.

**Comment by victorgarciaesgi** [comment]
@johnsoncodehk Added you in a private project `volar-repro-project` if you want to test it

**Comment by johnsoncodehk** [comment]
@victorgarciaesgi I'm checking the problem, thank you.

**Comment by johnsoncodehk** [comment]
Due to the good progress recently, I consider to support vue 2 template in some way.

**Comment by johnsoncodehk** [comment]
Please track #346
