### ISSUE TITLE
Components in the template are not recognized with JSX code

### ISSUE THREAD

**Issue by joker77877** [johnsoncodehk/volar#275]
![image](https://user-images.githubusercontent.com/62642184/122726828-f6176880-d2a8-11eb-8f8c-688354018ab0.png)

git: https://github.com/joker77877/vue-vite-volar

**Comment by jods4** [comment]
I don't think this is specific to TSX/JSX, I observe the same in my project (plain TS). 
I assumed this was because local components in non-`script setup` style were unsupported?

**Comment by johnsoncodehk** [comment]
> I don't think this is specific to TSX/JSX, I observe the same in my project (plain TS).
> I assumed this was because local components in non-`script setup` style were unsupported?

You may need to config `"editor.semanticHighlighting.enabled": true` in vscode.

**Comment by joker77877** [comment]
Please release the latest version as soon as possible, thank you.

**Comment by johnsoncodehk** [comment]
@joker77877 I'm still fixing #94 for next version, will check a patch release if possible.

You can also run volar master branch as debug mode for now.

https://github.com/johnsoncodehk/volar/blob/master/.github/STEP_TO_PROFILING.md#run-volar-on-debug-mode
