### ISSUE TITLE
script setup + const enum = 💔

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#277]
Even when everything is correct and runs properly, Volar complains about imported const enums.
![image](https://user-images.githubusercontent.com/3832820/122800475-456a9280-d2c3-11eb-92e1-f3c76ad30141.png)

This problem can be worked around a little by using `import type`, but depending on your code you get another error then:
![image](https://user-images.githubusercontent.com/3832820/122800635-764ac780-d2c3-11eb-9c0d-b4d293f58a3f.png)

I know the default Vite setup can't properly compile const enums, but we use a custom build with regular TSC that compiles const enums efficiently. This is important for us because we have tons of enums generated from server-side code and it really adds up.

**Comment by vuong-cuong-phoenix** [comment]
This is because `Vite` uses `esbuild` under the hood to perform transpilation. More information at: [Vite TypeScript support](https://vitejs.dev/guide/features.html#typescript) & [TSConfig `isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules).

**Comment by johnsoncodehk** [comment]
Thanks for the report. But we can't change this behavior, otherwise it will be a bug for general users, because users will get runtime error in this case.

You can use import type + `@ts-ignore` to bypass the problem.

```ts
import type { X } from "./enum";

const map = {
  // @ts-ignore
  [X.A]: 1
}
```

**Comment by jods4** [comment]
@johnsoncodehk could you please explain what runtime error general (who?) users would get? I am not sure I get it.

**Comment by jods4** [comment]
I want to add that I'm having similar error messages when importing types.

These can be work-around by using `import type` explicitly but it's inconvenient to have to split imports in two, that creates lots of imports quickly.

```ts
// Error: 'Type' only refers to a type, but is being used as a value here.ts(2693)
import { Type, Value } from "x";

// Work-around: double imports
import { Value } from "x";
import type { Type } from "x";
```

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/209#issuecomment-848448876.

**Comment by jods4** [comment]
I went down the linked issues to https://github.com/vuejs/vue-next/issues/3183 which seems to be the open issue for this.
