### ISSUE TITLE
When implementing custom `v-model` using `defineProps` & `defineEmit`, `$event` param of the emitter has union type with  `undefined`

### ISSUE THREAD

**Issue by vuong-cuong-phoenix** [johnsoncodehk/volar#278]
## Reproduction

Let's assume we have 2 following components:

```vue
<!-- Child.vue -->
<template>
  <button type="button" @click="emit('update:modalValue', modelValue + '-')">
    {{ modelValue }}
  </button>
</template>

<script setup lang="ts">
  import { defineProps, defineEmit } from 'vue';

  const props = defineProps({
    modelValue: {
      type: String,
      default: '',
    },
  });

  const emit = defineEmit({
    'update:modalValue': (value: string) => true,
  });
</script>
```

```vue
<!-- Parent.vue -->
<template>
  <div>
    <Child :model-value="childValue" @update:modelValue="childValue = $event" />
  </div>
</template>

<script setup lang="ts">
  import { ref } from 'vue';
  import Child from './Child.vue';

  const childValue = ref('');
</script>
```

## What is actually happening?

Both **Volar** and **vue-tsc** throw this error at the event listener:

```
src/components/Parent.vue:4:58 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

4     <Child :model-value="childValue" @update:modelValue="childValue = $event" />
```

If we define `modelValue` prop with `required: true` or replace `update:*` pattern of the emitter (e.g: use `updateModalValue` instead of `update:modelValue`) then the error will disappear.

## Expected result

No error should be thrown.

**Comment by johnsoncodehk** [comment]
Event name is inconsistent. `model` ~ `modal`

**Comment by vuong-cuong-phoenix** [comment]
> Event name is inconsistent. `model` ~ `modal

Sorry, it must be a typo mistake when I typed the code, but the issue was really there even with correct typing.
Great news is that it seems like recent versions of **Volar** have just fixed it! **vue-tsc** still throws the error though (you can check it yourself), but I assume it will be updated soon. :+1:

Again, very good work! I love this extension so much, no extension out there could perform reliable, fast, efficient like this one and it's just getting better day by day :1st_place_medal:

**Comment by johnsoncodehk** [comment]
Thank you. :) For vue-tsc, you need to delete yarn.lock / package-lock.json to update volar in node_modules.
