### ISSUE TITLE
Register ComponentPublicInstance type as GlobalComponent

### ISSUE THREAD

**Issue by pipe01** [johnsoncodehk/volar#279]
I'm using the [vue-fontawesome](https://github.com/FortAwesome/vue-fontawesome) library, which exports a `FontAwesomeIcon` component whose type is defined as `declare const FontAwesomeIcon: ComponentPublicInstance<FontAwesomeIconProps>`. When I try to register it as a global component by doing:

```ts
declare module 'vue' {
    export interface GlobalComponents {
        icon: typeof import('@fortawesome/vue-fontawesome')['FontAwesomeIcon']
    }
}

export {}
```

I get the following error on all references to the component:

![imagen](https://user-images.githubusercontent.com/3885705/123103724-98188b80-d436-11eb-900e-dc531f8eafda.png)

Is there any way to register the `ComponentPublicInstance` component globally?

**Comment by johnsoncodehk** [comment]
Try `icon: new () => typeof import('@fortawesome/vue-fontawesome')['FontAwesomeIcon']`.

**Comment by pipe01** [comment]
It complained about parameters so I had to change it to `icon: (_) => typeof...` and it works, thank you!
