### ISSUE TITLE
Re-exported value in <script setup> isn't recognized by Volar but it is by Vue

### ISSUE THREAD

**Issue by pipe01** [johnsoncodehk/volar#282]
When I import a value exported by a different module like this:

```html
<template>
<div>{{foo}}</div>
</template>

<script lang="ts" setup>
export { foo } from "./test"
</script>
```

test.ts:
```ts
export const foo = 42;
```

`foo` is recognized at runtime by Vue, but Volar reports a `Cannot find name 'foo'` error. A workaround is to add this below the `export ...` line:

```ts
import { foo } from "./test"
```

But it means that I have to duplicate all values I want to import.

**Comment by johnsoncodehk** [comment]
This is expected behavior. `foo` should not recognized at runtime. Please forward this issue to vue-next.
