### ISSUE TITLE
Unable to load typescript version of workspace

### ISSUE THREAD

**Issue by joker77877** [johnsoncodehk/volar#283]
![image](https://user-images.githubusercontent.com/62642184/123735718-4d818e00-d8d2-11eb-98fd-c26fee0b89b2.png)
![image](https://user-images.githubusercontent.com/62642184/123735796-7144d400-d8d2-11eb-9a65-c1e0d220fef1.png)

**Comment by johnsoncodehk** [comment]
Dose tsserver.js exist ini this path?

**Comment by joker77877** [comment]
![image](https://user-images.githubusercontent.com/62642184/123749453-07372980-d8e8-11eb-86ac-c28ed70f5191.png)
Yes, it exists.

**Comment by johnsoncodehk** [comment]
I am not familiar with yarn2, and not sure how it working, please try yarn1 / npm.

**Comment by joker77877** [comment]
I don't think the problem is yarn2 or NPM, because the official typescript plug-in can read yarn2 typescript package.
![image](https://user-images.githubusercontent.com/62642184/123897935-eb3e9100-d996-11eb-891c-497f28404f4e.png)
![image](https://user-images.githubusercontent.com/62642184/123897945-eed21800-d996-11eb-8921-909fe5fe9bc6.png)

Some people still use yarn2, so we should solve why it can't read the TS package of yarn2.

**Comment by johnsoncodehk** [comment]
Please provide a minimum reproduce.

**Comment by johnsoncodehk** [comment]
Related: https://github.com/johnsoncodehk/vue-tsc/issues/45

**Comment by joker77877** [comment]
I'm sorry, but the cause of the error is that the TS version in the SDK is inconsistent with the TS version in the devDependencies.
