### ISSUE TITLE
Typecheck regression in 0.25.23 for unknown properties

### ISSUE THREAD

**Issue by innocenzi** [johnsoncodehk/volar#284]
I'm not sure if this was wanted, but "unknown" props now give an error. This `icon` component is not known by Volar (it's dynamically included via `vite-plugin-components` without TypeScript support enabled).

# Before (0.25.22)

![](https://i.imgur.com/Hvf4X3i.png)

# After (0.25.23)

![](https://i.imgur.com/FI2M4Uq.png)

![](https://i.imgur.com/rbjiWUX.png)

**Comment by innocenzi** [comment]
I'm not sure if it's related, but I have an error in the popover component's `v-slot`: 

![](https://i.imgur.com/vQGnW1G.png)

This component comes from Headless UI: 
- <https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/popover/popover.ts>
- <https://headlessui.dev/vue/popover>

I don't think I had this issue before, but it seems that 0.25.22 still triggers the error for the popover. 

The `:open` error is present in 0.25.23 and disappears in 0.25.22. It's the exact same error message as the `<icon name="...">` one above.

**Comment by qiaozhu** [comment]
me too, I'm back 0.25.22 it's ok.

**Comment by johnsoncodehk** [comment]
> I'm not sure if it's related, but I have an error in the popover component's `v-slot`:
> 
> ![](https://camo.githubusercontent.com/c8a86568d3de68231965f27d770d098fdf02f33c195e96920586416f82bc2c6d/68747470733a2f2f692e696d6775722e636f6d2f7651476e5731472e706e67)
> 
> This component comes from Headless UI:
> 
> * https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/popover/popover.ts
> * https://headlessui.dev/vue/popover
> 
> I don't think I had this issue before, but it seems that 0.25.22 still triggers the error for the popover.
> 
> **EDIT** - After trying every version, the issue is introduced in 0.25.11 and is not present in 0.25.10.

You need to define `__VLS_slots` for third party libraries for now. See https://github.com/johnsoncodehk/volar#using.

**Comment by innocenzi** [comment]
Thanks! The solution works properly. Would Volar discover this if I PR it to HeadlessUI?

**Comment by johnsoncodehk** [comment]
@innocenzi yes volar will discover slots type if you define `__VLS_slots` to library. But I don't recommend you do this, because `__VLS_slots` is not official vue interface, and it will be replaced in the future.

**Comment by innocenzi** [comment]
Alright, I won't PR it then. Thanks a lot for the info and your work. 👍
