### ISSUE TITLE
Provide a way to infer emits types in Vue 2 projects

### ISSUE THREAD

**Issue by victorgarciaesgi** [johnsoncodehk/volar#286]
Hi!

I'm maintaining a vue chart.js library [vue-chart-3](https://github.com/victorgarciaesgi/vue-chart-3) and currently have problems with events types in Vue 2.

The library is using Vue Demi, and after traversing types from of `defineComponent` `@vue/composition-api`, there is no generics for infering the `emits` property, resulting in this:

```vue
<template>
   <Doughnut
      ref="doughnutRef"
      :data="testData"
      :options="options"
      @chart:render="handleChartRender"
    />
</template>
```

![image](https://user-images.githubusercontent.com/15092120/124129342-fd472f00-da7d-11eb-8def-c28cc7b98692.png)

![image](https://user-images.githubusercontent.com/15092120/124129914-88282980-da7e-11eb-84af-ab110bf69661.png)

Here is the portion of code coming from the `vue-chart-3` component.

```ts
export const defineChartComponent = <TType extends ChartType = ChartType>(
  chartId: string,
  chartType: TType
) => {
  const propsDefs = {
    chartId: { default: chartId, type: String },
    width: { default: 400, type: Number },
    height: { default: 400, type: Number },
    cssClasses: { type: String, default: '' },
    styles: { type: Object as PropType<StyleValue> },
    plugins: { type: Array as PropType<Plugin[]>, default: () => [] },
    data: { type: Object as PropType<ChartData<TType>>, required: true },
    options: { type: Object as PropType<ChartOptions<TType>> },
  } as const;

  const componentName = pascalCase(chartType);

  return defineComponent({
    name: componentName,
    props: propsDefs,
    emits: {
      'labels:update': () => true,
      'chart:update': (chartInstance: Chart<TType>) => true,
      'chart:destroy': (chartInstance: Chart<TType>) => true,
      'chart:render': (chartInstance: Chart<TType>) => true,
    },
    setup(props, { emit }) {
     //
    },
    render() {
      //
    },
  });
};

export const Doughnut = defineChartComponent('doughnut-chart', 'doughnut');
```

**Comment by heemoe** [comment]
I got same issues on Vue 3 project, fixed this infer problem by rollback to 0.25.24.

**Comment by johnsoncodehk** [comment]
@victorgarciaesgi you can't define events in props option to support typing for vue2.

```ts
  const propsDefs = {
    // ...
    'onLabels:update': Function as PropType<() => void>,
    'onChart:update': Function as PropType<(chartInstance: Chart<TType>) => void>,
    'onChart:destroy': Function as PropType<(chartInstance: Chart<TType>) => void>,
    'onChart:render': Function as PropType<(chartInstance: Chart<TType>) => void>,
  } as const;
```

@heemoe please provide a minimum reproduce.

**Comment by victorgarciaesgi** [comment]
@johnsoncodehk Ah yes thanks for the tip! 
But I wondered why unrecongnized events are infered by default with `($event: undefined)` and not `($event: any)` or ($event:unknown)

**Comment by johnsoncodehk** [comment]
`($event: undefined)` is define for no args event to fix https://github.com/johnsoncodehk/volar/issues/270.

`($event: undefined)` effective for unrecongnized events is unexpected, I need a vue3 minimum reproduce to check the problem.

**Comment by johnsoncodehk** [comment]
I just found the problem... if event arg is optional like `(str?: string) => void`, it will be infer to `($event?: undefined) => void`.

**Comment by victorgarciaesgi** [comment]
I have a repro here if you want (Vue 3) https://codesandbox.io/s/demo-vue-chart-3-ugynm?file=/src/App.vue

**Comment by johnsoncodehk** [comment]
Related: #287
