### ISSUE TITLE
$event regression in v0.25.25

### ISSUE THREAD

**Issue by cexbrayat** [johnsoncodehk/volar#287]
It looks like 8628f3f60161e2408141e83b3ee9209c054d26a4 introduced a regression in our projects.

We're using vee-validate, which offers a `Form` component, with a `submit` event. You can listen to this submit event to call a method of the component with the submitted values.

With volar v0.25.25, using a simple component like:
```vue
<template>
  <Form @submit="register($event)">
    <Field name="login"></Field>
  </Form>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Field, Form } from 'vee-validate';

export default defineComponent({
  name: 'App',
  components: {
    Form,
    Field
  },
  setup() {
    return {
      register(user: { login: string }) {
        console.log(user)
      }
    }
  }
});
</script>
```

Makes `vue-tsc` throw:
```
src/App.vue:2:27 - error TS2345: Argument of type 'undefined' is not assignable to parameter of type '{ login: string; }'.

2   <Form @submit="register($event)">
```

I put together a small repro here: https://github.com/cexbrayat/vue-v313/pull/1

**Comment by johnsoncodehk** [comment]
Thanks for the repro case! Fixed in https://github.com/johnsoncodehk/volar/commit/b0d6afc84fb3b620728d67869847c95e7eabd76b.

**Comment by cexbrayat** [comment]
@johnsoncodehk Awesome, thanks! I manually patched my `vscode-vue-languageservice` package with your fix and I confirm it fixes the issue in our project 👌
