### ISSUE TITLE
textDocument/hover error if JSDoc param has {@link}

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#289]
I noticed an error on hovering `onBeforeRouteEnter` with `vue-router` - it gives me this error:

```
Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property '0' of undefined
  Code: -32603 
```

The error is thrown only inside vue files, it works inside typescript files.

I noticed that if I remove the whole `@param` section, then the error goes away.

**Comment by johnsoncodehk** [comment]
<img width="913" alt="螢幕截圖 2021-07-04 上午2 01 09" src="https://user-images.githubusercontent.com/16279759/124363084-bae34500-dc6b-11eb-9664-6776d1f0e989.png">

I can't repro, please provide repro code or repo.

**Comment by sheremet-va** [comment]
You are showing object property. I am talking about setup functions like onBeforeRouteLeave, that need to be imported like `import { onBeforeRouteLeave } from "vue-router"`

**Comment by sheremet-va** [comment]
Also i import them inside script setup if that might help

**Comment by bsssshhhhhhh** [comment]
I think I have a related error:

```
[Error - 8:29:49 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: tag.text.map is not a function
  Code: -32603 
```

from volar/packages/vscode-typescript-languageservice/src/services/hover.ts - this issue is mentioned next to it

**Comment by johnsoncodehk** [comment]
> I think I have a related error:
> 
> ```
> [Error - 8:29:49 AM] Request textDocument/hover failed.
>   Message: Request textDocument/hover failed with message: tag.text.map is not a function
>   Code: -32603 
> ```
> 
> from volar/packages/vscode-typescript-languageservice/src/services/hover.ts - this issue is mentioned next to it

Please provide repro code or repo.

**Comment by qiqigou** [comment]
![image](https://user-images.githubusercontent.com/48587985/143001915-ac29e129-c044-47fd-b7eb-56442e68fe3f.png)
from `https://github.com/qiqigou/vue3-sample/blob/master/src/components/HelloWorld.vue`
