### ISSUE TITLE
Stylus language support

### ISSUE THREAD

**Issue by odex21** [johnsoncodehk/volar#29]
I know this doesn't seem like an easy one, but maybe we could reference Vetur?

**Comment by johnsoncodehk** [comment]
thanks for the suggest :) but same to https://github.com/johnsoncodehk/volar/issues/20.

this is not hard, just too much work for me. Volar have additional `<style module>` and `<style scoped>` services(I call this extra css services), so if I implement sass/stylus support in Volar, I need to do twice extra css services again for sass+stylus...

**"IF"** I have time, I will not implement it in Volar, I will implement it in https://github.com/microsoft/vscode-css-languageservice, everyone can benefit (Volar, Vetur, VSCode...etc), and I don't need to doing extra css services again.

**Comment by johnsoncodehk** [comment]
supported in 0.21.18.
