### ISSUE TITLE
Wrong type with new 'withDefaults' syntax

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#290]
Finalized script setup RFC added `withDefaults` syntax when defining `default` field for prop. But Volar gives the wrong types inside "template" tag. I made a reproduction inside `src/componets/HelloWorld.vue`:

Reproduction repo: https://github.com/sheremet-va/volar-type-bug

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk I see this was closed 12 days ago, but I still have the issue with v0.26.2.
> 
> This is my props:
> 
> ```ts
> const props = withDefaults(
>     defineProps<{
>       name: string;
>       editable?: boolean | string;
>       canCreate?: boolean | string;
>       canModify?: boolean | string;
>       canDelete?: boolean | string;
>       api: {
>         getAll(): Promise<any[]>;
>         get(id: any): Promise<any>;
>         save?(item: any): Promise<any>;
>         del?(id: any): Promise<void>;
>       };
>       rules?: Rules<any>;
>       columns: ColumnDefinition<any>[];
>     }>(),
>     {
>       editable: true,
>       canCreate: true,
>       canModify: true,
>       canDelete: true,
>     },
>   );
> ```
> 
> I get this error in template:
> `Argument of type 'string | boolean | undefined` is not assignable to parameter of type `string | boolean`.
> Given the `withDefaults` call, `undefined` should have been removed from `editable` and `canModify` props.
> ![image](https://user-images.githubusercontent.com/3832820/125968481-1035029c-95ab-425b-b1ef-c7b95e7c2176.png)
> 
> Although I wonder if the error is in Vue typing itself, because the `props` type returned from `withDefaults` doesn't look quite right to me:
> ![image](https://user-images.githubusercontent.com/3832820/125969251-039e3ab6-bfb9-4b2b-b80f-1af3f0e2db3a.png)

Fixed in https://github.com/johnsoncodehk/volar/commit/81794d6b9540fde2d7bbf4fd55a2a36e4e52551b.
