### ISSUE TITLE
May trigger stylelint in JSX style attribute

### ISSUE THREAD

**Issue by qmhc** [johnsoncodehk/volar#294]
When using JSX and set a style attribute, may trigger the stylelint check:

![image](https://user-images.githubusercontent.com/40221744/124856745-a8576b80-dfdd-11eb-81c2-9845e22b596f.png)

![image](https://user-images.githubusercontent.com/40221744/124856779-bad1a500-dfdd-11eb-9f3c-605ac005423c.png)

**Comment by johnsoncodehk** [comment]
I think this is alert is not from volar, it should be show even you disabled volar, please check your other extensions.

**Comment by qmhc** [comment]
@johnsoncodehk  my negligence, I will take more details test
