### ISSUE TITLE
Request completionItem/resolve failed.

### ISSUE THREAD

**Issue by ovensi** [johnsoncodehk/volar#299]
Message: Request completionItem/resolve failed with message: Could not find source file: '/xxxxxx/src/views/user/authentication/index.vue.__VLS_script.js'.

![image](https://user-images.githubusercontent.com/24306930/125256422-03b39180-e32f-11eb-95dc-15a3d5dfa450.png)

![image](https://user-images.githubusercontent.com/24306930/125256968-863c5100-e32f-11eb-9457-d73fa3eb4e6f.png)

When I directly type the component I want to import in the template node, Volar will report an error, but I successfully import it in the child node. Is this normal?
---
vscode version: v1.58.0
volar version: v0.25.28

**Comment by johnsoncodehk** [comment]
Currently SFC parsing broken by last unfinished root tag in `<template>`, we need wait for `@vue/compiler-sfc` improve error tolerance.
