### ISSUE TITLE
Volar gives type error on objects for style attribute

### ISSUE THREAD

**Issue by kadiryazici** [johnsoncodehk/volar#30]
```ts
const style = ref({
   'font-size': '25px',
   transform: 'scale(1.8)',
});
```
```vue
<a
         :style="style"
         :href="href"
         >to link</a
      >
```
When i try to bind a javascript object to style attribute it works but volar thinks not.

**Comment by johnsoncodehk** [comment]
When you define object type style, you can do this to match the types:

```
import { CSSProperties } from 'vue'
const style = ref<CSSProperties>({
   fontSize: '25px',
   transform: 'scale(1.8)',
});
```

The problem is CSSProperties has not 'font-size' property, only has 'fontSize', so this is a types define errors, you can report this problem to vue repo. :)
