### ISSUE TITLE
Incorrect handling of importing types in script-setup

### ISSUE THREAD

**Issue by roamiiing** [johnsoncodehk/volar#300]
App.vue:
```vue
<template>
  <div @click="count++">{{ count }}</div>
</template>

<script setup lang="ts">
import { ref, Ref } from 'vue';

const count: Ref<number> = ref(0);
</script>
```

I see that explicitly defining the `Ref<number>` type is not necessary, but this is just an example. VSCode shows an error in the `import` statement:

![Screenshot 2021-07-13 at 19 34 06](https://user-images.githubusercontent.com/31025389/125452326-9c59d13a-c974-41aa-9671-3e392a02f9c5.png)

Which is not actually an error because the imported type `Ref` is not being used as a value anywhere. This doesn't happen if we rewrite this code without using `<script setup>`:

```vue
<template>
  <div @click="count++">{{ count }}</div>
</template>

<script lang="ts">
import { defineComponent, ref, Ref } from 'vue';

export default defineComponent({
  setup() {
    const count: Ref<number> = ref(0);

    return {
      count,
    };
  },
});
</script>

```

**Comment by jods4** [comment]
This is a problem with the Vue compiler, the main issue about it is here:
https://github.com/vuejs/vue-next/issues/3183

Your code is correct, but the compiler exposes all imports (without knowing if they're a type or not, as there's not cross-file analysis going on here) to the template.
This puts `Ref`, a type, into a position where it can't be used, something like `return { Ref }` at the end of the setup function.

A consequence is that it's impossible to use const enums in script setup, see https://github.com/johnsoncodehk/volar/issues/277 as well.

**Comment by roamiiing** [comment]
Well now I see what is going on with that, but I am curious why then am I not getting a runtime error

**Comment by jods4** [comment]
Prob. because your code doesn't use that value symbol.
If the export ends up with an unused, `Ref` property set to `undefined`, nothing bad is gonna happen.

I also believe that in production build, `script setup` is compiled differently, with a closure. This way doesn't cause any type to leak at all, either.

**Comment by johnsoncodehk** [comment]
This is designed behavior to prevent runtime error.

<img width="935" alt="螢幕截圖 2021-07-14 下午3 45 42" src="https://user-images.githubusercontent.com/16279759/125583611-1fa842d4-9a43-41e2-ab8f-6e691a5e6c86.png">
