### ISSUE TITLE
[Question] Rename symbol in both script and template

### ISSUE THREAD

**Issue by perkrlsn** [johnsoncodehk/volar#301]
Hey @johnsoncodehk! First off,  awesome plugin 👍 

Now to my question. Any chance we can get the symbol renaming to propagate to the `template` as well instead of aliasing the property in the return.

Basically so that the `v-for` in the template turns into `thingie in list`.

![Jul-13-2021 17-18-23](https://user-images.githubusercontent.com/12989781/125479189-a6c4bf60-f8ed-461a-99d7-542cf1b4d290.gif)

**Comment by johnsoncodehk** [comment]
typescript support this behavior in *.ts with `"typescript.preferences.useAliasesForRenames": false` setting, volar will support this setting in future.

**Comment by johnsoncodehk** [comment]
Support this TS option in 0.26.3, but due to TS problem, currently not working properly.

TS reproduce:

```ts
// foo.ts

const component = defineComponent({
    setup() {
        const foo = 1 // <- try rename foo here
        return { foo }
    }
})
const instance = new component()
instance.foo // <- should change here but no effect
```
