### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by peterbud** [johnsoncodehk/volar#305]
@johnsoncodehk -  this is a great extension, thank you for your work!

I have recently experienced a strange behavior: when I hover over certain variables in a vue file, `volar` logs this error:
```
[Error - 2:34:05 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'positionAt' of undefined
  Code: -32603 
```

the script block is a typescript block:
```
<script lang="ts">
import { defineComponent } from 'vue'
import { useI18n } from 'vue-i18n'
...
</script>
```

when I hover over `defineComponent `I see the type definition, when I hover over `useI18n`, then I get the above mentioned error.

Any idea how to fix this?

**Comment by hello-hyh** [comment]
I get same issue, but my error message following:
```js
Message: Request textDocument/hover failed with message: Cannot read property 'replace' of undefined
  Code: -32603 
```
This extension is very awsome, thank your for your work

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce, please provide repro case.

<img width="983" alt="螢幕截圖 2021-07-17 上午4 22 45" src="https://user-images.githubusercontent.com/16279759/126004473-c04b61f9-9165-4d02-8164-d1b9aa1b8d2f.png">

**Comment by muttering-oldman** [comment]
I get the same error when hovering over `useI18n`.

![изображение](https://user-images.githubusercontent.com/22166486/126320078-a74d1b86-81e2-418a-a64b-052187a4aeeb.png)

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/f8e08e2699683f1561a1b86d3bce4065ffa17182.
