### ISSUE TITLE
Emits type checking on functional component

### ISSUE THREAD

**Issue by andylix** [johnsoncodehk/volar#306]
For a functional component like this:

```ts
type Emits = { 'clicked': (count: number) => void }

type Component = FunctionalComponent<{ count: number }, Emits>

const Counter: Component = function(props, context) {

  function onClick() {
    context.emit('clicked', props.count)
  }

  return h('p',
      h('button', { onClick }, 'Add')
   )
}

export default Counter
```

It would be nice to have type checking on `@clicked="handler"` just like in a component created with <script setup>. It's able to do it for the props, I wonder why not also for the emits.

**Comment by johnsoncodehk** [comment]
Have not handle FunctionalComponent events type yet, will support it.
