### ISSUE TITLE
Template validation fails with defineProps in JavaScript

### ISSUE THREAD

**Issue by lennyanders** [johnsoncodehk/volar#31]
So I got a fairly specific case where I get an error: `Cannot find name 'X'.`, that only appear when I have a `jsconfig.json` in my Project and use `defineProps` in script setup.

I use the jsconfig for path aliases, these don't work with autocompletion in vetur so "can't" switch to that. 

My `jsconfig.json` looks like this:
```json
{
  "compilerOptions": {
    "checkJs": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  }
}
```

And a Vue component that throws the stated error looks like this:
```vue
<script setup>
  import { defineProps } from 'vue';

  const props = defineProps({});

  const NOOP = () => {};
</script>

<template>
  <button @click="NOOP">click me</button>
</template>
```

I just checked and it seems that the same error also appears with a `tsonfig.json`, which I did not use yet, since I currently only use plain JavaScript.

**Comment by johnsoncodehk** [comment]
Thanks for the feedback! It has updated to 0.16.9.

But I plan to only support ts, so js support may not be very well.

**Comment by lennyanders** [comment]
Thanks man, this works great for now! I planned to switch to TypeScript anyway, but I don't know how soon. I probably could start with just converting the Vue files and convert the harder to type JS files later.
