### ISSUE TITLE
Volar Seperate Script Block Problem

### ISSUE THREAD

**Issue by kadiryazici** [johnsoncodehk/volar#310]
Hi, if you use a seperate block in your Vue component then Volar thinks the properties of second script is available in whole component, this causes naming problems. If you import same property in both scripts, Volar thinks you imported it twice.

Version: 0.26.1

```vue
<script lang="ts" setup>
import {ref} from 'vue';
interface Props {
   name: string
}
</script>

<script lang="ts">
import {ref} from 'vue';
export interface Props {
   id: string;
}
</script>
```
![image](https://user-images.githubusercontent.com/47540799/125794941-c000d27f-5a08-4765-8502-73aac2800bae.png)
![image](https://user-images.githubusercontent.com/47540799/125794963-11819e74-a59a-4347-bdfb-f3eef045d52e.png)

**Comment by johnsoncodehk** [comment]
This is the correct result based on runtime behavior.
