### ISSUE TITLE
Typescript errors for elements in v-for loop

### ISSUE THREAD

**Issue by kachidk** [johnsoncodehk/volar#3112]
After the update to Volar v1.63, elements of iterable objects with explicit type `any` in v-for loops are inferred as type unknown

![image](https://user-images.githubusercontent.com/61981167/235861905-c8564a8a-5105-497b-9538-45d546228d01.png)

**Comment by rchl** [comment]
Think that's probably correct because you have optional chaining there so that means that it considers the type being `undefined | any[]` and that would likely result in `never`.

**Comment by pjninnim** [comment]
Seeing the same problem too after the update when optional chaining is not being used so it is not linked to that. The same problem was present in v1.6.2.

**Comment by rchl** [comment]
It might help the author to fix it if you provide specific example. Ideally a repo.

**Comment by pjninnim** [comment]
The below shows a simple repo:
![image](https://user-images.githubusercontent.com/2931227/235890096-44205980-2cc2-4c36-9d88-90797ce693da.png)

**Comment by Jahtila** [comment]
Having the same problem, quite easy to replicate it:

```vue
<template>
  <div v-for="item of testArray" :key="item.id">
    {{ item.name }}
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  setup() {
    const testArray: any = [
      {id: 'one', name: 'Test One'},
      {id: 'two', name: 'Test Two'}
    ]
    return {
      testArray
    }
  }
})
</script>
``` 

![image](https://user-images.githubusercontent.com/12531474/235889758-92bf93a4-fcad-4c46-8032-63ce8738776d.png)

Previously (on versions < 1.6.2) **item** was 'any' type as well and not 'unknown' and had no error.
_(Forcing the testArray to be 'any' type here is just to replicate this problem, I'm aware that it should be properly typescripted.)_

**Comment by mzuccaroli** [comment]
same problem here, I  have updated vue-tsc to latest version but the problem persists

**Comment by so1ve** [comment]
@mzuccaroli Would you mind open a new issue with minimal reproduction?

**Comment by mzuccaroli** [comment]
> @mzuccaroli Would you mind opening a new issue with minimal reproduction?

yes as soon as possible (I had some personal issues sory)
meanwhile the quick & dirty solution I found is downgrading vue-tsc to 1.6.0
