### ISSUE TITLE
Events first letter cropped from auto-suggestions in Vue 3

### ISSUE THREAD

**Issue by victorgarciaesgi** [johnsoncodehk/volar#312]
Hi!

Was playing with events and event-props and found out that events names first letter is cropped from names!

![image](https://user-images.githubusercontent.com/15092120/125831920-7ea0d0eb-024b-4a13-8f5b-9ea0b9cc7056.png)

**On Vue 2, the problem is not here**

![image](https://user-images.githubusercontent.com/15092120/125832179-84bccd39-1b26-499e-942a-7c57556b14df.png)

Also I was wondering why props named `onXX` are automatically converted to events `@xx` ?
Is this valid in runtime or is there a convention?

Thanks! :)

**Comment by johnsoncodehk** [comment]
Could you make a vue3 repro by https://github.com/johnsoncodehk/volar-starter?

> Also I was wondering why props named onXX are automatically converted to events @xx ?
> Is this valid in runtime or is there a convention?

I'm not sure, but vue has define like this: https://github.com/vuejs/vue-next/blob/master/packages/runtime-dom/types/jsx.d.ts#L1183

**Comment by victorgarciaesgi** [comment]
The exact vue3 repro is already here if you want :) 
https://github.com/victorgarciaesgi/vue-chart-3/tree/main/packages/test/vue3

**Comment by johnsoncodehk** [comment]
It seems can only be repro with certain conditions?

<img width="956" alt="螢幕截圖 2021-07-16 上午1 48 17" src="https://user-images.githubusercontent.com/16279759/125834225-56e841e0-541e-4c2e-a9f9-945315e51787.png">

**Comment by victorgarciaesgi** [comment]
Hosorry not the good branch!
https://github.com/victorgarciaesgi/vue-chart-3/tree/0.4.0/packages/test/vue3

**Comment by victorgarciaesgi** [comment]
Btw I'm playing with `VueProxy` to type my components and permit access to the data types

**Comment by johnsoncodehk** [comment]
I found that this problem occur with pascalCase attr setting, thank you!

<img width="130" alt="螢幕截圖 2021-07-16 上午2 03 40" src="https://user-images.githubusercontent.com/16279759/125835918-4bdae591-4a02-410c-b3be-71fbf9c6aacd.png">
