### ISSUE TITLE
does not show quckHint in interface

### ISSUE THREAD

**Issue by thisVioletHydra** [johnsoncodehk/volar#313]
![image](https://user-images.githubusercontent.com/11839238/125889749-225b529b-2930-4be5-ae58-883e681ff39f.png)
![image](https://user-images.githubusercontent.com/11839238/125889768-f39e2285-267d-469e-ab3e-2bbc6bdac8df.png)

help 😢

**Comment by johnsoncodehk** [comment]
This is TS problem, volar can't change it.
