### ISSUE TITLE
I'm getting a warning

### ISSUE THREAD

**Issue by berkantsoytas** [johnsoncodehk/volar#316]
Version : 0.26.3
[Error - 15:01:49] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'quoteStyle' of null
  Code: -32603 
  
  
0.26.2 There were no errors,warning or bugs in this version.

**Comment by johnsoncodehk** [comment]
Can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?

If not please please a provide reproduce case.

**Comment by berkantsoytas** [comment]
The problem is that when I create a new component, it gives this warning no matter what key I press in that file.

**Comment by berkantsoytas** [comment]
And the error still persists
![image](https://user-images.githubusercontent.com/54627016/126080771-7cab2232-a5a6-4bc3-9581-fbe9573a3cc4.png)
Version : 0.26.4
