### ISSUE TITLE
CodeLens -- What are all these features!?

### ISSUE THREAD

**Issue by WesleyKapow** [johnsoncodehk/volar#318]
Would love some documentation on what all of the CodeLens features are. Specifically curious what Code Lens References and Code Lens: Script Setup Tools do.

**Comment by johnsoncodehk** [comment]
Hi @WesleyKapow, you can see https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup#_git-lens about references CodeLens. In volar, references CodeLens support for css class name in `<style scoped>`, `<style module>`, and slots in `<template>`.

**Code Lens: Script Setup Tools**: If enabled, with use `<script setup>`, you will a ref sugar toggle above `<script setup>` tag to quick convert ref sugar syntax. In future we will also support setup sugar conversion.
