### ISSUE TITLE
Can this be used side by side with Vetur? 

### ISSUE THREAD

**Issue by Stevenje** [johnsoncodehk/volar#32]
Can this be used side by side with Vetur?

**Comment by johnsoncodehk** [comment]
Not currently possible, but it may be supported if needed.

Can you say what problems you need to use together to solve?

**Comment by Stevenje** [comment]
Hey @johnsoncodehk Just trying to understand whether this would be considered a drop in replacement for Vetur or whether they would be used side by side. 

But I'll disable Vetur, and give this a go! :)

**Comment by johnsoncodehk** [comment]
You can think of it as a branch of Vetur, Volar focuses on performance and TS support, but Vetur has more language support. :)

**Comment by Stevenje** [comment]
Amazing! Volar all the way!

**Comment by johnsoncodehk** [comment]
Thank you. ^^

close but if you have still has problem you can reopen this issue.

**Comment by blurdylan** [comment]
@johnsoncodehk I think this should be specified somewhere on the Readme because most people already use Vetur.

**Comment by johnsoncodehk** [comment]
@blurdylan Due to many people's questions, I updated some instructions in the readme. Hope it answers.
