### ISSUE TITLE
v-for looses types of key for iterating over object

### ISSUE THREAD

**Issue by CzBiX** [johnsoncodehk/volar#323]
This issue is probably similar to #117.

For a component
```vue
<template>
  <div>
    <div v-for="(value, key) in obj">
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  setup() {
    const obj: {[x: string]: string} = {}

    return { obj }
  }
})
</script>
```

obj is correctly typed.
key is `string | number` while it should be `string`

**Comment by johnsoncodehk** [comment]
key is string in expected, please provide reproduce.

<img width="319" alt="螢幕截圖 2021-07-22 下午6 08 05" src="https://user-images.githubusercontent.com/16279759/126623075-872d46dd-731e-476d-bef4-cffe34db09fa.png">

**Comment by CzBiX** [comment]
@johnsoncodehk Sorry, I updated example code, please check it again.

**Comment by johnsoncodehk** [comment]
This is TS behavior, you should use Record.

```ts
const obj: {[x: string]: string} = {}
declare const key: keyof typeof obj // string | number
```

**Comment by CzBiX** [comment]
Thanks for the quick explanation.
I'm using the data structure generated by openapi-generator. It seems that I should raise an issue to them.
