### ISSUE TITLE
The type keyword is automatically added when typescript is introduced

### ISSUE THREAD

**Issue by TuiMao233** [johnsoncodehk/volar#325]
![image](https://user-images.githubusercontent.com/49724027/126728821-a353bec8-21fa-4fb1-9de7-ef5dc78a12a2.png)

**Comment by johnsoncodehk** [comment]
https://github.com/vuejs/vue-next/issues/3183 already resolved and no import type is no need anymore. Will remove this checking in volar.

**Comment by johnsoncodehk** [comment]
> [vuejs/vue-next#3183](https://github.com/vuejs/vue-next/issues/3183) already resolved and no need import type anymore. Will remove this checking in volar.
