### ISSUE TITLE
Request textDocument/codeAction failed since Volar 0.26.2

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#326]
Hi,

after upgrading to 0.26.x, my project starts to popup the following errors.

`
[Error - 9:57:06 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. False expression: /Users/xiake/dev/crm/node_modules/@xhs/yam-beer/cmp/common/Badge/Badge.vue.ts linked to nonexistent file /Users/xiake/dev/crm/node_modules/@xhs/yam-beer/cmp/common/Badge/Badge.vue.ts
  Code: -32603 
[Error - 9:59:01 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. False expression: /Users/xiake/dev/crm/node_modules/@xhs/yam-beer/cmp/overlayers/Option/MenuOption.vue.ts linked to nonexistent file /Users/xiake/dev/crm/node_modules/@xhs/yam-beer/cmp/overlayers/Option/MenuOption.vue.ts
  Code: -32603 
`

**Comment by johnsoncodehk** [comment]
Hi @oliverzy, can this problem reproduce in https://github.com/johnsoncodehk/volar-starter? And what are the steps to reproduce? Thank you.

**Comment by oliverzy** [comment]
It cannot be reproducible by volar-starter. I can solve this by adding `node_modules/@xhs/yam-beer/cmp` in 'include' section  of tsconfig.json.

But before 0.26, volar doesn't complain this. Ummm.

**Comment by johnsoncodehk** [comment]
Please try to make a repro case when you free, otherwise I can't check this.

**Comment by oliverzy** [comment]
I have trying to find the commit that related to this one. The version that starts to crash is 0.26.2, 0.26.1 is fine.
The issue happened when my project is consuming a vue file (no compiled) that comes from other packages.

**Comment by oliverzy** [comment]
Hi Johnson,

The project is too big. It's pretty hard to create a repro case.
anyway, I cloned the volar project and debug locally.
Finally I find the commit that causes issue is https://github.com/johnsoncodehk/volar/commit/f6480e4543990eadddf86a8293b6ad0537ff9584

Could you see any problem on this change?

**Comment by johnsoncodehk** [comment]
Useful, thanks. :) I think you need to config allowJs option after the fix.

But don't use 0.26.0 ~ 0.26.1 please it has serious performance issue and https://github.com/johnsoncodehk/volar/commit/f6480e4543990eadddf86a8293b6ad0537ff9584 fixed it.

**Comment by oliverzy** [comment]
Hi Johnson,

I pull the latest code, and allowJS is turned on, the issue still persists unless I make the following change.
![image](https://user-images.githubusercontent.com/1321817/127443139-e07e364e-c868-44cd-b8b7-4459902fbc77.png)

**Comment by johnsoncodehk** [comment]
Thanks to check it, I think this change will cause false positives. Can you share your tsconfig?

**Comment by oliverzy** [comment]
Sorry, Johnson.

The issue should have been fixed. It looks like some caching problem on my side, I cannot reproduce it anymore.

Thanks again.
