### ISSUE TITLE
[Error] Request textDocument/hover failed. 

### ISSUE THREAD

**Issue by EralChen** [johnsoncodehk/volar#330]
Hi,

~~QAQ(我不太会说英文)~~，the following errors：

![hover-error](https://user-images.githubusercontent.com/82485978/126875348-10a5ab54-fd66-4acb-98a9-bd59f789bb1d.png)

```shell
[Error]Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'replace' of undefined
  Code: -32603 
```

It can be reproducible in [the simple demo](https://github.com/EralChen/vite-cesium-start) . I tried `volar 0.25.x` and `volar 0.26.x` ，it seemed to happen.

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/7ee76fac05c8baa480eb980b61ecbb34caf4619b.
