### ISSUE TITLE
Component :is with custom event that overrides native event

### ISSUE THREAD

**Issue by jcppman** [johnsoncodehk/volar#333]
Is this currently supported? if not, what would be the most ideal workaround?

```
<template>
  <component :is="theComponent" @change="handleChange" />
</template>
<script lang="ts">
import { defineComponent, resolveComponent } from 'vue';

export default defineComponent({
  setup() {
    const theComponent = resolveComponent('custom-component');
    function handleChange(args1: boolean, args2: string) {}
    return {
      theComponent,
      handleChange,
    };
  },
});
</script>
```

the example above will have warning 
type '(args1: boolean, args2: string) => void' is not assignable to type '(payload: Event) => void'

And thanks for the awesome tool!

**Comment by johnsoncodehk** [comment]
It's supported in some ways in past, but it doesn’t work now, will fix it. Thanks!

**Comment by johnsoncodehk** [comment]
Disable type-checking in next version for now, because we don't have a good way to handle this case currently:

```vue
<component :is="condition ? Foo : Bar" />
```
