### ISSUE TITLE
Variable usage checking for css variable injection

### ISSUE THREAD

**Issue by caxerx** [johnsoncodehk/volar#335]
The variable used as css variable inject (https://github.com/vuejs/rfcs/pull/231) will not considered as an used variable and produce a 'declared but its value is never read' error.

Example:
```
<script setup lang="ts">
const containerHeight = "500px";
</script>

<style scoped>
.container {
  height: v-bind(containerHeight);
}
</style>
```
The variable `containerHeight` will cause a error since it only used in the style tag.

**Comment by glen-84** [comment]
@johnsoncodehk,

Is this supposed to handle string paths?

![image](https://user-images.githubusercontent.com/261509/130316161-22cb6a65-94cb-4029-8443-58da0d3eb9bb.png)

**Comment by johnsoncodehk** [comment]
@glen-84 No, I keep string paths as a way to escape diagnosis.

**Comment by glen-84** [comment]
But then how can I get the variable to show as used?

**Comment by johnsoncodehk** [comment]
Use `v-bind(xxx)` instead of `v-bind("xxx")`.

**Comment by glen-84** [comment]
https://v3.vuejs.org/api/sfc-style.html#state-driven-dynamic-css

> The syntax works with <script setup>, and supports JavaScript expressions (**must be wrapped in quotes**)

**Comment by johnsoncodehk** [comment]
@glen-84 Thanks to point this out! Will follow up this problem.
