### ISSUE TITLE
'Cannot find name' when using js

### ISSUE THREAD

**Issue by notiv-nt** [johnsoncodehk/volar#336]
VSCode gives me an error when i'm using `vue3 + js + props[ + setup]`
```
Cannot find name '%name%'.
```

<details>
  <summary>Image</summary>
  <img src="https://user-images.githubusercontent.com/10743009/127229316-f9259dea-ff90-4cb9-ac2f-034a41a5b0b0.png">
</details>

But the funny thing: 

<details>
  <summary><b>props + data + setup</b> — ok</summary>
  <img src="https://user-images.githubusercontent.com/10743009/127228610-4659c6f6-83ad-4367-9b8e-7243666ed4e8.png">
</details>

<details>
  <summary><b>props + data</b> — ok</summary>
  <img src="https://user-images.githubusercontent.com/10743009/127228905-88f569f8-98a0-47a1-a172-fc1d5d96d533.png">
</details>

<details>
  <summary><b>setup only</b> — ok</summary>
  <img src="https://user-images.githubusercontent.com/10743009/127229000-f3f538ea-3e26-40c0-b13f-2fee5c8fa38a.png">
</details>

<details>
  <summary><b>setup + props</b> — doesn't work at all</summary>
  <img src="https://user-images.githubusercontent.com/10743009/127228518-e284c0f9-d112-4686-b4a2-aac63a2a5fd6.png">
</details>

<details>
  <summary><b>props</b> — :(</summary>
  <img src="https://user-images.githubusercontent.com/10743009/127231221-aaf12c26-7d87-45bc-a523-60bc541575f0.png">
</details>

[Repo](https://github.com/notiv-nt/volar-vue-temp)

**Comment by Shinigami92** [comment]
Pls try

```ts
export default {
  props: { propName: String },
  // data: () => ({ dataName: 'hello' }),
  setup() { return { setupName: 'here' } },
};
```

or

```ts
export default {
  props: { propName: String },
  // data: () => ({ dataName: 'hello' }),
  setup: () => ({ setupName: ref('here') }),
};
```

**Comment by notiv-nt** [comment]
@Shinigami92 no, doesn't work either

**Comment by johnsoncodehk** [comment]
Please check your extension version, after 0.26.6 template is not type-check with `<script lang="js">`.

See https://github.com/johnsoncodehk/vue-tsc/discussions/46.

**Comment by notiv-nt** [comment]
@johnsoncodehk 
Volar **v0.26.3**

File:
```
<template>
  <div>{{ propName }}</div>
  <div>{{ setupName }}</div>
</template>

<script>
export default {
  props: {
    propName: String,
  },

  setup() {
    return {
      setupName: 'here',
    };
  },
};
</script>

```

**Comment by johnsoncodehk** [comment]
@notiv-nt please update your extension version to latest 0.26.9.

**Comment by notiv-nt** [comment]
@johnsoncodehk ok, need to update vscode too
Now, there is no error, but variables are type `any`
![image](https://user-images.githubusercontent.com/10743009/127339019-6df54766-4217-43c3-ae02-385da24b277b.png)

**Comment by johnsoncodehk** [comment]
This is expected, if you want type-check in template please use `lang="ts"`.

**Comment by notiv-nt** [comment]
Yes, i know, but is it possible to treat `<script>` with javascript as typescript? Even without `lang="ts"`?

**Comment by johnsoncodehk** [comment]
This is the behavior of the old version, but we found that the jsdoc type definition will be broken.

If you remove props option only keep setup(), you can still have some type-checking in template, because js limited depth of type-checking.

I think you're searching for this.

```vue
<script lang="ts">
// @ts-nocheck
...
</script>
```
