### ISSUE TITLE
Consider publishing the language server to npm

### ISSUE THREAD

**Issue by predragnikolic** [johnsoncodehk/volar#339]
Hello, 

Have you considered publishing the Volar language server to npm, so it can be reused in other editors as well?

**Comment by johnsoncodehk** [comment]
It's planned but still need some works. See https://github.com/yaegassy/coc-volar-experimental/issues/2, https://github.com/johnsoncodehk/volar/discussions/338.

**Comment by predragnikolic** [comment]
Thanks for the reply!

If you don't mind I would leave this issue open until it is published to npm.

**Comment by johnsoncodehk** [comment]
It's here: https://www.npmjs.com/package/@volar/server

**Comment by predragnikolic** [comment]
Top 🔝🙂
