### ISSUE TITLE
withDefault confuses props types

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#344]
It seems `withDefault` partially modifies the Volar types of props, in particular it can narrow an `any` type in the parent.

To work around a bug in current Vue release, I have defined my `data` prop as `any` but it has a default value like so:
```ts
const props = withDefaults(
  defineProps<{ data?: any }>(),
  { data: () => [] },
);
```

Now if I hover `props` in TS, I can clearly see that the returned value still has `{ data: any }`:
![image](https://user-images.githubusercontent.com/3832820/128194161-a33b5868-f738-425f-9e1f-94c91b48c15f.png)

Yet, in templates Volar thinks it's `data: never[] | undefined`, which is clearly influenced by the default value `[]`:
![image](https://user-images.githubusercontent.com/3832820/128194398-e07718d0-5dd3-4f84-852b-c090cb5ecb96.png)

**Comment by johnsoncodehk** [comment]
This is optional prop so it can be undefined in parent attr. It should be `never[]` in itself's template.

**Comment by jods4** [comment]
TS `props.data` and the type of component in template are in disagreement: one says `any`, the other `never[] | undefined`, so something is not coherent.

I would argue it's the latter that is wrong:

I declared `data` as `any`... or `any | undefined` if you wish but that's still basically `any`.

The default value must be assignment compatible with the base type, and it should remove `undefined` from the returned `props`, as there's a default now.
So it should be `any | undefined` minus the `undefined` -> just `any`.
And that actually works.

The component property should be just what I said in `defineProps`, regardless of the `withDefault`, since `undefined` is an acceptable binding -> it should stick to `any | undefined`... or just `any` as it's a special type.

From what I observe, the component property seems to be the type of `withDefault` or undefined. In this case, the type of `[]`, aka `never[]`, or `undefined`.

But that's narrowing the declared property type.

If I declare `x?: A | B | C` and give a default of `B`, the component property must not be `B | undefined` it should stick to `A | B | C | undefined`.

**Comment by johnsoncodehk** [comment]
Thanks for the shared, but this is `defineComponent` behavior not volar.

```ts
const Component = defineComponent({
	props: {
		data: {
			type: {} as PropType<any>,
			required: false,
			default: () => [],
		}
	}
});
type Data = InstanceType<typeof Component>['$props']['data']; // never[] | undefined
```

**Comment by jods4** [comment]
ah sorry... I'm never sure if the typing problems come from Vue types or Volar 😞 
I'm gonna move this issue to vue-next.

**Comment by johnsoncodehk** [comment]
Never mind, thank you for being active. :)
