### ISSUE TITLE
vuex4 mapState and mapAction can not infer correct type

### ISSUE THREAD

**Issue by Yijx** [johnsoncodehk/volar#345]
### First，I have a array in store and i use mapState in component,but vscode with volar can not infer the type,
[![fnGrE4.png](https://z3.ax1x.com/2021/08/06/fnGrE4.png)](https://imgtu.com/i/fnGrE4)
when i use mapState syntax like this [vuex mapState](https://next.vuex.vuejs.org/guide/state.html#the-mapstate-helper),vscode tell me has a overload error.and vue-cli can not work.[![fnU3fH.png](https://z3.ax1x.com/2021/08/06/fnU3fH.png)](https://imgtu.com/i/fnU3fH)

### Secondly, mapAction has same question
[![fnYmOf.png](https://z3.ax1x.com/2021/08/06/fnYmOf.png)](https://imgtu.com/i/fnYmOf)

so, if i want to vscode or volar can infer the vuex type with simplest synax， how can i do？

Environment：
vscode:1.59.0
volar: 0.26.11
vue:3.0.4
vuex: 4.0.0
typescript:4.1.5
Vue TS Plugin: √

**Comment by johnsoncodehk** [comment]
Please use Pinia instead of Vuex if you need type-check support.

> so, if i want to vscode or volar can infer the vuex type with simplest synax， how can i do？

change `...mapState({ ... })` to

```ts
(...mapState({ ... })) as any as {
  favoriteList(): Arr_Item_Type_You_Wanted[],
  ...
}
```
