### ISSUE TITLE
Volar stops working

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#352]
I believe that `0.26.12` must have a regression in it! Suddenly I can no longer run Volar without it crashing repeatedly!

![image](https://user-images.githubusercontent.com/980757/128647449-d5738a9a-6071-446b-9fb7-b0db41d57298.png)

I am working in a **pnpm** monorepo with workspaces and I'm only using Vue3 and Typescript in all frontend repos but the error suggests problems with VueJS 2:

<img width="1280" alt="2021-08-08_15-22-05 (1)" src="https://user-images.githubusercontent.com/980757/128647463-07438589-0e9c-4cf7-88f6-2a63e72a42ed.png">

I have double and triple checked that I have no references to Vue2 and I also did a `pnpm purge`. I also made no changes to VueJS (or ViteJS) in the past many hours and it had been working all day.

**Comment by torueck** [comment]
yes, same for me using 0.26.12

**Comment by ksnyde** [comment]
Note: I have now moved back to `0.26.11` and I can verify it fixes the problem!

**Comment by torueck** [comment]
thanks for the note - this indeed fixes the issue.
