### ISSUE TITLE
defineProps breaks types in JS with template

### ISSUE THREAD

**Issue by Goosterhof** [johnsoncodehk/volar#353]
When using defineProps in js the types all revert to any.

Without defineProps:
![image](https://user-images.githubusercontent.com/24678549/128688366-9fc0eb12-ac1c-4d0a-b6e0-b692e5d79185.png)

With defineProps:
![image](https://user-images.githubusercontent.com/24678549/128688536-ad7f489a-04bc-4e6f-a4b0-fb3da9b794b9.png)

**Comment by johnsoncodehk** [comment]
We can support template type-check with `lang="js"` due to typescript limitation. See https://github.com/johnsoncodehk/volar/issues/336#issuecomment-888368947

Will force disable template type-check with `lang="js"`.
