### ISSUE TITLE
Issue with missing Symbols in TS

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#354]
I'm running into an issue that developed around the same time yesterday as the regression from `0.26.12`. I have now upgraded to `0.26.14` and the TS features constantly crashing has indeed resolved. However, I am now getting a lot of odd TS inference in **vs-code** such below:

![image](https://user-images.githubusercontent.com/980757/128741283-b509f04b-4fd8-4a93-853d-6a2695e27831.png)

For some added color, you can see below that indeed **vs-code** complains about the symbol not being available while also providing details on the symbol:

<img width="884" alt="2021-08-09_09-34-07 (1)" src="https://user-images.githubusercontent.com/980757/128741598-88ece75b-24c7-443d-8125-7bd00f04793b.png">

Now I think there is a decent chance that this issue is _not_ related to **Volar** because I opened up one of my individual packages in the monorepo. The particular package uses TS but not Volar and in this case I am seeing a similar pattern which suggests something else may be in play. That said ... all of this started yesterday at the same time.

Anyway, feel free to close if you can't reproduce this in your repos or feel that it's clearly connected to some other artifact. I am using the _insiders edition_ of VS-Code and it's now on TS 4.5.0 so maybe this is where I'm hitting the wall.

**Comment by ksnyde** [comment]
I did roll back to TS 4.3.5 to see if that fixed things but I'm still seeing this behavior

**Comment by johnsoncodehk** [comment]
> ... eslint(import/named)

It's seem eslint extension error report, please try disable eslint / volar respective and check the error still on or not.

**Comment by ksnyde** [comment]
Yes you're right, i'm going to close this as it's clearly not a Volar issue but i'm at a loss where to point. The eslint plugin which appears to throw the error is not installed! I even ran `pnpm prune`  to be certain

![image](https://user-images.githubusercontent.com/980757/128758769-4d27d110-8008-4a73-9d80-f92cf36f3f1a.png)

I hate these sorts of time sinks.
