### ISSUE TITLE
defineEmits / defineProps not import error

### ISSUE THREAD

**Issue by heart-er** [johnsoncodehk/volar#355]
vue 3.2 defineEmits is a macro, so it can't must be import it

now:
it has a not import error

expect:
not import errnor

**Comment by johnsoncodehk** [comment]
You don't need to import after vue 3.1.3 and it's not volar side problem. Please check https://github.com/johnsoncodehk/volar-starter.

**Comment by numfin** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/1606
