### ISSUE TITLE
Support for GraphQL template highlighting

### ISSUE THREAD

**Issue by tgriesser** [johnsoncodehk/volar#358]
Hello! Just getting started with Vue and ran into an issue getting GraphQL syntax picked up within the `<script>` blocks using Volar. The same feature works with Vetur, so if you had any ideas on the best way to add support this I could work on a PR.

Here's a potentially relevant issue in Vetur: https://github.com/vuejs/vetur/issues/701#issuecomment-367069277 and here's where the `graphql-vscode` plugin defines [support for vue](https://github.com/graphql/vscode-graphql/blob/33a5edc32e7483602b2e95eee09184073cd28abe/grammars/graphql.js.json#L2-L4).

| Volar| Vetur|
|------| ----- |
| ![image](https://user-images.githubusercontent.com/154748/128898478-35fb3e01-67b5-4615-b2cc-d465b0e37efd.png) | ![image](https://user-images.githubusercontent.com/154748/128898163-067cdbdb-6f16-4ced-a67a-7edf501998eb.png) |

Thanks!

**Comment by djmtype** [comment]
Please also support graphql highlighting within Gridsome's `<page-query>` and `<static-query>` too.
