### ISSUE TITLE
Volar can't see Type which is declared in "script setup"

### ISSUE THREAD

**Issue by kadiryazici** [johnsoncodehk/volar#36]
When I use this volar say's "Couldn't find Tabs"

```vue
<script lang="ts" setup>
import { defineProps, PropType } from 'vue';
type Tabs = 'home' | 'album' | 'whatshot';
const props = defineProps({
   name: {
      type: String as () => PropType<Tabs>,
      required: true,
   },
});
</script>
```

**Comment by johnsoncodehk** [comment]
Thanks for the report! will fix it, you can do it temporarily:
```vue
<script lang="ts">
type Tabs = 'home' | 'album' | 'whatshot';
</script>

<script lang="ts" setup>
import { defineProps, PropType } from 'vue';
const props = defineProps({
   name: {
      type: String as () => PropType<Tabs>,
      required: true,
   },
});
</script>
```

**Comment by johnsoncodehk** [comment]
Sorry, after some digging, this is a design limitation of `<script setup>`, you should only put `defeineProps` reference type to `<script>` block, reference message: https://github.com/vuejs/vue-next/blob/085bbd5fe07c52056e9f7151fbaed8f6a2e442b3/packages/compiler-sfc/src/compileScript.ts# L324-L328
