### ISSUE TITLE
vscode-languageserver version

### ISSUE THREAD

**Issue by robokozo** [johnsoncodehk/volar#360]
Is it necessary to use the latest version of the `vscode-languageserver` package as a dependency inside the `vscode-vue-languageservice` package?

I ask because it is currently using `"vscode-languageserver": "^8.0.0-next.1",` My employer frowns on using beta/test versions of package dependencies in any dependency chain. (We have software that actually checks everything in the chain! :( )

Thank you

**Comment by johnsoncodehk** [comment]
We need the `next` version of `vscode-languageserver` to support vscode 1.58.0 or later.

But I think `next` not mean beta/test, it's mean has some breaking changes. vue 3 is `next` too.
