### ISSUE TITLE
codelens/resolve failed

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#361]
![image](https://user-images.githubusercontent.com/980757/129059877-e85d5b62-aff0-49f6-802d-99ecab2eb117.png)

I just upgraded to Vue `3.2.1` (from `3.1.5`) and now when I boot up a Volar/Vue project I get the above dialogs and the underlying error messages are:

```sh
[Error - 8:35:01 AM] Request codeLens/resolve failed.
  Message: Request codeLens/resolve failed with message: Value undefined out of range for undefined options property undefined
  Code: -32603
```

Now admittedly when I upgraded Vue I also updated my **vs-code** (insiders edition) too so possibly this is a factor but I'm guessing it is Vue derived as my upgrade to `3.2.1` was largely due to inconsistencies in the typings for Slots (which were giving me annoying warning squiggles).

**Comment by ksnyde** [comment]
<img width="193" alt="2021-08-11_08-42-11 (3)" src="https://user-images.githubusercontent.com/980757/129060587-51a50578-5321-4f3b-9264-fd4054261a5f.png">

Note that the error repeats every 18 seconds or so.

**Comment by johnsoncodehk** [comment]
We cannot ensure that the insiders work properly, please try the non-insiders version vscode to exclude the insiders factor.

**Comment by ksnyde** [comment]
I didn't have time to do this but after updating vs-code today I don't seem to get this anymore so closing.
