### ISSUE TITLE
false positive on vue/no-parsing-error

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#362]
<img width="1145" alt="2021-08-11_09-20-30" src="https://user-images.githubusercontent.com/980757/129066633-78dae3a7-25b5-434e-9bbd-6670adfd3591.png">

I've defined a **string** parameter `for` as a prop to a VueJS component and then I use this in the template section and get the above error. Unless I'm missing something this should be error free.

VueJS: `3.2.1`
Volar: `0.26.15`

**Comment by ksnyde** [comment]
Here's the component in text form for more convenient recreation:

```vue
<template>
  <label class="p-label" :class="labelStyle" :for="for">
    <slot>
      <!-- Default Slot -->
    </slot>
  </label>
</template>

<script lang="ts">
import { computed, defineComponent } from "vue";
import { useTailwind } from "use-particle";

export default defineComponent({
  props: {
    for: { type: String, default: "" },
  },
  setup(props, ctx) {
    const { tokenize, merge } = useTailwind(props, ctx);
    const t = tokenize();
    const labelStyle = computed(() => {
      return merge(
        (c) => c.layout("block").text("text-gray-600", "dark:text-gray-400", "font-medium", "text-sm"),
        t.value.root,
        "display",
        "textSize",
        "fontWeight",
        "textColor"
      );
    });

    return { labelStyle };
  },
});
</script>
```

**Comment by johnsoncodehk** [comment]
`for` is reserved word so it can't expose to global vars by volar, please rename `for`, or use `$props.for` instead of `for` in template.

**Comment by ksnyde** [comment]
ahhh i see ... ok I'll change my approach and close this issue.

**Comment by ksnyde** [comment]
- `$props.for` also produces a type error
- I tried setting a variable with explicit typing of `string | undefined` in `setup() [...}` but this too produced a type error

**Comment by ksnyde** [comment]
I've worked around it with the following in my `Setup()` function:

```ts
const forRef = (ctx.attrs.for as string | undefined) ? String(ctx.attrs.for) : undefined;
```

and then the following in my template:

```vue
<label class="p-label" :class="labelStyle" :for="forRef">
```

Kinda awkward but it works. Guess I'll close this but would be nice if the $attrs.for property were set to `string | undefined` from `unknown` so this just worked. This would be a VueJS change though I guess.
