### ISSUE TITLE
ref type check failed with vue@3.2

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#364]
![image](https://user-images.githubusercontent.com/41773861/129131780-2021bbcc-896b-4499-b004-27f86feadf74.png)

**Comment by tjx666** [comment]
The pathModalTitle is defined by:

```
const pathModalTitle = ref('xxxx');
```

**Comment by johnsoncodehk** [comment]
Please provide reproduce case by https://github.com/johnsoncodehk/volar-starter, or complete SFC reproduce code.

**Comment by tjx666** [comment]
就很奇怪啊，你发的那个模板项目我跑了没问题。我这边项目升到 vue3.2 就会出问题，一个简单的 HelloWorld 组件都会出问题。

![image](https://user-images.githubusercontent.com/41773861/129211655-c35489f0-4246-4425-a082-f0aa0af9d1e4.png)

**Comment by tjx666** [comment]
![image](https://user-images.githubusercontent.com/41773861/129211863-8fe5095e-51ef-4314-b637-b202ae9a433e.png)

**Comment by tjx666** [comment]
reproduce repository @johnsoncodehk https://github.com/tjx666/electron-vue-vite-boilerplate

**Comment by johnsoncodehk** [comment]
Thanks for the reproduce, I have no check it yet, but I found a similar issue: https://github.com/johnsoncodehk/volar/issues/322

Please try delete node_modules and reinstall it.

**Comment by johnsoncodehk** [comment]
Your vue deps version is not sync:

- https://github.com/tjx666/electron-vue-vite-boilerplate/blob/master/package.json#L34
- https://github.com/tjx666/electron-vue-vite-boilerplate/blob/master/packages/app/package.json#L15

**Comment by tjx666** [comment]
Finally, I fix by:

> remove @vue/runtime-dom in root package.json
> remove node_modules and reinstall

Thanks @johnsoncodehk
