### ISSUE TITLE
Better syntax highlight for global imported component

### ISSUE THREAD

**Issue by jzs11** [johnsoncodehk/volar#367]
Hi Chu,

Is there a way we could enhance this part to show a different color for global imported component?

![image](https://user-images.githubusercontent.com/2770401/129279996-cb767e34-0b05-4b67-aa8e-888857fa4a1f.png)

![image](https://user-images.githubusercontent.com/2770401/129280017-9013d22c-f50b-451a-9273-174d10c0ae6c.png)

Keep up with this great work!

**Comment by johnsoncodehk** [comment]
You could use `GlobalComponents` interface to define it, see https://github.com/johnsoncodehk/volar#using.

**Comment by jzs11** [comment]
> You could use `GlobalComponents` interface to define it, see https://github.com/johnsoncodehk/volar#using.

That's cool!  It would be even better if we could skip it. 😋
Love this plugin and thanks!

**Comment by jzs11** [comment]
hmm it's a tricky one, the library I am using which does not export the class. 

![image](https://user-images.githubusercontent.com/2770401/129307304-52172a50-7c5d-4e87-9e33-7ae81e486721.png)

![image](https://user-images.githubusercontent.com/2770401/129307370-9910a943-92e3-496f-ae53-21e16657c94b.png)

**Comment by johnsoncodehk** [comment]
It seem you already import it as `Dropdown`, just use `typeof Dropdown`.

```ts
declare module 'vue' {
  export interface GlobalComponents {
    Dropdown: typeof Dropdown
  }
}
```

**Comment by jzs11** [comment]
Thanks!
