### ISSUE TITLE
Does not work well if dependencies are installed with pnpm

### ISSUE THREAD

**Issue by Pizzacus** [johnsoncodehk/volar#37]
Hi, I've tried installing the dependencies on [vite-starter-ref-sugar](https://github.com/johnsoncodehk/vite-starter-ref-sugar) with yarn, and the extension works perfectly. But when the dependencies are installed with [pnpm](https://pnpm.js.org/), Volar will think all variables used in the template don't exist.

It happens no matter if setup is used or not. I am using Windows 10.

| With setup | Without setup |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/7659613/102889192-7d029a00-445a-11eb-85e9-b2858cafc4e1.png) | ![image](https://user-images.githubusercontent.com/7659613/102889243-93105a80-445a-11eb-8127-d01954f6b33f.png) |

(So either way, it doesn't work)

[pnpm is pretty cool](https://www.kochan.io/nodejs/why-should-we-use-pnpm.html), but it installs packages a bit differently.

It uses [a lot of symlinks](https://pnpm.js.org/blog/2020/05/27/flat-node-modules-is-not-the-only-way) (junctions on Windows actually) to create a global package storage, so that every package only exists on the disk once. It also creates a non-flat node_modules structure, that prevents your code from [requiring a package you don't depend on](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html). 

And it is probably one of those things that causes a compatibility issue with Volar.

pnpm is normally 100% compatible with Node.js and package bundlers. Even if it creates a different structure from npm, it is completely compliant. Voltar probably makes an assumption at some point about the structure of the node_modules folder that makes it unable to work with it... Or maybe it dislikes symlinks for some reason.

**I've found a workaround:** Installing `@vue/runtime-dom` directly, as suggested for Vue 2, makes Volar work as expected. Although I am on Vue 3 so that wouldn't normally be required

**Comment by johnsoncodehk** [comment]
Thanks for the report! this is because pnpm put '@vue/runtime-dom' module to `node_modules/.pnpm/@vue/runtime-dom@x.x.x`, so volar import '@vue/runtime-dom' fail. Checking to how to resolve.

**Comment by johnsoncodehk** [comment]
please try 0.18.12 and let me know if it working or not.

**Comment by Pizzacus** [comment]
It does seem to work, thank you so much! That was really fast 🚀
