### ISSUE TITLE
vite create vue-ts and vscode has installed volar,  but get errors

### ISSUE THREAD

**Issue by songjiachao** [johnsoncodehk/volar#370]
![image](https://user-images.githubusercontent.com/70792885/129349559-c04b7e41-29a2-479e-86fb-21d536127d81.png)
![image](https://user-images.githubusercontent.com/70792885/129349584-d5e4678e-c2e4-41db-8fcf-ee39f69a35e8.png)

**Comment by johnsoncodehk** [comment]
Please disable volar and check the error still on or not.

**Comment by songjiachao** [comment]
still has the error，vscode use ts analyse .vue file not volar
if I add the vetur the error disappeared


> Please disable volar and check the error still on or not.

**Comment by songjiachao** [comment]
I  found the reason about it.
I should add the setting in settings.json 

 "files.associations": {
        "*.vue": "vue"
  }

thank you very much

**Comment by johnsoncodehk** [comment]
Usually you don't need to set this, please check whether have `"*.vue": "javascriptreact"` in global config.
