### ISSUE TITLE
使用import useRouter 自动提示导入后 按下回车 导入的内容会带着一个$1

### ISSUE THREAD

**Issue by Veloma-Timer** [johnsoncodehk/volar#371]
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/49268882/129438981-2e49c2e4-2c3b-4507-81cd-d450b4b6886b.png">
将volar版本降到0.26.2版本才可以，但是这个版本识别setup有点问题。。。

**Comment by johnsoncodehk** [comment]
Can't reproduce in 0.26.3 and 0.26.16, and `useContext` has been remove in vue 3.2, please update the vue version.
