### ISSUE TITLE
When the component is not used directly, the component is not used

### ISSUE THREAD

**Issue by zhenzhenChange** [johnsoncodehk/volar#372]
[![fcNcOf.png](https://z3.ax1x.com/2021/08/15/fcNcOf.png)](https://imgtu.com/i/fcNcOf)

PS: `Vue 3.2.0` support namespaced component tags when using <script setup>

**Comment by Bobakanoosh** [comment]
This would be a very nice feature to have!

**Comment by arpadgabor** [comment]
Now that Vue 3.2 is officially released, any updates on this issue? I know it's not a very high-priority feature, but it's a welcome addition and could reduce endless imports.
