### ISSUE TITLE
Constant errors in VSCode

### ISSUE THREAD

**Issue by syropian** [johnsoncodehk/volar#374]
When editing template code in a Vue 3 component using `<script setup lang="ts">` this error constantly pops up:
```
[Error - 3:44:19 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
```

VSCode version is latest stable (1.59.0 at time of report)

**Comment by johnsoncodehk** [comment]
It seem happen after run `Volar: Restart Vue server` command, please use `Developer: Reload Window` command instead of `Volar: Restart Vue server` for now.

**Comment by syropian** [comment]
Thank you! 🙏🏻
