### ISSUE TITLE
Pug in setup surgar,Components cannot be registered automatically

### ISSUE THREAD

**Issue by wuchaoxin** [johnsoncodehk/volar#375]
Volar version: 0.27.1
Vue version:3.2.2

When I used Pug in setup surgar, I found that the components could not be registered automatically.

And the console will output：[Vue warn]: Invalid vnode type when creating vnode: undefined. 

Did I ignore something?

**Comment by jinrongni** [comment]
https://github.com/vuejs/vue-next/issues/4312#issuecomment-899317599

**Comment by johnsoncodehk** [comment]
> [vuejs/vue-next#4312 (comment)](https://github.com/vuejs/vue-next/issues/4312#issuecomment-899317599)

Thanks to point this out!
