### ISSUE TITLE
Volar not recognising webpack alias in typescript .vue SFCs

### ISSUE THREAD

**Issue by DanSweeney23** [johnsoncodehk/volar#376]
![image](https://user-images.githubusercontent.com/14074655/129587923-7337c469-201b-49d8-8134-6f36044aef51.png)

../../../ and @/ should be equivalent from the above SFC. The @ path resolution does compile and work correctly, volar just gives me an error with it. I get no errors from imports in .ts and .js files and no errors from non-ts .vue files.

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, but I think it not suitable for implementation.

**Comment by johnsoncodehk** [comment]
You need to config `paths` in tsconfig, it may like `"paths: {"@/*": ["src/*"]}`.

**Comment by DanSweeney23** [comment]
Hi, below is a screenshot of my tsconfig.json. 

![image](https://user-images.githubusercontent.com/14074655/129708311-900c40a7-be99-4721-b741-7b07326e8c07.png)


I also have this in my vue.config.js
![image](https://user-images.githubusercontent.com/14074655/129708461-55dc2e30-b86f-4555-954d-20757ecbfbe2.png)

**Comment by johnsoncodehk** [comment]
What is the error message? Can you provide a reproduce case?

**Comment by DanSweeney23** [comment]
My error messages are simply along the lines of

`Cannot find module '@/js/composables/inputComposables' or its corresponding type declarations.ts(2307)`

I can try to come up with a reproduce case when I am free.

**Comment by johnsoncodehk** [comment]
Just in case. A similar problem occurred to some users because jsconfig and tsconfig existed in the project.

**Comment by DanSweeney23** [comment]
Ah, deleting jsconfig has solved the problem. I thought I needed both as I am integrating typescript into an older js project. Thank you.
