### ISSUE TITLE
Add support for inline event handling

### ISSUE THREAD

**Issue by LukasCornille** [johnsoncodehk/volar#38]
Hi, first of all thanks for this plugin! It's almost been working flawlessly for my exploration with Vue. 

I've encountered one issue; When handling an event in a parent component by using an arrow function, the parameter becomes of type unknown instead of the type that the child passes on to the parent. Any idea's if there is support for this?

![afbeelding](https://user-images.githubusercontent.com/36887321/103367884-76150080-4ac6-11eb-90ba-3791f80d9f53.png)
In the following example, I would expect the Todo.vue component to be aware that the toDoItem is of type TodoItem.

repository can be found here: [https://github.com/LukasCornille/vue-todo](https://github.com/LukasCornille/vue-todo)

**Comment by johnsoncodehk** [comment]
Hi this is emits types define problem, please try this in From component:
```
defineComponent({
  emits: {
    'add-to-list': (item: TodoItem) => true
  }
})
```

**Comment by LukasCornille** [comment]
I've tried with both:

the type-only way
`defineEmit<(e: 'add-to-list', toDoItem: TodoItem) => void>();`
and snippet you suggested as item and todoItem
`defineEmit({
  'add-to-list': (item: TodoItem) => true,
});`

Both however still don't give my todoItem in the parent component a type besides unknown.

**Comment by johnsoncodehk** [comment]
I need to take a look for you project but I can't, maybe your repo is private.

**Comment by LukasCornille** [comment]
It was indeed private, made it public now. Sorry!

**Comment by johnsoncodehk** [comment]
I just found you need to add `"strict": true` to tsconfig.json, sorry I never know.

anyway I know let TS totally working is not easy, so I create a discord server to help, you can ask in server or open issue too next time.
https://discord.gg/5bnSSSSBbK

**Comment by LukasCornille** [comment]
Hmm, adding `"strict": true` in tsconfig.json did also not seem to fix this issue :/

**Comment by johnsoncodehk** [comment]
You may need reload vscode after change tsconfig.json

**Comment by LukasCornille** [comment]
Ah yes it worked indeed, thanks for the help!
