### ISSUE TITLE
function props startsWith on is regard as undefuned

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#382]
Reproduce: https://github.com/tjx666/volar-starter/commit/eee32c171d1ceaa8570de22d3252c1f36d654b02

![image](https://user-images.githubusercontent.com/41773861/129884731-0b2a3ccc-088f-4cac-a6cf-e5bd02ca02de.png)

**Comment by johnsoncodehk** [comment]
I can't reproduce, please make sure update to latest version 0.27.3.

<img width="261" alt="螢幕截圖 2021-08-18 下午7 30 07" src="https://user-images.githubusercontent.com/16279759/129890612-88f73a0a-56d5-4e90-94f1-777d416a00ee.png">

**Comment by tjx666** [comment]
I find this problems is caused by typescript 4.5.0...

**Comment by johnsoncodehk** [comment]
Thanks for the update. Close because we don't maintain for alpha / beta deps.
