### ISSUE TITLE
Typo: "prop using pascalCase" should be "prop using camelCase"

### ISSUE THREAD

**Issue by FADHsquared** [johnsoncodehk/volar#384]
I know this is a very minor pet peeve, but it seems like this is a typo?
<img width="595" alt="image" src="https://user-images.githubusercontent.com/77851256/129924029-f36f5a66-731f-432a-a996-cab7647377f4.png">

**Comment by johnsoncodehk** [comment]
Thanks to point this out!

**Comment by FADHsquared** [comment]
By the way there's the same typo in several places (like in the bottom status bar), just in case if you didn't know. Thanks!
