### ISSUE TITLE
[BUG]Intellisense completion sometimes will replaces the characters

### ISSUE THREAD

**Issue by MeteorGeminy** [johnsoncodehk/volar#385]
> Volar version: v0.27.3
> VS Code version: 1.59
> macOS version: 11.5

### What happend ? 
![bug](https://user-images.githubusercontent.com/14195576/130024056-ac5518e8-feb1-43be-938a-eccd73d7d413.gif)

**Comment by studnitz** [comment]
Got the same problem on the same Volar version.

![CleanShot 2021-08-19 at 10 14 33](https://user-images.githubusercontent.com/9549394/130033191-98589f71-9879-4426-a1b2-b763e7aa332a.png)


![CleanShot 2021-08-19 at 10 15 45](https://user-images.githubusercontent.com/9549394/130033156-6add4a56-a00d-412e-ac64-f0f67acc2164.gif)

**Comment by Shinigami92** [comment]
Oh! Seeing you last posted `gif`, yeah I can confirm I'm also affected by this bug. I just ignored it for now and fixed it myself.
_I'm using `pug`_

**Comment by johnsoncodehk** [comment]
Thanks for the report! It seems random, please let me know if found some way can actually reproduce it in https://github.com/johnsoncodehk/volar-starter.

**Comment by MeteorGeminy** [comment]
I've tried many times. It is just... irregular

**Comment by johnsoncodehk** [comment]
Let we observe 😅, I am also trying.

**Comment by johnsoncodehk** [comment]
Found reproduce steps. :) Please wait for next version.

**Comment by MeteorGeminy** [comment]
thx  :)
