### ISSUE TITLE
How to setup with eslint & format style tag

### ISSUE THREAD

**Issue by jd-0001** [johnsoncodehk/volar#386]
Hi, I am using Volar + ESLint + Prettier. For `.vue` files I am stuck with formatting.

Prettier conflicts w/ max attributes per line of eslint rule so I decided to use eslint for `.vue` file.

But the problem with this is I lost formatting for the `style` tag.

Now, to resolve this I am using Volar as code formatter but it is not following eslint rules like max attributes per line.

So, can I enable formatting for style tag using prettier somehow like Vetur (I guess I was able to achieve this when I was using etur) & tell volar to consider/follow eslint rules?

Regards.

**Comment by jd-0001** [comment]
For your reference below is the issue:

![image](https://user-images.githubusercontent.com/47495003/130027076-ae3a0bdd-f6c4-44a6-8eb7-759275199b5f.png)


```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: ['plugin:vue/vue3-recommended', 'plugin:import/recommended', 'plugin:import/typescript', 'airbnb-base'],
  parserOptions: {
    ecmaVersion: 12,
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
  },
  plugins: ['vue', '@typescript-eslint'],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',

    // we don't want it
    semi: ['error', 'never'],

    // add parens ony when required in arrow function
    'arrow-parens': ['error', 'as-needed'],

    // add new line above return
    'newline-before-return': 'error',

    // add new line below import
    'import/newline-after-import': ['error', { count: 1 }],
  },
}
```

**Comment by johnsoncodehk** [comment]
Please ask to https://github.com/Microsoft/vscode-eslint. 😅
