### ISSUE TITLE
Incorrect comment syntax for `<style>` blocks

### ISSUE THREAD

**Issue by sodatea** [johnsoncodehk/volar#388]
When I execute the `Toggle Line Comment` command (`⌘` + `/` on macOS) in a `<style>` block, Volar inserts HTML block comment `<!-- -->`, which leads to a syntax error in the SFC parser.

It should be `/* */`.

**Comment by johnsoncodehk** [comment]
I can't reproduce, it insert `/* */` to me for `<style>` block.

Please check and try disable other extensions.

**Comment by sodatea** [comment]
Oops. Sorry.
Turns out it's caused by https://marketplace.visualstudio.com/items?itemName=znck.vue 😅

I forgot I had installed that plugin…

**Comment by yxw007** [comment]
> Oops. Sorry. Turns out it's caused by https://marketplace.visualstudio.com/items?itemName=znck.vue 😅
> 
> I forgot I had installed that plugin…

Installing too many plug-ins is also a disaster
