### ISSUE TITLE
Using properties in template gives soft error

### ISSUE THREAD

**Issue by ADCJustinH** [johnsoncodehk/volar#389]
New to this extension so I'm probably missing something but why is it complaining about this?

![image](https://user-images.githubusercontent.com/12364860/130138258-bce251ec-e102-4b89-ba29-f291d5fc26f3.png)

**Comment by ADCJustinH** [comment]
All of this was fixed by changing the prop validator to an arrow function. Anyway to create/show a better error in this situation?

**Comment by johnsoncodehk** [comment]
This is defineComponent types problem, you can also use `as never` to resolve. See #93.
