### ISSUE TITLE
Left side of comma operator is unused and has no side effects

### ISSUE THREAD

**Issue by ollieSk8** [johnsoncodehk/volar#392]
`
使用了setup script 配合了volar 但下边注释的地方会报错
直接ts（2695)Left side of comma operator is unused and has no side effects. 这样咋解决？
<script lang="ts">
export default {
inheritAttrs: false, // 这块会ts编译器报错
customOptions: {},
}
</script>
<script lang="ts" setup>
import { reactive } from 'vue'
// other code
</script>
`
![1629447103566](https://user-images.githubusercontent.com/9378275/130202401-0f1335a2-8ef6-445d-b40c-138691af8878.JPEG)

**Comment by johnsoncodehk** [comment]
Duplicate to #383

**Comment by ollieSk8** [comment]
<img width="703" alt="define" src="https://user-images.githubusercontent.com/9378275/130212574-6dc028ea-15ba-44cb-88b7-c900d8be8488.png">
那就是说声明另外一个script只能用defineComponent？？？

**Comment by johnsoncodehk** [comment]
It's fixed but not release yet. See https://github.com/johnsoncodehk/volar/issues/383#issuecomment-901056477.

> Because `export default` has been remove in virtual file, so the statement syntax is broken, will fix it.
