### ISSUE TITLE
Props are not recognized if there are bindings with a type that refers to SFC itself

### ISSUE THREAD

**Issue by andylizi** [johnsoncodehk/volar#394]
### Reproduction

1. Starting from [volar-starter](https://github.com/johnsoncodehk/volar-starter).
2. Go to `src/components/HelloWorld.vue`, replace `const count = ref(0)` with
```ts
import type HelloWorld from "./HelloWorld.vue";
const count = ref(0) as unknown as typeof HelloWorld;
```
3. Boom.

### Description

![volar-1](https://user-images.githubusercontent.com/12008103/130257820-a1e3032d-75cb-4545-8d79-cd06711e3ac8.png)

This only happens when a top-level binding have a type that refers to the current SFC itself in any way. For example, changing the import statement above to `./App.vue` will still trigger the bug, because `App.vue` imports `HelloWorld.vue`.

`Write LS Template Files` outputs something like
```ts
/* Style Scoped */
declare var __VLS_styleScopedClasses: {
};
/* Props */
{
{
__VLS_componentProps['h1']({
});
// @ts-ignore start tag
__VLS_components.h1;
```
instead of the normal
```ts
/* Props */
declare var $: typeof __VLS_ctx.$;
declare var $data: typeof __VLS_ctx.$data;
declare var $props: typeof __VLS_ctx.$props;
// - snip -
```

### Environment

* Windows 10
* VSCode 1.59.1
* Typescript 4.3.5
* Volar 0.27.3
* Vue 3.2.4

**Comment by johnsoncodehk** [comment]
This is expected, TS does not support circular type references. What is your purpose for doing this?

**Comment by andylizi** [comment]
> What is your purpose for doing this?

Something like
```ts
const instance = getCurrentInstance()!.proxy as unknown as ThePublicInstanceTypeForThisComponent
```


> This is expected, TS does not support circular type references.

Oh, that makes sense. Though, would it be possible to make this error more explicit? As it is now, the `cannot find name` message is a bit confusing.

**Comment by johnsoncodehk** [comment]
You should not do this 😅, `getCurrentInstance` already return the correct type.

> Though, would it be possible to make this error more explicit?

Unfortunately there is no easy way to do it. And usually users will not do this, I think it is of little significance to improve this error prompt.

**Comment by andylizi** [comment]
> `getCurrentInstance` already return the correct type.

Err… its return type doesn't have any component-specific properties like `props` and `emits` through.

And I can think of a use case for this, which is recursive component in combination with template refs. The guide [explicitly said](https://v3.vuejs.org/api/sfc-script-setup.html#using-components) both are supported in `<script setup>`. For example, consider
```vue
<template>
    <div class="tree-menu">
        <button ref="button">{{ label }}</button>
        <tree-menu v-for="node in nodes" ref="submenus" :nodes="node.nodes" :label="node.label"></tree-menu>
    </div>
</template>

<script lang="ts">
import type TreeMenu from "./TreeMenu.vue"

type TreeMenuInstance = InstanceType<typeof TreeMenu>;

interface Node {
    label: string;
    nodes: Node[];
}
</script>

<script setup lang="ts">
import { ref } from "vue"

defineProps<Node>()

const button = ref<HTMLButtonElement | null>(null)
const submenus = ref<TreeMenuInstance[] | null>(null)

const focus = () => {
    button.value?.focus()
}

defineExpose({ focus })

function doSomethingWithSubmenus() {
    submenus.value![0].focus()
}
</script>
```

What should be the type of `submenus`? Of course you can just define a new interface independently like `interface TreeMenuInstance { focus(): void; }`, but then you'd need to make sure it's keep in sync with the actual shape of the instance, and that's not a very typescripty way to do things. Attempting to extract the existing interface from Vue is the obvious solution in my opinion.
