### ISSUE TITLE
missing type checking rendering components inside main.js

### ISSUE THREAD

**Issue by andylix** [johnsoncodehk/volar#398]
Let's say **_App is a component that requires a prop_**, the main.js that's rendering this App component won't raise an error even when no props are passed.

```ts
import { createApp, h } from 'vue'
import App from './App.vue'

createApp(App).mount('#app')
```

It should raise an error since the required prop isn't passed to App.

**Comment by johnsoncodehk** [comment]
It should handle by `createApp` types from vue module, please ask in vue-next repo.
