### ISSUE TITLE
cpu is very high

### ISSUE THREAD

**Issue by lwp001** [johnsoncodehk/volar#399]
use @vicons/ionicons5 or other @vicons/xxx package cpu is very high ;

**Comment by felismargarita** [comment]
I have also face this problem for several days,seems,it will not be fixed in short time,I just use @vicons/ionicons4 instead for a temporary solution. :)

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem by install `@vicons/ionicons5` to https://github.com/johnsoncodehk/volar-starter.

Please provide reproduce case and description of reproduce steps.

**Comment by neohan666** [comment]
so am I

**Comment by johnsoncodehk** [comment]
Please let me know if 0.27.8 still the problem.

**Comment by kikyous** [comment]
> Please let me know if 0.27.8 still the problem.

seems the problem has been solved in my project
😄

**Comment by johnsoncodehk** [comment]
Close because the problem may have been resolved. If not, please open a new issue and provide a reproduce case.

**Comment by lwp001** [comment]
reinstall  no problem  thanks.

**Comment by yaolunmao** [comment]
I reinstalled vscode and volar, but the CPU was still 100%. Only when volar was disabled can it return to normal

**Comment by felismargarita** [comment]
> I reinstalled vscode and volar, but the CPU was still 100%. Only when volar was disabled can it return to normal

have you installed naive-ui and its recommended icon lib vicons? If yes ,I guess the problem is caused by this. :)
