### ISSUE TITLE
Support unwrapping Ref<T> from @vue/composition-api in template

### ISSUE THREAD

**Issue by antfu** [johnsoncodehk/volar#404]
Repro: https://github.com/antfu/repro-volar-vue2-template-unref

![image](https://user-images.githubusercontent.com/11247099/130359338-89517914-271b-477f-93f6-14e293876ff9.png)

I recently made [`vue2-script-setup-transform`](https://github.com/antfu/vue2-script-setup-transform) which enables `<script setup>` in Vue 2 apps. When using with Volar, it get almost everything working perfect despite this one.

As I can see that Volar is unwrapping the type from Vue 3's, while `@vue/composition-api` has another. Is that possible to check the present of `@vue/composition-api` deps and add an additional check when it's the case? I believe this will make many Vue 2 developers start switching to Volar.

Thanks

**Comment by johnsoncodehk** [comment]
Hi @antfu, I think a shims script is more flexible, can you accept this way?

```ts
declare module '@vue/runtime-dom' {
	export * from '@vue/runtime-dom/dist/runtime-dom'
	export { defineComponent } from '@vue/composition-api'
}
```

**Comment by antfu** [comment]
Ah, that's an interesting approach.

I am able to make it work by:

```ts
declare module '@vue/composition-api' {
  export * from '@vue/runtime-dom'
  export * from '@vue/composition-api/dist/index'
}
```

While this could do, I am afraid this will introduce more problems due to type misalignment. Since now it redirects all the types from `@vue/runtime-dom`, they are Vue 3's type. For example,

```ts
import { computed } from '@vue/composition-api'

const foo = computed(() => {})

foo.effect // in Vue 2 this does not exist, while with this shims TS think it's there.
```

Not to mention more complex types involved with Vue 2's component types.

I have also thought about overriding only some of the APIs, but they are still not ideal:

```ts
declare module '@vue/composition-api' {
  export { ref, Ref, computed, WritableComputedRef, ... } from '@vue/runtime-dom'
  export * from '@vue/composition-api/dist/index'
}
```

```ts
import { watch, ref } from '@vue/composition-api'

const foo = ref(0)

watch(foo, () => {}) // incompatible
```

After all, I would think this approach a bit risky. If #405 is a valid fix, I guess it might be more straightforward?

**Comment by johnsoncodehk** [comment]
Unfortunately #405 can fix this problem, If implemented in volar, it needs to use the same method as shims, so the complexity is still there.

I tried https://github.com/antfu/vue2-script-setup-transform/tree/main/playground, and this shims seem fix all error:

```ts
declare module '@vue/runtime-dom' {
	export * from '@vue/runtime-dom/dist/runtime-dom'
	export { defineComponent, PropType } from '@vue/composition-api'
}
```

**Comment by antfu** [comment]
...it does work, even tho I don't understand what happened exactly. Emm, I mean, it's AWESOME! 👍

I will ship it with in the moudle and see if this fix is valid in larger scale apps. Thanks!

**Comment by sxzz** [comment]
I used this slim, but it can’t solve this problem.

<img width="897" alt="QQ20210823-205715@2x" src="https://user-images.githubusercontent.com/6481596/130450958-bcae29df-243e-4b1b-856f-ef1ed6a305fb.png">


```vue
<template>
  <div>
    <demo v-model="text" type="text" /> 
<!-- 
类型“{ modelValue: string; type: string; }”的参数不能赋给类型“Record<string, any> & Readonly<Partial<{}> & Omit<{ value: string; } & {}, never>> & Omit<__VLS_GlobalAttrs, string> & Record<...>”的参数。
  类型 "{ modelValue: string; type: string; }" 中缺少属性 "value"，但类型 "Readonly<Partial<{}> & Omit<{ value: string; } & {}, never>>" 中需要该属性。ts(2345)
-->
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue-demi';
import demo from './demo.vue';
const text = ref('hello');
</script>
```

```vue
<!-- demo.vue -->
<template>
  <div></div>
</template>

<script setup lang="ts">
defineProps<{ value: string }>();
</script>
```
