### ISSUE TITLE
invalid return, produce effects...thanks

### ISSUE THREAD

**Issue by zhangenming** [johnsoncodehk/volar#407]
![image](https://user-images.githubusercontent.com/21235555/130380837-e44bea2c-62fa-421c-8327-55e900fa0063.png)

**Comment by zhangenming** [comment]
one more question,
why  `<` and `>`  colors are so weird and inconsistent(yellow,red,pink,yellow)
Is it my own setup problem or the plugin problem
thanks
![image](https://user-images.githubusercontent.com/21235555/130380941-5daa097f-280a-4387-8790-1c106074a25a.png)

**Comment by johnsoncodehk** [comment]
This is the expected TS behavior. TS will incorporate the return value type even if the code is not available.

> one more question,
> why `<` and `>` colors are so weird and inconsistent(yellow,red,pink,yellow)
> Is it my own setup problem or the plugin problem
> thanks
> ![image](https://user-images.githubusercontent.com/21235555/130380941-5daa097f-280a-4387-8790-1c106074a25a.png)

It's not from volar, please check your other Extensions.
