### ISSUE TITLE
`optional chaining` Syntax Highlight

### ISSUE THREAD

**Issue by lijialiang** [johnsoncodehk/volar#408]
There are syntax highlighting issues within the template using `optional chaining`

vscode v1.59.1
Volar v0.27.7

![image](https://user-images.githubusercontent.com/12247242/130410745-a4e923d8-2082-49c7-b86f-25883c448c5f.png)

**Comment by johnsoncodehk** [comment]
Please show your installed Extensions.

**Comment by lijialiang** [comment]
If I disable volar, I get vue files without any syntax highlighting.

![image](https://user-images.githubusercontent.com/12247242/130432732-f0d044f0-6652-41ec-a0e7-920435a54221.png)


```vue
<template>
  <h1>id: {{ user?.id }}</h1>
</template>

<script lang="ts" setup>
import { ref } from '@vue/reactivity'

interface User {
  id: number
}

const user = ref<User>()
</script>
```

**Comment by johnsoncodehk** [comment]
It's works for me, I think the greater chance is the influence of other expansions.

<img width="235" alt="螢幕截圖 2021-08-23 下午6 35 25" src="https://user-images.githubusercontent.com/16279759/130433696-fb0d4288-2333-456a-b621-8dedee482902.png">

The interesting thing is that your comment's code block has the same problem.

<img width="604" alt="螢幕截圖 2021-08-23 下午6 37 22" src="https://user-images.githubusercontent.com/16279759/130434036-85888f4d-c86d-4ef0-ade7-78c769b41cc1.png">

**Comment by lijialiang** [comment]
After I tried to disable the extensions one by one, I found that it was this [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) that was affecting.

Thank you very much for your patient reply!
