### ISSUE TITLE
How to fix syntax highlighting of pug/sass

### ISSUE THREAD

**Issue by shadow-light** [johnsoncodehk/volar#409]
Hi, thanks for this great extension. I can't work out how to fix syntax highlighting for pug/sass though.

In Vetur it was fine, but doesn't seem to work in Volar. I installed [this sass extension](https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented) as suggested, but doesn't seem to work.

![Screenshot from 2021-08-24 01-02-38](https://user-images.githubusercontent.com/42055707/130470655-22cf59ed-4f84-4ff6-8dff-92fbf89a24dc.png)

![Screenshot from 2021-08-24 01-04-10](https://user-images.githubusercontent.com/42055707/130470718-59512978-1759-49c6-9828-32e9445fb4e9.png)

I inspected the scopes and it is treating the sections as regular HTML/CSS and not detecting pug/sass.

Do I need to change any settings, or is support not available for pug/sass yet?

**Comment by Shinigami92** [comment]
Could you try `<template lang="pug">`? So with double quotes instead of single?

**Comment by shadow-light** [comment]
Oh that did it! Thanks. Didn't realise it would be that simple...

**Comment by shadow-light** [comment]
I suspect this would be pretty easy to fix. I imagine there's a regex somewhere that needs tweaking, but I couldn't find it from a brief browse.

**Comment by shadow-light** [comment]
Thanks @johnsoncodehk, that fixes it
