### ISSUE TITLE
Options API support within methods (not template)

### ISSUE THREAD

**Issue by zoranpopovic** [johnsoncodehk/volar#410]
By using composition-api and defineComponent  in vue2 autocompletion works in the template.  However, i cannot get it to work within the options api methods.  Is this supported, or is there an issue with my setup?

**Comment by johnsoncodehk** [comment]
It's supports, you need to wrap the options object by `defineComponent` even using options api, and please make sure follow up vue 2 setup steps: https://github.com/johnsoncodehk/volar#using
