### ISSUE TITLE
Volar makes TSLint detection mandatory in new releases, but it is sometimes not required

### ISSUE THREAD

**Issue by IanLew** [johnsoncodehk/volar#411]
In version 0.27.7, Volar forces TSLint to be turned on, but it's not required everywhere.
When using vscode, not all projects use vue3, and not all versions use TypeScript.

**Comment by Shinigami92** [comment]
TSLint? 👀 TSLint is deprecated/archived for a year now

**Comment by johnsoncodehk** [comment]
Can you provide some examples for "sometimes not required"? We can more conclusive actual needs.

**Comment by IanLew** [comment]
> TSLint? 👀 TSLint is deprecated/archived for a year now

Error prompts are triggered by TSLint, but if you turn Volar off or lower it to a previous version you will not be prompted. For now, the issue has disappeared in V0.27.9.

**Comment by IanLew** [comment]
> TSLint? 👀 TSLint is deprecated/archived for a year now

I don't know why, but it was caused by Volar.  When I turned off or lowered Volar to 0.27.6, everything worked fine.

**Comment by IanLew** [comment]
> Can you provide some examples for "sometimes not required"? We can more conclusive actual needs.

This error occurs when vue2 is not TypeScript.
@Shinigami92: TSLint has been deprecated.
Possibly due to compatibility issues with VUe2.
