### ISSUE TITLE
HTMLElement type is automatically expanded

### ISSUE THREAD

**Issue by ollieSk8** [johnsoncodehk/volar#416]
1 . define a  custom hook useClickOutside and recive a argument elementRef ,the elementRef type is Ref<null | HTMLElement>
2. define a dropdownRef type is null or HTMLElement
3. template has a div  set ref attribute  dropdownRef 

**Result :
Here I think there may be a problem with the implementation of volar. It will directly expand the HTMLElement type, causing a mismatch of types.**
```javascript

//template  <div class="dropdown" ref="dropdownRef">

// custom hook

const useClickOutside = (elementRef: Ref<null | HTMLElement>): Ref<boolean> => {
    //some other code
}
 const dropdownRef = ref<null | HTMLElement>(null)
 const isClickOutside = useClickOutside(dropdownRef) //  causing a mismatch of types.

```
![截屏2021-08-25 下午2 23 10](https://user-images.githubusercontent.com/9378275/130737672-a4c362e6-6d3f-4d72-8211-485ce61d963e.png)

**Comment by johnsoncodehk** [comment]
This may just a vue type problem. Please try move the code to `*.ts` to check if there is the same error.

**Comment by ollieSk8** [comment]
> This may just a vue type problem. Please try move the code to `*.ts` to check if there is the same error.

sorry, I don’t understand too much, what's that mean "Please try move the code to `*.ts`"?

**Comment by johnsoncodehk** [comment]
Create foo.ts under same directory with Dropdown.vue, copy the Dropdown.ts script block code to foo.ts, and then check the error whether reproduce in foo.ts. (Similar to https://github.com/johnsoncodehk/volar/issues/415#issuecomment-905189308)

**Comment by ollieSk8** [comment]
> Create foo.ts under same directory with Dropdown.vue, copy the Dropdown.ts script block code to foo.ts, and then check the error whether reproduce in foo.ts. (Similar to [#415 (comment)](https://github.com/johnsoncodehk/volar/issues/415#issuecomment-905189308))

![截屏2021-08-25 下午2 47 06](https://user-images.githubusercontent.com/9378275/130740168-ca2734f8-b17f-4ec2-b57b-a1e3ee4b0af5.png)
The same error occurred

**Comment by johnsoncodehk** [comment]
That confirmed this is pure TS problem not volar problem, please ask in [Vue Land TS discord server](https://discord.com/channels/325477692906536972/331999220125138944).

**Comment by ollieSk8** [comment]
> That confirmed this is pure TS problem not volar problem, please ask in [Vue Land TS discord server](https://discord.com/channels/325477692906536972/331999220125138944).

ok ,thanks
