### ISSUE TITLE
TypeScript errors are not displayed in terminal with `--incremental` (vue-tsc@2)

### ISSUE THREAD

**Issue by wangshunnn** [johnsoncodehk/volar#4194]
## Related issue

- https://github.com/vuejs/language-tools/issues/4099

## Description

At first I had the same issue as  #4099 , and I'm very grateful for this quick fix!
Then, when I used `--incremental` based on this fix, I reproduced the issue again.

## Versions

Because `vue-tsc` based on the fixed version has not yet released a new version, I tested it after compiling the current latest `vue-tsc@2.0.7` source code locally, where the dependencies are:

- `@volar/language-core` : 2.2.0-alpha.3
- `@volar/typescript` : 2.2.0-alpha.3

## Steps to reproduce

> - I'm running vue-tsc via `./language-tools/packages/tsc/bin/vue-tsc.js --noEmit --incremental`. 
> - Local testing is required here, so it's also not convenient for me to provide a vue-tsc that can be tested directly, and I can try forking a repository later to reproduce the problem if needed.

1. When `vue-tsc --noEmit --incremental`, the **first execution** (without `tsconfig.tsbuildinfo`), everything **works fine** and a new `tsconfig.tsbuildinfo` cache file is generated. As shown in the figure below:
    
    > <img width="530" alt="image" src="https://github.com/vuejs/language-tools/assets/103867940/a337e524-1419-4cca-8dd4-4163a0d07edc">

3. Then, when **executed repeatedly**, the `.ts` file still prints the error as expected, but the `.vue` file no longer prints the source code for the error line. As shown in the figure below, the output error is **incomplete**. 
    
    > <img width="530" alt="image" src="https://github.com/vuejs/language-tools/assets/103867940/235e9aa4-b3cd-4a5e-a3e6-b89bdfadca4d">

Also, with testing, I noticed that only `.vue` files will have incomplete errors, `.ts` files everything works fine.

**Comment by johnsoncodehk** [comment]
Resolved by https://github.com/volarjs/volar.js/pull/158
