### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by JohnCampionJr** [johnsoncodehk/volar#42]
I wanted to make sure I'm not missing something with Volar.  I seem to not be able to add breakpoints or other debugging when Volar is enabled vs Vetur.

Is this expected?

**Comment by johnsoncodehk** [comment]
I never try debugging to vue, and Volar do not support debugging now. (it be support in future)

It seem the problem is Vetur debugging is broke because Vetur do not support `<script setup>`.

**Comment by JohnCampionJr** [comment]
Yeah, I know Vetur doesn't like script setup, but even if I move everything to standard Composition API, debug still puts breakpoints in all the wrong places.  

Interesting thing is that if I change language for the script block back to js, debugging works perfectly.  Something about the sourcemapping from TS to Webpack.   Way beyond my ability to diagnose.

Regardless, that is a Vetur issue, not Volar.
