### ISSUE TITLE
Support for TS 4.4 (VSCode 1.60)

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#428]
VSCode Insider bulit-in TS version is 4.4.x RC. Known issues:

- Auto-complete not working in template interpolations.

**Comment by yaegassy** [comment]
It seems that VSCode `v1.60` has been released, but the built-in typescript version is `v4.4.2`.

<img width="1011" alt="vscode-1-60-ts-version" src="https://user-images.githubusercontent.com/188642/131946780-3b5b5ba4-ce24-4ae5-98c2-7b14ddd3f435.png">

**Comment by johnsoncodehk** [comment]
Will fix it soon, thanks to point this out!

**Comment by productfrontenddeveloper** [comment]
![CleanShot 2021-09-03 at 09 24 47](https://user-images.githubusercontent.com/38668796/131960054-c3c7c1f0-71a9-43b5-9707-8da473d34cda.png)
some problem :)

**Comment by TrungRueta** [comment]
Just for mention, I'm using volar in Nuxt and yesterday after upgrade vscode to 1.60, i dropped in this same status. Look like Volar only working ok with typescript v4.3, v4.2 or v.4.4 both failed.

I added issue in other plugin which suggest use Volar for develop, i will add here maybe make clearer about issue:

https://github.com/antfu/unplugin-vue2-script-setup/issues/34

**Comment by productfrontenddeveloper** [comment]
no fixed some problem

**Comment by johnsoncodehk** [comment]
@productfrontenddeveloper I'm still checking, please post your founds to avoid I miss something.

**Comment by productfrontenddeveloper** [comment]
sorry i thought it was released when vscode saw the update, it hasn't been released yet. v0.27.12 😞

**Comment by yaegassy** [comment]
@productfrontenddeveloper You will need to build it yourself to try the current fix. try it.

**Cli**:

```
cd /tmp
git clone git@github.com:johnsoncodehk/volar.git
cd volar
yarn
code .
```

**VSCode**:

1. Run -> Start Debugging
2. (Extension Development Host) side:  File -> Open
