### ISSUE TITLE
Vite build process fails when using Yarn 3

### ISSUE THREAD

**Issue by lobo-tuerto** [johnsoncodehk/volar#430]
Hello,

I'm trying to setup a new project using Vite + TypeScript + Vue 3 + Yarn 3.
Dev server starts OK, but when trying to generate the production build, I'm seeing this:

```bash
Error: @volar/transforms tried to access vscode-languageserver,
but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: vscode-languageserver
Required by: @volar/transforms@npm:0.27.7
```

Is this a dependency that should be specified in Volar somehow?

BTW I can make the error go away with:

```bash
yarn add --dev vscode-languageserver
```

But I think Volar should be the one that fully specifies its dependencies. :thinking: 
WDYT?

**Comment by johnsoncodehk** [comment]
Fixed, thank you!
