### ISSUE TITLE
When import .vue file in ts via path alias, `Ctrl + Click` can not jump to the definition.

### ISSUE THREAD

**Issue by shixinla** [johnsoncodehk/volar#435]
When import .vue file in ts via path alias, `Ctrl + Click` can not jump to the definition any more, and the path intellisense can not find .vue file too.

Howerver, it works in v0.27.3 and before.

behavior in v0.27.3:
![GIF 2021-8-30 15-33-17](https://user-images.githubusercontent.com/84222913/131303227-6de71544-f375-4d92-aabe-e009674d24d9.gif)
behavior after v0.27.3(0.27.9):
![GIF 2021-8-30 15-30-21](https://user-images.githubusercontent.com/84222913/131303276-7af2ed0f-5e9b-4a82-a9b6-12b7d7c5d7a9.gif)
## info
Volar version: 0.27.9
Vue TS Plugin: on
tsconfig:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@/tests/*": ["tests/*"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}
```
Vscode info：
```
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by johnsoncodehk** [comment]
It seem TS plugin not working in 0.27.9, thanks for the report!

**Comment by tuan-lm97** [comment]
It look like this problem reappear recently.
v0.30.3 to be exact

**Comment by johnsoncodehk** [comment]
@tuan-lm97 I can confirmed this, thanks for letting me know.

**Comment by erradil** [comment]
I spend a lot of time to know the origin of issue (it's still persist in 0.32.1) 
the solution is simply to install this vscode extension 
https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-typescript-vue-plugin

I hope it's useful

**Comment by johnsoncodehk** [comment]
@erradil See #664.

This problem is actually a bit difficult to solve. Takeover mode is better than TS plugin in all aspects and does not have this problem. I recommend always using takeover mode. Are there any circumstances that make it necessary to use the TS plugin?

**Comment by pate313373** [comment]
Issue still persists in v1.0.25

**Comment by otabekoff** [comment]
This issue is happening again after the recent update.
