### ISSUE TITLE
Being aware of scoped slots types based on data from parent (typescript) 

### ISSUE THREAD

**Issue by chojnicki** [johnsoncodehk/volar#439]
Hi. Here's simple reproduction of scoped slots implementation (of course in this form it does not make any sense, it's just to show the problem).

_DemoParent.vue_
```
<template>
  <DemoChild
    :demo-prop="x" // value "a"
    v-slot="slotProps"
  >
    {{ slotProps.item }} <- will render "a" so should be same type as demo-prop
  </DemoChild>
</template>

<script setup lang="ts">
import DemoChild from '@/components/DemoChild.vue'

type DemoPropType = 'a' | 'b'
const x: DemoPropType = 'a'
</script>
```

_DemoChild.vue_
```
<template>
  <div>
    <slot :item="demoProp" />
  </div>
</template>

<script setup lang="ts">
defineProps({
  demoProp: {
    type: String,
    required: true,
  },
})
</script>
```

It's good that extension can detect in parent component type of `slotProps` based on types defined inside child component, so `slotProps.item` as string in this example. BUT in parent I'm passing not just any string but with certain type, so I need to know that returned slot prop is also in that type.

In real world example I have universal components for table and columns and it works just great on browser but in IDE I'm losing any information of passed data types which is bad.

Any ideas for workarounds or could this be supported by extension?

Regards!

**Comment by johnsoncodehk** [comment]
Hi @chojnicki, in short vue can't support this for now. But you can do it with some hack ways by volar (I don't recommend it).

See:
- https://github.com/johnsoncodehk/volar/discussions/143
- https://github.com/johnsoncodehk/volar/discussions/143#discussioncomment-653332
- https://github.com/vuejs/rfcs/pull/310

**Comment by chojnicki** [comment]
@johnsoncodehk  This hacky workaround will not work in my case :( Event if this cant be automatically detected it would be great to be at least able to assert type inside <template> like `v-slot="slotProps as someType"`

But thanks anyway for detailed answer!

**Comment by johnsoncodehk** [comment]
Let we wait for https://github.com/vuejs/vue-next/issues/1359 :)

**Comment by mesqueeb** [comment]
@johnsoncodehk sorry to comment on a closed issue.
However, the vueJS issue you linked was already closed, so I was hoping for some clarification.

My parent has the scope it passes to the slot typed correctly:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3253920/171073724-e0990678-b948-4f6b-bb82-2494c0ae36e8.png">

but this is still not recognised by the child:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3253920/171073629-018bbe2d-fb20-49c0-9273-c1355c55b0e5.png">

my feature request would be:
- allow for **auto-detecting the slot scope type** based on what the parent is passing into the slot scope.

Should I create a new FR issue for this?

Best regards.

**Comment by johnsoncodehk** [comment]
Hi @mesqueeb, this feature has been temporarily deprecated since v0.34.0.

See:
- #1108
- #1253

**Comment by johnsoncodehk** [comment]
Just for record, this feature is back at v0.36.0 (only for script setup): https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0360-202263
