### ISSUE TITLE
Nuxt and volar

### ISSUE THREAD

**Issue by essarn** [johnsoncodehk/volar#44]
Volar does not work with a generated nuxt project with typescript and composition api support using nuxt modules.

Getting `ts(2304)` error in the template. 
```
<template>
  <button @click="inc">{{ count }}</button>
</template>

<script setup>
import { ref } from 'vue'

export const count = ref(0)
export const inc = () => count.value++
</script>
```
Might have something to do with #37 because the project is using yarn.

**Comment by johnsoncodehk** [comment]
Hi @essarn, nuxt is base on vue 2, do you have install `@vue/runtime-dom`?

please see readme: https://github.com/johnsoncodehk/volar#using

**Comment by essarn** [comment]
Oops you are totally right, everything working now.

Thanks! 💯
