### ISSUE TITLE
Add a option to disable component auto-import

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#440]
### Discussed in https://github.com/johnsoncodehk/volar/discussions/438

<div type='discussions-op-text'>

<sup>Originally posted by **rtabulov** August 30, 2021</sup>
So in my project i have vite setup with vite-plugin-components, which injects import statements for componts in selected folder automatically. 
Can i somehow disable volar's auto-import feature i the auto-imported component is in the selected folder. 
Or maybe just disable auto-import totally?</div>

**Comment by Bobakanoosh** [comment]
This is a feature I'm interested in as well
