### ISSUE TITLE
[Proposal] Use local installed `vscode-vue-languageservice` instead of extensions embedded one

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#448]
Seems you already detect that there is a local lower/higher dependency 🤔 
Could your plugin try to use it?

<img src="https://user-images.githubusercontent.com/7195563/131840190-724b54bb-1ded-4d30-a60a-39b90897eb1b.png" width="400px"/>

We could also try to do something like VSCode is doing for TypeScript 🤔 

<img src="https://user-images.githubusercontent.com/7195563/131840320-30f5d36b-f577-4947-96a5-da144d038dbf.png" width="400px"/>

I'm fine with an option in `.vscode/settings.json`

**Comment by johnsoncodehk** [comment]
Thanks for your recommend, but already has a workaround, we can install any version in VSCode, so not considered currently.
<img width="578" alt="螢幕截圖 2021-09-03 下午3 49 21" src="https://user-images.githubusercontent.com/16279759/131970345-712d419a-2652-4ecd-8b14-1e33539f2448.png">
