### ISSUE TITLE
Crazy popover in the lower right corner

### ISSUE THREAD

**Issue by roojay520** [johnsoncodehk/volar#449]
vscode: 1.60.0
macos: 10.14.6

"vue": "^2.6.14",
"@vue/runtime-dom": "^3.1.1",

<img width="453" alt="Screenshot_2021-09-03_10-59-05" src="https://user-images.githubusercontent.com/11495164/131944611-1f0021a8-7167-4f7f-bcc3-8e008b794676.png">
<img width="917" alt="Screenshot_2021-09-03_10-58-50" src="https://user-images.githubusercontent.com/11495164/131944620-9c9d48b4-b71b-4e85-bd11-7b20fe061ecd.png">
<img width="785" alt="Screenshot_2021-09-03_11-02-21" src="https://user-images.githubusercontent.com/11495164/131944624-e4eb61ea-a0b1-4bf3-bf80-624a743e6485.png">

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?
