### ISSUE TITLE
How can I disable volar to check style block?

### ISSUE THREAD

**Issue by CarberryChai** [johnsoncodehk/volar#45]
I use `tailwindcss` and `postcss` and I don't want volar to check the style block. How can I config it ?
```js
// postcss.config.js
module.exports = {
  plugins: {
    'postcss-preset-env': {
      features: {
        'nesting-rules': true,
      },
    },
    tailwindcss: {},
    autoprefixer: {},
  },
}
```
![](https://cdn.jsdelivr.net/gh/CarberryChai/oss@master/image/FFhEzU-cD8tOa.png)

**Comment by johnsoncodehk** [comment]
Hi @CarberryChai, I don't have postcss / tailwindcss experience, I will check it today.

If you can provide a sample project will be very helpful.

**Comment by CarberryChai** [comment]
ok , You can click this [demo](https://github.com/CarberryChai/vite-demo)

**Comment by johnsoncodehk** [comment]
now support `@vue-ignore`, please try 0.19.14. for example:
```vue
<!-- @vue-ignore -->
<style scoped>
.btn-primary {
  @apply bg-blue-500 text-white border-none;
}
</style>
```

**Comment by CarberryChai** [comment]
好的，看你像国人啊？我还用英语说了老半天😂

**Comment by johnsoncodehk** [comment]
please try to use english on github, and we have a [chinese channel](https://discord.com/channels/793943652350427136/800345284320296990) on discord now.

**Comment by neilzhang618** [comment]
I encountered the same problem, but this solution(@vue-ignore) is no longer effective.

How can I disable volar to check style block? @johnsoncodehk 

I have set this config in my workspace settings.json:

```json
{
    "css.validate": false, // Disable css built-in lint
    "less.validate": false,
    "stylelint.enable": true,
}
```

**Comment by neilzhang618** [comment]
Can style block inherit the configuration of style in settings.json？

That would be very helpful, thank you.

**Comment by johnsoncodehk** [comment]
@neilzhang618 vscode css settings is not support yet, you can open a new issue to track.
