### ISSUE TITLE
Prop with the same name as a HTML tag causes incorrect error reporting

### ISSUE THREAD

**Issue by Kameecoding** [johnsoncodehk/volar#453]
using `<setup script lang="ts">`

[Defined props with name `label`](https://imgur.com/3ZZXWIz)

[Rename props label to `label`, correct report that label doesn't exist](https://imgur.com/wI2zILO)

**Comment by johnsoncodehk** [comment]
Thanks for the report! It seem 0.27.13 bug, you can use 0.27.12 for now if you are not using TS 4.4.
