### ISSUE TITLE
CSS Linting Issue

### ISSUE THREAD

**Issue by jdfwarrior** [johnsoncodehk/volar#454]
I'm traced this issue all the way back to Volar I believe. I have a project in Vue 3, using Volar 0.27.13 in VSCode 1.60.0. This project makes use of Tailwind CSS as well. With Volar enabled, I am unable to remove the CSS linting in VSCode which causes issues using Tailwind, specifically, its use of the @apply directive. I've seen multiple supposed fixes for this issue and none of them seemed to work. I had completely disabled the linting using the `css.validate` setting in VSCode. I set `css.lint.unknownAtRules` to `ignore`, I've tried using stylelint, I've tried Custom CSS Data in VSCode, all seem to fail.. until I disabled Volar. After enabling Volar again, it consistently flags at atDirective again and will not go away. 

Is there a known way to resolve this issue?

**Comment by johnsoncodehk** [comment]
CSS settings is not support yet, you can create feature request to track.

For `@apply` directive, you can use `<style lang="postcss">` to allow it.

**Comment by qgates** [comment]
This is a definite pain point for me as well. `@apply` and other directives are throwing errors, and `lang="postcss"` doesn't work as I lose coloring of the `style` section. For now the best I can find is `<style scoped lang="">` but then I lose codelens. Oh well.

Any likelihood of a fix to this? A volar option to disable validation, or better still respecting vscode's `css.validate` option would be most consistent.
