### ISSUE TITLE
template errors with recent versions for `ref` and `computed` variables

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#456]
I don't know if anyone can help me but I'm getting a lot of type errors which weren't there a few days ago (specifically it's type errors in the template for `ref` or `computed` props). I am using **pnpm** (v6.14.3) as the package manager.

1. Initially when running `pnpm ls vue-tsc` in the base of the monorepo I got nothing. This surprised me and indeed `npm ls vue-tsc` give the expected results:

    <img width="847" alt="2021-09-04_18-01-07 (2)" src="https://user-images.githubusercontent.com/980757/132111616-9aea448a-bb1d-4647-adec-c32d45a4ad75.png">

 
    This may be a red herring, but I found it odd. In any event, I install `vue-tsc` as a devDep in the root of the mono repo and am now getting this:
    
    ![image](https://user-images.githubusercontent.com/980757/132111600-5ade0334-d1d1-4f8b-98ae-189e42ce9964.png)

    This _should_ mean I'm on the latest version and I'd _not_ expect to get any more errors.

2. When starting vs-code (after step 1), I do unfortunately still get this "warning sign" from Volar:

     ![image](https://user-images.githubusercontent.com/980757/132111665-a982a99a-e969-4269-ad9c-f36f429db5b1.png)
3. Running `pnpm up --latest vue-tsc` as was suggested makes no changes I am already on the latest version but now I get tons of lint errors in the template section for `ref` and `computed` props. :( 
    
    ![image](https://user-images.githubusercontent.com/980757/132111698-ee7a369b-d831-4590-946b-e2ba0ddf3f09.png)

This all worked a few days ago. I'm now trying to isolate which version stopped working for me.

**Comment by ksnyde** [comment]
<img width="599" alt="2021-09-04_18-57-14" src="https://user-images.githubusercontent.com/980757/132112365-6228e727-8036-44c8-a259-f81aaecda59a.png">

An example ... most are just regular computed ref's, this one just happened to be a _writeable_ computed ref but neither work.

**Comment by ksnyde** [comment]
I am a bit confounded here ... as I say ... it was working up until a day or two ago (or at least my set of dependencies in vs-code) had it working but now in both **VS Code** and **Insiders Edition** I have the same issue and have gone back as far as `0.26.x` ... what could be causing this?

**Comment by johnsoncodehk** [comment]
Try reinstall node_modules, see https://github.com/johnsoncodehk/volar/issues/322.

**Comment by ksnyde** [comment]
@johnsoncodehk  yeah i did try that; that had worked for me in the past but not this time.

**Comment by ksnyde** [comment]
what is the dependency graph? How can I help in debugging this?

**Comment by johnsoncodehk** [comment]
Can you provide reproduce case?

**Comment by beetaa** [comment]
@ksnyde @johnsoncodehk Is this the same condition? 

![image](https://user-images.githubusercontent.com/5688224/132148143-555215e7-3cf3-4ecf-ad9f-0d49fe6c3ee6.png)

**Comment by johnsoncodehk** [comment]
@beetaa have you already tried solution from #322?

**Comment by beetaa** [comment]
@johnsoncodehk yes, but the tips still there. by the way, thanks so much for Volar and your good job, so quick and cool.

**Comment by johnsoncodehk** [comment]
@beetaa thank you :), and I need a repro case to check the problem.

**Comment by ksnyde** [comment]
@johnsoncodehk unfortunately the repos i'm working on are not open source and yesterday this error came as quickly as it went. If you can help me understand the dependency tree and how to interpret the error about versions of **vue-tsc** maybe I can do more leg work when this comes up again. 

Note: I still do get the **vue-tsc** warning but the template errors have gone away. So maybe they're not as connected as I assumed.

**Comment by ksnyde** [comment]
correction: the error _is_ still occurring ... my TS language server had crashed.  In  a way this makes me feel better as I hadn't changed anything.

**Comment by johnsoncodehk** [comment]
`vue-tsc` deps will not affect IDE type-checking, this is very likely to be the same problem as #322. Due to you are using monorepo, have you try delete node_modules + .lock in all sub folders?

**Comment by ksnyde** [comment]
Just got back to the frontend after several days on the backend.  Please reopen this issue. Yes i have monorepo and yes I've already taken those steps ... this does NOT sort out the issue. 

It would appear that VOLAR can parse types for reactive properties which use object indexes but not when using the `Record<T,U>` type. So for instance, a variable created in `setup()` which is typed with either notation _should_ work and _did_ work in the past:

- WORKS: `ComputedRef<{ root: string; wrapper: string; controls: string; component: string }>`
- BROKEN: `ComputedRef< Record<"root" | "wrapper" | "controls" | "component", string>`

In the broken case, everything of course _does_ work at runtime but the errors I illustrated above show up where it would appear to not be unwrapping the computed reference.

**Comment by ksnyde** [comment]
I attempted a recreation using your starter template and to my surprise both _did_ work. The code I used was the following:

```ts
export default defineComponent({
  setup() {
    const foo: ComputedRef<{ foo: string; bar: string }> = computed(() => ({
      foo: "foo",
      bar: "bar",
    }));
    const bar: ComputedRef<Record<"foo" | "bar", string>> = computed(() => ({
      foo: "foo",
      bar: "bar",
    }));

    return { foo, bar };
  },
});
```

I then cast my `style()` function which returns a computed function to an explicit type and found that there are props missing:
<img width="898" alt="2021-09-11_23-37-53" src="https://user-images.githubusercontent.com/980757/132976610-abc35d3c-c907-40b1-8fab-2e4789ef7edb.png">

That then _does_ look like the issue you were referring to before. I went into that library and updated it to the latest version of VueJS (they were both on 3.2.x but apparently the API is changing in patch versions ... or so it would appear).

**Comment by johnsoncodehk** [comment]
@ksnyde did you also solve it in the monorepo project?

**Comment by ksnyde** [comment]
I still get the warnings about being a different version of vue-tsc ... or
at least did but I disabled the warning. The bigger concern for me had been
around the inconsistent type experience but that must have come deps within
the monorepo being a different patch version of VueJS. It's working now but
still surprised that patch versions would have typing differences.

Either way, thanks for creating such a great plugin. TS fully integrated to
VueJS was always a dream and what you've enabled is very valuable to me.

**Comment by johnsoncodehk** [comment]
<img width="424" alt="螢幕截圖 2021-10-02 上午1 16 26" src="https://user-images.githubusercontent.com/16279759/135661014-aaa9d3ab-0bc2-4a0e-befe-8485d25a85cd.png">

You can click "Open package.json" to confirm your workspace vscode-vue-languageservice version, if it not same with VSCode volar version, the warning is show in expected.
