### ISSUE TITLE
Formatting vue sfc takes too long

### ISSUE THREAD

**Issue by byoungd** [johnsoncodehk/volar#457]
When use VSCode codeActionsOnSave `source.fixAll.eslint`, it takes too long to make the action (>10s) on Vue2 project.

```
正在保存“index.vue”: 从 "'Volar', 'ESLint'" (configure)中获取代码操作。
```

**Comment by IWANABETHATGUY** [comment]
you should close one of `volar` and `eslint` extension to make sure which one slow thing down.

**Comment by byoungd** [comment]
> you should close one of `volar` and `eslint` extension to make sure which one slow thing down.

I will test it. Thanks for reply!

**Comment by johnsoncodehk** [comment]
It should be ESLint, because volar ignored `source.fixAll.eslint`.
