### ISSUE TITLE
使用第三方组件ts报错

### ISSUE THREAD

**Issue by Qeney** [johnsoncodehk/volar#459]
升级vscode后，第三方组件一直提示ts类型缺失
升级之前都是好的，不知道是vs code还是volar的问题。

![WechatIMG3926](https://user-images.githubusercontent.com/85222064/132180551-d537ff03-acee-4025-8701-7760d632f025.jpeg)

**Comment by chouchoui** [comment]
Same problem with Volar v0.27.14 + ElementPlus
![Snipaste_2021-09-06_16-04-23](https://user-images.githubusercontent.com/14866249/132182441-f1b831fa-73ce-41ae-8605-d91749359e1b.png)

**Comment by Half-A-Turnip** [comment]
yes，back to 0.27.13 is good

**Comment by johnsoncodehk** [comment]
Fixed ElementPlus type-checking problem, but `ant-design-vue` components type definition incorrect.

Currently:

```ts
export declare class Button extends AntdComponent {
  static Group: typeof ButtonGroup;
  type: 'primary' | 'danger' | 'dashed' | 'ghost' | 'default';
  htmlType: 'button' | 'submit' | 'reset' | 'menu';
  icon: string;
  shape: 'circle' | 'circle-outline';
  size: 'small' | 'large' | 'default';
  loading: boolean | { delay: number };
  disabled: boolean;
  ghost: boolean;
  block: boolean;
}
```

Expected:

```ts
export declare class Button extends AntdComponent {
  static Group: typeof ButtonGroup;
  $props: {
    type?: 'primary' | 'danger' | 'dashed' | 'ghost' | 'default';
    htmlType?: 'button' | 'submit' | 'reset' | 'menu';
    icon?: string;
    shape?: 'circle' | 'circle-outline';
    size?: 'small' | 'large' | 'default';
    loading?: boolean | { delay: number };
    disabled?: boolean;
    ghost?: boolean;
    block?: boolean;
  }
}
```

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/132226623-58848799-037a-4c5c-9341-bd18a8a535da.png)

0.27.15 not find some error

**Comment by johnsoncodehk** [comment]
@tangjinzhou It seems correct? because all props are optional. What error expected?

**Comment by tangjinzhou** [comment]
> Fixed ElementPlus type-checking problem, but `ant-design-vue` components type definition incorrect.
> 
> Currently:
> 
> ```ts
> export declare class Button extends AntdComponent {
>   static Group: typeof ButtonGroup;
>   type: 'primary' | 'danger' | 'dashed' | 'ghost' | 'default';
>   htmlType: 'button' | 'submit' | 'reset' | 'menu';
>   icon: string;
>   shape: 'circle' | 'circle-outline';
>   size: 'small' | 'large' | 'default';
>   loading: boolean | { delay: number };
>   disabled: boolean;
>   ghost: boolean;
>   block: boolean;
> }
> ```
> 
> Expected:
> 
> ```ts
> export declare class Button extends AntdComponent {
>   static Group: typeof ButtonGroup;
>   $props: {
>     type?: 'primary' | 'danger' | 'dashed' | 'ghost' | 'default';
>     htmlType?: 'button' | 'submit' | 'reset' | 'menu';
>     icon?: string;
>     shape?: 'circle' | 'circle-outline';
>     size?: 'small' | 'large' | 'default';
>     loading?: boolean | { delay: number };
>     disabled?: boolean;
>     ghost?: boolean;
>     block?: boolean;
>   }
> }
> ```

why you got props not optional

**Comment by johnsoncodehk** [comment]
@tangjinzhou I got this in `node_modules/ant-design-vue/types/button/button.d.ts` from `ant-design-vue@1.7.8`:

```ts
// Project: https://github.com/vueComponent/ant-design-vue
// Definitions by: akki-jat <https://github.com/akki-jat>
// Definitions: https://github.com/vueComponent/ant-design-vue/types

import { AntdComponent } from '../component';
import { ButtonGroup } from './button-group';

export declare class Button extends AntdComponent {
  static Group: typeof ButtonGroup;

  /**
   * can be set to primary ghost dashed danger(added in 2.7) or omitted (meaning default)
   * @default 'default'
   * @type string
   */
  type: 'primary' | 'danger' | 'dashed' | 'ghost' | 'default';

  /**
   * set the original html type of button
   * @default 'button'
   * @type string
   */
  htmlType: 'button' | 'submit' | 'reset' | 'menu';

  /**
   * set the icon of button
   * @type string
   */
  icon: string;

  /**
   * can be set to circle or circle-outline or omitted
   * @type string
   */
  shape: 'circle' | 'circle-outline';

  /**
   * can be set to small large or omitted
   * @default 'default'
   * @type string
   */
  size: 'small' | 'large' | 'default';

  /**
   * set the loading status of button
   * @default false
   * @type boolean | { delay: number }
   */
  loading: boolean | { delay: number };

  /**
   * disabled state of button
   * @default false
   * @type boolean
   */
  disabled: boolean;

  /**
   * make background transparent and invert text and border colors, added in 2.7
   * @default false
   * @type boolean
   */
  ghost: boolean;

  /**
   * option to fit button width to its parent width
   * @default false
   * @type boolean
   */
  block: boolean;
}
```

**Comment by tangjinzhou** [comment]
ok  1.x for vue2.   we will not support volar for 1.x

**Comment by johnsoncodehk** [comment]
@tangjinzhou `new () => { $props }` is also vue 2 component type from [composition-api](https://github.com/vuejs/composition-api) and [vue-class-component](https://github.com/vuejs/vue-class-component), I think this is agreed component type. Anyway focus on vue 3 is fine.

**Comment by Qeney** [comment]
0.27.15 is fine
thanks

**Comment by Qeney** [comment]
0.27.15 is fine
thanks

**Comment by qieasan** [comment]
![image](https://user-images.githubusercontent.com/40800725/233528154-bcc129fe-ceb8-4274-aa66-618399226d8b.png)

Today's update vscode this problem occurs
vscode v1.77.3
Volar v1.4.0
