### ISSUE TITLE
Type checking failed on files that contain `[]` in the path

### ISSUE THREAD

**Issue by antfu** [johnsoncodehk/volar#46]
First of all, awesome work on the extension! I am really impressed to see how good it works for `<script setup>` 👍.

I am trying to use Volar on [Vitesse](https://github.com/antfu/vitesse), found a weird bug.

Type checking failed on files that contain `[]` in the path.

![image](https://user-images.githubusercontent.com/11247099/105479315-44ffa880-5cdf-11eb-9f0e-716a5f0fecb5.png)

While I renamed it out, everything works great.

![image](https://user-images.githubusercontent.com/11247099/105479443-6b254880-5cdf-11eb-8a5a-6738b0ca0ed2.png)

`[]` is used in Vitesse to serve dynamic routes params.

Guess it's related to path convention. Would love to help if you can share some hints about where could it potentially happens.

Thanks.

**Comment by johnsoncodehk** [comment]
hi @antfu, it was been fixed in 0.19.16, thanks to point this out!

**Comment by antfu** [comment]
Confirmed working. That was fast! I have switched Vitesse to use Volar. Thanks for your awesome work :)
