### ISSUE TITLE
Type Inference error in template

### ISSUE THREAD

**Issue by Darma1106** [johnsoncodehk/volar#460]
In BaseModel.vue:
```ts
interface Props {
  title: string
  width: string
  onOk: () => void
  onClose: () => void
}

const props = withDefaults(defineProps<Props>(), {
  title: 'defaultTitle',
  width: '50%'
})

```
In other file:
![onOK](https://user-images.githubusercontent.com/45746207/132278061-d432d294-9df0-4b9b-aeb8-4063f7d87d69.png)

why 'onOk' will be undefined

**Comment by johnsoncodehk** [comment]
Please make and provide a repro case by https://github.com/johnsoncodehk/volar-starter.

**Comment by johnsoncodehk** [comment]
It seems vue 3.2.0 problem by https://github.com/vuejs/vue-next/pull/3926.

**Comment by Darma1106** [comment]
> It seems vue 3.2.0 problem by [vuejs/vue-next#3926](https://github.com/vuejs/vue-next/pull/3926).

thank you, I just upgrade my dependencies and solved it.

**Comment by yotarotsukada** [comment]
The same occurred when I configured TS version as VSCode's version (4.9.0-dev.20220919).
