### ISSUE TITLE
script template Out of sync between

### ISSUE THREAD

**Issue by zhangenming** [johnsoncodehk/volar#462]
![image](https://user-images.githubusercontent.com/21235555/132298849-51c83b74-a6c2-4855-983d-17731c6fdf92.png)
**Single** click variable  activeMode ,  can't highlight activeMode in template
![image](https://user-images.githubusercontent.com/21235555/132298854-3ef37799-3083-4cec-a376-77851d02afba.png)
**Double** click variable  activeMode , also highlight activeModeElse in script

**Comment by johnsoncodehk** [comment]
Thanks for the report! But this required changes is conflict to embedded language support design, script code and template code actually in different virtual scripts, selection ranges is not easy to support cross file.

On the other hand, I'm not sure if this is the right design, because variables are different sources in script and template.

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/132603928-47fca57a-d78f-4843-aea2-4c486310dd20.png)
The API will automatically find all the variables,
Is it helpful for this need? thanks

**Comment by rodrigocfd** [comment]
> On the other hand, I'm not sure if this is the right design, because variables are different sources in script and template.

@johnsoncodehk Although technically they are different variables, for development purposes they are, effectively, the same. Highlighting simultaneously in both scripts would be **extremely** useful in large components.

Please reconsider implementing this. Thank you.

**Comment by johnsoncodehk** [comment]
@rodrigocfd Unfortunately I haven't thought of a proper way to implement it currently, use find references on each mouse click sound too much calculate.

**Comment by rodrigocfd** [comment]
Hi @johnsoncodehk, I just want to report that I updated Volar this morning and this feature is working. I consider it a _huge_ quality of life improvement.

Thank you very much for your work.
