### ISSUE TITLE
Variable usage checking for css variable injection(2)

### ISSUE THREAD

**Issue by zhangenming** [johnsoncodehk/volar#463]
Redo https://github.com/johnsoncodehk/volar/issues/335

![image](https://user-images.githubusercontent.com/21235555/132339922-8740a8f6-7ceb-4c34-b9a1-9444e8d93563.png)
![image](https://user-images.githubusercontent.com/21235555/132339928-c508403a-1bf8-4f29-8757-7192b4a57473.png)

**Comment by johnsoncodehk** [comment]
Is it valid runtime code?

**Comment by Shinigami92** [comment]
I think they is trying to use https://github.com/vuejs/rfcs/blob/master/active-rfcs/0043-sfc-style-variables.md

**Comment by zhangenming** [comment]
> Is it valid runtime code?

sorry?
They actually run correctly..
Same question with  #335
