### ISSUE TITLE
Global Directives?

### ISSUE THREAD

**Issue by Aaron-Pool** [johnsoncodehk/volar#465]
I see the note in the readme about defining global components. However, in addition to that, I have a global directive that I'm trying to setup so that volar doesn't throw an error every time it sees it. It's a css BEM helper that I used in virtually _every_ file, so it's one of the few directives that I felt justified being registered globally. Is it possible for me to configure my typescript shims for volar to allow this? I don't really care about having typescript _support_ for this directive. I'm mostly just trying to prevent volar from marking this directive as an error.

![image](https://user-images.githubusercontent.com/5634834/132403277-20f1b482-4d5f-40d4-b7b1-a069fd6ddf0e.png)

**Comment by johnsoncodehk** [comment]
GlobalDirectives interface still in https://github.com/vuejs/vue-next/pull/3399. You can use `ComponentCustomProperties` as global directives shims for now, but it will pollution component global properties.

```ts
directive.d.ts
import { FunctionDirective /* or ObjectDirective */ } from "@vue/runtime-core";

declare module 'vue' {
	export interface ComponentCustomProperties {
		vBem: FunctionDirective<HTMLElement, string>
	}
}

export { }
```

<img width="699" alt="螢幕截圖 2021-09-08 上午4 10 16" src="https://user-images.githubusercontent.com/16279759/132404774-c747c9c1-8ee6-4e03-b94c-be598a873dde.png">

---

In your case, it should not report error for unknown directives, can you provide a repro case?

**Comment by Aaron-Pool** [comment]
Yeah, I can try. Have you considered adding volar to the open VSX registry so that it's compatible with gitpod? That would make reproduction examples much easier to create.

**Comment by Aaron-Pool** [comment]
@johnsoncodehk sorry, this was my fault. I didn't install the `@vue/runtime-dom` like I was supposed to. The extension was 99% working without it, so I assumed that package wasn't necessary anymore after some of the recent vue 2 specific changes. My bad. Closing issue.

**Comment by yusufkandemir** [comment]
@johnsoncodehk Volar is currently using `GlobalComponents` for global component types, even though it's still not merged https://github.com/vuejs/core/pull/3399, which is fine and really useful. Would you be willing the use the same approach for `GlobalDirectives` so we can have a good way of doing this without waiting for the related PR to get merged and released?

**Comment by johnsoncodehk** [comment]
@yusufkandemir see https://github.com/johnsoncodehk/volar/issues/497#issuecomment-922600209
