### ISSUE TITLE
Volar doesn't follow vs code formatting rules

### ISSUE THREAD

**Issue by ERROPiX** [johnsoncodehk/volar#466]
The script tag in the Vue single file components is formatted differently than normal JS files

Is there anyway to use the buitlin vs code formatter for the script tags?

**Comment by yaegassy** [comment]
@ERROPiX Hi, Please refer to this page to change the formatter.

https://github.com/johnsoncodehk/volar/discussions/53

> Formatting tab size config & Change formatter

**Comment by ERROPiX** [comment]
@yaegassy I knew about this, but I prefer to use the built-in JS formatter of VS Code inside the script tags.

![image](https://user-images.githubusercontent.com/6576868/132425601-89dd647f-ef3e-4ece-9b9d-50f25d811742.png)

Or at least follow the same formatting rules

**Comment by yaegassy** [comment]
@ERROPiX See: <https://github.com/johnsoncodehk/volar/issues/386#issuecomment-901719457>

**Comment by johnsoncodehk** [comment]
> @yaegassy I knew about this, but I prefer to use the built-in JS formatter of VS Code inside the script tags.

We already using built-in JS formatter of VS Code inside the script tags, describe what are you expected and what actual you got?

**Comment by yaegassy** [comment]
@johnsoncodehk  Oh, sorry... I made the wrong comment. https://github.com/johnsoncodehk/volar/blob/master/packages/server/src/tsConfigs.ts#L10-L40

**Comment by johnsoncodehk** [comment]
@yaegassy no, thanks for help!

**Comment by ERROPiX** [comment]
@johnsoncodehk thank you for the confirmation, but still the rules are not respected.
* javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis set to **true**
* javascript.format.semicolons set to **insert**

Example JS code
```js
const log = ( message) => {
    console.log(message )
}

log("message")
```

When formatted as JS file, we get spaces inserted in parentheses and semicolons added to expressions.

```js
const log = ( message ) => {
    console.log( message );
};

log( "message" );
```
But, when formatted in vue files, all spaces in parentheses are removed, and semicolons not added to expressions

```html
<script setup>
const log = (message) => {
    console.log(message)
}

log("message")
</script>
```

**Comment by mariusa** [comment]
How can one specify in Volar that prettyhtml should use `options.wrapAttributes: true` ?
I don't have prettyhtml installed.
It would be great to use VSCode HTML formatter and the settings it already has. Why reinvent the wheel?
