### ISSUE TITLE
v-for strips private fields from type, causes type errors when trying to pass into a property

### ISSUE THREAD

**Issue by protango** [johnsoncodehk/volar#476]
Consider this example:
**App.vue:**
```vue
<script setup lang="ts">
  import { ref } from 'vue';
  import MyComponent from './component.vue'
  
  export class TestClass {
    private privateField = "";
    public publicField = "";
  }
  
  const objects = ref<TestClass[]>([]);
</script>

<template>
  <MyComponent v-for="obj in objects" :key="obj.publicField" :test-prop="obj" />
  <!--                                                        ^^^ This will error -->
</template>
```

**component.vue:**
```vue
<script setup lang="ts">
  import { TestClass } from './App.vue';
  defineProps<{ 
    testProp: TestClass
  }>();
</script>
<template>
</template>
```

In `App.vue`, the inferred type of `obj` in the `v-for` clause will be `{publicField: string}`, which is not compatible with the definition for `TestClass` as this requires the additional private field. Hence, when you try and use `obj` as a parameter to `test-prop`, it fails and complains about the missing field `privateField`, even though it should actually be there.
![image](https://user-images.githubusercontent.com/31492239/132820849-a896e3df-5b91-4e03-a0ee-905a6cdba1b5.png)
![image](https://user-images.githubusercontent.com/31492239/132820868-fee2ebc9-4810-43f2-963a-373b197df465.png)

This problem also occurs in `vue-tsc`:
![image](https://user-images.githubusercontent.com/31492239/132820934-9751d3c1-04bc-4b33-81e3-e85d73b75d12.png)

A reproduction repo is available here:
https://github.com/protango/volar-v-for-issue-demo

**Comment by johnsoncodehk** [comment]
Thanks for the report! Private fields strips by `ref()`, please forward this problem to vue-next repo.

<img width="260" alt="螢幕截圖 2021-09-11 上午11 44 25" src="https://user-images.githubusercontent.com/16279759/132935307-138c31a2-2b3e-4e1b-8f43-819484706294.png">
