### ISSUE TITLE
Add custom formatter for each block, like vetur does

### ISSUE THREAD

**Issue by shawn-yee** [johnsoncodehk/volar#478]
"vetur.format.defaultFormatter.scss": "prettier"
...
template, style, script, i18n,config

**Comment by johnsoncodehk** [comment]
Out of scope, see https://github.com/johnsoncodehk/volar/issues/386#issuecomment-901719457, https://github.com/johnsoncodehk/volar/discussions/444#discussioncomment-1263519.

**Comment by johnsoncodehk** [comment]
You could use https://github.com/johnsoncodehk/volar-plugins after v0.34.
