### ISSUE TITLE
<style lang="stylus">, the collapse and formatting features are missing

### ISSUE THREAD

**Issue by shawn-yee** [johnsoncodehk/volar#480]
1.The vscode folding strategy is denpend on curly braces || indentation,
volar currently doesn't have any code folding for stylus block.
If I set indent folding strategy, the code at the top level of vue file will not collapse.
<img width="875" alt="截屏2021-09-11 下午2 11 52" src="https://user-images.githubusercontent.com/66560386/132938401-a9641956-a8f0-4165-a946-8c362bd66b98.png">

2.The stylus formatting plugin currently only this, prettier does not.
https://marketplace.visualstudio.com/items?itemName=thisismanta.stylus-supremacy&ssr=false#review-details
![Jietu20210911-140818@2x](https://user-images.githubusercontent.com/66560386/132938504-61a518cf-2638-4193-aeec-200597d65a2e.jpg)

**Comment by shawn-yee** [comment]
Taking a look at the stylus language project, it seems that its contributors are dropping the project, so I closed this issue.

**Comment by qnp** [comment]
Hi @shawn-yee, where did you find that the contributors are dropping stylus project ?
I could not access that information.

**Comment by shawn-yee** [comment]
@qnp https://github.com/stylus/stylus/issues/2282

**Comment by shawn-yee** [comment]
@qnp https://github.com/stylus/stylus/issues/2282

**Comment by qnp** [comment]
Meanwhile, I have written a very small vscode extension just for formatting .vue SFC files, where `prettier` (alongside `@prettier/plugin-pug` for pug templates) is used for `<template>` and `<script>` formatting, while `stylus-supremacy` handles the formatting of the `<style lang="stylus">` block, If it can help you :
https://marketplace.visualstudio.com/items?itemName=ekqnp.prettylus

**Comment by shawn-yee** [comment]
@qnp I used to be a big fan of pug and stylus, but the indentation-based language was very challenging when it came to copying, pasting and refactoring, so I eventually gave up, but thank you for the plugin, which is helpful to a lot of people.

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1244#issuecomment-1112857885.
