### ISSUE TITLE
volar does not autocomplete

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#481]
hello i just use volar with script setup sfc. it is very good and works well with vue. but one thing that does not work is the auto complete of quote, parentheses, bracket, etc.

what i mean is when i type `{` it supposed to auto close the bracket so the result will automatically be `{}` but right now i need to do it manually which is very annoying. is there anyway to fix this?
thankyou.

**Comment by johnsoncodehk** [comment]
It's supported, try run `Preferences: Open Settings (JSON)`, `Preferences: Open Workspace Settings (JSON)` commands and clear all settings. If the problem persists, try disable all other extensions.
