### ISSUE TITLE
Built-in Component name color

### ISSUE THREAD

**Issue by Zenthae** [johnsoncodehk/volar#482]
Hello 👋,

The built-in component `component` syntax highlighting is wrong.

![image](https://user-images.githubusercontent.com/32647899/132992237-2a10a4d9-7893-478b-b0e3-3447bf6ca3b6.png)

![image](https://user-images.githubusercontent.com/32647899/132992217-d2b6fcde-bcbd-408c-a7a5-914556b28169.png)

Volar: `0.27.18`
VSCode : `1.60`

**Comment by johnsoncodehk** [comment]
Hi @Zenthae, vue only provide these built-in type but no `<component>`: https://github.com/johnsoncodehk/volar/blob/34318d21e78d7688f3411b3fd8e5e5cd7cb4fbc5/packages/vscode-vue-languageservice/src/utils/globalDoc.ts#L44-L48

If color is a problem to you, you can define `component` to GlobalComponents interface to patch the problem, see https://github.com/johnsoncodehk/volar#using.

```ts
// components.d.ts
declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		component: (props: { is: Component }) => void
	}
}

export { }
```

**Comment by Shinigami92** [comment]
But shouldn't this be fix in Vue itself?

**Comment by johnsoncodehk** [comment]
> But shouldn't this be fix in Vue itself?

These types is not a purpose for IDE type-checking, I just stole it for now.
I think this problem should be resolve by https://github.com/vuejs/vue-next/pull/3399.
