### ISSUE TITLE
Request textDocument/codeLens failed

### ISSUE THREAD

**Issue by huangd-d** [johnsoncodehk/volar#484]
vscode about:
  Version: 1.60.0 (system setup)
  Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
  Date: 2021-09-01T10:41:52.311Z
  Electron: 13.1.8
  Chrome: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Windows_NT x64 10.0.19042;

 @vue/cli: 4.5.13;

package.json:
   "dependencies": {
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "vue": "^3.2.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "less": "^4.0.0",
    "less-loader": "^7.0.0"
  },

 abnormal:  
    When I click in the SFC .vue file; Vscode prompt "A request has failed. See the output for more information";and then I click "Go to output"; I see "Request textDocument/codeLens failed. Message: Request textDocument/codeLens failed with message: Cannot read property 'fileNames' of undefined. Code: -32603";
   
I tried uninstalling and reinstalling several times, but I couldn't close this error.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by huangd-d** [comment]
> Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

I'll try to see if other plug-ins have affected it tonight.

**Comment by ChenWeihua123** [comment]
i have the same problem

![image](https://user-images.githubusercontent.com/33150900/145502441-131f5968-2b68-421b-9cf2-91b3d3bf1adf.png)
