### ISSUE TITLE
Some completions don't work in Neovim after and before 2.1.4

### ISSUE THREAD

**Issue by exzolink** [johnsoncodehk/volar#4847]
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

-

### Vue version

3.3.10

### TypeScript version

5.5.4

### System Info

```shell
Windows 10
Neovim 0.10
```

### package.json dependencies

```json
"dependencies": {
    "vue": "^3.3.10"
  },
  "devDependencies": {
    "@mdi/font": "^7.3.67",
    "@rushstack/eslint-patch": "^1.3.3",
    "@vitejs/plugin-vue": "^4.5.1",
    "@vue/eslint-config-prettier": "^8.0.0",
    "@vue/test-utils": "^2.4.3",
    "amfe-flexible": "^2.2.1",
    "axios": "^1.6.2",
    "eslint": "^8.49.0",
    "eslint-plugin-vue": "^9.17.0",
    "jsdom": "^23.0.1",
    "postcss-pxtorem": "^6.0.0",
    "prettier": "^3.0.3",
    "sass": "^1.69.5",
    "vite": "^5.0.5",
    "vite-plugin-vuetify": "^2.0.1",
    "vitest": "^1.0.1",
    "vue-router": "^4.2.5",
    "vuetify": "^3.5.0"
  }
```

### Steps to reproduce

Just updated from 2.1.4 to 2.1.6 (before 2.1.4 dont work too)

### What is expected?

Show completions like in 2.1.4

### What is actually happening?

Completions for props, events, binds, and emits stopped working both before and after version 2.1.4.

2.1.6
![Screenshot_1](https://github.com/user-attachments/assets/2f6d1e9a-31f3-47d2-83bd-5c44ed1d18f7)
![Screenshot_2](https://github.com/user-attachments/assets/d9d1bdc0-3c93-4bb4-b9d9-d2e8875c1ff2)

2.1.4
![Screenshot_3](https://github.com/user-attachments/assets/295ce06f-55ee-4545-8197-2389f7267fd5)
![Screenshot_4](https://github.com/user-attachments/assets/27673de8-0701-41da-8371-98da2e4cc6b9)

**Comment by RayGuo-ergou** [comment]
Working for me in 2.1.6, could you share a minimal reproduction?
![image](https://github.com/user-attachments/assets/069c9753-df7e-4db3-95ec-c33381507395)
![image](https://github.com/user-attachments/assets/192250ac-920e-4232-8a7f-86fe2467d403)
![image](https://github.com/user-attachments/assets/0dc4ab61-c0c7-41d6-aa26-dc6f3bc477b3)

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/user-attachments/assets/e0468c99-2ccb-4ea9-8181-e9c5dc404884)
Tried with your dotfile, definitely something about your nvim config caused this issue.

**Comment by exzolink** [comment]
Weird, 2.1.4 works perfectly with this config

**Comment by RayGuo-ergou** [comment]
what's your neovim version, can you try with nightly? Possible upstream change ( LSP itself )

**Comment by johnsoncodehk** [comment]
My intuition is that this is caused by the inconsistent version of `@vue/langugae-server` and `@vue/typescript-plugin`.

**Comment by exzolink** [comment]
> My intuition is that this is caused by the inconsistent version of `@vue/langugae-server` and `@vue/typescript-plugin`.

Which inside @vue/language-server? Its 2.1.6 too

![Screenshot_1](https://github.com/user-attachments/assets/3c602901-071a-4458-b7ae-f28dc4b26f99)

**Comment by RayGuo-ergou** [comment]
> My intuition is that this is caused by the inconsistent version of @vue/langugae-server and @vue/typescript-plugin.


It should be the same, as in the config the plugin path references to `@vue/language-server`

I kinda reproduced this when tsserver has not loaded yet. Can you check with `LspInfo` see if ts_ls or vtsls still attached and with `LspLog` see if any error with tsserver?

**Comment by exzolink** [comment]
I don't see any errors in the LspLog.

![Screenshot_1](https://github.com/user-attachments/assets/b3e0e44d-5d60-4c8e-be27-126a3d209768)

**Comment by exzolink** [comment]
I've figured out what the issue was.
vtsls was using the tsserver from the current project, which had typescript 4.9. After updating it to 5.6.2, the problem disappeared. 
Sorry for the confusion, i had assumed vtsls was using the version from mason.

Suppose I need to explicitly set the tsdk in vtsls?

**Comment by RayGuo-ergou** [comment]
Aha, glad you figured that out I am actually testing things with your vue repo and because I also have auto use workspace tsdk thus my config also have the same issue.

You can just disable it in here: https://github.com/exzolink/dotfiles/blob/main/nvim/lua/configs/lsp/servers/typescript.lua#L39

If you still want to keep this seeting,  vtsls provide a code action to select typerscript version to use.https://github.com/yioneko/vtsls?tab=readme-ov-file#commands

You can either call neovim api to invoke the code action or use https://github.com/yioneko/nvim-vtsls

**Comment by exzolink** [comment]
Got it, thank you very much for your help!
