### ISSUE TITLE
no-unused-components Error in tsx

### ISSUE THREAD

**Issue by Qeney** [johnsoncodehk/volar#485]
vue 3.2
volar 0.27.19
antd-vue 2.2.6

The "Button" component has been registered but not used.eslintvue/no-unused-components

<img width="700" alt="87DCF59C-4C89-4450-AB9B-34D763435649" src="https://user-images.githubusercontent.com/85222064/133056469-c1227de7-36eb-4587-b3aa-bc2a7fa850a0.png">

<img width="723" alt="0EFEF6A0-D5F3-4B72-8DCB-9EB741818C44" src="https://user-images.githubusercontent.com/85222064/133056667-82be2ddd-4398-4a7f-9997-24da9ea11b87.png">

**Comment by Qeney** [comment]
<img width="673" alt="0E803882-37CD-4219-B680-2193DB270A81" src="https://user-images.githubusercontent.com/85222064/133057080-07a27943-a00d-4eba-bf30-356e862c5d6b.png">

**Comment by johnsoncodehk** [comment]
This message comes from ESLint not Volar.
