### ISSUE TITLE
Neovim lsp integration

### ISSUE THREAD

**Issue by DvrDania** [johnsoncodehk/volar#488]
I installed @volar/server globally and enabled the server in my config, but it seems to be returning Null?

**Comment by yaegassy** [comment]
I have tried it in my environment and there is no problem. Is your Vue project TS or JS?

Neovim buitlin LSP seems to require the `typescript` package to be installed if the project is JS.

If the problem is specific to `nvim-lspconfig`, please report the issue to `nvim-lspconfig`.

@3nuc ping

**Comment by DvrDania** [comment]
My project setup is Vue 3 , TS, Vite
I've installed TS globally and I have tsserver lsp working
Can you share your config files? @yaegassy

**Comment by yaegassy** [comment]
Please refer to `nvim-lspconfig` and try to configure it for your environment! https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/volar.lua

If you are using `nvim-lspconfig`, this should work by itself.

```vim
lua << EOF
require'lspconfig'.volar.setup{}
EOF
```

<img width="713" alt="nvim-lsp-volar" src="https://user-images.githubusercontent.com/188642/133244543-05889b86-0732-4a83-bc14-cd15634342ef.png">

**Comment by 3nuc** [comment]
Let's track this in https://github.com/neovim/nvim-lspconfig/issues/1261, I doubt it's volar related

**Comment by DvrDania** [comment]
> Let's track this in [neovim/nvim-lspconfig#1261](https://github.com/neovim/nvim-lspconfig/issues/1261), I doubt it's volar related

Sure, I think so too
