### ISSUE TITLE
Adding ComponentCustomProperties breaks template type checking,

### ISSUE THREAD

**Issue by Spittal** [johnsoncodehk/volar#491]
I'm using `vue-i18n` v9, which includes an option to inject `$t` globally. You can see the options injected here: https://vue-i18n.intlify.dev/api/injection.html#componentcustomproperties

However when I've included `globalInjection: true` I still get an error that `$t` is not found within the template
![image](https://user-images.githubusercontent.com/1229177/133302988-6c014fed-d376-4f83-8826-34f61168b00b.png)

This should be no issue as I know I can use a `d.ts` file and add a `ComponentCustomProperties`.

```
// src/vue-i18n.d.ts
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $t: SomeType
  }
}
```

However when I do ☝️ everything breaks...

First problem is that $t has already been declared:
![image](https://user-images.githubusercontent.com/1229177/133303500-e04281ff-1d94-4e0a-95ed-f4964aac61c2.png)
You can see that here in vue-i18n https://github.com/intlify/vue-i18n-next/blob/ffcc6ada102d1151538bf4943b8f4b83d64c7960/packages/vue-i18n/src/vue.d.ts

Second problem is that it seems to overwrite the types from vue itself:
![image](https://user-images.githubusercontent.com/1229177/133303770-f99971c7-d13a-4322-a38a-ab42035d426e.png)

Am I adding the custom property incorrectly?

**Comment by johnsoncodehk** [comment]
> First problem is that $t has already been declared:
> ![image](https://user-images.githubusercontent.com/1229177/133303500-e04281ff-1d94-4e0a-95ed-f4964aac61c2.png)
> You can see that here in vue-i18n https://github.com/intlify/vue-i18n-next/blob/ffcc6ada102d1151538bf4943b8f4b83d64c7960/packages/vue-i18n/src/vue.d.ts

You don't need to define `$t` if library already define it.

> Second problem is that it seems to overwrite the types from vue itself:
> ![image](https://user-images.githubusercontent.com/1229177/133303770-f99971c7-d13a-4322-a38a-ab42035d426e.png)

Try add `export { }` to `src/vue-i18n.d.ts`.

**Comment by Spittal** [comment]
Hey @johnsoncodehk it seems like your suggestions are mutually exclusive. If I don't need to redefine `$t` then I shouldn't have to export anything from the file because it's no longer necessary. 

So I guess my question now is why `$t` isn't being recognized in the templates if it's being defined by `vue-i18n` as seen here: https://github.com/intlify/vue-i18n-next/blob/ffcc6ada102d1151538bf4943b8f4b83d64c7960/packages/vue-i18n/src/vue.d.ts?

**Comment by johnsoncodehk** [comment]
It's works for me. Do you have any `vue-18n` imports in any *.ts file? If you don't have it, you need to add `vue-i18n` to tsconfig's `compilerOptions.types` option.

**Comment by Spittal** [comment]
Hey @johnsoncodehk I created a little reproduction here: https://github.com/Spittal/i18n-reproduction

It seems like it could be Yarn's PNP mode, as as soon as I switched to that I got the error. This is odd because I've never had type issues using PNP before.

**Comment by johnsoncodehk** [comment]
emmm sorry I can't help with yarn pnp :/
