### ISSUE TITLE
Vscode SCSS and CSS lint setting support

### ISSUE THREAD

**Issue by kadiryazici** [johnsoncodehk/volar#492]
Title describes everything :D

![image](https://user-images.githubusercontent.com/47540799/133325218-2ad15d1d-0dc3-49cb-96ed-1f0a7f6dda4d.png)

**Comment by qgates** [comment]
Closed issues #454 #78 #69 (and probably a few more) all indicate this issue as well, and some of the suggested workarounds eg. `lang="postcss"` and '@vue-ignore` don't work presently.

Setting `script lang=""` is the only workaround I cam find but that disables codelens and other features.

This along with TS checking in the template (not supported by the vue template compiler at least for now) are the biggest pain points for me.

Be nice to have a few configs to selectively disable these things and also for volar to respect `css.lint.unknownAtRules` etc.

**Comment by qgates** [comment]
Thank you for fixing @johnsoncodehk 👍

**Comment by Boris-Karamanolev** [comment]
How was this fixed? How can I disable CSS formatting with Volar?

**Comment by johnsoncodehk** [comment]
@Boris-Karamanolev `"css.format.enable": false`
