### ISSUE TITLE
Reload extension host instead of the window on plugin installation

### ISSUE THREAD

**Issue by antfu** [johnsoncodehk/volar#496]
Just an idea, I thought this command would be enough to make the plugin working without being too distractive.

![image](https://user-images.githubusercontent.com/11247099/133530563-b37f4ba9-1700-4b97-a268-adac833c8a53.png)

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion! But it resolve by https://github.com/johnsoncodehk/volar/issues/501, we no longer need to reload for TS plugin in the next version. :)
