### ISSUE TITLE
Support built-in directive like "v-show"

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#497]
Currently it seems Volar doesn't support v-show directive. Could we have this supported? 🥇

**Comment by oliverzy** [comment]
I realize that it can implemented by myself, thanks.
```
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Component: (props: { is: Component | string }) => void;
  }

  export interface ComponentCustomProperties {
    vShow: typeof vShow;
  }
}```

**Comment by johnsoncodehk** [comment]
This will leak the vShow variable into the template context, but yes this is not a big problem.

Global directives interface will be supported by https://github.com/vuejs/vue-next/pull/3399. Built-in directives like `v-show`, `v-html` will get built-in support.

**Comment by ShenQingchuan** [comment]
> I realize that it can implemented by myself, thanks.
> 
> ```
> declare module '@vue/runtime-core' {
>   export interface GlobalComponents {
>     Component: (props: { is: Component | string }) => void;
>   }
> 
>   export interface ComponentCustomProperties {
>     vShow: typeof vShow;
>   }
> }```
> ```

I found that I must use `pnpm install --shamefully-hoist` to put all the packages under `node_modules` folder so that VSCode could recognize `@vue/runtime-core`

Does this issue and its relative issues or PRs have any updates ? @johnsoncodehk
