### ISSUE TITLE
Not support <T> syntax, "as T" will ok

### ISSUE THREAD

**Issue by heng1025** [johnsoncodehk/volar#498]
![image](https://user-images.githubusercontent.com/17466991/133582209-b2e3e5b8-48de-4e47-aa90-8d3de31c35a7.png)

**Comment by Shinigami92** [comment]
I think this is a limitation of TSX itself and not Volar.
Please use `as HTMLDivElement` here.

**Comment by heng1025** [comment]
> I think this is a limitation of TSX itself and not Volar.
> Please use `as HTMLDivElement` here.
Yes,thx. [referrence](https://www.typescriptlang.org/docs/handbook/jsx.html)
