### ISSUE TITLE
Pug class literal support

### ISSUE THREAD

**Issue by gedzeppelin** [johnsoncodehk/volar#50]
Hello, first of all I'm using this extension for about 3 weeks and feels really nice!

I found this strange behavior when using CSS classes on pug elements, basically in some scenarios the fact of using a CSS class on any element between a variable declaration with v-for makes the variable to no longer be recognized.

![1](https://user-images.githubusercontent.com/36518098/106234047-f0b86500-61c5-11eb-8353-bd99a68dbfe4.png)

The first reference of _lang_ variable throws no error when the first span has no classes.

![3](https://user-images.githubusercontent.com/36518098/106234207-53a9fc00-61c6-11eb-87a9-9630d1e55780.png)

The first reference of _lang_ variable throws no error when is used in the first element that has classes afer the v-for declaration.

![2](https://user-images.githubusercontent.com/36518098/106234105-0f1e6080-61c6-11eb-82b3-bf8b097fb754.png)

when there is no classes at all it works as expected.

![4](https://user-images.githubusercontent.com/36518098/106234320-a2f02c80-61c6-11eb-9628-86865168d9c1.png)

Thanks in advance.

**Comment by johnsoncodehk** [comment]
hi @gedzeppelin, thanks for your report :).

currently not support [pug class literal](https://pugjs.org/language/attributes.html#class-literal), you need to change `tag.className(...)` to `tag(class="className" ...)`, you can use pug-html convert tool to quick convert (click `html ☐`, and than click `pug ☐`).

it will support by `vscode-pug-languageservice`, please track https://github.com/johnsoncodehk/volar/projects/1#card-50201163

**Comment by johnsoncodehk** [comment]
implemented in 0.20.6. has many code changed, please let me know if your see any problem.
