### ISSUE TITLE
try to add some e2e-test

### ISSUE THREAD

**Issue by IWANABETHATGUY** [johnsoncodehk/volar#51]
Aiming to make a production ready vue vscode-extension, It's necessary add some test, like `vetur`

**Comment by johnsoncodehk** [comment]
I want to add unit tests for `vscode-vue-languageservice` as replacement, because:

- `vscode-vue-languageservice` will publish to npm as a module, unit-test is necessary.
- in future we will have multiple IDE support, e2e-test for each IDE is too much work.
- e2e-test very slow. :P

**Comment by johnsoncodehk** [comment]
Implement in: https://github.com/johnsoncodehk/volar/pull/55
