### ISSUE TITLE
No `.ts` file language features in takeover mode

### ISSUE THREAD

**Issue by Delerme** [johnsoncodehk/volar#511]
I switched over to takeover mode as recommended, but there is no intellisense or other language features in standard `.ts` files. [This discussion](https://github.com/johnsoncodehk/volar/discussions/471#discussioncomment-1354909) suggests `.ts` files should work normally after opening a Vue file.

Current plugin list:
- Volar (language features)
- ESLint
- Stylelint
- Live Share

Using vscode remote ssh

**Comment by sibbng** [comment]
I have the same issue. I'm working on [VueUse](https://github.com/vueuse/vueuse) code base.

Intellisense working at the composables in packages folder but on [scripts folder](https://github.com/vueuse/vueuse/tree/main/scripts) only working in `utils.ts`.

VS Code Version: 1.60.1
OS: Windows 10

**Comment by johnsoncodehk** [comment]
It seems that Volar's tsconfig project finding logic is different from typescript builtin extension, you can try add `scripts` to tsconfig include option to resolve for now.
