### ISSUE TITLE
rollover an emit in <template> shows me the type is "unknown"

### ISSUE THREAD

**Issue by andylix** [johnsoncodehk/volar#515]
I have something like this:
`<MyButton @add-something="addSomething"></MyButton>`

This `add-something` event has been defined in MyButton with defineEmits.

A month ago, when I rollover on `@add-something`, it will show me that its type is `(property) 'add-something': (param: number) => void`, which is accurate.

Now, after updating the plugin to the latest version 0.27.23 (plugin logo image is gone too), rollover on `@add-something` shows me `(property) 'add-something': unknown`.

v0.27.22 is the first version that's giving me 'unknown'.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter ?

**Comment by andylix** [comment]
https://github.com/andylix/volar-emit-type-unknown

Basically, `add` would work, but `add-something` wouldn't work, the hyphen is the problem.
