### ISSUE TITLE
Support stylelint.

### ISSUE THREAD

**Issue by myWsq** [johnsoncodehk/volar#52]
I don't know if I'm doing it the wrong way, but I've disabled css validation in the workspace settings. How should I switch the default css validation to stylelint?

<img width="575" alt="image" src="https://user-images.githubusercontent.com/35214490/106631779-0cea4680-65b8-11eb-837c-9c31c171b065.png">

<img width="224" alt="image" src="https://user-images.githubusercontent.com/35214490/106631801-11aefa80-65b8-11eb-8316-6564a889e9f9.png">

**Comment by johnsoncodehk** [comment]
stylelint may be support when I have time.

you can use `@vue-ignore` to disable a vue block checking, see: https://github.com/johnsoncodehk/volar/issues/45#issuecomment-761765256
