### ISSUE TITLE
Class string color scopes incorrect when v-model contains TS "as" cast

### ISSUE THREAD

**Issue by qgates** [johnsoncodehk/volar#520]
Example:

```vue
<textarea
  v-model="var as string"
  class="fld-module h-full resize-none">
...
```

Class string is assigned incorrect scopes `meta.namespace.declaration.ts` and `source.ts.embedded.html.vue` etc..

The order of attributes seems to make no difference. Workarounds:
- bracket the entire v-model expression eg. `v-model="(var as string)"`
- use angle bracket casting instead, eg. `v-model="<string>var"`

How it appears (using tomorrow night theme):

![image](https://user-images.githubusercontent.com/4213509/134498940-533e5fbf-67c5-4bd6-bd8e-9f4d5855f9b7.png)

How it should appear:

![image](https://user-images.githubusercontent.com/4213509/134499583-432b30a9-f3c7-4db6-975f-4db88f0c151e.png)

**Comment by johnsoncodehk** [comment]
This problem similar to #112, it's embed language syntax issue, we can't fix, you need to use `()` to catch it.

**Comment by qgates** [comment]
@johnsoncodehk which upstream package is responsible for this issue?

**Comment by johnsoncodehk** [comment]
This: https://github.com/microsoft/TypeScript-TmLanguage

**Comment by mesqueeb** [comment]
@johnsoncodehk adding round parentheses fixes it. It might be interesting for volar to auto-add those inside templates.

**Comment by johnsoncodehk** [comment]
@mesqueeb you can open a FR, but there is not necessarily a way to do it.

**Comment by douira** [comment]
What issue in https://github.com/microsoft/TypeScript-TmLanguage is the upstream issue for this? It doesn't make sense to have this closed without notifying the upstream repo to fix it.

**Comment by Mettbrot** [comment]
Marking any issue as duplicate of this one yet closing it without a proper path to get it fixed is kind of frustrating. How can we further track this issue, maybe over at microsoft/TypeScript-TmLanguage ?

**Comment by johnsoncodehk** [comment]
@matthew-dean Even in `.ts` files, problems can occur when writing syntax equivalent to the original topic.

<img width="413" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/0724e348-54dc-45d6-be78-04c8014180e1">

This is the code where we embed the ts syntax, you can try investigating:

https://github.com/vuejs/language-tools/blob/ffa590af35b0d6aa838dbb47b0eeda27da0a1422/extensions/vscode/syntaxes/vue.tmLanguage.json#L1042

I don't think upstream has a chance to fix it, it's more like a design limitation of the embedded language syntax highlight.

**Comment by johnsoncodehk** [comment]
Anyway this can't be fixed in this repo, but I just suggested a possible fix at https://github.com/microsoft/TypeScript-TmLanguage/issues/985#issuecomment-2127996567.

**Comment by spector32** [comment]
Related: https://github.com/prettier/prettier/issues/15201
