### ISSUE TITLE
Types for "ref sugar (take 2)" not available

### ISSUE THREAD

**Issue by akaufmann** [johnsoncodehk/volar#521]
(Possibly) Since the change from `script.refSugar` to `refTransform`, TS complains that the ref sugar (take 2) is unknown. The complaint only occurs in VSC, the bundle runs without errors in the browser. 

![Bildschirmfoto 2021-09-23 um 16 32 21](https://user-images.githubusercontent.com/288499/134529224-a9cff38f-bb36-4047-bbb5-df36024ef9f7.png)

PS:  Not sure if the type export is missing in Volar or Vue itself.

```shell
"volar": "0.27.24"
"vue": "3.2.16"
"@vue/compiler-sfc": "3.2.16"
"typescript": "^4.4.3",
"vite": "2.6.0-beta.2",
```

**Comment by johnsoncodehk** [comment]
You need to config tsconfig types. See https://github.com/vuejs/rfcs/blob/ref-sugar-2/active-rfcs/0000-ref-sugar.md#typescript--tooling-integration.

```
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": ["vue/ref-macros"]
  },
}
```

**Comment by akaufmann** [comment]
I missed that. Thanks @johnsoncodehk for the hint!

**Comment by kfields** [comment]
@johnsoncodehk solution worked until I just rebooted my machine and Visual Studio Code updated.
Now it's back to red squiggles and `Cannot find name '$ref'.ts(2304)`
I noticed they call it reactivityTransform  instead of refTransform now

**Comment by CharlesOkwuagwu** [comment]
the problem remains un fixed

**Comment by CharlesOkwuagwu** [comment]
> @johnsoncodehk solution worked until I just rebooted my machine and Visual Studio Code updated. Now it's back to red squiggles and `Cannot find name '$ref'.ts(2304)` I noticed they call it reactivityTransform instead of refTransform now

@kfields Please did you eventually get a fix for this?
