### ISSUE TITLE
file watcher improve

### ISSUE THREAD

**Issue by kikyous** [johnsoncodehk/volar#523]
yesterday I found change vs code settings to use fs events can stop volar polling fs files.
```json
"typescript.tsserver.watchOptions": {
    "watchDirectory": "useFsEvents",
    "watchFile": "useFsEvents",
    "useFsEvents": true,
    "usePolling": false
}
```
https://github.com/johnsoncodehk/volar/issues/507#issuecomment-925625137

But it seems not work when I restart vscode.

I don't  know much about lsp, but from https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#implementing-a-language-server, there is some built in event we can use (maybe):
```
connection.onDidChangeWatchedFiles(_change => {
  // Monitored files have change in VS Code
  connection.console.log('We received a file change event');
});
```
Vetur use this event too: 
https://github.com/vuejs/vetur/blob/HEAD/server/src/services/vls.ts#L474

Can volar use this ?

**Comment by johnsoncodehk** [comment]
Yes we can try this.

**Comment by kikyous** [comment]
I found some issues in vetur maybe useful to you.
https://github.com/vuejs/vetur/issues/355
https://github.com/vuejs/vetur/commit/6ef21326609cd1562709477b683726a8f2e0a2eb
