### ISSUE TITLE
"Go to Definition" in SFC is broken in Yarn 2 PnP Project.

### ISSUE THREAD

**Issue by miaulightouch** [johnsoncodehk/volar#524]
![image](https://user-images.githubusercontent.com/5199594/134635881-7b99deb4-2bcc-4145-8c9e-e1801fd07ece.png)

[demo repo](https://github.com/miaulightouch/volar-issue01)

1. install [ZipFS extension](https://marketplace.visualstudio.com/items?itemName=arcanis.vscode-zipfs)
2. press F1 and set typescript version to workspace version, both volar and typescript.
2. open `src/App.vue`
3. right click on `union` function and click "Go to Definition" and error pop up.

It would have no issue if it's in .ts file.

**Comment by merceyz** [comment]
For context:
We (Yarn) create a local TypeScript server file that adds the `zip:` protocol to the file paths that passes through `tsserver.server.Session` which allows the ZipFS extension to provide the content of the files and works perfectly fine with the default TypeScript server.
https://github.com/yarnpkg/berry/blob/2a421a616281cacfb4280e5c94fd643934148372/.yarn/sdks/typescript/lib/tsserverlibrary.js#L133-L160

It seems Volar doesn't use that patched `Session` but, like I mentioned in https://github.com/johnsoncodehk/volar/issues/248#issuecomment-864375594, I couldn't figure out where we would need to make changes for go to definition to work with Volar, @johnsoncodehk do you have any pointers?

**Comment by johnsoncodehk** [comment]
@merceyz volar don't use TS server, it call TS api direct, so I think this patch don't working for volar.
Does Angular support this?

**Comment by johnsoncodehk** [comment]
Close because this is not volar side problem.
If Angular support it please let me know, volar may have some way to support too by reference to Angular.
