### ISSUE TITLE
Extension consumes memory more then expected on code-server instance

### ISSUE THREAD

**Issue by LittleSound** [johnsoncodehk/volar#531]
## description

I was using the code-server instance on a virtual machine running on cloud, it caused **out of memory** issue two times in the past 3 days, during this time, code-server host will never be reached again until the memory free out. I was experiencing **out of memory** today, it shows loads of memory consumption after a immediate reboot, I don't know why this was happening, is there any memory leak in Volar extension? Or other process caused this problem?

## htop screenshot

![image](https://user-images.githubusercontent.com/19204772/134770352-e3f9c9f3-3c93-4800-bf75-7945f7923b19.png)

### code-server

version: 1.60.0
commit: b37ff28a0a582aee84a8f961755d0cb40a4081db
date: 2021-09-16T20:08:09Z (a week ago)
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36

### volar version

version: v0.27.24
id: johnsoncodehk.volar

### server specs

OS: CentOS Linux 8 x86_64 
Host: KVM RHEL 7.6.0 PC (i440FX + PIIX, 1996) 
Kernel: 5.14.7-1.el8.elrepo.x86_64
Shell: zsh 5.5.1 
Terminal: /dev/pts/0 
CPU: AMD EPYC-Milan (2) @ 1.996GHz 
Memory: 1708MiB / 3929MiB

**Comment by johnsoncodehk** [comment]
How many .ts, .vue, tsconfig.json files in your project? And please try config `"volar.lowPowerMode": true` and check for memory usage again.

**Comment by LittleSound** [comment]
The usage dropped significantly, thanks for this!

**Comment by johnsoncodehk** [comment]
Also make sure [Use Take Over Mode instead of TS Plugin](https://github.com/johnsoncodehk/volar/discussions/471) if you have using TS plugin.
