### ISSUE TITLE
Support other preprocessors

### ISSUE THREAD

**Issue by phil294** [johnsoncodehk/volar#533]
It would be great if we also had support for less-popular preprocessors like e.g. SLM (HTML) or Elm, CoffeScript (JS).

Surely it is a lot of work natively integrating and supporting these, so I suggest a LSP interface for custom preprocessors. Say, a configuration object
```json
"preprocessors": {
  "coffee": {
    "lspPath": "/some/path"
  }
}
```
And now, whenever Volar encounters a unsupported lang type as `<something lang="coffee">`, it simply functions as a proxy between client and a spun-up third party lsp instance at `/some/path`.

Of course, this falls short for special Vue syntax, like autocompletion for `v-if` inside a custom html preprocessor. But it's better than having no intellisense at all. In the case of Vue 3 composition api, things look bright anyway in comparison to Vue 2, where we needed [magic under the hood](https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/bridge.ts) to get TS integration.

Vetur's approach to preprocessors [is to ignore them](https://github.com/vuejs/vetur/issues/1184) and instead wait for the specific language to consider Vue syntax individually, like in the case of [ESLint](https://github.com/vuejs/eslint-plugin-vue). Volar seems to aim at integrating preprocessors into the codebase, if I understand the intent correctly. I think both approaches (if taken to the extreme) are wrong. Programming languages should arguably have higher precedence than frameworks, but language-to-framework is a a many-to-many relationship after all, [just like tooling-to-ide is](https://code.visualstudio.com/assets/api/language-extensions/language-server-extension-guide/lsp-languages-editors.png), so let's try and reuse existing servers [whereever possible](https://microsoft.github.io/language-server-protocol/implementors/servers/).
  
Congrats on becoming the recommended extension for Vue 3!

**Comment by johnsoncodehk** [comment]
Hi @phil294, this is the purpose of [Plugin API](https://github.com/johnsoncodehk/volar/issues/185).

For Elm / CoffeScript, it needs to be completely independent of TS processing, there is not much to talk about.

For template preprocessors, we need to implement a mapping protocol with template AST to support type flow analysis with v-if / v-for, and language support in interpolations.

Currently Volar does this internally for pug, but I planed migrate to plugin API in future.

**Comment by phil294** [comment]
ok I understand, thanks. Looking forward to this!
