### ISSUE TITLE
v-model and some default html attributes are wrongly typed.

### ISSUE THREAD

**Issue by horia16** [johnsoncodehk/volar#534]
I believe some attributes are wrongly typed. For example a select v-model should allow for null or for an object. Vue will happily work with it. Same for some other attributes like the value on the select options. This should be the case for most inputs as they are "restricting" functionality that Vue already has. 
Take the example below for a normal select:
![image](https://user-images.githubusercontent.com/32731652/134785744-e6dbc05c-e751-4692-bae5-843644cfe0cf.png)

Here is the option issue that I mentioned:
![image](https://user-images.githubusercontent.com/32731652/134785767-354e6d84-b133-4e9f-85f6-7227876e4dab.png)

:value="null"  behaves differently from :value="undefined" and should be considered as a valid value, yet Volar would force me to use undefined which won't achieve the desired result.

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/vue-next/issues/4574.
