### ISSUE TITLE
Missing README and CHANGELOG files

### ISSUE THREAD

**Issue by glen-84** [johnsoncodehk/volar#535]
The VS Code extension is missing a README and CHANGELOG file.

**Comment by glen-84** [comment]
@johnsoncodehk Why was this closed?

**Comment by Shinigami92** [comment]
Cause of autoclose keywords in the commit

![image](https://user-images.githubusercontent.com/7195563/136507842-081b1072-a2f9-48b0-a10a-f156707d274f.png)

**Comment by glen-84** [comment]
Yes I know that, the question is why, since it's not fixed. 🙂

**Comment by Shinigami92** [comment]
What exactly is missing on you side?
I check and I can see a README in the extension, the repo and on npm.
Also there is a changelog.

Maybe clear some caches or so on your side?

**Comment by glen-84** [comment]
The changelog.

https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

![image](https://user-images.githubusercontent.com/261509/136509356-1c501ee5-7173-45eb-9596-1661b6d94443.png)

VSC:

![image](https://user-images.githubusercontent.com/261509/136509439-efb2b8ab-38c7-4fb5-9cfa-05ce30475a94.png)

**Comment by johnsoncodehk** [comment]
With url link, I think I can update changelog before release, users can know what problems have been resolved but not release yet to avoid peoples open multiple issue for same issue. (Extension's changelog can only update with released)

So I don't need keep all issues in open, and until release new version to close it. 😄
