### ISSUE TITLE
Rename symbol (F2) on exported element (js file) doesn't rename named import (vue file).

### ISSUE THREAD

**Issue by mitow7821** [johnsoncodehk/volar#536]
As in title renaming exported function using F2 in vscode applies only in js files but not in vue `script setup` named imports

**Comment by mitow7821** [comment]
### To reproduce
-  Create js file with named export
- Import it inside another js file and in vue script setup scope
- Use F2 rename symbol in vscode
- Name of imported function changes only in js file

**Comment by johnsoncodehk** [comment]
You need to use [Volar TS plugin](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-typescript-vue-plugin) or [take over mode](https://github.com/johnsoncodehk/volar/discussions/471).

**Comment by mitow7821** [comment]
Using volarTs throws me error while using f2. With take over mode auto file renaming doesnt work. There are no other options available?

**Comment by johnsoncodehk** [comment]
Are you sure this is available in vanilla js? If yes, please provide repro case.

**Comment by mitow7821** [comment]
It is working because its renaming my named imports accross all js files, except vue ones.
Idk how could I provide repro it this case.
vscode - latest version 
volar extension - also latest 
plain vue project on vite export from 1 js file to other and to vue file then rename with f2

**Comment by johnsoncodehk** [comment]
Please modify https://github.com/johnsoncodehk/volar-starter to create necessary files and code for reproduce the problem.

**Comment by mitow7821** [comment]
https://github.com/mitow7821/f2problem 
- try to change test function name with f2

**Comment by johnsoncodehk** [comment]
With take over mode:

<img width="414" alt="螢幕截圖 2021-09-28 下午4 48 45" src="https://user-images.githubusercontent.com/16279759/135055258-4d9c5819-aec3-4900-969e-0ae1ea477713.png">

With TS plugin (this is consistency result with vanilla js, vanilla js can't rename importtest.js before open importtest.js):
<img width="364" alt="螢幕截圖 2021-09-28 下午4 56 26" src="https://user-images.githubusercontent.com/16279759/135056431-e581a000-ead6-4b17-95c2-6550f6683464.png">

What result actually you got?

**Comment by mitow7821** [comment]
With TS plugin it works in this particular project but I'd like to use it in vue JS based project .
In this scenario I am getting this error: 
![image](https://user-images.githubusercontent.com/34492112/135066178-4e1c63bb-d654-4fe9-a844-3f4f9de59706.png)

**Comment by johnsoncodehk** [comment]
@mitow7821 are you using workspace TS version? Have you try use VSCode bundle TS version?

**Comment by mitow7821** [comment]
@johnsoncodehk i am using vscode ts version but as I wrote earlier I want to use this in project where i dont have any TS file only JS ones. Shouldn't f2 feature/volar extension work without any typescript?
