### ISSUE TITLE
Native Events Throwing Type Errors in Template

### ISSUE THREAD

**Issue by Spittal** [johnsoncodehk/volar#537]
Quick question about warnings on native events not explicitly defined on the component.

I have a custom button component that doesn't define any events, because I only want to use native events with it (click, blur, focus, ect). But when I use the component Volar throws an error in the template saying that the native event isn't defined.

![image](https://user-images.githubusercontent.com/1229177/135155513-af408502-24d4-462c-9c5f-6db6262f9c37.png)

However, If I explicitly define the click event on the button component like...
```
defineEmits({
  click: null,
})
```
Then the warning goes away. But, I would prefer not to have to override every native event I intend to use for this component.

This behaviour also seems to be incongruent with how Vue actually works as described in [this documentation](https://v3.vuejs.org/guide/migration/v-on-native-modifier-removed.html)

> Vue will now add all event listeners that are not defined as component-emitted events in the child as native event listeners to the child's root element

I would like to request the Volar _not_ throw an error if the event being listened to is a native event.

**Comment by johnsoncodehk** [comment]
I can't reproduce, it may be a library-specific type problem, please provide a repro case.

**Comment by yusufkandemir** [comment]
@johnsoncodehk it only happens on Vue versions lower than `v3.2.8`, it works as expected on v3.2.8+.

**Comment by Spittal** [comment]
I can confirm that after 3.2.8, this works 🎉
