### ISSUE TITLE
Unrecognized components if Vue project isn't root folder

### ISSUE THREAD

**Issue by JonKo314** [johnsoncodehk/volar#541]
Hello :slightly_smiling_face: 

I have just added a vite-vue3-frontend to a project of mine and installed the Volar extension. The project has separate folders for the frontend and the backend in a common root folder. The frontend was created via vite `npm init vite@latest frontend --template vue`, so it uses single file components with `<script setup>`. Now it seems that Volar isn't recognizing the imported components in the template part, if I open the root folder with VS Code, while there are no issues when I just open the frontend folder with VS Code.

I've created a [sample repository](https://github.com/JonKo314/volar-vite-in-subfolder-test) to reproduce the issue.

And here is a comparison of two VS Code windows.
Opened frontend folder:
![opened-frontend-folder](https://user-images.githubusercontent.com/91629164/135335040-29c813e5-5f37-4e10-814e-493122a84aab.png)

Opened root folder:
![opened-root-folder](https://user-images.githubusercontent.com/91629164/135334982-fe10b454-f268-4bbf-92ec-8c1de3e1a7fc.png)

Also, when I add a component inside the template a second time, a pop-up suggests to import the component again, which adds the import statement to the script part although it's already there. So that makes auto-completion unusable:
![add-component-tag](https://user-images.githubusercontent.com/91629164/135335682-46a74f75-61fa-46cf-97cd-dd06fce360ed.png)

I'd be happy if that could be fixed, as using separate VS Code windows for the frontend and backend seems to be somewhat bothersome.

**Comment by johnsoncodehk** [comment]
Will check it, thanks for the report. :)
