### ISSUE TITLE
HTML events are not recognized on Vue components

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#543]
Native HTML events such as `@click` or `@submit` (on a form) are typed as `undefined` and reported as errors when they're used on a Vue component (where they actually work and fallback to the component root element).

![image](https://user-images.githubusercontent.com/3832820/135593416-ac9c8fdf-dbd7-4979-b445-4fe85264a858.png)

I never noticed this before, it might be a recent regression.

**Comment by johnsoncodehk** [comment]
It seem is a same problem to #537.

**Comment by jods4** [comment]
Yes, it's the same problem... I missed it because I only looked at open issues, sorry.

Also I thought my project was on Vue 3.2.19 but actually I never restored the packages and was still on 3.2.4 😅
