### ISSUE TITLE
vue-tsc's dependency version (0.27.7) is different to Extension version (0.27.27). Type-checking behavior maybe different.

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/volar#545]
```
Version: 1.61.0-insider (Universal)
Commit: c9e8266ee24f34107ff52d836a4e8f533afb93c5
Date: 2021-10-01T14:47:05.989Z
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
Volar: v0.27.27
```

Every time I restart vscode and open vue file, will alert this notification:

```
vue-tsc's dependency version (0.27.7) is different to Extension version (0.27.27). Type-checking behavior maybe different.
```

My vue-tsc version is 0.3.0.

![image](https://user-images.githubusercontent.com/41773861/135712131-6cd760a8-d2cf-4499-932e-0d00a316028d.png)

**Comment by johnsoncodehk** [comment]
![image](https://user-images.githubusercontent.com/16279759/135713539-7cc8678e-fbd1-4179-b955-85dc5626497c.png)

You can click "Open package.json" to check the version, and see #402 to check how to update it.
If you don't want this prompt, click "Disable Checking" to disable it.
