### ISSUE TITLE
"Property 'default' does not exist on type '{}'." On Router-view and Router-link v-slot

### ISSUE THREAD

**Issue by sibyl666** [johnsoncodehk/volar#547]
Repository to reproduce the error
https://github.com/sibyl666/issue

When v-slot is used with router-view it gives the error "Property 'default' does not exist on type '{}'."
this wasn't an issue a while ago with the same vue-router version on another repo, When I check the other repo it shows the same error so that's why I think the issue is related to the extension. Repository created with
`
yarn create vite issue --template vue-ts
`
![image](https://user-images.githubusercontent.com/54271295/135719436-8fd623d4-e16e-463e-8dcc-952139b050ca.png)

Vue Language Features (Volar) version v0.27.27
TypeScript Vue Plugin (Volar) version v0.27.27

**Comment by sapphi-red** [comment]
Creating `components.d.ts` fixed for me. (https://github.com/johnsoncodehk/volar#using)

But I have a different error when `noPropertyAccessFromIndexSignature` is true.
```
Property 'default' comes from an index signature, so it must be accessed with ['default'].
```

**Comment by sibyl666** [comment]
Thanks, @sapphi-red! The issue is gone. But I won't close this issue because you have a another issue, or should I close it?

**Comment by ndh103** [comment]
I have the same issue, and adding components.d.ts seems not working for me :(

**Comment by sibyl666** [comment]
@ndh103 I added components.d.ts in src folder and pasted
```
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
```
In it. Maybe you can share repo to reproduce the issue

**Comment by quezadaesteban** [comment]
I have red squiggles in all my `v-slots`/ `#slots` in this version. Nuxt + Composition API. Moving to 0.27.26 fixed it. Will comment later if it gets fixed with a future version.

**Comment by ndh103** [comment]
> @ndh103 I added components.d.ts in src folder and pasted
> 
> ```
> declare module 'vue' {
>   export interface GlobalComponents {
>     RouterLink: typeof import('vue-router')['RouterLink']
>     RouterView: typeof import('vue-router')['RouterView']
>   }
> }
> ```
> 
> In it. Maybe you can share repo to reproduce the issue

Thank you, I was created the components.d.ts in another folder, putting it in the src folder help solve the problem

**Comment by ndh103** [comment]
@sibyl666 I tried with components.d.ts and it still not work
Here are my repo branch that you can have a look
https://github.com/ndh103/person-hub/blob/features/error-with-volar/person-hub-web/src/views/home/events/EventDetails.vue

**Comment by innocenzi** [comment]
Having a similar, possibly related issue with locally-imported components: 

```vue
<script setup lang="ts">
import { Menu } from '@headlessui/vue'
//...
</script>

<template>
  <!-- -->
  <Menu v-slot="{ open }">
    <!-- -->
  <Menu>
  <!-- -->
</template>
```

![](https://i.imgur.com/JSpwktE.png)

This is using `v0.27.27`, but I'm unsure if this is normal because `v0.26.26` shows the type `any` instead.

Here is what the component in its `d.ts` looks like: 

<details>
<summary>Details</summary>

```ts
export declare let Menu: import("vue").DefineComponent<{
    as: {
        type: (ObjectConstructor | StringConstructor)[];
        default: string;
    };
}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
    [key: string]: any;
}> | import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
    [key: string]: any;
}>[] | null | undefined, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, Record<string, any>, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<{
    as: string;
} & {}>, {
    as: string;
}>;
```

</details>

Its source code is [here](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/menu/menu.ts) if it's of any help. 

If the "error" is intended on Volar's side, what's the workaround for me to hide the error?

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/d587ab162cf09fe79cec5a0f22624870b7ca08c0, please wait for release or use 0.27.26 for now, thanks!

@innocenzi it's also fixed in this commit.

Please keep this issue open, I will close when I release new version.
