### ISSUE TITLE
No typing on `useCssModule`

### ISSUE THREAD

**Issue by nbgraham** [johnsoncodehk/volar#548]
When using css modules in a SFC, the template knows which classes are available
![image](https://user-images.githubusercontent.com/11163850/135724963-410dd209-1860-4546-bacc-a1fa0deca3e7.png)
But in the TS setup code, `$style` is just a `Record<string, string>`
![image](https://user-images.githubusercontent.com/11163850/135725006-4b17faf4-7235-47d5-9a89-645bef775869.png)

I would like to know the available classes in both places for autocomplete/compile time validation.

Maybe there is just some setup I am missing?

Or maybe this belongs on the [vue composition api repo](https://github.com/vuejs/composition-api/pull/420/files)?

I think this is the code for Volar that provides the types to the template
https://github.com/johnsoncodehk/volar/blob/d5c222de81131bea6c10437abb28af62cd172b57/packages/vscode-vue-languageservice/src/use/useSfcTemplateScript.ts#L87-L94
Is there a way to also have this apply to the `useCssModule` output in component `setup`?

**Comment by johnsoncodehk** [comment]
This is by design, css module types is only generate to `<template>` for better IDE support.

I think user and libraries should have full control of `<script>` section, so I avoid volar has redundant affect to `<script>`.
