### ISSUE TITLE
Publish Volar in open-vsx to use it in Vscodium

### ISSUE THREAD

**Issue by LaBaude32** [johnsoncodehk/volar#550]
Is it possible to publish Volar in open vsx format to use it on VSCodium ?
The process is not really complicated, you can find it here : #https://github.com/open-vsx/publish-extensions

Thank you for your works ;)

**Comment by johnsoncodehk** [comment]
It seem already has it (thanks to @OnlyBjarne works!): https://github.com/open-vsx/publish-extensions/pull/436
