### ISSUE TITLE
Volar does not reload when script lang=ts src file changes

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#565]
```ts
// file.ts
import { defineComponent, ref } from 'vue'

export default defineComponent({
  setup() {
    return {
      // Comment this in again
      // life: ref(42)
    }
  }
})
```

```vue
<!-- file.vue -->
<template lang="pug">
div {{ life }}
//-    ~~~~ this will still not get recognized after exposing `life`
</template>

<script lang="ts" src="file"></script>
```

Currently we always need to restart Volar via VS Code command

**Comment by johnsoncodehk** [comment]
> Just theoretically (without looking in how Volar works) Would it be possible to watch for changes of files that are referenced via `src`? Or is this exactly the performance issue you mentioned?

This way have no performance problem, but the implement not as simple as it looks.

> We tried to change
> 
> ```
> <script lang="ts" src="file"></script>
> # to
> <script lang="ts" src="fil"></script> # save file
> # back to
> <script lang="ts" src="file"></script> # save file again
> ```
> 
> But that didn't work

This is expected, only `<script>` content trigger template update for now.

**Comment by chenjiangui** [comment]
same problem, when use `<script lang="ts" src="file"></script>`, file change volar don't reload

**Comment by reuwi** [comment]
@johnsoncodehk  I'm writing the script code into the same file of .vue file, still got this problem，and relative version is: 2022/4/16 15:04:20
