### ISSUE TITLE
Slot as JSX

### ISSUE THREAD

**Issue by euaaaio** [johnsoncodehk/volar#568]
This warning highlights all slots:

```
JSX element type '__VLS_9' does not have any construct or call signatures.
```

A simple reproduction from a real project: https://github.com/euaaaio/repro-storybook-vue-volar-jsx

**Comment by BreizhReloaded** [comment]
Ok, I found issue #558 and it looks very similar. I'm running v0.28.0 and vite/client is referenced.

**Comment by euaaaio** [comment]
This tsconfig.json works for me. 

```json
{
  "compilerOptions": {
    "types": []
  },
  "exclude": [
    "**/*.stories.ts",
  ]
}
```
