### ISSUE TITLE
ref intellisense enchancement

### ISSUE THREAD

**Issue by ShenQingchuan** [johnsoncodehk/volar#57]
please check https://github.com/vuejs/vetur/issues/2605  ，I think this is quite useful and worth to integrate in volar, the cost may be much cheeper than vetur... vetur is too big to add a new feature...

Can we do that ?

**Comment by johnsoncodehk** [comment]
please try 0.20.4. and this is experimental feature temporarily, it maybe revoke if not suitable.

**Comment by ShenQingchuan** [comment]
wow thanks！🎉⚡
