### ISSUE TITLE
template ref for component is broken since 0.27.27

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#572]
Hi Author,

In my project, I use a template ref for ElTable(Element) to retrieve the component instance.
Before 0.27.27, everything is ok. But since 0.27.27, volar will complain a type check issue.
I don't know how to fix it.

![image](https://user-images.githubusercontent.com/1321817/136512774-db9d30c5-072a-4cf3-bf98-efbdb3cf5576.png)

![image](https://user-images.githubusercontent.com/1321817/136512850-ce8e25b0-1551-4941-a614-56b5a5604d21.png)

![image](https://user-images.githubusercontent.com/1321817/136512877-ad411518-b146-4cc8-8ad2-f2b19db4dcb1.png)

**Comment by johnsoncodehk** [comment]
It look like #556 but I can't reproduce, can you provide a repro case?
