### ISSUE TITLE
"VNodeChild is not a valid JSX element"

### ISSUE THREAD

**Issue by bradlc** [johnsoncodehk/volar#574]
`vue-tsc` >= `v0.2.3` throws an error when using a render function as a component. I am not too familiar with Vue 3 but this seems incorrect as the app renders fine when not using `vue-tsc`.

### Example

```vue
<script setup lang="ts">
import { createVNode, RenderFunction } from 'vue'

const HelloWorld: RenderFunction = () => {
  return createVNode('h1', {}, 'Hello world')
}
</script>

<template>
  <HelloWorld />
</template>
```

```
src/App.vue:10:4 - error TS2786: '__VLS_2' cannot be used as a JSX component.
  Its return type 'VNodeChild' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.

10   <HelloWorld />
      ~~~~~~~~~~
```

Vue SFC Playground example that renders successfully: https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IGNyZWF0ZVZOb2RlIH0gZnJvbSAndnVlJ1xuXG5mdW5jdGlvbiBIZWxsb1dvcmxkKCkge1xuICByZXR1cm4gY3JlYXRlVk5vZGUoJ2gxJywge30sICdIZWxsbyB3b3JsZCcpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8SGVsbG9Xb3JsZCAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4xOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9

### Steps to reproduce

1. Clone https://github.com/bradlc/vue-ts-render-function
2. Run `npm install`
3. Run `npm run build`

**Comment by Michael-J-Ward** [comment]
> In next version, invalid functional component type is `any` in template, so it don't report error and not support props type-checking.

Does this mean that `volar` will not support type checking for any `.vue` component that uses the `<slots>` feature?

> This problem is RenderFunction return type VNodeChild is not compatible to vue's JSX element type VNode.

Is this a flaw in `vue`'s typesystem  (hence the `upstream` label)?

**Comment by johnsoncodehk** [comment]
> Does this mean that `volar` will not support type checking for any `.vue` component that uses the `<slots>` feature?

If your component typecheck working before, it still working. If the component report `'__VLS_x' cannot be used as a JSX component` beforer, component type changed to any in new version.

> Is this a flaw in `vue`'s typesystem (hence the `upstream` label)?

Yes this is upstream types problem.
