### ISSUE TITLE
Emits with no payload are typed as having an unknown payload

### ISSUE THREAD

**Issue by henribru** [johnsoncodehk/volar#575]
This defines an emit with no payload: https://github.com/henribru/volar-emit-bug/blob/master/src/components/HelloWorld.vue#L13

This treats that emit like it has a payload, but gives no error: https://github.com/henribru/volar-emit-bug/blob/master/src/App.vue#L3. Hovering over the event listener shows the type as `(...payload: unknown[]) => unknown`

**Comment by jzs11** [comment]
I can confirm this behavior. 
![image](https://user-images.githubusercontent.com/2770401/136623623-9ff1ada3-ae8d-4a62-9e73-8bc99c573575.png)

**Comment by sigmarising** [comment]
Similar issue occur to me but I did define the payload, which will not happen in the prevous volar version.

Current Version I used is `v0.28.1`.

![Emits Define](https://user-images.githubusercontent.com/25470568/136677711-13255dec-8cec-4438-9360-dd4871465831.png)

![Used emits](https://user-images.githubusercontent.com/25470568/136677714-0a9de39a-8166-4a43-b10a-5cbd53d3ce00.png)

![Problem](https://user-images.githubusercontent.com/25470568/136677728-9d0e6060-587c-4046-981f-111678b82e50.png)
