### ISSUE TITLE
Add option to disable template type-check and TS intellisense

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#577]

**Comment by Antti** [comment]
We are using different language for the template (not HTML and not pug), would this fix the issue? `vue-tsc` tries to interpret the template as HTML and fails with errors.

**Comment by johnsoncodehk** [comment]
@Antti this is an different issue, we should ignore template if it's not html or pug, you can open a bug report for track.

**Comment by justablob** [comment]
Is this on the roadmap to be implemented any time soon?

**Comment by johnsoncodehk** [comment]
After marge #1009 this is easy to do. Now you can config this in tsconfig to do it.

```jsonc
{
  "compilerOptions": ...
  "vueCompilerOptions": {
    "experimentalDisableTemplateSupport": true
  }
}
```

Don't be surprised that when config this most intellisense in template will stop working. Only html intellisense is working.

This option is for when you want to skip template type-checking in vue-tsc, or if volar memory usage is too high to your project. Disabling template TS support can reduce memory usage by more than half. (If enabled low power mode at the same time, the memory usage will be reduced to less then 1/4)

**Comment by ahnpnl** [comment]
> After marge #1009 this is easy to do. Now you can config this in tsconfig to do it.
> 
> ```js
> {
>   "compilerOptions": ...
>   "vueCompilerOptions": {
>     "experimentalDisableTemplateSupport": true
>   }
> }
> ```
> 
> Don't be surprised that when config this much intellisense in template will stop working. Only html intellisense is working.
> 
> This option is for when you want to skip template type-checking in vue-tsc, or if volar memory usage is too high to your project. Disabling template TS support can reduce memory usage by more than half. (If enabled low power mode at the same time, the memory usage will be reduced to less then 1/4)

Hi, I got this error after using that option
<img width="927" alt="image" src="https://user-images.githubusercontent.com/27772165/158264792-a23e8513-2798-4c10-917b-c5fd3008ad15.png">

I'm using **0.33.2**

**Comment by johnsoncodehk** [comment]
@ahnpnl thanks for the report! Could you try 0.33.2-patch.1?

**Comment by ahnpnl** [comment]
Thanks, the error doesn't exist anymore. I have a question about this option though, isn't it supposed to disable type checking on for HTML part of SFC?

**Comment by johnsoncodehk** [comment]
@ahnpnl yes

**Comment by ahnpnl** [comment]
I'm not sure this flag working. I still see it tries to check my HTML and throw TS error codes

**Comment by johnsoncodehk** [comment]
@ahnpnl it's works for me in https://github.com/johnsoncodehk/volar-starter, could you provide a minimal reproduction?

**Comment by yaegassy** [comment]
@johnsoncodehk Is this the basic compilerOptions in tsconfig.json? Does this include a reference to `vueCompilerOptions`?

**packages/vue-typescript/src/typescriptRuntime.ts**:

```typescript
    const templateTsHost = options.compilerOptions.experimentalDisableTemplateSupport ? undefined : createTsLsHost('template');
```

**Comment by johnsoncodehk** [comment]
@yaegassy here `options.compilerOptions` just mean vueCompilerOptions, see https://github.com/johnsoncodehk/volar/blob/4aea6349cf92746d5e3229630b4a0a300d899812/packages/vue-tsc/src/proxy.ts#L41. I will make the code clearer.

**Comment by yaegassy** [comment]
I have tried it in my environment and checked that only HTML Intellisense is now working. template type-check also be disabled? The ts error is still output.

Perhaps I am misunderstanding the correct behavior of this feature. It might be a good idea to have @ahnpnl try again.
