### ISSUE TITLE
Cannot find module #app in Nuxt 3 plugin

### ISSUE THREAD

**Issue by jonybekov** [johnsoncodehk/volar#586]
Just installed fresh beta version of Nuxt 3 and copy & pasted example https://v3.nuxtjs.org/docs/usage/state#example

It's either Volar cannot find type definition for #app or it's Nuxt 3 lacking the d.ts file for #app module
![image](https://user-images.githubusercontent.com/39439363/137019882-ca63c36f-f2a7-4153-a6c6-0fbd59ed182f.png)

**Comment by igorjacauna** [comment]
It's a Nuxt 3 documentation issue. You should use `nuxt3` instead `#app`

**Comment by jonybekov** [comment]
Thanks. Closing this

**Comment by sduduzog** [comment]
To add extra cheese to @pi0 's comment above, running `nuxi dev` generates a tsconfig.json file that lives in .nuxt folder, so adding
```json
{
+    "extends": "./.nuxt/tsconfig.json",
     "compilerOptions": {
```

solves the problem, see https://v3.nuxtjs.org/getting-started/bridge#update-tsconfigjson

**Comment by aseidma** [comment]
Also note that using `"extends": "./.nuxt/tsconfig.json"` does **not** extend the `"paths"` property in your own `tsconfig.json`. Instead the `"paths"` property from `./.nuxt/tsconfig.json` **is overwritten entirely** by your own `"paths"` value.

This won't work (lead to red squiggles from ts/volar/vetur):

```json
{
    "extends": "./.nuxt/tsconfig.json",
    "compilerOptions": {
        "target": "ES2018",
        "module": "ESNext",
        "moduleResolution": "Node",
        "lib": ["ESNext", "ESNext.AsyncIterable", "DOM"],
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "allowJs": true,
        "sourceMap": true,
        "strict": true,
        "noEmit": true,
        "baseUrl": ".",
        "experimentalDecorators": true,
        "paths": {   // This overwrites every "paths" mapping from ./.nuxt/tsconfig.json!
            "~/*": ["./*"],
            "@/*": ["./*"],
        },
        "types": [
            "@types/node",
            "@nuxt/types",
            "@types/jest",
        ]
    },
    "exclude": ["node_modules", "functions"]
}
```

This can lead to very frustrating behaviour when migrating from nuxt 2 (where you had to define your own path mappings in `tsconfig.json`). When migrating, make sure to remove the `"paths"` property from your `tsconfig.json` in order to adapt the one provided by `./.nuxt/tsconfig.json`.

Perhaps a remark in the documentation (at least within the migration guide) would be useful?

**Comment by davidnknight** [comment]
This is still the case with a new Nuxt 3 module.

I create a new module using:
```npx nuxi init -t module my-module```

Install dependencies:
```cd my-module && npm install```

I then open in Visual Studio Code (v1.69.1) with Volar (v0.39.1), open `src/runtime/plugin.ts` and hover `#app` in the import statement and see exactly the same as @jonybekov reported back in October 2021.

![CleanShot 2022-07-25 at 10 08 07](https://user-images.githubusercontent.com/1526840/180741211-e48ee6e0-df53-461d-be41-785f2bcab062.png)

**Comment by AqilCont** [comment]
@davidnknight Same for me

I've been trying to work around it, but it's extremely frustrating encountering non-existent linter errors and unresolved types.
![image](https://user-images.githubusercontent.com/32044067/181424725-8893550f-7ca3-4402-955f-9f66a7ebe930.png)

**Comment by brandonbronisz** [comment]
@davidnknight @AqilCont if you are referring to the nuxt 3 module template, `~/playground/.nuxt/tsconfig.ts` is missing the include for the module src dir. to fix this modify `~/tsconfig.ts` in your root to be the following: 

```json

{
  "extends": "./playground/.nuxt/tsconfig.json",
  "include": ["./src"]
}

```

**Comment by AqilCont** [comment]
> @davidnknight @AqilCont if you are referring to the nuxt 3 module template, `~/playground/.nuxt/tsconfig.ts` is missing the include for the module src dir. to fix this modify `~/tsconfig.ts` in your root to be the following:
> 
> ```json
> {
>   "extends": "./playground/.nuxt/tsconfig.json",
>   "include": ["./src"]
> }
> ```

Sorry, this only causes new errors for me. I don't have a `playground` dir, so I'm guessing we used a different template, and only included whatever was in the `include`. I've tried both Volar and Vetur and none of them seem to accept it.

**Comment by aqilc** [comment]
Why is this closed? It's still an issue.
@harryyaprakov and I are still experiencing the same tiring squigglies everywhere.

**Comment by danielroe** [comment]
This is a very old issue; please open a new one if you are experiencing a problem. That said, you need to enable `typescript.includeWorkspace` for the Nuxt types to apply within your module code:

https://github.com/nuxt/starter/blob/module/.nuxtrc#L2

**Comment by imcm7** [comment]
> ```json
> "#app": [
>         "./node_modules/nuxt3/dist/app/index"
>       ]
>     }
> ```

Is 2023, few days to October and I have the same error

**Comment by so1ve** [comment]
@imcm7 Please open a new issue with minimal reproduction

**Comment by imcm7** [comment]
@so1ve please resolve captcha to demonstrate you are not a bot :) 

That to put in nuxt config `typescript.includeWorkspace=true`?

**Comment by imcm7** [comment]
```
typescript: {
        includeWorkspace: true,
        typeCheck: true,
        shim: false, // For TypeScript Vue Plugin (Volar).
    },
```

**Comment by sduduzog** [comment]
There's about 11 other participants in this issue who would really appreciate if you opened another issue for this @imcm7

**Comment by imcm7** [comment]
@sduduzog I not understand how it work, in one page with nuxt page (index.vue) in the save vs code it not found '#app', in other, in other all work well.
Close vs code, stop nuxt dev. Restart nuxt in dev, open vs code, it not found '#app' in all pages.
Reload vs code window (ctr+shift+p) not help.

**Comment by imcm7** [comment]
@sduduzog  some one of them in elapsed time retired and no longer need it

**Comment by imcm7** [comment]
Cannot find name 'useRuntimeConfig'.ts

Cannot find '~/interfaces/bla-bla-bla'

**Comment by GexideL** [comment]
> > ```json
> > "#app": [
> >         "./node_modules/nuxt3/dist/app/index"
> >       ]
> >     }
> > ```
> 
> Is 2023, few days to October and I have the same error

@imcm7 Path has been changed to
"./node_modules/nuxt/dist/app/index"

**Comment by GarethWoodman** [comment]
For any poor soul who also had their keyboard bloodied by this:

❌ `import { defineNuxtPlugin } from 'nuxt/app'`
✅ `import { defineNuxtPlugin } from 'nuxt/app'`

**Comment by emink92** [comment]
> For any poor soul who also had their keyboard bloodied by this:
> 
> ❌ `import { defineNuxtPlugin } from '#app'` 
> ✅ `import { defineNuxtPlugin } from 'nuxt/app'`

I am literally going crazy for this. After adding this line I get the error:

```
SyntaxError: Cannot use 'import.meta' outside a module
```

The plugin file:

```
import { defineNuxtPlugin } from 'nuxt/app'

export default defineNuxtPlugin((nuxtApp) => {
  console.log('test')
})
```

**Comment by danielroe** [comment]
You should import from `#imports` or `#app`, not from `nuxt/app`.

**Comment by BurakVirtue** [comment]
> You should import from `#imports` or `#app`, not from `nuxt/app`.

The problem is definitely chronic, it needs to be fixed.

**Comment by davidstackio** [comment]
Restarting VS Code worked for me.

**Comment by SergioSuarezDev** [comment]
I have the same error trying to test with jest in nuxt 3.

**Comment by imcm7** [comment]
@SergioSuarezDev Strange, I not have such problem for a while... god forbid you have my current problems...

**Comment by morphatic** [comment]
I encountered this issue while developing a Nuxt (currently v4) module. I tried all of the things above. The idea from @GarethWoodman worked but I was bothered by the response from @danielroe.

Turns out I just needed to rebuild the `./.nuxt/` folder (by running `pnpm dev`) and the problem went away. I'm not sure how I got into that state in the first place. Some notes that are current to August 2025:

* Reproducing this is hard/impossible since it appears to be caused by out-of-date `./.nuxt/` build
* `"typescript.includeWorkspace": true` (in `.vscode/settings.json`) no longer appears to be an available configuration setting
* Restarting VSCode or restarting the TypeScript language server could, in theory, fix the issue, but didn't help me
* Switching between the VSCode and Workspace versions of TypeScript could help, but mine were the same version, so it didn't matter
* It shouldn't be necessary to modify `./tsconfig.json`

Hope this helps someone!

**Comment by molavec** [comment]
In my case, I have problem in Nuxt4,  error.vue page

<img width="1670" height="595" alt="Image" src="https://github.com/user-attachments/assets/1a52f57f-47a1-4315-a11c-8c5ae9673587" />

I solved adapting @pi0 answer in `tsconfig.json`

<img width="1668" height="565" alt="Image" src="https://github.com/user-attachments/assets/e2e49f6b-de23-4968-8a01-f9511298534e" />

**Comment by danielroe** [comment]
that is no longer the correct answer. please open an issue with a reproduction in the nuxt repo and i'll help 🙏

**Comment by Herant** [comment]
Running into the same issue with clean Nuxt4 project.

---

###  Steps to reproduce

1. Initialize a new **Nuxt 4** project following the official documentation.
2. Add the following modules in `nuxt.config.ts`:

```ts
import tailwindcss from '@tailwindcss/vite'
import { defineNuxtConfig } from 'nuxt/config'

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  css: ['~/assets/css/main.css'],
  modules: [
    '@nuxt/eslint',
    '@nuxt/image',
    '@nuxt/ui',
    '@clerk/nuxt',
    '@nuxtjs/color-mode',
  ],
  vite: {
    plugins: [tailwindcss()],
  },
})
```

3.Create app/error.vue as described in the Nuxt docs:

```vue
<script setup lang="ts">
import type { NuxtError } from '#app'

defineProps({
  // eslint-disable-next-line vue/require-default-prop
  error: Object as () => NuxtError,
})
</script>

<template>
  <section
    class="flex min-h-screen flex-col items-center justify-center bg-[#e8d7b8]"
  >
    <h1 class="mb-2 text-9xl font-bold">{{ error?.statusCode }}</h1>
    <p class="mb-10 text-xl sm:text-3xl">{{ error?.statusMessage }}</p>
    <NuxtLink
      to="/"
      class="cursor-pointer rounded-md bg-sky-600 px-4 py-2 text-lg text-white"
    >
      Go Back
    </NuxtLink>
  </section>
</template>
```

**Error**
Cannot find module '#app' or its corresponding type declarations.
Vetur(2307)
module "Users/user/Projects/project/node_modules/nuxt/dist/app/index"

**Environment**
Nuxt version: 4.1.3
Node version: v22.20.0
Package manager: npm
OS: macOS Sequoia 15.3.1

**Comment by so1ve** [comment]
@Herant `Vetur(2307)`
