### ISSUE TITLE
volar version 0.26.1 and 0.26.3 is error => command 'volar.action.splitEditors' not found

### ISSUE THREAD

**Issue by isliwei** [johnsoncodehk/volar#588]
![image](https://user-images.githubusercontent.com/49444387/137092405-4bdcbe51-1295-4d0b-8e5c-1518f595798a.png)

**Comment by zeroone001** [comment]
restart VSCode

**Comment by ch3cknull** [comment]
![image](https://user-images.githubusercontent.com/45302021/170863203-505f5640-b7c4-4956-a4f6-34bcfbef977d.png)

I have same problem in version `0.35.0`

**I tried restart VS Code，but not effect.**

My environment：
- Window 10 20H2
- VS Code 1.66.2

**However, I tried re-install VS Code(1.67.2), and it works.**

April this year，I also have this problem，I make sure that **I did not modify any configuration of VS Code or Volar**

**Comment by ThatOneCalculator** [comment]
I'm also having this problem on Arch Linux. Any suggestions?

**Comment by johnsoncodehk** [comment]
@ThatOneCalculator make sure update VSCode and Volar to latest version.
