### ISSUE TITLE
Typing setup props interferes with type inference

### ISSUE THREAD

**Issue by canac** [johnsoncodehk/volar#59]
I have this simplified component. With version v0.20.8, Volar doesn't know the type of `value` in my template.

```vue
<template>
  <div class="component">
    {{ value }}
  </div>
</template>

<script lang="ts">
export default {
  props: {
    foo: {
      type: String,
      required: true,
    },
  },

  setup(props: { foo: string }) {
    return {
      value: 0,
    };
  },
};
</script>
```

However, if I remove the type annotation from props and change that line to `setup(props) {`, Volar suddenly knows that value is a number, and the red error lines in VS Code go away. Removing the `props: { ... }` definition (by renaming it to `_props`, for example) also gets rid of the errors. Using destructuring syntax without a type annotation and replacing the setup line to `setup({ foo }) {` also gives errors.

This is an amazing and tremendously helpful extension! 🎉 Keep up the great work!

**Comment by johnsoncodehk** [comment]
hi @canac, please try use defineComponent :)

```ts
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    foo: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    return {
      value: 0,
    };
  },
});
```

if you don't, volar will warp your options as defineComponent, but not always effective, in your case:

```ts
import { defineComponent } from "vue";

const a = {
  props: {
    foo: {
      type: String,
      required: true,
    },
  },

  setup(props: { foo: string }) {
    return {
      value: 0,
    };
  },
}
const b = defineComponent(a); // No overload matches this call.ts(2769)
```

**Comment by canac** [comment]
Thanks for the quick response! I'll let you decide whether to make any changes, but using `export default defineComponent(...)` makes my code work and even gives me type inference on the `setup` `props` without having to explicitly type them.
