### ISSUE TITLE
Truncates React elements

### ISSUE THREAD

**Issue by bingalls** [johnsoncodehk/volar#6]
Below is a valid React 404.tsx file. Volar complains of unreachable code. After making a trivial change, e.g. add an extra blank line. When saving, VScode running Volar truncates half the return() expression, including the `</p>` closing tag, turning it into illegal syntax.

```typescript
import React, { ReactElement } from "react";

export default function FourOhFourPage(): ReactElement {
  return <p>Hey - That page doesn't exist!!</p>;
}
```

**Comment by johnsoncodehk** [comment]
Thank you for the report!
Please try 0.13.14, if the problem persists, can you provide a reproducible project?

**Comment by bingalls** [comment]
I successfully tested with 0.14.1. I noticed that Volar likes to trim () from `return` expressions, but it seems to be smart & effective.
