### ISSUE TITLE
Can't correctly display CSS references

### ISSUE THREAD

**Issue by thirteenthree** [johnsoncodehk/volar#603]
![image](https://user-images.githubusercontent.com/35475497/137637263-f8b243ce-e399-4d46-8835-2a0d3a9bbda4.png)
![image](https://user-images.githubusercontent.com/35475497/137637280-2aca3e97-a684-40ad-8af4-6ac564104b97.png)

I defined a CSS named m-card, but the number of reference  is 0

**Comment by johnsoncodehk** [comment]
It's working for me, can you provide repro case?

**Comment by thirteenthree** [comment]
> It's working for me, can you provide repro case?

the version of Vue Language Features(volar) is 0.28.6, the version of TypeScript Vue Plugin (Volar)
is 0.28.6.

**Comment by thirteenthree** [comment]
> It's working for me, can you provide repro case?

It's strange that the new project I recreated can be used. This problem project can also be used a few days ago, but I reinstalled vs code
