### ISSUE TITLE
Pug not support `@typescript-eslint/no-unused-vars` rule

### ISSUE THREAD

**Issue by yoyoys** [johnsoncodehk/volar#604]
<img width="964" alt="CleanShot 2021-10-18 at 02 42 51@2x" src="https://user-images.githubusercontent.com/22124891/137640625-d67ea924-0c73-416f-bf49-3569a90c9d18.png">

If template transform to HTML this works well

**Comment by johnsoncodehk** [comment]
Thanks for the report, but this is ESLint problem not volar problem :S

**Comment by alphaelf** [comment]
it seems solved by [eslint-plugin-vue-pug](https://github.com/rashfael/eslint-plugin-vue-pug)

**Comment by hecktarzuli** [comment]
> @alphaelf what makes you think that? I seems not like working on my machine

If you include eslint-plugin-vue-put in your project then add the 2 lines to your eslint file, it does seem to work.  I just wish there was a more official way to do it.
