### ISSUE TITLE
wrong comment type on comment command

### ISSUE THREAD

**Issue by yoyoys** [johnsoncodehk/volar#605]
Hi!

I've use `editor.foldAllBlockComments` on `<style lang="scss">` block, and I got wrong result like this:

<img width="439" alt="CleanShot 2021-10-18 at 04 35 26@2x" src="https://user-images.githubusercontent.com/22124891/137643999-a167c69f-5917-48b6-88b0-d4f6ebb77a2f.png">

and I try to search issue for answers and nothing found, thanks for reply.

**Comment by johnsoncodehk** [comment]
Do you mean `editor.action.blockComment` command?

Volar don't define scss language comment brackets, it's define by VSCode built-in css extension and your other scss extensions. Please try [resolving extension issues with bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect).
