### ISSUE TITLE
Semantic highlighting not working in *.vue files

### ISSUE THREAD

**Issue by NejcBW** [johnsoncodehk/volar#61]
Let me first start by thanking you for such an amazing extension! It is amazing that you support semantic scopes in *.vue files. This is something that is really missing in other extensions such as Vetur or VueDX to make coding experience closer to what I get in WebStorm.

However, speaking of the semantic tokens, I have noticed that the semantic highlighting does not work in *.vue files despite semantic scopes clearly being visible when I use the scope inspector and even some additional semantic scopes being defined in the package.json file. I have the `editor.semanticHighlighting.enabled` property set to `true` in the VSCode settings.json file and semantic highlighting works without any problems in .ts files. Any idea what could be the issue here?

**Comment by NejcBW** [comment]
I found the problem, which is that the language identifier for JS/TS scopes is not "javascript/typescript", respectively, but "vue". Since my theme doesn't use any default scoping styles but only explicit styles for every language (e.g. "variable:typescript"), the scopes in vue files were not covered.

**Comment by johnsoncodehk** [comment]
sorry different time zone :sweat_smile:, nice to hear your resolved.
