### ISSUE TITLE
Support for Web IDE

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#612]
Issue: #598

Tasks:
- [x] Syntax highlight
- [x] ~~Rollup~~ ESBuild
- [x] Document features
  - Selection Ranges
  - Folding Ranges
  - Linked Editing Ranges
  - Document Symbols
  - Document Colors
  - Formatting
- [ ] Language features

References:
- https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions
- https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-web-extension-sample

**Comment by johnsoncodehk** [comment]
Reference: https://github.com/vuejs/vetur/issues/3248#issuecomment-1103711779

**Comment by rayfoss** [comment]
This is fixed... ish, it now mostly works with the following installation errors
![image](https://user-images.githubusercontent.com/876076/169398874-28d0330b-c6f8-4512-a605-c3802589d188.png)

**Comment by rzhao271** [comment]
On https://insiders.vscode.dev on Microsoft Edge, I can get the extension to activate, but it seems that I can't run any Volar commands from the command palette afterwards.

**Comment by johnsoncodehk** [comment]
@rzhao271 Fixed in https://github.com/johnsoncodehk/volar/commit/377033785d18adaff2b22c6ed4303435a7802114.
