### ISSUE TITLE
Cannot resolve vue file in ts file when extending tsconfig.json 

### ISSUE THREAD

**Issue by pynnl** [johnsoncodehk/volar#62]
### Reproduce:
- Extend any config in `tsconfig.json`
- Reload vscode if error doesn't appear

![image](https://user-images.githubusercontent.com/31667324/107955024-45503400-6f6b-11eb-9349-ecf43607a6b8.png)

### Repo:
https://github.com/pynnl/volar-extend-tsconfig

### Use case:
I'd like to use [google style](https://github.com/google/gts) in my project.

P/S: Thank you for the great extension.

**Comment by johnsoncodehk** [comment]
@pynnl thanks to report! please try to add `"rootDir": "."`

**Comment by pynnl** [comment]
@johnsoncodehk `"rootDir": "."` doesn't work for me. I've tried several options but the it seems that only removing `extends` worked.

**Comment by johnsoncodehk** [comment]
I think I parsed tsconfig incorrectly, I'm checking.

**Comment by johnsoncodehk** [comment]
should be fix in 0.21.5, please let me know if working or not.

**Comment by pynnl** [comment]
It's working now. Thank you!
