### ISSUE TITLE
[Proposal] Document differences between Volar and Vetur

### ISSUE THREAD

**Issue by ddahan** [johnsoncodehk/volar#623]
I think it's currently difficult to someone to actually understand the differences between Volar. It could be great to have somewhere clear answers to these questions, in the `Readme` page:

- What's the main differences in features between 2 projects?
- In which case Volar is better than Vetur, and vice versa?
- Which one was first to be born, and why a second project?
- Why both projects can not be merged to double the collaboration and avoid unnecessary split?
- ...

What do you think?

**Comment by johnsoncodehk** [comment]
Actually I'm not sure how I should talk about this topic, and even some important points may have been forgotten because of the long time.

Can you reopen it in https://github.com/johnsoncodehk/volar-land/discussions? I will try to answer.
