### ISSUE TITLE
standalone LSP support?

### ISSUE THREAD

**Issue by sentriz** [johnsoncodehk/volar#63]
hey, thanks for volar it's very nice

Is it possible to run volar as a standalone LSP server? (for use with eg. vim/emacs/sublimetext LSP clients)
I image the functionality would be not 100% complete with the VS code plugin but just wondering if it's possible?

thanks!

**Comment by johnsoncodehk** [comment]
Yes volar is designed for this, we have `vscode-vue-languageservice` and this is a standalone vue language service api base on LSP for any node.js environment not only IDE.

I don't have time to focus on this temporarily. but you can comment which second IDE should we support first.

**Comment by sentriz** [comment]
cool that's good to hear :+1: 
I don't any IDEs in mind. but at least in my case, I use neovim with the builtin LSP client

for example to use that with the typescript LSP, you can call a command line program that takes LSP commands from stdio
```lua
local config_typescript = {
    cmd = {"typescript-language-server", "--stdio"},
    root_dir = util.root_pattern("package.json", "tsconfig.json", ".git"),
    filetypes = {
        "javascript",
        "javascriptreact",
        "javascript.jsx",
        "typescript",
        "typescriptreact",
        "typescript.tsx"
    }
}
```

**Comment by johnsoncodehk** [comment]
I will check it when I free, and now the main work is refactor this project. thanks for sharing :)
