### ISSUE TITLE
pug tag collapse has wrong end offset

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#636]
When I collapse a pug tag, it collapse also the blank line below it.
This is really annoying when working in some more larger files (I know, we could move more code to dedicated components... 🤷 but that's not the point)

https://user-images.githubusercontent.com/7195563/139017915-2c57e9fe-e8e5-4ec5-b739-875ad3aea4b0.mov

When I disable all plugins for VSCode it works like expected 👀 So I just currently assume that it is cause by Volar 🤔 

https://user-images.githubusercontent.com/7195563/139018082-883c8c01-8c4c-49f9-814c-c3332b3a6be1.mov

@johnsoncodehk If you fixed this, please show me the code (commit) so I can learn from it 🙂

**Comment by JarvisChao** [comment]
Vue - Official v2.1.10 has the same issue. Is there any solution?
