### ISSUE TITLE
Vue 2 template ref support bug

### ISSUE THREAD

**Issue by xiaoxiangmoe** [johnsoncodehk/volar#641]
see repo https://github.com/xiaoxiangmoe/volar-vue2-template-ref-desugar-bug

```vue
<script setup lang="ts">
import { ref as ref2 } from '@vue/composition-api';
import { ref as ref3 } from '@vue/reactivity';

defineProps<{ msg: string }>();

const count = ref2(0);
</script>

<template>
  <div>
    <h1>{{ msg }}</h1>
    <button type="button" @click="count++">count is: {{ count }}</button>
  </div>
</template>
```

if we use `ref2`, it will fail type checking.
if we use `ref3`, it works.

![image](https://user-images.githubusercontent.com/8111351/139198705-35b788b6-db2a-48db-9aad-4b7d9672f289.png)
![image](https://user-images.githubusercontent.com/8111351/139198737-2eadca04-cff0-4ef9-9059-2a9f0b98a11b.png)

**Comment by johnsoncodehk** [comment]
@xiaoxiangmoe please try add `defineProps({})`.

This is `@vue/composition-api` types issue, if `defineComponent` have no `props` option, component context includes `Record<string, any>` type so volar can't extract valid components from component context.

Just FYI @antfu.

**Comment by xiaoxiangmoe** [comment]
@johnsoncodehk Can you give me some guide about this? Thank you.

**Comment by johnsoncodehk** [comment]
See https://github.com/xiaoxiangmoe/volar-vue2/pull/1

**Comment by xiaoxiangmoe** [comment]
Do you known how to change `@vue/composition-api` to adapt volar 0.28.4?
It works well in 0.28.3.

**Comment by johnsoncodehk** [comment]
You can try this code.
```
import { defineComponent } from '@vue/composition-api';

const Foo = defineComponent({ props: {} });
const Bar = defineComponent({});

(new Foo()).xxx; // unknown
(new Bar()).xxx; // any, expected unkonwn
```

Seems change `VueProxy<unkonwn` to `VueProxy<{}` in this line resolved, but not sure any other affect.
https://github.com/vuejs/composition-api/blob/b59e8647442df94296955b4bc291af5de4ca6218/src/component/defineComponent.ts#L21

**Comment by xiaoxiangmoe** [comment]
Thank you very much !
