### ISSUE TITLE
Not correctly typing class instance with protected properties/methods when passing as prop

### ISSUE THREAD

**Issue by CreatedBySeb** [johnsoncodehk/volar#643]
I'm currently working with an SFC UserCard, which takes an instance of a User class and renders it. This User object comes from a separate API library and has protected properties and methods. When I pass a User object as a property, I get an error saying that the object is missing the protected properties and methods. If I comment out the protected keywords in the typing files, there are no errors. Additionally, the code works fine in practice as Vue does not throw any runtime errors and printing `this.user instanceof User` gives the value `true`. The protected methods and properties also do still exist on the objects, and can be logged.

**Comment by johnsoncodehk** [comment]
Please provide a repro case so I can check the problem, btw it seems a types problem not volar problem.

**Comment by CreatedBySeb** [comment]
I've published a minimal reproduction based on Vite's vue-ts template here: https://github.com/CreatedBySeb/volar-prop-typing-repro

When I was creating the reproduction, I also tried both the composition API and script setup, neither of which had this issue, so this seems to be a problem solely with using the defineComponent function to supply the class instance.

**Comment by johnsoncodehk** [comment]
`sampleInstance` deconstruct by `data` option of `defineComponent` in template, I'm not sure if this is the expected behavior, you can report to vue-next repo.

Just FWI @pikax.
