### ISSUE TITLE
Circular references between Vue 3 components cannot be resolved

### ISSUE THREAD

**Issue by benruehl** [johnsoncodehk/volar#644]
We have two components that import each other. This works fine in Vue but leads to lots of errors inside the components' templates displayed in vscode.

We use Vue 3 single-file components with `setup` tag.
Our components look roughly like this:

**MonitorChain.vue**
```html
<template>
  <MonitorChainDialog v-if="condition"/>
</template>

<script setup lang="ts">
import MonitorChainDialog from '@/components/MonitorChainDialog.vue'
// ...
</script>
```

**MonitorChainDialog .vue**
```html
<template>
  <MonitorChain/>
</template>

<script setup lang="ts">
import MonitorChain from '@/components/MonitorChain.vue'
// ...
</script>
```

The displayed errors look like this:

![image](https://user-images.githubusercontent.com/17962788/139231130-bcd82293-afac-4236-84db-3f0ab3409159.png)

Every property and imported component of both of the components is marked with "Cannot find name 'X'".

**Comment by johnsoncodehk** [comment]
This is expected behavior of TypeScript. You need to change your implementation if use TS. (Change to JS / GlobalComponent / merge to single component...)

<img width="1286" alt="螢幕截圖 2021-10-30 下午10 16 25" src="https://user-images.githubusercontent.com/16279759/139536598-ad16895a-d3bd-4b17-8b31-3264c8134f06.png">

**Comment by benruehl** [comment]
Thank you for the quick response.

If it would be an issue with typescript why does the typescript compiler run successfully then?
Just to remember: The app builds and runs perfectly fine. There are no runtime or compile time errors.
In addition, we opened the project in Webstorm which does not have any issues with it either.

**Comment by munir-uct** [comment]
This is only a problem in .vue and .ts files where setup returns exports. If you write your vue code in tsx where setup returns a render function, mutually recursive components work, and type checking works too.

`Foo.tsx`
```tsx
import { defineComponent, ref } from "vue";
import Bar from "./Bar";

interface FooProps {
    a: number;
}

export default defineComponent<FooProps>({
    setup(props) {
        const x = ref(0);
        return () => <Bar a={x.value} />;
    },
});
```

`Bar.tsx`
```tsx
import { defineComponent, ref } from "vue";
import Foo from "./Foo";

interface BarProps {
    a: number;
}

export default defineComponent<BarProps>({
    setup(props) {
        const x = ref(0);
        return () => <Foo a={x.value} />;
    },
});
```

The above code works without any type checking errors. So if you really want proper type-checking, tsx is really great. But the downside of tsx is that I can't use vue directives like `v-if` and `v-for` and nice syntactic sugars like `<template #slot>`.

**Comment by profound7** [comment]
This is only a problem in .vue and .ts files where setup returns exports. If you write your vue code in tsx where setup returns a render function, mutually recursive components work, and type checking works too.

`Foo.tsx`
```tsx
import { defineComponent, ref } from "vue";
import Bar from "./Bar";

interface FooProps {
    a: number;
}

export default defineComponent<FooProps>({
    setup(props) {
        const x = ref(0);
        return () => <Bar a={x.value} />;
    },
});
```

`Bar.tsx`
```tsx
import { defineComponent, ref } from "vue";
import Foo from "./Foo";

interface BarProps {
    a: number;
}

export default defineComponent<BarProps>({
    setup(props) {
        const x = ref(0);
        return () => <Foo a={x.value} />;
    },
});
```

The above code works without any type checking errors. So if you really want proper type-checking, tsx is really great. But the downside of tsx is that I can't use vue directives like `v-if` and `v-for` and nice syntactic sugars like `<template #slot>`.

**Comment by profound7** [comment]
I found a workaround to beat the typechecker, but you cannot use `<script setup lang="ts">`. You have to use `<script lang="ts">`.

`Foo.vue`
```vue
<template>
    <Bar :a="x" />
</template>

<script lang="ts">
import { defineComponent, DefineComponent, ref } from "vue";
import Bar, { BarProps } from "./Bar";

export interface FooProps {
    a: number;
}

export default defineComponent({
    setup() {
        const _Bar: any = Bar; // putting directly in return doesn't work
        const x = ref(0);
        return {
            Bar: _Bar as DefineComponent<BarProps>,
            x,
        };
    }
});
</script>
```

`Bar.vue`
```vue
<template>
    <Foo :a="x" />
</template>

<script lang="ts">
import { defineComponent, Component, ref } from "vue";
import Foo, { FooProps } from "./Foo";

export interface BarProps {
    a: number;
}

export default defineComponent({
    setup() {
        const _Foo: any = Foo; // putting directly in return doesn't work
        const x = ref(0);
        return {
            Foo: _Foo as DefineComponent<FooProps>,
            x,
        };
    }
});
</script>
```

Typechecking of the Foo and Bar props work as expected. Perhaps script setup could apply this additional transformation to get typechecking to work?

**Comment by profound7** [comment]
I found a way to get it to work with script setup.

`Foo.vue`
```vue
<template>
    <Bar :a="x" />
</template>
<script setup lang="ts">
import { defineAsyncComponent, DefineComponent, ref } from "vue";
import type { BarProps } from "./Bar.vue";

export interface FooProps {
    a: number;
}

const Bar = defineAsyncComponent<DefineComponent<BarProps>>(() => import("./Bar.vue") as any);
const x = ref(0);
</script>
```

Simply defining an async component will cause recursive type definitions between the two components, and the type checker will give up. You prevent recursion by typing the module as `any`, and you enable type checking using `DefineConponent<BarProps>`.

Hope this helps whoever is trying to get recursive components working.

**Comment by zigomir** [comment]
@profound7 thanks, works perfectly :)

Since Volar as VSC extension doesn't really have docs I wonder where this could be documented 🤔

**Comment by johnsoncodehk** [comment]
@zigomir nice to have a pr for add it to https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#note. :)

**Comment by Glandos** [comment]
Sorry to dig up this old things, but I'm using a different solution, and it might be clearer. It requires [Vue 3.3](https://vuejs.org/api/sfc-script-setup.html#defineoptions)
`Foo.vue`
```vue
defineOptions({
  components: { Bar: defineAsyncComponent(() => import('./Bar.vue')) }
})
```

`Bar.vue`
```vue
defineOptions({
  components: { Foo: defineAsyncComponent(() => import('./Foo.vue')) }
})
```

It's not even required to do this in both, only one.
