### ISSUE TITLE
Setup for Vue2: Template type-checking do support Vue.extend with TypeScript

### ISSUE THREAD

**Issue by lvjiaxuan** [johnsoncodehk/volar#647]
![微信截图_20211029163212](https://user-images.githubusercontent.com/11309921/139404151-510c83fc-d1d7-4725-99cf-115cc4b0356e.png)

Is that Doc should be more clearer?

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/66#issuecomment-782110095.
