### ISSUE TITLE
Throws "Volar - API" errors on text completion

### ISSUE THREAD

**Issue by Jaeiya** [johnsoncodehk/volar#65]
While editing a Vue file, the following messages are spammed in the console. As far as I can tell, this is only happening with **Volar** `v0.21.7` and the latest version of VSCode `v1.53.2`.

As far as I'm aware, I didn't get this issue with VSCode `v1.53.0`. But as I didn't do any extensive testing with the different versions of VSCode, I'm not entirely sure.

**The errors being spammed:**
![image](https://user-images.githubusercontent.com/2054218/108442653-3d62ef00-720c-11eb-90b5-0b76a6312970.png)

**Comment by johnsoncodehk** [comment]
the problem come from this change: https://github.com/johnsoncodehk/volar/commit/a2c952d600365012a94bd6a0a6978ef262382104#diff-3b64df4c409d958bfc2667ea4ba9eedac86dca165cd428aa9824a315a464d7beR367

fixed in 0.21.8, thanks for report!
