### ISSUE TITLE
Provide API to generate script setup virtual code for type-check

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#650]
I just remembered it. 🙈 Open an issue for tracking.

Implement https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/668#issuecomment-947864995.

**Comment by filimon-danopoulos-stratsys** [comment]
Do you have a rough ETA on this? I am working on a Webpack build that will be shared to all teams at the company I work at that utilizes ForkTsCheckerPlugin to get typing of .vue files and I am wondering if it is worth the time to build a workaround in the mean time.

**Comment by johnsoncodehk** [comment]
@filimon-danopoulos-stratsys I planed to implement and release in weekend.
