### ISSUE TITLE
Bug: volar does not unwrap ref from imports

### ISSUE THREAD

**Issue by Shigma** [johnsoncodehk/volar#651]
![image](https://user-images.githubusercontent.com/33423008/139587910-f55d7f56-b53d-413d-b8f0-6cbe44fb5d95.png)

The code above works properly but volar reports error.

![image](https://user-images.githubusercontent.com/33423008/139587939-adc3276b-7893-4c89-846d-74eeee190ef0.png)

The code above shows no error but will not work because the actual `store` is not a ref.

**Comment by Shigma** [comment]
Related versions:

- vue: 3.2.20
- volar: 0.28.10

**Comment by johnsoncodehk** [comment]
Please provide a minimum reproduce.
