### ISSUE TITLE
Support for SCSS selector concatenation

### ISSUE THREAD

**Issue by nachtfunke** [johnsoncodehk/volar#652]
I'm rather new to this ecosystem in general, but I found those little hints in components very helpful, that mark whether a selector is matching or not. But it seems like they fail on basic selector concatenation:

![image showing scss code with wrong referenc-hints](https://user-images.githubusercontent.com/4201323/139590301-9d612822-808d-483b-b3e0-7831e5557fc5.png)

But it would be very helpful, if it were able to understood the selectors that were written here. It also doesn't understand `&.`, it looks like it just goes by the string of the selector itself, which isn't as helpful, as it could be. Maybe there's a chance this could be improved upon?

So I am not sure if this is even the right place to post this, I'm sorry if it isn't!

**Comment by johnsoncodehk** [comment]
Thanks for your proposal, but will not implement at current stage, this a large work, see https://github.com/johnsoncodehk/volar/issues/157#issuecomment-826301783.

When I can develop this project full-time, I will plan this feature.
