### ISSUE TITLE
intellisense suggestions of kebabCase props is incorrectly converted to dash-case prop?

### ISSUE THREAD

**Issue by jdheeter** [johnsoncodehk/volar#653]
It seems that Volar is incorrectly converting the format of the prop?
![image](https://user-images.githubusercontent.com/2530957/139610238-7fe6d931-226b-4754-acc0-934c2a9e48b6.png)

here is the prop definition in rightMenu.vue
![image](https://user-images.githubusercontent.com/2530957/139610254-38bb5a4b-fd3c-414f-a133-ae0d0101ad72.png)

using Quasar and Pug template

**Comment by johnsoncodehk** [comment]
`page-title` and `pageTitle` both is valid, see https://v3.vuejs.org/guide/component-props.html#prop-casing-camelcase-vs-kebab-case.

Volar automatic detect current prop casing for auto-complete when you open a vue document. You click <img width="134" alt="螢幕截圖 2021-11-01 上午10 34 25" src="https://user-images.githubusercontent.com/16279759/139613711-fd3cd151-bd53-467b-bb6b-ca2cab8d779a.png"> from status bar to change it.

And you also can change the detect behavior by `volar.completion.preferredAttrNameCase` setting.
