### ISSUE TITLE
Broken syntax highlighting when using "instanceof" or "typeof"

### ISSUE THREAD

**Issue by MBuchalik** [johnsoncodehk/volar#656]
When using the `instanceof` or `typeof` operator in the template, syntax highlighting breaks. I have tested it in Volar `0.28.10`.

(I wouldn't consider it a big issue since you can easily avoid this problem by creating a simple function in your TS part.)

Example for `instanceof`:

``` vue
<template>
  <div v-if="foo instanceof someConstructor">Hello</div>
</template>

<script setup lang="ts">
const foo = {};
const someConstructor = Element;
</script>
```

![grafik](https://user-images.githubusercontent.com/8061217/139832503-b5b8510f-cb85-417a-a200-809c737ced15.png)

Example for `typeof`:

``` vue
<template>
  <div v-if="typeof foo !== 'string'">Hello</div>
</template>

<script setup lang="ts">
const foo = 'bar';
</script>
```

![grafik](https://user-images.githubusercontent.com/8061217/139832605-1c48d808-342c-4656-88a7-c82f6ec161d5.png)

For some reason, using `===` instead of `!==` does not have this problem:

![grafik](https://user-images.githubusercontent.com/8061217/139832739-93c65e07-1a77-4253-a07b-e9f433e3501c.png)

---

**Comment by johnsoncodehk** [comment]
Thanks for the report. This is upstream problem, see #520.
