### ISSUE TITLE
Cannot find name when import an array from file

### ISSUE THREAD

**Issue by polly3d** [johnsoncodehk/volar#657]
It will break all variables or methods recognization when importing an array from a file in the script setup section.

### Example

An array from router/index.ts

![image](https://user-images.githubusercontent.com/11608965/139834813-c66b7df2-cb2c-42ee-9584-72cfd84d4578.png)

A component Index.vue

![image](https://user-images.githubusercontent.com/11608965/139834671-ec68add1-9bba-47d7-a838-1534771d0816.png)

### Expected behavior

No issue showing on the editor

### Actual behavior

Break all variables or methods recognization and show  errors.

![image](https://user-images.githubusercontent.com/11608965/139835155-5af42445-27a5-4f88-906e-01912e7d372b.png)

**Comment by johnsoncodehk** [comment]
I think `router/index.ts` and `Index.vue` refer to each other. You cannot do this in TS.

Related: #644, #655
