### ISSUE TITLE
Add support of PropType checking in Vue 2

### ISSUE THREAD

**Issue by Hope410** [johnsoncodehk/volar#66]
Thank you for very useful extension, it helps me a lot.
And it would be more helpful if you add PropType checking like when project uses vue 3.
Currently this feature doesn't support vue 2 projects :(

![image](https://user-images.githubusercontent.com/19515610/108498937-9db26900-72be-11eb-91ec-0c178c2f49b5.png)

![image](https://user-images.githubusercontent.com/19515610/108498841-7fe50400-72be-11eb-95df-3418caa96ca5.png)

**Comment by johnsoncodehk** [comment]
hi @Hope410, you already can use PropType form `@vue/composition-api` module. I'm not sure which part you are missing, so here is a example:

```ts
import { defineComponent, PropType } from '@vue/composition-api'

export default defineComponent({
  props: {
    foo: Object as PropType<AnyTypeYouWant>
  }
})
```

**Comment by johnsoncodehk** [comment]
follow your pics, it seem your problem is the component can't infer BtnTheme correctly.

as I know defineComponent from vue2(`@vue/composition-api`) and vue3(`@vue/runtime-dom`) has different behavior. If you wan to the defineComponent from `@vue/composition-api` has follow `@vue/runtime-dom` behavior, you need to have a shim script:

```ts
declare module '@vue/composition-api' {
  export * from '@vue/composition-api/dist'
  export { defineComponent } from '@vue/runtime-dom'
}
```

**Comment by Hope410** [comment]
> hi @Hope410, you already can use PropType form @vue/composition-api module. I'm not sure which part you are missing, so here is a example:

I use PropType from vue import and don't use defineComponent from @vue/composition-api.
![image](https://user-images.githubusercontent.com/19515610/108503983-4b754600-72c6-11eb-9caa-b65eaeaf9a1c.png)

**Comment by johnsoncodehk** [comment]
have you try defineComponent? as I know PropType only work for defineComponent, but not Vue.extend.

**Comment by Hope410** [comment]
>as I know PropType only work for defineComponent, but not Vue.extend.

PropType from vue works as well.

So, i used defineComponent, and prop type infered correctly, thanks. But could you add support of Vue.extend? It would be very helpful for vue2 + typescript users, i think most of them use Vue.extend

**Comment by johnsoncodehk** [comment]
PropType from `vue` can only work for `this` type inside `Vue.extend({ ... })`, but not working for `$props`:

```ts
import Vue, { PropType } from 'vue';

const A = Vue.extend({
  props: {
    foo: String,
  },
});
const a = new A();

a.$props.foo // any
```

check the source code, `Vue.extend` seem do nothing for `$props` types infer: https://github.com/vuejs/vue/blob/dev/types/vue.d.ts#L34

I'm not sure dose they have plan to improve `Vue.extend` types or not, anyway this is upstream problem.

**Comment by Hope410** [comment]
I understood, anyway, thank you!

**Comment by dynamite-ready** [comment]
Somehow, Prop checking worked for me in Vue 2 (Nuxt), while using `Vue.extends({})`:

![image](https://user-images.githubusercontent.com/1124008/132261362-3e6d7674-9cba-4ba4-b3ec-5c29b029994d.png)

The docs for Volar say this shouldn't work, no?,

**Comment by johnsoncodehk** [comment]
@dynamite-ready The type inference provided by `Vue.extend` is very limited. For example, cross-component props type-checking is not supported.
