### ISSUE TITLE
Volar not picking up vite-plugin-pwa types

### ISSUE THREAD

**Issue by TheDutchCoder** [johnsoncodehk/volar#661]
With the following config, Volar doesn't resolve the `vite-plugin-pwa` types when the root directory of our monorepo is opened in VSCode. It **does work** if I open the app as the root in VSCode.

Reference for the vite plugin IDE integration: https://vite-plugin-pwa.netlify.app/guide/faq.html#ide-errors-cannot-find-module-ts2307

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client", "node", "jest", "vite-plugin-pwa/client"],
    "skipLibCheck": true,
    "paths": {
      "#/*": ["./src/*"],
      "#api": ["./src/api"],
      "#components/*": ["./src/components/*"],
      "#chalk2/*": ["./src/chalk2/*"],
      "#composables/*": ["./src/composables/*"],
      "#constants": ["./src/constants"],
      "#graphql/*": ["../api/graphql/*"],
      "#layouts/*": ["./src/layouts/*"],
      "#models": ["../api/models"],
      "#pages/*": ["./src/pages/*"],
      "#services/*": ["./src/services/*"],
      "#store/*": ["./src/store/*"],
      "#types/*": ["../api/types/*"],
      "#utils": ["./src/utils"]
    },
    "allowJs": true,
    "outDir": "dist"
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

**Comment by johnsoncodehk** [comment]
Please provide a minimum reproduce, thanks.

**Comment by TheDutchCoder** [comment]
Can you tell me what specifically you're looking for?
I can see if I maybe can make a quick repo with nested apps in it, just like ours?

**Comment by johnsoncodehk** [comment]
> I can see if I maybe can make a quick repo with nested apps in it, just like ours?

Yes please provide it, and describe what you expected but what you actually got.

**Comment by TheDutchCoder** [comment]
Here you go: https://github.com/TheDutchCoder/volar-ts-issue

## Instructions
1. `npm ci` in the `sub-folder`
2. Open the project at the root folder in VSCode
3. Open App.vue
4. You'll see a TS error for the Vite PWA plugin (screenshot 1)

Screenshot 1
![image](https://user-images.githubusercontent.com/1668207/140235441-b6b8dcc0-d47b-42d7-a2d6-afa2d0b3b7ab.png)

1. Open the project at the `sub-folder` in VSCode
2. Open App.vue
3. The error is no longer there and `tsconfig.json` seems to be respected (screenshot 2)

Screenshot 2
![image](https://user-images.githubusercontent.com/1668207/140235518-242291d9-be0a-40de-b4f6-ce1c08ef5d60.png)

Let me know if there's more I can help with!
