### ISSUE TITLE
ts error: cannot find name "ref"

### ISSUE THREAD

**Issue by 1018715564** [johnsoncodehk/volar#663]
When I use unplugin-auto-import, a plug-in that automatically imports functions, I just write a ref and my program will report an error. How can vue-tsc solve it?

![image](https://user-images.githubusercontent.com/35763284/140314430-2633d668-0227-4c5e-9cc4-727a57ba4fee.png)

```html
<script lang="ts" setup>
const a = ref<number>(1)
</script>
```

**Comment by johnsoncodehk** [comment]
I think there already has workaround, see https://github.com/antfu/unplugin-auto-import/issues?q=cannot+find+name.
