### ISSUE TITLE
TS support for importing .vue components within .tsx files

### ISSUE THREAD

**Issue by tgriesser** [johnsoncodehk/volar#664]
Hello - have been trying my best to search & read up through existing issues but I haven't quite been able to figure this out.

When importing a `.vue` component in a `.tsx` file, for instance in what we're doing in our Cypress [component testing](https://github.com/cypress-io/cypress/blob/0422ede8a5b2d696eb764decc56d98a90f2c11eb/packages/frontend-shared/src/components/Icon.spec.tsx#L1-L13) development workflow, is it possible via configuration or otherwise to get it so that an imported Vue SFC file is picked up as a normal TypeScript component the way that it it when imported from `.vue` files? 

I've tried a few things but haven't quite been able to get this working and first wanted to check if it was even possible, or if it's something I could try patching the `typescript-vue-plugin` to support.

<img src="https://user-images.githubusercontent.com/154748/140329206-13c9133f-1bc9-4f42-9d03-75ca7c89c51a.png" width=500 />

/cc @JessicaSachs

**Comment by johnsoncodehk** [comment]
You can use [TS plugin extension](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-typescript-vue-plugin) or [take over mode](https://github.com/johnsoncodehk/volar/discussions/471).

**Comment by JessicaSachs** [comment]
Just tested. This seems to work @tgriesser

**Comment by tgriesser** [comment]
Thanks for the info @johnsoncodehk, completely missed take over mode
