### ISSUE TITLE
How to disable volar in vue2, or how to choose to disable volar

### ISSUE THREAD

**Issue by joker77877** [johnsoncodehk/volar#667]
How to disable volar in vue2, or how to choose to disable volar.

**Comment by johnsoncodehk** [comment]
See https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension.

**Comment by joker77877** [comment]
I'm not talking about disabling the volar plugin, but how to close it in the project.

**Comment by johnsoncodehk** [comment]
I think the document has already mentioned it, you can disable plugin in the workspace (your project).

<img width="636" alt="螢幕截圖 2021-11-05 下午2 07 59" src="https://user-images.githubusercontent.com/16279759/140466063-c876ddca-41a7-4a7f-ab85-47742bbd2c43.png">

**Comment by joker77877** [comment]
I don't want to close it globally, but open it in vue3 project and close it in vue2 project. The previous version has such a function.

**Comment by joker77877** [comment]
I'm sorry, I didn't see it clearly just now.

**Comment by mesqueeb** [comment]
@johnsoncodehk is there any way we can sync this setting "disable (workspace)" to the rest of the team that also uses VSCode? Or does every team member need to manually set this up?

**Comment by johnsoncodehk** [comment]
@mesqueeb Please track https://github.com/microsoft/vscode/issues/39272.

**Comment by mesqueeb** [comment]
@johnsoncodehk thanks so much! I've added my use case to that thread.
