### ISSUE TITLE
Consider using Prettier 2.x by default instead of 1.x

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#673]
I was wondering why [Volar choose Prettier 1.x](https://github.com/johnsoncodehk/volar/blob/1cc570de60982748f80791776d71745adcbf6ace/packages/server/package.json#L23) as its default version that's included as opposed to Prettier 2.x.

In general, all our files besides Vue files are formatted by Prettier 2.4+ so I was hoping that Volar would also go for Prettier 2.x by default.

---

PS: Switching to Prettier entirely is not an option for us, because we need auto formatting of `<style lang="sass">` which is only provided by Volar and cannot be provided by Prettier. : (

**Comment by johnsoncodehk** [comment]
prettyhtml is depended to prettier v1.16.4, and prettier is a big module (~20MB), so volar fixed prettier to same version to avoid include multiple prettier module in install package.

If prettier version is a problem to you, you can consider to send a PR to prettyhtml repo for update depended prettier version.
