### ISSUE TITLE
two .value experience problem (npm init vite@latest)

### ISSUE THREAD

**Issue by shawn-yee** [johnsoncodehk/volar#674]
1. no .value auto generate in .ts/.js file,only in .vue file
2. .value generate xxx.value$0 would be better,now xxx${1:.value}

**Comment by johnsoncodehk** [comment]
> 1. no .value auto generate in .ts/.js file,only in .vue file

You need to use [take over mode](https://github.com/johnsoncodehk/volar/discussions/471).

> 2. .value generate xxx.value$0 would be better,now xxx${1:.value}

Before we use `xxx.value$0`, but I think it's too noisy. For example, in this code.

```ts
const foo = ref(1);
const foooo = 2;
```

When we want to input `return foooo`, with `xxx.value$0`, user got steps:
1. User input `return foo|`
2. Volar auto changed the text to `return foo.value|`
3. User cmd + z to undo to `return foo|`
4. User input `oo` to finish

With `${1:.value}`, user got steps:
1. User input `return foo|`
2. Volar auto changed the text to `return foo.value`, but selected `.value` text
3. User input `oo` to replace selected text `.value`

But this is still noisy, we will change in future, see #334.
