### ISSUE TITLE
Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by thefoxie** [johnsoncodehk/volar#679]
Since today, Volar throws errors.
Volar version: v0.29.0 (updated today)
vscode version: 1:62:0 (updated today)

```
[Error - 12:56:11] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'lastIndexOf' of undefined
  Code: -32603 
```
```
[Error - 13:00:41] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'lastIndexOf' of undefined
  Code: -32603 
```

**Comment by johnsoncodehk** [comment]
Hi @thefoxie, I can't reproduce this problem, please provide minimal reproduction, thank you.

**Comment by yannxaver** [comment]
Very similar but not identical error here - also since yesterday. 

`[Error - 10:16:15 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property '0' of undefined
  Code: -32603`

Volar 0.29.2
vsCode 1.62.9

**Comment by IWANABETHATGUY** [comment]
@yannxaver could you offer us a minimum reproduce demo?

**Comment by thefoxie** [comment]
I don't have time right now, but I will tomorrow or the day after if that helps.

**Comment by elevatebart** [comment]
To get a repro:

clone https://github.com/cypress-io/cypress/
checkout unified-desktop-gui
yarn install
open `App.vue`
start typing in a `<script setup>` block

It worked in 0.28.10 but started failing in 0.29.0

**Comment by IWANABETHATGUY** [comment]
packages/launchpad/src/App.vuepackages/launchpad/src/App.vue

**Comment by elevatebart** [comment]
@IWANABETHATGUY exactly

packages/launchpad/src/App.vue

**Comment by elevatebart** [comment]
It actually matters very little which component

**Comment by tgriesser** [comment]
This appears to be related to the typescript version bundled with VSCode? Changing it to VSCode's shipped version (4.4.3) and you see the errors. Switch it to workspace version (in our case 4.2.4), and the errors go away.

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:2258:20)
```

**Comment by JessicaSachs** [comment]
That fixed it for us, too.

**Comment by johndanek** [comment]
Changing between VSCode's version (4.4.3) and the workspace's version (3.9.7) only changes the error from

`[Error - 12:51:01 PM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot read property '0' of undefined
  Code: -32603 `

in 4.4.3 to 

`[Error - 12:48:40 PM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot read property 'length' of undefined
  Code: -32603`

for 3.9.7

**Comment by johnsoncodehk** [comment]
Related to https://github.com/microsoft/TypeScript/pull/46105, https://github.com/microsoft/TypeScript/issues/44953.

**Comment by Hyphon** [comment]
still has this issue now...
VS Code: 1.62.2
Volar: 0.29.4
Typescript: 4.16 (also have tried 4.2.4)

**Comment by johnsoncodehk** [comment]
@Hyphon I just fixed the repro case that provide by @elevatebart. So that may not be your case.

Please let me know if there is a problem in these situations:
1. volar 0.29.4 + typescript 4.4.4
2. volar 0.29.4 + typescript 4.5.1-rc
3. [volar-0.29.5-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/7524519/volar-0.29.5-alpha.1.vsix.zip) + typescript 4.4.4

Or if you can make a repro case, I can easily check it, thanks.

**Comment by Hyphon** [comment]
> @Hyphon I just fixed the repro case that provide by @elevatebart. So that may not be your case.
> 
> Please let me know if there is a problem in these situations:
> 
> 1. volar 0.29.4 + typescript 4.4.4
> 2. volar 0.29.4 + typescript 4.5.1-rc
> 3. [volar-0.29.5-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/7524519/volar-0.29.5-alpha.1.vsix.zip) + typescript 4.4.4
> 
> Or if you can make a repro case, I can easily check it, thanks.

all those fails for me.
sry i cannot provide a repo because of network restrictions.

here is more info in my case:
vue-cli ~4.5.0
vue 2.6.14
unplugin-vue2-script-setup 0.6.12
unplugin-auto-import 0.4.13

anyway, thx for replying

**Comment by johnsoncodehk** [comment]
@Hyphon it should be a different problem. When you can provide a repro case, please open a new issue any time.
