### ISSUE TITLE
Auto Highlight and Import doesn't work

### ISSUE THREAD

**Issue by adamkif** [johnsoncodehk/volar#680]
Today, I found that auto-highlight and import doesn't work, also vscode doesn't detect my custom components, I don't know if this issue is related to Volar or not

<img width="627" alt="Screen Shot 2021-11-08 at 8 28 43 PM" src="https://user-images.githubusercontent.com/44274368/140805999-36a6c820-7e64-432e-b0da-a4134aed3ecd.png">

**Comment by adamkif** [comment]
I got this issue from my Nuxt 3 project

<img width="725" alt="Screen Shot 2021-11-08 at 11 01 56 PM" src="https://user-images.githubusercontent.com/44274368/140825299-7570ca57-dd7e-4906-8221-cba1f175af52.png">

**Comment by YDKD** [comment]
I got the same issue at `0.29.0`.

**Comment by YDKD** [comment]
This issues has not been resolved. Volar will prompt me with the following information when I imported the vue3 compositionApi. `[TS Error] Error: Debug Failure. False expression.`

**Comment by johnsoncodehk** [comment]
@YDKD This issue has nothing to do with the subject of the issue. Please open a new issue and provide minimal reproduction.

**Comment by YDKD** [comment]
I' m so apologize that this is my problem. There is an option about TS version in the bottom column of Vs Code and I 
don't know when I chosed the node_ Modules folder. Now I can use it successfully.

**Comment by johnsoncodehk** [comment]
@YDKD it should be works even you chosen node_modules TS version. :S
If you can produce a repro case I will able to survey it.

**Comment by numfin** [comment]
why is it a closed issue if it still doesn't work?
