### ISSUE TITLE
0.29.0 Appears to have broken intellisense

### ISSUE THREAD

**Issue by napei** [johnsoncodehk/volar#681]
After Volar updated to `0.29.0` I lost all intellisense and documentation for `.vue` files. Downgrading to `0.28.10` resolved this. Working on a Vue 3 project with SFC.

VSCode versions
```
Version: 1.63.0-insider (system setup)
Commit: a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8
Date: 2021-11-08T05:14:49.440Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

Not sure about providing debugging logs, can't seem to find anything in the output tab in vscode.

**Comment by adamkif** [comment]
I got the same issue, 0.28.10 works fine to me as well

**Comment by zhongyue2332** [comment]
更新前不测试的吗？ <script setup> </script> 里面的代码提示全没有了，一开始还以为vscode的问题

**Comment by frankwang1101** [comment]
0.30.1 is fine but 0.30.2 this bug come up again

**Comment by johnsoncodehk** [comment]
@frankwang1101 please track #846.
