### ISSUE TITLE
vue-tsc: Implicit 'any' with recursive component using slots

### ISSUE THREAD

**Issue by dodgex** [johnsoncodehk/volar#683]
I just built a recursive component that uses slots to show items. My component is based on [this solution](https://github.com/vuejs/vue/issues/5965#issuecomment-530731096).

While it works as expected, I now get an error from `vue-tcs` that the variable used in the template is implicitly 'any'.

```
src/Issue.vue:17:23 - error TS7022: 'el' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indir
ectly in its own initializer.

17     <template #item="{el}">
                         ~~

src/Issue.vue:18:8 - error TS2502: 'item' is referenced directly or indirectly in its own type annotation.

18       <slot name="item" :el="el"/>
          ~~~~

```

`src/Issue.vue` - This is an extremely reduced version of my component. Depending on some conditions the first or the second nested `<Issue />` block is shown. In the cases where the second `<Issue />` is shown, the `<slot />` is shown before. Adding the first `<slot />` (here commented out) it changes nothing, but having the slot at the bottom it works!
```
<template>
  <!-- Error in second block -->
  <!--  <slot name="item" :el="item"/>-->

  <Issue v-for="(child, index) in item.children" :key="index"
         :item="child">
    <template #item="{el}">
      <slot name="item" :el="el"/>
    </template>
  </Issue>

  <!-- My Construct: Error in second block -->
  <slot name="item" :el="item"/>

  <Issue v-for="child in item.children" :key="child.id"
         :item="child">
    <template #item="{el}">
      <slot name="item" :el="el"/>
    </template>
  </Issue>

  <!-- No Error! -->
  <!--  <slot name="item" :el="item"/>-->
</template>

<script setup lang="ts">
type TreeItem = {
  id: number,
  name: string,
  children?: TreeItem[],
}

withDefaults(defineProps<{
  root?: boolean,
  item: TreeItem,
}>(), {
  root: false,
});
</script>
```

As a workaround, I currently have the slot wrapped in a `<template v-if="false">` at the bottom of my component. But i hope that there is a fix possible in vue-tsc.

Here is a `package.json` i used with the file above to test this issue.
```
{
  "name": "vue-tsc-issue",
  "version": "0.0.0",
  "scripts": {
    "verify": "vue-tsc --noEmit"
  },
  "dependencies": {
    "vue": "^3.2.6"
  },
  "devDependencies": {
    "@types/node": "^16.11.3",
    "@vitejs/plugin-vue": "^1.9.3",
    "@vue/compiler-sfc": "^3.2.20",
    "typescript": "^4.4.4",
    "vite": "^2.6.10",
    "vue-tsc": "0.29.2"
  }
}
```

**Comment by johnsoncodehk** [comment]
I think this is expected error, but the code just like this.

<img width="1084" alt="螢幕截圖 2021-11-11 上午2 37 02" src="https://user-images.githubusercontent.com/16279759/141173123-a842f50a-166e-4e80-b5a7-c3d847aed1f4.png">

You can use `: any` type annotation to avoid error.

```html
<Issue v-for="child in item.children" :key="child.id" :item="child">
  <template #item="{ el }: any">
    <slot name="item" :el="el" />
  </template>
</Issue>
```

**Comment by dodgex** [comment]
Thank you for your response. When I do this I get an "Unresolved type any" (weak) warning in IntellIJ, but this is not a vue-tsc/volar issue, and way better than a failing build.

**Comment by stijn-gravity** [comment]
@johnsoncodehk 

This doesn't solve every issue and doesn't answer the question directly. It's important that we are able to ignore lines of code using @ts-ignore or @ts-nocheck but from what I can find there is no support for this. Am I missing something or is this intended?

**Comment by johnsoncodehk** [comment]
@stijn-gravity just for record, `@ts-nocheck` is already supported since v0.40.0.
