### ISSUE TITLE
Font color issues

### ISSUE THREAD

**Issue by meanspa** [johnsoncodehk/volar#685]
I'm not sure if this is a Volar issue  or just a VSCode issue. Font colors aren't behaving correctly for me in single file components (see images):

![image](https://user-images.githubusercontent.com/403478/141214735-55b753c6-6042-4dbf-85b6-21db0e234989.png)
![image](https://user-images.githubusercontent.com/403478/141215030-8497abf4-91cb-4736-8a0e-3d41e4ab3d24.png)

If I adjust the indentation of that line, the colors change according to the column the characters are in. Right now Volar is the only extension I have enabled which is why I'm sharing this here, with all extensions disabled I can't seem to reproduce it in plain JS files. 

VSCode version: 1.62.1
Volar version: 0.29.3

Edit: more details in case they're helpful -
MacOS 12.0.1

**Comment by bitrevo** [comment]
Same issue here.
Version 0.29.1, 0.29.2, 0.29.3 are also affected.
Rollback to Volar version 0.29.0 as workaround for this issue.

**Comment by johnsoncodehk** [comment]
Thanks for your report. I can't reproduce this problem, can you reproduce it in https://github.com/johnsoncodehk/volar-starter?

**Comment by liqilong1997** [comment]
I have the same problem, maybe even worse, as shown in the following image, the color of the code and the underlining pointing to it are mispla
![Uploading 截屏2021-11-11 上午11.55.29.png…]()
c

**Comment by liqilong1997** [comment]
I have the same problem, maybe even worse, as shown in the following image, the color of the code and the underlining pointing to it are misplaced
<img width="442" alt="截屏2021-11-11 上午11 55 29" src="https://user-images.githubusercontent.com/42129409/141244716-aa5002e1-c4de-4e7a-8ded-e14c45048bf6.png">


VSCode version: 1.62.1
Volar version: 0.29.3

Edit: more details in case they're helpful -
MacOS 12.0.1

**Comment by bitrevo** [comment]
Seems like it only happened on non-typescript project.
I am able to reproduce it in vite starter project. (no typescript support)

```
npm init vite@latest my-vue-app -- --template vue
```

**Comment by johnsoncodehk** [comment]
@bitrevo I can see the problem now, thanks!

**Comment by meanspa** [comment]
Can confirm this appears to be fixed in 0.29.4. Much thanks @johnsoncodehk!
