### ISSUE TITLE
[vue-tsc] How to use with lint-stage

### ISSUE THREAD

**Issue by 1018715564** [johnsoncodehk/volar#686]
I want to use vue-tsc for type checking in vue.
I want to use lint-stage now, but vue-tsc can't seem to find my tsconfig.json

```
  "lint-staged": {
    "*.{ts,tsx}": [
      "prettier --write",
      "eslint --fix",
      "tsc --noEmit --pretty false --skipLibCheck",
      "git add"
    ],
    "*.{json,js,jsx}": [
      "prettier --write",
      "eslint --fix",
      "git add"
    ],
    "*.vue": [
      "prettier --write",
      "eslint --fix",
      "vue-tsc --noEmit --skipLibCheck",
      "git add"
    ]
  },
```

I want to verify only the vue file in the temporary storage area. Do you know how to do it?

**Comment by 1018715564** [comment]
this is demo: https://github.com/seho-code-life/project_template/tree/vue3-vite2-ts-template(dev)

**Comment by Shinigami92** [comment]
Are you sure that this will work?
As far as I know `lint-stage` passes each touched file individually to the command.
But `vue-tsc` needs the whole context starting from `src/main.ts`, does it?
In worse case you start `vue-tsc` for **each** file and if you have 100 files, it will check the project 100 times

**Comment by 1018715564** [comment]
yes, i agree

I know that vue-tsc will recheck the entire program, but is there a better way to check vue files?

**Comment by Shinigami92** [comment]
Maybe just use `precommit` 🤔 

See https://github.com/okonet/lint-staged/issues/185

**Comment by 1018715564** [comment]
But what I use now is pre_commit 😭
Does vue-tsc plan to do type checking on a batch of vue files in the future?

**Comment by johnsoncodehk** [comment]
@1018715564 Please treat vue-tsc as just tsc, maybe tsc can specify files in cli, I think there have been some discussions: https://github.com/okonet/lint-staged/issues/468

**Comment by 1018715564** [comment]
I already have an optimal lint-stage configuration. If anyone needs it, just use vue-tsc as tsc.

```js
// lint-staged.config.js
module.exports = {
  '*.{ts,tsx}': ['prettier --write', 'eslint --fix', 'tsc --noEmit'],
  '*.vue': ['prettier --write', 'eslint --fix', 'vue-tsc --noEmit'],
  '*.{json,js,jsx}': ['prettier --write', 'eslint --fix']
}

```

```json
 "scripts": {
   "lint-staged": "lint-staged",
 }
```

**Comment by joker77877** [comment]
> I already have an optimal lint-stage configuration. If anyone needs it, just use vue-tsc as tsc.
> 
> ```js
> // lint-staged.config.js
> module.exports = {
>   '*.{ts,tsx}': ['prettier --write', 'eslint --fix', 'tsc --noEmit'],
>   '*.vue': ['prettier --write', 'eslint --fix', 'vue-tsc --noEmit'],
>   '*.{json,js,jsx}': ['prettier --write', 'eslint --fix']
> }
> ```
> 
> ```json
>  "scripts": {
>    "lint-staged": "lint-staged",
>  }
> ```

This configuration is still wrong.

**Comment by 1018715564** [comment]
> 

I run this configuration successfully without errors; you can send out the error to see

**Comment by joker77877** [comment]
This is your demo.
![image](https://user-images.githubusercontent.com/62642184/144378839-0c0fc068-e740-48c2-91c7-42c59e03aeac.png)

**Comment by 1018715564** [comment]
> This is your demo. ![image](https://user-images.githubusercontent.com/62642184/144378839-0c0fc068-e740-48c2-91c7-42c59e03aeac.png)

please https://github.com/seho-code-life/project_template/issues/new

It has nothing to do with volar, we can change a place

**Comment by ningrunting** [comment]
Any update, I still have same issue with lint-stage

**Comment by Yill625** [comment]
it's ok!
vue-tsc version 0.29.3
```js
//.lintstagedrc.js
const fs = require('fs')
const generateTSConfig = (stagedFilenames) => {
  return (type) => {
    return `${type} --noEmit --skipLibCheck`
  }
}

module.exports = {
  'src/**/*.{js,jsx,vue,ts,tsx}': ['yarn lint'],
  '*.{vue,ts}': [(fileName) => generateTSConfig(fileName)('vue-tsc')],
}
```

**Comment by Roc-zhou** [comment]
> 我想使用 vue-tsc 在 vue 中进行类型检查。 我现在想使用 lint-stage，但是 vue-tsc 似乎找不到我的 tsconfig.json
> 
> ```
>   "lint-staged": {
>     "*.{ts,tsx}": [
>       "prettier --write",
>       "eslint --fix",
>       "tsc --noEmit --pretty false --skipLibCheck",
>       "git add"
>     ],
>     "*.{json,js,jsx}": [
>       "prettier --write",
>       "eslint --fix",
>       "git add"
>     ],
>     "*.vue": [
>       "prettier --write",
>       "eslint --fix",
>       "vue-tsc --noEmit --skipLibCheck",
>       "git add"
>     ]
>   },
> ```
> 
> 我只想验证临时存储区的vue文件。你知道怎么做吗？

"scripts": {
    "lint": "vue-tsc --noEmit && eslint --ext .vue,.js,.ts,.jsx,.tsx --fix",
  },

**Comment by Roc-zhou** [comment]
> 我想使用 vue-tsc 在 vue 中进行类型检查。 我现在想使用 lint-stage，但是 vue-tsc 似乎找不到我的 tsconfig.json
> 
> ```
>   "lint-staged": {
>     "*.{ts,tsx}": [
>       "prettier --write",
>       "eslint --fix",
>       "tsc --noEmit --pretty false --skipLibCheck",
>       "git add"
>     ],
>     "*.{json,js,jsx}": [
>       "prettier --write",
>       "eslint --fix",
>       "git add"
>     ],
>     "*.vue": [
>       "prettier --write",
>       "eslint --fix",
>       "vue-tsc --noEmit --skipLibCheck",
>       "git add"
>     ]
>   },
> ```
> 
> 我只想验证临时存储区的vue文件。你知道怎么做吗？

"scripts": {
    "lint": "vue-tsc --noEmit && eslint --ext .vue,.js,.ts,.jsx,.tsx --fix",
  },

"lint-staged": {
    "*.{js,vue,ts,jsx,tsx}": [
      "prettier --write",
      "npm run lint"
    ]
  }

**Comment by aalexlin** [comment]
See https://github.com/okonet/lint-staged/issues/468#issuecomment-605102567

**Comment by karladler** [comment]
> See [lint-staged/lint-staged#468 (comment)](https://github.com/lint-staged/lint-staged/issues/468#issuecomment-605102567)

This is just omitting the arguments, so ALL files are running with vue-tsc, while we explicitly want ONLY to check the staged files. 
The problem seems, that the command is not accepting `-p` config together with files selection.

> error TS5042: Option 'project' cannot be mixed with source files on a command line.
