### ISSUE TITLE
vue-tsc so slow 

### ISSUE THREAD

**Issue by QQhuan** [johnsoncodehk/volar#687]
Every time I use `vue-tsc --noEmit --skipLibCheck && vite --host` to start my project，it takes me a long time. 
Any tips to speed up?
Thank u for your reply!

**Comment by johnsoncodehk** [comment]
The check time is related to the number of files that need to be checked, so please make sure that `include` only lists the files that need to be checked directly.

On the other hand, if you do not need to check the template, future versions will provide the option to disable it, which will reduce the check time by half. (Track #577)
