### ISSUE TITLE
pug: code folding/collapse for big regions has to low offset

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#688]
When having a blank line in a region, it doesn't collapse the whole tag-tree

https://user-images.githubusercontent.com/7195563/141366362-ad13564f-f363-487f-83f7-e77d90598dd3.mp4

Repro:

```pug
div
  div 1

  div 2
```

**Comment by Shinigami92** [comment]
It's not perfect, but much better then before 🙂 
I think (at least for me) it's okay for now 👍

**Comment by johnsoncodehk** [comment]
@Shinigami92 Are there unhandled edge cases?

**Comment by Shinigami92** [comment]
Yes, like:

https://user-images.githubusercontent.com/7195563/141466620-167f9f14-231e-4415-8759-7f965e5b1a31.mov

Running with `"vue-tsc": "~0.29.4"`

At the end of the video I use shift + click to collapse all nested at once
Ignore errors, I currently working on things with i18n :D

**Comment by johnsoncodehk** [comment]
@Shinigami92 could you provide reproduce code?

**Comment by Shinigami92** [comment]
> @Shinigami92 could you provide reproduce code?

I will try over weekend

**Comment by Shinigami92** [comment]
Sry, didn't had time ^^'
Hope I find time next days, but also will try out your newest change tomorrow at work

**Comment by Shinigami92** [comment]
Using `~0.29.5` it works perfectly 🤩
