### ISSUE TITLE
CSS Ignore in style block

### ISSUE THREAD

**Issue by JohnCampionJr** [johnsoncodehk/volar#69]
OK, one more thing and then I'll stop :)

I have css.validate disabled in VS Code because it throws errors on Tailwind CSS's `@apply`

It seems like this setting is ignored in volar's parsing of CSS blocks.  This bit of style throws a variety of css errors.

Both lines throw `semi-colon expectedcss(css-semicolonexpected)` and `at-rule or selector expectedcss(css-ruleorselectorexpected)`

Is there any way to have volar not pass along the CSS for validation?

```css
<style scoped>
li :deep(a.router-link-exact-active) {
  @apply text-white bg-opacity-25;
}

li a {
  @apply flex flex-row items-center;
}
</style>

```

**Comment by johnsoncodehk** [comment]
you can use `@vue-ignore`, see: https://github.com/johnsoncodehk/volar#using

btw maybe I will change to `css.validate`, I'm considering.

**Comment by JohnCampionJr** [comment]
Does `css.validate` support monorepo now in VS Code, in normal use?

**Comment by johnsoncodehk** [comment]
> can it be set any more granular than that?

As I know it can't.

I'm not sure the final solution now, if has a replacement we should make sure it's a better way. `css.validate` cannot completely replace `@vue-ignore`, so I would like keep `@vue-ignore` way at least for now.

btw we will support postcss in future, and I personally recommend you join Discord group for discussion.

**Comment by johnsoncodehk** [comment]
postcss is supported in 0.21.12.

**Comment by chojnicki** [comment]
> I'm not sure the final solution now, if has a replacement we should make sure it's a better way. css.validate cannot completely replace @vue-ignore, so I would like keep @vue-ignore way at least for now.

Actually separate option for disabling CSS validation globally like in Vetur would be nice :) Adding extra line "@vue-ignore" in every file just to remove wrong IDE warning is not elegant solution.

**Comment by johnsoncodehk** [comment]
@chojnicki I know @vue-ignore is annoying.. sorry. but also need to consider consistency support verification with command line tool. `@vue-ignore` support IDE and cmd, but global IDE option only work for IDE. I need to avoid confusion.

The standalone option can still be considered, I just need to solve the monorepo and cmd problem.

btw you can also use `lang="postcss"` to avoid error, it should better then `@vue-ignore` for you.

**Comment by johnsoncodehk** [comment]
in 0.21.20 you can config `"volar.style.defaultLanguage": "postcss"` in vscode for experimental. please let me know it's good or not.

for command line tool I can also add default language option so not a problem, but I may have to give up monorepo support.

**Comment by chojnicki** [comment]
I did not know that I can replace scss/sass with postcss alone. It was good idea since Tailwind has it build in, so no need for scss packages.

After changing to `<style lang="postcss">` it works fine ;) Thanks

**Comment by vaaski** [comment]
I am using scss and I am running into the same issue.

![image](https://user-images.githubusercontent.com/17879327/126059582-7dc01c22-fe99-4a09-932a-66dd045d81ca.png)

I went [back in time](https://github.com/johnsoncodehk/volar/blob/ce032160a1da40fcb6755d08871789ae9009968f/README.md#using) to see the referenced `@vue-ignore` tag and how to actually use it, however it doesn't seem to work anymore.
My vscode settings contain `"scss.lint.unknownAtRules": "ignore"` and  `"css.lint.unknownAtRules": "ignore"` just to make sure, but volar doesn't seem to respect these settings.

Any idea how I could hide the warnings for unknownAtRules?

**Comment by johnsoncodehk** [comment]
@vaaski you can use `lang="postcss"`

**Comment by zynth17** [comment]
> @vaaski you can use `lang="postcss"`

this is not working when we need to use it with scss tho
