### ISSUE TITLE
How to run volar with Eclipse Theia

### ISSUE THREAD

**Issue by deviceGT** [johnsoncodehk/volar#691]
I'd like to use Eclipse Theia,but I can't find volar in Eclipse Theia's extensions.
Thank you.

**Comment by johnsoncodehk** [comment]
I tried Theia but it show `The language client requires VS Code version ^1.58.0 but received version 1.53.2`, I think we need to waiting for Theia to catch up.

**Comment by FossPrime** [comment]
Here's how to side load onto Theia based cloud IDE's.
https://github.com/eclipse-theia/theia/issues/11797#issue-1421613172

Theia is worth considering as a Node LTS of sorts. If we don't gain much from targeting the bleeding edge API, it may be worth targeting the stable one for wider compatibility with Theia, CloudFlow,  CodeSandbox, CodeAnywhere, etc.
