### ISSUE TITLE
Ref transform intellisense not working

### ISSUE THREAD

**Issue by soulsam480** [johnsoncodehk/volar#693]
hii @johnsoncodehk while working with the new ref sugar, I found an issue. Not sure if it's a bug or volar doesn't have support for this yet. Please check

![image](https://user-images.githubusercontent.com/35460828/141490899-fcc377ca-a137-4066-9da5-359ca553899c.png)

as you can see above, the intellisense should be `'sink' | 'index'`, but it's something different. is it a bug ?

**Comment by johnsoncodehk** [comment]
This is `$ref` types issue, `view` can't auto-complete as possible value because it is not basic union string type.

<img width="338" alt="螢幕截圖 2021-11-13 上午12 14 55" src="https://user-images.githubusercontent.com/16279759/141498684-475e5196-d43f-479d-b933-4d3e3894c5fe.png">

**Comment by soulsam480** [comment]
thx

**Comment by huzaifahj** [comment]
@soulsam480 Better solution here: https://staging.vuejs.org/guide/extras/reactivity-transform.html#typescript-integration-ts

`env.d.ts`
```ts
/// <reference types="vue/macros-global" />
```
