### ISSUE TITLE
in .vue file template->img.src  Ctrl + Click can not jump to correct image file path because drive is lost  on windows

### ISSUE THREAD

**Issue by lisonge** [johnsoncodehk/volar#694]
![2021-11-13_11-59-56](https://user-images.githubusercontent.com/38517192/141604934-12c984cf-ddf7-4c0c-bbd5-5a7f36dd050e.gif)

correct path should be `d:/any/path`, but it jump to `/any/path`

tsconfig.json
```json
{
    "compilerOptions": {
        "target": "esnext",
        "useDefineForClassFields": true,
        "module": "esnext",
        "moduleResolution": "node",
        "strict": true,
        "jsx": "preserve",
        "sourceMap": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "lib": ["esnext", "dom"],
        "baseUrl": ".",
        "paths": {
            "@/*": ["src/*"]
        }
    },
    "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}
```

vite.config.ts
```ts
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import path from 'path';

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [vue()],
    server: {
        proxy: {
        },
    },
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './src'),
        },
    },
});

```

vscode about
```txt
Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
```

volar version
`Vue Language Features (Volar)v0.29.4`

**Comment by lisonge** [comment]
What is the solution 捏?

**Comment by soulsam480** [comment]
@lisonge are your images in `public` directory inside your project root ? If yes you have to reference them using absolute paths i.e. `/file_name` and I think the jump to file won't work as the paths are absolute.

**Comment by lisonge** [comment]
> are your images in public directory inside your project root ? 

img real path is `src/assets/01/01.png`, not in public

---

>Did you check if this worked in older versions ?

0.29.x, 0.28.x is not work

**Comment by lisonge** [comment]
i open this folder in wsl2,  then `Ctrl + Click` is work, but it is still not work on windows

**Comment by soulsam480** [comment]
Then this might be an issue with volar. Still not sure. Let's wait for @johnsoncodehk yo check
