### ISSUE TITLE
nuxt 3 component dont see props ts

### ISSUE THREAD

**Issue by productdevbook** [johnsoncodehk/volar#696]
![CleanShot 2021-11-13 at 20 27 34](https://user-images.githubusercontent.com/38668796/141653267-9dd61aa2-d712-4a04-8f1b-c30e22f0d906.png)

![CleanShot 2021-11-13 at 20 28 00](https://user-images.githubusercontent.com/38668796/141653275-186cf836-4289-4cdc-90c8-2e1e793e13c6.png)

**Comment by johnsoncodehk** [comment]
It's works for me, please provide repro case.

Just in case, if you create nuxt 3 project by `npx nuxi init nuxt3-app`, you need to add `"include": ["**/*.vue"]` to tsconfig yourself.

**Comment by productdevbook** [comment]
> "include": ["**/*.vue"]

some problem, .nuxt/components.d.ts I guess doesn't read.
![CleanShot 2021-11-15 at 07 07 22](https://user-images.githubusercontent.com/38668796/141720863-5bcbe1fe-3d6e-4da1-a7e4-eb78193f7936.png)


![CleanShot 2021-11-15 at 07 09 23](https://user-images.githubusercontent.com/38668796/141720998-486c5375-3d37-4730-bde0-8e51e4eb41a6.png)

**Comment by productdevbook** [comment]
![CleanShot 2021-11-15 at 07 16 58](https://user-images.githubusercontent.com/38668796/141721592-f3cf27ca-e226-4edc-8e80-ec8139d7dfa6.png)

**Comment by johnsoncodehk** [comment]
I think this is a project setup problem, I must have a repro case to able to check.

**Comment by productdevbook** [comment]
> I think this is a project setup problem, I must have a repro case to able to check.

https://github.com/productdevbook/nuxt3-bug/tree/bug_ts

**Comment by productdevbook** [comment]
@johnsoncodehk custom add fixed. I guess tsconfig is not detecting it. You can check.

https://github.com/productdevbook/nuxt3-bug/tree/bug_ts
![CleanShot 2021-11-17 at 20 19 52](https://user-images.githubusercontent.com/38668796/142249949-a9861183-0ea6-43f2-af59-4a99055d6d7e.png)

**Comment by productdevbook** [comment]
`"include": ["./**/*.ts", "./**/*.vue"],` delete and fixed

**Comment by johnsoncodehk** [comment]
I think `.nuxt/nuxt.d.ts` is missing `/// <reference path="components.d.ts" />`, please consider report to nuxt 3 repo.

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/2002#issuecomment-972709404
