### ISSUE TITLE
Vue SFC Custom Node Transforms

### ISSUE THREAD

**Issue by fletcherhaz** [johnsoncodehk/volar#698]
I use a custom node transform, which combined with `vue-i18n` allows me to write localized props/attributes in my html like this:
```vue
<template>
  <button
    &aria-label="app.home"
  >
    <home-icon />
  </button>
</template>
```

However, `vue-tsc` does not currently have an easy way for me to provide custom compiler options to the SFC compiler. It looks like compiler options have made their way to `tsconfig.json` recently (#615), but because node transforms are JS functions, reading from JSON won't work.

I've manage to monkey patch my version of the compiled `vue-tsc` `proxy.js` file (https://github.com/johnsoncodehk/volar/blob/master/packages/vue-tsc/src/proxy.ts#L65) with the following:

```js
function getVueCompilerOptions() {
    // Additions
    const config = path.join(path.dirname(options.options.configFilePath), 'volar.config.js');
    try {
        const configContents = require(config)
        return configContents.default
    } catch (e) {}
    // End additions
    var _a, _b;
    const tsConfig = options.options.configFilePath;
    if (typeof tsConfig === 'string') {
        return (_b = (_a = shared.createParsedCommandLine(ts, ts.sys, tsConfig).raw) === null || _a === void 0 ? void 0 : _a.vueCompilerOptions) !== null && _b !== void 0 ? _b : {};
    }
    return {};
}
```

This seems to work (because most of my errors have gone away).

I realize this is all in flux and introducing a config file can complicate things, but I'm wondering if there is a chance something along these lines (supporting javascript for compiler options config) could be included?

**Comment by johnsoncodehk** [comment]
You can use `experimentalTemplateCompilerOptionsRequirePath` option, but it's experimental, it may be changed in the future.

```js
// myCompilerOptions.js
exports.default = {
  "compatConfig": { "MODE": 2 }
}
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    ...
  },
  "vueCompilerOptions": {
    "experimentalCompatMode": 2,
    "experimentalTemplateCompilerOptionsRequirePath": "./myCompilerOptions"
  }
}
```

**Comment by fletcherhaz** [comment]
Brilliant! Thank you!
