### ISSUE TITLE
Language server immediately crashes when trigger request at incomplete TS code

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#699]
```vue
<script lang="ts">
defineProps({
  props: {
    name: String as PropType< // <- input ' here
  }
});
</script>
```

**Comment by soulsam480** [comment]
I had seen this issue multiple times, but thought this is not a volar issue, sorry should've reported earlier.

**Comment by johnsoncodehk** [comment]
@soulsam480 this is TS problem not volar problem, but volar should not crashes when TS occur error, so I will just add try catch to all TS requests. :)

> This also happened when I added an incomplete css/scss code inside the style block.

Could you provide repro code?

**Comment by soulsam480** [comment]
Sure is it fine if I give it to you around 9:30 HKT?

**Comment by johnsoncodehk** [comment]
> Sure is it fine if I give it to you around 9:30 HKT?

Of course. :)

**Comment by soulsam480** [comment]
> > Sure is it fine if I give it to you around 9:30 HKT?
> 
> Of course. :)

Sorry man, got really busy yesterday.
