### ISSUE TITLE
Support Vitepress

### ISSUE THREAD

**Issue by harrytran998** [johnsoncodehk/volar#70]
When I create the `.vue` file on the `.vitepress` folder --> Volar doesnt work!
Hope you can check this! I'm currently used Volar latest!

![image](https://user-images.githubusercontent.com/24296018/108628586-698da280-748e-11eb-9239-9d25fb907f9e.png)

**Comment by johnsoncodehk** [comment]
hi @harrytran998, do you have a tsconfig.json in project? see: https://github.com/johnsoncodehk/volar#note

if yes please give me a repro.

**Comment by harrytran998** [comment]
> hi @harrytran998, do you have a tsconfig.json or jsconfig.json in the project? see: [johnsoncodehk/volar#note](https://github.com/johnsoncodehk/volar#note)
> 
> if yes please give me a repro.

Oop, thank you for the quick response. This is my repo: https://github.com/harrytran998/harrytran998.me.git

**Comment by harrytran998** [comment]
I use `ref sugar` style in this file: https://github.com/harrytran998/harrytran998.me/blob/main/src/.vitepress/components/Layout.vue

**Comment by johnsoncodehk** [comment]
hey, try add `"include": ["src/**/*", "src/.vitepress/**/*"]` to tsconfig.

**Comment by harrytran998** [comment]
Thanks, bro! It's worked! I think you should add some guide for this in `johnsoncodehk/volar#note`

**Comment by johnsoncodehk** [comment]
good point. I will add it, thanks for suggestion. :)
