### ISSUE TITLE
Wrong error for `v-once`: `Expected 1 arguments, but got 0.`

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#700]
```node
src/views/AdTemplates/AdTemplatesGroups/Details/Details.vue:166:15 - error TS2554: Expected 1 arguments, but got 0.

166               v-once,
                  ~~~~~~

Found 1 error.
```

Affected code snippet:

```pug
          //- ...
          v-card-title(v-else)
            v-btn(
              name="createEta",
              color="primary",
              rounded,
              v-once,
              @click.native="newAdTemplate",
              @shortkey.native="newAdTemplate",
              v-shortkey.once="['+']"
            )
              //- ...
```

This occurred somewhere between exclusive `0.29.3` and inclusive `0.29.5` and was not an issue before

---

Workaround until fixed `v-once="true"` ^^'

**Comment by johnsoncodehk** [comment]
I can repro this problem. Does `v-once` is a component name in your project?

**Comment by Shinigami92** [comment]
> I can repro this problem.

You can or you cannot? Hope nothing is lost in translation here. :)

> Does `v-once` is a component name in your project?

No `v-once` is not a `component` in my project but a `directive` from Vue itself
It's also in Vue 3: https://v3.vuejs.org/api/directives.html#v-once

**Comment by johnsoncodehk** [comment]
Sorry it's typo, I mean I cannot :S

Could your provide a minimal reproduction?

**Comment by Shinigami92** [comment]
Give me a second :)

**Comment by Shinigami92** [comment]
https://github.com/Shinigami92/volar-700

Run `yarn && yarn vue-tsc --noEmit`

**Comment by johnsoncodehk** [comment]
It seems that tsc did not compile the latest vue-tsc code when it was released. 0.29.6-patch.1 has been released for temporary correction.

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/154602284-a8e3ecd5-0aa9-4d5e-a047-74d7d9fadab5.png)


![image](https://user-images.githubusercontent.com/8424643/154602307-25f5c25f-d9e1-47ce-95cc-9250c399cfd1.png)


I have the same problem

vue-tsc -v
Version 4.5.4
