### ISSUE TITLE
nuxt 3 class problem

### ISSUE THREAD

**Issue by productdevbook** [johnsoncodehk/volar#702]
![CleanShot 2021-11-16 at 10 31 43](https://user-images.githubusercontent.com/38668796/141940591-6419c991-1c2d-4ef2-9ac0-b12a6aa96526.png)

**Comment by sethidden** [comment]
Some solutions to a similar error are here: https://github.com/johnsoncodehk/volar/discussions/592#discussioncomment-1569072
