### ISSUE TITLE
vue-tsc removing comments in defineProps when used with withDefaults

### ISSUE THREAD

**Issue by soulsam480** [johnsoncodehk/volar#703]
hii @johnsoncodehk , I noticed it today that when I use `vue-tsc` to emit declarations for vue components, it doesn't remove comments when the props are declared without `withDefaults`. When I wrap `defineProps` inside `withDefaults` it removes comments. 

steps to reproduce
- clone https://github.com/soulsam480/vue-chart
- run `npm run build:lib`
- check `lib/dist/components`
- You won't see any comments inside the generated declarations

Let me know if you need more clarity.

**Comment by johnsoncodehk** [comment]
I think TS can't keep props comments in this situation. You can try to build the vanilla TS script:

```ts
// foo.ts
export default defineComponent({
  props: {
    /**
     * a foo
     */
    foo: String
  }
})
```

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/vuejs/core/pull/5871.
