### ISSUE TITLE
incorrect type assertions if the event name collides with native event and has a validator

### ISSUE THREAD

**Issue by jcppman** [johnsoncodehk/volar#704]
when a component emits an event that the name collides with native events (e.g: `change`) and with a validator, volar will complain about incompatible arguments types:

```

// component-a

export default defineComponent({
  emits: {
    change(total: number) {
      return total > 0;
    },
  },
});

// usage

<component-a
  @change="handleChange" 
// ⬆️⬆️ Type '(total: number) => void' is not assignable to type '(payload: Event) => void'. 
// Types of parameters 'page' and 'payload' are incompatible.ts(2322)
/>

function handleChange(total: number) {
  // do things
}

```

removing the emit validator and using `emits: ['change']` instead fixes the issue

- volar version: v0.29.5
- vue version: v3.2.20
- typescript version: v4.4.3

**Comment by sethidden** [comment]
For context: https://v3.vuejs.org/api/options-data.html#emits (2nd example in code block). Thought I'd link to the docs as I didn't know of this feature before :P

**Comment by johnsoncodehk** [comment]
It's works for me, could you provide repro case?
<img width="569" alt="螢幕截圖 2021-11-18 下午1 09 34" src="https://user-images.githubusercontent.com/16279759/142355655-f2ea1b2d-657e-4121-9d51-1254e3718dbb.png">

**Comment by jcppman** [comment]
I've finally isolated the issue. Please refer to the code here:

https://gist.github.com/jcppman/ce77978d2792f086a7b0e5abb3cc0313

In `Sub.vue`, `@change`'s payload is declared as `n:boolean`, but `Parent.vue` thinks it should be `Event`.

Interestingly, remove `props` in `setup` function will solve the issue (see attached screen recording below).

https://user-images.githubusercontent.com/5248918/142456273-a9d8fe7a-dd3d-4d21-8eed-84e02e7a4773.mov

**Comment by johnsoncodehk** [comment]
`defineComponent` only resolve arrow function, try change the option to
```ts
change: (total: number) => {
  return total > 0;
},
```

@pikax for your reference
```ts
// vue version 3.2.22

/*
const a: DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, EmitsOptions, string, PublicProps, Readonly<...>, {}>
*/
const a = defineComponent({
    emits: {
        change(n: boolean) {
            return true;
        },
    },
    setup(props) {
        return {}
    },
});

/*
const b: DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {
    change: (n: boolean) => true; <-- expect this
}, string, PublicProps, Readonly<...> & {
    ...;
}, {}>
*/
const b = defineComponent({
    emits: {
        change: (n: boolean) => true,
    },
    setup(props) {
        return {}
    },
});
```
