### ISSUE TITLE
how to define global component that base on vue-class-component

### ISSUE THREAD

**Issue by xinnianyoulin** [johnsoncodehk/volar#705]
component icon.d.ts:
![image](https://user-images.githubusercontent.com/32128165/142174429-d08aa3de-c000-4475-b326-9e8e53599466.png)

components.d.ts
![image](https://user-images.githubusercontent.com/32128165/142174675-dd74070b-6a51-4550-8693-a1be22f414fe.png)

but get any
![image](https://user-images.githubusercontent.com/32128165/142175000-9747e28e-df5f-4795-838b-8403b2eec897.png)

**Comment by sethidden** [comment]
I see you're trying to do what [the global components docs](https://github.com/johnsoncodehk/volar/blob/17b50db7dbcee55457fa55127ad93a3806111abd/extensions/vscode-vue-language-features/README.md?plain=1#L71-L89) are telling you to do, but I think those docs were added preemptively. What you're trying to do will only work after https://github.com/vuejs/vue-next/pull/3399 is merged and released. 

See https://github.com/johnsoncodehk/volar/issues/465

**Comment by xinnianyoulin** [comment]
@sethidden ok, thanks！In earlier versions, I used the `declare global { interface __VLS_GlobalComponents { } }` that is work fine, may has changed something that i have not notice, by the way i use vue2.

**Comment by johnsoncodehk** [comment]
I pre-supported https://github.com/vuejs/vue-next/pull/3399 through some hacks, but `declare  module @vue/runtime-core` maybe only support for vue 3, could you try change it to `declare  module @vue/runtime-dom` for vue 2?

And also make sure follow vue 2 setup: https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#using

**Comment by xinnianyoulin** [comment]
@johnsoncodehk change to `declare module @vue/runtime-dom` it seem still not work. and i have configured those about using. [here](https://github.com/xinnianyoulin/test-volar) have a repository about this question.

**Comment by johnsoncodehk** [comment]
Please try this

```ts
export default class Icon extends Vue {
  $props: {
    /**
     * [@props] name
     */
    name: string
    /**
     * [@props] name prefix
     */
    prefix: string
  }
}
```

```ts
declare module '@vue/runtime-dom' {
  export interface GlobalComponents {
    BIcon: typeof Icon
    BCheckbox: typeof Checkbox
  }
}
```

**Comment by xinnianyoulin** [comment]
@johnsoncodehk that's great! But I found that if there are two attributes with the wrong type at the same time, then the type check will be lost.

![image](https://user-images.githubusercontent.com/32128165/142754744-befcfcd4-4ec7-4eb8-a0a0-82c261935aff.png)

**Comment by johnsoncodehk** [comment]
This is a unfortunate bug :S

**Comment by xinnianyoulin** [comment]
Thank you very much!
