### ISSUE TITLE
Look into html.customData integration for VS Code

### ISSUE THREAD

**Issue by oddcelot** [johnsoncodehk/volar#707]
It would be nice to get some intellisense on some custom declaration as you would in a plain .html file 🙂
Like if all the other hints for the standard HTML declarations work, i feel like `customData` should be honored too.
(maybe via [contribution points](https://code.visualstudio.com/api/extension-guides/custom-data-extension)?)

```json
{
    "html.customData": [
      "./node_modules/@ionic/core/dist/html.html-data.json",
    ]
  }
```
(see: https://github.com/microsoft/vscode-custom-data)

No idea atm if this could/should be integrated or if I am missing something, but would be really useful for DX when using custom elements from other sources.

**Comment by johnsoncodehk** [comment]
Will do, thank you.

**Comment by filimon-danopoulos-stratsys** [comment]
Does this mean that Volar respects custom elements defined via `customData`? 

Using the following `.vscode/settings.json` 
```json
{
  "html.customData": [".vscode/my-elements.json"]
}
```
and custom element configuration `.vscode/my-elements.json`
```json
{
  "version": 1.1,
  "tags": [
    {
      "name": "example-element",
      "description": "",
      "attributes": [
        {
          "name": "foo",
          "values": [
            {
              "name": "bar"
            }
          ]
        }
      ]
    }
  ]
}
```
I get working completion in my test HTML file, `test.html`
```html
<!DOCTYPE html>
<html lang="en">
<body>
  <example-element foo=""></example-element>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/42338558/194084002-805a844d-c6f0-492b-97e3-8081d30699fe.png)


But I don't get completion in the simple `TestComponent.vue`
```vue
<template>
  <example-element foo=""></example-element>
</template>
```

![image](https://user-images.githubusercontent.com/42338558/194085605-90ffdc2e-fa65-4872-ba87-35ff0ae79303.png)

**Comment by johnsoncodehk** [comment]
@filimon-danopoulos-stratsys fixed in https://github.com/johnsoncodehk/volar/commit/05dec6965afc278539b4c3cb6fe5903a954525c6

**Comment by filimon-danopoulos-stratsys** [comment]
Great, thanks for your awesome work!

**Comment by Audie80** [comment]
I can't get this feature to work. I do have a vscode-html-custom-data.json file and a `"html.customData": ["./.vscode/vscode-html-custom-data.json"]` line in my .vscode/settings.json file, as well as the Vue Language Features (Volar) extension v.1.61.1.
Am I missing something?

**Comment by crudobaker** [comment]
Me neither. I'd like to hover the custom element tag in my `.vue` or `.svelte` files and a tooltip appears showing the information related to that component.
