### ISSUE TITLE
setup sugar not showing up

### ISSUE THREAD

**Issue by simlevesque** [johnsoncodehk/volar#708]
Hi, I have a Vue 3 project and I'd like to auto convert the SFC to the Setup RFC, it worked before but right not the suggestion is not showing up at all. On 0.29.5

**Comment by yaegassy** [comment]
Check the box for `Volar > Code Lens: Script Setup Tools` settings to enable it.

<img width="937" alt="volar-issue-708" src="https://user-images.githubusercontent.com/188642/142304436-3efb26cf-6c69-48cb-aa6c-5f66acae4fe0.png">

The default value used to be enable, but is now set to disable.

**Comment by acegank** [comment]
vscode 1.75.1 can't show up convert to setup sugar, why?

**Comment by yaegassy** [comment]
Please check CHANGELOG.

- <https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#110-2023216>

> Removed script setup convert tool

**Comment by acegank** [comment]
tks! @yaegassy 

it means if want to use script setup convert tool, only version 1.0.24 or low？

**Comment by nicooprat** [comment]
Any reason to have removed this tool? No details are available in the changelog.

**Comment by johnsoncodehk** [comment]
This feature was previously implemented in a hacky way, which is no longer supported by the new architecture. However, this feature will be migrated to the 1.6 Rules API.

You can temporarily downgrade to version 1.0.24 to use it.
