### ISSUE TITLE
v-model in Vue 2 warning

### ISSUE THREAD

**Issue by jiyingzhi** [johnsoncodehk/volar#709]
There is a fix : v-model for <input> tag default prop name is value not modelValue，bug it's only for native HTML form elements，not for custom components，So can this fix also applies to custom components when I set these config：
```json
"vueCompilerOptions": {
    "experimentalCompatMode": 2,
    "experimentalTemplateCompilerOptions": {
      "compatConfig": {
        "Mode": 2
      }
    }
  },
```

**Comment by ckvv** [comment]
@jiyingzhi 
把这个去掉就可以了
```diff
"vueCompilerOptions": {
    "experimentalCompatMode": 2,
-    "experimentalTemplateCompilerOptions": {
-      "compatConfig": {
-        "Mode": 2
-      }
-    }
  },
```

**Comment by jiyingzhi** [comment]
我这里不行

**Comment by johnsoncodehk** [comment]
It's works for me, please provide minimal reproduction.

<img width="903" alt="螢幕截圖 2021-11-21 下午3 37 41" src="https://user-images.githubusercontent.com/16279759/142753795-fb4648ec-6a5d-4812-bfe6-1f4a56fd6d2e.png">
