### ISSUE TITLE
Standard HTML attributes on components are interpreted as props and return a warning-like message

### ISSUE THREAD

**Issue by robyedlin** [johnsoncodehk/volar#710]
I'm not sure if this is a bug, but I get a Volar message on the `class` attribute of a component when `class` is not a defined prop.
```
<TableRow v-for="item in items" class="text-gray-500">
```
Hovering over class show the following message:
```
Property 'class' does not exist on type '{ ... }'. ts(2339)
```
I'm not 100% sure, but I think that standard HTML attributes on components are expected to pass through to the root element of the component. So I'm not sure if a warning is necessary.

**Comment by sethidden** [comment]
Works fine for me in the template from `npm init vue@next` then changed App.vue on line 11 to:
```html
<HelloWorld msg="You did it!" v-for="i in [1,2,3]" class="text-gray-500" />
```
Can you provide a repo with a minimal repro?

Maybe this'll help, but it's shot in the dark. Throwing it in since it's related to the class/className stuff
https://github.com/johnsoncodehk/volar/discussions/592

Related https://github.com/johnsoncodehk/volar/issues/552

**Comment by robyedlin** [comment]
Ok, something may be wrong on my end.

**Comment by robyedlin** [comment]
@sethidden I repeated your procedure and I got this:

<img width="864" alt="Screen Shot 2021-11-18 at 11 51 32 PM" src="https://user-images.githubusercontent.com/10917203/142566965-1362070a-2d35-4fa0-b923-61179b9e1a80.png">

**Comment by robyedlin** [comment]
@sethidden Actually I can see it when using ts as well.

**Comment by AlmarAubel** [comment]
It looks like this issue still exists in version v.0.29.6
![image](https://user-images.githubusercontent.com/14359811/143209362-39a66926-04f9-41b1-9b81-e409df5e0d42.png)

**Comment by johnsoncodehk** [comment]
@AlmarAubel this is a similar but different problem, see #592.
