### ISSUE TITLE
run "vue-tsc --noEmit --skipLibCheck" command error,  The error message is as follows:

### ISSUE THREAD

**Issue by zf1998** [johnsoncodehk/volar#711]
JSX element type '__VLS_9' does not have any construct or call signatures.

 <router-view />
 
Use "RouterView" in the template of the. Vue file, does the "RouterView" component need to be registered once?

This problem has bothered me for a long time. I hope I can get your help. Thank you!

**Comment by justin-schroeder** [comment]
I get similar errors in Vue SFC templates when I use features that are not JSX compatible. The project doesn't use JSX so its a bit odd.

![image](https://user-images.githubusercontent.com/1950463/142554552-32095d30-f55d-4458-b7f0-0c56f29b1376.png)

**Comment by zf1998** [comment]
![image](https://user-images.githubusercontent.com/28880564/142570263-4e6ac852-a4a6-498d-a0fa-fd4c284d6dee.png)
I know the reason. This error will be caused when a null is returned in the setup function.

**Comment by zf1998** [comment]
> I get similar errors in Vue SFC templates when I use features that are not JSX compatible. The project doesn't use JSX so its a bit odd. In this example it's clearly wanting me to use `className` instead of `class`
> 
> ![image](https://user-images.githubusercontent.com/1950463/142554552-32095d30-f55d-4458-b7f0-0c56f29b1376.png)

You can try adding the following code:
```
<template>
  <div class="tree"></div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  name: 'ComponentName',
})
</script>
```

**Comment by johnsoncodehk** [comment]
@justin-schroeder see #592.
