### ISSUE TITLE
Props of type `any` becomes `unknown` in template

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#713]
See screenshot.
In script-setup I define a prop of type `any` but inside the template it is considered as `unknown`
![image](https://user-images.githubusercontent.com/3832820/142632181-55e2c5bf-65ac-4a6b-83ba-c99c3e7007b5.png)

**Comment by johnsoncodehk** [comment]
This is `DefineComponent` types problem, you can see
```ts
const Foo = defineComponent({
	props: { foo: Object as PropType<any> }
});
(new Foo()).foo; // <-- unknown
```
