### ISSUE TITLE
Typescript warn underline when i use the prop by defineExpose

### ISSUE THREAD

**Issue by AlphaYoung111** [johnsoncodehk/volar#715]
when i use script setup with Typescript in componet Son ,and i use defineExpose to expose a function named handleSearch,and i call it by component Son 's InstanceType in component Parent,(code: sonRef.value.handleSearch() ),the function can successful called,but the handleSearch is warn underline and tips show with  sonRef.value don't havae handleSearch on it by Typescript(I have to comment @ts-ignore above the line to fix the warn message) .But when i change component Son by defineComponent,the warn will disappear.

**Comment by johnsoncodehk** [comment]
See https://github.com/vuejs/vue-next/issues/4397.
