### ISSUE TITLE
Custom attributes specified via `IntrinsicAttributes` prompt as nonexistent

### ISSUE THREAD

**Issue by kidonng** [johnsoncodehk/volar#717]
https://user-images.githubusercontent.com/44045911/142768537-9f327ec9-15b3-4c0b-a439-4edbab131eef.mov

I'm using [Attributify Mode in Windi CSS](https://windicss.org/features/attributify.html), which allow user to specify CSS classes as attributes:

```tsx
const el = <div text="center 2xl"/>
```

The above is equalivent to:

```tsx
const el = <div class="text-center text-2xl"/>
```

I tried typing it with `IntrinsicAttributes`, as I would do in React projects:

```ts
declare namespace JSX {
    interface IntrinsicAttributes {
        text?: string;
    }
}
```

But TypeScript still prompts me it does not exist on the element. A workaround is to extend `IntrinsicElements` instead:

```ts
declare namespace JSX {
    interface IntrinsicElements {
        summary: import('@vue/runtime-dom').HTMLAttributes & { text?: string }
    }
}
```

My question: is this error caused by Volar or [types from `@vue/runtime-dom`](https://github.com/vuejs/vue-next/blob/61720231b48dc57eeda8930eae11b5a03d9210a3/packages/runtime-dom/types/jsx.d.ts#L1325-L1341) are wrong? Is there a better way to deal with it?

---

- Editor: VSCode 1.62.3, Volar 0.29.6
- Package versions:
  - `typescript`: 4.5.2
  - `vue` / `@vue/runtime-dom`: 3.2.22
- Package manager: Yarn 3.2.0-rc.5, with PnP
- `tsconfig.json`:

```json
{
  "extends": "@sindresorhus/tsconfig"
}
```

**Comment by johnsoncodehk** [comment]
Try this
```ts
declare module '@vue/runtime-dom' {
	export interface HTMLAttributes {
		text?: string;
	}
}
```

**Comment by kidonng** [comment]
It doesn't work. But I suppose it is more likely an issue with `@vue/runtime-dom`, so I will report there as well.

**Comment by johnsoncodehk** [comment]
Maybe `@vue/runtime-dom` module is not in node_modules top level in your project so it doesn't work, you can try replace `declare module '@vue/runtime-dom'` to `declare module 'vue'`.

**Comment by kidonng** [comment]
No, that would only remove all type imported from `vue`. Also as I mentioned this is an JSX issue, so no Vue Server (and possibly Volar) is involved. Sorry for the noise.
