### ISSUE TITLE
Does this actually do anything?

### ISSUE THREAD

**Issue by WebMechanic** [johnsoncodehk/volar#718]
Hi,

I made several attempts to use this extension but it's either inherently non functional or I'm missing something relevant beyond installing it and open a .vue file. I was told to ditch Vetur as this is the "new thing", but this extension does plain nothing beyond syntax colouring - which is nice, but ...

- Ctrl+click onto anything vue-related (like {{ fubar }} in a template get's me nowhere.
- F12 shows a tooltip: "no definiton found"
- same for the Script parts

So what does this extension actually do / provide? 🙄 I'm sure I am missing something here.

Help. Please?

**Comment by soulsam480** [comment]
Did you try following this https://github.com/johnsoncodehk/volar/discussions/471#discussioncomment-1361669 ? Please try this and see if it works or not

**Comment by WebMechanic** [comment]
> Did you try following this [#471 (comment)](https://github.com/johnsoncodehk/volar/discussions/471#discussioncomment-1361669) ? 

no I didn't, because I was not aware of this post or the discussions. Thanks.

So it's either Vue2 + Vetur or Vue3 + Volar then? 
Can't have both in the same IDE setup w/o constantly enabling and disabling extensions or fiddling with the workspace. I guess I stick to WebStorm then and give them Russions a few bucks for saving my nerves and time, where all of this works like a charm out of the box and w/o any effort at all. 
I was hoping I could ditch WebStorm, but it appears to be still superior in several areas. I find other areas where VSCode can hopefully shine.

Thanks and bye.

**Comment by Shinigami92** [comment]
Interesting, I have a Vue 2 + Vuetify 2 + Volar setup and it works like a charm :shrug:

**Comment by soulsam480** [comment]
> Interesting, I have a Vue 2 + Vuetify 2 + Volar setup and it works like a charm shrug

May be it's easy to blame the tool when you don't know how to use it. I think this is the case with this issue

**Comment by kingyue737** [comment]
> Interesting, I have a Vue 2 + Vuetify 2 + Volar setup and it works like a charm 🤷

Can you share how you makes Vuetify 2 component type-checking / auto-complete work in template with Volar?
