### ISSUE TITLE
Request textDocument/hover failed with message: Could not find source file

### ISSUE THREAD

**Issue by robyedlin** [johnsoncodehk/volar#719]
Is anyone else getting bombarded with this message on every page action lately?

<img width="501" alt="Screen Shot 2021-11-21 at 3 27 17 PM" src="https://user-images.githubusercontent.com/10917203/142778037-296a04d3-9e60-4157-b83e-8501c1665324.png">

<img width="885" alt="Screen Shot 2021-11-21 at 3 35 50 PM" src="https://user-images.githubusercontent.com/10917203/142778060-0d5e6342-77ca-4639-be0f-880e6a383622.png">

I'm using the standard setup from `npm init vue@next` with node 14 and ts enabled.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by robyedlin** [comment]
I will try that, but I noticed that the tsconfig file for volar-starter is different than the tsconfig file used for on npm init vue@next. Should these be kept in sync?

**Comment by robyedlin** [comment]
Should we also be using `import * as volar from '@volar/experimental/client'` in main.ts?

**Comment by johnsoncodehk** [comment]
> I will try that, but I noticed that the tsconfig file for volar-starter is different than the tsconfig file used for on npm init vue@next. Should these be kept in sync?

No need, but please try to see if these differences are causing your problem.

> Should we also be using `import * as volar from '@volar/experimental/client'` in main.ts?

No need too, this is setup for volar experimental component previewer and code finder features.

**Comment by robyedlin** [comment]
I will close this until I can reproduce it. The problem is intermittent.

**Comment by robyedlin** [comment]
@johnsoncodehk Disabling vue ref sugar take 2 in vite and env.d.ts seemed to resolve the issue.

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk Disabling vue ref sugar take 2 in vite and env.d.ts seemed to resolve the issue.

I think it's not affect, but please let me know if you reproduce it in some ways.

**Comment by robyedlin** [comment]
Ok, another thing I realized was that I still had some components without `lang="ts"`. Maybe that caused it.

**Comment by hyisboy** [comment]
> 
I have a some problem, The reason is the typescript version used. Try to reduce the typescript version to solve it.
![image](https://user-images.githubusercontent.com/42001846/147637390-1cfd3911-b21f-4c7e-a11f-874bb7a63e1b.png)
