### ISSUE TITLE
Reference other project's vue files in a monorepo setup

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#72]
Hi Author,

I've a monorepo setup like this:
`
packages

---ads

---shared
`.

And ads and shared folder has their own tsconfig.json.
a vue file in ads will import a vue file in shared.
But volar complains it cannot find the vue file, but for ts/js file, there's no problem. 

![image](https://user-images.githubusercontent.com/1321817/108994335-9cc27280-76d6-11eb-942a-58ce0b2965e5.png)

How can I resolve this issue, please help.

**Comment by johnsoncodehk** [comment]
hi @oliverzy, try add `"include": ["src/**/*", "../shared/src/**/*"]` to tsconfig for finding `*.vue` files.

**Comment by oliverzy** [comment]
> "../shared/src/**/*

Thanks for your reply. I have tried as you mentioned above. It doesn't work as well.

This is a very big project. Tomorrow I will make a much simple setup to reproduce this issue.

**Comment by johnsoncodehk** [comment]
I found that it does not working in monorepo indeed, and it should be fix in 0.21.16.

**Comment by josefernandezatceiba** [comment]
any workaround on this ?
