### ISSUE TITLE
false negative for **emits**

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#720]
Just updated to the latest deps and noticed that I'm not getting a lot of linting errors about:

> The "input" event has been triggered but not declared on `emits` option.eslintvue/require-explicit-emits

But I believe my types are sound, as this screenshot would indicate:

![image](https://user-images.githubusercontent.com/980757/142788777-ad9cc704-bdbb-420e-908f-a18ec90b95d0.png)

The type information highlighted in green is correct and by that logic the value in the first parameter is also correct. However, instead I get the **require-explicit-emits** linting error.

OS: macOs Monterey
Volar: `0.29.6`
Typescript: `4.5.2`

**Comment by johnsoncodehk** [comment]
Volar do not provide linting, you should report to ESLint. :S

**Comment by ksnyde** [comment]
ahhh; but this same signature wouldn't give a linting error in a `.ts` file ... at least I'm pretty sure it wouldn't.

**Comment by ksnyde** [comment]
Maybe it would but it didn't in the past ... very odd. I'll try and raise an issue there though. Thanks for pointing me in the right direction.
