### ISSUE TITLE
Error of v-model error in pug

### ISSUE THREAD

**Issue by sinbino** [johnsoncodehk/volar#721]
If a tag is followed by a colon, volar will report an wrong error about v-model.

For example, in the following code
```vue
td: input(v-model="name")
```
The latest version of volar reports the following error.
```
v-model can only be used on <input>, <textarea> and <select> elements.vue(54)
```
The preceding code is equivalent to the following code, which should not actually result in an error.
```vue
td
  input(v-model="name")
```
This problem is present in v0.28.10 or later, and does not seem to be present in v0.28.9 or earlier.

edit:
My mistake, it was a colon, not a semicolon.

**Comment by Shinigami92** [comment]
I think you mean `colon` instead of `semicolon`, do you?

**Comment by johnsoncodehk** [comment]
Reference: https://pugjs.org/language/tags.html#block-expansion

**Comment by sinbino** [comment]
Thank you for the fix.
