### ISSUE TITLE
Namespace Components are lost on format

### ISSUE THREAD

**Issue by fallsimply** [johnsoncodehk/volar#722]
After formatting a vue file, namespaced components are replaced with class names. I think emmet is being ran as part of the formatting process

Before
``` vue
<template>
	<Controls.Button type="link">Open Editor</Controls.Button>
</template>

<script lang="ts" setup>
import Controls from "~/components/Controls"
</script>
```

After
``` vue
<template>
	<Controls class="Button" type="link">Open Editor</Controls>
</template>

<script lang="ts" setup>
import Controls from "~/components/Controls"
</script>
```

Related to #372

**Comment by johnsoncodehk** [comment]
This is issue of https://github.com/Prettyhtml/prettyhtml, you can consider to contribute a PR to prettyhtml or move to prettier.

**Comment by fallsimply** [comment]
Thanks for the quick response and that fixed the issue!
