### ISSUE TITLE
vue3 + typescript textDocument/hover error if JSDoc param has {@link}

### ISSUE THREAD

**Issue by qiqigou** [johnsoncodehk/volar#724]
![image](https://user-images.githubusercontent.com/48587985/143003967-618aa74f-48a9-47b9-bb5a-ac8b4837bd8e.png)
code from `https://github.com/qiqigou/vue3-sample/blob/master/src/components/HelloWorld.vue`

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce. Please check your volar and vscode version if it can update.

<img width="463" alt="螢幕截圖 2021-11-29 上午12 15 54" src="https://user-images.githubusercontent.com/16279759/143776498-56346272-8fe1-41dc-9138-ae548568f001.png">
