### ISSUE TITLE
In .vue file use "@" alias for "src", Command + Click can not work

### ISSUE THREAD

**Issue by LYY** [johnsoncodehk/volar#728]
I have configured "@" alias for "src", in src dir contains 2 files:

src/components/HelloWorld.vue
src/App.vue

```vue
# App.vue
<script setup lang="ts">
  import HelloWorld from '@/components/HelloWorld.vue'
</script>
```

Command + click can not jump to HelloWorld.vue.

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client"],
    "isolatedModules": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "declaration": true,
    "declarationMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "*.ts"
  ],
  "exclude": ["node_modules", ".vscode", "public", "*.js"]
}
```

vite.config.ts
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import { resolve } from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  plugins: [vue(), vueJsx()],
})
```

vscode about
```
版本: 1.62.3
提交: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
日期: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.5.0
```

volar version
`v0.29.6`

**Comment by yukecs** [comment]
me too

**Comment by reslear** [comment]
and me, any news?

**Comment by BTBMan** [comment]
if import .vue file use alias path in ts file, it's not goto definition when the .vue file has code `<script setup lang="ts"></script>`

<img width="512" alt="图片" src="https://user-images.githubusercontent.com/26108004/157605756-0ca7818c-bbd1-4a4b-a58f-022364d9b4db.png">

it works!!!
<img width="489" alt="图片" src="https://user-images.githubusercontent.com/26108004/157605802-84ca4313-a074-406a-82f1-15894b553124.png">

it's not work with script tag
<img width="404" alt="图片" src="https://user-images.githubusercontent.com/26108004/157605926-b56c5253-de7e-4bbd-8838-3346ada26b14.png">

**Comment by BTBMan** [comment]
@johnsoncodehk

**Comment by BTBMan** [comment]
it works when use take over mode!!! [take over mode](https://github.com/johnsoncodehk/volar/discussions/471)

**Comment by johnsoncodehk** [comment]
@BTBMan this is a bug with TS plugin, see #435.
