### ISSUE TITLE
Intellisense doesn't seem to be working with a fresh Vuepress 2 installation

### ISSUE THREAD

**Issue by yaakov123** [johnsoncodehk/volar#729]
Not sure if I should create this issue here or in the Vuepress repo, but on a fresh installation of Vuepress 2, the intellisense doesn't seem to be working at all.

**Comment by johnsoncodehk** [comment]
You may need to add vuepress folder to tsconfig's include option, see https://github.com/johnsoncodehk/volar/issues/70#issuecomment-782876369.
