### ISSUE TITLE
Generic language server or dedicated typescript plugin?

### ISSUE THREAD

**Issue by mhartington** [johnsoncodehk/volar#73]
Looking through the available packages, is `@volar/typescript-vue-plugin` something that will be published and provide similar tooling to non-vscode editors? 

Similar to vls

https://www.npmjs.com/package/vls

and @vuedx/typescript-plugin-vue

https://www.npmjs.com/package/@vuedx/typescript-plugin-vue

These can be included via lsp or as a generic typescript plugin.

**Comment by johnsoncodehk** [comment]
yes it's available, I just no ready to publish, and I want to implement tsc command proxy too.

**Comment by johnsoncodehk** [comment]
close because similar to https://github.com/johnsoncodehk/volar/issues/71.

btw I forget to say, `@volar/typescript-vue-plugin` == `@vuedx/typescript-plugin-vue` and `@volar/vscode-vue-languageservice` == vetur `vls`.

publish `@volar/typescript-vue-plugin` for command line tool support is what I next to do.

but with `@volar/vscode-vue-languageservice` I want to publish after refactor finish because it should has stable API interface.

**Comment by johnsoncodehk** [comment]
Done: https://www.npmjs.com/package/vscode-vue-languageservice

**Comment by mvllow** [comment]
Is there a binary that can be run similar to vetur's `vls`? Can't seem to find one in the package

**Comment by johnsoncodehk** [comment]
@mvllow I am not familiar with `vls` so I have no idea with binary.

`vscode-vue-languageservice` has same level apis with [vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice) and [vscode-html-languageservice](https://github.com/microsoft/vscode-html-languageservice), it will easy to use if you have experience with these.

**Comment by johnsoncodehk** [comment]
I don't think this can be used directly for neovim, you need to provide language service host for `vscode-vue-languageservice`.

I don't know how neovim working currently, I will take a look after finishing the backlog.

**Comment by johnsoncodehk** [comment]
> These can be included via lsp or as a generic typescript plugin.

Also published TS plugin module: https://www.npmjs.com/package/typescript-vue-plugin

**Comment by euoia** [comment]
Just want to comment here since I am also interested in getting Volar working with Neovim's Language Service Protocol.

**Comment by johnsoncodehk** [comment]
@euoia It's here: https://github.com/yaegassy/coc-volar

**Comment by euoia** [comment]
@johnsoncodehk I'll take a closer look, but that appears to be specifically for Coc, which is a Vim plugin. I am presently trying to see whether it's possible to get it working with Neovim 0.5's built in language server protocol. Here's a bit more info:
https://github.com/neovim/nvim-lspconfig/wiki/Comparison-to-other-LSP-ecosystems-(CoC,-vim-lsp,-etc.)

**Comment by Ultra-Code** [comment]
@euoia I am also very interested in getting this for neovim's builtin lsp . But I don't really understand this code-base and some of the tools that look very promising like @volar/server and vscode-vue-languageservice arent't documented

**Comment by mhartington** [comment]
Looking at this, it seems that all the `@volar/server` module needs is a bin entry in the package json and a way to actually call the server from the command line and communicating it with over stdio. 

The editor provides it's own "client" in a sense, we just need a process to start and send LSP requests to. Would be happy to either lend a hand or help explain further if needed.
