### ISSUE TITLE
It feels slow in use

### ISSUE THREAD

**Issue by a145789** [johnsoncodehk/volar#730]
hello,I have been using it for a long time, maybe my project is too big, it always feels a little bit slow, prompt or save need to wait a long time, my situation is similar to the following link

[https://learnku.com/vuejs/t/60948](https://learnku.com/vuejs/t/60948)

now version: v0.29.6

Maybe my project problem, but this problem has bothered me for a long time, I want to ask for help.

My English is not good, sorry.

**Comment by johnsoncodehk** [comment]
For the save time, you should be able to simply check `editor.codeActionsOnSave` to search the reason.

For the auto-complete time, it is best to provide a repro case.
Otherwise you need to profiling(#413) and provide the record, but profiling may not be able to solve, because it can only debug the performance shortcomings from volar code, but can't found the project side reason.

In addition, can you compare the auto-complete time of the same code in *.ts and *.vue to see if *.vue is much slower than *.ts.

> My English is not good, sorry.

If you join Discord server(https://discord.gg/5bnSSSSBbK) we can talk in Chinese.

**Comment by zhubei1998** [comment]
<img width="1355" alt="2021-11-25_10-20-50" src="https://user-images.githubusercontent.com/61346370/143366689-a83f4502-dc28-495e-95a2-abfd311f2876.png"
[CPU-20211125T101919.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/7599722/CPU-20211125T101919.cpuprofile.zip)
>
It is a little bit slow, hope this profile can help you...

**Comment by johnsoncodehk** [comment]
@zhubei1998 seems the profiling record shows some performance issues from volar, thank you to provide it!

**Comment by chivesssss** [comment]
@johnsoncodehk  老师您好，今天更新了最新版本以后自动补全还是特别慢，然后按照[方法](https://github.com/johnsoncodehk/volar/discussions/413)试了一下，下面是分析的结果，请老师再看一下。
![2021-11-29_16-23-19](https://user-images.githubusercontent.com/23553358/143832960-e4d5ba31-86de-4dd0-a61b-9704d991e1bf.jpg)
![2021-11-29_16-23-36](https://user-images.githubusercontent.com/23553358/143832980-096e8aa6-222d-4884-9723-89cb7797cf96.jpg)
[CPU-20211129T162004.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/7616694/CPU-20211129T162004.cpuprofile.zip)

**Comment by johnsoncodehk** [comment]
@chivesssss thanks to provide profiling record.

Seems your project spent lot of time to calculate auto import, could you try [no-auto-import](https://github.com/johnsoncodehk/volar/tree/no-auto-import) branch? It was hardcode disabled auto import.

**Comment by chivesssss** [comment]
> @chivesssss thanks to provide profiling record.
> 
> Seems your project spent lot of time to calculate auto import, could you try [no-auto-import](https://github.com/johnsoncodehk/volar/tree/no-auto-import) branch? It was hardcode disabled auto import.

@johnsoncodehk  老师您好，拉取新的分支以后，简单测试了一下，虽然说还是要稍微停顿一下，但是在可接受范围内了，相较昨天的版本感觉快了很多。下面是截图：
![2021-11-30_10-13-07](https://user-images.githubusercontent.com/23553358/143974177-ca296b49-384f-4f95-a13a-aa0771d0b3ee.jpg)

![2021-11-30_10-13-56](https://user-images.githubusercontent.com/23553358/143974195-13d0a35b-92c2-4c8b-b37d-2cf7c0613956.jpg)
[CPU-20211130T101405.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/7622461/CPU-20211130T101405.cpuprofile.zip)

**Comment by johnsoncodehk** [comment]
@chivesssss could you try 0.29.8 and no-auto-import branch last commit, I've add cache logic in https://github.com/johnsoncodehk/volar/commit/83f14472202fff014f681c98bcce07367ea89270 due to your profiling.

**Comment by chivesssss** [comment]
> @chivesssss could you try 0.29.8 and no-auto-import branch last commit, I've add cache logic in [83f1447](https://github.com/johnsoncodehk/volar/commit/83f14472202fff014f681c98bcce07367ea89270) due to your profiling.

@johnsoncodehk  您好，下面分别是no-auto-import分支和0.29.8版本的截图，在我验证的过程中，能够明显感觉到 no-auto-import 分支代码提示快很多。

**_no-auto-import 截图_**  ⬇️⬇️⬇️⬇️⬇️
![no-auto-import-2021-11-30_12-22-31](https://user-images.githubusercontent.com/23553358/143986552-6d247fe4-e8f2-4754-88e2-50ae8907ce08.jpg)

![no-auto-import-2021-11-30_12-23-14](https://user-images.githubusercontent.com/23553358/143986567-a6cbfa7e-1f5b-4d43-8ba3-82e1a3c4f6da.jpg)

[CPU-No-Auto-Import.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/7622955/CPU-No-Auto-Import.cpuprofile.zip)

**0.29.8 版本 截图** ⬇️⬇️⬇️⬇️⬇️

![0 29 8-2021-11-30_12-33-20](https://user-images.githubusercontent.com/23553358/143986631-232fa5ca-18ba-4b33-996e-c2101b7d6b09.jpg)

![0 29 8-2021-11-30_12-33-50](https://user-images.githubusercontent.com/23553358/143986644-bf4e3442-6539-4ace-9066-b40554e2d591.jpg)

[CPU-0.29.8-20211130T123233.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/7622960/CPU-0.29.8-20211130T123233.cpuprofile.zip)

**Comment by johnsoncodehk** [comment]
Please track #808.

**Comment by RennCheung** [comment]
I just imported the import path when I import the path. How can I solve it?

https://user-images.githubusercontent.com/50518861/175483332-e177f077-9375-4ddd-a754-8dc805d053c1.mp4

**Comment by johnsoncodehk** [comment]
@RennCheung please provide profile record. (#413)
