### ISSUE TITLE
Question: vscode auto formatting

### ISSUE THREAD

**Issue by webfansplz** [johnsoncodehk/volar#734]
How can i use `volar` formatting `<style>` section , but use `eslint` (without prettier) formatting `<template>` and `<script>` in SFC.

```json
    "[vue]": {
        "editor.defaultFormatter": "johnsoncodehk.volar"
    },
```

when i setting it, volar will formatting whole SFC .

**Comment by Shinigami92** [comment]
Looks like a very exotic config 👀 
Could you explain why you need such a complex setup and don't just use formatting and linting for whole vue file?

**Comment by webfansplz** [comment]
> Looks like a very exotic config 👀
> Could you explain why you need such a complex setup and don't just use formatting and linting for whole vue file?

```json
// .eslintrc
{
  "extends": "@my-team",
}
```
we have custom eslint config (without prettier),so we  want to follow this specification when formatting.
But when i change default formatter (disable volar format), we missing the `style` section formatting

**Comment by Shinigami92** [comment]
I'm using `stylelint` in my current project, but we have e.g. `<style lang="scss" src="./App.scss"></style>` ... so... don't know if it can also lint vue sfc 🤔

**Comment by webfansplz** [comment]
@Shinigami92 Thanks !

**Comment by johnsoncodehk** [comment]
Maybe I can simply provide these VSCode settings to resolve this requirement:
- `volar.format.template.enabled`
- `volar.format.script.enabled`
- `volar.format.style.enabled`

But I'm not sure if we really need it.

**Comment by webfansplz** [comment]
> Maybe I can simply provide these VSCode settings to resolve this requirement:
> 
> * `volar.format.template.enabled`
> * `volar.format.script.enabled`
> * `volar.format.style.enabled`
> 
> But I'm not sure if we really need it.

it’s very useful for me, maybe we can support it (more flexible ? ), enabled all by default.

**Comment by nolimitdev** [comment]
@webfansplz was following finally added? In VSCode it is grayed out as unknown options. How https://github.com/vuejs/language-tools/pull/1028 solves closes this please?

```
volar.format.template.enabled
volar.format.script.enabled
volar.format.style.enabled
```

**Comment by johnsoncodehk** [comment]
@nolimitdev we don't have these options, please open a feature request if you think it should have.
