### ISSUE TITLE
[feat-req] vue-tsc support for symlinked files whose entities are outside the rootDir.

### ISSUE THREAD

**Issue by sinbino** [johnsoncodehk/volar#738]
Can vue-tsc support the import of symlinks that have entities outside the rootDir?

https://github.com/sinbino/issue-vue-tsc-symlink
Above is a reproduction repository of the problem.

In main-proj, there is a "types" directory that is a symlink to sub-proj.
The index.ts in main-proj imports the hello.ts in "types" directory.
```
|–sub-proj/src/types
| `–hello.ts
`–main-proj/src
  |–index.ts  (import hello from './types/hello.ts')
  `–types -> ../../sub-proj/src/types/
```

This project compiles successfully in tsc, but fails in vue-tsc with the following error.
"error TS6059: File 'sub-proj/src/types/hello.ts' is not under 'rootDir' 'main-proj'. 'rootDir' is expected to contain all source files."

**Comment by johnsoncodehk** [comment]
Thanks for the report! I need to survey how tsc handle this.

**Comment by sinbino** [comment]
Thank you for the fix.
