### ISSUE TITLE
Go to definition with Vue peek

### ISSUE THREAD

**Issue by dominikjasek** [johnsoncodehk/volar#739]
My goal is that when I hold `cmd` or `ctrl` and click on component name, I go directly to the component file. This is not working with `volar`. Current behaviour is this:

![notworking](https://user-images.githubusercontent.com/48070343/143674767-fd41d35f-30be-46fb-970f-b8144d1767ab.gif)

If I install `Vue peek` extension, it works just fine. The problem is when I restart my VSCode, both extensions launch in parallel and it may happen that `volar` extension launches after `Vue peek`. In order to make it work again, I need to disable or uninstall `Vue peek`, restart IDE and then install it again.

![working](https://user-images.githubusercontent.com/48070343/143674772-40153c47-91a7-482c-a6ff-bce85d8b2317.gif)
Thanks for any advices

**Comment by sethidden** [comment]
I see that it only happens if you use `<script>`.  In `<script setup>` it works like you want it so you could switch to that in your project.

This is indeed seems inconsistent since script setup behaves differently that regular script.

**Comment by johnsoncodehk** [comment]
This is the expected behavior consistent with TSX, and I think sometimes it is necessary to jump to script instead of component.
As an alternative, you can cmd / ctrl + click component props `msg` to jump to the component.

**Comment by dominikjasek** [comment]
> This is the expected behavior consistent with TSX, and I think sometimes it is necessary to jump to script instead of component. As an alternative, you can cmd / ctrl + click component props `msg` to jump to the component.

Ok, but this is working as expected in Webstorm :(
