### ISSUE TITLE
Editor doesn't auto-indent in template section

### ISSUE THREAD

**Issue by lanthaler** [johnsoncodehk/volar#74]
In `script` and `style` sections, the editor automatically indents the cursor as expected when typing:

```
foo {↵
  |
```

In the template section that doesn't work however. Instead, the cursor always jumps to the current indentation point:

```
<template>                               <template>
<div>↵              instead of           <div>
|                                          |
```

or

```
<template>                               <template>
<div>               instead of           <div>
  <h1>↵                                    <h1>↵
  |                                          |
```

**Comment by johnsoncodehk** [comment]
hi @lanthaler, please check your vscode indent config, see: https://code.visualstudio.com/docs/editor/codebasics#_autodetection

**Comment by lanthaler** [comment]
Thanks for the quick reply. VSCode is set up correctly as far as I can tell

![image](https://user-images.githubusercontent.com/456407/109185809-a3152500-7790-11eb-80b1-01e1c92f770a.png)

As explained above, it works file in the `<script>` and `<style>` blocks of `.vue` files but not the `<template>` block. It also works fine in `.html` files. Anything else I can check to help debug this?

**Comment by johnsoncodehk** [comment]
if you disable volar is it correctly?
if yes, I don't know why but this is volar problem, I need a repro to check.
if no, it may other extension problem, you can try this tool to search: https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect

**Comment by lanthaler** [comment]
I disabled all extensions but Volar and the issue is still there. It works with Vetur. With no extension installed at all, it doesn't work either but then there also isn't any syntax highlighting and the `.vue` file is interpreted as plain text which doesn't seem to indent on html tags but does on parentheses. So it seems that VSCode uses plain text for indentation logic with Volar instead of HTML (or something specific for Vue). While Vetur handles it correctly

**Comment by johnsoncodehk** [comment]
I just got your problem.. we need

```
<template>                               <template>
<div>↵              instead of           <div>
  |                                      |
```

I misunderstood the opposite meaning. I will fix it, thanks for your report. :)

**Comment by lanthaler** [comment]
Yeah, exactly. Sorry that I haven't been clear enough and thanks a lot for fixing it!

**Comment by johnsoncodehk** [comment]
supported in 0.21.17.

**Comment by lanthaler** [comment]
Oh wow, that was fast. Thanks so much. Works great now
