### ISSUE TITLE
No event prompt, such as "@cki", should prompt "@click= ""  

### ISSUE THREAD

**Issue by liweiook** [johnsoncodehk/volar#745]
like this
![image](https://user-images.githubusercontent.com/42706756/143827154-d4780c9c-dad5-4d52-b8f9-5be7eff7df60.png)
Here's vetur hint，but But there is conflict between the two  plug-ins

**Comment by sethidden** [comment]
[Are you using Volar and Vetur at the same time?](https://github.com/johnsoncodehk/volar/blob/bd2a7bad02deb2e0b04156ca1b788e2cb6c934ce/extensions/vscode-vue-language-features/README.md?plain=1#L96)

You can only use one or the other, don't use both at the same time.

If that's not the issue, I'm not really sure what error are you reporting. Can you provide step by step instructions of what are you doing (and code samples from .vue files, you think they're relevant)

**Comment by johnsoncodehk** [comment]
I think you are using vue 2, please make sure follow vue 2 setup: https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#using
