### ISSUE TITLE
Component type checking failed when work along side with defineEmits()

### ISSUE THREAD

**Issue by ShineKidd** [johnsoncodehk/volar#748]
**Env**

vue 2.6.11
@vue/runtime-dom 3.2.23
unplugin-vue2-script-setup 0.7.1
volar 0.29.7
typescript 4.1.5

**code**

Home.vue
![image](https://user-images.githubusercontent.com/25340861/143879107-452de192-186b-4f1b-8d17-0d7369462168.png)

HelloWorld.vue
![image](https://user-images.githubusercontent.com/25340861/143879214-669ae898-8a6e-47b6-8ea5-5622972a7b1a.png)

**Comment by johnsoncodehk** [comment]
Please make sure follow unplugin-vue2-script-setup setup: https://github.com/antfu/unplugin-vue2-script-setup#ide

**Comment by ShineKidd** [comment]
> Please make sure follow unplugin-vue2-script-setup setup: https://github.com/antfu/unplugin-vue2-script-setup#ide
This occurs when using `defineEmits()`

**Comment by johnsoncodehk** [comment]
Could you provide repro case?

**Comment by ShineKidd** [comment]
repo: git@github.com:ShineKidd/vue2-typescript.git

component: `<HelloWorld />` in `src/views/Home.vue`

thanks!!

**Comment by johnsoncodehk** [comment]
@ShineKidd delete shims-tsx.d.ts should fix the problem.
