### ISSUE TITLE
 Multi-root Workspaces support

### ISSUE THREAD

**Issue by chojnicki** [johnsoncodehk/volar#75]
I have mono repository with multiple directories, for ex. "frontend" and "backend", opened as multi root in workspace.
I'm testing this extension with fresh Vue 3 + Vite install. First this I checked was if code definitions are recognized correctly, and it failed.
For ex. in App.vue when I hover import path `import HelloWorld from './components/HelloWorld.vue` or `<HelloWorld />` nothing appears, also while clicking it with CTRL it does not open HelloWorld.vue file.
With extension Vetur it actually works, so my last attempt was to open Vue directory directly (not in monorepo workspace) and now it works fine. So this extension doesn't supports monorepo / multi-root workspaces or is this a bug?

**Comment by johnsoncodehk** [comment]
hi @chojnicki, do you have tsconfig in your each monorepo folder? if you have please give me a repro.

**Comment by chojnicki** [comment]
There is single frontend (vue) subfolder.
Tsconfig is standard, like I said, I tried this with fresh Vue project:

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}

```

**Comment by johnsoncodehk** [comment]
<img width="1169" alt="螢幕截圖 2021-02-26 上午10 12 08" src="https://user-images.githubusercontent.com/16279759/109245343-3f840980-781b-11eb-865f-bade60d05d3d.png">

I tried a monorepo like from [vite/create-app](https://github.com/vitejs/vite/tree/main/packages/create-app/template-vue-ts) and it should work. can you provide a repro?

**Comment by chojnicki** [comment]
I actually did not need anymore, because I decided to switch to multiple workspaces (IDE windows) anyway. Just less problems.. Also if I just open whole repo as single directory it works just fine.

But many people are using multi-root in vscode so I decided to make more tests. I got strange behavior.
Actually I do not need to make reproduction repository because vite/create-app is good example.

Video from these steps: [https://streamable.com/3zyu0f](url)

```
1. git clone https://github.com/vitejs/vite.git
2. cd vite/packages/create-app/template-vue-ts
3. npm install
4. Now open fresh vscode window.
5. File / Add folder to workspace. Select vite/packages/create-app/template-vue-ts/
6. Save workspace in vite/packages/create-app/
7. --- it works ---
8. Again File / Add folder to workspace. Select other directory from same place, for ex. React
9. --- it still works ---
10. Save workspace and restart IDE.
11. --- it does NOT work ---
12. Delete second directory from workspace.
13. Save workspace and restart IDE.
14. --- it again works ---
15. Repeat steps from 8 - same results.
```

**Comment by johnsoncodehk** [comment]
I got it now, this is multiple workspaces not monorepo problem. if you open `packages/create-app` folder in vscode it should be work.

I will check multiple workspaces support, thanks for report!

**Comment by chojnicki** [comment]
> I got it now, this is multiple workspaces not monorepo problem
I'm new in vscode but I do not think this can be called "multiple workspaces". As far I know vscode does not support multiple workspaces in single IDE window (feature requested by many people for years).

I think what I did on video was with multi-root feature, just like I said in first post. Multi-root is probably usually used for monorepo? But yes, just like I said previously, opening this monorepo as single root works OK. But I'm not sure this is good solution.

**Comment by johnsoncodehk** [comment]
supported in 0.21.17.
