### ISSUE TITLE
FR: CSS classes available in template

### ISSUE THREAD

**Issue by kabiaa** [johnsoncodehk/volar#752]
Index classes in CSS, SCSS, etc files and make them available inside Vue components

**Comment by IWANABETHATGUY** [comment]
I have implement this here https://github.com/IWANABETHATGUY/tjs-postfix/blob/master/README.md#scsscss-completion-and-jump-to-definition , maybe i could extract this feature and offer a node-binding we could easily integrate with volar

**Comment by johnsoncodehk** [comment]
@IWANABETHATGUY I am refactoring the Plugin architecture (#185), and I am also considering how to integrate additional IDE behaviors, so I still can’t say anything at the moment.
