### ISSUE TITLE
Intellisense not working if used with vue-property-decorator (Vue 2)

### ISSUE THREAD

**Issue by MAG-Christian-Birkl** [johnsoncodehk/volar#753]
I can't get intellisense to work if i use vue-property-decorator (or vue-class-components) in combination with Vue 2.

Given the following template:

```typescript
import HelloWorld from './HelloWorld.vue';
@Component({
  components: { HelloWorld },
})
export default class App extends Vue {
}
```

and the following template:

```html
<template>
  <div>
    <HelloWorld what="world" />
  </div>
</template>
```

`HelloWorld` is red and of type `any`. But if a i change the code to `Vue.extend` everything is fine:

```typescript
import HelloWorld from './HelloWorld.vue';
export default Vue.extend({
  components: {
    HelloWorld
  }
});
````

`HelloWorld` is recognized and of type `typeof HelloWorld`.

repository is available at https://github.com/MAG-Christian-Birkl/volar-vue2-test-mag.

https://github.com/MAG-Christian-Birkl/volar-vue2-test-mag/blob/main/src/App.vue
vs
https://github.com/MAG-Christian-Birkl/volar-vue2-test-mag/blob/main/src/App_Working.vue

Am i missing something in my vue 2 setup?

**Comment by yooouuri** [comment]
Same here

<img width="342" alt="image" src="https://user-images.githubusercontent.com/12934957/144519426-6b4bc1f8-a3d4-4bef-8a71-fc73173204bf.png">

Takeover mode is enabled. `@vue/runtime-dom` is installed

**Comment by johnsoncodehk** [comment]
Decorators will not affect type-checking, see #21.

But I will add support by additional property definition in next version.

```ts
@Component({
  components: { HelloWorld },
})
export default class App extends Vue {
  static components: { HelloWorld: typeof HelloWorld } // <--
}
```

**Comment by MAG-Christian-Birkl** [comment]
Oh cool :-) Thank you.

Just one thing - does this mean i need to specify my components twice (@Components and static?) in order to get intellisense?

**Comment by johnsoncodehk** [comment]
@MAG-Christian-Birkl Volar only need `static components` for intellisense.

**Comment by SniperJoe** [comment]
@johnsoncodehk why not add an option to treat all imports from '*.vue' files as components, as it seems to happen in ```<script setup>``` files (it looks like all the code inside ```<script setup>``` is treated as ```setup()``` function code, unlike non-setup components, but still)? In that case volar maintainers would not even need to separately add support for ```Vue.extend```, ```@Component({})```, ```@Options({})``` whatever etc. syntax in order to enable proper intellisense in non-setup components.

**Comment by johnsoncodehk** [comment]
@SniperJoe sorry for late to reply! We can't do this because it not working for all situation.

For example:
```ts
import Foo from './Foo.vue';

export default {
  components: {
    Bar: Foo // alias component
    Baz: defineComponent({ ... }) // inline component
    Qux: defineAsyncComponent(() => import('...')) // dynamic import
  }
}
```
