### ISSUE TITLE
Allow array syntax for style binding

### ISSUE THREAD

**Issue by OvidijusParsiunas** [johnsoncodehk/volar#757]
Framework: Vue 3

By convention, Vue 3 allows the binding of multiple CSSProperties objects within array like so:
<div :style="[{ width: '10px'}, {height: '10px'}]"></div>

Documentation ref:
https://v3.vuejs.org/guide/class-and-style.html#array-syntax-2

However upon doing this I get the following error:
Type '{ width: string; }' is not assignable to type 'string'. ts(23222)

![image](https://user-images.githubusercontent.com/18709577/144687369-de5e6ba0-19ee-4556-8782-841bd44968b2.png)

Is there any way to fix this?

**Comment by OvidijusParsiunas** [comment]
I am also more than happy to contribute to this project to allow this syntax. :)

**Comment by johnsoncodehk** [comment]
Works for me in https://github.com/johnsoncodehk/volar-starter.
<img width="464" alt="螢幕截圖 2021-12-05 下午7 36 32" src="https://user-images.githubusercontent.com/16279759/144744850-d3e871c9-96f1-4b80-ad5e-74360d202b94.png">

This is relate to your `@vue/runtime-dom` version, please check if it can update.
