### ISSUE TITLE
Type checking doesn't work for components written in .ts files

### ISSUE THREAD

**Issue by sqal** [johnsoncodehk/volar#76]
Hi. I would like to report a problem with type checking components written in javascript.

I created  a minimal reproduction for you to check - https://github.com/sqal/volar-bug-repro
(just install deps and check App.vue)

As you can see, there are two same components. One written in .vue, the other in .ts, and type checking completely doesn't work for the .ts component.  What's interesting when I click on the <icon/> component, vs-code takes me to @vue/runtime-dom.d.ts file and specifically to this part of the code

```ts
interface IntrinsicElements extends NativeElements {
  // allow arbitrary elements
  // @ts-ignore suppress ts:2374 = Duplicate string index signature.
  [name: string]: any
}
```

... so I don't know if it's directly related to this extension or if it's a bug within vue types however, I can't figure it out :/

I would appreciate it if you could take a look and tell me how can I resolve this issue. Thanks!

**Comment by johnsoncodehk** [comment]
fixed in 0.21.17.
