### ISSUE TITLE
formatting failed when `:=` is used

### ISSUE THREAD

**Issue by ycw** [johnsoncodehk/volar#760]
we get "formatting failed" when v-bind shorthand `:=` is used

```vue
<!-- MyComp.vue -->
<template>
  <h1> .. </h1>
  <p :='$attrs'> .. </p> <!-- inherit attrs -->
</template>
```

output panel:

```
[Error - 6:05:08 PM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags
  Code: -32603 
```

**Comment by ycw** [comment]
@soulsam480 compiled OK. 

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxDb21wIHJlZGlzaD48L0NvbXA+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjIzL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+XG4gIDxoMT4gLi4gPC9oMT5cbiAgPGgyIDo9JyRhdHRycyc+IGluaGVyaXQgYXR0cnMgaGVyZSA8L2gyPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICBoMltyZWRpc2hdIHsgY29sb3I6IGNyaW1zb24gfVxuPC9zdHlsZT4ifQ==

**Comment by IWANABETHATGUY** [comment]
This seems to be a upstream problem maybe we could change the defualt format plugin

**Comment by IWANABETHATGUY** [comment]
@ycw to work around now, just add this to your vscode `settings.json`
```json
{
  // ..snip
 "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
   },
  // ..snip
}
```

**Comment by ycw** [comment]
> @ycw to work around now, just add this to your vscode `settings.json`
> 
> ```json
> {
>   // ..snip
>  "[vue]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>    },
>   // ..snip
> }
> ```
@IWANABETHATGUY it works.

**Comment by henrycunh** [comment]
didn't knew about that `:=` shorthand, pretty cool!

**Comment by ycw** [comment]
> Is this documented anywhere within the Vue 3 docs (searched, no luck)? Smells like and unintended side-effect rather than something official

@sethidden there's no "restrictions:" about shorthand usages in api docs https://v3.vuejs.org/api/directives.html#v-bind, but I did find one related in https://v3.vuejs.org/guide/component-slots.html#named-slots-shorthand :
> However, just as with other directives, the shorthand is only available when an argument is provided

I reckon that `:=` ( as well as `#=` ) are *unintended* usages. 

BTW I've made a feature request https://github.com/vuejs/vue-next/issues/5142
