### ISSUE TITLE
contains template #default Syntax coloring

### ISSUE THREAD

**Issue by gezhigang1005** [johnsoncodehk/volar#761]
contains template #default Syntax coloring

![image](https://user-images.githubusercontent.com/5440493/144951916-1e8ac2bc-aaec-47c5-92b9-ae8b175a4754.png)

**Comment by IWANABETHATGUY** [comment]
please offer a minimum reproduce code snippet instead a screenshot

**Comment by IWANABETHATGUY** [comment]
```vue
<template>
    <div class="settings-main card">
        <a-input title="标题" >
            <template #default={row}>

            </template>
        </a-input>
    </div>
</template>
```

minimum reproduce snippet

**Comment by gezhigang1005** [comment]
So you can reproduce it
> Volar： v0.29.8

> VsCode： 1.62.3

> appVersion: "5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 
 Safari/537.36"

```xml
<template>
    <div class="settings-main card">
        <a-input title="标题" >
            <template #default={row}>

            </template>
        </a-input>
        <a-input title="标题" >
            <template #default={row}>

            </template>
        </a-input>
        <a-input title="标题" >
            <template #default={row}>

            </template>
        </a-input>
    </div>
</template>
```

**Comment by gezhigang1005** [comment]
> Just add in the position of the deconstruction `"` It's good

`#default="{row}"`

```xml
<template>
    <div class="settings-main card">
        <a-input title="标题" >
            <template #default="{row}">

            </template>
        </a-input>
        <a-input title="标题" >
            <template #default="{row}">

            </template>
        </a-input>
        <a-input title="标题" >
            <template #default="{row}">

            </template>
        </a-input>
    </div>
</template>
```

**Comment by IWANABETHATGUY** [comment]
i wrote a sematic token extension MVP here https://github.com/IWANABETHATGUY/volar-semantic-token-demo, 
maybe we could integrate this in volar so that we could reduce the syntax highlighting issue

**Comment by IWANABETHATGUY** [comment]
@johnsoncodehk any thought about this ?

**Comment by johnsoncodehk** [comment]
This is a tmLanguage issue, and may not be suitable to be solved by semitic token, because vscode relies on tmLanguage to parse embedded language. This will affect the language configuration of autoClosingPairs, wordPattern, code snippet... in interpolation.
<img width="623" alt="螢幕截圖 2021-12-08 上午9 38 20" src="https://user-images.githubusercontent.com/16279759/145133120-d1fb5d20-1ae4-4d77-9e9b-94b05eb28e47.png">

It should modify here to resolve. html tmLanguage has resolved it already and I will refer to.
https://github.com/johnsoncodehk/volar/blob/b71700d1ce0ff8be7fda857b022530e02a58f2bd/extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json#L783-L794

**Comment by IWANABETHATGUY** [comment]
> This is a tmLanguage issue, and may not be suitable to be solved by semitic token, because vscode relies on tmLanguage to parse embedded language. This will affect the language configuration of autoClosingPairs, wordPattern, code snippet... in interpolation. <img alt="螢幕截圖 2021-12-08 上午9 38 20" width="623" src="https://user-images.githubusercontent.com/16279759/145133120-d1fb5d20-1ae4-4d77-9e9b-94b05eb28e47.png">
> 
> It should modify here to resolve. html tmLanguage has resolved it already and I will refer to.
> 
> https://github.com/johnsoncodehk/volar/blob/b71700d1ce0ff8be7fda857b022530e02a58f2bd/extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json#L783-L794

agree, but tmLang seems more complicated and unpredicatable, we only use semantic token for html template, leave other with tmLang. semantic could be a experimental feature and disabled by default.What's more tree-sitter is incremental parser and parsing after every keystroke only took a few ms (normally 1-5ms) no matter how big the file is.

**Comment by johnsoncodehk** [comment]
> agree, but tmLang seems more complicated and unpredicatable

Yes, even though I rewrote vue tmLanguage, I still don't fully understand how it works. :S

> What's more tree-sitter is incremental parser and parsing after every keystroke only took a few ms (normally 1-5ms) no matter how big the file is.

It will not be so fast in real world, because the semantic token will be implemented based on the LSP request. All LSP performance problems will affect the semantic token. For example, the request blocking problem caused by the long diagnosis time, the user may see that the semantic token is updated only after the diagnosis is updated.

**Comment by IWANABETHATGUY** [comment]
> the request blocking problem caused by the long diagnosis time, the user may see that the semantic token is updated only after the diagnosis is updated.

need to test on real project and open this feature on demand, so i don't think this would be a big problem

**Comment by IWANABETHATGUY** [comment]
> > agree, but tmLang seems more complicated and unpredicatable
> 
> Yes, even though I rewrote vue tmLanguage, I still don't fully understand how it works. :S
> 
> > What's more tree-sitter is incremental parser and parsing after every keystroke only took a few ms (normally 1-5ms) no matter how big the file is.
> 
> It will not be so fast in real world, because the semantic token will be implemented based on the LSP request. All LSP performance problems will affect the semantic token. For example, the request blocking problem caused by the long diagnosis time, the user may see that the semantic token is updated only after the diagnosis is updated.

IIRC, vscode will fallback to regex based highlight when semantic token is hanging. We could also add a switch to control it , 
open it as needed.
