### ISSUE TITLE
Support for PostCSS nesting in .vue files

### ISSUE THREAD

**Issue by dsimon-dev** [johnsoncodehk/volar#765]
Nested styles in single file components currently report an error:

![image](https://user-images.githubusercontent.com/73468772/145190392-21b928a8-9c36-4d17-839b-ce8a020d02b5.png)

Setting `lang="postcss"` removes the errors but also removes syntax highlighting:

![image](https://user-images.githubusercontent.com/73468772/145190571-acaa2253-53d3-4b94-99cd-56bddcac51ff.png)

Interestingly, the tooltips are are still working, which means the syntax is parsed correctly, just the highlighting is missing:

![image](https://user-images.githubusercontent.com/73468772/145190738-65bc87a4-9c51-45b5-977e-ffecd3d21e67.png)

I have the vscode extensions [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) installed.

**Comment by johnsoncodehk** [comment]
You can use https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss instead of.

**Comment by kameas** [comment]
@dsimon-dev thanks for images, its help to find the solution in google, @johnsoncodehk thanks for solution

**Comment by MrCawet** [comment]
Hello, 

> You can use https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss instead of.

Same issue as it describe in the initial @dsimon-dev description, and this plugin didn't help. 
I tested with a fresh install, by following the instruction given by tailwind 
https://v2.tailwindcss.com/docs/guides/vue-3-vite

**Comment by mmgolden** [comment]
> You can use https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss instead of.

I have the same issue. The language-postcss extension works for me, but it's no longer maintained.

**Comment by CodingWithAnxiety** [comment]
Bump. Same problem as above, I'd like to avoid using unmaintained plugins where possible.
