### ISSUE TITLE
No error when definitions from <script setup> used in <script>

### ISSUE THREAD

**Issue by JakubValtar** [johnsoncodehk/volar#766]
Volar currently does not report any errors for this code. The `count` variable in the `<script>` block links to the definition in the `<script setup>` block.

```vue
<script setup lang="ts">
const count = 0;
</script>

<script lang="ts">
export function logCount() {
  console.log(count); // Should get an error here that `count` is not defined
}
</script>
```
When used, there is an error during runtime:
```ts
import { logCount } from 'Count.vue';

logCount(); // Uncaught ReferenceError: count is not defined
```

### Expected behavior

According to Vue docs, the code should get transformed like this:

```ts
export function logCount() {
  console.log(count); // Should get an error here that `count` is not defined
}

export default {
  setup() {
    const count = 0;
    return {
      count
    };
  }
}
```

There should be en error from Volar in the exported function that `count` is not defined.

In general, definitions from `<script>` should be available in `<script setup>`, but not the other way around.

Volar VSCode plugin version: v0.29.8

**Comment by johnsoncodehk** [comment]
This is a trade-off behavior considering the performance and reliability of virtual code mapping, and I will try to solve it.

**Comment by JakubValtar** [comment]
Thanks for looking into this!
