### ISSUE TITLE
Volar lost auto imported properties typing

### ISSUE THREAD

**Issue by ThomasBerne** [johnsoncodehk/volar#769]
I have an issue. Today I did the VS Code update to v1.63.0. And suddenly volar seems to have lost some of auto imported properties in the template of my components. properties imported from script setup seems to work but some others like $t, localePath (@nuxtjs/i18n), and explicitely typed refs.
My project uses Vue 2, Nuxt bridge, vuetify, i18n and vuelidate. I intalled @vue/runtime-dom for the volar typing. I use vscode and volar to code. 
Also, yesterday, it worked fine.
![image](https://user-images.githubusercontent.com/23033483/145413731-7c763544-197e-41fd-a7f2-809bbe3071d1.png)

**Comment by ThomasBerne** [comment]
I found the solution. I needed to select the project eslint configuration.

**Comment by johnsoncodehk** [comment]
I think this problem has nothing not relate to eslint. If it happens again, please provide a repro case.
