### ISSUE TITLE
Feat: Does volar have a plan to support frameworks

### ISSUE THREAD

**Issue by JosephMing** [johnsoncodehk/volar#770]
Vetur currently bundles Component Data for the following vue libraries:

![image](https://user-images.githubusercontent.com/31059354/145505747-f89ae441-883b-46e3-9e9b-fd026ac8ec96.png)

This greatly improves the development efficiency. I hope volar supports it. 

Thank you for reading. Have a good day!

**Comment by oliverzy** [comment]
volar doesn’t need this because it uses TS

**Comment by soulsam480** [comment]
I think it's supports many frameworks by default as it uses TS

**Comment by yaegassy** [comment]
@JosephMing  Hi,  

Check this issue. <https://github.com/johnsoncodehk/volar/issues/418#issuecomment-905384222>

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, but this is a responsibility attribution problem, ui librarys should have full control over their component definitions.
