### ISSUE TITLE
intelligence bug with vite's `vue-ts` template

### ISSUE THREAD

**Issue by xiangqunXiao** [johnsoncodehk/volar#773]
# steps
- Follow vite's doc to create with `pnpm create vite`
- select `vue-ts` template
- run `pnpm install`
- open `HelloWorld.vue` file

# Results
you'll see error tips from vscode belows:
```
<script setup lang="ts">
  import { ref } from 'vue'; // Cannot find module 'vue' or its corresponding type declarations.ts(2307)
  defineProps<{ msg: string }>();  // Cannot find name 'defineProps'.ts(2304)
  const count = ref(0);
</script>

<template>
  <h1>{{ msg }}</h1>  // Cannot find name 'msg'.ts(2304)
  ...
<template>

```

**Comment by johnsoncodehk** [comment]
You may need to restart volar language server by command after updated node_modules.

**Comment by xiangqunXiao** [comment]
> 

@johnsoncodehk   how to  restart volar language server? I can't see it in document.

**Comment by johnsoncodehk** [comment]
Command + Shift + P and run this command.
![image](https://user-images.githubusercontent.com/16279759/145546856-50ff7a5c-0d6d-492f-819d-a0d560e3f743.png)

You can also use `Developer: Reload Window` instead of, it's more thorough.

**Comment by xiangqunXiao** [comment]
> Command + Shift + P and run this command. ![image](https://user-images.githubusercontent.com/16279759/145546856-50ff7a5c-0d6d-492f-819d-a0d560e3f743.png)
> 
> You can also use `Developer: Reload Window` instead of, it's more thorough.

I've try both of them, but not work.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If not, please provide a repro repo.

**Comment by xiangqunXiao** [comment]
> Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If not, please provide a repro repo.

the same error happens at `volar-starter`, by the way, I need to add `   "noImplicitAny": false` to `tsconfig.json` to fix `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)`.
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
Sorry for missing your reply! `noImplicitAny` should not be required, is this problem still on latest version 0.30.2?

**Comment by cesasol** [comment]
Is still prevalent on v0.31.1
