### ISSUE TITLE
type support for rfc 0043-sfc-style-variables

### ISSUE THREAD

**Issue by upupming** [johnsoncodehk/volar#777]
hi there, just a small suggestion, now vue has supported the `v-bind` for `<style>` section in SFC, see the RFC link: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0043-sfc-style-variables.md

Will the type of the variable be supported in the style section whening using a complex type, I think it will be useful:

```
<style>
.calendar-grid {
  grid-template-columns: repeat(v-bind(grids[0].length), max-content);
	          	          	            |--> will be helpful if type is enabled here
}
</style>
```

[example link](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxDb21wIDpzdGFydFRpbWU9XCJuZXcgRGF0ZSgnMjAyMS0xMi0wNiAwMDowMDowMCcpXCJcbiAgOmVuZFRpbWU9XCJuZXcgRGF0ZSgnMjAyMS0xMi0xMiAyMzowMDowMCcpXCIgOnJvb209XCJ7IG5hbWU6ICdSZXN0Um9vbScgfVwiIC8+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBjb21wdXRlZCwgZGVmaW5lQ29tcG9uZW50LCBFeHRyYWN0UHJvcFR5cGVzIH0gZnJvbSAndnVlJ1xuZXhwb3J0IGNvbnN0IHJvb21DYWxlbmRhclByb3BzID0ge1xuICByb29tOiBPYmplY3QsXG4gIC8qKiDml6XljoblvIDlp4vml7bpl7QgKi9cbiAgc3RhcnRUaW1lOiB7XG4gICAgdHlwZTogRGF0ZSxcbiAgICByZXF1aXJlZDogdHJ1ZVxuICB9LFxuICAvKiog5pel5Y6G57uT5p2f5pe26Ze0ICovXG4gIGVuZFRpbWU6IHtcbiAgICB0eXBlOiBEYXRlLFxuICAgIHJlcXVpcmVkOiB0cnVlXG4gIH1cbn1cbmV4cG9ydCBkZWZhdWx0IGRlZmluZUNvbXBvbmVudCh7XG4gIHByb3BzOiByb29tQ2FsZW5kYXJQcm9wcyxcbiAgc2V0dXAgKHByb3BzKSB7XG4gICAgY29uc3QgZm9ybWF0RGF0ZSA9IChkYXRlOiBEYXRlKSA9PiB7XG4gICAgICByZXR1cm4gYCR7ZGF0ZS5nZXRGdWxsWWVhcigpLnRvU3RyaW5nKCl9LSR7KGRhdGUuZ2V0TW9udGgoKSArIDEpLnRvU3RyaW5nKCkucGFkU3RhcnQoMiwgJzAnKX0tJHsoZGF0ZS5nZXREYXRlKCkpLnRvU3RyaW5nKCkucGFkU3RhcnQoMiwgJzAnKX1gXG4gICAgfVxuXG4gICAgY29uc3QgZ3JpZHMgPSBjb21wdXRlZCgoKSA9PiB7XG4gICAgICBjb25zdCBkYXlzID0gcHJvcHMuZW5kVGltZS5nZXREYXRlKCkgLSBwcm9wcy5zdGFydFRpbWUuZ2V0RGF0ZSgpICsgMVxuICAgICAgLy8gMC41IGhvdXIgcGVyIHJvd1xuICAgICAgcmV0dXJuIFsuLi5BcnJheSgyNCAvIDAuNSldLm1hcCgoXywgcGVyaW9kSWR4KSA9PiB7XG4gICAgICAgIHJldHVybiBbLi4uQXJyYXkoZGF5cyldLm1hcCgoXywgZGF5SWR4KSA9PiBbcGVyaW9kSWR4LCBkYXlJZHhdIGFzIGNvbnN0KVxuICAgICAgfSlcbiAgICB9KVxuXG4gICAgcmV0dXJuIHtcbiAgICAgIGZvcm1hdERhdGUsXG4gICAgICBncmlkcyxcbiAgICAgIGNvbG9yOiAncmVkJ1xuICAgIH1cbiAgfVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJiZy10aGVtZWFibGUtYmFja2dyb3VuZCB0ZXh0LXRoZW1lYWJsZS1mb3JlZ3JvdW5kIGJvcmRlci10aGVtZWFibGUtY29tbWVudFwiPlxuICAgIDxkaXYgY2xhc3M9XCJib3JkZXItYiBmbGV4IHAtNCBqdXN0aWZ5LWJldHdlZW5cIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJmbGV4IGl0ZW1zLWNlbnRlciB0ZXh0LTJ4bFwiPlxuICAgICAgICB7eyByb29tPy5uYW1lIH19XG4gICAgICA8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJmbGV4IGl0ZW1zLWNlbnRlciB0ZXh0LXhsXCI+XG4gICAgICAgIHt7IGZvcm1hdERhdGUoc3RhcnRUaW1lKSB9fSAtIHt7IGZvcm1hdERhdGUoZW5kVGltZSkgfX1cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXZcbiAgICAgIGNsYXNzPVwiY2FsZW5kYXItZ3JpZCBncmlkIG92ZXJmbG93LXgtc2Nyb2xsXCJcbiAgICA+XG4gICAgICA8ZGl2XG4gICAgICAgIHYtZm9yPVwiW3BlcmlvZElkeCwgZGF5SWR4XSBpbiBncmlkcy5mbGF0KClcIlxuICAgICAgICA6a2V5PVwicGVyaW9kSWR4ICsgJ18nICsgZGF5SWR4XCJcbiAgICAgICAgY2xhc3M9XCJjZWxsXCJcbiAgICAgID5cbiAgICAgICAgVGltZSBwZXJpb2Q6e3sgcGVyaW9kSWR4IH19IERhdGU6e3sgZGF5SWR4IH19XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4uY2FsZW5kYXItZ3JpZCB7XG4gIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KHYtYmluZChncmlkc1swXS5sZW5ndGgpLCBtYXgtY29udGVudCk7XG59XG4uZmxleCB7XG5cdGRpc3BsYXk6IGZsZXg7ICAgIFxufVxuICAuZ3JpZCB7XG4gICAgZGlzcGxheTogZ3JpZDtcbiAgfVxuICAuY2VsbCB7XG4gICAgcGFkZGluZzogMTBweDtcbiAgfVxuICAub3ZlcmZsb3cteC1zY3JvbGwge1xuICBvdmVyZmxvdy14OiBzY3JvbGw7XG59XG48L3N0eWxlPlxuIn0=)

**Comment by johnsoncodehk** [comment]
It should be already supported, but I found that I didn’t deal with all situations completely, will fix it.
