### ISSUE TITLE
Can we have basic snippets along with volar extension? (Just like vetur)

### ISSUE THREAD

**Issue by anburocky3** [johnsoncodehk/volar#781]
Vetur has some basic snippets built in like `template`, `script` & `style`. Can we have those with both `vue` & `vue-ts` snippets?

**Comment by sethidden** [comment]
Volar doesn't have this. You're supposed to use VS Code's snippets instead.
The maintainer's stance on this is here https://github.com/johnsoncodehk/volar/issues/183
See https://github.com/johnsoncodehk/volar/blob/master/extensions/vscode-vue-language-features/README.md?plain=1#L126

**Comment by anburocky3** [comment]
So this means, volar doesn't have default vue snippets and we have to create it on our own? Am i right?

**Comment by sethidden** [comment]
Yes — you need to use https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by anburocky3** [comment]
Ok thanks, I'll make my own. Does the @johnsoncodehk accept PR related to basic vue snippets with this extension? If so, I can contribute to that.

**Comment by johnsoncodehk** [comment]
You can submit pr and I will test it to see if it applies.
