### ISSUE TITLE
LESS (css) intellisense in SFCs across files

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#783]
Hello! I'm not 100% sure this is the right place for this issue but I think it is...
Also PS - working with the new Vue 3 script setup syntax, typescript, and volar has overall been really great. Thank you!

Basically the problem is this:
- I am using LESS css, but I suspect the problem would be similar if using other preprocessors
- I have some variables defined in a file meant to be used throughout my codebase, say `src/common/style/_colors.less`
- While intellisense/autocomplete does not automatically work for these variables, I can enable it using [a plugin](https://github.com/mrmlnc/vscode-less)
- this plugin works when authoring another less file, but does not work within a style block of a Vue SFC

Example of autocomplete working
![image](https://user-images.githubusercontent.com/1158956/145879904-3ef15989-876c-4505-a4f1-aadc53dbb44f.png)

Example of autocomplete not working :(
![image](https://user-images.githubusercontent.com/1158956/145880151-03c9e07b-e4a1-4053-b571-48e01c3b9169.png)

I'll also add that in my setup I am using vite config to automatically import these variable files, however it makes no difference if I import them explicitly.
```
...,
css: {
  preprocessorOptions: {
    less: {
      // automatically loads our colors and variables into the style blocks of .vue files
      // otherwise we end up importing in almost every file
      additionalData: `
        @import "@/common/style/_colors.less";
        @import "@/common/style/_variables.less";
      `,
    },
  },
},
```

I'm assuming that Volar has to deal with some of this stuff directly to support SFCs, but hopefully delegates a lot back to VSCode itself. If it is not possible to somehow tell VSCode that the style block should enable other related plugins within that block, then I think it could be very helpful to try to include some of this functionality in volar itself.

Specifically I'd love to be able to tell volar that I have some globally applied style (could be variables and utility classes) and then autocomplete on variables in LESS and utility class names in pug.

**Comment by johnsoncodehk** [comment]
This is out of scope, volar will not built-in support it. But it can be realized by a third party in the future base on [plugin api](#185).

The more active option is to contribute to https://github.com/microsoft/vscode-css-languageservice to support it.
