### ISSUE TITLE
<style lang="postcss"> have no syntax highlighting

### ISSUE THREAD

**Issue by SmallComfort** [johnsoncodehk/volar#784]
<img width="222" alt="截屏2021-12-14 下午3 18 21" src="https://user-images.githubusercontent.com/8806899/145951147-a0957761-744a-4936-9910-c7832835891b.png">

I have installed [PostCss Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss)

**Comment by thisVioletHydra** [comment]
https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss

**Comment by johnsoncodehk** [comment]
Duplicate of #765

**Comment by genu** [comment]
Is this still the solution?

The referenced extension is deprecated by the author.

**Comment by Darkzarich** [comment]
@genu it still works for the time maybe eventually it will stop working but as for now it works
