### ISSUE TITLE
Prioritize types from `script setup` in template rather than regular `script`

### ISSUE THREAD

**Issue by Aaron-Pool** [johnsoncodehk/volar#785]
**Update**: After further investigation, it seems like it's actually the `defineEmits` macro that is breaking template typing. I'm not sure whether this is due to Volar or the vue 2 vite script setup plugin.

Hey! First of all, just want to say thank you for all your great work on tool support for vue2 `script setup`! I've noticed an issue recently where, if I use a second script block, so that I can define some legacy options props (like `inheritAttrs`) it breaks typing in the template. It seems possible related to #766 , but I'm not concerned with named exports between files, only the template typing working. The below snippet fails to locate appropriate template types when the first `lang="ts"` block is included, but it works fine if it is removed. Am I doing something wrong? Or is this a known issue? 

```html
<script lang="ts">
export default { inheritAttrs: false };
</script>
<script lang="ts" setup>
import { ref, computed } from '@vue/composition-api';

interface Props {
  value: boolean| null;
  readonly: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  value: () => null,
  readonly: false,
});

const emit = defineEmits<{
  (event: 'input', value: boolean): void;
}>();

const isActive= ref(false);

function setToggle(value: boolean) {
  isActive.value = value;
}
</script>
<!--- cannot find 'isActive'! -->
<template>
  <div>
    <span>{{isActive}}</span>
  </div>
</template>
```

**Comment by johnsoncodehk** [comment]
Because you're using vue2, make sure you have correct setup: https://github.com/antfu/unplugin-vue2-script-setup#ide

If there is still a problem, please provide a repro case.
