### ISSUE TITLE
Autoclose and Linked editing: possible in Vue files?

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#786]
VS Code has a built-in features for auto-closing an html tag when you type it; and another feature called `linkedEditing` to rename the end tag when you modify the opening tag.

Those features are enabled in some native files such as `.html` or `.xml`, but not in custom file formats such as `.vue`. MS says it's up to extensions that handles custom formats to provide this feature.

I use VS Code extensions _Auto Rename Tag_ and _Auto Close Tag_ to achieve the same in `.vue`, but they are not totally satisfying. 
In particular, auto-close happens in the whole file, including `<script>` blocks. As a result, typing generic typescript code or casts is super-painful because it turns `<T>` into `<T></T>` and `<any>` into `<any></any>`.

I wonder if there is any way for the Volar extension to enable those VS Code behaviors inside the template parts and not the script part? 
I would love a more robust solution and getting rid of those 2 extensions.

**Comment by soulsam480** [comment]
I think volar does `linkedEditing` for template. See here https://github.com/johnsoncodehk/volar/discussions/53#discussion-2649272 -> Instead of other extensions. 
>As a result, typing generic typescript code or casts is super-painful because it turns <T> into <T></T> and <any> into <any></any>.

I never found this issue, but if it's happening to you may be this is a bug or something. But I'm not sure

**Comment by jods4** [comment]
> > As a result, typing generic typescript code or casts is super-painful because it turns into and into .
>
> I never found this issue, but if it's happening to you may be this is a bug or something. But I'm not sure

To clarify: the unwanted behaviour is from _Auto Close Tag_ extension in action, not vanilla Volar.
That's why I'd love if Volar could lift support for auto-closing tags from VS Code and I could drop that extension.

**Comment by DCLangX** [comment]
I think Volar already does two things. I've been uninstalling Auto Rename Tag and Auto Close Tag for a year.

**Comment by jods4** [comment]
@DCLangX 
Yesterday I disabled them one by one and tested each before creating this issue -- and it didn't seem to work.
Because of your comment I tried disabling both... and it actually seems to work?

I'm super confused 😵
But at least it indeed seems to work, so I'm closing this.
Thanks!
