### ISSUE TITLE
incremental mode is not yet support

### ISSUE THREAD

**Issue by yangdan8** [johnsoncodehk/volar#787]
Error message:
```bash
node_modules\typescript\lib\tsc.js:99284
    function createIncrementalProgram(_a) { console.error('incremental mode is not yet support'); throw 'incremental mode is not yet support';
```

Demo link:
https://github.com/yangdan8/incremental-err-demo

Repro steps
```bash
yarn ins
yarn lint
yarn lint-tsc
```

**Comment by johnsoncodehk** [comment]
You need to disable `incremental` and `composite` options to avoid incremental program for now.

**Comment by yangdan8** [comment]
> 您现在需要禁用`incremental`和`composite`选项来避免增量程序。

The references attribute needs to be configured with composite to take effect

**Comment by IWANABETHATGUY** [comment]
> You need to disable `incremental` and `composite` options to avoid incremental program for now.

I am curious why not us support incremental mode, this may gain a lot performance improvement, since typescript should only spend a few time to reparse the file especially when file is big.

**Comment by johnsoncodehk** [comment]
@yangdan8 I personally recommend that you use a single tsconfig in monorepo so that IDE / tsc performance is actually much better.

@IWANABETHATGUY not that easy, and vue-tsc watch has a higher priority. I will study it after supporting vue-tsc watch.

**Comment by JessicaSachs** [comment]
Hey @johnsoncodehk, I have a read for why I need multiple `references` (global type conflicts) -- what is the solution for using `composite` today?
