### ISSUE TITLE
Missing quick fix in .vue files

### ISSUE THREAD

**Issue by gertqin** [johnsoncodehk/volar#79]
Hi,

I've been experimenting with volar lately for our vue 3 apps, and I must say I'm very impressed!! :) Especially about the component typing (props and emits) in the template - this has been the big missing feature of Vetur.

I've discovered a number of minor issues, so I'll report them as separate issues. First I'm missing the quick fix (ctrl + .) command in .vue files. I'm using it all the time to add missing imports, so it would be great to have :).

![quick_fix](https://user-images.githubusercontent.com/17803278/109861127-3eaa0800-7c5f-11eb-8679-33154b44d3d2.png)

**Comment by johnsoncodehk** [comment]
hi @gertqin, small problems sometimes have a big impact on DX, so these are all important.

thanks for reporting these!

**Comment by johnsoncodehk** [comment]
Supported in 0.22.0.

**Comment by gertqin** [comment]
It works great, but I've found one case where it doesn't: in script setup if there is no import statement

![quick_fix2](https://user-images.githubusercontent.com/17803278/110161728-0f75d100-7dee-11eb-9add-40e40ede4a91.png)

If there is an import statement, then it works. :)

**Comment by johnsoncodehk** [comment]
@gertqin Thanks to let me know, I will fix this. :)
