### ISSUE TITLE
Exceptions are supported for declarationmap and references

### ISSUE THREAD

**Issue by yangdan8** [johnsoncodehk/volar#790]
The ordinary ts file "Go to Definition" jumps to the ts file of the target project, while the ts code in the Vue file "Go to Definition" jumps to the d.ts file

**Comment by johnsoncodehk** [comment]
Please provide a minimal reproduction.

**Comment by AbaoFromCUG** [comment]
I encounter the same issue, I create simple project https://github.com/AbaoFromCUG/ts-monorepo-demo

# Monorepo Introduce
Which project only include simple typescript code (even not include `*.vue` files`

* `packages/lib` define a lib
* `packages/lib` call the lib's function

The monorepo is  combined via [Project Reference](https://www.typescriptlang.org/docs/handbook/project-references.html)

# Reproduce Steps
* git clone my repo
* `pnpm install`
* `pnpm dev` to build the monorepo

### `ts-ls` only 
When I use builtin [ts-ls](https://github.com/typescript-language-server/typescript-language-server) in vscode as the only ts-languageserver,  any thing ok, I can `Go to definition` success


### `volar` only 
If I disabled builtin `ts-ls`, and use valor in `Takeover Mode`,    `Go to definition` will goto `packages/lib/dist/index.d.ts` instand of `packages/lib/src/index.ts`

_Based on previous results, I guess the ts-ls which volar embedded is too old (did volar builtin a ts-ls?), or missing some glue code between volar and ts-ls?_

# Additional info

when I  in  `*.vue` and `*.ts`  file  call `Go to Definition` to same lib files, include `volar` and `builtin ts-ls` in normal mode, `*.vue` goto failed, `*.ts` susccess
