### ISSUE TITLE
postcss(css-lcurlyexpected) error with Tailwind media query screen() function

### ISSUE THREAD

**Issue by zmwangx** [johnsoncodehk/volar#791]
Volar version: v0.29.8

This is similar to #103. I'm using the Tailwind [`screen()` function](https://tailwindcss.com/docs/functions-and-directives#screen) for media queries:

```vue
<style lang="postcss" scoped>
@media screen(sm) {
  .CalendarMonth {
    width: 24rem;
  }
}
</style>
```

This causes an error:

<img src="https://user-images.githubusercontent.com/4149852/146182608-2feb2b02-5771-4f13-9e7d-385fa36c68b1.png" width="394">

Apparently an unsupported syntax. #103 mentioned `<!-- @vue-ignore -->` but support for that has been removed in v0.24.0. https://github.com/johnsoncodehk/volar/discussions/134 says "May support `"css.validate": false` for replacement", but (1) that's not ideal for a single syntax error; (2) AFAICT it's not supported at the moment. Not really sure what can be done to suppress the error.

**Comment by johnsoncodehk** [comment]
I think there is no good way to deal with it in Volar, could you open an issue at https://github.com/microsoft/vscode-css-languageservice?
