### ISSUE TITLE
Issues with reactivity on VSCode 1.63 update

### ISSUE THREAD

**Issue by henrycunh** [johnsoncodehk/volar#792]
Ever since Microsoft introduced the new [1.63 release](https://code.visualstudio.com/updates/v1_63) for VSCode, I'm getting some issues on most of my code, mostly on the form of some reactivity issues.

## Sample
Taking the following snippet:
```vue
<script lang="ts" setup>
...
const v$ = useVuelidate(rules, instanceDetails)
</script>

<template>
...
<element v-model="v$.name.$model" />
</template>
```

The `v$.name.$model` gets highlighted as an error, as if `name` doesn't exist on `v$`. But if I change it to `v$.value.name.$model`, the error on editor disappears, at the cost of not being able to build the application.

The same snippet of code on the 1.62 release works just fine, as evidenced bellow.

## Evidence
On 1.63
![image](https://user-images.githubusercontent.com/8951736/146199580-3d5416ae-b687-43da-b1f2-a0e453652776.png)

On 1.62
![image](https://user-images.githubusercontent.com/8951736/146199657-842efc38-0a58-44fe-b3ef-75fcec4490e8.png)

**Comment by johnsoncodehk** [comment]
It should be relate to vscode's typescript version, please provide a minimal reproduction.

**Comment by henrycunh** [comment]
Reproduction repo
https://github.com/henrycunh/reactivity-issue

![image](https://user-images.githubusercontent.com/8951736/146399654-dadd1231-7db8-4447-a749-745b0b28fc66.png)

![image](https://user-images.githubusercontent.com/8951736/146399737-ede8a04c-9699-418d-bc62-6a00dfdb8797.png)

**Comment by johnsoncodehk** [comment]
Have you try 1.63.2? It's works for me.

<img width="636" alt="螢幕截圖 2021-12-19 下午8 43 25" src="https://user-images.githubusercontent.com/16279759/146675250-309dfe16-48f8-474e-b5bc-aec9319edd8b.png">

```
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (4 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.3.0
```

**Comment by henrycunh** [comment]
confirmed fix! thanks for checking :]
