### ISSUE TITLE
New feature request：Sort import statements in the SFC

### ISSUE THREAD

**Issue by popojja** [johnsoncodehk/volar#798]
If I can provide an SFC import sorting scheme, I can better standardize my project 。

**Comment by gadfly3173** [comment]
https://eslint.org/docs/rules/sort-imports maybe this can help you

**Comment by sethidden** [comment]
Yeah I agree that his sounds like something eslint should handle. Adding to gadfly's comment above, if you don't know how to set up ESLint so it can understand .vue SFCs and the TypeScript/JavaScript within the \<script\> block see https://github.com/sethidden/vue3-eslint-stylelint-demo

**Comment by johnsoncodehk** [comment]
Volar supports organize imports, you have 3 ways to trigger it.

1. Option + Shift + O (on osx)
2. Right click in script block > Select "Source Actions..." > Select "Organize Imports"
3. Run Organize Imports in command palette (Seem broken in 0.29.8, will fix in next version)

**Comment by bmikaili** [comment]
Would it be possible to add this as an on save action?

**Comment by johnsoncodehk** [comment]
You can add `"editor.codeActionsOnSave": { "source.organizeImports": true }` to .vscode/settings.json
