### ISSUE TITLE
folded complex template syntax highlight wrong

### ISSUE THREAD

**Issue by gadfly3173** [johnsoncodehk/volar#801]
it is fine under normal circumstances
![image](https://user-images.githubusercontent.com/28685179/146509266-1ac727c0-7082-44cc-85ed-bf4225a3c8ed.png)

When I folded the code, it would be like this, then scroll up would be normal
![image](https://user-images.githubusercontent.com/28685179/146509455-caa163d1-16d4-43a0-b785-b0901c9c9eeb.png)
![image](https://user-images.githubusercontent.com/28685179/146509640-89c8a28a-60e3-4f18-becc-a3e26fd483c4.png)

if the code is not comment also have similiar situation.
![image](https://user-images.githubusercontent.com/28685179/146509820-82528fd3-5a33-4238-98f9-de44e457fd39.png)

not a big issue but seems weird.

**Comment by gadfly3173** [comment]
![image](https://user-images.githubusercontent.com/28685179/148717713-bedcec93-3127-46c0-ac0f-04c95758ec0a.png)
i think this bug is still exist on `0.30.2`

**Comment by johnsoncodehk** [comment]
@gadfly3173 could you provide the reproduce code?

**Comment by gadfly3173** [comment]
https://github.com/gadfly3173/chakki-vue/tree/volar-issue

reproduction file: https://github.com/gadfly3173/chakki-vue/blob/642b6027efc5c4ccc82c48a4e22f83bcc2aea5d8/src/view/admin/group/group-list.vue

**Comment by gadfly3173** [comment]
vscode setting: "editor.foldingStrategy": "indentation"

**Comment by johnsoncodehk** [comment]
<img width="755" alt="螢幕截圖 2022-01-16 19 44 18" src="https://user-images.githubusercontent.com/16279759/149658520-0f73d36f-44bb-4bec-ae56-4b9aaf5bc5ac.png">

I can only folding line 17 but can't folding line 18 like your screenshot. Could your share your vscode info from `Help: About` command?

**Comment by gadfly3173** [comment]
> vscode setting: "editor.foldingStrategy": "indentation"

please check this setting
