### ISSUE TITLE
No type completion in spec.ts files when using <script setup> for SFC

### ISSUE THREAD

**Issue by jayEvans89** [johnsoncodehk/volar#805]
When using the setup syntactic sugar I can't get any variables, methods, computed variables etc to show in the autocomplete/intellisense in my test files. Props are showing correctly and I can get everything working correctly if I use the defineComponent option without the setup attribute.

I am using Volar's Take Over mode and Vue test utils for testing

Reproduction repo can be found here https://github.com/jayEvans89/vue-app-template

**Comment by johnsoncodehk** [comment]
This is a design limitation. If expose all script setup variables, we can't got unused variables report.

But before I find a solution, at least I will add an option to switch this behavior.

**Comment by johnsoncodehk** [comment]
Please try add `vueCompilerOptions.experimentalExposeScriptSetupContext` to tsconfig in next version.

```
// tsconfig.json
{
  // ...
  "vueCompilerOptions": {
    "experimentalExposeScriptSetupContext": true
  }
}
```
