### ISSUE TITLE
Vue2 - unrecognized tag in template

### ISSUE THREAD

**Issue by jmroon** [johnsoncodehk/volar#806]
![image](https://user-images.githubusercontent.com/36086006/146833434-cce337ae-75e0-4b35-a4a5-5f5fe87ff491.png)

Not sure if I'm doing something wrong here. Using the composition-api with defineComponent (typescript) with Vue 2. I followed the Volar instructions and included the runtime-dom. However, my imported vue components remain undefined in the template. 

I also set the compat mode in tsconfig:
![image](https://user-images.githubusercontent.com/36086006/146833757-4b8a9539-a3a5-4930-adde-4860d6b9613b.png)

Any ideas?

**Comment by johnsoncodehk** [comment]
Does config "editor.semanticHighlighting.enabled": true` helps? See #522.

**Comment by stephenhowells** [comment]
I'm experiencing the same issue where components are marked invalid in the editor. The setting for `editor.semanticHighlighting.enabled": true` doesn't make a difference.

![image](https://user-images.githubusercontent.com/436173/146878235-cfc7b5dd-dc98-48b6-89be-cd5bef645e14.png)

**Comment by stephenhowells** [comment]
I'm experiencing the same issue where components are marked invalid in the editor. The setting for editor.semanticHighlighting.enabled": true doesn't make a difference.

![image](https://user-images.githubusercontent.com/436173/146878749-b9b3da07-50ea-44c8-9b86-a67faa2e83c8.png)

**Comment by johnsoncodehk** [comment]
@stephenhowells `ClockIcon` is not valid component type, you can report to `@heroicons/vue`.

```tsx
// test.tsx
import { ClockIcon } from '@heroicons/vue/solid';

// 'ClockIcon' cannot be used as a JSX component.
//  Its return type 'VNodeChild' is not a valid JSX element.ts(2786)
() => <ClockIcon />
```
