### ISSUE TITLE
Does not work well if dependencies are installed with pnpm and custom d.ts

### ISSUE THREAD

**Issue by yanzhangshuai** [johnsoncodehk/volar#807]
hi, I've tried install the dependencies using pnpm, But  have a problem  when use custom d.ts （extension Vue ComponentCustomProperties)

![image](https://user-images.githubusercontent.com/31086862/146874613-01d841d4-7832-4a21-9ca6-961ce804841e.png)

I've tested using npm and yarn，That's perfectly

This is my test code https://github.com/yanzhangshuai/pnpm-volar-test

**Comment by johnsoncodehk** [comment]
`@vue/runtime-core` is not under node_modules if use pnpm, you can add `@vue/runtime-core` to dependencies in package.json, or change `declare module '@vue/runtime-core'` to `declare module 'vue'` for fix.

**Comment by yanzhangshuai** [comment]
> `@vue/runtime-core`不在 node_modules如果使用 pnpm，则可以添加到 package.json 中的依赖项，或更改为以进行修复。`@vue/runtime-core``declare module '@vue/runtime-core'``declare module 'vue'`

That's right, thanks
