### ISSUE TITLE
Use TS InferredProject, ConfiguredProject instead of language service API

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#808]
If project depend on some large packages (lot of .d.ts files), language service API spend lot of time to resolve auto import from node_modules packages.

TS implement cache logic in InferredProject, ConfiguredProject over language service API to avoid performance issue. Not sure is possible to use InferredProject, ConfiguredProject instead of language service API in volar. If can, should be able to fully achieve vanilla TS level performance.

https://github.com/microsoft/TypeScript/blob/009dd487a6543d16c8e403ea055ac0683c6bc5d3/src/server/project.ts#L258

**Comment by johnsoncodehk** [comment]
In 0.30.0, you can config `"typescript.suggest.autoImports": false` to skip calculate auto import for now.

**Comment by jahnli** [comment]
@johnsoncodehk  In the Settings. The json?

**Comment by johnsoncodehk** [comment]
@jahnli in VSCode settings / `.vscode/settings.json`.

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/147308273-dfc16d03-3f13-4b48-972e-44673813c82a.png)

Is that right ?

**Comment by johnsoncodehk** [comment]
Just tried reference TS internal code to implement auto-import cache logic for language service API, but it may invalid at any time with TS version update, has happened once in the past (https://github.com/johnsoncodehk/volar/commit/15e744f335fcbdb4db2e42a2778970d597b92ae0).
