### ISSUE TITLE
Support for event handlers in kebab-case

### ISSUE THREAD

**Issue by gertqin** [johnsoncodehk/volar#81]
This is not very critical, but event handler types are only supported in camelCase which is not recommended in the template part (although it will work in a SFC). Volar already supports transforming prop types to kebab-case, so it would be nice to have support for event handlers in kebab-case also.

![emit_casing](https://user-images.githubusercontent.com/17803278/109864545-4075ca80-7c63-11eb-9227-1bcc99080443.png)

**Comment by johnsoncodehk** [comment]
thanks for report! I don't know we can use it, let me sort it out.

```md
props:
onAaaBbb -> @aaa-bbb // supported
emit:
aaaBbb -> @aaaBbb // supported
aaaBbb -> @aaa-bbb // is it the only missing piece?
```

**Comment by gertqin** [comment]
Yes.

Props
```
myProp: String -> myProp="foo" // supported
myProp: String -> my-prop="foo" // supported
```

Emits
```
myEmit() {} -> @myEmit="() => {}" // supported
myEmit() {} -> @my-emit="() => {}" // not supported
```

**Comment by gertqin** [comment]
Note that emits only have good typing in script setup atm i.e. using ```defineEmit```. It should be fixed for ```defineComponent``` with https://github.com/vuejs/vue-next/pull/2164 I believe.

**Comment by johnsoncodehk** [comment]
Supported in 0.22.0.
