### ISSUE TITLE
Volar not respecting "html.format.wrapAttributes" settings.

### ISSUE THREAD

**Issue by ZackPlauche** [johnsoncodehk/volar#812]
In my VSCode settings I have `"html.format.wrapAttributes"` setting set to `"force-aligned"`, yet in my `.vue` files it still makes my layout look wrong.

For example, say this is my starter code:
```
<button type="submit" class="bg-pink-200 text-white p-2">
  Hello
</button>
```
Here's what happens in a normal html file with my formatting:
```
<button type="submit"
        class="bg-pink-200 text-white p-2">
  Hello
</button>
```
Here's the mess my vue format to:
```
<button
  type="submit"
  class="bg-pink-200 text-white p-2"
>Hello</button>
```

How do I fix this behavior?

**Comment by soulsam480** [comment]
If you use prettier, can you try this ? https://prettier.io/docs/en/options.html#vue-files-script-and-style-tags-indentation

**Comment by johnsoncodehk** [comment]
`html.format.wrapAttributes` is option of vscode-html-languageservice formatter, but volar using prettyhtml not vscode-html-languageservice for html format, so `html.format.wrapAttributes` has no effect to volar formatting in expected.

If you need more controllable formatting behavior, I suggest you use prettier.

**Comment by douglasg14b** [comment]
Prettier provides VERY few actual formatting options though, and makes heaps of bad assumptions that can be undesirable and even conflict with linting rules (There are plenty of threads on their GH for this)

How can we configure volar's usage o `prettyhtml`?

**Comment by johnsoncodehk** [comment]
@douglasg14b I have just shared it. 👀 https://twitter.com/johnsoncodehk/status/1599416049514184704
