### ISSUE TITLE
ts(2304): Cannot find name ...

### ISSUE THREAD

**Issue by creage** [johnsoncodehk/volar#813]
I have a simple .vue file written in Vue3

```vue
<template>
    <div class="home">
        <img alt="Vue logo" :src="logo" />
        <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" />
    </div>
</template>

<script lang="ts">
import { Options, Vue } from 'vue-class-component';

@Options({
    data() {
        return {
            logo: './logo.png'
        };
    }
})
export default class Home extends Vue {}
</script>
```

But Volar fails to locate property from my data:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/910967/147259823-bffd8853-cf8f-4dc8-8eaa-f1970b27dce9.png">

**Comment by creage** [comment]
My bad, sorry. Converting `data` into class props fixes the issue.

**Comment by creage** [comment]
But then - what about Composition API?

Here is the example from the Vue3 documentation, with `lang="ts"` in it's `<script>` tag, and it has same issue(s):
```vue
<!-- MyBook.vue -->
<template>
    <div>{{ readersNumber }} {{ book.title }}</div>
</template>

<script lang="ts">
import { ref, reactive } from 'vue';

export default {
    setup() {
        const readersNumber = ref(0);
        const book = reactive({ title: 'Vue 3 Guide' });

        // expose to template
        return {
            readersNumber,
            book
        };
    }
};
</script>
```

**Comment by creage** [comment]
We should use `defineComponent` for full TS support.

**Comment by johnsoncodehk** [comment]
For class base component, you can see https://github.com/johnsoncodehk/volar/issues/21#issuecomment-725974112.
