### ISSUE TITLE
Autocompete creates duplicate imports.

### ISSUE THREAD

**Issue by cefn** [johnsoncodehk/volar#815]
I used `@vue/cli` and `@vue/cli-plugin-typescript` to create a v2 boilerplate project at https://github.com/cefn/vue2-gist/tree/00c9a4d2bdd638588173a8ddc2a35e6377e5b1ba 

At that commit, if you open App.vue in VSCode with Volar (with or without Vetur) and use JSX autocomplete to try and create a new instance of `<HelloWorld>` via autocomplete, it adds a duplicate import and a duplicate `components` entry as shown below...

![image](https://user-images.githubusercontent.com/159819/147358721-12ba5fe2-c364-4a36-a600-900cc3aeab92.png)

VSCode Version: 1.63.2 (Universal)
Volar Last updated 21/12/2021, 15:56:08
Identifier johnsoncodehk.volar
Extension id `johnsoncodehk.volar`

**Comment by johnsoncodehk** [comment]
You need to make these changes in your project:
- Delete src/shims-vue.d.ts, src/shims-tsx.d.ts
- Add `@vue/runtime-dom` to devDependencies and install
- Use `defineComponent` from `@vue/composition-api` instead of `Vue.extend`.

**Comment by cefn** [comment]
Thanks, @johnsoncodehk and happy christmas! So helpful! 

I thought I'd followed through all the Vue2 steps under the settings panel of the Volar VSCode plugin, (this attempt was not visible in the commit I referenced, but because I thought I'd done all the steps and they had no effect I fell back to sharing the simpler reproduction).

However, the crucial one I missed was the `App.vue` still referencing `Vue.extend`. After eliminating that, everything worked fine.
