### ISSUE TITLE
Can I format Pug in SFC ?

### ISSUE THREAD

**Issue by richex-cn** [johnsoncodehk/volar#816]
I create a Vue3 + TypeScript + Vite project and installed the Volar plugin. When I use Pug in SFC, The JavaScript and CSS portions other than `template` are formatted, But `template` is not formatted.

This is a example: https://github.com/richex-cn/example-volar-format-sfc-pug/blob/main/src/App.vue

The reproduction steps are as follows:

1. Clone repo: <https://github.com/richex-cn/example-volar-format-sfc-pug>.
2. `pnpm i`
3. Open this repo in VSCode, And go to `src/App.vue` file.
4. Run Command: **Format Document With...** and select Volar.

I've been searching documentation, issues, and Google for a while with no results, am I missing something?

**Comment by Shinigami92** [comment]
I'm not sure if volar handles formatting on its own
Maybe you should just use my https://github.com/prettier/plugin-pug

**Comment by richex-cn** [comment]
Cool, You provided `.prettierrc.cjs` code helps me successfully format in projects using pnpm. Thanks @Shinigami92 !
