### ISSUE TITLE
Import suggestion for .vue files ends with "Vue"

### ISSUE THREAD

**Issue by gertqin** [johnsoncodehk/volar#82]
Another minor thing - the auto import suggestion for .vue files ends with Vue, e.g. 

```ts
// VolarTest.vue -> 
import VolarTestVue from "./{path}/VolarTest.vue";
```
![auto_import](https://user-images.githubusercontent.com/17803278/109931743-806f9880-7cc9-11eb-8745-5fea5e85b68c.png)

I believe most people will prefer to use the filename without the "Vue" part.

**Comment by johnsoncodehk** [comment]
thanks for report! but this is typescript correct behavior because `.vue` in included in import path.

In this project, typescript behavior has a higher priority than DX/UX.

**Comment by gertqin** [comment]
Ah, I didn't know that, because normally typescript doesn't suggest imports other than .ts (where the .ts ending is removed). If it is outside the scope of this project, then feel free to close the issue. :)

**Comment by johnsoncodehk** [comment]
Actually it's make sense. :)

import ? from "foo" -> Foo
import ? from "foo.vue" -> FooVue

**Comment by Akryum** [comment]
Is there a way to tell TypeScript not to add `Vue`?

**Comment by johnsoncodehk** [comment]
@Akryum see https://github.com/johnsoncodehk/volar/discussions/1208#discussioncomment-2598610.

**Comment by johnsoncodehk** [comment]
I'm thinking of implementing this and making it optional.

**Comment by lehni** [comment]
Our code-base is not using any TS at all and yet this `Vue` suffix gets added in imports. It's pretty confusing. An option to disable this behavior would be appreciated.
