### ISSUE TITLE
Feature request: add import intellisense (autocomplete) inside template

### ISSUE THREAD

**Issue by soulsam480** [johnsoncodehk/volar#823]
hii @johnsoncodehk, I also posted this request in discord a while ago. Basically what I wanted to request is supporting TS imports intellisense for functiions, constants etc. Currently we get import intellisense (autocomplete) for vue components, it'd be great to have similar kind of autocomplete for functions, constants etc. directly from template. I'm not sure if this is possible to implement or not, but I've seen this in svelte vscode extension https://github.com/sveltejs/language-tools . 

Again thanks for your hard work

e.g.
```ts
// file.ts
export const hello = 'world'
```
and in `.vue` file
```vue
<sciript setup>
// if we type hello here it'll give us autocomplete
</script>
<template>
{{hello}}
<!--- typing hello here can give us autocomplete intellisense -->
</template>
```

I hope you understood what I'm trying to express. thx

**Comment by johnsoncodehk** [comment]
One of the differences between vue and svelte is that due to the characteristics of vue template context, vue's template and script are not the same virtual script, so vue cannot simply support code behavior across scripts and templates.

Considering the implementation and maintenance costs, it has been decided not to support it for the time being. Maybe something will change in the future.

**Comment by social-uni** [comment]
> One of the differences between vue and svelte is that due to the characteristics of vue template context, vue's template and script are not the same virtual script, so vue cannot simply support code behavior across scripts and templates.
> 
> Considering the implementation and maintenance costs, it has been decided not to support it for the time being. Maybe something will change in the future.

Would you like to accept if I want to submit a PR about this feature

**Comment by johnsoncodehk** [comment]
After #1686, template and script is same virtual file now, reopen this.

**Comment by brunoinds** [comment]
Any news on this?
