### ISSUE TITLE
Syntax check prompt dislocation in style tag when change code in script tag

### ISSUE THREAD

**Issue by jerry000lin** [johnsoncodehk/volar#826]
When i insert newline in <script> tag, there Syntax check prompt dislocation in <style> tag

```js
<template>
  <div class="test">
    test
  </div>
</template>
<script setup>
const data = 1;
// insert newline here
</script>
<style lang="less">
.class {
}
</style>

```

![image](https://user-images.githubusercontent.com/37827614/147559989-5eb3fc01-828e-4095-bed5-5cbd1ec5b2e8.png)

it will be fixed when i change template or style tag content

![image](https://user-images.githubusercontent.com/37827614/147560083-4eaa7eb8-b40e-4388-9814-5881bdc2cc52.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report!
