### ISSUE TITLE
JSDoc comment suggestion not working

### ISSUE THREAD

**Issue by sodatea** [johnsoncodehk/volar#827]
In normal `.ts` files, `/**` would trigger a JSDoc comment suggestion:
![Kapture 2021-12-28 at 19 24 24](https://user-images.githubusercontent.com/3277634/147561529-a861589e-391f-48c4-a063-ffed18ed1c0b.gif)

This feature is described at https://code.visualstudio.com/docs/languages/typescript#_jsdoc-support

---

In `script lang="ts"`, JSDoc comment is not triggered:
![Kapture 2021-12-28 at 19 27 28](https://user-images.githubusercontent.com/3277634/147561747-d643f35f-7517-4fc5-8f67-d42747359c04.gif)

---

In normal `.ts` files after enabling Volar take-over mode:
![Kapture 2021-12-28 at 19 31 48](https://user-images.githubusercontent.com/3277634/147562076-96895321-e082-4ade-9d48-5786e2ce1e1e.gif)

**Comment by johnsoncodehk** [comment]
Thanks for the report!
