### ISSUE TITLE
pls how to fix this error Property 'template' does not exist on type 'JSX.IntrinsicElements' vue2

### ISSUE THREAD

**Issue by ysneo** [johnsoncodehk/volar#828]
in vue2
![image](https://user-images.githubusercontent.com/17615113/147723903-bda7bc68-add1-4c4d-a550-a29a0917ab84.png)
![image](https://user-images.githubusercontent.com/17615113/147723909-b72012ea-6031-47b6-bd3b-42fc17e0f631.png)

**Comment by johnsoncodehk** [comment]
Please make sure follow vue2 setup, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#usage

**Comment by ysneo** [comment]
still has warning.and more warning
![image](https://user-images.githubusercontent.com/17615113/147724687-47c9bf6b-9a49-4b8c-b185-475a950207f8.png)
![image](https://user-images.githubusercontent.com/17615113/147724698-949cf0ba-ab96-412b-bcee-174a64711a40.png)
![image](https://user-images.githubusercontent.com/17615113/147724709-18abcedd-e96a-4ac5-93ac-512dfce17a32.png)

**Comment by johnsoncodehk** [comment]
You can remove `experimentalTemplateCompilerOptions` to ignore warning, and you need to reload vscode after install `@vue/runtime-dom`.

**Comment by ysneo** [comment]
hello @johnsoncodehk , I remove `'experimentalTemplateCompilerOptions' ` and reintall `@vue/runtime-dom`, and reload vscode, its still has `Property 'template' does not exist on type 'JSX.IntrinsicElements'.ts(2339)`  error.

**Comment by johnsoncodehk** [comment]
Please try https://github.com/johnsoncodehk/volar/issues/815#issuecomment-1000867217.
