### ISSUE TITLE
ref string literals autocompletion

### ISSUE THREAD

**Issue by jd-0001** [johnsoncodehk/volar#829]
If we have code like below:

```ts
import type { Ref } from 'vue'
import { ref } from 'vue'

interface Config {
  navbar: 'sticky' | 'static' | 'hidden'
  navbarRef: Ref<'sticky' | 'static' | 'hidden'>
}

export const config: Config = {
  navbar: 'sticky',
  navbarRef: ref('sticky')
}
```

```ts
export const config: Config = {
  // pressing ctrl + space for navbar gives autocompletion
  navbar: 'sticky',

  // pressing ctrl + space inside ref should give autocompletion as well
  navbarRef: ref('sticky')
}
```

**navbar without ref**
![Screenshot 2021-12-30 at 6 11 23 PM](https://user-images.githubusercontent.com/47495003/147752861-79dd13f0-6361-4a8a-9a06-aa2ff13b1884.png)

**navbar with ref**
![Screenshot 2021-12-30 at 6 11 54 PM](https://user-images.githubusercontent.com/47495003/147752894-72812030-3beb-4916-bad6-926bf8d62fd1.png)

**Comment by johnsoncodehk** [comment]
This is expected type behavior, it can reproduce in vanilla TS script.
