### ISSUE TITLE
Weird syntax coloring on vue files

### ISSUE THREAD

**Issue by ERROPiX** [johnsoncodehk/volar#830]
I noticed that there is a weird syntax coloring behavior as I add new lines or move code, see in the bellow gif:

![volar-issue](https://user-images.githubusercontent.com/6576868/147758223-7f7c4b4c-f287-4e71-b9e6-99d2f808fe1a.gif)

The issue gets fixed once I open another tab and return back, or after I save the file and it gets reformated.

**Comment by johnsoncodehk** [comment]
Are you using 0.30.1? If yes please provide the vscode info by `Help: About` command.

**Comment by ERROPiX** [comment]
Yes, I am using the latest version of both Volar and VS Code
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by johnsoncodehk** [comment]
Can you reproduce it in https://github.com/johnsoncodehk/volar-starter?

**Comment by ERROPiX** [comment]
I couldn't replicate this anymore in any of my projects, I assume it was a temporary issue with my system.
