### ISSUE TITLE
trigger HTML to Pug

### ISSUE THREAD

**Issue by jasonfharris** [johnsoncodehk/volar#835]
Hi there,

How does one trigger the html2pug action on a selection using Volar?

I can see the other extension: https://marketplace.visualstudio.com/items?itemName=dbalas.vscode-html2pug#review-details

which does this but I can see in the sources for volar there is already the html2pug extension

**Comment by johnsoncodehk** [comment]
You need to config `"volar.codeLens.pugTools": true` from vscode setting to enable [converter codeLens](https://github.com/johnsoncodehk/volar/issues/318).
