### ISSUE TITLE
Syntax highlighting issue if we don't use dot notation

### ISSUE THREAD

**Issue by jd-0001** [johnsoncodehk/volar#836]
If we have something like below in render function of vue then syntax highlight breaks:

```js
slots['content-loading']
  ? shallShowPageLoading.value ? slots['content-loading']?.() : slots.default?.()
  : slots.default?.(),
```
![Screenshot 2022-01-03 at 4 08 07 PM](https://user-images.githubusercontent.com/47495003/147921598-d83469aa-65c8-47a0-b71e-26ccb3d5db8e.png)

![Screenshot 2022-01-03 at 4 10 15 PM](https://user-images.githubusercontent.com/47495003/147921624-98a186be-c1fe-4bdb-b6e0-c60d96957e5b.png)

Now, if we use normal dot notation like:
```js
slots.loading
  ? shallShowPageLoading.value ? slots.loading?.() : slots.default?.()
  : slots.default?.(),
```

then everything is fine.
![Screenshot 2022-01-03 at 4 11 45 PM](https://user-images.githubusercontent.com/47495003/147921771-3e9a2061-1c7f-4d35-8f9a-336197c0f527.png)

**Comment by johnsoncodehk** [comment]
It should be a vscode issue, please also try the same code in .ts file.
