### ISSUE TITLE
Increase the priority of props  to the highest level, to avoid the unnecessary suggestions scroll.

### ISSUE THREAD

**Issue by shawn-yee** [johnsoncodehk/volar#838]
![image](https://user-images.githubusercontent.com/66560386/147990320-16d08f22-df1e-4100-8cc7-60c06dba3d80.png)

**Comment by johnsoncodehk** [comment]
Thanks your suggestion, but this is expected behavior of JSX, so we will keep that for consistency.

<img width="544" alt="螢幕截圖 2022-01-09 02 17 11" src="https://user-images.githubusercontent.com/16279759/148655212-53dc3e90-d370-4c58-aeb6-13e608948c4e.png">
