### ISSUE TITLE
Volar does not respect "Editor: Auto Closing Quotes" setting when writing attributes in templates

### ISSUE THREAD

**Issue by its-dlh** [johnsoncodehk/volar#840]
When you start typing something like `class=` the Volar extension tries to be helpful and adds a pair of quotes automatically.

![image](https://media0.giphy.com/media/YKKGnQecEdRhBCUp4A/giphy.gif)

I'm sure this is an intended feature. However, this disregards the setting in VS Code that allows the developer to disable "Editor: Auto Closing Quotes".

![image](https://user-images.githubusercontent.com/2491467/148132080-f005dffa-4ce8-4837-8053-9ae178105e2e.png)

Personally, I find auto quotes or brackets distracting, as I don't expect characters to appear without my input, so I have that setting set to "never". I'm sure that I'm in the minority on that preference, given the fact that the setting is enabled by default, but I do think I'm justified in expecting an extension to respect this preference, or to add a setting of its own to disable auto quotes.

**Comment by johnsoncodehk** [comment]
This is by new html config `html.autoCreateQuotes` and it is not release yet, you need to add `"html.autoCreateQuotes": false` to settings manually for now, see https://github.com/microsoft/vscode/blob/f0054e049cd286ff317c738efe0fd8810b48ae98/extensions/html-language-features/package.json#L200-L205.

**Comment by its-dlh** [comment]
Ah, thanks, and sorry to bother you.

**Comment by johnsoncodehk** [comment]
Never mind, thanks for your report. :)

**Comment by its-dlh** [comment]
Just out of curiosity, why does it only seem to affect my Vue templates and not pure HTML files or PHP or things like that?

**Comment by johnsoncodehk** [comment]
This feature does not rely on vscode client upgrades, so Volar can release this feature earlier than vscode.

**Comment by its-dlh** [comment]
Ah, so it's an upcoming part of the spec, but the implementation is left up to extension maintainers rather than being built into VS Code itself?

**Comment by johnsoncodehk** [comment]
HTML extension is built-in support by vscode, I just refer to the code of vscode to add it for vue.

> If the implementation is custom, do you have control over which quote gets overtyped? If I type `=` and then `"`, I would expect the opening quote to get overtyped, but instead the opening quote stays in place, and the closing quote gets overtyped. Is it known yet how VS Code's core implementation will handle this?

I just follow the logic of vscode. You can open an issue in vscode. If vscode decides to change this logic, volar will change it together.

FYR https://github.com/microsoft/vscode/blob/main/extensions/html-language-features/client/src/autoInsertion.ts

**Comment by its-dlh** [comment]
Gotcha, thanks!

**Comment by keithbrink** [comment]
@johnsoncodehk There seems to be a regression on Volar where it doesn't respect the `"html.autoClosingTags": false` setting:

![0c9d7a33-32e2-459c-bd16-173bc5f2e2d8](https://user-images.githubusercontent.com/15267205/159222278-815bc6db-821e-458c-8159-a33d02af9393.gif)
