### ISSUE TITLE
question: Cannot find name on mixin data

### ISSUE THREAD

**Issue by hanbitdrone** [johnsoncodehk/volar#841]
pages/index.vue
```vue
<template>
	<Test :value="111"></Test>
</template>

<script setup lang="ts">
import Test from "~/components/test.vue";
</script>
```

components/test-parent.ts
```ts
import { defineComponent, ref } from "@nuxtjs/composition-api";

export default defineComponent({
	name: "TestParent",
	setup() {
		const parentValue = ref(314);

		return {
			parentValue,
		};
	},
});
```

components/test.vue
```vue
<template>
	<div>{{ value }} {{ parentValue }}</div>
</template>

<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";
import TestParent from "./test-parent";

export default defineComponent({
	name: "Test",
	mixins: [TestParent],
	props: {
		value: { type: Number },
	},
});
</script>
```

It works finely but Volar (I think...) shows an error **Cannot find name 'parentValue'.ts(2304)**
I'm using nuxt 2 with ```@nuxtjs/composition-api``` and ```unplugin-vue2-script-setup```

I think already set Volar settings properly.
How can I remove that error ? please help

**Comment by johnsoncodehk** [comment]
You can't, defineComponent do not handle mixins types, I think this option is not recommended in vue3.

You should use Composition API instead of mixin in vue3, you can see https://learnvue.co/2020/03/extract-and-reuse-logic-in-the-vue-composition-api/#the-problem.
