### ISSUE TITLE
Type checking without Typescript

### ISSUE THREAD

**Issue by laspinacristian** [johnsoncodehk/volar#844]
With Vetur I can get proper type checking in VScode using just Javascript (with JSDoc comments where necessary) and putting a jsconfig.json on root folder of my project with `"checkJs": true`

Is this possibile with Volar?
I tried and it seems that type checking are enable only when `lang="ts"` on `<script>` is present

**Comment by johnsoncodehk** [comment]
It's supports. `allowJs` + `checkJs` combo works for me in https://github.com/johnsoncodehk/volar-starter.

If it don't works for you, please provide a repro case.

<img width="606" alt="螢幕截圖 2022-01-09 02 02 58" src="https://user-images.githubusercontent.com/16279759/148654742-0a024cea-3c11-46b6-a2b9-cb86e2a70651.png">

**Comment by laspinacristian** [comment]
Hi @johnsoncodehk,

I meant it will not do type checking inside template interpolations (sorry to have not specified this)
In your example if you do 
```html
<template>
<p>{{ count.toLowerCase() }}</p>
</template>
```
count.toLowerCase() won't be highlited as error.

**Comment by johnsoncodehk** [comment]
@laspinacristian we can't support template type-check in js with defineComponent, because typescript only performs limited type calculations on js code, so defineComponent callback type is always any in js.

```js
// test.js
const Comp = (await import('vue')).defineComponent({ setup() { return { count: 0 } } });
(new Comp()).count.toLowerCase // no error
```

```ts
// test.ts
const Comp = (await import('vue')).defineComponent({ setup() { return { count: 0 } } });
(new Comp()).count.toLowerCase // Property 'toLowerCase' does not exist on type 'number'.ts(2339)
```
