### ISSUE TITLE
new version does not suggest props

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#846]
seems like version 0.30.2 broke the auto suggestion for props

my component
![image](https://user-images.githubusercontent.com/45350572/148505943-e175dcb7-7fe6-43de-b7c0-43fe5c1d2390.png)

suggestion 
![image](https://user-images.githubusercontent.com/45350572/148505993-5bfec03e-20d3-4fb4-a3b5-a567383c8fcf.png)

i'm using typescript version 4.5.4 and vue-tsc 0.30.2

**Comment by johnsoncodehk** [comment]
Hi @zynth17, it's works for me, could you provide repro case?

<img width="824" alt="螢幕截圖 2022-01-09 01 55 24" src="https://user-images.githubusercontent.com/16279759/148654525-be414d58-4223-47c4-a9da-ea3ad1ebd35f.png">
