### ISSUE TITLE
Multi package mono repo with inter dependencies

### ISSUE THREAD

**Issue by rikbrowning** [johnsoncodehk/volar#847]
First let me say awesome job, these tools you've created are brilliant!

This is really a question, I am a bit of a n00b when it comes to typescript set up and was wondering if you could give me some advice on how to handle it.
We have a mono repo that contains multiple packages that have inter dependencies. Right now I have manually created very basic type definition files for the packages. I would however like to leverage vue-tsc declaration generation to provide better typescript support with minimal effort.

The main issue I have is that the inter dependencies might not be compiled whenever they are referenced by consumers. I see that typescript introduced the `composite` option which seems like it's meant for this situation. Any suggestions on how best to go about this? Right now I am thinking that I will need to order the compilation to avoid any errors.

**Comment by johnsoncodehk** [comment]
The incremental build support requires a lot of effort, and there is no time to do it yet. See #787.

As an alternative, you can use `types` alias instead of project references for now.

This is a example https://github.com/johnsoncodehk/volar-starter/tree/monorepo.

**Comment by rikbrowning** [comment]
Thanks for the link, don't know how I didn't think to check these before!
