### ISSUE TITLE
<script setup> No Intellisense of imported component

### ISSUE THREAD

**Issue by 838239178** [johnsoncodehk/volar#850]
No Intellisense of imported component on SFC
![屏幕截图 2022-01-09 161924](https://user-images.githubusercontent.com/55338151/148674753-ad14099d-151a-4b56-99b3-1c73e3e6457f.png)

**Comment by 838239178** [comment]
No intellisense of 'v-model' too
![image](https://user-images.githubusercontent.com/55338151/148675023-cacb5f82-f0a9-4422-a4d4-4971fe468103.png)

**Comment by ltshb** [comment]
I've the same issue when importing component without extension e.g. `import HelloWorld from './components/HelloWorld'` although this is a valid syntax and the app is working, intellisense doesn't work and we can't jump to the definition of the HelloWorld component. However if we use the `vue` extension in the import, then intellisense works; e.g. `import HelloWorld from './components/HelloWorld.vue'`

**Comment by 838239178** [comment]
@ltshb Custom components at 'src/components' have intellisense like first image I posted

**Comment by johnsoncodehk** [comment]
It seem that `PencilIcon` is a invalid JSX component type `RenderFunction`, so volar filter it in auto-complete list.

Please see #574 for more infomation.
