### ISSUE TITLE
el-table border attribute rendered as red color

### ISSUE THREAD

**Issue by gadfly3173** [johnsoncodehk/volar#852]
![image](https://user-images.githubusercontent.com/28685179/148877090-44acf963-6c3e-4e45-bcd1-a5d8d3c029da.png)

![image](https://user-images.githubusercontent.com/28685179/148717437-d32b5e35-14cc-4e71-a4f5-f1655b6de698.png)
![image](https://user-images.githubusercontent.com/28685179/148717447-53662af0-4a7b-41d7-b246-e436110faef4.png)

It seems that the `border` property of the `<table>` is deprecated, so vscode marked it in red. But in `el-table` this property is used normally.Although I can bypass it by `:border="true"`, I still want to know if there are other solutions, because this is a bit verbose

**Comment by johnsoncodehk** [comment]
This is upstream html syntax highlight behavior so we will not change it. But you can change the highlight color your self in vscode setting, see https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme.
