### ISSUE TITLE
"type" keyword breaks template syntax highlighting

### ISSUE THREAD

**Issue by nicooprat** [johnsoncodehk/volar#854]
Hey,

Looks like the keyword `type` in a template expression (`v-for` in my case) breaks all further syntax highlighting:

![image](https://user-images.githubusercontent.com/645641/148786233-23660158-d34b-4594-8902-26a6e63f0686.png)

(Quick fix would be to use another keyword, of course)

Tried to force `editor.semanticHighlighting.enabled: true` without luck.

**Comment by nicooprat** [comment]
Thanks for the heads up. Not really handy in our case because ESlint removes it :D :

![image](https://user-images.githubusercontent.com/645641/149305817-149ed9b9-4416-4539-8b2d-95b0e860c677.png)

**Comment by johnsoncodehk** [comment]
Ah I mead this `v-for="(type in expert.user.groupedxxxxx)"`
