### ISSUE TITLE
How to add custom rules for volar

### ISSUE THREAD

**Issue by 1018715564** [johnsoncodehk/volar#856]
In some applet frameworks, there are some custom components, such as image, view, text; but vscode will report errors when formatting the code, how can I ignore these errors?

![image](https://user-images.githubusercontent.com/35763284/149155070-fb28b773-199f-4409-ac37-73e0439e71a7.png)

**Comment by johnsoncodehk** [comment]
In your case, you can change `<image ...></image>` to `<image ... />` to avoid this problem if it do not have child nodes.

Otherwise you need to send a PR to https://github.com/Prettyhtml/prettyhtml for fix.
