### ISSUE TITLE
Unhandled mehod volar/...

### ISSUE THREAD

**Issue by otatar** [johnsoncodehk/volar#857]
Hi there,

just installed volar in vs code on fresh vue 3 typescript project...my screen is filled with errors:  Request textDocument/... failed. Source: Vue Language Feature(Volar)(Extension)

OUTPUT window:

Error - 8:20:52 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
(node:38632) UnhandledPromiseRejectionWarning: Error: Unhandled method volar/getAttrNameCaseClient
    at handleResponse (/home/kali/.vscode/extensions/johnsoncodehk.volar-0.30.2/node_modules/vscode-jsonrpc/lib/common/connection.js:510:48)
    at processMessageQueue (/home/kali/.vscode/extensions/johnsoncodehk.volar-0.30.2/node_modules/vscode-jsonrpc/lib/common/connection.js:308:17)
    at Immediate.<anonymous> (/home/kali/.vscode/extensions/johnsoncodehk.volar-0.30.2/node_modules/vscode-jsonrpc/lib/common/connection.js:292:13)
    at processImmediate (internal/timers.js:461:21)
(Use `code --trace-warnings ...` to show where the warning was created)
(node:38632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:53 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:54 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:56 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:56 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:57 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:20:58 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:06 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:07 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:10 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:10 PM] Request textDocument/signatureHelp failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:11 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:11 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:12 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:14 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:15 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:16 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:17 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:17 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:18 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:18 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:18 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:19 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:19 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:20 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:22 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:22 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:23 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:25 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:25 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:26 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:21:26 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:20 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:20 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:24 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:24 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:26 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:26 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:27 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:29 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:29 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:29 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:30 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:31 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:31 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:32 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:32 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:33 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:34 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:34 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:35 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:36 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:37 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:37 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:37 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:40 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:40 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:41 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:42 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:43 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:51 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:51 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:59 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601  - 8:26:51 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:59 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:59 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:59 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:59 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 8:26:59 PM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 

Snippet from package.json:

```
 "devDependencies": {
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-0",
    "autoprefixer": "^9.8.8",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "postcss": "^7.0.39",
    "prettier": "^2.2.1",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17",
    "typescript": "~4.1.5",
    "vue-jest": "^5.0.0-0"
```

**Comment by johnsoncodehk** [comment]
Hi @otatar, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? And what operation does this problem occur in?

**Comment by MichealPearce** [comment]
My team has also been experiencing this issue. I have not been able to pin point what it causing it. Everything works perfectly fine until it doesn't. Has been a mild issue up until today where it's happening basically every 5 minutes. Restarting the volar server does not fix the issue either.

@johnsoncodehk I tried reproducing the issue in your linked starter but so far I am not experiencing it.

I've noticed that everything goes borked seemingly when I am writing code. Most of the time I would be halfway thru writing something so there would be syntax errors and then it goes borked. I've had my editor sitting open doing nothing while writing this comment and it has yet to bork out

Some details about my setup:
- in codespace
- a monorepo
- using `unplugin-vue-components`, `vite-plugin-vue-layouts`, and `vite-plugin-pages` with components, layouts, and pages spread-out into different root directories
- loaded in a vscode workspace

These are my dev deps
```
"@antfu/eslint-config": "^0.11.1",
"@types/glob": "^7.2.0",
"@types/lodash": "^4.14.177",
"@types/node": "^16.11.12",
"@typescript-eslint/eslint-plugin": "^5.4.0",
"@typescript-eslint/parser": "^5.4.0",
"@vitejs/plugin-vue": "^1.9.3",
"eslint": "^8.3.0",
"eslint-config-prettier": "^8.3.0",
"eslint-plugin-prettier": "^4.0.0",
"fibers": "^5.0.0",
"nodemon": "^2.0.15",
"npm-run-all": "^4.1.5",
"prettier": "^2.5.0",
"sass": "^1.43.5",
"typescript": "^4.5.4",
"unplugin-vue-components": "^0.17.2",
"vite": "^2.6.4",
"vite-plugin-pages": "^0.18.2",
"vite-plugin-vue-layouts": "^0.5.0",
"vue-tsc": "^0.3.0"
```

**Comment by MichealPearce** [comment]
Possible memory issue?

https://user-images.githubusercontent.com/8726457/149590472-2519eb34-9d3a-4b85-874b-2d823bcee0a3.mp4

**Comment by johnsoncodehk** [comment]
@MichealPearce thanks for your information! If memory usage is a problem, please try low power mode by setting `"volar.lowPowerMode": true`.

Relate: #531

**Comment by otatar** [comment]
> Hi @otatar, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? And what operation does this problem occur in?

I cannot reproduce with it volar-starter. But my problem is intermittent, it comes and goes with no obivous reason...

**Comment by MichealPearce** [comment]
> @MichealPearce thanks for your information! If memory usage is a problem, please try low power mode by setting `"volar.lowPowerMode": true`.
> 
> Relate: #531

Yes I tried but that that actually crashes it mostly immediately

**Comment by cefn** [comment]
I am also experiencing pages and pages of output like this when working in VSCode...

```
[Error - 10:30:57 AM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:30:57 AM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:31:10 AM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:31:11 AM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:31:12 AM] Request textDocument/hover failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
```

...and popups like 

![image](https://user-images.githubusercontent.com/159819/150767208-79a913a6-16ab-4b76-bedf-ffb4c2a91ca2.png)

It's on a large project, which I guess might have created fatal issues for Volar, compared to the starter.

**Comment by johnsoncodehk** [comment]
I have received a lot of similar problems recently. I suspect that it is related to some recent version upgrades. Please try to downgrade volar to 0.30.6, and downgrade vscode, and let me know if it has any effect.

**Comment by cefn** [comment]
Thanks, @johnsoncodehk could you suggest a target VSCode version so that I can test effectively? Or do you not know what to target and we need to bisect?

**Comment by johnsoncodehk** [comment]
@cefn I can't suggest the exact version, but if that's the reason, I think the problem should happen with a version update within 2 months.
