### ISSUE TITLE
Go to definition doesn't work with Vue component imported without extension

### ISSUE THREAD

**Issue by ltshb** [johnsoncodehk/volar#858]
When importing a single file Vue component without the `*.vue` extension, then the `Go to definition` doesn't work.

For example with the code below

```html
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <HelloWorld msg="Welcome to Your Vue.js App"/>
</template>

<script>
import HelloWorld from './components/HelloWorld'

export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>

<style>
...
</style>
```
We cannot use `Go to definition` to go to the definition of `HelloWorld` Vue component. However if you change the import as follow:

```javascript
import HelloWorld from './components/HelloWorld.vue'
```
It works.

**Comment by johnsoncodehk** [comment]
This is expected behavior, and vue3 has deprecated the use of no extension.
