### ISSUE TITLE
vue-tsc build dts doesn't handle tsconfig path alias correctly

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#863]
Hi Author,

My Project use tsconfig path alias and the output of `vue-tsc --declaration --emitDeclarationOnly` seems to keep them intact rather than replace them with the real path.

![image](https://user-images.githubusercontent.com/1321817/149547672-9657d1b8-6d58-489a-966c-78d59d74e2bb.png)

![image](https://user-images.githubusercontent.com/1321817/149547414-19acc2be-1c73-43b5-9f2a-d12549e75768.png)

**Comment by johnsoncodehk** [comment]
This is expected behavior, `compilerOptions.paths` is only for how do TS resolve your path, but it do not change the emit path, see https://www.typescriptlang.org/tsconfig#paths.

**Comment by HankZhi** [comment]
> This is expected behavior, `compilerOptions.paths` is only for how do TS resolve your path, but it do not change the emit path, see https://www.typescriptlang.org/tsconfig#paths.

So is there any method that we could use `typescript-transform-paths` plugin in `vue-tsc`? when use it in `tsc` tool, this plugin has resulted as @cmcnicholas expected

**Comment by visualjerk** [comment]
There is a npm packages, which can solve that exact issue: https://www.npmjs.com/package/resolve-tspaths

Simply chain it after generating the `.d.ts` files and it resolves and replaces all path aliases:

```bash
vue-tsc && resolve-tspaths
```

If you have a specific tsconfig, make sure to provide it to resolve-tpaths as well:

```bash
vue-tsc --project tsconfig.declarations.json && resolve-tspaths --project tsconfig.declarations.json
```

**Comment by uturnr** [comment]
To add to @visualjerk's comments, I used another package `tsc-watch` to get a watch mode working.

**Build once**
```
vue-tsc -p tsconfig.app.json && resolve-tspaths -p tsconfig.app.json
```

**Watch**
```
tsc-watch --compiler vue-tsc/bin/vue-tsc -p tsconfig.app.json --onSuccess 'resolve-tspaths -p tsconfig.app.json'
```
