### ISSUE TITLE
New version does not suggest props

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#864]
Hello, i just want to follow up for #846 
try to call hello world component with msg props.
it does not suggest the props msg anymore.

here is the repro.
https://github.com/zynth17/vitailse/tree/bug-vue-tsc

**Comment by johnsoncodehk** [comment]
Do you have update build make components.d.ts include HelloWorld?

```diff
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
+    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
  }
}
```

**Comment by zynth17** [comment]
> Do you have update build make components.d.ts include HelloWorld?
> 
> ```diff
> declare module 'vue' {
>   export interface GlobalComponents {
>     AppHeader: typeof import('./src/components/AppHeader.vue')['default']
> +    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
>     'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
>     'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
>     'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
>   }
> }
> ```

![image](https://user-images.githubusercontent.com/45350572/149639695-f6a406cc-cae1-4887-b9ec-b5c9c26ded90.png)

yes i have.
it does not show the  props.

**Comment by johnsoncodehk** [comment]
I can't reproduce, it's works for me. Could you try delete `env.d.ts`?

**Comment by IIFelix** [comment]
Don't know if this is related, but typechecking doesn't work if if use "withDefaults" in script setup.
Tested it in a new project from "yarn create vite"
![volar-bug](https://user-images.githubusercontent.com/56734789/149666553-843ec261-e260-473e-aae9-b8d1b3ca8504.PNG)
"

**Comment by johnsoncodehk** [comment]
@IIFelix this is a regression in 0.30.3, I'm publishing 0.30.4 for fix, please try it later.

**Comment by IIFelix** [comment]
Sure thing. Ty for the fix :)

**Comment by zynth17** [comment]
> I can't reproduce, it's works for me. Could you try delete `env.d.ts`?

it does work on my repro, but weirdly does not work on my real project.

**Comment by johnsoncodehk** [comment]
@zynth17 You need to check how the repro case is different from your project, if it can't reproduce in the repro case we can't help. :)
