### ISSUE TITLE
SFC on Nuxt doesn't read tsconfig.json

### ISSUE THREAD

**Issue by pei-pay** [johnsoncodehk/volar#867]
I keep getting the following error stack in VS Code(only *.vue files.  *.ts files are fine)

![スクリーンショット 2022-01-17 18 07 22](https://user-images.githubusercontent.com/68349963/149740176-e89ed234-0dee-4100-bc97-a7beaf49895a.png)

vscode footer shows `No tsconfig` when I open vue files 
![スクリーンショット 2022-01-17 18 08 48](https://user-images.githubusercontent.com/68349963/149740391-ed456eb6-150a-46f6-8ded-b30ab37be995.png)

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": ["ESNext", "ESNext.AsyncIterable", "DOM"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": [
      "@types/node",
      "@types/jest",
      "expect-playwright",
      "@nuxt/types",
      "@nuxtjs/vuetify",
      "@nuxt/vue-app",
      "@nuxtjs/sentry",
      "nuxt-logrocket",
      "nuxt-i18n",
      // "pinia/nuxt/types",
      "@types/chart.js",
      "unplugin-vue2-script-setup/types",
      "unplugin-vue2-script-setup/ref-macros"
    ]
  },
  "vueCompilerOptions": {
    "experimentalCompatMode": 2
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

nuxt settings
```ts
declare module '@vue/runtime-dom' {
  export * from '@vue/runtime-dom/dist/runtime-dom'
  export * from '@vue/composition-api'
}
```

environment
```
OS: Mac Catalina 10.15.7
VSCode: 1.63.2(Universal)
Extensions: Only Volar v0.30.5 (I deleted other extensions for debug)
```

**Comment by johnsoncodehk** [comment]
You may need to use `include` option to include your vue files, you can reference https://github.com/johnsoncodehk/volar-starter/blob/7a4b2f99103f5eab0bad76365be841f264623211/tsconfig.json#L14.

**Comment by pei-pay** [comment]
thank you 

but... it's not working.

**Comment by johnsoncodehk** [comment]
Could your provide a minimal reproduction?

**Comment by pei-pay** [comment]
i tried cloning my repositories and somehow it's fixed..

It might be my local env problem, but still not sure what the problem really was.

Sorry to trouble you.　I appreciate your kind response.
