### ISSUE TITLE
Very high CPU usage with Volar

### ISSUE THREAD

**Issue by aalexgabi** [johnsoncodehk/volar#872]
### Description

I experience 50% CPU usage when Volar is enabled. To reproduce it I simply type continuously in a .vue file while 10 other .vue files are open and task manager is also open. Then I go to process details for the vs code child process that uses most CPU and I find Volar and eslint both using about 15%.

If I disable Volar CPU goes to 15% for entire vscode process tree.

This was also reported [here](https://github.com/johnsoncodehk/volar/issues/256) but the issue was closed for lack of reproducibility. I hope that you are able to reproduce it by typing very fast.

Using volar@0.30.5 and vscode@1.63.2

### Task manager overview
![image](https://user-images.githubusercontent.com/600821/149920377-79181461-8c8e-404d-860e-d88a96693bac.png)

### Process details
![image](https://user-images.githubusercontent.com/600821/149920612-5f9beadc-2d14-4ae2-997c-d1fdfd6197d1.png)

**Comment by aalexgabi** [comment]
Maybe the issue is related to autocomplete? Just an idea.

**Comment by johnsoncodehk** [comment]
Does opened 10 other .vue files is the necessary condition to reproduce the problem?

**Comment by aalexgabi** [comment]
@johnsoncodehk With one file open the usage is around 27% CPU (while typing) which is very high for an editor with one file opened. The problem becomes really visible and annoying when the editor becomes laggy if other programs are running on the system and characters appear later.

**Comment by johnsoncodehk** [comment]
These are options you can try to reduce cpu usage.

- Do not open multiple files at the same time, this will aggravate the diagnostic work.
- Use low power mode by setting `"volar.lowPowerMode": true`
- Disable `.value` auto-complete by setting `"volar.autoCompleteRefs": false`
- Disable auto import by setting `"javascript.suggest.autoImports": false`, `"typescript.suggest.autoImports": false`
