### ISSUE TITLE
TS errors appear depending on the semicolon in SFC script setup

### ISSUE THREAD

**Issue by Oleksii14** [johnsoncodehk/volar#874]
Hello! I noticed an issue while writing unit tests in my Vue 3 application.

### Description

While using two top-level script blocks in SFC, there appear TS errors in the console after Vite build. Errors are thrown from `@vue/test-utils` typings, but it does not seem to be an issue with this library. Those errors depend on the trailing coma from the first script block, which seems to be a parsing issue.

Reproduction repository: https://github.com/Oleksii14/vue-jest-type-issue

### Steps to reproduce

[Reproduction repo](https://github.com/Oleksii14/vue-jest-type-issue)
Steps:
```shell
pnpm i
```

```shell
pnpm run test:unit # test will pass
```

```shell
pnpm run build # will fail, see the type errors
```

Then go to `HelloWorld.vue` and remove a semicolon in line 4.
Perform the steps above and the build error will disappear.

### Expected behavior
Type errors do not appear and do not depend on the semicolon in the top-level script

See the related [issue](https://github.com/vuejs/test-utils/issues/1232) I've created in `@vue/test-utils` repo

**Comment by johnsoncodehk** [comment]
Thanks for the report!

**Comment by Oleksii14** [comment]
@johnsoncodehk thanks for a quick fix!
