### ISSUE TITLE
Volar wrongly giving not-found errors when not using script setup

### ISSUE THREAD

**Issue by zhekaiii** [johnsoncodehk/volar#875]
This happens if I'm not using the setup sugar `<script setup>` and instead am using `setup() { return {  } }`. Switching to `<script setup>` fixes the red wiggly lines. I know `<script setup>` probably should be preferred, and the Script Setup Tools is making it easy to refactor, but still.

![image](https://user-images.githubusercontent.com/40530851/150076471-bfb71ff4-d285-49c7-857a-765a21110113.png)
![image](https://user-images.githubusercontent.com/40530851/150076496-5e12e210-dabe-4367-bf00-92b35b5609d9.png)
![image](https://user-images.githubusercontent.com/40530851/150076526-a3cce500-7f70-4351-93ad-440dee1b932e.png)

**Comment by johnsoncodehk** [comment]
Please try wrap your component options with `defineComponent` if you have not.
