### ISSUE TITLE
Rename `@volar/server` package name and cli command

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#876]
As a part of refactor tasks, I'm planing rename `@volar/server` to `@volar/vue-language-server`, and change cli command from `volar-server` to `vue-language-server`.

Considering this has some impact on other IDE tools, I'll keep this issue for a while.

**Comment by williamboman** [comment]
Hey! I think it'd be neat if the old executable had remained (but been deprecated), to allow room for tooling to update without breaking!

**Comment by williamboman** [comment]
Ah, that's a good point. I didn't consider that the package name was changed.
