### ISSUE TITLE
ts(6133): never read in v-for if only using the index

### ISSUE THREAD

**Issue by panwauu** [johnsoncodehk/volar#878]
I use v-for sometimes for iterating using the index of an array. Normally in typescript I can use "_" to ignore the first parameter and only use the second one. Using Volar I always get an error.
```vue
<div v-for="(_, i) in ['a','b','c']">{{i}}</div>
```
```
'_' is declared but its value is never read.ts(6133)
```

Workarounds are:

```vue
<div v-for="(_, i) in ['a','b','c']">{{i}}</div> // Renders: 0 1 2; Leads to ts error
<div v-for="i in ['a','b','c'].length">{{i}}</div> // Renders: 1 2 3; Workaround a
<div v-for="i in [...Array(['a','b','c'].length).keys()]">{{i}}</div> // Renders: 0 1 2; Workaround b
```

Old issue: https://github.com/johnsoncodehk/vue-tsc/issues/59

Related problem: https://github.com/johnsoncodehk/volar/issues/329
Here the issue is, that the variable is used in :key but volar does not recognize that it is actually used

**Comment by johnsoncodehk** [comment]
Thanks for the report!
