### ISSUE TITLE
Global Components with Custom Elements

### ISSUE THREAD

**Issue by Sertion** [johnsoncodehk/volar#879]
Greetings.

I've been trying to use Vue with Custom Elements in Typescript and can not get typing to work in the templates.

[Repro repo](https://github.com/Sertion/volar-starter).

I've used the `GlobalComponents` interface as described in the [vscode Volar extension README](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) and the custom element tags show up as `any`.

**Comment by botteroxom** [comment]
I have the same problem.. 
I create an vue plugin and I have a folder with all d.ts with jsdocs comments like /*This is a simples button*/
How can I add all those components so they can be seen in intelisense when someone is using my plugin.. 
they are located in node_modeules\myplugin\dist\components 
and look like this.. 
``` ts
declare const _default: import("vue").DefineComponent<{
    /**
     * Display as a primary button.
     * Set a primary button anytime there is a preferred
     * path among multiple buttons (in a pair of OK and Cancel buttons,
     * for example, OK is typically the primary button).
     */
    primary: BooleanConstructor;
    /**
     * The default appearance of an button
     */
    secondary: BooleanConstructor;
    /**
    
    ...
    
    
    
    Buttons trigger actions or navigation.
They are either button (for action) or an a elements (for navigation).
Soft corners (set to 4 px) suggest confidence and stability.

@example ./UButton.Example.md

*/
export default _default;
```

**Comment by johnsoncodehk** [comment]
Sorry for late to reply, I'm not familiar with Custom Elements, but `MyElement` seems not a valid JSX element type, so it can't use in template.

```tsx
// src/test.tsx
import { MyElement } from './MyElement';
() => <MyElement></MyElement>; // 'MyElement' cannot be used as a JSX component.
```

Maybe you could reference this solution: https://github.com/johnsoncodehk/volar/issues/505#issuecomment-923563463
