### ISSUE TITLE
support vue2 scope-slot

### ISSUE THREAD

**Issue by BTBMan** [johnsoncodehk/volar#881]
![image](https://user-images.githubusercontent.com/26108004/150451422-5144094d-d610-4bf3-8883-d2c54c644d4f.png)

**Comment by xiaoxiangmoe** [comment]
@BTBMan slot-scope is deprecated. use v-slot instead. Volar support it well.

**Comment by johnsoncodehk** [comment]
@xiaoxiangmoe since I'm not familiar with vue2, thanks for the clarification!
