### ISSUE TITLE
hope support vue2 computed

### ISSUE THREAD

**Issue by xiaoxian521** [johnsoncodehk/volar#882]
thanks！！！
![image](https://user-images.githubusercontent.com/44761321/150460224-4ec124d4-663d-4b27-a53f-47911f9e0a3c.png)

**Comment by johnsoncodehk** [comment]
Hi @xiaoxian521, you need to use `defineComponent` to wrap your component, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#usage.

**Comment by xiaoxian521** [comment]
thanks for your reply this solved my problem thanks
