### ISSUE TITLE
some error occur when install volar 0.30.6 , but 0.30.5 is normal

### ISSUE THREAD

**Issue by hayabusa2009** [johnsoncodehk/volar#883]
![image](https://user-images.githubusercontent.com/28643492/150515937-9a5524c4-ef1b-4ce5-baba-151ee8d290bd.png)

**Comment by johnsoncodehk** [comment]
Thanks for the report! When using script setup, extra options intellisense is always base on `defineComponent` is future, so remove `defineComponent` from export options when using script setup is the official recommendation.
