### ISSUE TITLE
Pug format/convert classes to class attribute

### ISSUE THREAD

**Issue by xxSkyy** [johnsoncodehk/volar#888]
Using Tailwind/WindiCSS often requires using colons in class names for responsiveness which is not supported by pug non-attribute class names or rather not allowed for further pug functionalities. So when using pug in this configuration it's best to keep all classes in class attributes for consistency.

It'd be great if Volar had the option for pug converter to always place classes in class attribute than dot elements before

**Comment by johnsoncodehk** [comment]
Could you give a example what is the expected behavior and what is actually result you got?

**Comment by Shinigami92** [comment]
@xxSkyy You may be interested in https://prettier.github.io/plugin-pug/guide/pug-specific-options.html#notation
`pugClassNotation`

**Comment by xxSkyy** [comment]
> Hi @xxSkyy, could you provide an example what is the expected behavior and what is actually result you got?

Having

```vue
<template>
<div class="mt-2 bg-red-200 rounded-md">
  Content
</div>
</template>
```

when I'll convert it to pug with volar I'll get result like

```vue
<template lang="pug">
.mt-2.bg-red-200.rounded-md
  | Content
</template>
```

but It'll be nice to have attribute only classes as I said above for code consistency in tailwind/windi like to get output like this instead

```vue
<template lang="pug">
div(class="mt-2 bg-red-200 rounded-md")
  | Content
</template>
```

**Comment by Shinigami92** [comment]
Okay, yeah, then you should just use `pugClassNotation: 'attribute'` with @prettier/plugin-pug and it will just format it over the whole project as you want it

**Comment by xxSkyy** [comment]
> Okay, yeah, then you should just use `pugClassNotation: 'attribute'` with @prettier/plugin-pug and it will just format it over the whole project as you want it

I've just checked that and works as should, thanks! 

But it'll be great to have this feature in volar pug-html conversion in the future
