### ISSUE TITLE
Volar cannot offer intellisense auto completion due to your project being ....

### ISSUE THREAD

**Issue by myWsq** [johnsoncodehk/volar#89]
I'm pretty sure I'm using vue v3.0.7... Maybe it's a problem caused by the new version.
![image](https://user-images.githubusercontent.com/35214490/110150663-790bd480-7e1a-11eb-83a7-0584e47db661.png)

**Comment by johnsoncodehk** [comment]
Actually I make a bug in volar 0.22.2 :sweat_smile:, I'm not sure is 0.22.2 problem or not. Can you try 0.22.3?

**Comment by myWsq** [comment]
It worked
