### ISSUE TITLE
Cannot reference type in template from `<script setup>` since 0.31.0

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#891]
```html
<template>{{ 1 as Foo /* any */ }}</template>

<script lang="ts" setup>
type Foo = string;
</script>
```

**Comment by rogier-stegeman** [comment]
Doesn't work without `setup` for me either.

**Comment by johnsoncodehk** [comment]
@jaulz this behavior changed in https://github.com/johnsoncodehk/volar/commit/c5a62efaa10acb6f095169d4cdcff099c61180e6, actually now this is a design limitation, I still finding a workaround.

**Comment by jaulz** [comment]
@johnsoncodehk thanks for the feedback (and of course your work)! Fingers crossed that there will be a solution soon since I sometimes get an `any` from scoped slots that I need to cast and that's impossible to fix at the moment as far as I can see.
