### ISSUE TITLE
Typescript cannot find module using @ root path syntax in a project created from create-vue

### ISSUE THREAD

**Issue by pholly** [johnsoncodehk/volar#894]
I've got a weird one. Originally posted in https://github.com/vuejs/create-vue/issues/35

### Summary
When creating a project in the new recommended way using `npm init vue@3`, `@` root path imports show an error in .vue files. `@` root path imports work fine inside .ts files. The strange thing is others haven't been able to reproduce my problem. See the issue mentioned above.

### Setup
Visual Studio code - up to date
Vue Language Features (Volar) - v0.31.1
TypeScript Vue Plugin (Volar) - v0.31.1
Windows 11

### Steps to reproduce
```
npm init vue@3
Typescript support: yes
Everything else: no

pnpm install (or npm install)
```

Open App.vue and change an import to use `@/` root path syntax. E.g.  `import TheWelcome from '@/components/TheWelcome.vue'`. I get an error: `Cannot find module '@/components/TheWelcome.vue' or its corresponding type declarations.ts(2307)`

<img width="596" alt="image" src="https://user-images.githubusercontent.com/3717650/150814635-42829539-a0c2-44a9-8fd1-bf35864fbb97.png">

### Things I tried

- Disabling all other plugins
- Uninstalling/reinstalling Volar plugins
- Enabled Take Over Mode

**Comment by xiaoxiangmoe** [comment]
@pholly Can you give a minimal reproducible demo?

**Comment by olemarius** [comment]
Rolling back from 0.31.1 to v0.30.6 worked for me.

**Comment by pholly** [comment]
@xiaoxiangmoe the easiest reproducable demo is to use `npm init vue@3` and choose TypeScript and no to every other option then change an import inside App.vue to use `@/` syntax instead of relative path.

I tried Visual Studio Code Insiders:

- No error now in App.vue - `@/` root path syntax works
- Now I get a cannot find module error in main.ts on `import App from '@/App.vue'`. The `@/` syntax works for non .vue imports, like if I try to import another TypeScript file. 

@olemarius rolling back to v0.30.6 didn't work for me - I still get the error in App.vue.

**Comment by xiaoxiangmoe** [comment]
@pholly 

Do you install https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-typescript-vue-plugin ？

**Comment by johnsoncodehk** [comment]
@pholly can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by pholly** [comment]
@johnsoncodehk yes same problem. I also get an error in main.ts when using `@/` syntax on import of a vue file. Relative paths work in both cases. Screenshots below.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/3717650/151174550-1f39cc7e-4bd6-4e12-a12c-b68eee6242cf.png">

<img width="473" alt="image" src="https://user-images.githubusercontent.com/3717650/151174928-f24a539d-5a20-4195-af69-c2569d7e57c4.png">

**Comment by johnsoncodehk** [comment]
@pholly have you try config `"paths": { "@/*":["./src/*"] },` in tsconfig on the project?

**Comment by pholly** [comment]
@johnsoncodehk just tried. Still same errors in both. Also the error in main.ts prevents the app from running (starting the dev server). If I fix main.ts, the site builds and runs but the error in App.vue shows up immediately in the browser.

I also tried closing and reopening VS Code.

Let me know if there's anything else you want me to try.

**Comment by xiaoxiangmoe** [comment]
It seems that Windows will not allow use `"paths": { "@/*":["src/*"] },`, try change it to `"paths": { "@/*":["./src/*"] },`.

**Comment by johnsoncodehk** [comment]
@pholly I can't reproduce this problem and I think it's related to your system, please try @xiaoxiangmoe's suggestion.

If still not working, you can use [live share](https://code.visualstudio.com/learn/collaboration/live-share) with me so I will able to check the problem. You can join volar discord server(https://discord.gg/5bnSSSSBbK) to find me.

**Comment by pholly** [comment]
No errors in either main.ts or App.vue! I mistakenly put the paths line outside of compilerOptions. When I moved it there both errors went away. Yes I have to specify `./src/*` like you both mentioned. If I put just `src/*` an error shows that the baseUrl is not specified.

I still get the error in App.vue in a project created from `vue init vue@3` (create-vue). BaseUrl is specified in compilerOptions and even if I change path to `./src/* I still get the error.

Let me know how I should proceed - go back to my issue in create-vue project?

**Comment by johnsoncodehk** [comment]
@pholly if the path option generated by `create-vue` you should report there.

**Comment by pholly** [comment]
@johnsoncodehk sorry although I don't get errors when viewing main.ts or App.vue in VS Code, I get errors when trying to run the app with `npm run dev`.: 

`[vite] Internal server error: Failed to resolve import "@/App.vue" from "src\main.ts". Does the file exist?`

Likewise I get an error in App.vue if I fix the path in main.ts to be relative.

I'll reach out to you on volar's discord. Thanks for all your work and help.

**Comment by johnsoncodehk** [comment]
@pholly tsconfig only for IDE, you should config (resolve.alias)[https://cn.vitejs.dev/config/#resolve-alias] in vite.config for vite.

**Comment by johnsoncodehk** [comment]
@alexvoedi make sure you have add your vue files to `include` option of tsconfig: https://github.com/johnsoncodehk/volar-starter/blob/7a4b2f99103f5eab0bad76365be841f264623211/tsconfig.json#L14

**Comment by alexvoedi** [comment]
Everything is set up correctly in my project. Vetur works fine, Volar does not. This has only been a problem for a few days.

**Comment by johnsoncodehk** [comment]
@alexvoedi could you provide minimal reproduction?

**Comment by pholly** [comment]
@johnsoncodehk I have the same problem as @alexvoedi in .vue files in projects created from create-vue. `"src/**/*.vue"` is definitely in `include` in tsconfig. 

tsconfig:
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "isolatedModules": true,
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"],
    "skipLibCheck": true
  },
  "include": ["vite.config.*", "env.d.ts", "src/**/*", "src/**/*.vue"]
}
```

<img width="863" alt="image" src="https://user-images.githubusercontent.com/3717650/151571775-b908692a-b61a-49e5-b62a-4140b49bd285.png">

**Comment by xiaoxiangmoe** [comment]
@pholly could you provide minimal reproduction?

**Comment by pholly** [comment]
@xiaoxiangmoe I can't reproduce anymore - `npm init vue@3` works now. I just tried it 3 times and in all 3 projects tsconfig was recognized in .vue files. The screenshot above was from the same command a few days ago. I see that create-vue npm package was just updated a few hours ago - maybe that's why I have no issue now.

@johnsoncodehk I have no problems with projects created from create-vue now. 

Thank you both.

**Comment by coader** [comment]
> I have the same problem. Something I noticed:
> 
> ![image](https://user-images.githubusercontent.com/37340862/151375163-baa12e7c-3c0c-40d6-b4f2-1d84fa963d63.png)
> 
> In newly created *.vue files VS Code does not find tsconfig.json.

also got this tips

**Comment by mattiaz9** [comment]
if I have a component named `home.vue` doesn't recognize the tsconfig, but with any other name it does.

**Comment by moreant** [comment]
I have the same problem. Looks like tsconfig is not found.  
I have done case renaming of this file and directory, system is windows.

<img width="1012" alt="7fa155047714c4afdec0491ce1ce0f0" src="https://user-images.githubusercontent.com/45537528/164071553-5912fad8-44a0-47b1-ab82-2fc3738a3e2b.png">

vue files in the same folder are normal
<img width="1036" alt="283837d3ad6f221a287111fd2564042" src="https://user-images.githubusercontent.com/45537528/164071592-7004e0b7-2033-49eb-810e-6d3ecfb15bd2.png">

When I move the TempCoverPage.vue file to the "form" folder it works fine
![image](https://user-images.githubusercontent.com/45537528/164071821-b7a90d8e-e0a6-451e-b5b5-0409acc739e9.png)

**Comment by moreant** [comment]
https://github.com/johnsoncodehk/volar/issues/894#issuecomment-1102964298

I deleted the temp folder and then recreated the vue folder. It was normal. At that time, the temp folder with different capitalization appeared in the git commit. I'm guessing it might have something to do with this
![image](https://user-images.githubusercontent.com/45537528/164075400-1f832246-1f9b-48fc-b28b-28345d60dcd1.png)

**Comment by pleek91** [comment]
I have this issue in a project as well. Seems like the alias works if the .vue file doing the importing is either two words, or lowercase its fine. 

`button.vue` - alias works
`ButtonSection.vue` - alias works
`Button.vue` - alias does not work

**Comment by mollyxfma** [comment]
I got same problem recently, without any update in my project.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/102200626/174565273-4a1fd201-49c5-4c8d-abe5-3aa20c446915.png">

**Comment by mollyxfma** [comment]
> 

when i disable volar and use vetur, typescript errors disappeared
<img width="689" alt="image" src="https://user-images.githubusercontent.com/102200626/174569876-6cfc3201-5f92-4e35-aa38-78f1484a0215.png">

**Comment by gitlilimin** [comment]
I have the same problem, i have not change any file, it was normal to open it yesterday, but now this problem happened.

This is a windows10 PC, volar auto update to v0.38.7

the problem looks like:
- in .ts file, import xx from "@/xxx" is right
- in .vue file, import xx from "@/xxx" is wrong
- tsconfig.json filled in the correct settings
- project can be "dev" without any error
- project can be "build" without any error
- all project occur same problem in your VSCode workspace

I try there things:
1. reload my PC
2. uninstall VSCode and install it (no any other extensions), and install volar 
3. try vscode-typescript-vue-plugin
4. try [Take Over Mode](https://github.com/johnsoncodehk/volar/discussions/471)
5. try create a new vue project

As an obsessive-compulsive disorder, I feel hopeless...

But in the end, I found the problem.
**It seems to be related to VSCode workspace**
when i pick the project to a new VSCode window, it fixed. And when i open it in the old workspace, this problem reappears.

Bad workspace, "../../tsconfig"
![bad](https://user-images.githubusercontent.com/32194203/179374498-ff7679bf-3c86-45cb-9d64-b3dd86477690.png)

Good workspace
![good-takeover](https://user-images.githubusercontent.com/32194203/179374531-041583ca-8a06-4237-8b8b-6787c80bb567.png)

you can see right-bottom, "tsconfig.app.json", It seems that volar read the root directory of the project incorrectly

**Comment by gitlilimin** [comment]
> 

I found a new phenomenon right now

2 project in 1 workspace, the first project is right, second project wrong

![image](https://user-images.githubusercontent.com/32194203/179374824-b123eb7a-8b31-4e5c-991c-dba6e5971173.png)
 
change the project order, result changed

![image](https://user-images.githubusercontent.com/32194203/179374836-b647cf1b-8c57-40dd-a926-30ac302fa982.png)


Interesting~

**Comment by johnsoncodehk** [comment]
@gitlilimin It may related to #1193, #1262 fixing. Could you provide a minimal reproduction?

**Comment by gitlilimin** [comment]
@johnsoncodehk ok, I tried it, this problem only occur at volar 0.38.8

### My environment

- PC, windows 10
- VS Code:
![image](https://user-images.githubusercontent.com/32194203/179416632-0a43dd13-dedb-4dc1-8ddc-052ea2f91240.png)
- VS Code extension: 
![image](https://user-images.githubusercontent.com/32194203/179416589-43437229-094a-4c04-b5c7-bc8db0200fa0.png)


### Reproduction steps
1. clone this repo from https://github.com/gitlilimin/debug-volar-0.38.8, there are 3 project in it

- [vue3-create] is create from `npm init vue@latest`, [doc](https://staging-cn.vuejs.org/guide/quick-start.html#with-build-tools)
- [vite-create] is create from `npm init vite@latest`, [doc](https://vitejs.cn/guide/#scaffolding-your-first-vite-project)
- [old-project] is the project with problems after the update of volar yesterday, it's a real project, i have removed useless code.

2. you'd better run `npm install` for there 3 project
3. open a VS Code window, make sure it's workspace is empty, the window bottom color is blue (not purple)
4. drag [vue3-create] to VS Code window, and it will looks like
![image](https://user-images.githubusercontent.com/32194203/179417185-6c3d5aad-893c-468a-bc02-4063891307c2.png)

5. drag [vite-create] to VS Code window, and drag [old-project] to VS Code window
![image](https://user-images.githubusercontent.com/32194203/179417222-94e7b4a5-f1a2-477c-9e46-93ec230da33c.png)

7. now there 3 project in VS Code window, and there are in same workspace.
8. open [old-project]/src/views/home.vue and you will look this:
![image](https://user-images.githubusercontent.com/32194203/179417284-f6d8f283-13c3-49fb-abc7-6dbef38149d1.png)


### Personal summary

**I think this problem must be related to the workspace of vscode, and I'm sure it happened in volar 0.38.8**

I found some phenomena in the process of trying to find the problem.

- VSCode open a pure project (no workspace), i use above [old-project], it's always right.
![image](https://user-images.githubusercontent.com/32194203/179417531-5eba0639-ff60-4ce8-80a9-fc284ab4629d.png)

- in above case, in [vue3-create] project, some component import by "@xxx" can be distinguish, but some cannot (like <TestComponentVue/>).
![image](https://user-images.githubusercontent.com/32194203/179417618-6da8a566-a326-4e70-b783-65887697ea3c.png)

- in [vue3-create]/src/App.vue,  <HelloWorld /> tag, put mouse on it can get right tips, but cannot use Ctrl+Click to open it's file.
![image](https://user-images.githubusercontent.com/32194203/179417810-f926e01b-abfc-475a-9935-7a19b8a4bd64.png)

- in [old-project]/src/vies/home.vue, <HelloWorldVue/> tag can use Ctrl+Click to open it's file. in this file, only <XButton> and <XComponent> is wrong, becase their path is deeper than others

- in a few case, VSCode open [old-project] some .vue file, the right-bottom "tsconfig.json" cannot be read, it's only show "no tsconfig". it's ok when i restart VSCode.

**Comment by zhangyanwei** [comment]
@gitlilimin Thank you, you saved my time.

**Comment by wsli10** [comment]
> ![image](https://user-images.githubusercontent.com/37340862/151375163-baa12e7c-3c0c-40d6-b4f2-1d84fa963d63.png)

The vscode right-bottom "No tsconfig" maybe just caused by incorrect **include** config.
`./src/**/*.vue` didn't match vue files out of `src` dir, use `./**/*.vue` instead.
see [tsconfig#include](https://www.typescriptlang.org/tsconfig#include)
```json
{
  "compilerOptions": {
    // ...
    "paths": { "@/*": ["./src/*"] } // path alias
  },
  "include": ["./**/*.ts", "./**/*.vue"]
}
```

**Comment by saeedtabrizi** [comment]
> @johnsoncodehk I have the same problem as @alexvoedi in .vue files in projects created from create-vue. `"src/**/*.vue"` is definitely in `include` in tsconfig.
> 
> tsconfig:
> 
> ```
> {
>   "compilerOptions": {
>     "baseUrl": "./",
>     "target": "esnext",
>     "useDefineForClassFields": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "isolatedModules": true,
>     "strict": true,
>     "jsx": "preserve",
>     "sourceMap": true,
>     "resolveJsonModule": true,
>     "esModuleInterop": true,
>     "paths": {
>       "@/*": ["src/*"]
>     },
>     "lib": ["esnext", "dom", "dom.iterable", "scripthost"],
>     "skipLibCheck": true
>   },
>   "include": ["vite.config.*", "env.d.ts", "src/**/*", "src/**/*.vue"]
> }
> ```
> 
> <img alt="image" width="863" src="https://user-images.githubusercontent.com/3717650/151571775-b908692a-b61a-49e5-b62a-4140b49bd285.png">

This is a good hint . I had same issue but now it's OK . Thanks @olemarius

**Comment by gitamitdixit** [comment]
@johnsoncodehk @alexvoedi @saeedtabrizi I also had the same issue today after scaffolding a brand new project using vite, it got resolved by simply adding  "moduleResolution": "node" in compilerOptions object of tsconfig.app.json
<img width="471" alt="Screenshot 2023-06-12 at 20 32 06" src="https://github.com/vuejs/language-tools/assets/15609148/6092a81e-e121-4d76-a022-0c60498d8851">

**Comment by mitar** [comment]
For me it worked after I added to `src` directory a `env.d.ts` file with the following:

```
declare module "*.vue" {
  import type { DefineComponent } from "vue"
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/ban-types
  const component: DefineComponent<{}, {}, any>
  export default component
}
```

**Comment by Stubbs** [comment]
@mitar your solution works for me too, do you know why?

**Comment by msteen** [comment]
I ran into this issue with my own Volar (not Vue) project and it turned out I had to set `baseUrl` in `compilerOptions` for `paths` to work. I thought this was no longer require due to the [TypeScript docs](https://www.typescriptlang.org/tsconfig#baseUrl) saying:

> As of TypeScript 4.1, baseUrl is no longer required to be set when using [paths](https://www.typescriptlang.org/tsconfig#paths).

**Comment by joshrincon-aven** [comment]
FYI i noticed for me that adding `.vue` to the import statement solves the problem for me. more of a short term solution, however.

**Comment by lorenzyannick** [comment]
Solved by adding a file named "vetur.config.js" at the root of the project


with
```
module.exports = {
  // **optional** default: `{}`
  // override vscode settings
  // Notice: It only affects the settings used by Vetur.
  settings: {
    "vetur.useWorkspaceDependencies": true,
    "vetur.experimental.templateInterpolationService": true,
  },
  // **optional** default: `[{ root: './' }]`
  // support monorepos
  projects: [
    "./mySubDirWhereTheVueJSProjectIs", // Shorthand for specifying only the project root location
  ],
};

```

See https://vuejs.github.io/vetur/guide/setup.html#advanced

**Comment by so1ve** [comment]
You should disable vetur.

**Comment by lorenzyannick** [comment]
> You should disable vetur.

Oh yes !
Vetur is the old version. I didn't even notice. After removing Vetur extension from VSCode it's working well. THX !
(No need vetur.config.js anymore)

**Comment by Leander-van-Boven** [comment]
> > ![image](https://user-images.githubusercontent.com/37340862/151375163-baa12e7c-3c0c-40d6-b4f2-1d84fa963d63.png)
> 
> The vscode right-bottom "No tsconfig" maybe just caused by incorrect **include** config. `./src/**/*.vue` didn't match vue files out of `src` dir, use `./**/*.vue` instead. see [tsconfig#include](https://www.typescriptlang.org/tsconfig#include)
> 
> ```json
> {
>   "compilerOptions": {
>     // ...
>     "paths": { "@/*": ["./src/*"] } // path alias
>   },
>   "include": ["./**/*.ts", "./**/*.vue"]
> }
> ```

This fixed it for me, apparently the create vue CLI did not add the `./src/**/*.vue` to the `include` while `./src/**/*.ts` was

**Comment by RejownAhmed** [comment]
> @johnsoncodehk @alexvoedi @saeedtabrizi I also had the same issue today after scaffolding a brand new project using vite, it got resolved by simply adding "moduleResolution": "node" in compilerOptions object of tsconfig.app.json <img alt="Screenshot 2023-06-12 at 20 32 06" width="471" src="https://private-user-images.githubusercontent.com/15609148/245235373-6092a81e-e121-4d76-a022-0c60498d8851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTcwOTgsIm5iZiI6MTcyNzA5Njc5OCwicGF0aCI6Ii8xNTYwOTE0OC8yNDUyMzUzNzMtNjA5MmE4MWUtZTEyMS00ZDc2LWEwMjItMGM2MDQ5OGQ4ODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEzMDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZGEwNzkzYjY2MDdhZDQ1Y2NlY2U0Mjg4NDk5NmViOWY2ZWRhZjllY2VlY2QxMzYzZTRmYmUzNmMwNDQzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KjB4e3WfSdkdjut_mmU7ZPa1qmD4uz8tppY_i9qN7Dc">

It fixed my pb

**Comment by dan-wellman-cs** [comment]
FWIW I had this same issue in a (large) commercial Vue3 app that I am trying to migrate to TypeScript.

I started out by scaffolding out a brand new project with create-vue, choosing Yes for the TypeScript option, and then copying the generated config from the new app to the existing app.

Everything was kind of working, but I could not get rid of the red underlining under every single import path that used `@/...`

I tried most of the suggestions here, disabled extensions in VSCode, added extensions in VSCode, changed module resolution to node, etc, etc. But still the problem persisted.

The only thing that worked for me was to move the `baseUrl` and `paths` options from tsconfig.app.js up to the root tsconfig.json file. Then, finally, the red underlining under my imports vanished. It seems VSCode, or the official (recommended) Vue extension, loads only the default tsconfig file, not the tsconfig.app version...

**Comment by mitar** [comment]
My fix with `env.d.ts` starting returning errors after upgrading to latest versions of everything:

```
.../env.d.ts
  3:3   error  Definition for rule '@typescript-eslint/ban-types' was not found                                                                                                                                                                                                                                                                                                                           @typescript-eslint/ban-types
  4:36  error  The `{}` ("empty object") type allows any non-nullish value, including literals like `0` and `""`.
- If that's what you want, disable this lint rule with an inline comment or configure the 'allowObjectTypes' rule option.
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead  @typescript-eslint/no-empty-object-type
  4:40  error  The `{}` ("empty object") type allows any non-nullish value, including literals like `0` and `""`.
- If that's what you want, disable this lint rule with an inline comment or configure the 'allowObjectTypes' rule option.
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead  @typescript-eslint/no-empty-object-type
✖ 3 problems (3 errors, 0 warnings)
```

I simply removed it and for now it seems things work in VS Code, but I am not sure if that is just some caching or do things really work now without it.
