### ISSUE TITLE
release configuration for the repo

### ISSUE THREAD

**Issue by Oleksii14** [johnsoncodehk/volar#895]
Hello!
I always check the latest updates of `vue-tsc` and it is very hard to understand the changes using git tags without any information. Could you configure `semantic-release` or another approach?

**Comment by johnsoncodehk** [comment]
Hi @Oleksii14, is [Changelog](https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md) hard to read the changes of vue-tsc?

**Comment by Oleksii14** [comment]
My bad 🤦, didn't notice the change log. I was always looking at the tags section and there was no description at all. Thanks!
