### ISSUE TITLE
type information lost in slot item variable

### ISSUE THREAD

**Issue by fabsenet** [johnsoncodehk/volar#896]
![image](https://user-images.githubusercontent.com/2065705/150979979-416ee5a7-cd5e-44b9-b3c3-714c51bc5093.png)

I have this code and `item`s type is detected as any. `Partner.PartnerMsgTypeVersion` is of type `Something[]`, so item should be of type `Something` then, but is actually detected as type any. Consequently it does not all me to call the function, which is properly typed.

Help? 🥲 

    "vue": "^2.6.12",
    "vuetify": "^2.5.1",

**Comment by johnsoncodehk** [comment]
Seems `v-data-table` do not provide generics slots type, so you need to make type annotation your self.

`#item.sensitivity="({ item } as typeof partnet.partnerMessageTypeVersions[number])"`
