### ISSUE TITLE
unexpected type script errors related to imports

### ISSUE THREAD

**Issue by Oleksii14** [johnsoncodehk/volar#897]
### Reproduction

Repo: https://github.com/Oleksii14/volar-import-issue

```shell
pnpm run build
```
See the errors in the console.

Then:
1. Visit App.vue
2. Move line 2 to line 3 or 4
3. The error will disappear

Seems to be a parsing issue

**Comment by trusktr** [comment]
imports in `.vue` files recently stopped working. Everything is imported as type `any`.

![Screenshot 2022-01-24 172320](https://user-images.githubusercontent.com/297678/151076566-1c62f22d-c17b-4377-8d82-c57259b5f4b3.jpg)

This shows that no refs can be found except in the file I'm using them in (not the source file):

![Screenshot 2022-01-24 153344](https://user-images.githubusercontent.com/297678/151076570-aefc8e67-76d8-4a3d-a33a-e49fe4ed0b1b.jpg)

**Comment by trusktr** [comment]
Hmm, actually I downgraded, but still can't get import types back. Perhaps something in the codebase makes Volar fail. The repo is at https://github.com/nasa/openmct.

**Comment by johnsoncodehk** [comment]
@Oleksii14 this is expected trade off behavior on volar. After 0.31, import expressions must be placed at the top. Will this be a problem in some cases?

**Comment by johnsoncodehk** [comment]
@trusktr I can't reproduce this first problem. Have you reload vscode or restart volar server after installed node_modules? Which branch and file are you test in?
<img width="506" alt="螢幕截圖 2022-01-26 11 47 43" src="https://user-images.githubusercontent.com/16279759/151100922-b5bbf7d5-cf61-41b2-94d7-dab5a7abf2ef.png">

`import xxx from` expression can only response current file references. You need do find references on `default` keyword to  find other import references. (But there is currently a bug in including virtual files.)
<img width="717" alt="螢幕截圖 2022-01-26 11 51 07" src="https://user-images.githubusercontent.com/16279759/151101175-479e319a-de88-4f28-97f3-9789b5f34b11.png">

Or if you using TS plugin or take over mode (See #664), you can do fine references at `default` keyword on ConfigStore.js.
<img width="483" alt="螢幕截圖 2022-01-26 12 01 19" src="https://user-images.githubusercontent.com/16279759/151101926-02a078ec-dccf-4b77-afd0-9e41ed9a7fe1.png">

**Comment by Oleksii14** [comment]
@johnsoncodehk in this case, this issue is not actual. Didn't know that imports should be on the top 😄 
Thanks for the response 👍🏻

**Comment by Oleksii14** [comment]
@trusktr I am not sure it is a reason or not, but why to you use `Vue.extend` in Vue 3? 😄 
Try to use `<script setup>`, maybe it will fix the issue

**Comment by johnsoncodehk** [comment]
@Oleksii14 Just to clarify, this is a volar limitation not vue limitation. Volar must simplify the way of virtual code generation for the reliability of IDE features, otherwise some IDE features cannot effectively map between original code and virtual code.

If this behavior becomes a problem in some cases please raise it and I will seek a solution.

> @trusktr I am not sure it is a reason or not, but why do you use `Vue.extend` in Vue 3? 😄 Try to use `<script setup>`, maybe it will fix the issue

This is a vue 2 project so it use `Vue.extend`. But anyway this is a different problem, nice to have a new issue for tracking.

**Comment by dmoles** [comment]
Is there a way… not to use Volar? This is not something I expected, and it's going to mean major refactoring if I want to keep my code readable but can no longer group imports with related code.
