### ISSUE TITLE
Can't skip verification of node_modules

### ISSUE THREAD

**Issue by scinos** [johnsoncodehk/volar#899]
Similar to https://github.com/johnsoncodehk/vue-tsc/issues/16

When I run `vue-tsc`, I get errors from `node_modules`, even if I use `--skipLibCheck`.

![image](https://user-images.githubusercontent.com/975703/151144924-18bc6639-54a5-4317-8544-eb0b10a02612.png)

Using vue-tsc 0.31.1

**Comment by johnsoncodehk** [comment]
`--skipLibCheck` can't ignore files that if you have reference it.

In this case you need to config `"noImplicitAny": false` in tsconfig to ignore this error.
