### ISSUE TITLE
Code completion for props doesn't work in template

### ISSUE THREAD

**Issue by alex-knyazev** [johnsoncodehk/volar#909]
As we see VS Code can parse props in js part of file:
![image](https://user-images.githubusercontent.com/15632220/151538377-23308490-0cbf-40a6-af38-09aff7c230f0.png)

But not in template. In template editor know that `props` variable exists, but don't know it's type
 
![image](https://user-images.githubusercontent.com/15632220/151538494-56d5b61b-5659-4e23-9193-55bb48e5d224.png)

**Comment by johnsoncodehk** [comment]
Because the type of `defineComponent` is too complex, using `lang="js"` exceeds the type calculation limit. TypeScript can only extract props types when used `lang="ts"`.

**Comment by alex-knyazev** [comment]
@johnsoncodehk Maybe is it possible to add this feature but disable it by default. It works for js code, why can't it work in the same way in templates?

**Comment by johnsoncodehk** [comment]
This is a limitation of TS, not something volar can change, if you want type-safe in template you can just use `lang="ts"`.

> It works for js code, why can't it work in the same way in templates?

It can't works for js, you can try `test.js` in your project from https://github.com/johnsoncodehk/volar/issues/909#issuecomment-1024153150

**Comment by Akryum** [comment]
Is there a way to change this limit? Is there an issue in the Typescript repo about this?

**Comment by johnsoncodehk** [comment]
@Akryum I don't think TypeScript will resolve it... Does `lang="ts"` + `// @ts-nocheck` can be a option?
