### ISSUE TITLE
v-for directive wrong types with 3 arguments

### ISSUE THREAD

**Issue by JSteitz** [johnsoncodehk/volar#910]
Currently, I get the wrong type for name and index in `v-for` directive with 3 arguments.

```vue
<div v-for="(value, name, index) in object"></div>
```
`name`: Type 'number' is not assignable to type 'string'
`index`: Argument of type 'undefined' is not assignable to parameter of type 'number'

**Comment by johnsoncodehk** [comment]
Please provide a minimal reproduction.
