### ISSUE TITLE
Ref flagged as deprecated

### ISSUE THREAD

**Issue by Eldair** [johnsoncodehk/volar#911]
Custom variable/ref marked as deprecated in template of SFC

![image](https://user-images.githubusercontent.com/470003/151571427-94822ebb-6bbe-4c79-9ee8-00f32e5e8394.png)

**Comment by johnsoncodehk** [comment]
Please provide a minimal reproduction.

**Comment by Eldair** [comment]
Here it is

```
<template>
    <div :class="[status ? 'asd' : 'zxc']"></div>
</template>

<script>
import {ref} from 'vue';

export default {
    setup() {
        const status = ref(false);

        return {status};
    },
};
</script>

```

**Comment by johnsoncodehk** [comment]
You can't typed component context in template without defineComponent and `lang="ts"`, please try
```vue
<template>
  <div :class="[status ? 'asd' : 'zxc']"></div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  setup() {
    const status = ref(false);

    return { status };
  },
});
</script>
```

**Comment by Eldair** [comment]
I'm not using TS at all

**Comment by johnsoncodehk** [comment]
`lang="ts"` is optional, at least you need `defineComponent`, otherwise volar cannot extract the component context.

**Comment by Eldair** [comment]
Hm, so that's plugin specific (it is not in vue docs and it works without that)? It seem like unnecessary additional func call.
