### ISSUE TITLE
vue-3-sanitize is not detected

### ISSUE THREAD

**Issue by florianrubel** [johnsoncodehk/volar#913]
Link to package: https://www.npmjs.com/package/vue-3-sanitize

Volar says, it can't find the name $sanitize if the plugin is registered globally.

Vetur can. So I switched back to Vetur.

Also global Components are marked as red. not an error. Just red.

**Comment by johnsoncodehk** [comment]
Hi @florianrubel, please check out solutions from
- https://vuejs.org/api/utility-types.html#componentcustomproperties
- https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#usage
