### ISSUE TITLE
Path resolution bugs with symbolic links

### ISSUE THREAD

**Issue by SnowyCoder** [johnsoncodehk/volar#914]
This has been quite confusing for me.

**Summary**

Since JS projects tend to be quite heavy I tend to put them in a separate hard disk and make a symbolic link to my /home.
Found out this messes things up quite a bit.

**Setup**

VSCodium - 1.63.2
Vue Language Features (Volar) - v0.31.1
Manjaro Linux (5.16.2-1-MANJARO)

**Steps to reproduce**
``` bash
cd /tmp # Or any
mkdir a
ln -s a b
cd b
npm init vue@3
# Typescriupt: Yes
# Everything else: No
cd vue-project
npm install
```
Open /tmp/a with vscode, disable `@builtin typescript...` and reload (to enter takeover mode), here everything works.
Open /tmp/b with vscode, disable `@builtin typescript...` and reload,
- App.vue will show "No tsconfig"
- If we change main.ts import to use `@/App.vue` it won't be recognized (`Cannot find module...`).

**Comment by johnsoncodehk** [comment]
Thanks for the report!
