### ISSUE TITLE
First auto-import is added on same line as `<script>`

### ISSUE THREAD

**Issue by Akryum** [johnsoncodehk/volar#916]
When I auto import something in a `.vue` file, the first time it add the code on the same line as the opening `<script>` tag.

Actual:
```vue
<script lang="ts" setup>import { PropType } from 'vue'
import { Story } from '../types'
import StoryListItem from './StoryListItem.vue'

const props = defineProps({
  stories: {
    type: Array as PropType<Story[]>,
    required: true,
  },
})
</script>
```

Expected:
```vue
<script lang="ts" setup>
import { PropType } from 'vue'
import { Story } from '../types'
import StoryListItem from './StoryListItem.vue'

const props = defineProps({
  stories: {
    type: Array as PropType<Story[]>,
    required: true,
  },
})
</script>
```

Reproduction steps:
- Create an empty `.vue` file
- Add a `script` section
- Auto import something using the intellisense popover

Volar v0.31.1

**Comment by johnsoncodehk** [comment]
Hi @Akryum, thanks for the report! But unfortunately even this is a simple problem, we don't have a suitable solution to resolve. Unless we have to prohibit any code at first line in script block.

**Comment by Akryum** [comment]
So there is no possible solution their from Volar, VS Code or another part of the stack?

**Comment by johnsoncodehk** [comment]
Just have a idea to fix. :)

**Comment by Akryum** [comment]
Awesome! 😻

**Comment by Akryum** [comment]
Looks like the issue is back @johnsoncodehk 

![image](https://user-images.githubusercontent.com/2798204/160611604-adb198ab-ccf9-45f1-911e-4cdeae86cd66.png)

![image](https://user-images.githubusercontent.com/2798204/160611664-19749927-d210-4dff-bdd9-a17de17f0478.png)

![image](https://user-images.githubusercontent.com/2798204/160611793-7e504fe4-f1c6-4e8d-89b7-2952242371af.png)
