### ISSUE TITLE
vite: require doesn't work in .vue template for dynamic image path

### ISSUE THREAD

**Issue by SamRahnama** [johnsoncodehk/volar#919]
hello there i'm not sure this duplicated or not 
steps to reproduce:

1. 

 `<img
            v-for="number in [currentPosition]"
            :src="getImg"
        />
`

2. 

>  data(){
> return {
>       currentPosition: 0,
>  images: ["dog.jpg", "download.jpg", "sad.jpg", "shrek.jpg"],
> }
> }
> computed:{
>     getImg(){
>       return require(`@/assets/images/${this.images[this.currentPosition]}`)
>     }
>   }

my package.json:

> {
>   "private": true,
>   "scripts": {
>     "dev": "nuxi dev",
>     "build": "nuxi build",
>     "start": "node .output/server/index.mjs"
>   },
>   "devDependencies": {
>     "nuxt3": "latest"
>   }
> }

and you probably get this 
![image](https://user-images.githubusercontent.com/18219117/151747519-23a575ab-f41c-453a-83b2-2e5c5b52a800.png)
just solve this by turning off vite so webpack be in charge .

> export default defineNuxtConfig({
>     vite: false
> })

 **edit: images array added**

**Comment by Shinigami92** [comment]
I think this is expected, cause Vite doesn't support old legacy `require`
Beside that, I think this has nothing to do with Volar
