### ISSUE TITLE
vetur attributes to volar ? 

### ISSUE THREAD

**Issue by productfrontenddeveloper** [johnsoncodehk/volar#92]
![Screen Shot 2021-03-08 at 06 59 18](https://user-images.githubusercontent.com/38668796/110272683-cf744100-7fdb-11eb-9272-c21aa9201ea7.png)
iam used custom components props in vetur setting add, how to volar ? 

attributes.json
![Screen Shot 2021-03-08 at 07 00 16](https://user-images.githubusercontent.com/38668796/110272736-f0d52d00-7fdb-11eb-8282-c293a5908ab7.png)

tags.json
![Screen Shot 2021-03-08 at 07 00 29](https://user-images.githubusercontent.com/38668796/110272751-fa5e9500-7fdb-11eb-870a-e799f9738557.png)

Vetur is not reading what I have done now, since I deleted it.

**Comment by johnsoncodehk** [comment]
For now we using App `component()` calls and `__VLS_GlobalComponents` to define global components, see: https://github.com/johnsoncodehk/volar#using

Attributes intellisense support is base on props option, and I deliberately avoid support json config.

**Comment by productfrontenddeveloper** [comment]
```
import AtomFormsTitleAndDescription from 'components/atom/forms/TitleAndDescription.vue'

export const plugin: Plugin = {
    install(app) {
        app.component('AtomFormsTitleAndDescription', AtomFormsTitleAndDescription);
    }
}

/* The following code will be automatically generated */
declare global {
    interface __VLS_GlobalComponents {

        'AtomFormsTitleAndDescription': typeof AtomFormsTitleAndDescription
    }
}``` 

nuxt ./my-global-components-plugin.ts path add thats true ?

**Comment by johnsoncodehk** [comment]
```ts
import { App } from 'vue'
import AtomFormsTitleAndDescription from 'components/atom/forms/TitleAndDescription.vue'

export const plugin: Plugin = {
    install(app) {
        app.component('AtomFormsTitleAndDescription', AtomFormsTitleAndDescription);
    }
}
```

It should be work, if not working please give me a repro.

**Comment by productfrontenddeveloper** [comment]
![Screen Shot 2021-03-10 at 06 28 05](https://user-images.githubusercontent.com/38668796/110572075-c7e2a280-8169-11eb-979b-3f21f3a38434.png)

**Comment by productfrontenddeveloper** [comment]
![Screen Shot 2021-03-10 at 06 31 52](https://user-images.githubusercontent.com/38668796/110572379-50614300-816a-11eb-9c3a-bff840f251e3.png)

**Comment by johnsoncodehk** [comment]
Many issues to be aware of here... could you just share the repo? I will show you how to make it work.

**Comment by productfrontenddeveloper** [comment]
https://codesandbox.io/s/zealous-tu-2jsuh
rerepo, You can test it for any component.

**Comment by johnsoncodehk** [comment]
[2jsuh - volar.zip](https://github.com/johnsoncodehk/volar/files/6113177/2jsuh.-.volar.zip)
![螢幕截圖 2021-03-10 下午12 29 05](https://user-images.githubusercontent.com/16279759/110576871-80293e80-819c-11eb-9405-9dc7b4a22d45.png)

1. Make sure you have install `@vue/runtime-dom` because you are using vue 2, see: https://github.com/johnsoncodehk/volar#using
2. When you using `*.vue` import path in ts files, you should have `shims-vue.d.ts` or enabled `volar.tsPlugin`.

**Comment by johnsoncodehk** [comment]
> ![Screen Shot 2021-03-10 at 07 44 06](https://user-images.githubusercontent.com/38668796/110577770-65db6a80-8174-11eb-9aeb-6ed223c26240.png)
> 
> Thank you fix, does auto not recommend
> 
> ![Screen Shot 2021-03-10 at 07 44 51](https://user-images.githubusercontent.com/38668796/110577827-81df0c00-8174-11eb-8caa-07ef50cbb40c.png)

Sorry it's a bug with vue 2, should be fixed in 0.22.9.

**Comment by productfrontenddeveloper** [comment]
![Screen Shot 2021-03-10 at 11 18 31](https://user-images.githubusercontent.com/38668796/110598040-59fea100-8192-11eb-97a4-4ad721676d7c.png)
new problem :)

**Comment by productfrontenddeveloper** [comment]
Fixed, thank you :)

**Comment by johnsoncodehk** [comment]
Please open a vue file after updated volar, and than vscode should tell you reload.

**Comment by productfrontenddeveloper** [comment]
![Screen Shot 2021-03-10 at 11 25 48](https://user-images.githubusercontent.com/38668796/110598904-5e778980-8193-11eb-96bf-c91ef1070413.png)

![Screen Shot 2021-03-10 at 11 27 19](https://user-images.githubusercontent.com/38668796/110599117-95e63600-8193-11eb-877b-7ba1c9b2e7b4.png)

```color='black'``` 
shouldn't it be used that way, or is it automatic what you do is correct?

**Comment by johnsoncodehk** [comment]
`:color="'black'"` is equal to `color="black"`, but I just show `:color` on auto-complete list to make it simplify, you can remove `:` character yourself.
