### ISSUE TITLE
Breacking on update vue-tsc 0.30.6 -> 0.31.1

### ISSUE THREAD

**Issue by cawa-93** [johnsoncodehk/volar#921]
When I tried to upgrade vue-tsc 0.30.6 -> 0.31.1, I started getting the following error: ([Source Code](https://github.com/cawa-93/anime-library/blob/942c0fd9acfdbfb1e19a2217e24b224cf16089a7/packages/renderer/src/pages/Home/AnimeCollection/AnimeCollectionSingleCard.vue#L11-L15), [Failed build](https://github.com/cawa-93/anime-library/runs/5021158490?check_suite_focus=true))
```js
<script setup>

// imports 

declare module 'csstype' { // error TS1234: An ambient module declaration is only allowed at the top level in a file.
  interface Properties {
    '--bullet-color'?: string;
  }
}

// ...
</script>
```

**Comment by xiaoxiangmoe** [comment]
use this instead.
```vue
<script lang="ts">
declare module 'csstype' { // error TS1234: An ambient module declaration is only allowed at the top level in a file.
  interface Properties {
    '--bullet-color'?: string;
  }
}
</script>
<script setup lang="ts">

// imports 


// ...
</script>
