### ISSUE TITLE
`class` types appear to have React bleed-in

### ISSUE THREAD

**Issue by ksnyde** [johnsoncodehk/volar#922]
I suspect this might not be really a **Volar** issue but i'm not sure where else to turn at the moment. I have a documentation site that is based off of @antfu's popular **Vitesse** plugin and all of my `.vue` files are reporting errors on the class property:

![image](https://user-images.githubusercontent.com/980757/152032671-f54a1eac-fadc-427b-86c1-a4ce40d9a288.png)

with the language around `className` i'm suspecting that something that likes React is interfering as I have another repo on the same machine which is behaving correctly. That said, if you look at the direct dependencies of this project they are all pretty much "the usual suspects":

```json
"dependencies": {
    "@vueuse/core": "^7.5.5",
    "@vueuse/head": "^0.7.5",
    "date-fns": "^2.28.0",
    "floating-vue": "^2.0.0-beta.5",
    "inferred-types": "^0.18.4",
    "nprogress": "^0.2.0",
    "pinia": "^2.0.11",
    "prism-theme-vars": "^0.2.2",
    "tauri-search": "workspace:*",
    "vue": "^3.2.29",
    "vue-demi": "^0.12.1",
    "vue-i18n": "^9.1.9",
    "vue-router": "^4.0.12"
  },
```

with my own repo being the sole outlier but it's dependencies are relatively innocuous too:

```json
  "dependencies": {
    "axios": "^0.25.0",
    "dotenv": "^14.3.2",
    "fast-glob": "^3.2.11",
    "inferred-types": "^0.18.4",
    "native-dash": "^1.21.5"
  },
```

the last two are my own repos but I'm using these with Volar in other repos without issue. Is there any way that a dev-dep could interfere? Is there anyway to work around this? The impact is quite large in that my Vue templates no longer format/indent anymore (plus all those red squigglies are slowly driving me mad).

**Comment by ksnyde** [comment]
Also note that I did see other people say that adding `vite/client` to their **tsconfig.json** helped but I have done that:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "ESNext",
    "target": "es2016",
    "lib": ["DOM", "ESNext"],
    "strict": true,
    "esModuleInterop": true,
    "incremental": false,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "types": [
      "vite/client",
      "vite-plugin-pages/client",
      "vite-plugin-vue-layouts/client"
    ],
    "paths": {
      "~/*": ["src/*"],
    }
  },
  "include": ["src", "test", "vite.config.ts"],
  "exclude": ["dist", "node_modules",]
}
```

**Comment by ksnyde** [comment]
It seems a devDep is bleeding from my dep on a workspace module which has a devDep on `simple-markdown` which in turn depends on `@types/react`: 

![image](https://user-images.githubusercontent.com/980757/152040664-ba3137d9-b327-43c0-a3f8-a551dd7b7280.png)

I'm surprised this is coming in.

**Comment by Jassmin586** [comment]
I have project based on Vue CLI (not Vite). Same problem and I didn't know how to fix this.

**Comment by MichealPearce** [comment]
> Also note that I did see other people say that adding `vite/client` to their **tsconfig.json** helped but I have done that:
> 
> ```json
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "module": "ESNext",
>     "target": "es2016",
>     "lib": ["DOM", "ESNext"],
>     "strict": true,
>     "esModuleInterop": true,
>     "incremental": false,
>     "skipLibCheck": true,
>     "moduleResolution": "node",
>     "resolveJsonModule": true,
>     "noUnusedLocals": true,
>     "strictNullChecks": true,
>     "forceConsistentCasingInFileNames": true,
>     "types": [
>       "vite/client",
>       "vite-plugin-pages/client",
>       "vite-plugin-vue-layouts/client"
>     ],
>     "paths": {
>       "~/*": ["src/*"],
>     }
>   },
>   "include": ["src", "test", "vite.config.ts"],
>   "exclude": ["dist", "node_modules",]
> }
> ```

Adding `vite/client` to my tsconfig didn't do anything for me. I'm not sure why, but I found a work around to be importing in a ambient declaration file. 

```ts
// vite.d.ts
import 'vite/client'
```

I don't think this will help your issue tho, but are you in a vscode workspace context? If yes, is that workspace module added to the vscode workspace? If no, does the folder you have open in vscode contain both this vue app and the `tauri-search` module?

I use a similar setup with workspaces in yarn2 and don't experience any bleed thru of deps. I got the exact opposite where I have issues making sure types are getting in from my workspace deps.

**Comment by MichealPearce** [comment]
I also found something in the [README.md](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#note) of the vscode extension that relates to this

**Comment by johnsoncodehk** [comment]
Please check out solutions from #592.
