### ISSUE TITLE
functional component props issues

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#924]
Apologies if this is not the right place for this, as I'm unclear if this is a volar issue or vue core issue.

UPDATE - Did some more digging and I think I see what's happening (sort of).

It seems that previously, when defining functional components, we could define them by adding an extra `.props` property on the exported function, and type-checking would work correctly. For example:
```vue
<script lang="ts">
const FunctionalComponent = (props, context) => {
  return h('div', { class: 'functional-thing' });
};
FunctionalComponent.props = {
  prop1: { type: String as PropType<'foo' | 'bar'>, required: true },
});
export default FunctionalComponent;
</script>
```

It seems recently something changed and now the types are being inferred from the types set on the `props` arg only, similar to how things work when using type-based props syntax on defineProps.
```vue
<script lang="ts">
type ShapeOfMyProps = {
  prop1: 'foo' | 'bar',
};

const FunctionalComponent = (props: ShapeOfMyProps, context) => {
  return h('div', { class: 'functional-thing' });
};
export default FunctionalComponent;
</script>
```

While at first glance this seems great, there are a few issues:
- some features are only available via the object based syntax (default values, validation functions, boolean coercion), which means we'll still have to use the object syntax _in addition_ in many cases
- the shape of the props when passed to the function are different than the shape that define the props
  - for example an optional boolean prop or a prop with a default value is optional when using the component, but will always be defined when passed into the function

Regardless, we'll need to figure out best practices here, add some examples in the vue docs, and make sure everything works with what is recommended. Having two ways to do things in normal components (non functional) still presents some problems as well, so I think there may be a [larger discussion](https://github.com/vuejs/rfcs/discussions/394#discussioncomment-2114242) to be had in general...

Personally, I think requiring the object syntax to define the props would make sense, and volar can infer the prop types relevant to _using_ the component from that `FunctionalComponent.props` object. The shape of the props arg within the function should then be able to be inferred fairly easily (I think `ExtractPropTypes` already does this). I don't know if theres any way to make this happen automatically though, so it will have to be explicit. 

For example:
```typescript
const propsDefinition = {
  prop1: { type: String as PropType<'foo' | 'bar'>, required: true },
};

const FunctionalTest3 = (props: ExtractPropTypes<typeof propsDefinition>, context: any) => {
  return h('div', { class: ['functional-test-3'] }, context.slots.default());
};

FunctionalTest3.props = propsDefinition;
```

Some examples of what's not working

![image](https://user-images.githubusercontent.com/1158956/152395280-324f6835-87b5-4ae7-8725-86eb5f99ce2e.png)

Repro with some examples available here - https://github.com/theoephraim/vue-ts-props-bugs

Thanks!

**Comment by johnsoncodehk** [comment]
Hi @theoephraim, sorry for late to reply! Just had a quick look and these is problems what I found.

For `ImportedObject`, `RegularComponent`, you should define props object by `as const`.
```diff
export const propsDefinitionObject = {
  // should be checked that some value is set
  requiredProp: { type: String, required: true },
- };
+ } as const;
```

```diff
export const propsDefinition = {
  // should be checked to match one of these values, should get intellisense autocomplete to pick one too
  prop1: { type: String as PropType<'foo' | 'bar'> },
  // should be checked to be a number
  numberProp: { type: Number },
  // should be checked that some value is set
  requiredProp: { type: String, required: true },
  // should not be checked value is string, should NOT be required
  hasDefault: { type: String, default: 'has a default' },
  // should be checked value is boolean, should NOT be required
  optionalBoolean: { type: Boolean },
- };
+ } as const;
```

---

> It seems that previously, when defining functional components, we could define them by adding an extra .props property on the exported function, and type-checking would work correctly. For example:

For `FunctionalWithStaticProps`, `FunctionalTest`, `FunctionalTest2`, as I know we never supported this before. And we can't, because it's incompatible to TS working principle

---

For `FunctionalTest3`, please try use `InstanceType<DefineComponent<typeof propsDefinition>>['$props']` instead of `ExtractPropTypes<typeof propsDefinition>`.

**Comment by theoephraim** [comment]
@johnsoncodehk - I finally got back to working on the tool this question came up on and can confirm the typing works with `InstanceType<DefineComponent<typeof propsDefinition>>['$props']` :)

One issue still remains - the type still seems to think the prop could be undefined, even though I have a default set. Any ideas there?
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1158956/189427350-9affeabe-0389-4c7e-b8cb-376e2ad05305.png">

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1158956/189427391-13e02b5f-ae71-408d-b4e5-971a6b38061b.png">

Also - any idea what the TS type should be for the `context` arg in a functional component like this?

Thanks so much!

PS - It might be nice to make an official exported type as part of vue (the one that extracts the props from an object) since it's pretty gnarly and I definitely could imagine it changing in the future... When I get this all figured out, I think I'll add some PRs to the official vue docs and maybe this type as well.
