### ISSUE TITLE
vs code Indent

### ISSUE THREAD

**Issue by tmkmk** [johnsoncodehk/volar#925]
vs code 
版本: 1.63.2 (user setup)
提交: 899d46d82c4c95423fb7e10e68eba52050e30ba3
日期: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

![vs code](https://user-images.githubusercontent.com/23163691/152186275-780684ff-a0e7-4e38-b24f-c258195a37c7.png)

![volar](https://user-images.githubusercontent.com/23163691/152186393-240508fc-3ddf-48d5-a9e5-927e6f589675.png)

![Bug](https://user-images.githubusercontent.com/23163691/152186430-1d316b59-3601-4499-bc62-980a351ae79d.gif)

**Comment by sethidden** [comment]
@tmkmk To clarify - the problem you're reporting is that collapsed code blocks un-collapse themselves when you remove some code that's above those code blocks, right?

**Comment by WhiteCoffee9834** [comment]
我的不会,除非删除的代码会导致错误才会引起折叠失效

可能是其他扩展导致的结果?

**Comment by tmkmk** [comment]
> @tmkmk To clarify - the problem you're reporting is that collapsed code blocks un-collapse themselves when you remove some code that's above those code blocks, right?

yes,collapsed code blocks un-collapse themselves;
Sorry, I can't speak English. You see my sentence is not smooth

**Comment by tmkmk** [comment]
> 

![cash vue - cmp-p - Visual Studio Code 2022-02-08 08-49-48 00_00_07-00_00_39](https://user-images.githubusercontent.com/23163691/152897720-4cd47492-49ee-4f17-a949-447495d2b60d.gif)

**Comment by tmkmk** [comment]
> 感谢您的报告！但是我无法重现此问题，您能提供最小的复制代码吗？
Thank you very much for your response.After the plug-in is updated, I can't reproduce it
