### ISSUE TITLE
defineEmits with union operator bug

### ISSUE THREAD

**Issue by leonzalion** [johnsoncodehk/volar#926]
Firstly, thanks for all your work on vue-tsc!

When using union operator in defineEmits:

```vue
<script setup lang="ts">
defineEmits<{
	(e: "a" | "b"): string;
}>();

const count = 0;
</script>

<template>
	{{ count }}
</template>
```

vue-tsc is unable to find variables in the component template:
![vue-tsc-error](https://user-images.githubusercontent.com/36966635/152258787-57c65221-394c-4dcc-80c9-dbc536a54ebe.png)

You can find a repro at this repository: https://github.com/leonzalion/vue-tsc-bug

Let me know if you need any more information and/or if I'm missing anything

**Comment by xiaoxiangmoe** [comment]
Do not use union type, use this instead.

```vue
<script setup lang="ts">
defineEmits<{
	(e: "a"): void;
	(e: "b"): void;
}>();

const count = 0;
</script>

<template>
	{{ count }}
</template>

**Comment by leonzalion** [comment]
Yep, that's how I ended up fixing the issue (and I originally used a union because of the [@typescript-eslint/unified-signatures](https://typescript-eslint.io/rules/unified-signatures) lint, but disabling it shouldn't be hard)

However, the union type causing the type checking problem is still pretty unexpected (and it took me a while to debug), so I assume it's still a bug that needs to be fixed (or otherwise mentioned somewhere in the docs).

Thanks for providing a solution in any case!

**Comment by xiaoxiangmoe** [comment]
But i'm not sure if union type works on `defineEmits` in Vue 3

**Comment by yaegassy** [comment]
I took a look at the test code for difineEmits itself. There seems to be a test for the Union type.

- <https://github.com/vuejs/core/blob/main/packages/compiler-sfc/__tests__/compileScript.spec.ts#L957-L1061>
