### ISSUE TITLE
Variables not found if shadowing in `<script setup>`

### ISSUE THREAD

**Issue by equt** [johnsoncodehk/volar#927]
If a variable in the `setup` script happens to share the same name defined in the component's props, all `v-bind`s in the style block will report TS 2304, a.k.a., `cannot find variable name ...`.

```vue
<script setup lang="ts">
defineProps<{
  foo: string
}>()

const foo = "Foo" // Define `foo` here
const bar = "Bar"
</script>

<template>
  <!-- ... -->
</template>

<style scoped>
div {
  /* All following `v-bind`s will report error, even for the `bar`. */
  property-foo: v-bind("foo");
  property-bar: v-bind("bar");
}
</style>
```

PS, This also happens in the `<template>`.

**Comment by johnsoncodehk** [comment]
Hi @equt, I can't reproduce this problem, can you reproduce it in https://github.com/johnsoncodehk/volar-starter?

**Comment by equt** [comment]
It seems to be fine after a fresh installation of both the VS Code plugin & the deps. Close it for now.

PS, glad to see you back :)
