### ISSUE TITLE
Prop types not showing correctly in template when using different casing in template and defineProps?

### ISSUE THREAD

**Issue by zhekaiii** [johnsoncodehk/volar#929]
Not sure if it's just me, but I have this issue where if I define a prop with camelCase, and then I assign a value in the template of the parent component using kebab-case, hovering over the attribute will show the type of my input instead of the type of the actual prop. Using camelCase instead will show the correct typing on hover.

Child Component (tried using type declaration, runtime declaration and non script setup method with `defineComponent`)
![image](https://user-images.githubusercontent.com/40530851/152339443-0c3f7881-4fdd-4b26-b92d-35f74c5a0c82.png)

Parent Component:
![image](https://user-images.githubusercontent.com/40530851/152359977-2e16f70b-4bc5-4384-b188-07d18a35ea8e.png)
![image](https://user-images.githubusercontent.com/40530851/152360115-17d8814d-cf79-42dd-9d52-34eb69d0a700.png)
![image](https://user-images.githubusercontent.com/40530851/152360174-e2a9ee14-4b30-4ac4-afe0-2d28740b0a1e.png)

On v0.31.1

**Comment by Shinigami92** [comment]
`1 | 2 !== '1' | '2'`

**Comment by zhekaiii** [comment]
Sorry, I think you missed my point. Using camel-case, IntelliSense thinks `my-prop` has the type of whatever I put. Notice how when I put `my-prop="2"`, when I hover over `my-prop`, it says `string`. Similar to when I put `:my-prop=2`, it thought `my-prop` is a `number` where it should've been `1 | 2` instead. It's only when I used `myProp` when it correctly identifies it as `1 | 2`

**Comment by zhekaiii** [comment]
But even if I use kebab-case, even when I provide a value with an invalid type, the red wiggly lines correctly show up. Only when I hover over the attribute it shows the wrong type as shown in my screenshots.

**Comment by Shinigami92** [comment]
Oh you mean this 
![image](https://user-images.githubusercontent.com/7195563/152359560-cbb41949-e135-4464-93c2-6ce88b9f086a.png)
:eyes: 

You should mark this, it was not clear to me on first look, sry for noise

**Comment by zhekaiii** [comment]
My bad, will update my screenshots

**Comment by jacobprudhomme** [comment]
Similar to above, when I use `snake_case` for naming my props in the script section and `kebab-case` for using them in the template, it seems Volar is not able to make the link:

![Example1](https://user-images.githubusercontent.com/2160185/166961401-88a45f71-c2ed-4eab-a946-9fc3bd4b7976.png)
_Error when using `CreateFormFilter` component_

![Example2](https://user-images.githubusercontent.com/2160185/166961441-3ac0625f-a061-4f14-9054-e64612a951a5.png)
_Props defined on `CreateFormFilter` component_

If I change the props to `camelCase`, the error disappears. However, `snake_case` should also work, as Vue has support for it as per this [lint rule](https://eslint.vuejs.org/rules/prop-name-casing.html). Additionally, compiling with `vue-cli-service build` works, with no errors.

**Comment by johnsoncodehk** [comment]
@jacobprudhomme unfortunately `snake_case` is currently intentionally not supported, because it will makes type computation and codegen more complicate.

**Comment by johnsoncodehk** [comment]
Now we show both casing hover info.
<img width="493" alt="螢幕截圖 2022-10-18 04 55 21" src="https://user-images.githubusercontent.com/16279759/196281473-9d605856-a1cc-43a2-bceb-929384740158.png">

For go further use case you can setting `vueCompilerOptions.strictTemplates = true`, it only allow define prop as camelCase  so that avoid this problem.
<img width="422" alt="螢幕截圖 2022-10-18 04 59 12" src="https://user-images.githubusercontent.com/16279759/196282155-8fb46afc-da41-406a-8663-62b9325bb653.png">
