### ISSUE TITLE
Way to enforce PostCSS in .vue style section? 

### ISSUE THREAD

**Issue by Darkzarich** [johnsoncodehk/volar#931]
Right now to get the highlight for PostCSS it is required to set

```
<style lang="postcss">
```

Is there a way to enforce `postcss` parsing in `*.vue` style section?

**Comment by sethidden** [comment]
eslint-plugin-vue already has something like this: https://eslint.vuejs.org/rules/block-lang.html#vue-block-lang

For a template with set up ESLint with Vue, see https://github.com/sethidden/vue3-eslint-stylelint-demo

**Comment by johnsoncodehk** [comment]
We have tried to support this before, but we ended up dropping support it due to it's too many hacks. (#134)
