### ISSUE TITLE
Feature request: Add an option for vue-tsc to report unused slots and css statements

### ISSUE THREAD

**Issue by ilyub** [johnsoncodehk/volar#934]
Inside VSCode I see that Volar shows reference count for slots and css statements:
![image](https://user-images.githubusercontent.com/70687432/152398119-91287ae3-ebcb-4f88-a714-d871fcd447e1.png)

Is it possible to add an option for vue-tsc to report slots and css statements with zero references?

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, but unfortunately there is no proper way to implement this feature, and we cannot count references accurately.
