### ISSUE TITLE
error TS1005: ')' expected in multi-line expressions in template

### ISSUE THREAD

**Issue by halimb** [johnsoncodehk/volar#935]
While trying to convert an existing large vue (nuxt) project to typescript I'm having an error `error TS1005: ')' expected.` in multiline expressions in vue templates

Example:

```vue
<template>
  <img
    @click="
      myFunc()
      myVar = 42
    "
  />
</template>
```

![err](https://user-images.githubusercontent.com/20999471/152404350-b4c7f180-d1cd-4e0c-87d7-4efc61e43e6a.png)

Not sure if this is an expected behavior, but here's a minimal reproduction link:

https://github.com/halimb/nuxt-edge-ts

Any idea how to solve this?

Thanks

**Comment by equt** [comment]
See the doc [here](https://vuejs.org/guide/essentials/event-handling.html#listening-to-events),

> The handler value can be one of the following:
> - Inline handlers: Inline JavaScript to be executed when the event is triggered (similar to the native onclick attribute).
> - Method handlers: A property name or path that points to a method defined on the component.

The value is simply invalid, you should wrap it into a function.

**Comment by yaegassy** [comment]
@halimb How about adding a `;`?

```vue
<template>
  <img
    @click="
      myFunc();
      myVar = 42;
    "
  />
</template>

// ...snip
```

**Comment by halimb** [comment]
@yaegassy semi-columns worked :+1: 


> The value is simply invalid, you should wrap it into a function.
@equt it can be a multi-line expression, adding the semi-columns solved it
