### ISSUE TITLE
allow exporting types using `keyof typeof`

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#936]
In the past I have found it very useful to be able to export types using `keyof typeof someObject`. It had been working previously, but volar has just started complaining:

![image](https://user-images.githubusercontent.com/1158956/152440453-eb1e74ea-9d46-46bb-8c54-622428b2ddf2.png)

While in theory exporting types only at the top of the file makes sense, it means that you cannot create a type based on a const. Also, doing so works fine in a regular `*.ts` file.

Why would I want to do this? It allows you to have some arbitrarily complex configuration associated with some set of string keys, and then create a type that is only valid when using one of those keys, without having to define the list of possible values more than once.

For example, I can use it to create a list of possible icon names, with a mapping to specific Icons.
```typescript
import CheckIcon from '@/images/icons/CheckIcon.svg';
import CheckCircleIcon from '@/images/icons/CheckCircle.svg';
// ...

const POSSIBLE_ICONS = {
  check: CheckIcon,
 'check-circle': CheckCircleIcon,
  // ...
};

export type IconNames = keyof typeof POSSIBLE_ICONS;
```
there are many other cases where this can be useful as well...

Note - may be somewhat related to https://github.com/johnsoncodehk/volar/issues/923 which is just complaining about exporting additional types altogether.

**Comment by theoephraim** [comment]
More digging and I've found that moving these extra exports to an additional `<script>` block alongside the `<script setup>` block seems to do the trick.

I think this may be the intended behaviour, but the [vue docs](https://v3.vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script) are a bit lacking in specifics about TS, and the fact that it used to work but changed suddenly created the extra confusion.

**Comment by theoephraim** [comment]
One potential remaining issue is what to do if we need access to the const object in the template

```vue
<script lang="ts">
  // I need to define config here in order to export the type
  const CONFIG = {
    a: 'a',
    b: 'b',
  };

  export type ConfigKeys = keyof typeof CONFIG;
</script>

<script lang="ts" setup>
  // we do have access to CONFIG and ConfigKeys here!
  // how can I re-export CONFIG back to the template? other than some hacky renaming?
</script>

<template>
  <!-- We do not have access to CONFIG here :( -->
</template>
```

**Comment by theoephraim** [comment]
Closing this.
See related https://github.com/johnsoncodehk/volar/issues/940

Will open above question in vue/core

**Comment by johnsoncodehk** [comment]
> One potential remaining issue is what to do if we need access to the const object in the template
> 
> ```
> <script lang="ts">
>   // I need to define config here in order to export the type
>   const CONFIG = {
>     a: 'a',
>     b: 'b',
>   };
> 
>   export type ConfigKeys = keyof typeof CONFIG;
> </script>
> 
> <script lang="ts" setup>
>   // we do have access to CONFIG and ConfigKeys here!
>   // how can I re-export CONFIG back to the template? other than some hacky renaming?
> </script>
> 
> <template>
>   
> </template>
> ```

This is actually working for me, but I don't that is not working in previous vue version. Have you tried update to latest vue version?

**Comment by jaulz** [comment]
@johnsoncodehk regarding your question, I just tried with `v0.33.10` and with `v0.33.13` and this does not work:
```vue
<script lang="ts">
import { defineComponent } from 'vue'

export type CustomType = {}

export default defineComponent({ ... })
</script>

<template>
  <!-- type CustomType = /*unresolved*/ any -->
  <!-- Cannot find name 'CustomType'.ts(2304) -->
</template>
```
