### ISSUE TITLE
Fold comments command does not work in VSCode with Volar, but works with Vetur

### ISSUE THREAD

**Issue by ilyub** [johnsoncodehk/volar#937]
I mean this command:
![image](https://user-images.githubusercontent.com/70687432/152503478-ff7c28aa-6f5f-4d49-a27c-85b7a6691f9c.png)

After I replaced Vetur with Volar it stopped working.

**Comment by johnsoncodehk** [comment]
Hi @ilyub, I can't reproduce this problem, it's working for me, please provide minimal reproduction code if you can.

**Comment by ilyub** [comment]
Hi @johnsoncodehk, thx for the response.

Here is a sample vue file that does not fold comments on Ctrl+K + Ctrl+/:
```vue
<script lang="ts">
/**
 * Description.
 */
export function withComment(): void {
  /*
   * Function body
   */
}

export default {
  name: "sample-component"
};
</script>

<template>
  <div></div>
</template>
```
![image](https://user-images.githubusercontent.com/70687432/156323430-f7127650-be00-44b9-9357-4d12c426556d.png)

Here is a sample ts file that folds comments on Ctrl+K + Ctrl+/:
/**
 * Description.
 */
export function withComment(): void {
  /*
   * Function body
   */
}
![image](https://user-images.githubusercontent.com/70687432/156323542-4d6fcc6f-6e5d-4f35-807f-d87b4d28534a.png)

This is what Ctrl+K + Ctrl+/ should do:
![image](https://user-images.githubusercontent.com/70687432/156324387-e399b625-c1f5-49f0-9908-0af17763f916.png)

Please, let me know if any aditional info is needed.
