### ISSUE TITLE
FR: Make Outline view work with script setup too

### ISSUE THREAD

**Issue by hinogi** [johnsoncodehk/volar#938]
Currently `script` and `style` are not supported in the outline view when you use script setup, would be nice to add it.

**Comment by Shinigami92** [comment]
![image](https://user-images.githubusercontent.com/7195563/152523911-34873c05-41f7-402c-90a4-274ff3399b1d.png)

Can reproduce it and I'm now also interested in this

VSCode has a nice new update so we can now show a Side Panel on the side
and now I'm using that for Outline View
