### ISSUE TITLE
Improvement request: Auto-complete for boolean props should omit =""

### ISSUE THREAD

**Issue by ilyub** [johnsoncodehk/volar#939]
For example, quasar QBtn has boolean prop "loading":
https://quasar.dev/vue-components/button

When Volar autocompletion inserts it, it should insert:
```vue
<q-btn loading />
```
instead of 
```vue
<q-btn loading="" />
```

It can also insert:
```vue
<q-btn :loading="" />
```

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion! But it required doing prop type-checking when insert completion, so it will has perf problem.

**Comment by so1ve** [comment]
hi @johnsoncodehk. is there an option to?disable this behavior?
