### ISSUE TITLE
Show more helpful error when trying to export from script setup

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#940]
According to the vue docs, additional named exports SFCs using script setup should be placed in a separate script block alongside setup one. From the latest changes to vue, I believe this applies to type exports as well, and I have updated to the vue docs accordingly.

However volar's handling and errors are not in sync with this.

- When exporting a const, we currently get a TS error (and a linting error if you have that set up).
![image](https://user-images.githubusercontent.com/1158956/152608001-a92cf709-51e8-4f9a-9ca7-c5ad77c75987.png)

- When exporting a type at the top of the file, we get no error, but vue-tsc will complain.

- When exporting a type later in the file, we get the same TS error, plus a special warning from volar that it should be moved to the top of the file.
![image](https://user-images.githubusercontent.com/1158956/152608229-40524677-15f8-4d2e-ae5a-44e5e670c59b.png)

Instead volar should give more helpful errors, warning the user if creating _any_ additional named exports (types or not) within the script setup block, and specifically telling the user to move the export to an additional script block. Might even be able to provide a VSCode "quick fix" which moves it for you?

**Comment by johnsoncodehk** [comment]
For me I think the message is enough, but if you have an idea to improve the message PR is very welcome: https://github.com/johnsoncodehk/volar/blob/4e20cfbb354671c4621d5bebeded2cbd3b430703/vue-language-tools/vue-language-service/src/plugins/vue.ts#L156
