### ISSUE TITLE
Take a break

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#941]
I've had some problems in my life recently, I may not be able to pay attention to this repo. I hope I can resolved my problem at soon and come back here in March. I promise I would not give up this repo. If you could sponsoring me without pressure I would be very grateful for that.

I'm really sorry about that. 🙏

**Comment by Shinigami92** [comment]
https://twitter.com/Shini_92/status/1490288557726052352

**Comment by johnsoncodehk** [comment]
@Shinigami92 Thank you. 🙏

**Comment by patak-dev** [comment]
https://twitter.com/patak_dev/status/1490374970870018056

Thanks for your amazing work @johnsoncodehk, take as much time as you need

**Comment by johnsoncodehk** [comment]
@patak-dev Thank you. 🙏 I have no idea that the vue community was so loving. I will make improve vue DX to the extreme as my main goal!

**Comment by soulsam480** [comment]
Totally fine to take your time. Come back stronger. Also due to some issues github sponsorships are not working in my country rn and all of my previous sponsorships were cancelled automatically. Will try to fix that and resume it. Thanks for your invaluable contribution 😊💚

**Comment by johnsoncodehk** [comment]
@soulsam480 Don't mind, I'm already very grateful, thank you. 🙏

**Comment by RedBlueKoi** [comment]
Hey mate! Wish you all the best. Huge thanks for an awesome tool! Wanted to subscribe for a long time and this is a great reason =)

**Comment by victorgarciaesgi** [comment]
Take care @johnsoncodehk and all Vue users are really thankfull of the awesome tool you built. I'm still amazed by the quality of it💚💚

**Comment by theoephraim** [comment]
Thank you so much for all your hard work on this tool. It is a huge part of what makes using the new vue stuff so exciting :)
Take care of yourself!!

**Comment by JessicaSachs** [comment]
Another signal boost https://twitter.com/_jessicasachs/status/1490404586405965831?s=21

@johnsoncodehk Cypress would not have switched to Vue if not for your amazing work. Take the time you need. Sending love and support.

**Comment by sethidden** [comment]
https://youtu.be/KsIN33ANybM?t=1571

Johnson is a beast 💪

**Comment by ddahan** [comment]
Was already sponsoring...just triggered a one-time payment to help. Take care.
What I give back versus what I earn thanks to your work is not comparable... Thanks again.

**Comment by tangjinzhou** [comment]
sponsoring

**Comment by sodatea** [comment]
https://twitter.com/haoqunjiang/status/1490523806515208196
Thank you for all the great help. Take care 🙏

**Comment by shawn-yee** [comment]
Thank you for your hard work.
 I wish you good health and happy every day.

**Comment by WhiteCoffee9834** [comment]
Thank you !
Good luck !

**Comment by sullyD64** [comment]
Thank you for Volar, @johnsoncodehk! Truly a vital part of the Vue ecosystem. Take your time and see you soon <3

**Comment by johnsoncodehk** [comment]
Thanks for all the sharing, thanks for all the encouragement, thanks for all the help, I'm really wordless gratitude. 🙏🙏🙏

I feeling everything is going to get better, will see you soon.

**Comment by douglasg14b** [comment]
Do what you need to do!

If the repo has maintainers who you trust to review & merge PRs then you're already in a great place to take care of yourself.

**Comment by johnsoncodehk** [comment]
I'm trying to create some extra charge features to increase income to help myself (https://twitter.com/johnsoncodehk/status/1496978502385422336). If you've sponsored me in the past, you can access these features as an early sponsor (I'm really appreciate you guys 🙏). If you're a new sponsor, now we have a new sponsor tier to access extra features.

But anyway, obviously the world has more important things to focus on now, take care yourself, protect those around you. 💪

**Comment by soulsam480** [comment]
> Totally fine to take your time. Come back stronger. Also due to some issues github sponsorships are not working in my country rn and all of my previous sponsorships were cancelled automatically. Will try to fix that and resume it. Thanks for your invaluable contribution blushgreen_heart

Restored sponsorship today. :green_heart:
