### ISSUE TITLE
Cannot find namespace 'form' ... etc

### ISSUE THREAD

**Issue by productfrontenddeveloper** [johnsoncodehk/volar#95]
Under error is the code directory I am using. No error.
![Screen Shot 2021-03-14 at 14 27 40](https://user-images.githubusercontent.com/38668796/111066703-7ae82e80-84d1-11eb-8979-0018414873d0.png)

![Screen Shot 2021-03-14 at 14 28 42](https://user-images.githubusercontent.com/38668796/111066727-98b59380-84d1-11eb-96e9-405fcd0cfd78.png)

label in component used. but it makes such mistakes. Not all but some.
![Screen Shot 2021-03-14 at 14 29 58](https://user-images.githubusercontent.com/38668796/111066762-c3075100-84d1-11eb-90ab-ab43b6d7cde6.png)

**Comment by johnsoncodehk** [comment]
Duplicate: https://github.com/johnsoncodehk/volar/issues/93
