### ISSUE TITLE
Not working in win10 WSL2

### ISSUE THREAD

**Issue by xiangqunXiao** [johnsoncodehk/volar#950]
# Environment
- OS: win10 wsl2 Ubuntu  (it's normal in local win10)
- Typescript: 4.5.2
- Vue 3.x

# Error Message
hover red underline with `Cannot find name 'xxx' .ts(2304)`

![image](https://user-images.githubusercontent.com/95326074/153368564-f966be66-fe16-493c-a07c-cc6ab44049ff.png)

**Comment by johnsoncodehk** [comment]
Hi @xiangqunXiao, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?
