### ISSUE TITLE
cannot correctly infer type for $slots of global components

### ISSUE THREAD

**Issue by aimergenge** [johnsoncodehk/volar#953]
reproduce repo:  https://github.com/aimergenge/volar-slots-reproduce

run `pnpm lint`, get:
```
src/components/CompB.vue:3:26 - error TS7022: 'name' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

3     <template v-for="(_, name) in $slots"
                           ~~~~

src/components/CompB.vue:5:14 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ one: {}; two: {}; } & ({} | {})'.

5       v-slot:[name]="slotData"
               ~~~~~~

Found 2 errors.
```

But CompA doesn't have same problem
The difference between CompA and CompB is that CompA is used locally while CompB is used globally via a `global-components.d.ts`

I also note #701 , but add `($slots as Pick<typeof $slots, 'one' | 'two'>)` doesn't have any effect

**Comment by Shinigami92** [comment]
Also affected by this

**Comment by johnsoncodehk** [comment]
This is expected behavior, `$slots` type is from `DefineComponent` but not define by volar. You can not inherit parent slots type by this way. If you need type-safe it, you must be hardcode each slot currently.

```vue
<template>
  <comp-c>
    <template #one="slotData">
      <slot name="one" v-bind="slotData"></slot>
    </template>
    <template #two="slotData">
      <slot name="two" v-bind="slotData"></slot>
    </template>
  </comp-c>
</template>
```

**Comment by yusufkandemir** [comment]
@johnsoncodehk 
```html
<template>
  <q-table :rows="rows">
    <template
      v-for="(_, slot) in ($slots as Readonly<QTableSlots>)"
      #[slot]="scope"
    >
      <slot :name="slot" v-bind="scope || {}" />
    </template>
  </q-table>
</template>

<script lang="ts" setup>
import type { QTableProps, QTableSlots } from 'quasar';

interface Props extends QTableProps {
  rows: { test: string }[];
}

defineProps<Props>();
</script>
```

```html
```

**Comment by johnsoncodehk** [comment]
@yusufkandemir Unfortunately based on the behavior of TypeScript this is not possible and you may have to annotate the exported component type. (You can reference https://twitter.com/johnsoncodehk/status/1579151876662390784)
