### ISSUE TITLE
Incorrect globalProperties types on the template

### ISSUE THREAD

**Issue by pikax** [johnsoncodehk/volar#954]
[GlobalProperties aka ComponentCustomProperties ](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties) are not property shallowUnref on the template type.

```tsx
import { Ref } from "vue";

declare module "vue" {
  interface ComponentCustomProperties {
    $myVar: Ref<number>;
  }
}

// Comp.vue
<template>
  {{ $myVar /* type: Ref<number>; Prints: number*/}}
</template>
```

Found on https://github.com/vuejs/core/pull/5389

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/pull/955#issuecomment-1037887026.

**Comment by xiaoxiangmoe** [comment]
Maybe you can just write
```ts
declare module "vue" {
  interface ComponentCustomProperties {
    $myVar: UnwrapRef<Ref<number>>;
  }
}
```
