### ISSUE TITLE
No Error or warning, but highlighted unrecognized component

### ISSUE THREAD

**Issue by ehajri** [johnsoncodehk/volar#958]
System:
```
VS Code v1.64.2
Volar Extension v0.31.2
```

My custom component (Drawer) is shown in red as follows:
![image](https://user-images.githubusercontent.com/1648916/153716006-ac0388fb-7026-4ca9-a865-655fd5346bc5.png)

When I tried your volar-starter repo, I am getting the same behavior (With HelloWorld component):
![image](https://user-images.githubusercontent.com/1648916/153716120-c8784801-e5fe-4305-8128-1895a336f0b6.png)

Do you know what is the problem?

**Comment by johnsoncodehk** [comment]
Could you show the code of the Drawer component?

> When I tried your volar-starter repo, I am getting the same behavior (With HelloWorld component):

Please make sure you have install node_modules after clone the repo.

**Comment by ehajri** [comment]
Thanks, I totally forgot to do npm install on volar-starter.

After comparing the two projects, the following caused the component to be labeled in red:
`"useDefineForClassFields": false,`
in `tsconfig.json`.
