### ISSUE TITLE
Why the server can't work on a new created file

### ISSUE THREAD

**Issue by jadestrong** [johnsoncodehk/volar#960]
I use emacs lsp-mode and `@volar/server`, when create a new file, the server doesn't work on it. I need to restart the LSP server manually.
After some debug, I found it because of the following line of code:
https://github.com/johnsoncodehk/volar/blob/573dad2efb6faa5fcb68e147498f1a2e58f65b3e/packages/vscode-typescript-languageservice/src/index.ts#L83
The typescript language service can't get the source file of the new file.
I also tried `neovim/nvim-lspconfig` and `sublime` ,  from the results of my test, they also have this problem. But vscode works fine.

**Comment by johnsoncodehk** [comment]
It seems related to https://github.com/yaegassy/coc-volar/issues/81

**Comment by jadestrong** [comment]
It seems so. I'll try it. Thanks.

**Comment by jadestrong** [comment]
After adding file watcher, it can work normally on new files! Thank you very much for your work.
