### ISSUE TITLE
default split editors view

### ISSUE THREAD

**Issue by AlexKougianos** [johnsoncodehk/volar#961]
Is there a way to enable split editors view as default for all vue files?

**Comment by johnsoncodehk** [comment]
Yes this is possible, but I think it's counterintuitive. 😅

**Comment by ruihildt** [comment]
@johnsoncodehk Would you consider to add it as a pref?

I understand having as default would be counter-intuitive, but if I want to use it, I have to click the icon every time, which is cumbersome.

**Comment by OhaiHFO** [comment]
> yes, dear user
> 
> the original feature was added as it was thought that users may find being able to split code into multiple panes useful for their workflow
>
> oh? you want to have an optional setting to have this extremely useful feature enabled by default?
> 
> it sounds like your wish is to always have single file components open in split view, to prevent you from having to click the button "every single time" you open that file...
> 
> no, that sounds counter intuitive
>
> i think we'll just keep this useful feature that improves your workflow the way it is, and then detract from that positive workflow benefit by making you click that button every time
>
> because providing an option that actually makes this a useful feature that can be used all the time sounds "counter-intuitive"

Volar is a great plugin, and i'm sorry for the sarcastic delivery of the above - but i really wanted to illustrate just how silly the above situation is

That was nearly half a year ago, and we've really not seen the benefit of this?

c'mon, i know we're all intelligent here, what's the issue?

**Comment by johnsoncodehk** [comment]
@OhaiHFO Unfortunately VSCode doesn't provide an API to query editor group status, so there's no way to do that.

You can consider make a keybinding for it.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/16279759/187058979-5be3d711-0a6e-47ad-8515-58a52de27c30.png">
