### ISSUE TITLE
Error: volar/getAttrNameCaseClient

### ISSUE THREAD

**Issue by ddmoyu** [johnsoncodehk/volar#962]
vscode 自动升级 volar 到0.31.4 之后不停的弹窗报错
降级到 0.31.3 之后正常
![image](https://user-images.githubusercontent.com/97585153/153796547-1cd0993b-d06f-4b30-b451-d81228cc68fd.png)

**Comment by Shana-AE** [comment]
same here, seems like [this line](https://github.com/johnsoncodehk/volar/commit/19da69b350ede741898f508382dbb18d6002b445#diff-f442b5be99bbbf289179e14078a8f79c97f2c82fef9b52dee3d1bbc1a39d6a48R4) 

```ts
import type * as ts from 'typescript/lib/tsserverlibrary';
```

imported ts as type but used as a variable at [this line](https://github.com/johnsoncodehk/volar/commit/19da69b350ede741898f508382dbb18d6002b445#diff-f442b5be99bbbf289179e14078a8f79c97f2c82fef9b52dee3d1bbc1a39d6a48R15)

```ts
const exportMapCache = (ts as any).createCacheableExportInfoMap({
```

**Comment by johnsoncodehk** [comment]
@Shana-AE `ts` is also a variable pass here https://github.com/johnsoncodehk/volar/commit/19da69b350ede741898f508382dbb18d6002b445#diff-f442b5be99bbbf289179e14078a8f79c97f2c82fef9b52dee3d1bbc1a39d6a48R9.

Maybe `createCacheableExportInfoMap` do not exist on your TS version, could you try update vscode / typescript version to latest (Just for confirm the problem)?

**Comment by yaegassy** [comment]
I've checked it in my environment, and it seems to output an error if typescript v4.4 or higher is not used.

**Comment by Shana-AE** [comment]
> @Shana-AE `ts` is also a variable pass here [19da69b#diff-f442b5be99bbbf289179e14078a8f79c97f2c82fef9b52dee3d1bbc1a39d6a48R9](https://github.com/johnsoncodehk/volar/commit/19da69b350ede741898f508382dbb18d6002b445#diff-f442b5be99bbbf289179e14078a8f79c97f2c82fef9b52dee3d1bbc1a39d6a48R9).
> 
> Maybe `createCacheableExportInfoMap` do not exist on your TS version, could you try update vscode / typescript version to latest (Just for confirm the problem)?

Thank you for your replay! I've tried updating typescript, now version is 4.5.5, after reload window(not just Volar: Select typescript version or Restart Vue server), it works. my previous TS version is 4.3.4

**Comment by Shana-AE** [comment]
Just for curiosity, why is it possible using `import type` to import a module and use its member?  I only found it would be removed later in TS document, [importing types](https://www.typescriptlang.org/docs/handbook/modules.html#importing-types).
Thank you!
