### ISSUE TITLE
`defineprops` cannot infer the base type defined by `Proptype` in Vue2

### ISSUE THREAD

**Issue by starmooms** [johnsoncodehk/volar#965]
`defineProps` cannot infer the base type defined by `PropType` in Vue2

[can view the demo reference](https://github.com/starmooms/vue2-volar-demo/tree/master)

### The vscode
![5B6B812E-75E0-4a3e-A782-E33ACA0F8F10](https://user-images.githubusercontent.com/30034746/154215101-af77ace0-0e14-4f8c-8755-a43f4a95276b.png)

### run `vue-tsc --noEmit`
```
src/App.vue:5:8 - error TS2322: Type 'number' is not assignable to type '{ type: PropType<BaseProp>; required: true; }'.

5       :base-prop="baseProp"
         ~~~~~~~~~

Found 1 error.
```

I'm not sure if this is related to the `PropType` I use from `@vue/runtime-core` , [see the unplugin-vue2-script-setup issues](https://github.com/antfu/unplugin-vue2-script-setup/issues/17)

**Comment by johnsoncodehk** [comment]
Hi @starmooms, you should use `{ PropType } from '@vue/composition-api'` instead of `{ PropType } from '@vue/runtime-core'` in vue 2.

**Comment by starmooms** [comment]
@johnsoncodehk Thanks for your reply
If use the `Proptype` of `@vue/composition-api`，the `props` inference in `script setup` is wrong
Any other suggestions
![5B6B812E-75E0-4a3e-A782-E33ACA0F8F10](https://user-images.githubusercontent.com/30034746/156280979-85cb8314-6778-44b3-a523-778b64b8daef.png)

**Comment by johnsoncodehk** [comment]
Do you have setup tsconfig? See https://github.com/antfu/unplugin-vue2-script-setup#support-vue-2-template.

**Comment by johnsoncodehk** [comment]
Okay I found it, you should import `'@vue/runtime-dom'` instead off `'@vue/runtime-core'`. :)

**Comment by johnsoncodehk** [comment]
After survey the types, I think defineProps can't totally working PropType. You could use type only definition as replacement.

```ts
const props = defineProps<{
  baseProp: BaseProp
}>();
```
