### ISSUE TITLE
Plugin Split Button not working correctly 

### ISSUE THREAD

**Issue by heipi2001** [johnsoncodehk/volar#966]
I can't use it Split Button.

Click the button to appear "command 'volar.action.splitEditors' not found".

Vscode version: 1.60.0
Node.js version: 14.16.0

![image](https://user-images.githubusercontent.com/52134529/154391511-5de27360-9549-4160-bd72-2fa6d7202e3e.png)

**Comment by yaegassy** [comment]
Please update your version of Visiaul Studio Code. The current split editor feature does not work on older Visiaul Studio Code

**Comment by johnsoncodehk** [comment]
Duplicate of #642
