### ISSUE TITLE
How to close "refrence" prompt in volar

### ISSUE THREAD

**Issue by yeahliv** [johnsoncodehk/volar#968]
![Snipaste_2022-02-17_19-44-01](https://user-images.githubusercontent.com/34160612/154476053-95859d35-00eb-4082-9c4b-a7e71e1719bc.png)

**Comment by yaegassy** [comment]
Disable the `Volar > Code Lens: References` setting. It is enabled by default.

<img width="674" alt="vscode-volar-issue968-1" src="https://user-images.githubusercontent.com/188642/154587594-ebb9fd69-1929-44f6-a9f6-e12b24af186d.png">

Or, if you want to edit `.vscode/settings.json` directly, write the following

```
{
    "volar.codeLens.references": false
}
```
