### ISSUE TITLE
🐛 [BUG]: Outline show wrong nesting in pug

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [johnsoncodehk/volar#969]
The generated oultine does not follow the source
![image](https://user-images.githubusercontent.com/86342787/154476046-6003deac-1dc4-4d59-908c-c84350cdf7c2.png)
![image](https://user-images.githubusercontent.com/86342787/154476110-1ef091a0-34b9-4745-b81f-0bf4f4f8ccf2.png)

**Comment by hinogi** [comment]
there is also a .. before content

**Comment by hinogi** [comment]
Will all those seemingly minimal changes, if feels a bit like magic what you do @johnsoncodehk
