### ISSUE TITLE
Is this meant to replace vetur?

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#97]
Since the README says:
> You need to disable Vetur to avoid conflicts.

I wonder, is this project meant to replace Vetur?

Does it include other benefits vetur offers like
- syntax highlighting for vue files
- auto formatting `lang="sass"` css for style blocks
- auto formatting for script and template via prettier

?

**Comment by cereschen** [comment]
At least I can assure you that it won't modify or delete your files, so why not give it a try

**Comment by mesqueeb** [comment]
@cereschen how to disable Vetur?

**Comment by cereschen** [comment]
> @cereschen how to disable Vetur?
In your vscode extensions panel

**Comment by johnsoncodehk** [comment]
Yes you can take a try... and my opinion is if you have no idea, just keep using Vetur.
