### ISSUE TITLE
Shouldn't the CSS property `width` come above `widows` in IntelliSense?

### ISSUE THREAD

**Issue by mirumirumi** [johnsoncodehk/volar#971]
When I'm writing CSS in a Vue file, I want to type `width` but IntelliSense always suggests `widows` first.

![3](https://user-images.githubusercontent.com/88871226/154795414-4845b187-03f7-4ae9-ba65-53325327ac80.png)

I thought this problem might be specific to Volar, because in other files (such as `.html`, `.css` and `.scss`), `width` is always at the top. 
I'm really sorry if I'm wrong.

![1](https://user-images.githubusercontent.com/88871226/154795325-46eb53f6-69f3-41b7-866c-813d0fb8094b.png)
![2](https://user-images.githubusercontent.com/88871226/154795329-4248a7f5-014a-4763-8d0f-3aeda3fd6e68.png)

(This happens equally in `<template>` and `<style>` files as long as they are in `.vue` files.)

### My environment

- VS Code: 1.64.2
- Volar: 0.31.4
- Windows 11 (no WSL)
- Other extensions that may be relevant
  - HTML CSS Support
  - HTML Snippets
- no Prettier 
- It doesn't mean that the `width` has already been entered.

Thank you!

**Comment by yaegassy** [comment]
@mirumirumi 

`widows: ;` is a suggestion by the `emmet` feature, not a css property suggestion.  It is possible to control the sort order by changing `emmet-related` settings.

Add the following settings to `.vscode/settings.json` and give it a try.

```jsonc
{
  "emmet.showSuggestionsAsSnippets": true,
  "editor.snippetSuggestions": "bottom"
}
```

**Comment by mirumirumi** [comment]
@yaegassy 

I see, it was a function of Emmet, wasn't it?

Thanks for your help!
Please feel free to close this issue.

**Comment by mirumirumi** [comment]
I did it !
