### ISSUE TITLE
[Take Over mode] Function Implementation Syntax Highlight is broken

### ISSUE THREAD

**Issue by zardoy** [johnsoncodehk/volar#973]
Hold ctrl while hovering on function:
<img width="619" alt="Screenshot 2022-02-21 at 20 07 05" src="https://user-images.githubusercontent.com/46503702/155000209-c165dee0-4848-4068-bbd1-ff6f58fae7aa.png">

As you can see codefence is missing.

**Comment by johnsoncodehk** [comment]
Seems fixed in vscode too, but not sure which commit for it: https://github.com/microsoft/vscode/commits/main/extensions/typescript-basics

**Comment by zardoy** [comment]
Sorry for some delay with response, it just wasn't a big issue for me, but now it became annoying again. I just tested it with latest insiders (1.66.0-insider) and I can see that nothing is changed.

Here is exact steps to reproduce:

1. `pnpm create vite` -> `vite-ts` preset.
2. Optionally `pnpm i`
3. Open `src\components\HelloWorld.vue` with **Take Over Mode Enabled**
4. Call definition hover (hover mouse with ctrl) on `count` (line 6) or `msg` (line 10). Actual result:

![image](https://user-images.githubusercontent.com/46503702/158038213-3610e88c-0456-4767-905e-8c2817a96ce3.png)

Expected: TS highliting.

This affects only `.vue` files.

Since we can return only range of document from definition provider, as I can understand vue language id is being used to highlight this. This is actually might be upstream issue. I think we need a way from vscode API to override language id from that provider.

**Comment by johnsoncodehk** [comment]
I agree this is vscode issue, in hover box it just equivalence to this.

<img width="219" alt="螢幕截圖 2022-04-20 07 12 45" src="https://user-images.githubusercontent.com/16279759/164116131-aaaec4d4-9620-431f-8e49-b02c85a3a49b.png">

But vscode should know `const count = ref(0)` is include in `<script>` tag and volar has define it to typescript/javascript embedded language.

https://github.com/johnsoncodehk/volar/blob/615eb158d5f99c56843bb1ee6859b5658151ed79/extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json#L541
https://github.com/johnsoncodehk/volar/blob/615eb158d5f99c56843bb1ee6859b5658151ed79/extensions/vscode-vue-language-features/package.json#L181

<img width="427" alt="螢幕截圖 2022-04-20 07 15 27" src="https://user-images.githubusercontent.com/16279759/164116327-23d4425e-fa8b-4de9-92b8-560a08f03b6c.png">
