### ISSUE TITLE
[Take Over mode] Not inserting `*` on enter in JSDoc

### ISSUE THREAD

**Issue by zardoy** [johnsoncodehk/volar#974]
```ts
/**
 * |
 */
let interval: number
```
TS: Pressing enter in `|` position inserts asterisk in new line.
This is not a case when take over mode is enabled.

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

> If the implementation is independent, is it possible to expect some extra features that we have been waiting for years, such as correct sorting of suggestions or disabling import suggestions from specific library?

We need to be consistent with VSCode, so their designed behavior is verified by more users, and changing it in volar might be counterproductive.

> EDIT: Just got some thoughts from #471. However "hacking" into ext and ext reload after each update (that occurs once a month) wasn't so bad solution IMO.

Svelte is also looking a way to avoid it, I think we will not go back. 😅
https://github.com/sveltejs/language-tools/issues/1358

**Comment by zardoy** [comment]
Can't repro anymore, everything works perfectly. Have no idea why it didn't work before.

**Comment by johnsoncodehk** [comment]
I think it was changed in https://github.com/microsoft/vscode/issues/125748.
