### ISSUE TITLE
Template syntax highlighting broken for custom components

### ISSUE THREAD

**Issue by andrewcourtice** [johnsoncodehk/volar#975]
Hi there

A recent change appears to have introduced a bug where the syntax highlighting of custom components in templates is incorrect. The change seems to have occurred around version **0.30.4**. I suspect this PR is the culprit: #801.

**Before:**
<img width="1006" alt="Screen Shot 2022-02-22 at 10 43 25 am" src="https://user-images.githubusercontent.com/11718453/155043329-b817030b-fb53-4bf9-b9a8-2675f740081b.png">

**After:**
<img width="1023" alt="Screen Shot 2022-02-22 at 10 40 40 am" src="https://user-images.githubusercontent.com/11718453/155043357-fde69b47-194e-4325-82e7-d7e7471a021e.png">

Thanks

**Comment by johnsoncodehk** [comment]
I think the opposite is the case, the new version of highlight is correct, it is distinguishing the color of the component from the html element.

<img width="409" alt="螢幕截圖 2022-03-01 21 35 51" src="https://user-images.githubusercontent.com/16279759/156178796-9deff01e-2fb1-4d52-896b-7369e2c8e171.png">

It should be occur in https://github.com/johnsoncodehk/volar/commit/67b596375da12f768b5c75994ecaa41a293f41c1
