### ISSUE TITLE
Should prefer component custom events 

### ISSUE THREAD

**Issue by lsdsjy** [johnsoncodehk/volar#977]
```vue
<script lang="ts">
declare const Bar: new () => {
  $props: {};
  $emit: {
    (event: "click", e: number): void;
  };
};
</script>
<script setup lang="ts">
import { ref } from '@vue/composition-api';
const v = ref(1);
</script>
<template>
  <div id="app">
    <Bar @click="v = $event" />
  </div>
</template>
```

Volar gives the following error:
`Type 'MouseEvent' is not assignable to type 'number'`

I think maybe it can be solved by changing the order of code generation in https://github.com/johnsoncodehk/volar/blob/01e0edd906f3bb9ac43700c95a729e08bb820843/packages/vue-code-gen/src/generators/template.ts#L707-L725

**Comment by johnsoncodehk** [comment]
We can't priority extract event type by `$emit`. For `defineComponent({ props: { onFooBar: Function as PropType<(num: number) => void> } })`, `$emit` type is `(event: string, ...args: any[]) => void`, it will completely cover props events.

**Comment by lsdsjy** [comment]
Can we use different logic for the `defineComponent` form and the `new () => { $emit: ... }` form? Maybe we can prefer prop events for the former and $emit for the latter.

**Comment by johnsoncodehk** [comment]
@lsdsjy it will depends with `DefineComponent` and make type extract logic more complex, I think it's not worth to do.

You could consider open a issue to vue/core repo for discuss if we could replace `$emit` type as `{}` instead of `(event: string, ...args: any[]) => void` if user do not provide emits option.
