### ISSUE TITLE
Renaming vue file where only casing changes breaks volar

### ISSUE THREAD

**Issue by olemarius** [johnsoncodehk/volar#979]
1. Createa a component Test.Vue
2. import { something} from '@/my/thing';
3. Rename component from Test.Vue to Test.vue
4 now @ alias wont work and we get error about module not resolved. 

Not sure what's going on here, but I suspect something's cached so Volar still thinks the extension is .Vue and ignores it because of case sensitivity?

**Comment by johnsoncodehk** [comment]
If the component file name end with `.Vue` volar just ignore it, you can only get diagnosis with `Test.vue`.
I think you may missing `"paths": { "@/*": ["./src/*"] }` in tsconfig.
