### ISSUE TITLE
code hint requires a script setup block: even if an emply block will work, but the block cannot be omitted

### ISSUE THREAD

**Issue by Shigma** [johnsoncodehk/volar#98]
![image](https://user-images.githubusercontent.com/33423008/111123513-61ff7c00-85aa-11eb-9b87-e0332dcda591.png)

![image](https://user-images.githubusercontent.com/33423008/111123544-6c217a80-85aa-11eb-9a61-a07f515a043d.png)

**Comment by johnsoncodehk** [comment]
Fixed in 0.22.13, thanks for the report!
