### ISSUE TITLE
Code color changes after a few seconds

### ISSUE THREAD

**Issue by xinnianyoulin** [johnsoncodehk/volar#980]
version **0.31.4**

Opening a vue file for the first time: 

![image](https://user-images.githubusercontent.com/32128165/155478652-5ec3362b-def1-4fa4-ac2a-dfe9dbeccf25.png)

After a while: 

![image](https://user-images.githubusercontent.com/32128165/155478755-2a796674-0df3-4676-b482-762be27c76aa.png)

Some codes have changed color.

**Comment by johnsoncodehk** [comment]
This is expected behavior, when you first time open a vue document you will got syntax highlighting, after language server startup, volar provide semantic highlighting by LSP, it is more precise highlighting.

**Comment by johnsoncodehk** [comment]
Some extensions disabled semantic highlighting, volar add config to enable it by default https://github.com/johnsoncodehk/volar/issues/975#issuecomment-1055450560
