### ISSUE TITLE
The "vue-ts" command causes the server CPU100%

### ISSUE THREAD

**Issue by chengzixian** [johnsoncodehk/volar#982]
At present, I use Jenkins to compile and deploy the project on the server, but every time I execute the "vue-tsc --noEmit --skipLibCheck" command, it will lead to CPU overload and server downtime. I want to ask if there is any way to limit the CPU used by this command. I can accept the slow compilation, but I can't accept the downtime;
cpu-info
![cpu-info](https://user-images.githubusercontent.com/23517357/155657936-b520aae4-90e0-4b80-805c-a34f6cbff6f9.png)
ram-info
![ram-info](https://user-images.githubusercontent.com/23517357/155658178-36ddc654-4fbd-468a-ab6d-c2dc2ac84ab9.png)
ordinary
![ordinary](https://user-images.githubusercontent.com/23517357/155658191-cba0fe1c-21c5-4b6f-be95-50089819b993.png)
Compiling
![Compiling](https://user-images.githubusercontent.com/23517357/155658243-5830c343-3270-427c-86de-e4a529d9f3ae.png)

**Comment by chengzixian** [comment]
![WX20220225-131934](https://user-images.githubusercontent.com/23517357/155658468-06a2d97c-3ddc-441b-a19d-e53d261f493f.png)

**Comment by johnsoncodehk** [comment]
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

If it can't, could you provide repro case? Otherwise I can't survey it.

**Comment by johnsoncodehk** [comment]
If your project is larger 1GB memory may not enough, you could track #1108.
