### ISSUE TITLE
Space is removed after '</router-link>'

### ISSUE THREAD

**Issue by mariusa** [johnsoncodehk/volar#983]
On save, this
```
<div>
Please <router-link to="/support">let us know</router-link> any questions.
</div>
```

is changed to
```
        <div>
            Please
            <router-link to="/support">let us know</router-link>any questions.
        </div>
```
removing the white space after `</router-link>`

**Comment by johnsoncodehk** [comment]
Thanks for the report, this is [prettyhtml](https://github.com/Prettyhtml/prettyhtml) behavior, please open a issue there or consider contribute PR if you can.
