### ISSUE TITLE
syntax highlighting breaks when script tags export types without an empty line break

### ISSUE THREAD

**Issue by JessicaSachs** [johnsoncodehk/volar#986]
### Summary

When you export a type from a non-setup script block and do not add an empty line, the syntax highlighting breaks.

### Pics
<img width="662" alt="Screen Shot 2022-02-25 at 6 47 13 PM" src="https://user-images.githubusercontent.com/2801156/155818078-117056d7-cde8-4c28-ab13-00b771ea5b45.png">
<img width="681" alt="Screen Shot 2022-02-25 at 6 47 21 PM" src="https://user-images.githubusercontent.com/2801156/155818079-be81c05a-588f-42f1-a53b-07233c59c95e.png">

### Steps to reproduce

Export a type from an SFC (it doesn't seem to fail when exporting constants, functions, or interfaces)

**Broken Example**

```vue
<script lang="ts">
export type foo = 1
</script>

<script setup lang="ts">
console.log('some stuff')
</script>
```

**Workaround**

```vue
<script lang="ts">
export type foo = 1

</script>

<script setup lang="ts">
console.log('some stuff')
</script>
```

**Comment by JessicaSachs** [comment]
Lol it seems to be an issue in the parser in general! The code example has the same problem :P

**Comment by johnsoncodehk** [comment]
Thanks for the report :), this is embedded language syntax highlight issue, it's hard to change in volar (or maybe impossible), I personal use semicolon at line end so I can avoid it.

(Run `editor.action.inspectTMScopes` command to inspect it)
<img width="557" alt="image" src="https://user-images.githubusercontent.com/16279759/156191305-f430ebb3-df95-4d3c-a279-a8d0e2ef469e.png">

**Comment by c5n8** [comment]
I noticed this issue has been marked as complete, but there’s no reference to an upstream issue. Could you provide a link to the relevant upstream discussion or fix? This would help with tracking progress and understanding how the issue was resolved.
