### ISSUE TITLE
vue GlobalComponents cause use @types/node Blob instead of dom Blob?

### ISSUE THREAD

**Issue by exherb** [johnsoncodehk/volar#989]
No idea why @types/node got injected.

pnpm 6.32.1, monorepo

```bash
➜ npm run lint:vuetsc

> @adtalos/dashboard@0.0.0 lint:vuetsc
> vue-tsc --noEmit

src/components/dynamic_material/download.ts:39:37 - error TS2551: Property 'pipeTo' does not exist on type 'ReadableStream'. Did you mean 'pipe'?

39   await new Blob([buffer]).stream().pipeTo(writable);
                                       ~~~~~~

  ../node_modules/.pnpm/@types+node@17.0.21/node_modules/@types/node/globals.d.ts:197:9
    197         pipe<T extends WritableStream>(destination: T, options?: { end?: boolean | undefined; }): T;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'pipe' is declared here.


Found 1 error.
```

tsconfig.json

```javascript
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "lib": ["esnext", "dom"],
    "types": ["vite/client", "wicg-file-system-access", "unplugin-icons/types/vue"],
    "baseUrl": "./"
    }
  },
  "include": [
    ".eslintrc.js",
    "*.js",
    "**/*.ts",
    "**/*.vue"
  ]
}
```

../tsconfig.json

```javascript
{
    "compilerOptions": {
    "types": [],
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true
  }
}
```

**Comment by xiaoxiangmoe** [comment]
Can you provide a minimal reproduction?

**Comment by exherb** [comment]
ok, I will prepare one latter

**Comment by exherb** [comment]
> Can you provide a minimal reproduction?

The dependencies is too complicated, is there anyway or tool to determine why? Thank you.

**Comment by xiaoxiangmoe** [comment]
You can create a empty project and try to reproduce the problem by adding code which you think may cause the problem.

**Comment by exherb** [comment]
https://github.com/exherb/vue-tsc

here is the minimal reproduction, if remove dashboard/vite.config.ts, everything will ok.

**Comment by exherb** [comment]
somehow `ElAlert: typeof import('element-plus')['ElAlert']` import `@types/node`

I think vue-tsc should respect types in tsconfig.json

**Comment by xiaoxiangmoe** [comment]
This is not volar's bug

element-plus/lib/index.d.ts
`export * from 'element-plus/es/components';`

element-plus/es/components/index.d.ts
`export * from './upload';`

element-plus/lib/components/upload/index.d.ts
`/// <reference types="node" />`

You should create a issue in element-plus and tell them remove all `/// <reference types="node" />` in packages

**Comment by exherb** [comment]
ok, thanks, is there any workaround for now?

**Comment by xiaoxiangmoe** [comment]
I'm sorry, there is no workaround now.

Maybe you should use as any or something else.

**Comment by exherb** [comment]
```typescript
// NOTE: workaround for https://github.com/element-plus/element-plus/issues/6338
interface Blob {
  stream(): ReadableStream;
}

declare let Blob: {
  new (blobParts?: BlobPart[], options?: BlobPropertyBag): Blob;
};
```

workaround, if anyone enccounter this issue.
