### ISSUE TITLE
interfaces inferred from JSON files are not updated on file update

### ISSUE THREAD

**Issue by pikax** [johnsoncodehk/volar#99]
When you import a `json` file and use it or just the type, volar won't refresh the type on json changes.

Example of usage: https://pikax.me/vue-composable/composable/i18n/i18n.html#typescript

Repro: 
- open the zip 
- run `yarn`
- on the `App.vue`  try `test.` and you should see the available keys for the json
- open the `test.json` and add a new `key` 
- Go back to the `App.vue` and see if the `key` is there.
- If you do the same on main.ts, you will notice that the typescript server will actually gets the new key.

[src-vite-json.zip](https://github.com/johnsoncodehk/volar/files/6140244/src-vite-json.zip)

**Comment by johnsoncodehk** [comment]
Fixed in 0.22.13, thanks for the report!

**Comment by johnsoncodehk** [comment]
Seem not working for windows.

**Comment by johnsoncodehk** [comment]
Should be fixed in 0.22.16.
