### ISSUE TITLE
Doesn't find component methods on Vue2

### ISSUE THREAD

**Issue by douglasg14b** [johnsoncodehk/volar#991]
When trying out Voalr on a Vue2 project, I regularly get  `Cannot find name 'someFunction'` whenever anything under `methods: {}` is referenced in the template.

![image](https://user-images.githubusercontent.com/1400380/156053345-330f8270-6066-428a-be0b-1f7fb1979eee.png)

**Comment by yaegassy** [comment]
Please check the setup instructions for Vue2 here. <https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#usage>

Use `<script setup lang="ts">` or `defineComponent` is recommended.

**Comment by douglasg14b** [comment]
Gotcha, so we have to use the composition API or class-components, the options API is not supported by Volar for Vue 2 at this time?

As for the `setup` script, I thought that was only Vue 3?

**Comment by yaegassy** [comment]
If you install `@vue/composition-api` and use the `defineComponent`, you can write in the option api style. `setup` option is also available. <https://github.com/vuejs/composition-api>

```vue
<script lang="ts">
import { defineComponent } from "@vue/composition-api";

export default defineComponent({
  // setup, components, data, computed, methods and more option
});
</script>
```

**Comment by douglasg14b** [comment]
@yaegassy  gotcha!

If you don't mind, the setup step for removing the vue type declarations breaks the ability to import vue files into ts files without errors.

Adding the shim back resolves this.

Is this expected?

main.ts:

```ts
// Cannot find module './App.vue' or its corresponding type declarations.ts(2307)
import App from './App.vue'
```

App.vue:

```vue
<template>
  <router-view></router-view>
</template>
<script>
import { mapActions } from 'vuex'
export default {
  name: 'App',
  computed: {
    pageTitle () {
      return this.$route.meta.title || 'Sales'
    }
  },
  beforeMount () {
    const isTest = this.$root.$environment === 'Test'
    this.getCurrentEnvironment(isTest)
  },
  methods: {
    ...mapActions('environment', ['getCurrentEnvironment'])
  }
}
</script>
```
