### ISSUE TITLE
[Bug]: False positive type check on force binding attribute with `vue-tsc`

### ISSUE THREAD

**Issue by ahnpnl** [johnsoncodehk/volar#992]
Hi,

I ran into some false positive type check errors with my Vite + Vue tsc when using force binding attribute template syntax
<img width="561" alt="image" src="https://user-images.githubusercontent.com/27772165/156058301-656d613c-924b-4561-a4ad-1a64343bcbd0.png">

Here is the repo to reproduce the issue https://github.com/ahnpnl/vite-vue-ts

### Step to reproduce

- Check out the repo
- Install deps with `yarn`
- Run `yarn production` or `yarn ts-check`
- Observe the error like the screenshot.

**Comment by johnsoncodehk** [comment]
Hi @ahnpnl, I think template AST is broken by this syntax, is it valid in vue? Could you share document link if it have?

**Comment by ahnpnl** [comment]
Hi, I use https://vuejs.org/api/built-in-directives.html#v-bind 

I also tried the syntax like the docs related to attribute and prop force binding `.`/`^` I also ran into similar issue.
