### ISSUE TITLE
i have a problem when i use @vue/composition-api with volar

### ISSUE THREAD

**Issue by 1436085923** [johnsoncodehk/volar#993]
![image](https://user-images.githubusercontent.com/24776681/156131967-a4491a99-70df-44da-9f27-f315419bef2c.png)

**Comment by 1436085923** [comment]
I think my syntax is no problem, but volar show the error

**Comment by johnsoncodehk** [comment]
Hi @1436085923, I can't reproduce this problem, please provide a minimal reproduction.

<img width="448" alt="螢幕截圖 2022-03-01 23 08 34" src="https://user-images.githubusercontent.com/16279759/156194215-3d0c6bf7-2fc7-46f0-b09d-ea8d7ac689ff.png">

**Comment by 1436085923** [comment]
I have built a new project without replay this problem. But my project still has this problem. maybe my project has too much configure. I will check them one by one, thank you for your help

**Comment by 1436085923** [comment]
> Hi @1436085923, I can't reproduce this problem, please provide a minimal reproduction.
> 
> <img alt="螢幕截圖 2022-03-01 23 08 34" width="448" src="https://user-images.githubusercontent.com/16279759/156194215-3d0c6bf7-2fc7-46f0-b09d-ea8d7ac689ff.png">

I have built a new project without replay this problem. But my project still has this problem. maybe my project has too much configure. I will check them one by one, thank you for your help

**Comment by 1436085923** [comment]
@johnsoncodehk So which depends will volar read the local project? just like tsconfig.json..

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk So which depends will volar read the local project? just like tsconfig.json..

Sorry if i misunderstood. Volar on read your project tsconfig.json / jsconfig.json, it don't have any other depends.

**Comment by 1436085923** [comment]
![image](https://user-images.githubusercontent.com/24776681/156286687-3e8fc1b1-2f00-4fcc-969e-6115b4214d55.png)
Maybe volar cant identify "defineComponent" in my project

**Comment by johnsoncodehk** [comment]
What is the type of `bar` on below code?

```ts
const foo = defineComponent({ ... });
const bar = new foo();
export default foo;
```

**Comment by 1436085923** [comment]
![image](https://user-images.githubusercontent.com/24776681/156290063-a7b51ed6-6d1d-4f00-bf95-267351737bc8.png)
![image](https://user-images.githubusercontent.com/24776681/156290094-7aba9bc8-cd7f-4825-885a-32627cc06159.png)
`any`
@johnsoncodehk

**Comment by johnsoncodehk** [comment]
I guess some of your dependencies make `defineComponent` types broken, you need to investigate it, or I can check if provide repo case.

**Comment by 1436085923** [comment]
Thank you for your help, I'm trying to check

> I guess some of your dependencies make `defineComponent` types broken, you need to investigate it, or I can check if you provide repo case.
